import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'algo-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['big-o', 'complexity'],
    questionRu: 'Что такое Big O нотация?',
    questionEn: 'What is Big O notation?',
    answerRu: 'Big O описывает верхнюю границу роста времени или памяти алгоритма в зависимости от размера входных данных n. Игнорирует константы и младшие члены. O(1) — константное, O(log n) — логарифмическое, O(n) — линейное, O(n log n) — линейно-логарифмическое, O(n²) — квадратичное, O(2ⁿ) — экспоненциальное.',
    answerEn: 'Big O describes the upper bound on the growth of an algorithm\'s time or memory usage relative to the input size n. It ignores constants and lower-order terms. O(1) — constant, O(log n) — logarithmic, O(n) — linear, O(n log n) — linearithmic, O(n²) — quadratic, O(2ⁿ) — exponential.',
  },
  {
    id: 'algo-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['array', 'complexity'],
    questionRu: 'Какова сложность основных операций с массивом?',
    questionEn: 'What is the complexity of basic array operations?',
    answerRu: 'Доступ по индексу: O(1). Поиск элемента: O(n). Вставка/удаление в конец (push/pop): O(1) амортизированно. Вставка/удаление в начало (unshift/shift): O(n) — сдвиг всех элементов. Вставка в середину: O(n). Для частых вставок в начало лучше LinkedList или Deque.',
    answerEn: 'Index access: O(1). Element search: O(n). Insert/delete at the end (push/pop): O(1) amortized. Insert/delete at the beginning (unshift/shift): O(n) — all elements must be shifted. Insert in the middle: O(n). For frequent insertions at the front, prefer a LinkedList or Deque.',
  },
  {
    id: 'algo-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['hash-table', 'map', 'complexity'],
    questionRu: 'Какова сложность операций с хэш-таблицей (объектом/Map)?',
    questionEn: 'What is the complexity of hash table (Object/Map) operations?',
    answerRu: 'Вставка, поиск, удаление по ключу: O(1) в среднем. O(n) в худшем случае при коллизиях. Перебор всех элементов: O(n). JavaScript Object и Map используют хэш-таблицу. Map лучше для частых добавлений/удалений и нестроковых ключей. Именно поэтому поиск в объекте быстрее чем в массиве.',
    answerEn: 'Insert, lookup, delete by key: O(1) on average. O(n) in the worst case due to collisions. Iterating all entries: O(n). JavaScript Object and Map both use a hash table under the hood. Map is preferable for frequent additions/deletions and non-string keys. This is why lookups in an object are faster than searching an array.',
  },
  {
    id: 'algo-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['space-complexity', 'complexity'],
    questionRu: 'Что такое пространственная сложность?',
    questionEn: 'What is space complexity?',
    answerRu: 'Пространственная сложность — сколько дополнительной памяти использует алгоритм относительно размера входных данных. O(1) — константная (in-place). O(n) — линейная (копия массива). O(n²) — квадратичная (матрица n×n). При рекурсии учитывается стек вызовов: рекурсия глубиной n — O(n) памяти.',
    answerEn: 'Space complexity measures how much additional memory an algorithm uses relative to the input size. O(1) — constant (in-place). O(n) — linear (array copy). O(n²) — quadratic (n×n matrix). For recursion, the call stack counts: a recursion of depth n uses O(n) memory.',
  },
  {
    id: 'algo-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['big-o', 'complexity'],
    questionRu: 'В чём разница между O(n log n) и O(n²) на практике?',
    questionEn: 'What is the practical difference between O(n log n) and O(n²)?',
    answerRu: 'При n=1000: O(n log n) ≈ 10000 операций, O(n²) = 1000000. Разница в 100 раз. При n=10000: O(n log n) ≈ 130000, O(n²) = 100000000. Разница в 770 раз. O(n²) алгоритмы (пузырьковая сортировка) неприемлемы для больших данных. O(n log n) — оптимум для сортировки основанной на сравнении.',
    answerEn: 'At n=1000: O(n log n) ≈ 10,000 operations vs O(n²) = 1,000,000 — a 100× difference. At n=10,000: O(n log n) ≈ 130,000 vs O(n²) = 100,000,000 — a 770× difference. O(n²) algorithms (e.g. bubble sort) are unacceptable for large inputs. O(n log n) is the theoretical optimum for comparison-based sorting.',
  },
  {
    id: 'algo-006',
    difficulty: 'EASY',
    order: 6,
    tags: ['array', 'hash-table', 'two-sum'],
    questionRu: 'Как найти два числа в массиве дающих заданную сумму (Two Sum)?',
    questionEn: 'How do you find two numbers in an array that add up to a target sum (Two Sum)?',
    answerRu: 'Наивно: два цикла O(n²). Оптимально через хэш-таблицу O(n): итерировать массив, для каждого элемента x проверять есть ли (target - x) в Map. Если нет — добавить x в Map. Один проход, O(n) времени и памяти. Классическая задача демонстрирующая трейдофф время/память.',
    answerEn: 'Naive approach: two nested loops, O(n²). Optimal approach using a hash table, O(n): iterate the array, for each element x check whether (target - x) is already in the Map. If not, add x to the Map. Single pass, O(n) time and space. A classic problem illustrating the time/space tradeoff.',
  },
  {
    id: 'algo-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['two-pointers', 'array'],
    questionRu: 'Что такое техника двух указателей?',
    questionEn: 'What is the two-pointer technique?',
    answerRu: 'Два указателя движутся по массиву (с разных концов или в одном направлении) для решения задач за O(n) вместо O(n²). Примеры: поиск пары с суммой в отсортированном массиве (left и right с краёв), удаление дубликатов in-place (slow и fast pointer), разворот строки. Требует отсортированного массива или специфичной структуры.',
    answerEn: 'Two pointers move through an array (from opposite ends or in the same direction) to solve problems in O(n) instead of O(n²). Examples: finding a pair with a target sum in a sorted array (left and right pointers from both ends), removing duplicates in-place (slow and fast pointers), reversing a string. Usually requires a sorted array or a specific data structure.',
  },
  {
    id: 'algo-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['sliding-window', 'array', 'string'],
    questionRu: 'Что такое техника скользящего окна (sliding window)?',
    questionEn: 'What is the sliding window technique?',
    answerRu: 'Sliding window — подмассив/подстрока фиксированного или переменного размера скользит по данным. Избегает вложенных циклов. Фиксированное окно: сумма k элементов — сдвигаем, добавляем новый, убираем старый O(n). Переменное: longest substring without repeating characters — расширяем/сужаем окно через two pointers.',
    answerEn: 'Sliding window — a subarray or substring of fixed or variable size slides over the data, avoiding nested loops. Fixed window: sum of k elements — shift the window by adding the new element and removing the old one, O(n). Variable window: longest substring without repeating characters — expand or shrink the window using two pointers.',
  },
  {
    id: 'algo-009',
    difficulty: 'EASY',
    order: 9,
    tags: ['two-pointers', 'string', 'array'],
    questionRu: 'Как развернуть строку или массив in-place?',
    questionEn: 'How do you reverse a string or array in-place?',
    answerRu: "Two pointers: left=0, right=n-1. Пока left < right: swap(arr[left], arr[right]), left++, right--. O(n) время, O(1) память. Строки в JS иммутабельны — нужно split('') → reverse array → join('') или через spread: [...str].reverse().join(''). In-place разворот классический вопрос на понимание работы с памятью.",
    answerEn: "Two pointers: left=0, right=n-1. While left < right: swap(arr[left], arr[right]), left++, right--. O(n) time, O(1) space. Strings in JS are immutable — you need split('') → reverse array → join('') or via spread: [...str].reverse().join(''). In-place reversal is a classic question testing understanding of memory usage.",
  },
  {
    id: 'algo-010',
    difficulty: 'EASY',
    order: 10,
    tags: ['two-pointers', 'string', 'palindrome'],
    questionRu: 'Как проверить является ли строка палиндромом?',
    questionEn: 'How do you check if a string is a palindrome?',
    answerRu: "Two pointers: left=0, right=n-1, сравнивать символы пока left < right. O(n) время, O(1) память. Альтернатива: str === str.split('').reverse().join('') — O(n) но O(n) памяти. Для игнорирования регистра и не-буквенных символов: предобработка строки через regex.",
    answerEn: "Two pointers: left=0, right=n-1, compare characters while left < right. O(n) time, O(1) space. Alternative: str === str.split('').reverse().join('') — O(n) but uses O(n) memory. To ignore case and non-alphanumeric characters, preprocess the string with a regex.",
  },
  {
    id: 'algo-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['array', 'dynamic-programming', 'kadane'],
    questionRu: 'Как найти максимальную сумму подмассива (алгоритм Кадане)?',
    questionEn: 'How do you find the maximum subarray sum (Kadane\'s algorithm)?',
    answerRu: 'Алгоритм Кадане: currentSum = Math.max(num, currentSum + num), maxSum = Math.max(maxSum, currentSum). O(n) время, O(1) память. Ключевая идея: если текущая сумма стала отрицательной — начать заново с текущего элемента. Классика динамического программирования с оптимизацией до одного прохода.',
    answerEn: 'Kadane\'s algorithm: currentSum = Math.max(num, currentSum + num), maxSum = Math.max(maxSum, currentSum). O(n) time, O(1) space. Key idea: if the running sum becomes negative, restart from the current element. A classic dynamic programming problem reduced to a single pass.',
  },
  {
    id: 'algo-012',
    difficulty: 'EASY',
    order: 12,
    tags: ['string', 'hash-table', 'anagram'],
    questionRu: 'Что такое анаграмма и как проверить?',
    questionEn: 'What is an anagram and how do you check for one?',
    answerRu: 'Анаграмма — строки из одних и тех же символов в разном порядке. Метод 1: отсортировать обе строки и сравнить — O(n log n). Метод 2: подсчёт символов через Map/объект — O(n) время, O(1) память (26 букв алфавита). Метод 2 оптимальнее. Предварительно проверить длины строк.',
    answerEn: 'An anagram consists of the same characters in a different order. Method 1: sort both strings and compare — O(n log n). Method 2: count characters using a Map/object — O(n) time, O(1) space (26 alphabet letters). Method 2 is more efficient. Always check string lengths first.',
  },
  {
    id: 'algo-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['array', 'hash-table', 'duplicates'],
    questionRu: 'Как найти все дубликаты в массиве?',
    questionEn: 'How do you find all duplicates in an array?',
    answerRu: 'Через Set: итерировать, если элемент уже в seen — дубликат. O(n) время и память. Через Map с подсчётом: найти элементы с count > 1. Для массива из чисел 1..n без доп. памяти: помечать посещённые через отрицательный знак по индексу — O(n) время, O(1) память.',
    answerEn: 'Using a Set: iterate the array; if an element is already in the seen set, it\'s a duplicate. O(n) time and space. Using a Map with counts: find elements where count > 1. For an array of numbers 1..n with no extra memory: mark visited indices by negating the value at that index — O(n) time, O(1) space.',
  },
  {
    id: 'algo-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['linked-list', 'data-structures'],
    questionRu: 'Что такое связный список (linked list) и когда использовать?',
    questionEn: 'What is a linked list and when should you use one?',
    answerRu: 'Linked list — узлы с данными и ссылкой на следующий (и предыдущий для doubly). Вставка/удаление в начало: O(1). Доступ по индексу: O(n). В JS нет нативного linked list — используют массив или реализуют вручную. Преимущество перед массивом: O(1) вставка/удаление если есть ссылка на узел. Для очереди, LRU кеша.',
    answerEn: 'A linked list consists of nodes, each holding data and a reference to the next node (and previous for a doubly linked list). Insert/delete at the head: O(1). Index access: O(n). JS has no native linked list — use an array or implement one manually. Advantage over arrays: O(1) insert/delete given a reference to the node. Useful for queues and LRU caches.',
  },
  {
    id: 'algo-015',
    difficulty: 'EASY',
    order: 15,
    tags: ['stack', 'queue', 'data-structures'],
    questionRu: 'Что такое стек и очередь, как реализовать в JS?',
    questionEn: 'What are a stack and a queue, and how do you implement them in JS?',
    answerRu: 'Стек (LIFO): push/pop с конца массива — оба O(1). Применение: история браузера, undo/redo, обход DFS, скобочные задачи. Очередь (FIFO): enqueue через push, dequeue через shift — shift O(n). Эффективная очередь: двусвязный список или circular buffer. Применение: BFS, Task Queue, обработка событий.',
    answerEn: 'Stack (LIFO): push/pop from the end of an array — both O(1). Uses: browser history, undo/redo, DFS traversal, bracket matching. Queue (FIFO): enqueue via push, dequeue via shift — shift is O(n). Efficient queue: doubly linked list or circular buffer. Uses: BFS, task queue, event processing.',
  },
  {
    id: 'algo-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['bst', 'tree', 'data-structures'],
    questionRu: 'Что такое бинарное дерево поиска (BST)?',
    questionEn: 'What is a Binary Search Tree (BST)?',
    answerRu: 'BST: левый потомок < узел < правый потомок. Поиск, вставка, удаление: O(log n) для сбалансированного, O(n) для вырожденного (отсортированный вход). Обходы: inorder (LNR) даёт отсортированную последовательность, preorder (NLR), postorder (LRN). Применение: упорядоченные данные, диапазонные запросы.',
    answerEn: 'BST: left child < node < right child. Search, insert, delete: O(log n) for a balanced tree, O(n) for a degenerate tree (sorted input). Traversals: inorder (LNR) yields a sorted sequence, preorder (NLR), postorder (LRN). Use cases: ordered data, range queries.',
  },
  {
    id: 'algo-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['hash-table', 'data-structures', 'collisions'],
    questionRu: 'Что такое хэш-таблица и как обрабатываются коллизии?',
    questionEn: 'What is a hash table and how are collisions handled?',
    answerRu: 'Хэш-таблица: хэш-функция отображает ключ в индекс массива. Коллизия — два ключа дают один индекс. Методы разрешения: chaining (цепочки — список в ячейке), open addressing (линейное пробирование — следующая свободная ячейка). JS Object и Map используют chaining. Хорошая хэш-функция минимизирует коллизии.',
    answerEn: 'A hash table uses a hash function to map a key to an array index. A collision occurs when two keys produce the same index. Resolution methods: chaining (a linked list at each bucket) and open addressing (linear probing — find the next free slot). JS Object and Map use chaining internally. A good hash function minimizes collisions.',
  },
  {
    id: 'algo-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['graph', 'data-structures'],
    questionRu: 'Что такое граф и способы его представления?',
    questionEn: 'What is a graph and how can it be represented?',
    answerRu: 'Граф: вершины (nodes) и рёбра (edges). Направленный/ненаправленный, взвешенный. Представления: матрица смежности — O(V²) память, O(1) проверка ребра; список смежности — O(V+E) память, эффективен для разреженных графов. В JS: Map или объект где ключ — вершина, значение — массив соседей.',
    answerEn: 'A graph consists of vertices (nodes) and edges. It can be directed/undirected and weighted. Representations: adjacency matrix — O(V²) space, O(1) edge lookup; adjacency list — O(V+E) space, efficient for sparse graphs. In JS: use a Map or plain object where the key is a vertex and the value is an array of neighbors.',
  },
  {
    id: 'algo-019',
    difficulty: 'HARD',
    order: 19,
    tags: ['heap', 'priority-queue', 'data-structures'],
    questionRu: 'Что такое куча (heap) и для чего используется?',
    questionEn: 'What is a heap and what is it used for?',
    answerRu: 'Heap — полное бинарное дерево где родитель >= потомков (max-heap) или <= (min-heap). Вставка и извлечение max/min: O(log n). Получение max/min: O(1). Реализуется массивом. Применение: Priority Queue, сортировка кучей (heapsort), топ-K элементов. В JS нет нативной кучи — реализуют вручную или через библиотеку.',
    answerEn: 'A heap is a complete binary tree where each parent is >= its children (max-heap) or <= (min-heap). Insert and extract max/min: O(log n). Peek max/min: O(1). Implemented as an array. Uses: Priority Queue, heapsort, top-K elements. JS has no native heap — implement one manually or use a library.',
  },
  {
    id: 'algo-020',
    difficulty: 'MEDIUM',
    order: 20,
    tags: ['sorting', 'merge-sort', 'quick-sort'],
    questionRu: 'Какие алгоритмы сортировки нужно знать фронтендеру?',
    questionEn: 'Which sorting algorithms should a frontend developer know?',
    answerRu: 'Обязательно: merge sort O(n log n) стабильный, quick sort O(n log n) средний/O(n²) худший. Знать принцип: bubble O(n²), insertion O(n²) — для малых данных. Array.sort() в V8: TimSort (merge+insertion) — O(n log n), стабильный с ES2019. Counting/radix sort для целых чисел O(n+k).',
    answerEn: 'Must know: merge sort O(n log n) stable, quick sort O(n log n) average / O(n²) worst case. Understand the principles of: bubble sort O(n²), insertion sort O(n²) — suitable for small data. Array.sort() in V8 uses TimSort (merge + insertion) — O(n log n), stable since ES2019. Counting/radix sort for integers, O(n+k).',
  },
  {
    id: 'algo-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['binary-search', 'search'],
    questionRu: 'Как работает бинарный поиск?',
    questionEn: 'How does binary search work?',
    answerRu: 'Бинарный поиск работает на отсортированном массиве: сравнить с серединой, если меньше — искать в левой половине, больше — в правой. O(log n). Реализация: left=0, right=n-1, mid=Math.floor((left+right)/2). Применение: поиск в отсортированном массиве, поиск границы (первый/последний элемент удовлетворяющий условию).',
    answerEn: 'Binary search operates on a sorted array: compare the target with the middle element; if smaller, search the left half; if larger, search the right half. O(log n). Implementation: left=0, right=n-1, mid=Math.floor((left+right)/2). Use cases: search in a sorted array, boundary search (first/last element satisfying a condition).',
  },
  {
    id: 'algo-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['quick-sort', 'sorting'],
    questionRu: 'Как работает быстрая сортировка (quicksort)?',
    questionEn: 'How does quicksort work?',
    answerRu: 'Quicksort: выбрать pivot, разделить массив на меньшие и большие pivot, рекурсивно сортировать части. Divide and conquer. O(n log n) средний, O(n²) худший (уже отсортированный массив с плохим pivot). In-place, O(log n) памяти на стек. Случайный или median-of-three pivot для улучшения худшего случая.',
    answerEn: 'Quicksort: choose a pivot, partition the array into elements smaller and larger than the pivot, then recursively sort each part. Divide and conquer. O(n log n) average, O(n²) worst case (already sorted array with a bad pivot). In-place, O(log n) stack space. Use a random or median-of-three pivot to mitigate the worst case.',
  },
  {
    id: 'algo-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['merge-sort', 'sorting'],
    questionRu: 'Как работает сортировка слиянием (merge sort)?',
    questionEn: 'How does merge sort work?',
    answerRu: 'Merge sort: разделить массив пополам рекурсивно до одного элемента, затем слить отсортированные половины. O(n log n) всегда — нет худшего случая. Стабильный. O(n) дополнительной памяти. Предпочтителен для связных списков и внешней сортировки. Основа TimSort используемого в V8.',
    answerEn: 'Merge sort: recursively split the array in half down to single elements, then merge the sorted halves back together. O(n log n) always — no worst case. Stable. O(n) extra memory. Preferred for linked lists and external sorting. Forms the basis of TimSort used in V8.',
  },
  {
    id: 'algo-024',
    difficulty: 'MEDIUM',
    order: 24,
    tags: ['bfs', 'dfs', 'graph', 'tree'],
    questionRu: 'Что такое BFS и DFS и когда применять?',
    questionEn: 'What are BFS and DFS and when should each be used?',
    answerRu: 'BFS (поиск в ширину): обходит по уровням через очередь. Находит кратчайший путь в невзвешенном графе. O(V+E). DFS (поиск в глубину): идёт вглубь через стек/рекурсию. Для: обхода дерева, топологической сортировки, поиска компонент связности, решения лабиринтов. BFS для кратчайшего пути, DFS для исчерпывающего поиска.',
    answerEn: 'BFS (breadth-first search): traverses level by level using a queue. Finds the shortest path in an unweighted graph. O(V+E). DFS (depth-first search): goes deep using a stack or recursion. Used for: tree traversal, topological sort, finding connected components, solving mazes. Use BFS for shortest paths, DFS for exhaustive search.',
  },
  {
    id: 'algo-025',
    difficulty: 'MEDIUM',
    order: 25,
    tags: ['heap', 'sorting', 'top-k'],
    questionRu: 'Как найти K-й наибольший элемент?',
    questionEn: 'How do you find the K-th largest element?',
    answerRu: 'Метод 1: отсортировать O(n log n), взять n-k индекс. Метод 2: min-heap размером K — итерировать, поддерживать кучу размером K, в конце вершина кучи — ответ. O(n log k). Метод 3: QuickSelect — как quicksort но рекурсия только в нужную сторону. O(n) средний. Для потоковых данных — min-heap.',
    answerEn: 'Method 1: sort the array O(n log n) and take index n-k. Method 2: min-heap of size K — iterate the array maintaining a heap of size K; the top of the heap is the answer. O(n log k). Method 3: QuickSelect — like quicksort but recurse only into the relevant partition. O(n) average. For streaming data, use a min-heap.',
  },
  {
    id: 'algo-026',
    difficulty: 'HARD',
    order: 26,
    tags: ['graph', 'topological-sort', 'dag'],
    questionRu: 'Что такое топологическая сортировка?',
    questionEn: 'What is topological sort?',
    answerRu: 'Топологическая сортировка — линейный порядок вершин направленного ациклического графа (DAG) где каждая вершина предшествует всем вершинам в которые ведут её рёбра. Алгоритм Кана: подсчёт входящих рёбер, BFS от вершин без входящих. DFS с postorder. Применение: порядок зависимостей, сборка проекта.',
    answerEn: 'Topological sort produces a linear ordering of the vertices of a directed acyclic graph (DAG) such that each vertex comes before all vertices it has edges pointing to. Kahn\'s algorithm: count in-degrees, then BFS from zero-in-degree vertices. Alternatively, DFS with postorder traversal. Use cases: dependency resolution, build order.',
  },
  {
    id: 'algo-027',
    difficulty: 'MEDIUM',
    order: 27,
    tags: ['recursion', 'stack'],
    questionRu: 'Что такое рекурсия и хвостовая рекурсия?',
    questionEn: 'What is recursion and tail recursion?',
    answerRu: 'Рекурсия — функция вызывает себя с меньшим входом. Базовый случай останавливает рекурсию. Каждый вызов занимает место в стеке — O(n) памяти для глубины n. Хвостовая рекурсия: рекурсивный вызов последний в функции — компилятор может оптимизировать в цикл. JS не гарантирует TCO (tail call optimization).',
    answerEn: 'Recursion is when a function calls itself with a smaller input. The base case stops the recursion. Each call occupies stack space — O(n) memory for depth n. Tail recursion: the recursive call is the last operation in the function, allowing the compiler to optimize it into a loop. JS does not guarantee TCO (tail call optimization).',
  },
  {
    id: 'algo-028',
    difficulty: 'MEDIUM',
    order: 28,
    tags: ['memoization', 'dynamic-programming', 'recursion'],
    questionRu: 'Что такое мемоизация в контексте рекурсии?',
    questionEn: 'What is memoization in the context of recursion?',
    answerRu: 'Мемоизация — кеширование результатов рекурсивных вызовов для избежания повторных вычислений. Fibonacci без мемоизации: O(2ⁿ). С мемоизацией: O(n). Реализация: Map или объект где ключ — аргументы. Первый шаг динамического программирования top-down подход. Превращает экспоненциальные алгоритмы в полиномиальные.',
    answerEn: 'Memoization is caching the results of recursive calls to avoid redundant computation. Fibonacci without memoization: O(2ⁿ). With memoization: O(n). Implementation: a Map or plain object keyed by the arguments. It is the first step toward dynamic programming (top-down approach) and can turn exponential algorithms into polynomial ones.',
  },
  {
    id: 'algo-029',
    difficulty: 'HARD',
    order: 29,
    tags: ['dynamic-programming'],
    questionRu: 'Что такое динамическое программирование?',
    questionEn: 'What is dynamic programming?',
    answerRu: 'ДП — разбивка задачи на перекрывающиеся подзадачи, сохранение результатов для переиспользования. Top-down (мемоизация): рекурсия + кеш. Bottom-up (табуляция): итеративно заполнять таблицу от малых подзадач к большим. Признаки ДП задачи: оптимальная подструктура и перекрывающиеся подзадачи.',
    answerEn: 'Dynamic programming (DP) breaks a problem into overlapping subproblems and stores results for reuse. Top-down (memoization): recursion + cache. Bottom-up (tabulation): iteratively fill a table from smaller subproblems to larger ones. Indicators of a DP problem: optimal substructure and overlapping subproblems.',
  },
  {
    id: 'algo-030',
    difficulty: 'EASY',
    order: 30,
    tags: ['dynamic-programming', 'fibonacci'],
    questionRu: 'Как решить задачу о числах Фибоначчи оптимально?',
    questionEn: 'How do you solve the Fibonacci problem optimally?',
    answerRu: 'Наивная рекурсия: O(2ⁿ). Мемоизация: O(n) время, O(n) память. Bottom-up ДП: массив dp[i] = dp[i-1] + dp[i-2], O(n) время, O(n) память. Оптимально: хранить только два предыдущих числа — O(n) время, O(1) память. Матричное возведение в степень: O(log n) время для очень больших n.',
    answerEn: 'Naive recursion: O(2ⁿ). Memoization: O(n) time, O(n) space. Bottom-up DP: array dp[i] = dp[i-1] + dp[i-2], O(n) time, O(n) space. Optimal: keep only the last two numbers — O(n) time, O(1) space. Matrix exponentiation: O(log n) time for very large n.',
  },
  {
    id: 'algo-031',
    difficulty: 'HARD',
    order: 31,
    tags: ['dynamic-programming', 'knapsack'],
    questionRu: 'Что такое задача о рюкзаке (knapsack)?',
    questionEn: 'What is the knapsack problem?',
    answerRu: '0/1 Knapsack: N предметов с весом и ценностью, рюкзак вместимостью W. Максимизировать ценность не превышая вместимость. Каждый предмет берём или нет. ДП таблица dp[i][w]: max ценность для i предметов и вместимости w. O(n*W) время и память. Паттерн для задач выбора с ограничениями.',
    answerEn: '0/1 Knapsack: given N items with weights and values and a knapsack with capacity W, maximize the total value without exceeding the capacity. Each item is either taken or not. DP table dp[i][w]: max value for i items and capacity w. O(n*W) time and space. A foundational pattern for constrained selection problems.',
  },
  {
    id: 'algo-032',
    difficulty: 'MEDIUM',
    order: 32,
    tags: ['tree', 'dfs', 'bfs', 'iteration'],
    questionRu: 'Как обойти дерево без рекурсии?',
    questionEn: 'How do you traverse a tree without recursion?',
    answerRu: 'DFS итеративно через явный стек: push root, while stack не пуст — pop, обработать, push правый затем левый потомок (для preorder). BFS через очередь: enqueue root, while queue не пуст — dequeue, обработать, enqueue потомков. Итеративный подход избегает stack overflow для глубоких деревьев.',
    answerEn: 'Iterative DFS using an explicit stack: push root, then while the stack is non-empty — pop, process, push right then left child (for preorder). BFS using a queue: enqueue root, then while the queue is non-empty — dequeue, process, enqueue children. The iterative approach avoids stack overflow on deep trees.',
  },
  {
    id: 'algo-033',
    difficulty: 'EASY',
    order: 33,
    tags: ['stack', 'string', 'parentheses'],
    questionRu: 'Что такое задача о скобках (valid parentheses)?',
    questionEn: 'What is the valid parentheses problem?',
    answerRu: 'Проверить правильность расстановки скобок: стек — при открывающей скобке push, при закрывающей — pop и проверить соответствие. В конце стек должен быть пуст. O(n) время, O(n) память. Расширение: generate all valid parentheses — backtracking. Классическая задача на понимание стека.',
    answerEn: 'Check whether a string of brackets is valid: use a stack — push on an opening bracket, pop on a closing bracket and verify it matches. At the end the stack must be empty. O(n) time, O(n) space. Extension: generate all valid parentheses combinations — backtracking. A classic problem for understanding stacks.',
  },
];
