import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'algo-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['big-o', 'complexity'],
    questionRu: 'Что такое Big O нотация?',
    questionEn: 'What is Big O notation?',
    answerRu: '**Big O** описывает верхнюю границу роста времени или памяти алгоритма в зависимости от размера входных данных `n`. Игнорирует константы и младшие члены.\n\n- `O(1)` — константное\n- `O(log n)` — логарифмическое\n- `O(n)` — линейное\n- `O(n log n)` — линейно-логарифмическое\n- `O(n²)` — квадратичное\n- `O(2ⁿ)` — экспоненциальное',
    answerEn: '**Big O** describes the upper bound on the growth of an algorithm\'s time or memory usage relative to the input size `n`. It ignores constants and lower-order terms.\n\n- `O(1)` — constant\n- `O(log n)` — logarithmic\n- `O(n)` — linear\n- `O(n log n)` — linearithmic\n- `O(n²)` — quadratic\n- `O(2ⁿ)` — exponential',
  },
  {
    id: 'algo-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['array', 'complexity'],
    questionRu: 'Какова сложность основных операций с массивом?',
    questionEn: 'What is the complexity of basic array operations?',
    answerRu: '- Доступ по индексу: `O(1)`\n- Поиск элемента: `O(n)`\n- Вставка/удаление в конец (`push`/`pop`): `O(1)` амортизированно\n- Вставка/удаление в начало (`unshift`/`shift`): `O(n)` — сдвиг всех элементов\n- Вставка в середину: `O(n)`\n\nДля частых вставок в начало лучше использовать **LinkedList** или **Deque**.',
    answerEn: '- Index access: `O(1)`\n- Element search: `O(n)`\n- Insert/delete at the end (`push`/`pop`): `O(1)` amortized\n- Insert/delete at the beginning (`unshift`/`shift`): `O(n)` — all elements must be shifted\n- Insert in the middle: `O(n)`\n\nFor frequent insertions at the front, prefer a **LinkedList** or **Deque**.',
  },
  {
    id: 'algo-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['hash-table', 'map', 'complexity'],
    questionRu: 'Какова сложность операций с хэш-таблицей (объектом/Map)?',
    questionEn: 'What is the complexity of hash table (Object/Map) operations?',
    answerRu: '- Вставка, поиск, удаление по ключу: `O(1)` в среднем\n- `O(n)` в худшем случае при коллизиях\n- Перебор всех элементов: `O(n)`\n\n**JavaScript** `Object` и `Map` используют хэш-таблицу. `Map` лучше для частых добавлений/удалений и нестроковых ключей. Именно поэтому поиск в объекте быстрее, чем в массиве.',
    answerEn: '- Insert, lookup, delete by key: `O(1)` on average\n- `O(n)` in the worst case due to collisions\n- Iterating all entries: `O(n)`\n\n**JavaScript** `Object` and `Map` both use a hash table under the hood. `Map` is preferable for frequent additions/deletions and non-string keys. This is why lookups in an object are faster than searching an array.',
  },
  {
    id: 'algo-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['space-complexity', 'complexity'],
    questionRu: 'Что такое пространственная сложность?',
    questionEn: 'What is space complexity?',
    answerRu: '**Пространственная сложность** — сколько дополнительной памяти использует алгоритм относительно размера входных данных.\n\n- `O(1)` — константная (in-place)\n- `O(n)` — линейная (копия массива)\n- `O(n²)` — квадратичная (матрица n×n)\n\nПри **рекурсии** учитывается стек вызовов: рекурсия глубиной `n` — `O(n)` памяти.',
    answerEn: '**Space complexity** measures how much additional memory an algorithm uses relative to the input size.\n\n- `O(1)` — constant (in-place)\n- `O(n)` — linear (array copy)\n- `O(n²)` — quadratic (n×n matrix)\n\nFor **recursion**, the call stack counts: a recursion of depth `n` uses `O(n)` memory.',
  },
  {
    id: 'algo-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['big-o', 'complexity'],
    questionRu: 'В чём разница между O(n log n) и O(n²) на практике?',
    questionEn: 'What is the practical difference between O(n log n) and O(n²)?',
    answerRu: '- При `n=1000`: `O(n log n)` ≈ 10 000 операций, `O(n²)` = 1 000 000 — разница в **100 раз**\n- При `n=10000`: `O(n log n)` ≈ 130 000, `O(n²)` = 100 000 000 — разница в **770 раз**\n\n`O(n²)` алгоритмы (например, **пузырьковая сортировка**) неприемлемы для больших данных. `O(n log n)` — теоретический оптимум для сортировки, основанной на сравнении.',
    answerEn: '- At `n=1000`: `O(n log n)` ≈ 10,000 operations vs `O(n²)` = 1,000,000 — a **100× difference**\n- At `n=10,000`: `O(n log n)` ≈ 130,000 vs `O(n²)` = 100,000,000 — a **770× difference**\n\n`O(n²)` algorithms (e.g. **bubble sort**) are unacceptable for large inputs. `O(n log n)` is the theoretical optimum for comparison-based sorting.',
  },
  {
    id: 'algo-006',
    difficulty: 'EASY',
    order: 6,
    tags: ['array', 'hash-table', 'two-sum'],
    questionRu: 'Как найти два числа в массиве дающих заданную сумму (Two Sum)?',
    questionEn: 'How do you find two numbers in an array that add up to a target sum (Two Sum)?',
    answerRu: '**Наивно:** два цикла — `O(n²)`.\n\n**Оптимально** через хэш-таблицу — `O(n)`:\n- итерировать массив\n- для каждого элемента `x` проверять, есть ли `(target - x)` в `Map`\n- если нет — добавить `x` в `Map`\n\nОдин проход, `O(n)` времени и памяти. Классическая задача, демонстрирующая **трейдофф время/память**.',
    answerEn: '**Naive approach:** two nested loops — `O(n²)`.\n\n**Optimal approach** using a hash table — `O(n)`:\n- iterate the array\n- for each element `x` check whether `(target - x)` is already in the `Map`\n- if not, add `x` to the `Map`\n\nSingle pass, `O(n)` time and space. A classic problem illustrating the **time/space tradeoff**.',
  },
  {
    id: 'algo-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['two-pointers', 'array'],
    questionRu: 'Что такое техника двух указателей?',
    questionEn: 'What is the two-pointer technique?',
    answerRu: '**Два указателя** движутся по массиву (с разных концов или в одном направлении) для решения задач за `O(n)` вместо `O(n²)`.\n\nПримеры:\n- поиск пары с суммой в отсортированном массиве (`left` и `right` с краёв)\n- удаление дубликатов in-place (`slow` и `fast` pointer)\n- разворот строки\n\nТребует отсортированного массива или специфичной структуры.',
    answerEn: '**Two pointers** move through an array (from opposite ends or in the same direction) to solve problems in `O(n)` instead of `O(n²)`.\n\nExamples:\n- finding a pair with a target sum in a sorted array (`left` and `right` pointers from both ends)\n- removing duplicates in-place (`slow` and `fast` pointers)\n- reversing a string\n\nUsually requires a sorted array or a specific data structure.',
  },
  {
    id: 'algo-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['sliding-window', 'array', 'string'],
    questionRu: 'Что такое техника скользящего окна (sliding window)?',
    questionEn: 'What is the sliding window technique?',
    answerRu: '**Sliding window** — подмассив/подстрока фиксированного или переменного размера скользит по данным, избегая вложенных циклов.\n\n- **Фиксированное окно:** сумма `k` элементов — сдвигаем, добавляем новый, убираем старый — `O(n)`\n- **Переменное окно:** longest substring without repeating characters — расширяем/сужаем окно через **two pointers**',
    answerEn: '**Sliding window** — a subarray or substring of fixed or variable size slides over the data, avoiding nested loops.\n\n- **Fixed window:** sum of `k` elements — shift the window by adding the new element and removing the old one — `O(n)`\n- **Variable window:** longest substring without repeating characters — expand or shrink the window using **two pointers**',
  },
  {
    id: 'algo-009',
    difficulty: 'EASY',
    order: 9,
    tags: ['two-pointers', 'string', 'array'],
    questionRu: 'Как развернуть строку или массив in-place?',
    questionEn: 'How do you reverse a string or array in-place?',
    answerRu: "**Two pointers:** `left=0`, `right=n-1`. Пока `left < right`: `swap(arr[left], arr[right])`, `left++`, `right--`. `O(n)` время, `O(1)` память.\n\nСтроки в JS **иммутабельны** — нужно `split('') → reverse array → join('')` или через spread: `[...str].reverse().join('')`.\n\nIn-place разворот — классический вопрос на понимание работы с памятью.",
    answerEn: "**Two pointers:** `left=0`, `right=n-1`. While `left < right`: `swap(arr[left], arr[right])`, `left++`, `right--`. `O(n)` time, `O(1)` space.\n\nStrings in JS are **immutable** — you need `split('') → reverse array → join('')` or via spread: `[...str].reverse().join('')`.\n\nIn-place reversal is a classic question testing understanding of memory usage.",
  },
  {
    id: 'algo-010',
    difficulty: 'EASY',
    order: 10,
    tags: ['two-pointers', 'string', 'palindrome'],
    questionRu: 'Как проверить является ли строка палиндромом?',
    questionEn: 'How do you check if a string is a palindrome?',
    answerRu: "**Two pointers:** `left=0`, `right=n-1`, сравнивать символы пока `left < right`. `O(n)` время, `O(1)` память.\n\nАльтернатива: `str === str.split('').reverse().join('')` — `O(n)`, но `O(n)` памяти.\n\nДля игнорирования регистра и не-буквенных символов — предобработка строки через **regex**.",
    answerEn: "**Two pointers:** `left=0`, `right=n-1`, compare characters while `left < right`. `O(n)` time, `O(1)` space.\n\nAlternative: `str === str.split('').reverse().join('')` — `O(n)` but uses `O(n)` memory.\n\nTo ignore case and non-alphanumeric characters, preprocess the string with a **regex**.",
  },
  {
    id: 'algo-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['array', 'dynamic-programming', 'kadane'],
    questionRu: 'Как найти максимальную сумму подмассива (алгоритм Кадане)?',
    questionEn: 'How do you find the maximum subarray sum (Kadane\'s algorithm)?',
    answerRu: '**Алгоритм Кадане:**\n\n```\ncurrentSum = Math.max(num, currentSum + num)\nmaxSum = Math.max(maxSum, currentSum)\n```\n\n`O(n)` время, `O(1)` память.\n\n**Ключевая идея:** если текущая сумма стала отрицательной — начать заново с текущего элемента. Классика **динамического программирования** с оптимизацией до одного прохода.',
    answerEn: '**Kadane\'s algorithm:**\n\n```\ncurrentSum = Math.max(num, currentSum + num)\nmaxSum = Math.max(maxSum, currentSum)\n```\n\n`O(n)` time, `O(1)` space.\n\n**Key idea:** if the running sum becomes negative, restart from the current element. A classic **dynamic programming** problem reduced to a single pass.',
  },
  {
    id: 'algo-012',
    difficulty: 'EASY',
    order: 12,
    tags: ['string', 'hash-table', 'anagram'],
    questionRu: 'Что такое анаграмма и как проверить?',
    questionEn: 'What is an anagram and how do you check for one?',
    answerRu: '**Анаграмма** — строки из одних и тех же символов в разном порядке.\n\n- **Метод 1:** отсортировать обе строки и сравнить — `O(n log n)`\n- **Метод 2:** подсчёт символов через `Map`/объект — `O(n)` время, `O(1)` память (26 букв алфавита)\n\nМетод 2 оптимальнее. Предварительно проверить длины строк.',
    answerEn: 'An **anagram** consists of the same characters in a different order.\n\n- **Method 1:** sort both strings and compare — `O(n log n)`\n- **Method 2:** count characters using a `Map`/object — `O(n)` time, `O(1)` space (26 alphabet letters)\n\nMethod 2 is more efficient. Always check string lengths first.',
  },
  {
    id: 'algo-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['array', 'hash-table', 'duplicates'],
    questionRu: 'Как найти все дубликаты в массиве?',
    questionEn: 'How do you find all duplicates in an array?',
    answerRu: '- **Через `Set`:** итерировать; если элемент уже в `seen` — дубликат. `O(n)` время и память.\n- **Через `Map` с подсчётом:** найти элементы с `count > 1`.\n- **Без доп. памяти** (массив чисел `1..n`): помечать посещённые через отрицательный знак по индексу — `O(n)` время, `O(1)` память.',
    answerEn: '- **Using a `Set`:** iterate the array; if an element is already in the `seen` set, it\'s a duplicate. `O(n)` time and space.\n- **Using a `Map` with counts:** find elements where `count > 1`.\n- **Without extra memory** (array of numbers `1..n`): mark visited indices by negating the value at that index — `O(n)` time, `O(1)` space.',
  },
  {
    id: 'algo-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['linked-list', 'data-structures'],
    questionRu: 'Что такое связный список (linked list) и когда использовать?',
    questionEn: 'What is a linked list and when should you use one?',
    answerRu: '**Linked list** — узлы с данными и ссылкой на следующий (и предыдущий для **doubly linked list**).\n\n- Вставка/удаление в начало: `O(1)`\n- Доступ по индексу: `O(n)`\n\nВ JS нет нативного linked list — используют массив или реализуют вручную.\n\n**Преимущество перед массивом:** `O(1)` вставка/удаление при наличии ссылки на узел.\n\nПрименение:\n- **очередь**\n- **LRU кеш**',
    answerEn: 'A **linked list** consists of nodes, each holding data and a reference to the next node (and previous for a **doubly linked list**).\n\n- Insert/delete at the head: `O(1)`\n- Index access: `O(n)`\n\nJS has no native linked list — use an array or implement one manually.\n\n**Advantage over arrays:** `O(1)` insert/delete given a reference to the node.\n\nUse cases:\n- **queues**\n- **LRU caches**',
  },
  {
    id: 'algo-015',
    difficulty: 'EASY',
    order: 15,
    tags: ['stack', 'queue', 'data-structures'],
    questionRu: 'Что такое стек и очередь, как реализовать в JS?',
    questionEn: 'What are a stack and a queue, and how do you implement them in JS?',
    answerRu: '**Стек (LIFO):** `push`/`pop` с конца массива — оба `O(1)`.\n\nПрименение:\n- история браузера\n- undo/redo\n- обход **DFS**\n- скобочные задачи\n\n**Очередь (FIFO):** `enqueue` через `push`, `dequeue` через `shift` — `shift` `O(n)`.\n\nЭффективная очередь: **двусвязный список** или **circular buffer**.\n\nПрименение:\n- **BFS**\n- **Task Queue**\n- обработка событий',
    answerEn: '**Stack (LIFO):** `push`/`pop` from the end of an array — both `O(1)`.\n\nUses:\n- browser history\n- undo/redo\n- **DFS** traversal\n- bracket matching\n\n**Queue (FIFO):** enqueue via `push`, dequeue via `shift` — `shift` is `O(n)`.\n\nEfficient queue: **doubly linked list** or **circular buffer**.\n\nUses:\n- **BFS**\n- task queue\n- event processing',
  },
  {
    id: 'algo-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['bst', 'tree', 'data-structures'],
    questionRu: 'Что такое бинарное дерево поиска (BST)?',
    questionEn: 'What is a Binary Search Tree (BST)?',
    answerRu: '**BST:** левый потомок < узел < правый потомок.\n\n- Поиск, вставка, удаление: `O(log n)` для сбалансированного, `O(n)` для вырожденного (отсортированный вход)\n\n**Обходы:**\n- `inorder` (LNR) — даёт отсортированную последовательность\n- `preorder` (NLR)\n- `postorder` (LRN)\n\nПрименение:\n- упорядоченные данные\n- диапазонные запросы',
    answerEn: '**BST:** left child < node < right child.\n\n- Search, insert, delete: `O(log n)` for a balanced tree, `O(n)` for a degenerate tree (sorted input)\n\n**Traversals:**\n- `inorder` (LNR) — yields a sorted sequence\n- `preorder` (NLR)\n- `postorder` (LRN)\n\nUse cases:\n- ordered data\n- range queries',
  },
  {
    id: 'algo-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['hash-table', 'data-structures', 'collisions'],
    questionRu: 'Что такое хэш-таблица и как обрабатываются коллизии?',
    questionEn: 'What is a hash table and how are collisions handled?',
    answerRu: '**Хэш-таблица:** хэш-функция отображает ключ в индекс массива. **Коллизия** — два ключа дают один индекс.\n\nМетоды разрешения:\n- **Chaining** (цепочки) — список в ячейке\n- **Open addressing** (линейное пробирование) — следующая свободная ячейка\n\nJS `Object` и `Map` используют **chaining**. Хорошая хэш-функция минимизирует коллизии.',
    answerEn: 'A **hash table** uses a hash function to map a key to an array index. A **collision** occurs when two keys produce the same index.\n\nResolution methods:\n- **Chaining** — a linked list at each bucket\n- **Open addressing** (linear probing) — find the next free slot\n\nJS `Object` and `Map` use **chaining** internally. A good hash function minimizes collisions.',
  },
  {
    id: 'algo-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['graph', 'data-structures'],
    questionRu: 'Что такое граф и способы его представления?',
    questionEn: 'What is a graph and how can it be represented?',
    answerRu: '**Граф:** вершины (**nodes**) и рёбра (**edges**). Бывает направленным/ненаправленным, взвешенным.\n\n**Представления:**\n- **Матрица смежности** — `O(V²)` память, `O(1)` проверка ребра\n- **Список смежности** — `O(V+E)` память, эффективен для разреженных графов\n\nВ JS: `Map` или объект, где ключ — вершина, значение — массив соседей.',
    answerEn: 'A **graph** consists of vertices (**nodes**) and **edges**. It can be directed/undirected and weighted.\n\n**Representations:**\n- **Adjacency matrix** — `O(V²)` space, `O(1)` edge lookup\n- **Adjacency list** — `O(V+E)` space, efficient for sparse graphs\n\nIn JS: use a `Map` or plain object where the key is a vertex and the value is an array of neighbors.',
  },
  {
    id: 'algo-019',
    difficulty: 'HARD',
    order: 19,
    tags: ['heap', 'priority-queue', 'data-structures'],
    questionRu: 'Что такое куча (heap) и для чего используется?',
    questionEn: 'What is a heap and what is it used for?',
    answerRu: '**Heap** — полное бинарное дерево, где родитель `>=` потомков (**max-heap**) или `<=` (**min-heap**).\n\n- Вставка и извлечение max/min: `O(log n)`\n- Получение max/min: `O(1)`\n- Реализуется массивом\n\nПрименение:\n- **Priority Queue**\n- `heapsort`\n- топ-K элементов\n\nВ JS нет нативной кучи — реализуют вручную или через библиотеку.',
    answerEn: 'A **heap** is a complete binary tree where each parent is `>=` its children (**max-heap**) or `<=` (**min-heap**).\n\n- Insert and extract max/min: `O(log n)`\n- Peek max/min: `O(1)`\n- Implemented as an array\n\nUses:\n- **Priority Queue**\n- `heapsort`\n- top-K elements\n\nJS has no native heap — implement one manually or use a library.',
  },
  {
    id: 'algo-020',
    difficulty: 'MEDIUM',
    order: 20,
    tags: ['sorting', 'merge-sort', 'quick-sort'],
    questionRu: 'Какие алгоритмы сортировки нужно знать фронтендеру?',
    questionEn: 'Which sorting algorithms should a frontend developer know?',
    answerRu: '**Обязательно:**\n- **Merge sort** — `O(n log n)`, стабильный\n- **Quick sort** — `O(n log n)` средний, `O(n²)` худший\n\n**Принцип:**\n- **Bubble sort** — `O(n²)`\n- **Insertion sort** — `O(n²)`, эффективен для малых данных\n\n`Array.sort()` в V8 использует **TimSort** (merge + insertion) — `O(n log n)`, стабильный с ES2019.\n\n**Counting/Radix sort** для целых чисел — `O(n+k)`.',
    answerEn: '**Must know:**\n- **Merge sort** — `O(n log n)`, stable\n- **Quick sort** — `O(n log n)` average, `O(n²)` worst case\n\n**Understand the principles of:**\n- **Bubble sort** — `O(n²)`\n- **Insertion sort** — `O(n²)`, suitable for small data\n\n`Array.sort()` in V8 uses **TimSort** (merge + insertion) — `O(n log n)`, stable since ES2019.\n\n**Counting/Radix sort** for integers — `O(n+k)`.',
  },
  {
    id: 'algo-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['binary-search', 'search'],
    questionRu: 'Как работает бинарный поиск?',
    questionEn: 'How does binary search work?',
    answerRu: '**Бинарный поиск** работает на отсортированном массиве: сравнить с серединой, если меньше — искать в левой половине, больше — в правой. `O(log n)`.\n\nРеализация: `left=0`, `right=n-1`, `mid=Math.floor((left+right)/2)`.\n\nПрименение:\n- поиск в отсортированном массиве\n- поиск границы (первый/последний элемент, удовлетворяющий условию)',
    answerEn: '**Binary search** operates on a sorted array: compare the target with the middle element; if smaller, search the left half; if larger, search the right half. `O(log n)`.\n\nImplementation: `left=0`, `right=n-1`, `mid=Math.floor((left+right)/2)`.\n\nUse cases:\n- search in a sorted array\n- boundary search (first/last element satisfying a condition)',
  },
  {
    id: 'algo-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['quick-sort', 'sorting'],
    questionRu: 'Как работает быстрая сортировка (quicksort)?',
    questionEn: 'How does quicksort work?',
    answerRu: '**Quicksort:** выбрать **pivot**, разделить массив на меньшие и большие pivot, рекурсивно сортировать части. **Divide and conquer**.\n\n- `O(n log n)` средний\n- `O(n²)` худший (уже отсортированный массив с плохим pivot)\n- In-place, `O(log n)` памяти на стек\n\nСлучайный или **median-of-three** pivot для улучшения худшего случая.',
    answerEn: '**Quicksort:** choose a **pivot**, partition the array into elements smaller and larger than the pivot, then recursively sort each part. **Divide and conquer**.\n\n- `O(n log n)` average\n- `O(n²)` worst case (already sorted array with a bad pivot)\n- In-place, `O(log n)` stack space\n\nUse a random or **median-of-three** pivot to mitigate the worst case.',
  },
  {
    id: 'algo-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['merge-sort', 'sorting'],
    questionRu: 'Как работает сортировка слиянием (merge sort)?',
    questionEn: 'How does merge sort work?',
    answerRu: '**Merge sort:** разделить массив пополам рекурсивно до одного элемента, затем слить отсортированные половины.\n\n- `O(n log n)` всегда — нет худшего случая\n- Стабильный\n- `O(n)` дополнительной памяти\n\nПредпочтителен для связных списков и внешней сортировки. Основа **TimSort**, используемого в V8.',
    answerEn: '**Merge sort:** recursively split the array in half down to single elements, then merge the sorted halves back together.\n\n- `O(n log n)` always — no worst case\n- Stable\n- `O(n)` extra memory\n\nPreferred for linked lists and external sorting. Forms the basis of **TimSort** used in V8.',
  },
  {
    id: 'algo-024',
    difficulty: 'MEDIUM',
    order: 24,
    tags: ['bfs', 'dfs', 'graph', 'tree'],
    questionRu: 'Что такое BFS и DFS и когда применять?',
    questionEn: 'What are BFS and DFS and when should each be used?',
    answerRu: '**BFS** (поиск в ширину): обходит по уровням через **очередь**. Находит кратчайший путь в невзвешенном графе. `O(V+E)`.\n\n**DFS** (поиск в глубину): идёт вглубь через **стек**/рекурсию. Для:\n- обхода дерева\n- топологической сортировки\n- поиска компонент связности\n- решения лабиринтов\n\nИспользуй **BFS** для кратчайшего пути, **DFS** для исчерпывающего поиска.',
    answerEn: '**BFS** (breadth-first search): traverses level by level using a **queue**. Finds the shortest path in an unweighted graph. `O(V+E)`.\n\n**DFS** (depth-first search): goes deep using a **stack** or recursion. Used for:\n- tree traversal\n- topological sort\n- finding connected components\n- solving mazes\n\nUse **BFS** for shortest paths, **DFS** for exhaustive search.',
  },
  {
    id: 'algo-025',
    difficulty: 'MEDIUM',
    order: 25,
    tags: ['heap', 'sorting', 'top-k'],
    questionRu: 'Как найти K-й наибольший элемент?',
    questionEn: 'How do you find the K-th largest element?',
    answerRu: '- **Метод 1:** отсортировать `O(n log n)`, взять индекс `n-k`\n- **Метод 2:** **min-heap** размером `K` — итерировать, поддерживать кучу размером `K`; вершина кучи — ответ. `O(n log k)`\n- **Метод 3:** **QuickSelect** — как quicksort, но рекурсия только в нужную сторону. `O(n)` средний\n\nДля потоковых данных — **min-heap**.',
    answerEn: '- **Method 1:** sort the array `O(n log n)` and take index `n-k`\n- **Method 2:** **min-heap** of size `K` — iterate the array maintaining a heap of size `K`; the top of the heap is the answer. `O(n log k)`\n- **Method 3:** **QuickSelect** — like quicksort but recurse only into the relevant partition. `O(n)` average\n\nFor streaming data, use a **min-heap**.',
  },
  {
    id: 'algo-026',
    difficulty: 'HARD',
    order: 26,
    tags: ['graph', 'topological-sort', 'dag'],
    questionRu: 'Что такое топологическая сортировка?',
    questionEn: 'What is topological sort?',
    answerRu: '**Топологическая сортировка** — линейный порядок вершин направленного ациклического графа (**DAG**), где каждая вершина предшествует всем вершинам, в которые ведут её рёбра.\n\nАлгоритмы:\n- **Алгоритм Кана:** подсчёт входящих рёбер, BFS от вершин без входящих\n- **DFS** с postorder\n\nПрименение:\n- порядок зависимостей\n- сборка проекта',
    answerEn: '**Topological sort** produces a linear ordering of the vertices of a directed acyclic graph (**DAG**) such that each vertex comes before all vertices it has edges pointing to.\n\nAlgorithms:\n- **Kahn\'s algorithm:** count in-degrees, then BFS from zero-in-degree vertices\n- **DFS** with postorder traversal\n\nUse cases:\n- dependency resolution\n- build order',
  },
  {
    id: 'algo-027',
    difficulty: 'MEDIUM',
    order: 27,
    tags: ['recursion', 'stack'],
    questionRu: 'Что такое рекурсия и хвостовая рекурсия?',
    questionEn: 'What is recursion and tail recursion?',
    answerRu: '**Рекурсия** — функция вызывает себя с меньшим входом. Базовый случай останавливает рекурсию. Каждый вызов занимает место в стеке — `O(n)` памяти для глубины `n`.\n\n**Хвостовая рекурсия:** рекурсивный вызов последний в функции — компилятор может оптимизировать в цикл.\n\nJS **не гарантирует TCO** (tail call optimization).',
    answerEn: '**Recursion** is when a function calls itself with a smaller input. The base case stops the recursion. Each call occupies stack space — `O(n)` memory for depth `n`.\n\n**Tail recursion:** the recursive call is the last operation in the function, allowing the compiler to optimize it into a loop.\n\nJS **does not guarantee TCO** (tail call optimization).',
  },
  {
    id: 'algo-028',
    difficulty: 'MEDIUM',
    order: 28,
    tags: ['memoization', 'dynamic-programming', 'recursion'],
    questionRu: 'Что такое мемоизация в контексте рекурсии?',
    questionEn: 'What is memoization in the context of recursion?',
    answerRu: '**Мемоизация** — кеширование результатов рекурсивных вызовов для избежания повторных вычислений.\n\n- Fibonacci без мемоизации: `O(2ⁿ)`\n- С мемоизацией: `O(n)`\n\nРеализация: `Map` или объект, где ключ — аргументы.\n\nПервый шаг **динамического программирования** (top-down подход). Превращает экспоненциальные алгоритмы в полиномиальные.',
    answerEn: '**Memoization** is caching the results of recursive calls to avoid redundant computation.\n\n- Fibonacci without memoization: `O(2ⁿ)`\n- With memoization: `O(n)`\n\nImplementation: a `Map` or plain object keyed by the arguments.\n\nIt is the first step toward **dynamic programming** (top-down approach) and can turn exponential algorithms into polynomial ones.',
  },
  {
    id: 'algo-029',
    difficulty: 'HARD',
    order: 29,
    tags: ['dynamic-programming'],
    questionRu: 'Что такое динамическое программирование?',
    questionEn: 'What is dynamic programming?',
    answerRu: '**Динамическое программирование (ДП)** — разбивка задачи на перекрывающиеся подзадачи, сохранение результатов для переиспользования.\n\n- **Top-down** (мемоизация): рекурсия + кеш\n- **Bottom-up** (табуляция): итеративно заполнять таблицу от малых подзадач к большим\n\n**Признаки ДП задачи:**\n- оптимальная подструктура\n- перекрывающиеся подзадачи',
    answerEn: '**Dynamic programming (DP)** breaks a problem into overlapping subproblems and stores results for reuse.\n\n- **Top-down** (memoization): recursion + cache\n- **Bottom-up** (tabulation): iteratively fill a table from smaller subproblems to larger ones\n\n**Indicators of a DP problem:**\n- optimal substructure\n- overlapping subproblems',
  },
  {
    id: 'algo-030',
    difficulty: 'EASY',
    order: 30,
    tags: ['dynamic-programming', 'fibonacci'],
    questionRu: 'Как решить задачу о числах Фибоначчи оптимально?',
    questionEn: 'How do you solve the Fibonacci problem optimally?',
    answerRu: '- **Наивная рекурсия:** `O(2ⁿ)`\n- **Мемоизация:** `O(n)` время, `O(n)` память\n- **Bottom-up ДП:** массив `dp[i] = dp[i-1] + dp[i-2]` — `O(n)` время, `O(n)` память\n- **Оптимально:** хранить только два предыдущих числа — `O(n)` время, `O(1)` память\n- **Матричное возведение в степень:** `O(log n)` время для очень больших `n`',
    answerEn: '- **Naive recursion:** `O(2ⁿ)`\n- **Memoization:** `O(n)` time, `O(n)` space\n- **Bottom-up DP:** array `dp[i] = dp[i-1] + dp[i-2]` — `O(n)` time, `O(n)` space\n- **Optimal:** keep only the last two numbers — `O(n)` time, `O(1)` space\n- **Matrix exponentiation:** `O(log n)` time for very large `n`',
  },
  {
    id: 'algo-031',
    difficulty: 'HARD',
    order: 31,
    tags: ['dynamic-programming', 'knapsack'],
    questionRu: 'Что такое задача о рюкзаке (knapsack)?',
    questionEn: 'What is the knapsack problem?',
    answerRu: '**0/1 Knapsack:** `N` предметов с весом и ценностью, рюкзак вместимостью `W`. Максимизировать ценность, не превышая вместимость. Каждый предмет берём или нет.\n\nДП таблица `dp[i][w]`: максимальная ценность для `i` предметов и вместимости `w`. `O(n*W)` время и память.\n\nПаттерн для задач **выбора с ограничениями**.',
    answerEn: '**0/1 Knapsack:** given `N` items with weights and values and a knapsack with capacity `W`, maximize the total value without exceeding the capacity. Each item is either taken or not.\n\nDP table `dp[i][w]`: max value for `i` items and capacity `w`. `O(n*W)` time and space.\n\nA foundational pattern for **constrained selection problems**.',
  },
  {
    id: 'algo-032',
    difficulty: 'MEDIUM',
    order: 32,
    tags: ['tree', 'dfs', 'bfs', 'iteration'],
    questionRu: 'Как обойти дерево без рекурсии?',
    questionEn: 'How do you traverse a tree without recursion?',
    answerRu: '**DFS итеративно** через явный стек: push root, пока стек не пуст — pop, обработать, push правый затем левый потомок (для **preorder**).\n\n**BFS** через очередь: enqueue root, пока очередь не пуста — dequeue, обработать, enqueue потомков.\n\nИтеративный подход избегает **stack overflow** для глубоких деревьев.',
    answerEn: '**Iterative DFS** using an explicit stack: push root, then while the stack is non-empty — pop, process, push right then left child (for **preorder**).\n\n**BFS** using a queue: enqueue root, then while the queue is non-empty — dequeue, process, enqueue children.\n\nThe iterative approach avoids **stack overflow** on deep trees.',
  },
  {
    id: 'algo-033',
    difficulty: 'EASY',
    order: 33,
    tags: ['stack', 'string', 'parentheses'],
    questionRu: 'Что такое задача о скобках (valid parentheses)?',
    questionEn: 'What is the valid parentheses problem?',
    answerRu: 'Проверить правильность расстановки скобок: **стек** — при открывающей скобке `push`, при закрывающей — `pop` и проверить соответствие. В конце стек должен быть пуст.\n\n`O(n)` время, `O(n)` память.\n\nРасширение: **generate all valid parentheses** — backtracking. Классическая задача на понимание стека.',
    answerEn: 'Check whether a string of brackets is valid: **stack** — push on an opening bracket, pop on a closing bracket and verify it matches. At the end the stack must be empty.\n\n`O(n)` time, `O(n)` space.\n\nExtension: **generate all valid parentheses** combinations — backtracking. A classic problem for understanding stacks.',
  },
];
