import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'browser-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['rendering'],
    questionRu: 'Что происходит когда браузер получает HTML?',
    questionEn: 'Что происходит когда браузер получает HTML?',
    answerRu: 'Браузер парсит HTML → строит DOM. Встречает CSS → загружает и строит CSSOM. DOM + CSSOM → Render Tree (только видимые элементы). Layout — вычисляет размеры и позиции. Paint — рисует пиксели. Composite — собирает слои. Скрипты без defer/async блокируют парсинг HTML.',
    answerEn: 'Браузер парсит HTML → строит DOM. Встречает CSS → загружает и строит CSSOM. DOM + CSSOM → Render Tree (только видимые элементы). Layout — вычисляет размеры и позиции. Paint — рисует пиксели. Composite — собирает слои. Скрипты без defer/async блокируют парсинг HTML.',
  },
  {
    id: 'browser-002',
    difficulty: 'EASY',
    order: 2,
    tags: ['rendering'],
    questionRu: 'Что такое DOM и CSSOM?',
    questionEn: 'Что такое DOM и CSSOM?',
    answerRu: 'DOM (Document Object Model) — древовидное представление HTML в памяти, API для JS. CSSOM (CSS Object Model) — аналогичное дерево для CSS со всеми стилями включая унаследованные. Браузер не может построить Render Tree пока не готовы оба — CSS блокирует рендеринг.',
    answerEn: 'DOM (Document Object Model) — древовидное представление HTML в памяти, API для JS. CSSOM (CSS Object Model) — аналогичное дерево для CSS со всеми стилями включая унаследованные. Браузер не может построить Render Tree пока не готовы оба — CSS блокирует рендеринг.',
  },
  {
    id: 'browser-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['rendering'],
    questionRu: 'Почему CSS блокирует рендеринг, а JS блокирует парсинг?',
    questionEn: 'Почему CSS блокирует рендеринг, а JS блокирует парсинг?',
    answerRu: 'CSS блокирует рендеринг: браузер не строит Render Tree без CSSOM, чтобы не показывать FOUC. JS блокирует парсинг: скрипт может изменить DOM и CSSOM, поэтому браузер останавливается, загружает и выполняет JS. defer/async снимают блокировку парсинга.',
    answerEn: 'CSS блокирует рендеринг: браузер не строит Render Tree без CSSOM, чтобы не показывать FOUC. JS блокирует парсинг: скрипт может изменить DOM и CSSOM, поэтому браузер останавливается, загружает и выполняет JS. defer/async снимают блокировку парсинга.',
  },
  {
    id: 'browser-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['rendering'],
    questionRu: 'Что такое render-blocking ресурсы и как с ними бороться?',
    questionEn: 'Что такое render-blocking ресурсы и как с ними бороться?',
    answerRu: 'Render-blocking: CSS в <head>, синхронный JS. Решения для CSS: inline critical CSS, media queries (print CSS не блокирует). Для JS: defer, async, перенос в конец body. Также: preload для приоритетных ресурсов, HTTP/2 для параллельной загрузки.',
    answerEn: 'Render-blocking: CSS в <head>, синхронный JS. Решения для CSS: inline critical CSS, media queries (print CSS не блокирует). Для JS: defer, async, перенос в конец body. Также: preload для приоритетных ресурсов, HTTP/2 для параллельной загрузки.',
  },
  {
    id: 'browser-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['rendering'],
    questionRu: 'Что такое critical CSS?',
    questionEn: 'Что такое critical CSS?',
    answerRu: 'Critical CSS — минимальный набор стилей для отрисовки видимой части страницы (above the fold). Инлайнится в <style> в <head> для мгновенного рендера без ожидания загрузки CSS-файла. Остальные стили загружаются асинхронно. Улучшает FCP и LCP.',
    answerEn: 'Critical CSS — минимальный набор стилей для отрисовки видимой части страницы (above the fold). Инлайнится в <style> в <head> для мгновенного рендера без ожидания загрузки CSS-файла. Остальные стили загружаются асинхронно. Улучшает FCP и LCP.',
  },
  {
    id: 'browser-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['rendering'],
    questionRu: 'Что такое preload, prefetch и preconnect?',
    questionEn: 'Что такое preload, prefetch и preconnect?',
    answerRu: 'preload (<link rel="preload">): загрузить ресурс с высоким приоритетом для текущей страницы — шрифты, критичные скрипты. prefetch: загрузить с низким приоритетом для следующей навигации. preconnect: заранее установить TCP/TLS соединение с доменом. dns-prefetch: только DNS-резолюция.',
    answerEn: 'preload (<link rel="preload">): загрузить ресурс с высоким приоритетом для текущей страницы — шрифты, критичные скрипты. prefetch: загрузить с низким приоритетом для следующей навигации. preconnect: заранее установить TCP/TLS соединение с доменом. dns-prefetch: только DNS-резолюция.',
  },
  {
    id: 'browser-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['rendering'],
    questionRu: 'Что такое Core Web Vitals?',
    questionEn: 'Что такое Core Web Vitals?',
    answerRu: 'Core Web Vitals — метрики Google для оценки UX. LCP (Largest Contentful Paint): загрузка главного контента, цель <2.5s. FID (First Input Delay) / INP (Interaction to Next Paint): отзывчивость, цель <200ms. CLS (Cumulative Layout Shift): стабильность layout, цель <0.1. Влияют на поисковый рейтинг.',
    answerEn: 'Core Web Vitals — метрики Google для оценки UX. LCP (Largest Contentful Paint): загрузка главного контента, цель <2.5s. FID (First Input Delay) / INP (Interaction to Next Paint): отзывчивость, цель <200ms. CLS (Cumulative Layout Shift): стабильность layout, цель <0.1. Влияют на поисковый рейтинг.',
  },
  {
    id: 'browser-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['reflow'],
    questionRu: 'В чём разница между reflow и repaint?',
    questionEn: 'В чём разница между reflow и repaint?',
    answerRu: 'Reflow (layout): пересчёт геометрии элементов — размеров и позиций. Дорогая операция, затрагивает соседей и родителей. Триггеры: изменение width, height, margin, font-size, добавление/удаление элементов. Repaint: перерисовка пикселей без изменения геометрии. Триггеры: color, background, visibility. Reflow всегда вызывает repaint.',
    answerEn: 'Reflow (layout): пересчёт геометрии элементов — размеров и позиций. Дорогая операция, затрагивает соседей и родителей. Триггеры: изменение width, height, margin, font-size, добавление/удаление элементов. Repaint: перерисовка пикселей без изменения геометрии. Триггеры: color, background, visibility. Reflow всегда вызывает repaint.',
  },
  {
    id: 'browser-009',
    difficulty: 'HARD',
    order: 9,
    tags: ['reflow'],
    questionRu: 'Что такое композитинг (compositing)?',
    questionEn: 'Что такое композитинг (compositing)?',
    answerRu: 'Compositing — финальный этап: браузер собирает слои (layers) в итоговое изображение на GPU. Некоторые элементы выносятся в отдельный compositor layer: transform, opacity, will-change, video, canvas. Анимации transform/opacity происходят только на этапе compositing — не вызывают reflow/repaint.',
    answerEn: 'Compositing — финальный этап: браузер собирает слои (layers) в итоговое изображение на GPU. Некоторые элементы выносятся в отдельный compositor layer: transform, opacity, will-change, video, canvas. Анимации transform/opacity происходят только на этапе compositing — не вызывают reflow/repaint.',
  },
  {
    id: 'browser-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['reflow'],
    questionRu: 'Как минимизировать reflow?',
    questionEn: 'Как минимизировать reflow?',
    answerRu: 'Батчить DOM-изменения: читать геометрию отдельно от записи (избегать layout thrashing). Использовать DocumentFragment. Скрывать элемент через display:none перед множественными изменениями. Использовать transform вместо top/left. requestAnimationFrame для визуальных изменений. Избегать чтение offsetWidth в цикле.',
    answerEn: 'Батчить DOM-изменения: читать геометрию отдельно от записи (избегать layout thrashing). Использовать DocumentFragment. Скрывать элемент через display:none перед множественными изменениями. Использовать transform вместо top/left. requestAnimationFrame для визуальных изменений. Избегать чтение offsetWidth в цикле.',
  },
  {
    id: 'browser-011',
    difficulty: 'HARD',
    order: 11,
    tags: ['reflow'],
    questionRu: 'Что такое layout thrashing?',
    questionEn: 'Что такое layout thrashing?',
    answerRu: "Layout thrashing — чередование чтения и записи DOM-геометрии в цикле: el.style.width = el.offsetWidth + 'px' в цикле заставляет браузер делать reflow на каждой итерации. Решение: сначала прочитать все значения, потом записать все изменения. Библиотека FastDOM помогает батчить.",
    answerEn: "Layout thrashing — чередование чтения и записи DOM-геометрии в цикле: el.style.width = el.offsetWidth + 'px' в цикле заставляет браузер делать reflow на каждой итерации. Решение: сначала прочитать все значения, потом записать все изменения. Библиотека FastDOM помогает батчить.",
  },
  {
    id: 'browser-012',
    difficulty: 'HARD',
    order: 12,
    tags: ['reflow'],
    questionRu: 'Что такое paint flashing и как его обнаружить?',
    questionEn: 'Что такое paint flashing и как его обнаружить?',
    answerRu: 'Paint flashing — визуальная индикация областей, которые браузер перерисовывает. Включается в Chrome DevTools: Rendering → Paint flashing. Зелёные вспышки = repaint. Частые перерисовки больших областей — признак проблемы с производительностью. Цель: минимизировать перерисовываемые области.',
    answerEn: 'Paint flashing — визуальная индикация областей, которые браузер перерисовывает. Включается в Chrome DevTools: Rendering → Paint flashing. Зелёные вспышки = repaint. Частые перерисовки больших областей — признак проблемы с производительностью. Цель: минимизировать перерисовываемые области.',
  },
  {
    id: 'browser-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['reflow'],
    questionRu: 'Как работает requestAnimationFrame?',
    questionEn: 'Как работает requestAnimationFrame?',
    answerRu: 'requestAnimationFrame(callback) вызывает callback перед следующим рендером браузера (~60fps). Синхронизирован с частотой обновления дисплея. Преимущества над setTimeout: не вызывается в фоновых вкладках (экономит CPU), точно приурочен к циклу рендера, автоматически батчит визуальные обновления.',
    answerEn: 'requestAnimationFrame(callback) вызывает callback перед следующим рендером браузера (~60fps). Синхронизирован с частотой обновления дисплея. Преимущества над setTimeout: не вызывается в фоновых вкладках (экономит CPU), точно приурочен к циклу рендера, автоматически батчит визуальные обновления.',
  },
  {
    id: 'browser-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['web-apis'],
    questionRu: 'Что такое IntersectionObserver и как использовать?',
    questionEn: 'Что такое IntersectionObserver и как использовать?',
    answerRu: 'IntersectionObserver отслеживает пересечение элемента с viewport или другим элементом. new IntersectionObserver(callback, { threshold: 0.5 }) — вызов при 50% видимости. Применения: ленивая загрузка изображений, бесконечный скролл, анимации при появлении. Эффективнее scroll-событий — не блокирует main thread.',
    answerEn: 'IntersectionObserver отслеживает пересечение элемента с viewport или другим элементом. new IntersectionObserver(callback, { threshold: 0.5 }) — вызов при 50% видимости. Применения: ленивая загрузка изображений, бесконечный скролл, анимации при появлении. Эффективнее scroll-событий — не блокирует main thread.',
  },
  {
    id: 'browser-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['web-apis'],
    questionRu: 'Что такое MutationObserver?',
    questionEn: 'Что такое MutationObserver?',
    answerRu: 'MutationObserver отслеживает изменения в DOM-дереве: добавление/удаление узлов, изменения атрибутов и текста. Асинхронный — использует микрозадачи, не блокирует. Применения: отслеживание изменений сторонних скриптов, полифилы, автоматизация. Эффективнее устаревших mutation events.',
    answerEn: 'MutationObserver отслеживает изменения в DOM-дереве: добавление/удаление узлов, изменения атрибутов и текста. Асинхронный — использует микрозадачи, не блокирует. Применения: отслеживание изменений сторонних скриптов, полифилы, автоматизация. Эффективнее устаревших mutation events.',
  },
  {
    id: 'browser-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['web-apis'],
    questionRu: 'Что такое ResizeObserver?',
    questionEn: 'Что такое ResizeObserver?',
    answerRu: 'ResizeObserver отслеживает изменения размеров элемента. В отличие от window resize event — работает для любого элемента, не только окна. Применения: адаптивные компоненты (container queries вручную), canvas с динамическим размером, виртуализация. Не вызывает reflow при чтении размеров.',
    answerEn: 'ResizeObserver отслеживает изменения размеров элемента. В отличие от window resize event — работает для любого элемента, не только окна. Применения: адаптивные компоненты (container queries вручную), canvas с динамическим размером, виртуализация. Не вызывает reflow при чтении размеров.',
  },
  {
    id: 'browser-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['web-apis'],
    questionRu: 'Что такое Web Workers и когда использовать?',
    questionEn: 'Что такое Web Workers и когда использовать?',
    answerRu: 'Web Workers — отдельные потоки для тяжёлых вычислений без блокировки main thread. Общение через postMessage/onmessage. Нет доступа к DOM. Типы: Dedicated Worker (один потребитель), Shared Worker (несколько вкладок), Service Worker (перехват сетевых запросов). Для: парсинга, шифрования, обработки данных.',
    answerEn: 'Web Workers — отдельные потоки для тяжёлых вычислений без блокировки main thread. Общение через postMessage/onmessage. Нет доступа к DOM. Типы: Dedicated Worker (один потребитель), Shared Worker (несколько вкладок), Service Worker (перехват сетевых запросов). Для: парсинга, шифрования, обработки данных.',
  },
  {
    id: 'browser-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['web-apis'],
    questionRu: 'Что такое Service Worker?',
    questionEn: 'Что такое Service Worker?',
    answerRu: 'Service Worker — скрипт в фоновом потоке, перехватывающий сетевые запросы. Основа PWA. Возможности: офлайн-работа через Cache API, push-уведомления, фоновая синхронизация. Жизненный цикл: install → activate → fetch. Работает только по HTTPS (кроме localhost).',
    answerEn: 'Service Worker — скрипт в фоновом потоке, перехватывающий сетевые запросы. Основа PWA. Возможности: офлайн-работа через Cache API, push-уведомления, фоновая синхронизация. Жизненный цикл: install → activate → fetch. Работает только по HTTPS (кроме localhost).',
  },
  {
    id: 'browser-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['web-apis'],
    questionRu: 'Что такое WebSocket и когда использовать?',
    questionEn: 'Что такое WebSocket и когда использовать?',
    answerRu: 'WebSocket — протокол для двусторонней связи клиент-сервер в реальном времени по одному соединению. В отличие от HTTP: сервер может инициировать отправку данных. Применения: чат, live-обновления, онлайн-игры, совместное редактирование. Альтернативы: SSE (только сервер → клиент), long polling.',
    answerEn: 'WebSocket — протокол для двусторонней связи клиент-сервер в реальном времени по одному соединению. В отличие от HTTP: сервер может инициировать отправку данных. Применения: чат, live-обновления, онлайн-игры, совместное редактирование. Альтернативы: SSE (только сервер → клиент), long polling.',
  },
  {
    id: 'browser-020',
    difficulty: 'MEDIUM',
    order: 20,
    tags: ['web-apis'],
    questionRu: 'Что такое History API и как работает SPA-роутинг?',
    questionEn: 'Что такое History API и как работает SPA-роутинг?',
    answerRu: 'History API: pushState, replaceState — изменяют URL без перезагрузки страницы. popstate событие — при нажатии назад/вперёд. SPA-роутинг: перехватывает клики по ссылкам, вызывает pushState, рендерит нужный компонент. Сервер должен отдавать index.html для всех маршрутов.',
    answerEn: 'History API: pushState, replaceState — изменяют URL без перезагрузки страницы. popstate событие — при нажатии назад/вперёд. SPA-роутинг: перехватывает клики по ссылкам, вызывает pushState, рендерит нужный компонент. Сервер должен отдавать index.html для всех маршрутов.',
  },
  {
    id: 'browser-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['storage'],
    questionRu: 'В чём разница между localStorage, sessionStorage и cookies?',
    questionEn: 'В чём разница между localStorage, sessionStorage и cookies?',
    answerRu: 'localStorage: до 5-10MB, постоянное, только клиент, один origin. sessionStorage: то же, но очищается при закрытии вкладки. Cookies: до 4KB, отправляются с каждым запросом на сервер, управляются сервером, поддерживают httpOnly/secure/SameSite. Для сессий и авторизации — cookies. Для UI-настроек — localStorage.',
    answerEn: 'localStorage: до 5-10MB, постоянное, только клиент, один origin. sessionStorage: то же, но очищается при закрытии вкладки. Cookies: до 4KB, отправляются с каждым запросом на сервер, управляются сервером, поддерживают httpOnly/secure/SameSite. Для сессий и авторизации — cookies. Для UI-настроек — localStorage.',
  },
  {
    id: 'browser-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['storage'],
    questionRu: 'Что такое IndexedDB?',
    questionEn: 'Что такое IndexedDB?',
    answerRu: 'IndexedDB — низкоуровневая NoSQL база данных в браузере. Хранит большие объёмы структурированных данных (сотни MB), поддерживает транзакции, индексы, бинарные данные. Асинхронный API. Используется в PWA для офлайн-данных. Обёртки для удобства: idb, Dexie.js.',
    answerEn: 'IndexedDB — низкоуровневая NoSQL база данных в браузере. Хранит большие объёмы структурированных данных (сотни MB), поддерживает транзакции, индексы, бинарные данные. Асинхронный API. Используется в PWA для офлайн-данных. Обёртки для удобства: idb, Dexie.js.',
  },
  {
    id: 'browser-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['storage'],
    questionRu: 'Как работает HTTP-кеширование?',
    questionEn: 'Как работает HTTP-кеширование?',
    answerRu: 'Cache-Control: max-age=3600 — кешировать на 1 час. no-cache — всегда валидировать с сервером. no-store — не кешировать. ETag и Last-Modified — условные запросы: браузер отправляет If-None-Match, сервер отвечает 304 Not Modified если не изменилось. immutable для неизменяемых ресурсов.',
    answerEn: 'Cache-Control: max-age=3600 — кешировать на 1 час. no-cache — всегда валидировать с сервером. no-store — не кешировать. ETag и Last-Modified — условные запросы: браузер отправляет If-None-Match, сервер отвечает 304 Not Modified если не изменилось. immutable для неизменяемых ресурсов.',
  },
  {
    id: 'browser-024',
    difficulty: 'HARD',
    order: 24,
    tags: ['storage'],
    questionRu: 'Что такое Cache API и как использовать с Service Worker?',
    questionEn: 'Что такое Cache API и как использовать с Service Worker?',
    answerRu: 'Cache API — хранилище пар запрос/ответ для офлайн-работы. Используется в Service Worker: cache.put(request, response), cache.match(request). Стратегии: Cache First (офлайн), Network First (актуальность), Stale While Revalidate (скорость + свежесть). Workbox автоматизирует стратегии.',
    answerEn: 'Cache API — хранилище пар запрос/ответ для офлайн-работы. Используется в Service Worker: cache.put(request, response), cache.match(request). Стратегии: Cache First (офлайн), Network First (актуальность), Stale While Revalidate (скорость + свежесть). Workbox автоматизирует стратегии.',
  },
  {
    id: 'browser-025',
    difficulty: 'HARD',
    order: 25,
    tags: ['storage'],
    questionRu: 'Что такое мемоизация на уровне браузера (bfcache)?',
    questionEn: 'Что такое мемоизация на уровне браузера (bfcache)?',
    answerRu: 'bfcache (back/forward cache) — браузер сохраняет полный снимок страницы в памяти при навигации. При нажатии назад — мгновенное восстановление без повторной загрузки. Страница не подходит для bfcache если: открытое WebSocket-соединение, Cache-Control: no-store, обработчик unload. Проверка в DevTools → Application.',
    answerEn: 'bfcache (back/forward cache) — браузер сохраняет полный снимок страницы в памяти при навигации. При нажатии назад — мгновенное восстановление без повторной загрузки. Страница не подходит для bfcache если: открытое WebSocket-соединение, Cache-Control: no-store, обработчик unload. Проверка в DevTools → Application.',
  },
];
