import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'browser-001',
    difficulty: 'HARD',
    questionRu: 'Как браузер отображает страницу? Опиши Critical Rendering Path.',
    questionEn: 'How does the browser render a page? Describe the Critical Rendering Path.',
    answerRu: '**Critical Rendering Path** — последовательность шагов от HTML до пикселей на экране:\n\n1. **Parse HTML → DOM** — парсинг HTML в дерево объектов\n2. **Parse CSS → CSSOM** — парсинг CSS в дерево стилей\n3. **DOM + CSSOM → Render Tree** — объединение видимых элементов со стилями\n4. **Layout (Reflow)** — вычисление размеров и позиций\n5. **Paint** — отрисовка пикселей\n6. **Composite** — склейка слоёв на GPU\n\n**Блокирующие ресурсы:**\n- CSS блокирует рендеринг\n- `<script>` без `async/defer` блокирует парсинг HTML\n\n**Оптимизации:** `async`/`defer` для скриптов, минификация CSS, критический CSS inline.',
    answerEn: '**Critical Rendering Path** — sequence of steps from HTML to pixels on screen:\n\n1. **Parse HTML → DOM** — parse HTML into object tree\n2. **Parse CSS → CSSOM** — parse CSS into style tree\n3. **DOM + CSSOM → Render Tree** — combine visible elements with styles\n4. **Layout (Reflow)** — calculate sizes and positions\n5. **Paint** — draw pixels\n6. **Composite** — merge layers on GPU\n\n**Blocking resources:**\n- CSS blocks rendering\n- `<script>` without `async/defer` blocks HTML parsing\n\n**Optimizations:** `async`/`defer` for scripts, CSS minification, critical CSS inline.',
    tags: ['rendering', 'dom', 'cssom', 'performance'],
    order: 1,
  },
  {
    id: 'browser-002',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое event bubbling и capturing?',
    questionEn: 'What is event bubbling and capturing?',
    answerRu: 'При клике на элемент событие проходит 3 фазы:\n\n1. **Capturing** (перехват) — от window вниз до цели\n2. **Target** — на самом элементе\n3. **Bubbling** (всплытие) — от цели вверх до window\n\n```js\n// По умолчанию — bubbling фаза\nelement.addEventListener("click", handler);\n\n// Capturing фаза\nelement.addEventListener("click", handler, true);\n\n// Остановить всплытие\nevent.stopPropagation();\n\n// Остановить всплытие + другие обработчики на этом элементе\nevent.stopImmediatePropagation();\n```\n\n**Event Delegation** — используй всплытие чтобы вешать один обработчик на родителя вместо многих на детей.',
    answerEn: 'When clicking an element, the event passes through 3 phases:\n\n1. **Capturing** — from window down to the target\n2. **Target** — on the element itself\n3. **Bubbling** — from target up to window\n\n```js\n// Default — bubbling phase\nelement.addEventListener("click", handler);\n\n// Capturing phase\nelement.addEventListener("click", handler, true);\n\n// Stop bubbling\nevent.stopPropagation();\n\n// Stop bubbling + other handlers on this element\nevent.stopImmediatePropagation();\n```\n\n**Event Delegation** — use bubbling to attach one handler to a parent instead of many handlers to children.',
    tags: ['events', 'bubbling', 'capturing', 'delegation'],
    order: 2,
  },
  {
    id: 'browser-003',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое LocalStorage, SessionStorage и Cookie? В чём отличия?',
    questionEn: 'What are LocalStorage, SessionStorage and Cookies? What are the differences?',
    answerRu: '|  | localStorage | sessionStorage | Cookie |\n|---|---|---|---|\n| Объём | ~5-10MB | ~5MB | ~4KB |\n| Срок жизни | Бессрочно | Вкладка | Задаётся |\n| Отправка на сервер | ❌ | ❌ | ✅ автоматически |\n| Доступ из JS | ✅ | ✅ | ✅ (если не httpOnly) |\n| Домен | Текущий | Текущий | Настраивается |\n\n```js\n// localStorage\nlocalStorage.setItem("key", "value");\nlocalStorage.getItem("key");\nlocalStorage.removeItem("key");\n\n// sessionStorage — тот же API\nsessionStorage.setItem("key", "value");\n```\n\n**Cookie флаги безопасности:** `HttpOnly` (нет доступа из JS), `Secure` (только HTTPS), `SameSite` (защита от CSRF).',
    answerEn: '|  | localStorage | sessionStorage | Cookie |\n|---|---|---|---|\n| Size | ~5-10MB | ~5MB | ~4KB |\n| Lifetime | Permanent | Tab session | Configurable |\n| Sent to server | ❌ | ❌ | ✅ automatically |\n| JS access | ✅ | ✅ | ✅ (if not httpOnly) |\n| Domain | Current | Current | Configurable |\n\n```js\n// localStorage\nlocalStorage.setItem("key", "value");\nlocalStorage.getItem("key");\nlocalStorage.removeItem("key");\n\n// sessionStorage — same API\nsessionStorage.setItem("key", "value");\n```\n\n**Cookie security flags:** `HttpOnly` (no JS access), `Secure` (HTTPS only), `SameSite` (CSRF protection).',
    tags: ['storage', 'localstorage', 'cookies', 'security'],
    order: 3,
  },
  {
    id: 'browser-004',
    difficulty: 'HARD',
    questionRu: 'Что такое CORS и как он работает?',
    questionEn: 'What is CORS and how does it work?',
    answerRu: '**CORS (Cross-Origin Resource Sharing)** — механизм браузера, контролирующий запросы между разными источниками (origin = protocol + host + port).\n\n**Preflight запрос** — браузер отправляет OPTIONS перед реальным запросом, если:\n- Метод не GET/POST/HEAD\n- Нестандартные заголовки\n- Content-Type не простой\n\n```\nBrowser → OPTIONS /api/data → Server\nBrowser ← Access-Control-Allow-Origin: * ← Server\nBrowser → POST /api/data → Server\n```\n\n**Нужные заголовки сервера:**\n```\nAccess-Control-Allow-Origin: https://mysite.com\nAccess-Control-Allow-Methods: GET, POST\nAccess-Control-Allow-Headers: Content-Type\n```\n\nCORS — защита браузера, не сервера. curl не соблюдает CORS.',
    answerEn: '**CORS (Cross-Origin Resource Sharing)** — browser mechanism controlling requests between different origins (origin = protocol + host + port).\n\n**Preflight request** — browser sends OPTIONS before the real request if:\n- Method is not GET/POST/HEAD\n- Non-standard headers\n- Content-Type is not simple\n\n```\nBrowser → OPTIONS /api/data → Server\nBrowser ← Access-Control-Allow-Origin: * ← Server\nBrowser → POST /api/data → Server\n```\n\n**Required server headers:**\n```\nAccess-Control-Allow-Origin: https://mysite.com\nAccess-Control-Allow-Methods: GET, POST\nAccess-Control-Allow-Headers: Content-Type\n```\n\nCORS is a browser protection, not a server one. curl ignores CORS.',
    tags: ['cors', 'security', 'http', 'preflight'],
    order: 4,
  },
  {
    id: 'browser-005',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое reflow и repaint? Как их минимизировать?',
    questionEn: 'What are reflow and repaint? How to minimize them?',
    answerRu: '**Reflow (layout)** — пересчёт геометрии элементов (дорого!). Вызывается:\n- Изменением размеров/позиций\n- Добавлением/удалением DOM-элементов\n- Чтением layout-свойств (offsetWidth, getBoundingClientRect)\n\n**Repaint** — перерисовка пикселей без изменения геометрии (дешевле).\n\n**Как минимизировать:**\n```js\n// ❌ Плохо — читаем и пишем поочерёдно (layout thrashing)\nfor (const el of elements) {\n  el.style.width = el.offsetWidth + 10 + "px";\n}\n\n// ✅ Хорошо — сначала все чтения, потом все записи\nconst widths = elements.map(el => el.offsetWidth);\nelements.forEach((el, i) => {\n  el.style.width = widths[i] + 10 + "px";\n});\n```\n\nИспользуй `transform` и `opacity` — они не вызывают reflow.',
    answerEn: '**Reflow (layout)** — recalculation of element geometry (expensive!). Triggered by:\n- Size/position changes\n- Adding/removing DOM elements\n- Reading layout properties (offsetWidth, getBoundingClientRect)\n\n**Repaint** — redrawing pixels without geometry changes (cheaper).\n\n**How to minimize:**\n```js\n// ❌ Bad — interleaved reads/writes (layout thrashing)\nfor (const el of elements) {\n  el.style.width = el.offsetWidth + 10 + "px";\n}\n\n// ✅ Good — batch reads first, then writes\nconst widths = elements.map(el => el.offsetWidth);\nelements.forEach((el, i) => {\n  el.style.width = widths[i] + 10 + "px";\n});\n```\n\nUse `transform` and `opacity` — they don\'t trigger reflow.',
    tags: ['reflow', 'repaint', 'performance', 'rendering'],
    order: 5,
  },
];
