import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'css-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['specificity'],
    questionRu: 'Как работает специфичность в CSS?',
    questionEn: 'How does specificity work in CSS?',
    answerRu: '**Специфичность** определяет, какое правило применяется при конфликте.\n\nУровни (от высшего к низшему):\n- `#id` — высший\n- `.class`, `[attr]`, `:hover` — средний\n- `div`, `::before` — низший\n\n**Inline-стили** перебивают все селекторы.\n\n`!important` перебивает всё.',
    answerEn: '**Specificity** determines which rule is applied when there is a conflict.\n\nTiers (highest to lowest):\n- `#id` — highest\n- `.class`, `[attr]`, `:hover` — medium\n- `div`, `::before` — lowest\n\n**Inline styles** override all selectors.\n\n`!important` overrides everything.',
  },
  {
    id: 'css-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['specificity'],
    questionRu: 'Что такое каскад в CSS и как определяется итоговый стиль?',
    questionEn: 'What is the CSS cascade and how is the final style determined?',
    answerRu: '**Каскад** — алгоритм разрешения конфликтов стилей.\n\nПорядок приоритета:\n- `!important`\n- специфичность селектора\n- порядок появления в коде (последнее побеждает)\n\nИсточники по приоритету:\n- браузерные стили\n- пользовательские стили\n- авторские стили (наш CSS)',
    answerEn: 'The **cascade** is an algorithm for resolving style conflicts.\n\nPriority order:\n- `!important`\n- selector specificity\n- order of appearance in the code (last one wins)\n\nSources by priority:\n- browser styles\n- user styles\n- author styles (our CSS)',
  },
  {
    id: 'css-003',
    difficulty: 'EASY',
    order: 3,
    tags: ['specificity'],
    questionRu: 'Что такое наследование в CSS?',
    questionEn: 'What is inheritance in CSS?',
    answerRu: 'Некоторые свойства автоматически наследуются от родителя:\n- `color`\n- `font-*`\n- `line-height`\n- `text-align`\n\nНе наследуются:\n- `margin`\n- `padding`\n- `border`\n- `background`\n\nКлючевые слова управления:\n- `inherit` — принудительно наследовать\n- `initial` — сбросить к дефолту\n- `unset` — `inherit` если наследуемое, иначе `initial`',
    answerEn: 'Some properties are automatically inherited from the parent:\n- `color`\n- `font-*`\n- `line-height`\n- `text-align`\n\nNot inherited:\n- `margin`\n- `padding`\n- `border`\n- `background`\n\nControl keywords:\n- `inherit` — force inheritance\n- `initial` — reset to default\n- `unset` — `inherit` if the property is inheritable, otherwise `initial`',
  },
  {
    id: 'css-004',
    difficulty: 'EASY',
    order: 4,
    tags: ['specificity'],
    questionRu: 'В чём проблема !important и когда его допустимо использовать?',
    questionEn: 'What is the problem with !important and when is it acceptable to use it?',
    answerRu: '`!important` нарушает естественный каскад, делает код хрупким и трудно переопределяемым. Создаёт **гонку `!important`**.\n\nДопустимые случаи:\n- утилитарные классы: `.hidden { display: none !important }`\n- переопределение сторонних стилей, которые нельзя изменить\n- стили доступности',
    answerEn: '`!important` breaks the natural cascade, makes the code brittle and hard to override. It creates an **`!important` arms race**.\n\nAcceptable use cases:\n- utility classes: `.hidden { display: none !important }`\n- overriding third-party styles that cannot be changed\n- accessibility styles',
  },
  {
    id: 'css-005',
    difficulty: 'EASY',
    order: 5,
    tags: ['specificity'],
    questionRu: 'Что такое CSS-переменные (custom properties)?',
    questionEn: 'What are CSS variables (custom properties)?',
    answerRu: '**CSS-переменные** объявляются через `--name: value` и используются через `var(--name)`.\n\nОсобенности:\n- каскадируются и наследуются как обычные свойства\n- можно переопределять в медиазапросах и на уровне элемента\n\nОтличие от переменных препроцессора: работают в **runtime**, доступны из JS.',
    answerEn: '**CSS variables** are declared with `--name: value` and used with `var(--name)`.\n\nKey traits:\n- cascade and inherit like regular properties\n- can be overridden in media queries and at the element level\n\nUnlike preprocessor variables, they work at **runtime** and are accessible from JS.',
  },
  {
    id: 'css-006',
    difficulty: 'HARD',
    order: 6,
    tags: ['specificity'],
    questionRu: 'Что такое CSS-слои (@layer)?',
    questionEn: 'What are CSS layers (@layer)?',
    answerRu: '`@layer` позволяет явно управлять приоритетом групп стилей.\n\nСтили в слое с меньшим приоритетом не перебивают слой с большим, даже при высокой специфичности.\n\nПример: `@layer base, components, utilities` — `utilities` всегда победит `base`.',
    answerEn: '`@layer` lets you explicitly control the priority of groups of styles.\n\nStyles in a lower-priority layer cannot override a higher-priority layer, even with higher specificity.\n\nExample: `@layer base, components, utilities` — `utilities` will always win over `base`.',
  },
  {
    id: 'css-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['box-model'],
    questionRu: 'Что такое блочная модель (box model)?',
    questionEn: 'What is the box model?',
    answerRu: 'Каждый элемент — прямоугольник из слоёв (от внутреннего к внешнему):\n- `content`\n- `padding`\n- `border`\n- `margin`\n\n`box-sizing` управляет тем, что входит в `width`:\n- По умолчанию (`content-box`): `width` задаёт только `content`\n- С `box-sizing: border-box`: `width` включает `padding` и `border`\n\n`border-box` предпочтителен и обычно задаётся глобально через `*`, `*::before`, `*::after`.',
    answerEn: 'Every element is a rectangle composed of layers (from innermost to outermost):\n- `content`\n- `padding`\n- `border`\n- `margin`\n\n`box-sizing` controls what is included in `width`:\n- By default (`content-box`): `width` sets only the `content` area\n- With `box-sizing: border-box`: `width` includes `padding` and `border`\n\n`border-box` is preferred and is usually set globally via `*`, `*::before`, `*::after`.',
  },
  {
    id: 'css-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['box-model'],
    questionRu: 'Что такое margin collapsing?',
    questionEn: 'What is margin collapsing?',
    answerRu: '**Схлопывание margin** — вертикальные `margin` соседних блоков и пары родитель/первый ребёнок объединяются в один (берётся максимальный).\n\nНе происходит для:\n- `flex`/`grid` контейнеров\n- элементов с `overflow`, отличным от `visible`\n- `inline-block`\n\nГоризонтальный `margin` никогда не схлопывается.',
    answerEn: '**Margin collapsing** — the vertical `margin` of adjacent blocks and parent/first-child pairs collapse into one (the larger value is used).\n\nDoes not occur for:\n- `flex`/`grid` containers\n- elements with `overflow` other than `visible`\n- `inline-block`\n\nHorizontal `margin` never collapses.',
  },
  {
    id: 'css-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['box-model'],
    questionRu: 'Как работают position: relative, absolute, fixed, sticky?',
    questionEn: 'How do position: relative, absolute, fixed, and sticky work?',
    answerRu: '- `position: relative` — смещение от нормального положения, остаётся в потоке\n- `position: absolute` — позиционируется относительно ближайшего positioned предка, уходит из потока\n- `position: fixed` — относительно viewport, не скроллится\n- `position: sticky` — ведёт себя как `relative` пока не достигнет порога `top`/`left`, затем как `fixed`',
    answerEn: '- `position: relative` — offset from its normal position, stays in the flow\n- `position: absolute` — positioned relative to the nearest positioned ancestor, removed from the flow\n- `position: fixed` — relative to the viewport, does not scroll\n- `position: sticky` — acts like `relative` until it reaches the `top`/`left` threshold, then behaves like `fixed`',
  },
  {
    id: 'css-010',
    difficulty: 'HARD',
    order: 10,
    tags: ['box-model'],
    questionRu: 'Что такое stacking context и как работает z-index?',
    questionEn: 'What is a stacking context and how does z-index work?',
    answerRu: '**Stacking context** — локальный контекст наложения слоёв. `z-index` работает только между элементами одного контекста.\n\nСоздаётся при:\n- `position` + `z-index` не `auto`\n- `opacity` < `1`\n- `transform`\n- `filter`\n- `isolation: isolate`\n\nЭлемент с `z-index: 9999` внутри контекста с `z-index: 1` будет **ПОД** элементом с `z-index: 2` снаружи.',
    answerEn: 'A **stacking context** is a local layering context. `z-index` only works between elements within the same context.\n\nCreated by:\n- `position` + `z-index` other than `auto`\n- `opacity` < `1`\n- `transform`\n- `filter`\n- `isolation: isolate`\n\nAn element with `z-index: 9999` inside a context with `z-index: 1` will be **BELOW** an element with `z-index: 2` outside it.',
  },
  {
    id: 'css-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['box-model'],
    questionRu: 'В чём разница между display: none, visibility: hidden и opacity: 0?',
    questionEn: 'What is the difference between display: none, visibility: hidden, and opacity: 0?',
    answerRu: '- `display: none` — элемент удалён из потока, не занимает место, недоступен скринридерам и событиям\n- `visibility: hidden` — место сохраняется, скрыт визуально, недоступен скринридерам\n- `opacity: 0` — полностью прозрачен, место сохраняется, остаётся кликабельным и доступным скринридерам',
    answerEn: '- `display: none` — the element is removed from the flow, takes up no space, inaccessible to screen readers and events\n- `visibility: hidden` — space is preserved, visually hidden, inaccessible to screen readers\n- `opacity: 0` — fully transparent, space is preserved, remains clickable and accessible to screen readers',
  },
  {
    id: 'css-012',
    difficulty: 'EASY',
    order: 12,
    tags: ['box-model'],
    questionRu: 'Как центрировать элемент по горизонтали и вертикали?',
    questionEn: 'How do you center an element horizontally and vertically?',
    answerRu: '**Flexbox:** родитель `display: flex; justify-content: center; align-items: center`\n\n**Grid:** родитель `display: grid; place-items: center`\n\n**Абсолютное позиционирование:** `position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%)`\n\nДля блочного элемента по горизонтали: `margin: 0 auto` с заданной шириной.',
    answerEn: '**Flexbox:** parent `display: flex; justify-content: center; align-items: center`\n\n**Grid:** parent `display: grid; place-items: center`\n\n**Absolute positioning:** `position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%)`\n\nFor horizontal centering of a block element: `margin: 0 auto` with a defined width.',
  },
  {
    id: 'css-013',
    difficulty: 'HARD',
    order: 13,
    tags: ['box-model'],
    questionRu: 'Что такое BFC (Block Formatting Context)?',
    questionEn: 'What is a BFC (Block Formatting Context)?',
    answerRu: '**BFC** — независимый контейнер со своими правилами раскладки.\n\nВнутри BFC:\n- `margin` не схлопываются с внешними\n- `float` содержится внутри контейнера\n\nСоздаётся при:\n- `overflow`, отличном от `visible`\n- `display: flow-root` (чистый способ)\n- `flex`/`grid` контейнере\n- `position: absolute` / `fixed`',
    answerEn: 'A **BFC** is an independent container with its own layout rules.\n\nInside a BFC:\n- margins do not collapse with outside margins\n- floats are contained within the container\n\nCreated by:\n- `overflow` other than `visible`\n- `display: flow-root` (the clean way)\n- `flex`/`grid` container\n- `position: absolute` / `fixed`',
  },
  {
    id: 'css-014',
    difficulty: 'EASY',
    order: 14,
    tags: ['flexbox'],
    questionRu: 'Что такое Flexbox и когда его использовать?',
    questionEn: 'What is Flexbox and when should you use it?',
    answerRu: '**Flexbox** — одномерная система раскладки (главная ось + поперечная).\n\nИдеален для:\n- навигации\n- выравнивания элементов в строку или колонку\n- равномерного распределения пространства\n- центрирования\n\nДля двумерных раскладок (строки и колонки одновременно) предпочтительнее **Grid**.',
    answerEn: '**Flexbox** is a one-dimensional layout system (main axis + cross axis).\n\nIdeal for:\n- navigation\n- aligning items in a row or column\n- distributing space evenly\n- centering\n\nFor two-dimensional layouts (rows and columns simultaneously), **Grid** is preferable.',
  },
  {
    id: 'css-015',
    difficulty: 'EASY',
    order: 15,
    tags: ['flexbox'],
    questionRu: 'В чём разница между justify-content и align-items?',
    questionEn: 'What is the difference between justify-content and align-items?',
    answerRu: '`justify-content` — выравнивание по **главной оси** (горизонтальной по умолчанию):\n- `flex-start`\n- `flex-end`\n- `center`\n- `space-between`\n- `space-around`\n\n`align-items` — выравнивание по **поперечной оси** (вертикальной):\n- `stretch`\n- `flex-start`\n- `flex-end`\n- `center`\n- `baseline`\n\nПри `flex-direction: column` оси меняются местами.',
    answerEn: '`justify-content` — alignment along the **main axis** (horizontal by default):\n- `flex-start`\n- `flex-end`\n- `center`\n- `space-between`\n- `space-around`\n\n`align-items` — alignment along the **cross axis** (vertical):\n- `stretch`\n- `flex-start`\n- `flex-end`\n- `center`\n- `baseline`\n\nWith `flex-direction: column`, the axes are swapped.',
  },
  {
    id: 'css-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['flexbox'],
    questionRu: 'Что делают flex-grow, flex-shrink и flex-basis?',
    questionEn: 'What do flex-grow, flex-shrink, and flex-basis do?',
    answerRu: '- `flex-basis` — базовый размер элемента до распределения пространства (аналог `width`)\n- `flex-grow` — коэффициент роста при наличии свободного места (`0` — не растёт)\n- `flex-shrink` — коэффициент сжатия при нехватке места (`0` — не сжимается)\n\nШортханд: `flex: 1` = `flex: 1 1 0`',
    answerEn: '- `flex-basis` — the base size of the item before space is distributed (similar to `width`)\n- `flex-grow` — the growth factor when free space is available (`0` — does not grow)\n- `flex-shrink` — the shrink factor when there is not enough space (`0` — does not shrink)\n\nShorthand: `flex: 1` = `flex: 1 1 0`',
  },
  {
    id: 'css-017',
    difficulty: 'EASY',
    order: 17,
    tags: ['flexbox'],
    questionRu: 'В чём разница между align-items и align-self?',
    questionEn: 'What is the difference between align-items and align-self?',
    answerRu: '- `align-items` — задаётся на **контейнере**, применяется ко всем flex-элементам\n- `align-self` — задаётся на **конкретном элементе**, переопределяет `align-items` для него\n\nЗначения те же:\n- `auto`\n- `flex-start`\n- `flex-end`\n- `center`\n- `stretch`\n- `baseline`',
    answerEn: '- `align-items` — set on the **container**, applies to all flex items\n- `align-self` — set on a **specific item**, overrides `align-items` for that item\n\nThe values are the same:\n- `auto`\n- `flex-start`\n- `flex-end`\n- `center`\n- `stretch`\n- `baseline`',
  },
  {
    id: 'css-018',
    difficulty: 'EASY',
    order: 18,
    tags: ['flexbox'],
    questionRu: 'Что такое flex-wrap и когда его использовать?',
    questionEn: 'What is flex-wrap and when should you use it?',
    answerRu: 'Значения `flex-wrap`:\n- `nowrap` (по умолчанию) — все элементы в одну строку, могут выходить за пределы\n- `wrap` — переносит на следующую строку при нехватке места\n- `wrap-reverse` — переносит в обратном направлении\n\n`align-content` управляет многострочным выравниванием при `wrap`.',
    answerEn: 'Values of `flex-wrap`:\n- `nowrap` (default) — all items in one line, can overflow\n- `wrap` — wraps to the next line when there is not enough space\n- `wrap-reverse` — wraps in the reverse direction\n\n`align-content` controls multi-line alignment when wrapping.',
  },
  {
    id: 'css-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['flexbox'],
    questionRu: 'Как работает order во Flexbox?',
    questionEn: 'How does order work in Flexbox?',
    answerRu: '`order` изменяет **визуальный порядок** flex-элементов без изменения DOM.\n\n- Значение по умолчанию: `0`\n- Элементы с меньшим `order` идут первыми\n- Отрицательные значения ставят элемент в начало\n\n**Важно:** порядок для скринридеров и Tab-навигации остаётся по DOM.',
    answerEn: '`order` changes the **visual order** of flex items without modifying the DOM.\n\n- Default value: `0`\n- Items with a lower `order` value come first\n- Negative values place an item at the beginning\n\n**Important:** the order for screen readers and Tab navigation remains as it is in the DOM.',
  },
  {
    id: 'css-020',
    difficulty: 'EASY',
    order: 20,
    tags: ['grid'],
    questionRu: 'Что такое CSS Grid и чем отличается от Flexbox?',
    questionEn: 'What is CSS Grid and how does it differ from Flexbox?',
    answerRu: '**Grid** — двумерная система раскладки (строки и колонки одновременно).\n\n**Flexbox** — одномерная (либо строка, либо колонка).\n\n**Grid** лучше для:\n- общей раскладки страницы\n- сложных сеток\n- выравнивания в двух измерениях\n\n**Flexbox** лучше для:\n- компонентов\n- навигации\n- одномерных списков',
    answerEn: '**Grid** is a two-dimensional layout system (rows and columns simultaneously).\n\n**Flexbox** is one-dimensional (either a row or a column).\n\n**Grid** is better for:\n- overall page layout\n- complex grids\n- two-dimensional alignment\n\n**Flexbox** is better for:\n- components\n- navigation\n- one-dimensional lists',
  },
  {
    id: 'css-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['grid'],
    questionRu: 'Как задать колонки и строки в Grid?',
    questionEn: 'How do you define columns and rows in Grid?',
    answerRu: '`grid-template-columns`:\n- `200px 1fr 1fr` — три колонки\n- `repeat(3, 1fr)` — три равные колонки\n- `repeat(auto-fill, minmax(200px, 1fr))` — адаптивная сетка\n\n`grid-template-rows` работает аналогично для строк.\n\n`fr` — доля свободного пространства. `auto-fill`/`auto-fit` + `minmax` используются для адаптивных сеток.',
    answerEn: '`grid-template-columns`:\n- `200px 1fr 1fr` — three columns\n- `repeat(3, 1fr)` — three equal columns\n- `repeat(auto-fill, minmax(200px, 1fr))` — responsive grid\n\n`grid-template-rows` works the same way for rows.\n\n`fr` — a fraction of the available space. `auto-fill`/`auto-fit` + `minmax` are used for responsive grids.',
  },
  {
    id: 'css-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['grid'],
    questionRu: 'Что такое grid-area и как размещать элементы?',
    questionEn: 'What is grid-area and how do you place elements?',
    answerRu: '- `grid-column: 1 / 3` — элемент занимает колонки с 1 по 3\n- `grid-row: 1 / 2`\n- Шортханд `grid-area: row-start / col-start / row-end / col-end`\n\n**Именованные зоны:** `grid-template-areas` задаёт имена зон, `grid-area: name` назначает элемент в зону.',
    answerEn: '- `grid-column: 1 / 3` — the element spans columns 1 through 3\n- `grid-row: 1 / 2`\n- Shorthand `grid-area: row-start / col-start / row-end / col-end`\n\n**Named areas:** `grid-template-areas` defines area names, `grid-area: name` assigns an element to an area.',
  },
  {
    id: 'css-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['grid'],
    questionRu: 'В чём разница между auto-fill и auto-fit?',
    questionEn: 'What is the difference between auto-fill and auto-fit?',
    answerRu: 'Оба создают столько колонок, сколько помещается.\n\n- `auto-fill` — создаёт пустые колонки если элементов мало, сетка сохраняет структуру\n- `auto-fit` — схлопывает пустые колонки, элементы растягиваются на всю ширину\n\nРазница заметна когда элементов меньше, чем колонок.',
    answerEn: 'Both create as many columns as will fit.\n\n- `auto-fill` — creates empty columns when there are few items, the grid preserves its structure\n- `auto-fit` — collapses empty columns, items stretch to fill the full width\n\nThe difference is visible when there are fewer items than columns.',
  },
  {
    id: 'css-024',
    difficulty: 'EASY',
    order: 24,
    tags: ['grid'],
    questionRu: 'Что такое gap (grid-gap)?',
    questionEn: 'What is gap (grid-gap)?',
    answerRu: '`gap` (ранее `grid-gap`) задаёт отступы между ячейками:\n- `gap: 16px` — одинаковые отступы для строк и колонок\n- `gap: 8px 16px` — строки и колонки раздельно\n\nПреимущество над `margin`: отступ только **между** ячейками, не по краям.\n\nРаботает и во **Flexbox**.',
    answerEn: '`gap` (formerly `grid-gap`) sets spacing between cells:\n- `gap: 16px` — equal spacing for rows and columns\n- `gap: 8px 16px` — rows and columns separately\n\nAdvantage over `margin`: spacing only **between** cells, not on the edges.\n\nAlso works in **Flexbox**.',
  },
  {
    id: 'css-025',
    difficulty: 'HARD',
    order: 25,
    tags: ['grid'],
    questionRu: 'Что такое implicit и explicit grid?',
    questionEn: 'What are implicit and explicit grids?',
    answerRu: '- **Explicit grid** — явно заданные строки/колонки через `grid-template-*`\n- **Implicit grid** — автоматически создаётся для элементов, выходящих за пределы явной сетки\n\n`grid-auto-rows` и `grid-auto-columns` задают размер неявных треков.\n\n`grid-auto-flow` управляет направлением авторазмещения.',
    answerEn: '- **Explicit grid** — rows/columns explicitly defined via `grid-template-*`\n- **Implicit grid** — automatically created for items that fall outside the explicit grid\n\n`grid-auto-rows` and `grid-auto-columns` set the size of implicit tracks.\n\n`grid-auto-flow` controls the direction of auto-placement.',
  },
  {
    id: 'css-026',
    difficulty: 'EASY',
    order: 26,
    tags: ['animations'],
    questionRu: 'В чём разница между transition и animation?',
    questionEn: 'What is the difference between transition and animation?',
    answerRu: '**`transition`** — плавный переход между двумя состояниями при изменении свойства (`hover`, класс). Простой, декларативный.\n\n**`animation`** с `@keyframes` — независимая анимация с полным контролем:\n- несколько кадров\n- повторение, направление, задержка\n\nДля сложных сценариев нужна `animation`.',
    answerEn: '**`transition`** — a smooth change between two states when a property changes (`hover`, class). Simple and declarative.\n\n**`animation`** with `@keyframes` — an independent animation with full control:\n- multiple frames\n- repetition, direction, delay\n\nFor complex scenarios, `animation` is needed.',
  },
  {
    id: 'css-027',
    difficulty: 'MEDIUM',
    order: 27,
    tags: ['animations'],
    questionRu: 'Какие CSS-свойства безопасно анимировать для производительности?',
    questionEn: 'Which CSS properties are safe to animate for performance?',
    answerRu: '**Дешёвые** (не вызывают reflow, выполняются на GPU):\n- `transform` (в т.ч. `translate`, `scale`, `rotate`)\n- `opacity`\n\n**Дорогие** (вызывают reflow всей страницы):\n- `width`\n- `height`\n- `top`\n- `left`\n- `margin`\n- `padding`\n\nПравило: анимировать только `transform` и `opacity`.',
    answerEn: '**Cheap** (do not trigger reflow, run on the GPU):\n- `transform` (including `translate`, `scale`, `rotate`)\n- `opacity`\n\n**Expensive** (trigger a reflow of the entire page):\n- `width`\n- `height`\n- `top`\n- `left`\n- `margin`\n- `padding`\n\nRule of thumb: only animate `transform` and `opacity`.',
  },
  {
    id: 'css-028',
    difficulty: 'MEDIUM',
    order: 28,
    tags: ['animations'],
    questionRu: 'Что такое will-change и когда использовать?',
    questionEn: 'What is will-change and when should you use it?',
    answerRu: '`will-change` подсказывает браузеру заранее оптимизировать элемент для анимации.\n\n`will-change: transform` создаёт compositor layer — ускоряет анимации, но **потребляет память**.\n\nПравила использования:\n- только для действительно анимируемых элементов\n- убирать после завершения анимации\n- не применять ко всему подряд',
    answerEn: '`will-change` hints to the browser to optimize an element for animation in advance.\n\n`will-change: transform` creates a compositor layer — speeds up animations but **consumes memory**.\n\nUsage rules:\n- only for elements that are actually being animated\n- remove it after the animation completes\n- do not apply it indiscriminately',
  },
  {
    id: 'css-029',
    difficulty: 'MEDIUM',
    order: 29,
    tags: ['animations'],
    questionRu: 'Что такое prefers-reduced-motion?',
    questionEn: 'What is prefers-reduced-motion?',
    answerRu: '`@media (prefers-reduced-motion: reduce)` — медиазапрос для пользователей, отключивших анимации в системе (вестибулярные нарушения, эпилепсия).\n\nВнутри: отключать или упрощать анимации.\n\n**Best practice:** писать анимации по умолчанию, убирать в `prefers-reduced-motion`.',
    answerEn: '`@media (prefers-reduced-motion: reduce)` is a media query for users who have disabled animations in their system settings (vestibular disorders, epilepsy).\n\nInside it: disable or simplify animations.\n\n**Best practice:** write animations by default and disable them within `prefers-reduced-motion`.',
  },
  {
    id: 'css-030',
    difficulty: 'MEDIUM',
    order: 30,
    tags: ['animations'],
    questionRu: 'Как работает animation-fill-mode?',
    questionEn: 'How does animation-fill-mode work?',
    answerRu: '`animation-fill-mode` определяет стили элемента до и после анимации:\n\n- `none` — стили из `@keyframes` не применяются вне анимации\n- `forwards` — после завершения сохраняет стили последнего кадра\n- `backwards` — применяет стили первого кадра во время задержки\n- `both` — комбинация `forwards` и `backwards`',
    answerEn: '`animation-fill-mode` defines the styles of an element before and after the animation:\n\n- `none` — styles from `@keyframes` are not applied outside the animation\n- `forwards` — after completion, retains the styles of the last keyframe\n- `backwards` — applies the styles of the first keyframe during the delay\n- `both` — a combination of `forwards` and `backwards`',
  },
  {
    id: 'css-031',
    difficulty: 'MEDIUM',
    order: 31,
    tags: ['methodologies'],
    questionRu: 'Чем CSS-переменные лучше переменных Sass/Less?',
    questionEn: 'How are CSS variables better than Sass/Less variables?',
    answerRu: '**CSS-переменные** работают в **runtime**:\n- меняются через JS\n- каскадируются\n- переопределяются в медиазапросах и на уровне элемента\n\n**Sass/Less** переменные — только **compile-time**, статичны в итоговом CSS.\n\nCSS-переменные идеальны для тем оформления и динамических изменений.',
    answerEn: '**CSS variables** work at **runtime**:\n- can be changed via JS\n- cascade\n- can be overridden in media queries and at the element level\n\n**Sass/Less** variables are **compile-time** only and static in the output CSS.\n\nCSS variables are ideal for theming and dynamic changes.',
  },
  {
    id: 'css-032',
    difficulty: 'EASY',
    order: 32,
    tags: ['methodologies'],
    questionRu: 'Что такое методология БЭМ?',
    questionEn: 'What is the BEM methodology?',
    answerRu: '**БЭМ** (Блок-Элемент-Модификатор) — соглашение именования классов:\n- `.block` — независимый компонент\n- `.block__element` — часть блока (`.card__title`)\n- `.block--modifier` — вариация (`.card--featured`)\n\nПредотвращает конфликты стилей и облегчает поддержку.',
    answerEn: '**BEM** (Block-Element-Modifier) is a class naming convention:\n- `.block` — an independent component\n- `.block__element` — part of a block (`.card__title`)\n- `.block--modifier` — a variation (`.card--featured`)\n\nIt prevents style conflicts and makes maintenance easier.',
  },
  {
    id: 'css-033',
    difficulty: 'MEDIUM',
    order: 33,
    tags: ['methodologies'],
    questionRu: 'Что такое CSS Modules?',
    questionEn: 'What are CSS Modules?',
    answerRu: '**CSS Modules** — инструмент сборки, делающий классы локальными по умолчанию.\n\nИмена классов хешируются при компиляции: `.button` → `.Button_button__abc12`.\n\nИмпортируется как объект:\n```\nimport s from \'./Button.module.css\';\nclassName={s.button}\n```\n\nПолностью решает проблему конфликтов имён.',
    answerEn: '**CSS Modules** is a build tool that makes class names local by default.\n\nClass names are hashed at compile time: `.button` → `.Button_button__abc12`.\n\nImported as an object:\n```\nimport s from \'./Button.module.css\';\nclassName={s.button}\n```\n\nCompletely solves the naming conflict problem.',
  },
  {
    id: 'css-034',
    difficulty: 'MEDIUM',
    order: 34,
    tags: ['methodologies'],
    questionRu: 'Что такое CSS-in-JS и каковы его плюсы и минусы?',
    questionEn: 'What is CSS-in-JS and what are its pros and cons?',
    answerRu: '**CSS-in-JS** (`styled-components`, `Emotion`) — стили прямо в JS.\n\nПлюсы:\n- полная изоляция\n- динамические стили через props\n- автоудаление неиспользуемых стилей\n\nМинусы:\n- runtime overhead\n- увеличение JS-бандла\n- сложность SSR\n- потеря привычных инструментов браузера',
    answerEn: '**CSS-in-JS** (`styled-components`, `Emotion`) — styles written directly in JS.\n\nPros:\n- full isolation\n- dynamic styles via props\n- automatic removal of unused styles\n\nCons:\n- runtime overhead\n- increased JS bundle size\n- SSR complexity\n- loss of familiar browser tooling',
  },
  {
    id: 'css-035',
    difficulty: 'EASY',
    order: 35,
    tags: ['methodologies'],
    questionRu: 'Что такое utility-first CSS (Tailwind)?',
    questionEn: 'What is utility-first CSS (Tailwind)?',
    answerRu: '**Utility-first** — подход, где вместо семантических классов используются утилитарные:\n`class="flex items-center gap-4 p-2"`\n\nПлюсы:\n- нет придумывания имён\n- нет роста CSS-файла\n- консистентность\n\nМинусы:\n- длинные `className`\n- нужна привычка\n\n**Tailwind** — самый популярный фреймворк.',
    answerEn: '**Utility-first** is an approach where utility classes are used instead of semantic ones:\n`class="flex items-center gap-4 p-2"`\n\nPros:\n- no need to invent names\n- no CSS file growth\n- consistency\n\nCons:\n- long `className` values\n- requires getting used to\n\n**Tailwind** is the most popular framework.',
  },
];
