import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'css-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['specificity'],
    questionRu: 'Как работает специфичность в CSS?',
    questionEn: 'Как работает специфичность в CSS?',
    answerRu: 'Специфичность определяет, какое правило применяется при конфликте. Считается по уровням: ID (#id) — высший, классы/атрибуты/псевдоклассы (.class, [attr], :hover) — средний, теги/псевдоэлементы (div, ::before) — низший. Inline-стили перебивают все селекторы. !important перебивает всё.',
    answerEn: 'Специфичность определяет, какое правило применяется при конфликте. Считается по уровням: ID (#id) — высший, классы/атрибуты/псевдоклассы (.class, [attr], :hover) — средний, теги/псевдоэлементы (div, ::before) — низший. Inline-стили перебивают все селекторы. !important перебивает всё.',
  },
  {
    id: 'css-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['specificity'],
    questionRu: 'Что такое каскад в CSS и как определяется итоговый стиль?',
    questionEn: 'Что такое каскад в CSS и как определяется итоговый стиль?',
    answerRu: 'Каскад — алгоритм разрешения конфликтов стилей. Порядок приоритета: 1) !important, 2) специфичность селектора, 3) порядок появления в коде (последнее побеждает). Источники по приоритету: браузерные стили → пользовательские → авторские (наш CSS).',
    answerEn: 'Каскад — алгоритм разрешения конфликтов стилей. Порядок приоритета: 1) !important, 2) специфичность селектора, 3) порядок появления в коде (последнее побеждает). Источники по приоритету: браузерные стили → пользовательские → авторские (наш CSS).',
  },
  {
    id: 'css-003',
    difficulty: 'EASY',
    order: 3,
    tags: ['specificity'],
    questionRu: 'Что такое наследование в CSS?',
    questionEn: 'Что такое наследование в CSS?',
    answerRu: 'Некоторые свойства автоматически наследуются от родителя: color, font-*, line-height, text-align и др. Не наследуются: margin, padding, border, background. Управление: inherit — принудительно наследовать, initial — сбросить к дефолту, unset — inherit если наследуемое, иначе initial.',
    answerEn: 'Некоторые свойства автоматически наследуются от родителя: color, font-*, line-height, text-align и др. Не наследуются: margin, padding, border, background. Управление: inherit — принудительно наследовать, initial — сбросить к дефолту, unset — inherit если наследуемое, иначе initial.',
  },
  {
    id: 'css-004',
    difficulty: 'EASY',
    order: 4,
    tags: ['specificity'],
    questionRu: 'В чём проблема !important и когда его допустимо использовать?',
    questionEn: 'В чём проблема !important и когда его допустимо использовать?',
    answerRu: '!important нарушает естественный каскад, делает код хрупким и трудно переопределяемым. Создаёт гонку !important. Допустимые случаи: утилитарные классы (.hidden { display: none !important }), переопределение сторонних стилей которые нельзя изменить, стили доступности.',
    answerEn: '!important нарушает естественный каскад, делает код хрупким и трудно переопределяемым. Создаёт гонку !important. Допустимые случаи: утилитарные классы (.hidden { display: none !important }), переопределение сторонних стилей которые нельзя изменить, стили доступности.',
  },
  {
    id: 'css-005',
    difficulty: 'EASY',
    order: 5,
    tags: ['specificity'],
    questionRu: 'Что такое CSS-переменные (custom properties)?',
    questionEn: 'Что такое CSS-переменные (custom properties)?',
    answerRu: 'CSS-переменные объявляются через --name: value и используются через var(--name). Каскадируются и наследуются как обычные свойства. Можно переопределять в медиазапросах и на уровне элемента. Отличие от препроцессорных переменных: работают в runtime, доступны из JS.',
    answerEn: 'CSS-переменные объявляются через --name: value и используются через var(--name). Каскадируются и наследуются как обычные свойства. Можно переопределять в медиазапросах и на уровне элемента. Отличие от препроцессорных переменных: работают в runtime, доступны из JS.',
  },
  {
    id: 'css-006',
    difficulty: 'HARD',
    order: 6,
    tags: ['specificity'],
    questionRu: 'Что такое CSS-слои (@layer)?',
    questionEn: 'Что такое CSS-слои (@layer)?',
    answerRu: '@layer позволяет явно управлять приоритетом групп стилей. Стили в слое с меньшим приоритетом не перебивают слой с большим, даже при высокой специфичности. Полезно для организации: @layer base, components, utilities — utilities всегда победит base.',
    answerEn: '@layer позволяет явно управлять приоритетом групп стилей. Стили в слое с меньшим приоритетом не перебивают слой с большим, даже при высокой специфичности. Полезно для организации: @layer base, components, utilities — utilities всегда победит base.',
  },
  {
    id: 'css-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['box-model'],
    questionRu: 'Что такое блочная модель (box model)?',
    questionEn: 'Что такое блочная модель (box model)?',
    answerRu: 'Каждый элемент — прямоугольник из: content → padding → border → margin. По умолчанию (content-box) width задаёт только content. С box-sizing: border-box — width включает padding и border. border-box предпочтителен и обычно задаётся глобально через *, *::before, *::after.',
    answerEn: 'Каждый элемент — прямоугольник из: content → padding → border → margin. По умолчанию (content-box) width задаёт только content. С box-sizing: border-box — width включает padding и border. border-box предпочтителен и обычно задаётся глобально через *, *::before, *::after.',
  },
  {
    id: 'css-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['box-model'],
    questionRu: 'Что такое margin collapsing?',
    questionEn: 'Что такое margin collapsing?',
    answerRu: 'Схлопывание margin — вертикальные margin соседних блоков и родитель/первый ребёнок объединяются в один (берётся максимальный). Не происходит для flex/grid контейнеров, элементов с overflow не visible, inline-block. Горизонтальный margin никогда не схлопывается.',
    answerEn: 'Схлопывание margin — вертикальные margin соседних блоков и родитель/первый ребёнок объединяются в один (берётся максимальный). Не происходит для flex/grid контейнеров, элементов с overflow не visible, inline-block. Горизонтальный margin никогда не схлопывается.',
  },
  {
    id: 'css-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['box-model'],
    questionRu: 'Как работают position: relative, absolute, fixed, sticky?',
    questionEn: 'Как работают position: relative, absolute, fixed, sticky?',
    answerRu: 'relative: смещение от нормального положения, остаётся в потоке. absolute: позиционируется относительно ближайшего positioned предка, уходит из потока. fixed: относительно viewport, не скроллится. sticky: relative пока не достигнет порога top/left, затем ведёт себя как fixed.',
    answerEn: 'relative: смещение от нормального положения, остаётся в потоке. absolute: позиционируется относительно ближайшего positioned предка, уходит из потока. fixed: относительно viewport, не скроллится. sticky: relative пока не достигнет порога top/left, затем ведёт себя как fixed.',
  },
  {
    id: 'css-010',
    difficulty: 'HARD',
    order: 10,
    tags: ['box-model'],
    questionRu: 'Что такое stacking context и как работает z-index?',
    questionEn: 'Что такое stacking context и как работает z-index?',
    answerRu: 'Stacking context — локальный контекст наложения слоёв. z-index работает только между элементами одного контекста. Создаётся при: position + z-index не auto, opacity < 1, transform, filter, isolation: isolate. Элемент с z-index:9999 внутри контекста с z-index:1 будет ПОД элементом с z-index:2 снаружи.',
    answerEn: 'Stacking context — локальный контекст наложения слоёв. z-index работает только между элементами одного контекста. Создаётся при: position + z-index не auto, opacity < 1, transform, filter, isolation: isolate. Элемент с z-index:9999 внутри контекста с z-index:1 будет ПОД элементом с z-index:2 снаружи.',
  },
  {
    id: 'css-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['box-model'],
    questionRu: 'В чём разница между display: none, visibility: hidden и opacity: 0?',
    questionEn: 'В чём разница между display: none, visibility: hidden и opacity: 0?',
    answerRu: 'display: none — элемент удалён из потока, не занимает место, недоступен скринридерам и событиям. visibility: hidden — место сохраняется, скрыт визуально, недоступен скринридерам. opacity: 0 — полностью прозрачен, место сохраняется, остаётся кликабельным и доступным скринридерам.',
    answerEn: 'display: none — элемент удалён из потока, не занимает место, недоступен скринридерам и событиям. visibility: hidden — место сохраняется, скрыт визуально, недоступен скринридерам. opacity: 0 — полностью прозрачен, место сохраняется, остаётся кликабельным и доступным скринридерам.',
  },
  {
    id: 'css-012',
    difficulty: 'EASY',
    order: 12,
    tags: ['box-model'],
    questionRu: 'Как центрировать элемент по горизонтали и вертикали?',
    questionEn: 'Как центрировать элемент по горизонтали и вертикали?',
    answerRu: 'Flexbox: родитель display:flex; justify-content:center; align-items:center. Grid: родитель display:grid; place-items:center. Абсолютное позиционирование: position:absolute; top:50%; left:50%; transform:translate(-50%,-50%). Для блочного элемента по горизонтали: margin: 0 auto с заданной шириной.',
    answerEn: 'Flexbox: родитель display:flex; justify-content:center; align-items:center. Grid: родитель display:grid; place-items:center. Абсолютное позиционирование: position:absolute; top:50%; left:50%; transform:translate(-50%,-50%). Для блочного элемента по горизонтали: margin: 0 auto с заданной шириной.',
  },
  {
    id: 'css-013',
    difficulty: 'HARD',
    order: 13,
    tags: ['box-model'],
    questionRu: 'Что такое BFC (Block Formatting Context)?',
    questionEn: 'Что такое BFC (Block Formatting Context)?',
    answerRu: 'BFC — независимый контейнер со своими правилами раскладки. Внутри BFC: margin не схлопываются с внешними, float содержится внутри контейнера. Создаётся при: overflow не visible, display: flow-root (чистый способ), flex/grid контейнер, position absolute/fixed.',
    answerEn: 'BFC — независимый контейнер со своими правилами раскладки. Внутри BFC: margin не схлопываются с внешними, float содержится внутри контейнера. Создаётся при: overflow не visible, display: flow-root (чистый способ), flex/grid контейнер, position absolute/fixed.',
  },
  {
    id: 'css-014',
    difficulty: 'EASY',
    order: 14,
    tags: ['flexbox'],
    questionRu: 'Что такое Flexbox и когда его использовать?',
    questionEn: 'Что такое Flexbox и когда его использовать?',
    answerRu: 'Flexbox — одномерная система раскладки (главная ось + поперечная). Идеален для: навигации, выравнивания элементов в строку или колонку, равномерного распределения пространства, центрирования. Для двумерных раскладок (строки и колонки одновременно) предпочтительнее Grid.',
    answerEn: 'Flexbox — одномерная система раскладки (главная ось + поперечная). Идеален для: навигации, выравнивания элементов в строку или колонку, равномерного распределения пространства, центрирования. Для двумерных раскладок (строки и колонки одновременно) предпочтительнее Grid.',
  },
  {
    id: 'css-015',
    difficulty: 'EASY',
    order: 15,
    tags: ['flexbox'],
    questionRu: 'В чём разница между justify-content и align-items?',
    questionEn: 'В чём разница между justify-content и align-items?',
    answerRu: 'justify-content управляет выравниванием по главной оси (по умолчанию горизонтальной): flex-start, flex-end, center, space-between, space-around. align-items — по поперечной оси (вертикальной): stretch, flex-start, flex-end, center, baseline. При flex-direction: column оси меняются местами.',
    answerEn: 'justify-content управляет выравниванием по главной оси (по умолчанию горизонтальной): flex-start, flex-end, center, space-between, space-around. align-items — по поперечной оси (вертикальной): stretch, flex-start, flex-end, center, baseline. При flex-direction: column оси меняются местами.',
  },
  {
    id: 'css-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['flexbox'],
    questionRu: 'Что делают flex-grow, flex-shrink и flex-basis?',
    questionEn: 'Что делают flex-grow, flex-shrink и flex-basis?',
    answerRu: 'flex-basis: базовый размер элемента до распределения пространства (аналог width). flex-grow: коэффициент роста при наличии свободного места (0 — не растёт). flex-shrink: коэффициент сжатия при нехватке места (0 — не сжимается). Shorthand: flex: 1 = flex: 1 1 0.',
    answerEn: 'flex-basis: базовый размер элемента до распределения пространства (аналог width). flex-grow: коэффициент роста при наличии свободного места (0 — не растёт). flex-shrink: коэффициент сжатия при нехватке места (0 — не сжимается). Shorthand: flex: 1 = flex: 1 1 0.',
  },
  {
    id: 'css-017',
    difficulty: 'EASY',
    order: 17,
    tags: ['flexbox'],
    questionRu: 'В чём разница между align-items и align-self?',
    questionEn: 'В чём разница между align-items и align-self?',
    answerRu: 'align-items задаётся на контейнере и применяется ко всем flex-элементам. align-self задаётся на конкретном элементе и переопределяет align-items для него. Значения те же: auto, flex-start, flex-end, center, stretch, baseline.',
    answerEn: 'align-items задаётся на контейнере и применяется ко всем flex-элементам. align-self задаётся на конкретном элементе и переопределяет align-items для него. Значения те же: auto, flex-start, flex-end, center, stretch, baseline.',
  },
  {
    id: 'css-018',
    difficulty: 'EASY',
    order: 18,
    tags: ['flexbox'],
    questionRu: 'Что такое flex-wrap и когда его использовать?',
    questionEn: 'Что такое flex-wrap и когда его использовать?',
    answerRu: 'flex-wrap: nowrap (по умолчанию) — все элементы в одну строку, могут выходить за пределы. wrap — переносит на следующую строку при нехватке места. wrap-reverse — переносит в обратном направлении. align-content управляет многострочным выравниванием при wrap.',
    answerEn: 'flex-wrap: nowrap (по умолчанию) — все элементы в одну строку, могут выходить за пределы. wrap — переносит на следующую строку при нехватке места. wrap-reverse — переносит в обратном направлении. align-content управляет многострочным выравниванием при wrap.',
  },
  {
    id: 'css-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['flexbox'],
    questionRu: 'Как работает order во Flexbox?',
    questionEn: 'Как работает order во Flexbox?',
    answerRu: 'order изменяет визуальный порядок flex-элементов без изменения DOM. Значение по умолчанию: 0. Элементы с меньшим order идут первыми. Отрицательные значения ставят элемент в начало. Важно: порядок для скринридеров и Tab-навигации остаётся по DOM.',
    answerEn: 'order изменяет визуальный порядок flex-элементов без изменения DOM. Значение по умолчанию: 0. Элементы с меньшим order идут первыми. Отрицательные значения ставят элемент в начало. Важно: порядок для скринридеров и Tab-навигации остаётся по DOM.',
  },
  {
    id: 'css-020',
    difficulty: 'EASY',
    order: 20,
    tags: ['grid'],
    questionRu: 'Что такое CSS Grid и чем отличается от Flexbox?',
    questionEn: 'Что такое CSS Grid и чем отличается от Flexbox?',
    answerRu: 'Grid — двумерная система раскладки (строки и колонки одновременно). Flexbox — одномерная (либо строка, либо колонка). Grid лучше для: общей раскладки страницы, сложных сеток, выравнивания в двух измерениях. Flexbox лучше для: компонентов, навигации, одномерных списков.',
    answerEn: 'Grid — двумерная система раскладки (строки и колонки одновременно). Flexbox — одномерная (либо строка, либо колонка). Grid лучше для: общей раскладки страницы, сложных сеток, выравнивания в двух измерениях. Flexbox лучше для: компонентов, навигации, одномерных списков.',
  },
  {
    id: 'css-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['grid'],
    questionRu: 'Как задать колонки и строки в Grid?',
    questionEn: 'Как задать колонки и строки в Grid?',
    answerRu: 'grid-template-columns: 200px 1fr 1fr — три колонки. repeat(3, 1fr) — три равные колонки. auto-fill/auto-fit с minmax для адаптивных сеток: repeat(auto-fill, minmax(200px, 1fr)). grid-template-rows аналогично для строк. fr — доля свободного пространства.',
    answerEn: 'grid-template-columns: 200px 1fr 1fr — три колонки. repeat(3, 1fr) — три равные колонки. auto-fill/auto-fit с minmax для адаптивных сеток: repeat(auto-fill, minmax(200px, 1fr)). grid-template-rows аналогично для строк. fr — доля свободного пространства.',
  },
  {
    id: 'css-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['grid'],
    questionRu: 'Что такое grid-area и как размещать элементы?',
    questionEn: 'Что такое grid-area и как размещать элементы?',
    answerRu: 'grid-column: 1 / 3 — элемент занимает колонки с 1 по 3. grid-row: 1 / 2. Shorthand grid-area: row-start / col-start / row-end / col-end. Именованные зоны: grid-template-areas задаёт имена зон, grid-area: name назначает элемент в зону.',
    answerEn: 'grid-column: 1 / 3 — элемент занимает колонки с 1 по 3. grid-row: 1 / 2. Shorthand grid-area: row-start / col-start / row-end / col-end. Именованные зоны: grid-template-areas задаёт имена зон, grid-area: name назначает элемент в зону.',
  },
  {
    id: 'css-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['grid'],
    questionRu: 'В чём разница между auto-fill и auto-fit?',
    questionEn: 'В чём разница между auto-fill и auto-fit?',
    answerRu: 'Оба создают столько колонок, сколько помещается. auto-fill: создаёт пустые колонки если элементов мало — сетка сохраняет структуру. auto-fit: схлопывает пустые колонки — элементы растягиваются на всю ширину. Разница заметна когда элементов меньше чем колонок.',
    answerEn: 'Оба создают столько колонок, сколько помещается. auto-fill: создаёт пустые колонки если элементов мало — сетка сохраняет структуру. auto-fit: схлопывает пустые колонки — элементы растягиваются на всю ширину. Разница заметна когда элементов меньше чем колонок.',
  },
  {
    id: 'css-024',
    difficulty: 'EASY',
    order: 24,
    tags: ['grid'],
    questionRu: 'Что такое gap (grid-gap)?',
    questionEn: 'Что такое gap (grid-gap)?',
    answerRu: 'gap (ранее grid-gap) задаёт отступы между ячейками: gap: 16px — и строки и колонки. gap: 8px 16px — строки и колонки раздельно. Преимущество над margin: отступ только между ячейками, не по краям. Работает и во Flexbox.',
    answerEn: 'gap (ранее grid-gap) задаёт отступы между ячейками: gap: 16px — и строки и колонки. gap: 8px 16px — строки и колонки раздельно. Преимущество над margin: отступ только между ячейками, не по краям. Работает и во Flexbox.',
  },
  {
    id: 'css-025',
    difficulty: 'HARD',
    order: 25,
    tags: ['grid'],
    questionRu: 'Что такое implicit и explicit grid?',
    questionEn: 'Что такое implicit и explicit grid?',
    answerRu: 'Explicit grid — явно заданные строки/колонки через grid-template-*. Implicit grid — автоматически создаётся для элементов, выходящих за пределы явной сетки. grid-auto-rows и grid-auto-columns задают размер неявных треков. grid-auto-flow управляет направлением авторазмещения.',
    answerEn: 'Explicit grid — явно заданные строки/колонки через grid-template-*. Implicit grid — автоматически создаётся для элементов, выходящих за пределы явной сетки. grid-auto-rows и grid-auto-columns задают размер неявных треков. grid-auto-flow управляет направлением авторазмещения.',
  },
  {
    id: 'css-026',
    difficulty: 'EASY',
    order: 26,
    tags: ['animations'],
    questionRu: 'В чём разница между transition и animation?',
    questionEn: 'В чём разница между transition и animation?',
    answerRu: 'transition: плавный переход между двумя состояниями при изменении свойства (hover, класс). Простой, декларативный. animation с @keyframes: независимая анимация с полным контролем — несколько кадров, повторение, направление, задержка. Для сложных сценариев нужна animation.',
    answerEn: 'transition: плавный переход между двумя состояниями при изменении свойства (hover, класс). Простой, декларативный. animation с @keyframes: независимая анимация с полным контролем — несколько кадров, повторение, направление, задержка. Для сложных сценариев нужна animation.',
  },
  {
    id: 'css-027',
    difficulty: 'MEDIUM',
    order: 27,
    tags: ['animations'],
    questionRu: 'Какие CSS-свойства безопасно анимировать для производительности?',
    questionEn: 'Какие CSS-свойства безопасно анимировать для производительности?',
    answerRu: 'Дешёвые для анимации (не вызывают reflow): transform (translate, scale, rotate) и opacity — выполняются на GPU, не затрагивают layout. Дорогие: width, height, top, left, margin, padding — вызывают reflow всей страницы. Правило: анимировать только transform и opacity.',
    answerEn: 'Дешёвые для анимации (не вызывают reflow): transform (translate, scale, rotate) и opacity — выполняются на GPU, не затрагивают layout. Дорогие: width, height, top, left, margin, padding — вызывают reflow всей страницы. Правило: анимировать только transform и opacity.',
  },
  {
    id: 'css-028',
    difficulty: 'MEDIUM',
    order: 28,
    tags: ['animations'],
    questionRu: 'Что такое will-change и когда использовать?',
    questionEn: 'Что такое will-change и когда использовать?',
    answerRu: 'will-change подсказывает браузеру заранее оптимизировать элемент для анимации: will-change: transform создаёт compositor layer. Ускоряет анимации, но потребляет память. Использовать только для действительно анимируемых элементов, убирать после анимации. Не применять ко всему подряд.',
    answerEn: 'will-change подсказывает браузеру заранее оптимизировать элемент для анимации: will-change: transform создаёт compositor layer. Ускоряет анимации, но потребляет память. Использовать только для действительно анимируемых элементов, убирать после анимации. Не применять ко всему подряд.',
  },
  {
    id: 'css-029',
    difficulty: 'MEDIUM',
    order: 29,
    tags: ['animations'],
    questionRu: 'Что такое prefers-reduced-motion?',
    questionEn: 'Что такое prefers-reduced-motion?',
    answerRu: '@media (prefers-reduced-motion: reduce) — медиазапрос для пользователей, отключивших анимации в системе (вестибулярные нарушения, эпилепсия). Внутри: отключать или упрощать анимации. Best practice: писать анимации по умолчанию, убирать в prefers-reduced-motion.',
    answerEn: '@media (prefers-reduced-motion: reduce) — медиазапрос для пользователей, отключивших анимации в системе (вестибулярные нарушения, эпилепсия). Внутри: отключать или упрощать анимации. Best practice: писать анимации по умолчанию, убирать в prefers-reduced-motion.',
  },
  {
    id: 'css-030',
    difficulty: 'MEDIUM',
    order: 30,
    tags: ['animations'],
    questionRu: 'Как работает animation-fill-mode?',
    questionEn: 'Как работает animation-fill-mode?',
    answerRu: 'animation-fill-mode определяет стили элемента до и после анимации. none: стили из @keyframes не применяются вне анимации. forwards: после завершения сохраняет стили последнего кадра. backwards: применяет стили первого кадра во время задержки. both: комбинация forwards и backwards.',
    answerEn: 'animation-fill-mode определяет стили элемента до и после анимации. none: стили из @keyframes не применяются вне анимации. forwards: после завершения сохраняет стили последнего кадра. backwards: применяет стили первого кадра во время задержки. both: комбинация forwards и backwards.',
  },
  {
    id: 'css-031',
    difficulty: 'MEDIUM',
    order: 31,
    tags: ['methodologies'],
    questionRu: 'Чем CSS-переменные лучше переменных Sass/Less?',
    questionEn: 'Чем CSS-переменные лучше переменных Sass/Less?',
    answerRu: 'CSS-переменные работают в runtime: меняются через JS, каскадируются, переопределяются в медиазапросах и на уровне элемента. Sass/Less переменные — только compile-time, статичны в CSS. CSS-переменные идеальны для тем оформления и динамических изменений.',
    answerEn: 'CSS-переменные работают в runtime: меняются через JS, каскадируются, переопределяются в медиазапросах и на уровне элемента. Sass/Less переменные — только compile-time, статичны в CSS. CSS-переменные идеальны для тем оформления и динамических изменений.',
  },
  {
    id: 'css-032',
    difficulty: 'EASY',
    order: 32,
    tags: ['methodologies'],
    questionRu: 'Что такое методология БЭМ?',
    questionEn: 'Что такое методология БЭМ?',
    answerRu: 'БЭМ (Блок-Элемент-Модификатор) — соглашение именования классов: .block, .block__element, .block--modifier. Блок — независимый компонент. Элемент — часть блока (.card__title). Модификатор — вариация (.card--featured). Предотвращает конфликты стилей и облегчает поддержку.',
    answerEn: 'БЭМ (Блок-Элемент-Модификатор) — соглашение именования классов: .block, .block__element, .block--modifier. Блок — независимый компонент. Элемент — часть блока (.card__title). Модификатор — вариация (.card--featured). Предотвращает конфликты стилей и облегчает поддержку.',
  },
  {
    id: 'css-033',
    difficulty: 'MEDIUM',
    order: 33,
    tags: ['methodologies'],
    questionRu: 'Что такое CSS Modules?',
    questionEn: 'Что такое CSS Modules?',
    answerRu: 'CSS Modules — инструмент сборки, делающий классы локальными по умолчанию. Имена классов хешируются при компиляции: .button → .Button_button__abc12. Импортируется как объект: import s from \'./Button.module.css\'; className={s.button}. Полностью решает проблему конфликтов.',
    answerEn: 'CSS Modules — инструмент сборки, делающий классы локальными по умолчанию. Имена классов хешируются при компиляции: .button → .Button_button__abc12. Импортируется как объект: import s from \'./Button.module.css\'; className={s.button}. Полностью решает проблему конфликтов.',
  },
  {
    id: 'css-034',
    difficulty: 'MEDIUM',
    order: 34,
    tags: ['methodologies'],
    questionRu: 'Что такое CSS-in-JS и каковы его плюсы и минусы?',
    questionEn: 'Что такое CSS-in-JS и каковы его плюсы и минусы?',
    answerRu: 'CSS-in-JS (styled-components, Emotion) — стили прямо в JS. Плюсы: полная изоляция, динамические стили через props, автоудаление неиспользуемых стилей. Минусы: runtime overhead, увеличение JS-бандла, сложность SSR, потеря привычных инструментов браузера.',
    answerEn: 'CSS-in-JS (styled-components, Emotion) — стили прямо в JS. Плюсы: полная изоляция, динамические стили через props, автоудаление неиспользуемых стилей. Минусы: runtime overhead, увеличение JS-бандла, сложность SSR, потеря привычных инструментов браузера.',
  },
  {
    id: 'css-035',
    difficulty: 'EASY',
    order: 35,
    tags: ['methodologies'],
    questionRu: 'Что такое utility-first CSS (Tailwind)?',
    questionEn: 'Что такое utility-first CSS (Tailwind)?',
    answerRu: 'Utility-first — подход, где вместо семантических классов используются утилитарные: class="flex items-center gap-4 p-2". Плюсы: нет придумывания имён, нет роста CSS-файла, консистентность. Минусы: длинные className, нужна привычка. Tailwind — самый популярный фреймворк.',
    answerEn: 'Utility-first — подход, где вместо семантических классов используются утилитарные: class="flex items-center gap-4 p-2". Плюсы: нет придумывания имён, нет роста CSS-файла, консистентность. Минусы: длинные className, нужна привычка. Tailwind — самый популярный фреймворк.',
  },
];
