import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'css-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['specificity'],
    questionRu: 'Как работает специфичность в CSS?',
    questionEn: 'How does specificity work in CSS?',
    answerRu: 'Специфичность определяет, какое правило применяется при конфликте. Считается по уровням: ID (#id) — высший, классы/атрибуты/псевдоклассы (.class, [attr], :hover) — средний, теги/псевдоэлементы (div, ::before) — низший. Inline-стили перебивают все селекторы. !important перебивает всё.',
    answerEn: 'Specificity determines which rule is applied when there is a conflict. It is calculated in tiers: ID (#id) — highest, classes/attributes/pseudo-classes (.class, [attr], :hover) — medium, tags/pseudo-elements (div, ::before) — lowest. Inline styles override all selectors. !important overrides everything.',
  },
  {
    id: 'css-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['specificity'],
    questionRu: 'Что такое каскад в CSS и как определяется итоговый стиль?',
    questionEn: 'What is the CSS cascade and how is the final style determined?',
    answerRu: 'Каскад — алгоритм разрешения конфликтов стилей. Порядок приоритета: 1) !important, 2) специфичность селектора, 3) порядок появления в коде (последнее побеждает). Источники по приоритету: браузерные стили → пользовательские → авторские (наш CSS).',
    answerEn: 'The cascade is an algorithm for resolving style conflicts. Priority order: 1) !important, 2) selector specificity, 3) order of appearance in the code (last one wins). Sources by priority: browser styles → user styles → author styles (our CSS).',
  },
  {
    id: 'css-003',
    difficulty: 'EASY',
    order: 3,
    tags: ['specificity'],
    questionRu: 'Что такое наследование в CSS?',
    questionEn: 'What is inheritance in CSS?',
    answerRu: 'Некоторые свойства автоматически наследуются от родителя: color, font-*, line-height, text-align и др. Не наследуются: margin, padding, border, background. Управление: inherit — принудительно наследовать, initial — сбросить к дефолту, unset — inherit если наследуемое, иначе initial.',
    answerEn: 'Some properties are automatically inherited from the parent: color, font-*, line-height, text-align, etc. Not inherited: margin, padding, border, background. Control keywords: inherit — force inheritance, initial — reset to default, unset — inherit if the property is inheritable, otherwise initial.',
  },
  {
    id: 'css-004',
    difficulty: 'EASY',
    order: 4,
    tags: ['specificity'],
    questionRu: 'В чём проблема !important и когда его допустимо использовать?',
    questionEn: 'What is the problem with !important and when is it acceptable to use it?',
    answerRu: '!important нарушает естественный каскад, делает код хрупким и трудно переопределяемым. Создаёт гонку !important. Допустимые случаи: утилитарные классы (.hidden { display: none !important }), переопределение сторонних стилей которые нельзя изменить, стили доступности.',
    answerEn: '!important breaks the natural cascade, makes the code brittle and hard to override. It creates an !important arms race. Acceptable use cases: utility classes (.hidden { display: none !important }), overriding third-party styles that cannot be changed, accessibility styles.',
  },
  {
    id: 'css-005',
    difficulty: 'EASY',
    order: 5,
    tags: ['specificity'],
    questionRu: 'Что такое CSS-переменные (custom properties)?',
    questionEn: 'What are CSS variables (custom properties)?',
    answerRu: 'CSS-переменные объявляются через --name: value и используются через var(--name). Каскадируются и наследуются как обычные свойства. Можно переопределять в медиазапросах и на уровне элемента. Отличие от препроцессорных переменных: работают в runtime, доступны из JS.',
    answerEn: 'CSS variables are declared with --name: value and used with var(--name). They cascade and inherit like regular properties. They can be overridden in media queries and at the element level. Unlike preprocessor variables, they work at runtime and are accessible from JS.',
  },
  {
    id: 'css-006',
    difficulty: 'HARD',
    order: 6,
    tags: ['specificity'],
    questionRu: 'Что такое CSS-слои (@layer)?',
    questionEn: 'What are CSS layers (@layer)?',
    answerRu: '@layer позволяет явно управлять приоритетом групп стилей. Стили в слое с меньшим приоритетом не перебивают слой с большим, даже при высокой специфичности. Полезно для организации: @layer base, components, utilities — utilities всегда победит base.',
    answerEn: '@layer lets you explicitly control the priority of groups of styles. Styles in a lower-priority layer cannot override a higher-priority layer, even with higher specificity. Useful for organization: @layer base, components, utilities — utilities will always win over base.',
  },
  {
    id: 'css-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['box-model'],
    questionRu: 'Что такое блочная модель (box model)?',
    questionEn: 'What is the box model?',
    answerRu: 'Каждый элемент — прямоугольник из: content → padding → border → margin. По умолчанию (content-box) width задаёт только content. С box-sizing: border-box — width включает padding и border. border-box предпочтителен и обычно задаётся глобально через *, *::before, *::after.',
    answerEn: 'Every element is a rectangle composed of: content → padding → border → margin. By default (content-box), width sets only the content area. With box-sizing: border-box, width includes padding and border. border-box is preferred and is usually set globally via *, *::before, *::after.',
  },
  {
    id: 'css-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['box-model'],
    questionRu: 'Что такое margin collapsing?',
    questionEn: 'What is margin collapsing?',
    answerRu: 'Схлопывание margin — вертикальные margin соседних блоков и родитель/первый ребёнок объединяются в один (берётся максимальный). Не происходит для flex/grid контейнеров, элементов с overflow не visible, inline-block. Горизонтальный margin никогда не схлопывается.',
    answerEn: 'Margin collapsing — the vertical margins of adjacent blocks and parent/first-child collapse into one (the larger value is used). It does not occur for flex/grid containers, elements with overflow other than visible, or inline-block. Horizontal margins never collapse.',
  },
  {
    id: 'css-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['box-model'],
    questionRu: 'Как работают position: relative, absolute, fixed, sticky?',
    questionEn: 'How do position: relative, absolute, fixed, and sticky work?',
    answerRu: 'relative: смещение от нормального положения, остаётся в потоке. absolute: позиционируется относительно ближайшего positioned предка, уходит из потока. fixed: относительно viewport, не скроллится. sticky: relative пока не достигнет порога top/left, затем ведёт себя как fixed.',
    answerEn: 'relative: offset from its normal position, stays in the flow. absolute: positioned relative to the nearest positioned ancestor, removed from the flow. fixed: relative to the viewport, does not scroll. sticky: acts like relative until it reaches the top/left threshold, then behaves like fixed.',
  },
  {
    id: 'css-010',
    difficulty: 'HARD',
    order: 10,
    tags: ['box-model'],
    questionRu: 'Что такое stacking context и как работает z-index?',
    questionEn: 'What is a stacking context and how does z-index work?',
    answerRu: 'Stacking context — локальный контекст наложения слоёв. z-index работает только между элементами одного контекста. Создаётся при: position + z-index не auto, opacity < 1, transform, filter, isolation: isolate. Элемент с z-index:9999 внутри контекста с z-index:1 будет ПОД элементом с z-index:2 снаружи.',
    answerEn: 'A stacking context is a local layering context. z-index only works between elements within the same context. One is created by: position + z-index other than auto, opacity < 1, transform, filter, isolation: isolate. An element with z-index:9999 inside a context with z-index:1 will be BELOW an element with z-index:2 outside it.',
  },
  {
    id: 'css-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['box-model'],
    questionRu: 'В чём разница между display: none, visibility: hidden и opacity: 0?',
    questionEn: 'What is the difference between display: none, visibility: hidden, and opacity: 0?',
    answerRu: 'display: none — элемент удалён из потока, не занимает место, недоступен скринридерам и событиям. visibility: hidden — место сохраняется, скрыт визуально, недоступен скринридерам. opacity: 0 — полностью прозрачен, место сохраняется, остаётся кликабельным и доступным скринридерам.',
    answerEn: 'display: none — the element is removed from the flow, takes up no space, and is inaccessible to screen readers and events. visibility: hidden — space is preserved, visually hidden, inaccessible to screen readers. opacity: 0 — fully transparent, space is preserved, remains clickable and accessible to screen readers.',
  },
  {
    id: 'css-012',
    difficulty: 'EASY',
    order: 12,
    tags: ['box-model'],
    questionRu: 'Как центрировать элемент по горизонтали и вертикали?',
    questionEn: 'How do you center an element horizontally and vertically?',
    answerRu: 'Flexbox: родитель display:flex; justify-content:center; align-items:center. Grid: родитель display:grid; place-items:center. Абсолютное позиционирование: position:absolute; top:50%; left:50%; transform:translate(-50%,-50%). Для блочного элемента по горизонтали: margin: 0 auto с заданной шириной.',
    answerEn: 'Flexbox: parent display:flex; justify-content:center; align-items:center. Grid: parent display:grid; place-items:center. Absolute positioning: position:absolute; top:50%; left:50%; transform:translate(-50%,-50%). For horizontal centering of a block element: margin: 0 auto with a defined width.',
  },
  {
    id: 'css-013',
    difficulty: 'HARD',
    order: 13,
    tags: ['box-model'],
    questionRu: 'Что такое BFC (Block Formatting Context)?',
    questionEn: 'What is a BFC (Block Formatting Context)?',
    answerRu: 'BFC — независимый контейнер со своими правилами раскладки. Внутри BFC: margin не схлопываются с внешними, float содержится внутри контейнера. Создаётся при: overflow не visible, display: flow-root (чистый способ), flex/grid контейнер, position absolute/fixed.',
    answerEn: 'A BFC is an independent container with its own layout rules. Inside a BFC: margins do not collapse with outside margins, floats are contained within the container. Created by: overflow other than visible, display: flow-root (the clean way), flex/grid container, position absolute/fixed.',
  },
  {
    id: 'css-014',
    difficulty: 'EASY',
    order: 14,
    tags: ['flexbox'],
    questionRu: 'Что такое Flexbox и когда его использовать?',
    questionEn: 'What is Flexbox and when should you use it?',
    answerRu: 'Flexbox — одномерная система раскладки (главная ось + поперечная). Идеален для: навигации, выравнивания элементов в строку или колонку, равномерного распределения пространства, центрирования. Для двумерных раскладок (строки и колонки одновременно) предпочтительнее Grid.',
    answerEn: 'Flexbox is a one-dimensional layout system (main axis + cross axis). Ideal for: navigation, aligning items in a row or column, distributing space evenly, centering. For two-dimensional layouts (rows and columns simultaneously), Grid is preferable.',
  },
  {
    id: 'css-015',
    difficulty: 'EASY',
    order: 15,
    tags: ['flexbox'],
    questionRu: 'В чём разница между justify-content и align-items?',
    questionEn: 'What is the difference between justify-content and align-items?',
    answerRu: 'justify-content управляет выравниванием по главной оси (по умолчанию горизонтальной): flex-start, flex-end, center, space-between, space-around. align-items — по поперечной оси (вертикальной): stretch, flex-start, flex-end, center, baseline. При flex-direction: column оси меняются местами.',
    answerEn: 'justify-content controls alignment along the main axis (horizontal by default): flex-start, flex-end, center, space-between, space-around. align-items controls alignment along the cross axis (vertical): stretch, flex-start, flex-end, center, baseline. With flex-direction: column, the axes are swapped.',
  },
  {
    id: 'css-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['flexbox'],
    questionRu: 'Что делают flex-grow, flex-shrink и flex-basis?',
    questionEn: 'What do flex-grow, flex-shrink, and flex-basis do?',
    answerRu: 'flex-basis: базовый размер элемента до распределения пространства (аналог width). flex-grow: коэффициент роста при наличии свободного места (0 — не растёт). flex-shrink: коэффициент сжатия при нехватке места (0 — не сжимается). Shorthand: flex: 1 = flex: 1 1 0.',
    answerEn: 'flex-basis: the base size of the item before space is distributed (similar to width). flex-grow: the growth factor when free space is available (0 — does not grow). flex-shrink: the shrink factor when there is not enough space (0 — does not shrink). Shorthand: flex: 1 = flex: 1 1 0.',
  },
  {
    id: 'css-017',
    difficulty: 'EASY',
    order: 17,
    tags: ['flexbox'],
    questionRu: 'В чём разница между align-items и align-self?',
    questionEn: 'What is the difference between align-items and align-self?',
    answerRu: 'align-items задаётся на контейнере и применяется ко всем flex-элементам. align-self задаётся на конкретном элементе и переопределяет align-items для него. Значения те же: auto, flex-start, flex-end, center, stretch, baseline.',
    answerEn: 'align-items is set on the container and applies to all flex items. align-self is set on a specific item and overrides align-items for that item. The values are the same: auto, flex-start, flex-end, center, stretch, baseline.',
  },
  {
    id: 'css-018',
    difficulty: 'EASY',
    order: 18,
    tags: ['flexbox'],
    questionRu: 'Что такое flex-wrap и когда его использовать?',
    questionEn: 'What is flex-wrap and when should you use it?',
    answerRu: 'flex-wrap: nowrap (по умолчанию) — все элементы в одну строку, могут выходить за пределы. wrap — переносит на следующую строку при нехватке места. wrap-reverse — переносит в обратном направлении. align-content управляет многострочным выравниванием при wrap.',
    answerEn: 'flex-wrap: nowrap (default) — all items in one line, can overflow. wrap — wraps to the next line when there is not enough space. wrap-reverse — wraps in the reverse direction. align-content controls multi-line alignment when wrapping.',
  },
  {
    id: 'css-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['flexbox'],
    questionRu: 'Как работает order во Flexbox?',
    questionEn: 'How does order work in Flexbox?',
    answerRu: 'order изменяет визуальный порядок flex-элементов без изменения DOM. Значение по умолчанию: 0. Элементы с меньшим order идут первыми. Отрицательные значения ставят элемент в начало. Важно: порядок для скринридеров и Tab-навигации остаётся по DOM.',
    answerEn: 'order changes the visual order of flex items without modifying the DOM. Default value: 0. Items with a lower order value come first. Negative values place an item at the beginning. Important: the order for screen readers and Tab navigation remains as it is in the DOM.',
  },
  {
    id: 'css-020',
    difficulty: 'EASY',
    order: 20,
    tags: ['grid'],
    questionRu: 'Что такое CSS Grid и чем отличается от Flexbox?',
    questionEn: 'What is CSS Grid and how does it differ from Flexbox?',
    answerRu: 'Grid — двумерная система раскладки (строки и колонки одновременно). Flexbox — одномерная (либо строка, либо колонка). Grid лучше для: общей раскладки страницы, сложных сеток, выравнивания в двух измерениях. Flexbox лучше для: компонентов, навигации, одномерных списков.',
    answerEn: 'Grid is a two-dimensional layout system (rows and columns simultaneously). Flexbox is one-dimensional (either a row or a column). Grid is better for: overall page layout, complex grids, two-dimensional alignment. Flexbox is better for: components, navigation, one-dimensional lists.',
  },
  {
    id: 'css-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['grid'],
    questionRu: 'Как задать колонки и строки в Grid?',
    questionEn: 'How do you define columns and rows in Grid?',
    answerRu: 'grid-template-columns: 200px 1fr 1fr — три колонки. repeat(3, 1fr) — три равные колонки. auto-fill/auto-fit с minmax для адаптивных сеток: repeat(auto-fill, minmax(200px, 1fr)). grid-template-rows аналогично для строк. fr — доля свободного пространства.',
    answerEn: 'grid-template-columns: 200px 1fr 1fr — three columns. repeat(3, 1fr) — three equal columns. auto-fill/auto-fit with minmax for responsive grids: repeat(auto-fill, minmax(200px, 1fr)). grid-template-rows works the same way for rows. fr — a fraction of the available space.',
  },
  {
    id: 'css-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['grid'],
    questionRu: 'Что такое grid-area и как размещать элементы?',
    questionEn: 'What is grid-area and how do you place elements?',
    answerRu: 'grid-column: 1 / 3 — элемент занимает колонки с 1 по 3. grid-row: 1 / 2. Shorthand grid-area: row-start / col-start / row-end / col-end. Именованные зоны: grid-template-areas задаёт имена зон, grid-area: name назначает элемент в зону.',
    answerEn: 'grid-column: 1 / 3 — the element spans columns 1 through 3. grid-row: 1 / 2. Shorthand grid-area: row-start / col-start / row-end / col-end. Named areas: grid-template-areas defines area names, grid-area: name assigns an element to an area.',
  },
  {
    id: 'css-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['grid'],
    questionRu: 'В чём разница между auto-fill и auto-fit?',
    questionEn: 'What is the difference between auto-fill and auto-fit?',
    answerRu: 'Оба создают столько колонок, сколько помещается. auto-fill: создаёт пустые колонки если элементов мало — сетка сохраняет структуру. auto-fit: схлопывает пустые колонки — элементы растягиваются на всю ширину. Разница заметна когда элементов меньше чем колонок.',
    answerEn: 'Both create as many columns as will fit. auto-fill: creates empty columns when there are few items — the grid preserves its structure. auto-fit: collapses empty columns — items stretch to fill the full width. The difference is visible when there are fewer items than columns.',
  },
  {
    id: 'css-024',
    difficulty: 'EASY',
    order: 24,
    tags: ['grid'],
    questionRu: 'Что такое gap (grid-gap)?',
    questionEn: 'What is gap (grid-gap)?',
    answerRu: 'gap (ранее grid-gap) задаёт отступы между ячейками: gap: 16px — и строки и колонки. gap: 8px 16px — строки и колонки раздельно. Преимущество над margin: отступ только между ячейками, не по краям. Работает и во Flexbox.',
    answerEn: 'gap (formerly grid-gap) sets spacing between cells: gap: 16px — both rows and columns. gap: 8px 16px — rows and columns separately. Advantage over margin: spacing only between cells, not on the edges. Also works in Flexbox.',
  },
  {
    id: 'css-025',
    difficulty: 'HARD',
    order: 25,
    tags: ['grid'],
    questionRu: 'Что такое implicit и explicit grid?',
    questionEn: 'What are implicit and explicit grids?',
    answerRu: 'Explicit grid — явно заданные строки/колонки через grid-template-*. Implicit grid — автоматически создаётся для элементов, выходящих за пределы явной сетки. grid-auto-rows и grid-auto-columns задают размер неявных треков. grid-auto-flow управляет направлением авторазмещения.',
    answerEn: 'The explicit grid consists of rows/columns explicitly defined via grid-template-*. The implicit grid is automatically created for items that fall outside the explicit grid. grid-auto-rows and grid-auto-columns set the size of implicit tracks. grid-auto-flow controls the direction of auto-placement.',
  },
  {
    id: 'css-026',
    difficulty: 'EASY',
    order: 26,
    tags: ['animations'],
    questionRu: 'В чём разница между transition и animation?',
    questionEn: 'What is the difference between transition and animation?',
    answerRu: 'transition: плавный переход между двумя состояниями при изменении свойства (hover, класс). Простой, декларативный. animation с @keyframes: независимая анимация с полным контролем — несколько кадров, повторение, направление, задержка. Для сложных сценариев нужна animation.',
    answerEn: 'transition: a smooth change between two states when a property changes (hover, class). Simple and declarative. animation with @keyframes: an independent animation with full control — multiple frames, repetition, direction, delay. For complex scenarios, animation is needed.',
  },
  {
    id: 'css-027',
    difficulty: 'MEDIUM',
    order: 27,
    tags: ['animations'],
    questionRu: 'Какие CSS-свойства безопасно анимировать для производительности?',
    questionEn: 'Which CSS properties are safe to animate for performance?',
    answerRu: 'Дешёвые для анимации (не вызывают reflow): transform (translate, scale, rotate) и opacity — выполняются на GPU, не затрагивают layout. Дорогие: width, height, top, left, margin, padding — вызывают reflow всей страницы. Правило: анимировать только transform и opacity.',
    answerEn: 'Cheap to animate (do not trigger reflow): transform (translate, scale, rotate) and opacity — run on the GPU, do not affect layout. Expensive: width, height, top, left, margin, padding — trigger a reflow of the entire page. Rule of thumb: only animate transform and opacity.',
  },
  {
    id: 'css-028',
    difficulty: 'MEDIUM',
    order: 28,
    tags: ['animations'],
    questionRu: 'Что такое will-change и когда использовать?',
    questionEn: 'What is will-change and when should you use it?',
    answerRu: 'will-change подсказывает браузеру заранее оптимизировать элемент для анимации: will-change: transform создаёт compositor layer. Ускоряет анимации, но потребляет память. Использовать только для действительно анимируемых элементов, убирать после анимации. Не применять ко всему подряд.',
    answerEn: 'will-change hints to the browser to optimize an element for animation in advance: will-change: transform creates a compositor layer. It speeds up animations but consumes memory. Use it only for elements that are actually being animated, and remove it after the animation. Do not apply it indiscriminately.',
  },
  {
    id: 'css-029',
    difficulty: 'MEDIUM',
    order: 29,
    tags: ['animations'],
    questionRu: 'Что такое prefers-reduced-motion?',
    questionEn: 'What is prefers-reduced-motion?',
    answerRu: '@media (prefers-reduced-motion: reduce) — медиазапрос для пользователей, отключивших анимации в системе (вестибулярные нарушения, эпилепсия). Внутри: отключать или упрощать анимации. Best practice: писать анимации по умолчанию, убирать в prefers-reduced-motion.',
    answerEn: '@media (prefers-reduced-motion: reduce) is a media query for users who have disabled animations in their system settings (vestibular disorders, epilepsy). Inside it: disable or simplify animations. Best practice: write animations by default and disable them within prefers-reduced-motion.',
  },
  {
    id: 'css-030',
    difficulty: 'MEDIUM',
    order: 30,
    tags: ['animations'],
    questionRu: 'Как работает animation-fill-mode?',
    questionEn: 'How does animation-fill-mode work?',
    answerRu: 'animation-fill-mode определяет стили элемента до и после анимации. none: стили из @keyframes не применяются вне анимации. forwards: после завершения сохраняет стили последнего кадра. backwards: применяет стили первого кадра во время задержки. both: комбинация forwards и backwards.',
    answerEn: 'animation-fill-mode defines the styles of an element before and after the animation. none: styles from @keyframes are not applied outside the animation. forwards: after completion, retains the styles of the last keyframe. backwards: applies the styles of the first keyframe during the delay. both: a combination of forwards and backwards.',
  },
  {
    id: 'css-031',
    difficulty: 'MEDIUM',
    order: 31,
    tags: ['methodologies'],
    questionRu: 'Чем CSS-переменные лучше переменных Sass/Less?',
    questionEn: 'How are CSS variables better than Sass/Less variables?',
    answerRu: 'CSS-переменные работают в runtime: меняются через JS, каскадируются, переопределяются в медиазапросах и на уровне элемента. Sass/Less переменные — только compile-time, статичны в CSS. CSS-переменные идеальны для тем оформления и динамических изменений.',
    answerEn: 'CSS variables work at runtime: they can be changed via JS, they cascade, and can be overridden in media queries and at the element level. Sass/Less variables are compile-time only and static in CSS. CSS variables are ideal for theming and dynamic changes.',
  },
  {
    id: 'css-032',
    difficulty: 'EASY',
    order: 32,
    tags: ['methodologies'],
    questionRu: 'Что такое методология БЭМ?',
    questionEn: 'What is the BEM methodology?',
    answerRu: 'БЭМ (Блок-Элемент-Модификатор) — соглашение именования классов: .block, .block__element, .block--modifier. Блок — независимый компонент. Элемент — часть блока (.card__title). Модификатор — вариация (.card--featured). Предотвращает конфликты стилей и облегчает поддержку.',
    answerEn: 'BEM (Block-Element-Modifier) is a class naming convention: .block, .block__element, .block--modifier. A Block is an independent component. An Element is part of a block (.card__title). A Modifier is a variation (.card--featured). It prevents style conflicts and makes maintenance easier.',
  },
  {
    id: 'css-033',
    difficulty: 'MEDIUM',
    order: 33,
    tags: ['methodologies'],
    questionRu: 'Что такое CSS Modules?',
    questionEn: 'What are CSS Modules?',
    answerRu: 'CSS Modules — инструмент сборки, делающий классы локальными по умолчанию. Имена классов хешируются при компиляции: .button → .Button_button__abc12. Импортируется как объект: import s from \'./Button.module.css\'; className={s.button}. Полностью решает проблему конфликтов.',
    answerEn: 'CSS Modules is a build tool that makes class names local by default. Class names are hashed at compile time: .button → .Button_button__abc12. Imported as an object: import s from \'./Button.module.css\'; className={s.button}. Completely solves the naming conflict problem.',
  },
  {
    id: 'css-034',
    difficulty: 'MEDIUM',
    order: 34,
    tags: ['methodologies'],
    questionRu: 'Что такое CSS-in-JS и каковы его плюсы и минусы?',
    questionEn: 'What is CSS-in-JS and what are its pros and cons?',
    answerRu: 'CSS-in-JS (styled-components, Emotion) — стили прямо в JS. Плюсы: полная изоляция, динамические стили через props, автоудаление неиспользуемых стилей. Минусы: runtime overhead, увеличение JS-бандла, сложность SSR, потеря привычных инструментов браузера.',
    answerEn: 'CSS-in-JS (styled-components, Emotion) — styles written directly in JS. Pros: full isolation, dynamic styles via props, automatic removal of unused styles. Cons: runtime overhead, increased JS bundle size, SSR complexity, loss of familiar browser tooling.',
  },
  {
    id: 'css-035',
    difficulty: 'EASY',
    order: 35,
    tags: ['methodologies'],
    questionRu: 'Что такое utility-first CSS (Tailwind)?',
    questionEn: 'What is utility-first CSS (Tailwind)?',
    answerRu: 'Utility-first — подход, где вместо семантических классов используются утилитарные: class="flex items-center gap-4 p-2". Плюсы: нет придумывания имён, нет роста CSS-файла, консистентность. Минусы: длинные className, нужна привычка. Tailwind — самый популярный фреймворк.',
    answerEn: 'Utility-first is an approach where utility classes are used instead of semantic ones: class="flex items-center gap-4 p-2". Pros: no need to invent names, no CSS file growth, consistency. Cons: long classNames, requires getting used to. Tailwind is the most popular framework.',
  },
];
