import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'html-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['semantics'],
    questionRu: 'Что такое семантический HTML и зачем он нужен?',
    questionEn: 'Что такое семантический HTML и зачем он нужен?',
    answerRu: 'Семантический HTML — использование тегов по их смысловому назначению: <header>, <nav>, <main>, <article>, <section>, <footer>. Преимущества: лучшая индексация поисковиками, доступность для скринридеров, читаемость кода.',
    answerEn: 'Семантический HTML — использование тегов по их смысловому назначению: <header>, <nav>, <main>, <article>, <section>, <footer>. Преимущества: лучшая индексация поисковиками, доступность для скринридеров, читаемость кода.',
  },
  {
    id: 'html-002',
    difficulty: 'EASY',
    order: 2,
    tags: ['semantics'],
    questionRu: 'В чём разница между <div> и семантическими тегами?',
    questionEn: 'В чём разница между <div> и семантическими тегами?',
    answerRu: '<div> — контейнер без смысла, только для стилизации/группировки. Семантические теги несут значение: <article> — самостоятельный контент, <section> — тематическая группа, <aside> — боковой контент. Скринридеры и поисковики понимают структуру через семантику.',
    answerEn: '<div> — контейнер без смысла, только для стилизации/группировки. Семантические теги несут значение: <article> — самостоятельный контент, <section> — тематическая группа, <aside> — боковой контент. Скринридеры и поисковики понимают структуру через семантику.',
  },
  {
    id: 'html-003',
    difficulty: 'EASY',
    order: 3,
    tags: ['semantics'],
    questionRu: 'В чём разница между <section>, <article> и <div>?',
    questionEn: 'В чём разница между <section>, <article> и <div>?',
    answerRu: '<article> — независимый самодостаточный контент (пост, новость, комментарий), который имеет смысл вне контекста страницы. <section> — тематическая группа контента внутри страницы, обычно с заголовком. <div> — нейтральный контейнер без семантики.',
    answerEn: '<article> — независимый самодостаточный контент (пост, новость, комментарий), который имеет смысл вне контекста страницы. <section> — тематическая группа контента внутри страницы, обычно с заголовком. <div> — нейтральный контейнер без семантики.',
  },
  {
    id: 'html-004',
    difficulty: 'EASY',
    order: 4,
    tags: ['semantics'],
    questionRu: 'Что такое DOCTYPE и зачем он нужен?',
    questionEn: 'Что такое DOCTYPE и зачем он нужен?',
    answerRu: 'DOCTYPE сообщает браузеру версию HTML. <!DOCTYPE html> — декларация HTML5, включает стандартный режим рендеринга (standards mode). Без DOCTYPE браузер переходит в quirks mode — имитирует баги старых браузеров. Всегда должен быть первой строкой документа.',
    answerEn: 'DOCTYPE сообщает браузеру версию HTML. <!DOCTYPE html> — декларация HTML5, включает стандартный режим рендеринга (standards mode). Без DOCTYPE браузер переходит в quirks mode — имитирует баги старых браузеров. Всегда должен быть первой строкой документа.',
  },
  {
    id: 'html-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['semantics'],
    questionRu: 'В чём разница между <script>, <script defer> и <script async>?',
    questionEn: 'В чём разница между <script>, <script defer> и <script async>?',
    answerRu: 'Обычный <script>: останавливает парсинг HTML, загружает и выполняет скрипт. defer: загружает параллельно, выполняет после парсинга HTML, сохраняет порядок. async: загружает параллельно, выполняет сразу после загрузки, порядок не гарантирован. defer предпочтителен для большинства скриптов.',
    answerEn: 'Обычный <script>: останавливает парсинг HTML, загружает и выполняет скрипт. defer: загружает параллельно, выполняет после парсинга HTML, сохраняет порядок. async: загружает параллельно, выполняет сразу после загрузки, порядок не гарантирован. defer предпочтителен для большинства скриптов.',
  },
  {
    id: 'html-006',
    difficulty: 'EASY',
    order: 6,
    tags: ['semantics'],
    questionRu: 'Что такое data-атрибуты и когда их использовать?',
    questionEn: 'Что такое data-атрибуты и когда их использовать?',
    answerRu: 'data-* атрибуты хранят пользовательские данные прямо в HTML: <div data-user-id="42">. Доступны через dataset: el.dataset.userId. Используются для передачи данных из HTML в JS без скрытых полей. Не подходят для критичных данных — видны в DOM.',
    answerEn: 'data-* атрибуты хранят пользовательские данные прямо в HTML: <div data-user-id="42">. Доступны через dataset: el.dataset.userId. Используются для передачи данных из HTML в JS без скрытых полей. Не подходят для критичных данных — видны в DOM.',
  },
  {
    id: 'html-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['semantics'],
    questionRu: 'В чём разница между <strong> и <b>, <em> и <i>?',
    questionEn: 'В чём разница между <strong> и <b>, <em> и <i>?',
    answerRu: '<strong> — семантически важный текст (скринридер акцентирует). <b> — визуально жирный без семантики. <em> — акцент, смысл меняется от интонации (скринридер меняет ударение). <i> — курсив без семантики, для технических терминов, иностранных слов. Предпочитать семантические теги.',
    answerEn: '<strong> — семантически важный текст (скринридер акцентирует). <b> — визуально жирный без семантики. <em> — акцент, смысл меняется от интонации (скринридер меняет ударение). <i> — курсив без семантики, для технических терминов, иностранных слов. Предпочитать семантические теги.',
  },
  {
    id: 'html-008',
    difficulty: 'EASY',
    order: 8,
    tags: ['forms'],
    questionRu: 'Какие типы input существуют в HTML5?',
    questionEn: 'Какие типы input существуют в HTML5?',
    answerRu: 'Основные: text, password, email, number, tel, url, search, date, time, datetime-local, month, week, color, range, file, checkbox, radio, submit, reset, button, hidden. Типы обеспечивают нативную валидацию, правильную клавиатуру на мобильных и семантику.',
    answerEn: 'Основные: text, password, email, number, tel, url, search, date, time, datetime-local, month, week, color, range, file, checkbox, radio, submit, reset, button, hidden. Типы обеспечивают нативную валидацию, правильную клавиатуру на мобильных и семантику.',
  },
  {
    id: 'html-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['forms'],
    questionRu: 'Что такое нативная валидация форм в HTML?',
    questionEn: 'Что такое нативная валидация форм в HTML?',
    answerRu: 'HTML5 предоставляет атрибуты валидации: required, minlength/maxlength, min/max, pattern (regex), type. Браузер валидирует перед отправкой и показывает встроенные сообщения. Кастомизация через Constraint Validation API: setCustomValidity(), checkValidity().',
    answerEn: 'HTML5 предоставляет атрибуты валидации: required, minlength/maxlength, min/max, pattern (regex), type. Браузер валидирует перед отправкой и показывает встроенные сообщения. Кастомизация через Constraint Validation API: setCustomValidity(), checkValidity().',
  },
  {
    id: 'html-010',
    difficulty: 'EASY',
    order: 10,
    tags: ['forms'],
    questionRu: 'В чём разница между method GET и POST в форме?',
    questionEn: 'В чём разница между method GET и POST в форме?',
    answerRu: 'GET: данные передаются в URL (query string), видны пользователю, кешируются, ограничены по длине. Используется для поиска, фильтров. POST: данные в теле запроса, не видны в URL, нет ограничения размера. Для отправки данных, логина, загрузки файлов.',
    answerEn: 'GET: данные передаются в URL (query string), видны пользователю, кешируются, ограничены по длине. Используется для поиска, фильтров. POST: данные в теле запроса, не видны в URL, нет ограничения размера. Для отправки данных, логина, загрузки файлов.',
  },
  {
    id: 'html-011',
    difficulty: 'EASY',
    order: 11,
    tags: ['forms'],
    questionRu: 'Что такое <label> и почему важно его использовать?',
    questionEn: 'Что такое <label> и почему важно его использовать?',
    answerRu: '<label for="id"> связывает текст с полем ввода. При клике на label фокус переходит на input. Критично для доступности: скринридер объявляет label при фокусе на поле. Можно использовать обёртку: <label><input type="checkbox"> Согласен</label> без атрибута for.',
    answerEn: '<label for="id"> связывает текст с полем ввода. При клике на label фокус переходит на input. Критично для доступности: скринридер объявляет label при фокусе на поле. Можно использовать обёртку: <label><input type="checkbox"> Согласен</label> без атрибута for.',
  },
  {
    id: 'html-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['forms'],
    questionRu: 'Что такое fieldset и legend?',
    questionEn: 'Что такое fieldset и legend?',
    answerRu: '<fieldset> группирует связанные элементы формы. <legend> даёт группе название. Скринридер читает legend перед каждым полем группы. Особенно важно для групп radio/checkbox. fieldset можно отключить атрибутом disabled — отключит все вложенные поля.',
    answerEn: '<fieldset> группирует связанные элементы формы. <legend> даёт группе название. Скринридер читает legend перед каждым полем группы. Особенно важно для групп radio/checkbox. fieldset можно отключить атрибутом disabled — отключит все вложенные поля.',
  },
  {
    id: 'html-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['forms'],
    questionRu: 'Как работает атрибут autocomplete?',
    questionEn: 'Как работает атрибут autocomplete?',
    answerRu: 'autocomplete управляет автозаполнением браузера. autocomplete="off" — отключить. Конкретные значения: "name", "email", "current-password", "new-password", "one-time-code" и др. Правильные значения улучшают UX и помогают менеджерам паролей.',
    answerEn: 'autocomplete управляет автозаполнением браузера. autocomplete="off" — отключить. Конкретные значения: "name", "email", "current-password", "new-password", "one-time-code" и др. Правильные значения улучшают UX и помогают менеджерам паролей.',
  },
  {
    id: 'html-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['accessibility'],
    questionRu: 'Что такое ARIA и когда её использовать?',
    questionEn: 'Что такое ARIA и когда её использовать?',
    answerRu: 'ARIA (Accessible Rich Internet Applications) — атрибуты для описания семантики интерактивных элементов скринридерам: role, aria-label, aria-hidden, aria-expanded и др. Правило: сначала нативный HTML (button вместо div+role), ARIA только если нативного решения нет.',
    answerEn: 'ARIA (Accessible Rich Internet Applications) — атрибуты для описания семантики интерактивных элементов скринридерам: role, aria-label, aria-hidden, aria-expanded и др. Правило: сначала нативный HTML (button вместо div+role), ARIA только если нативного решения нет.',
  },
  {
    id: 'html-015',
    difficulty: 'EASY',
    order: 15,
    tags: ['accessibility'],
    questionRu: 'Что такое alt у изображений и как правильно заполнять?',
    questionEn: 'Что такое alt у изображений и как правильно заполнять?',
    answerRu: 'alt — текстовая альтернатива изображения для скринридеров и при ошибке загрузки. Правила: описывать смысл (не «картинка»), декоративные изображения — alt="" (скринридер пропустит), иконки-кнопки — описывать действие. Пустой alt лучше отсутствующего.',
    answerEn: 'alt — текстовая альтернатива изображения для скринридеров и при ошибке загрузки. Правила: описывать смысл (не «картинка»), декоративные изображения — alt="" (скринридер пропустит), иконки-кнопки — описывать действие. Пустой alt лучше отсутствующего.',
  },
  {
    id: 'html-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['accessibility'],
    questionRu: 'Что такое tabindex и как управлять порядком фокуса?',
    questionEn: 'Что такое tabindex и как управлять порядком фокуса?',
    answerRu: 'tabindex управляет навигацией с клавиатуры. tabindex="0" — добавить в естественный порядок. tabindex="-1" — программный фокус без Tab-навигации (для модалок). tabindex="1+" — задать порядок явно (антипаттерн, нарушает естественный поток). Нативные элементы (button, a, input) фокусируются по умолчанию.',
    answerEn: 'tabindex управляет навигацией с клавиатуры. tabindex="0" — добавить в естественный порядок. tabindex="-1" — программный фокус без Tab-навигации (для модалок). tabindex="1+" — задать порядок явно (антипаттерн, нарушает естественный поток). Нативные элементы (button, a, input) фокусируются по умолчанию.',
  },
  {
    id: 'html-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['accessibility'],
    questionRu: 'В чём разница между aria-label, aria-labelledby и aria-describedby?',
    questionEn: 'В чём разница между aria-label, aria-labelledby и aria-describedby?',
    answerRu: 'aria-label: задаёт текстовое название элемента напрямую. aria-labelledby: ссылается на id элемента, чей текст будет названием. aria-describedby: ссылается на id элемента с дополнительным описанием (читается после label). labelledby приоритетнее label.',
    answerEn: 'aria-label: задаёт текстовое название элемента напрямую. aria-labelledby: ссылается на id элемента, чей текст будет названием. aria-describedby: ссылается на id элемента с дополнительным описанием (читается после label). labelledby приоритетнее label.',
  },
  {
    id: 'html-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['accessibility'],
    questionRu: 'Что такое skip links?',
    questionEn: 'Что такое skip links?',
    answerRu: 'Skip link — первая ссылка на странице «Перейти к основному контенту», видимая при фокусе с клавиатуры. Позволяет пропустить навигацию и сразу перейти к <main>. Реализуется: <a href="#main" class="skip-link">Skip to content</a> с CSS visibility на :focus.',
    answerEn: 'Skip link — первая ссылка на странице «Перейти к основному контенту», видимая при фокусе с клавиатуры. Позволяет пропустить навигацию и сразу перейти к <main>. Реализуется: <a href="#main" class="skip-link">Skip to content</a> с CSS visibility на :focus.',
  },
  {
    id: 'html-019',
    difficulty: 'EASY',
    order: 19,
    tags: ['accessibility'],
    questionRu: 'Почему нельзя использовать div вместо button для кликабельных элементов?',
    questionEn: 'Почему нельзя использовать div вместо button для кликабельных элементов?',
    answerRu: 'button нативно: фокусируется с клавиатуры, активируется Enter/Space, имеет role="button" для скринридеров, поддерживает disabled. div нужно вручную добавлять tabindex, role, обработчики keydown, aria-disabled. Нативный элемент надёжнее и доступнее.',
    answerEn: 'button нативно: фокусируется с клавиатуры, активируется Enter/Space, имеет role="button" для скринридеров, поддерживает disabled. div нужно вручную добавлять tabindex, role, обработчики keydown, aria-disabled. Нативный элемент надёжнее и доступнее.',
  },
  {
    id: 'html-020',
    difficulty: 'MEDIUM',
    order: 20,
    tags: ['seo'],
    questionRu: 'Какие мета-теги важны для SEO?',
    questionEn: 'Какие мета-теги важны для SEO?',
    answerRu: '<title> — самый важный, отображается в результатах поиска. <meta name="description"> — описание в сниппете. <meta name="robots"> — управление индексацией. Open Graph теги (og:title, og:image) для соцсетей. canonical — указывает основной URL при дублях.',
    answerEn: '<title> — самый важный, отображается в результатах поиска. <meta name="description"> — описание в сниппете. <meta name="robots"> — управление индексацией. Open Graph теги (og:title, og:image) для соцсетей. canonical — указывает основной URL при дублях.',
  },
  {
    id: 'html-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['seo'],
    questionRu: 'Что такое viewport meta тег?',
    questionEn: 'Что такое viewport meta тег?',
    answerRu: '<meta name="viewport" content="width=device-width, initial-scale=1"> — обязателен для адаптивных сайтов. Без него мобильный браузер рендерит страницу как десктоп и масштабирует. width=device-width устанавливает ширину viewport равной ширине экрана устройства.',
    answerEn: '<meta name="viewport" content="width=device-width, initial-scale=1"> — обязателен для адаптивных сайтов. Без него мобильный браузер рендерит страницу как десктоп и масштабирует. width=device-width устанавливает ширину viewport равной ширине экрана устройства.',
  },
  {
    id: 'html-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['performance'],
    questionRu: 'Что такое <link rel="preload"> и <link rel="prefetch">?',
    questionEn: 'Что такое <link rel="preload"> и <link rel="prefetch">?',
    answerRu: 'preload — загрузить ресурс как можно скорее, нужен для текущей страницы (критичные шрифты, CSS, JS). prefetch — загрузить с низким приоритетом для будущей навигации. preconnect — заранее установить соединение с доменом. Правильное использование ускоряет LCP.',
    answerEn: 'preload — загрузить ресурс как можно скорее, нужен для текущей страницы (критичные шрифты, CSS, JS). prefetch — загрузить с низким приоритетом для будущей навигации. preconnect — заранее установить соединение с доменом. Правильное использование ускоряет LCP.',
  },
  {
    id: 'html-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['performance'],
    questionRu: 'Что такое атрибуты loading="lazy" и decoding="async" у изображений?',
    questionEn: 'Что такое атрибуты loading="lazy" и decoding="async" у изображений?',
    answerRu: 'loading="lazy" откладывает загрузку изображения до приближения к viewport — нативная ленивая загрузка без JS. loading="eager" — загрузить сразу (по умолчанию). decoding="async" разрешает браузеру декодировать изображение асинхронно, не блокируя рендеринг.',
    answerEn: 'loading="lazy" откладывает загрузку изображения до приближения к viewport — нативная ленивая загрузка без JS. loading="eager" — загрузить сразу (по умолчанию). decoding="async" разрешает браузеру декодировать изображение асинхронно, не блокируя рендеринг.',
  },
  {
    id: 'html-024',
    difficulty: 'MEDIUM',
    order: 24,
    tags: ['performance'],
    questionRu: 'Что такое <picture> и srcset у изображений?',
    questionEn: 'Что такое <picture> и srcset у изображений?',
    answerRu: '<picture> и srcset позволяют задать разные изображения для разных условий. srcset с sizes — разные разрешения одного изображения, браузер выбирает оптимальное. <picture> с <source media> — разные изображения для разных breakpoint или форматов (WebP с fallback на JPEG).',
    answerEn: '<picture> и srcset позволяют задать разные изображения для разных условий. srcset с sizes — разные разрешения одного изображения, браузер выбирает оптимальное. <picture> с <source media> — разные изображения для разных breakpoint или форматов (WebP с fallback на JPEG).',
  },
];
