import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'html-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['semantics'],
    questionRu: 'Что такое семантический HTML и зачем он нужен?',
    questionEn: 'What is semantic HTML and why does it matter?',
    answerRu: 'Семантический HTML — использование тегов по их смысловому назначению: <header>, <nav>, <main>, <article>, <section>, <footer>. Преимущества: лучшая индексация поисковиками, доступность для скринридеров, читаемость кода.',
    answerEn: 'Semantic HTML means using tags according to their intended meaning: <header>, <nav>, <main>, <article>, <section>, <footer>. Benefits: better search engine indexing, accessibility for screen readers, and more readable code.',
  },
  {
    id: 'html-002',
    difficulty: 'EASY',
    order: 2,
    tags: ['semantics'],
    questionRu: 'В чём разница между <div> и семантическими тегами?',
    questionEn: 'What is the difference between <div> and semantic tags?',
    answerRu: '<div> — контейнер без смысла, только для стилизации/группировки. Семантические теги несут значение: <article> — самостоятельный контент, <section> — тематическая группа, <aside> — боковой контент. Скринридеры и поисковики понимают структуру через семантику.',
    answerEn: '<div> is a meaningless container used only for styling or grouping. Semantic tags carry meaning: <article> is standalone content, <section> is a thematic group, <aside> is supplementary content. Screen readers and search engines understand page structure through semantics.',
  },
  {
    id: 'html-003',
    difficulty: 'EASY',
    order: 3,
    tags: ['semantics'],
    questionRu: 'В чём разница между <section>, <article> и <div>?',
    questionEn: 'What is the difference between <section>, <article>, and <div>?',
    answerRu: '<article> — независимый самодостаточный контент (пост, новость, комментарий), который имеет смысл вне контекста страницы. <section> — тематическая группа контента внутри страницы, обычно с заголовком. <div> — нейтральный контейнер без семантики.',
    answerEn: '<article> is independent, self-contained content (a post, news item, or comment) that makes sense on its own outside the page context. <section> is a thematic group of content within a page, usually with a heading. <div> is a neutral container with no semantic meaning.',
  },
  {
    id: 'html-004',
    difficulty: 'EASY',
    order: 4,
    tags: ['semantics'],
    questionRu: 'Что такое DOCTYPE и зачем он нужен?',
    questionEn: 'What is DOCTYPE and why is it needed?',
    answerRu: 'DOCTYPE сообщает браузеру версию HTML. <!DOCTYPE html> — декларация HTML5, включает стандартный режим рендеринга (standards mode). Без DOCTYPE браузер переходит в quirks mode — имитирует баги старых браузеров. Всегда должен быть первой строкой документа.',
    answerEn: 'DOCTYPE tells the browser which version of HTML is being used. <!DOCTYPE html> is the HTML5 declaration that enables standards mode rendering. Without DOCTYPE, the browser switches to quirks mode, which emulates bugs of old browsers. It must always be the first line of the document.',
  },
  {
    id: 'html-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['semantics'],
    questionRu: 'В чём разница между <script>, <script defer> и <script async>?',
    questionEn: 'What is the difference between <script>, <script defer>, and <script async>?',
    answerRu: 'Обычный <script>: останавливает парсинг HTML, загружает и выполняет скрипт. defer: загружает параллельно, выполняет после парсинга HTML, сохраняет порядок. async: загружает параллельно, выполняет сразу после загрузки, порядок не гарантирован. defer предпочтителен для большинства скриптов.',
    answerEn: 'Plain <script>: blocks HTML parsing while downloading and executing the script. defer: downloads in parallel and executes after HTML parsing is complete, preserving order. async: downloads in parallel and executes immediately after downloading, with no guaranteed order. defer is preferred for most scripts.',
  },
  {
    id: 'html-006',
    difficulty: 'EASY',
    order: 6,
    tags: ['semantics'],
    questionRu: 'Что такое data-атрибуты и когда их использовать?',
    questionEn: 'What are data attributes and when should you use them?',
    answerRu: 'data-* атрибуты хранят пользовательские данные прямо в HTML: <div data-user-id="42">. Доступны через dataset: el.dataset.userId. Используются для передачи данных из HTML в JS без скрытых полей. Не подходят для критичных данных — видны в DOM.',
    answerEn: 'data-* attributes store custom data directly in HTML: <div data-user-id="42">. They are accessible via dataset: el.dataset.userId. Used to pass data from HTML to JS without hidden fields. Not suitable for sensitive data — they are visible in the DOM.',
  },
  {
    id: 'html-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['semantics'],
    questionRu: 'В чём разница между <strong> и <b>, <em> и <i>?',
    questionEn: 'What is the difference between <strong> and <b>, and between <em> and <i>?',
    answerRu: '<strong> — семантически важный текст (скринридер акцентирует). <b> — визуально жирный без семантики. <em> — акцент, смысл меняется от интонации (скринридер меняет ударение). <i> — курсив без семантики, для технических терминов, иностранных слов. Предпочитать семантические теги.',
    answerEn: '<strong> marks semantically important text (screen readers emphasize it). <b> is visually bold with no semantic meaning. <em> conveys stress emphasis where the meaning shifts with intonation (screen readers change inflection). <i> is italic without semantics, used for technical terms or foreign words. Prefer semantic tags.',
  },
  {
    id: 'html-008',
    difficulty: 'EASY',
    order: 8,
    tags: ['forms'],
    questionRu: 'Какие типы input существуют в HTML5?',
    questionEn: 'What input types are available in HTML5?',
    answerRu: 'Основные: text, password, email, number, tel, url, search, date, time, datetime-local, month, week, color, range, file, checkbox, radio, submit, reset, button, hidden. Типы обеспечивают нативную валидацию, правильную клавиатуру на мобильных и семантику.',
    answerEn: 'The main types are: text, password, email, number, tel, url, search, date, time, datetime-local, month, week, color, range, file, checkbox, radio, submit, reset, button, and hidden. Input types provide native validation, the correct keyboard on mobile devices, and semantic meaning.',
  },
  {
    id: 'html-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['forms'],
    questionRu: 'Что такое нативная валидация форм в HTML?',
    questionEn: 'What is native HTML form validation?',
    answerRu: 'HTML5 предоставляет атрибуты валидации: required, minlength/maxlength, min/max, pattern (regex), type. Браузер валидирует перед отправкой и показывает встроенные сообщения. Кастомизация через Constraint Validation API: setCustomValidity(), checkValidity().',
    answerEn: 'HTML5 provides validation attributes: required, minlength/maxlength, min/max, pattern (regex), and type. The browser validates before form submission and displays built-in error messages. Customization is done via the Constraint Validation API: setCustomValidity() and checkValidity().',
  },
  {
    id: 'html-010',
    difficulty: 'EASY',
    order: 10,
    tags: ['forms'],
    questionRu: 'В чём разница между method GET и POST в форме?',
    questionEn: 'What is the difference between GET and POST methods in a form?',
    answerRu: 'GET: данные передаются в URL (query string), видны пользователю, кешируются, ограничены по длине. Используется для поиска, фильтров. POST: данные в теле запроса, не видны в URL, нет ограничения размера. Для отправки данных, логина, загрузки файлов.',
    answerEn: 'GET: data is passed in the URL (query string), visible to the user, can be cached, and has length limits. Used for search and filters. POST: data is sent in the request body, not visible in the URL, and has no size restriction. Used for submitting data, login, and file uploads.',
  },
  {
    id: 'html-011',
    difficulty: 'EASY',
    order: 11,
    tags: ['forms'],
    questionRu: 'Что такое <label> и почему важно его использовать?',
    questionEn: 'What is <label> and why is it important to use it?',
    answerRu: '<label for="id"> связывает текст с полем ввода. При клике на label фокус переходит на input. Критично для доступности: скринридер объявляет label при фокусе на поле. Можно использовать обёртку: <label><input type="checkbox"> Согласен</label> без атрибута for.',
    answerEn: '<label for="id"> associates a text description with an input field. Clicking the label moves focus to the input. It is critical for accessibility: a screen reader announces the label when the field receives focus. You can also use the wrapper pattern: <label><input type="checkbox"> Agree</label> without a for attribute.',
  },
  {
    id: 'html-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['forms'],
    questionRu: 'Что такое fieldset и legend?',
    questionEn: 'What are fieldset and legend?',
    answerRu: '<fieldset> группирует связанные элементы формы. <legend> даёт группе название. Скринридер читает legend перед каждым полем группы. Особенно важно для групп radio/checkbox. fieldset можно отключить атрибутом disabled — отключит все вложенные поля.',
    answerEn: '<fieldset> groups related form elements together. <legend> gives the group a name. A screen reader reads the legend before each field in the group. This is especially important for radio/checkbox groups. fieldset can be disabled with the disabled attribute, which disables all nested fields.',
  },
  {
    id: 'html-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['forms'],
    questionRu: 'Как работает атрибут autocomplete?',
    questionEn: 'How does the autocomplete attribute work?',
    answerRu: 'autocomplete управляет автозаполнением браузера. autocomplete="off" — отключить. Конкретные значения: "name", "email", "current-password", "new-password", "one-time-code" и др. Правильные значения улучшают UX и помогают менеджерам паролей.',
    answerEn: 'autocomplete controls browser autofill behavior. autocomplete="off" disables it. Specific token values include: "name", "email", "current-password", "new-password", "one-time-code", and others. Using the correct values improves UX and helps password managers work correctly.',
  },
  {
    id: 'html-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['accessibility'],
    questionRu: 'Что такое ARIA и когда её использовать?',
    questionEn: 'What is ARIA and when should you use it?',
    answerRu: 'ARIA (Accessible Rich Internet Applications) — атрибуты для описания семантики интерактивных элементов скринридерам: role, aria-label, aria-hidden, aria-expanded и др. Правило: сначала нативный HTML (button вместо div+role), ARIA только если нативного решения нет.',
    answerEn: 'ARIA (Accessible Rich Internet Applications) is a set of attributes for describing the semantics of interactive elements to screen readers: role, aria-label, aria-hidden, aria-expanded, and others. The rule is: prefer native HTML first (button instead of div+role), and use ARIA only when there is no native solution.',
  },
  {
    id: 'html-015',
    difficulty: 'EASY',
    order: 15,
    tags: ['accessibility'],
    questionRu: 'Что такое alt у изображений и как правильно заполнять?',
    questionEn: 'What is the alt attribute on images and how should it be filled in correctly?',
    answerRu: 'alt — текстовая альтернатива изображения для скринридеров и при ошибке загрузки. Правила: описывать смысл (не «картинка»), декоративные изображения — alt="" (скринридер пропустит), иконки-кнопки — описывать действие. Пустой alt лучше отсутствующего.',
    answerEn: 'alt is a text alternative for an image, used by screen readers and displayed when the image fails to load. Rules: describe the meaning (not just "image"), decorative images should have alt="" (screen readers will skip them), icon buttons should describe the action. An empty alt is better than a missing one.',
  },
  {
    id: 'html-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['accessibility'],
    questionRu: 'Что такое tabindex и как управлять порядком фокуса?',
    questionEn: 'What is tabindex and how do you control focus order?',
    answerRu: 'tabindex управляет навигацией с клавиатуры. tabindex="0" — добавить в естественный порядок. tabindex="-1" — программный фокус без Tab-навигации (для модалок). tabindex="1+" — задать порядок явно (антипаттерн, нарушает естественный поток). Нативные элементы (button, a, input) фокусируются по умолчанию.',
    answerEn: 'tabindex controls keyboard navigation. tabindex="0" adds an element to the natural tab order. tabindex="-1" allows programmatic focus without Tab navigation (useful for modals). tabindex="1+" sets an explicit order (an anti-pattern that disrupts the natural flow). Native elements (button, a, input) are focusable by default.',
  },
  {
    id: 'html-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['accessibility'],
    questionRu: 'В чём разница между aria-label, aria-labelledby и aria-describedby?',
    questionEn: 'What is the difference between aria-label, aria-labelledby, and aria-describedby?',
    answerRu: 'aria-label: задаёт текстовое название элемента напрямую. aria-labelledby: ссылается на id элемента, чей текст будет названием. aria-describedby: ссылается на id элемента с дополнительным описанием (читается после label). labelledby приоритетнее label.',
    answerEn: 'aria-label: provides a text name for the element directly. aria-labelledby: references the id of an element whose text content will serve as the name. aria-describedby: references the id of an element with additional description (read after the label). labelledby takes precedence over label.',
  },
  {
    id: 'html-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['accessibility'],
    questionRu: 'Что такое skip links?',
    questionEn: 'What are skip links?',
    answerRu: 'Skip link — первая ссылка на странице «Перейти к основному контенту», видимая при фокусе с клавиатуры. Позволяет пропустить навигацию и сразу перейти к <main>. Реализуется: <a href="#main" class="skip-link">Skip to content</a> с CSS visibility на :focus.',
    answerEn: 'A skip link is the first link on a page — "Skip to main content" — visible when focused via keyboard. It lets users bypass navigation and jump directly to <main>. Implemented as: <a href="#main" class="skip-link">Skip to content</a> with CSS visibility toggled on :focus.',
  },
  {
    id: 'html-019',
    difficulty: 'EASY',
    order: 19,
    tags: ['accessibility'],
    questionRu: 'Почему нельзя использовать div вместо button для кликабельных элементов?',
    questionEn: 'Why should you not use a div instead of a button for clickable elements?',
    answerRu: 'button нативно: фокусируется с клавиатуры, активируется Enter/Space, имеет role="button" для скринридеров, поддерживает disabled. div нужно вручную добавлять tabindex, role, обработчики keydown, aria-disabled. Нативный элемент надёжнее и доступнее.',
    answerEn: 'A button natively: receives keyboard focus, is activated by Enter/Space, has role="button" for screen readers, and supports the disabled attribute. A div requires manually adding tabindex, role, keydown handlers, and aria-disabled. The native element is more reliable and accessible.',
  },
  {
    id: 'html-020',
    difficulty: 'MEDIUM',
    order: 20,
    tags: ['seo'],
    questionRu: 'Какие мета-теги важны для SEO?',
    questionEn: 'Which meta tags are important for SEO?',
    answerRu: '<title> — самый важный, отображается в результатах поиска. <meta name="description"> — описание в сниппете. <meta name="robots"> — управление индексацией. Open Graph теги (og:title, og:image) для соцсетей. canonical — указывает основной URL при дублях.',
    answerEn: '<title> is the most important — it appears in search results. <meta name="description"> provides the snippet description. <meta name="robots"> controls indexing behavior. Open Graph tags (og:title, og:image) are used for social media sharing. canonical specifies the canonical URL when duplicate pages exist.',
  },
  {
    id: 'html-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['seo'],
    questionRu: 'Что такое viewport meta тег?',
    questionEn: 'What is the viewport meta tag?',
    answerRu: '<meta name="viewport" content="width=device-width, initial-scale=1"> — обязателен для адаптивных сайтов. Без него мобильный браузер рендерит страницу как десктоп и масштабирует. width=device-width устанавливает ширину viewport равной ширине экрана устройства.',
    answerEn: '<meta name="viewport" content="width=device-width, initial-scale=1"> is required for responsive websites. Without it, mobile browsers render the page as a desktop layout and scale it down. width=device-width sets the viewport width equal to the device screen width.',
  },
  {
    id: 'html-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['performance'],
    questionRu: 'Что такое <link rel="preload"> и <link rel="prefetch">?',
    questionEn: 'What are <link rel="preload"> and <link rel="prefetch">?',
    answerRu: 'preload — загрузить ресурс как можно скорее, нужен для текущей страницы (критичные шрифты, CSS, JS). prefetch — загрузить с низким приоритетом для будущей навигации. preconnect — заранее установить соединение с доменом. Правильное использование ускоряет LCP.',
    answerEn: 'preload — fetch a resource as soon as possible; used for resources needed on the current page (critical fonts, CSS, JS). prefetch — fetch with low priority for future navigation. preconnect — establish a connection to a domain in advance. Using these correctly improves LCP.',
  },
  {
    id: 'html-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['performance'],
    questionRu: 'Что такое атрибуты loading="lazy" и decoding="async" у изображений?',
    questionEn: 'What are the loading="lazy" and decoding="async" attributes on images?',
    answerRu: 'loading="lazy" откладывает загрузку изображения до приближения к viewport — нативная ленивая загрузка без JS. loading="eager" — загрузить сразу (по умолчанию). decoding="async" разрешает браузеру декодировать изображение асинхронно, не блокируя рендеринг.',
    answerEn: 'loading="lazy" defers loading an image until it is near the viewport — native lazy loading without JS. loading="eager" loads the image immediately (the default). decoding="async" allows the browser to decode the image asynchronously without blocking rendering.',
  },
  {
    id: 'html-024',
    difficulty: 'MEDIUM',
    order: 24,
    tags: ['performance'],
    questionRu: 'Что такое <picture> и srcset у изображений?',
    questionEn: 'What are <picture> and srcset on images?',
    answerRu: '<picture> и srcset позволяют задать разные изображения для разных условий. srcset с sizes — разные разрешения одного изображения, браузер выбирает оптимальное. <picture> с <source media> — разные изображения для разных breakpoint или форматов (WebP с fallback на JPEG).',
    answerEn: '<picture> and srcset allow you to provide different images for different conditions. srcset with sizes offers multiple resolutions of the same image and lets the browser pick the optimal one. <picture> with <source media> serves different images for different breakpoints or formats (WebP with a JPEG fallback).',
  },
];
