import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'js-001',
    difficulty: 'EASY',
    questionRu: 'Какие типы данных существуют в JavaScript?',
    questionEn: 'Какие типы данных существуют в JavaScript?',
    answerRu: 'Примитивные: string, number, bigint, boolean, undefined, null, symbol. Ссылочный: object (включает массивы, функции, объекты).',
    answerEn: 'Примитивные: string, number, bigint, boolean, undefined, null, symbol. Ссылочный: object (включает массивы, функции, объекты).',
    tags: ['types', 'operators'],
    order: 1,
  },
  {
    id: 'js-002',
    difficulty: 'EASY',
    questionRu: 'В чём разница между == и ===?',
    questionEn: 'В чём разница между == и ===?',
    answerRu: '== выполняет приведение типов перед сравнением (например, "5" == 5 → true). === сравнивает без приведения типов — значение и тип должны совпадать ("5" === 5 → false).',
    answerEn: '== выполняет приведение типов перед сравнением (например, "5" == 5 → true). === сравнивает без приведения типов — значение и тип должны совпадать ("5" === 5 → false).',
    tags: ['types', 'operators'],
    order: 2,
  },
  {
    id: 'js-003',
    difficulty: 'EASY',
    questionRu: 'Что такое typeof null и почему?',
    questionEn: 'Что такое typeof null и почему?',
    answerRu: 'typeof null возвращает "object" — это исторический баг JavaScript с первой версии. null является примитивом, но из-за внутреннего представления в двоичном коде был отнесён к объектам.',
    answerEn: 'typeof null возвращает "object" — это исторический баг JavaScript с первой версии. null является примитивом, но из-за внутреннего представления в двоичном коде был отнесён к объектам.',
    tags: ['types', 'operators'],
    order: 3,
  },
  {
    id: 'js-004',
    difficulty: 'EASY',
    questionRu: 'Что такое NaN и как проверить, является ли значение NaN?',
    questionEn: 'Что такое NaN и как проверить, является ли значение NaN?',
    answerRu: 'NaN (Not a Number) — результат некорректной математической операции. Особенность: NaN !== NaN. Для проверки используют Number.isNaN(value) (строгий) или isNaN(value) (с приведением типов).',
    answerEn: 'NaN (Not a Number) — результат некорректной математической операции. Особенность: NaN !== NaN. Для проверки используют Number.isNaN(value) (строгий) или isNaN(value) (с приведением типов).',
    tags: ['types', 'operators'],
    order: 4,
  },
  {
    id: 'js-005',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает приведение типов в JavaScript?',
    questionEn: 'Как работает приведение типов в JavaScript?',
    answerRu: 'JS автоматически приводит типы в определённых контекстах. Явное: Number("5"), String(5), Boolean(0). Неявное: "5" * 2 → 10, [] + {} → "[object Object]". Правила: при + с строкой — конкатенация, при -, *, / — числовое приведение.',
    answerEn: 'JS автоматически приводит типы в определённых контекстах. Явное: Number("5"), String(5), Boolean(0). Неявное: "5" * 2 → 10, [] + {} → "[object Object]". Правила: при + с строкой — конкатенация, при -, *, / — числовое приведение.',
    tags: ['types', 'operators'],
    order: 5,
  },
  {
    id: 'js-006',
    difficulty: 'EASY',
    questionRu: 'В чём разница между null и undefined?',
    questionEn: 'В чём разница между null и undefined?',
    answerRu: 'undefined — переменная объявлена, но не инициализирована. null — явно присвоенное «пустое» значение. typeof undefined === "undefined", typeof null === "object". При сравнении: null == undefined → true, null === undefined → false.',
    answerEn: 'undefined — переменная объявлена, но не инициализирована. null — явно присвоенное «пустое» значение. typeof undefined === "undefined", typeof null === "object". При сравнении: null == undefined → true, null === undefined → false.',
    tags: ['types', 'operators'],
    order: 6,
  },
  {
    id: 'js-007',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое Symbol и для чего используется?',
    questionEn: 'Что такое Symbol и для чего используется?',
    answerRu: 'Symbol — уникальный примитивный тип, каждый Symbol() гарантированно уникален. Используется для создания уникальных ключей объектов, скрытых свойств (не перечисляются в for...in), и встроенных итераторов (Symbol.iterator).',
    answerEn: 'Symbol — уникальный примитивный тип, каждый Symbol() гарантированно уникален. Используется для создания уникальных ключей объектов, скрытых свойств (не перечисляются в for...in), и встроенных итераторов (Symbol.iterator).',
    tags: ['types', 'operators'],
    order: 7,
  },
  {
    id: 'js-008',
    difficulty: 'EASY',
    questionRu: 'Как работает оператор ?. (optional chaining)?',
    questionEn: 'Как работает оператор ?. (optional chaining)?',
    answerRu: 'Optional chaining (?.) позволяет безопасно обращаться к свойствам объекта, который может быть null или undefined. user?.address?.city вернёт undefined вместо ошибки, если user или address равны null/undefined.',
    answerEn: 'Optional chaining (?.) позволяет безопасно обращаться к свойствам объекта, который может быть null или undefined. user?.address?.city вернёт undefined вместо ошибки, если user или address равны null/undefined.',
    tags: ['types', 'operators'],
    order: 8,
  },
  {
    id: 'js-009',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое замыкание (closure)?',
    questionEn: 'Что такое замыкание (closure)?',
    answerRu: 'Замыкание — функция, которая запоминает переменные из внешней области видимости даже после того, как внешняя функция завершила выполнение. Пример: счётчик через замыкание сохраняет значение count между вызовами.',
    answerEn: 'Замыкание — функция, которая запоминает переменные из внешней области видимости даже после того, как внешняя функция завершила выполнение. Пример: счётчик через замыкание сохраняет значение count между вызовами.',
    tags: ['scope', 'closures'],
    order: 9,
  },
  {
    id: 'js-010',
    difficulty: 'EASY',
    questionRu: 'В чём разница между var, let и const?',
    questionEn: 'В чём разница между var, let и const?',
    answerRu: 'var: функциональная область видимости, поднимается (hoisting) с инициализацией undefined, можно переопределить. let: блочная область видимости, поднимается без инициализации (TDZ), нельзя переопределить. const: то же что let, но нельзя переназначить (объект мутировать можно).',
    answerEn: 'var: функциональная область видимости, поднимается (hoisting) с инициализацией undefined, можно переопределить. let: блочная область видимости, поднимается без инициализации (TDZ), нельзя переопределить. const: то же что let, но нельзя переназначить (объект мутировать можно).',
    tags: ['scope', 'closures'],
    order: 10,
  },
  {
    id: 'js-011',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое Temporal Dead Zone (TDZ)?',
    questionEn: 'Что такое Temporal Dead Zone (TDZ)?',
    answerRu: 'TDZ — промежуток от начала блока до строки объявления переменной let/const, где переменная существует, но недоступна. Обращение к ней в этот период выбрасывает ReferenceError.',
    answerEn: 'TDZ — промежуток от начала блока до строки объявления переменной let/const, где переменная существует, но недоступна. Обращение к ней в этот период выбрасывает ReferenceError.',
    tags: ['scope', 'closures'],
    order: 11,
  },
  {
    id: 'js-012',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое IIFE и зачем используется?',
    questionEn: 'Что такое IIFE и зачем используется?',
    answerRu: 'IIFE (Immediately Invoked Function Expression) — функция, которая выполняется сразу после объявления: (function() { ... })(). Используется для изоляции области видимости, предотвращения загрязнения глобального пространства имён.',
    answerEn: 'IIFE (Immediately Invoked Function Expression) — функция, которая выполняется сразу после объявления: (function() { ... })(). Используется для изоляции области видимости, предотвращения загрязнения глобального пространства имён.',
    tags: ['scope', 'closures'],
    order: 12,
  },
  {
    id: 'js-013',
    difficulty: 'MEDIUM',
    questionRu: 'Почему в цикле с var все функции выводят одно значение?',
    questionEn: 'Почему в цикле с var все функции выводят одно значение?',
    answerRu: 'Из-за того, что var имеет функциональную область видимости, все итерации делят одну переменную i. К моменту вызова колбэков цикл уже завершён и i равна финальному значению. Решение: использовать let или IIFE.',
    answerEn: 'Из-за того, что var имеет функциональную область видимости, все итерации делят одну переменную i. К моменту вызова колбэков цикл уже завершён и i равна финальному значению. Решение: использовать let или IIFE.',
    tags: ['scope', 'closures'],
    order: 13,
  },
  {
    id: 'js-014',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое лексическая область видимости?',
    questionEn: 'Что такое лексическая область видимости?',
    answerRu: 'Лексическая (статическая) область видимости означает, что область видимости функции определяется местом её объявления в коде, а не местом вызова. JavaScript использует именно лексическую область видимости.',
    answerEn: 'Лексическая (статическая) область видимости означает, что область видимости функции определяется местом её объявления в коде, а не местом вызова. JavaScript использует именно лексическую область видимости.',
    tags: ['scope', 'closures'],
    order: 14,
  },
  {
    id: 'js-015',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое hoisting (поднятие)?',
    questionEn: 'Что такое hoisting (поднятие)?',
    answerRu: 'Hoisting — механизм, при котором объявления переменных и функций перемещаются в начало своей области видимости на этапе компиляции. function declaration поднимается целиком. var поднимается с undefined. let/const поднимаются, но остаются в TDZ.',
    answerEn: 'Hoisting — механизм, при котором объявления переменных и функций перемещаются в начало своей области видимости на этапе компиляции. function declaration поднимается целиком. var поднимается с undefined. let/const поднимаются, но остаются в TDZ.',
    tags: ['scope', 'closures'],
    order: 15,
  },
  {
    id: 'js-016',
    difficulty: 'MEDIUM',
    questionRu: 'Как создать приватные переменные в JavaScript?',
    questionEn: 'Как создать приватные переменные в JavaScript?',
    answerRu: 'Несколько способов: 1) Замыкания — переменная внутри функции недоступна снаружи. 2) WeakMap для хранения приватного состояния. 3) Приватные поля класса через # (ES2022): class A { #x = 0; }.',
    answerEn: 'Несколько способов: 1) Замыкания — переменная внутри функции недоступна снаружи. 2) WeakMap для хранения приватного состояния. 3) Приватные поля класса через # (ES2022): class A { #x = 0; }.',
    tags: ['scope', 'closures'],
    order: 16,
  },
  {
    id: 'js-017',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое прототип в JavaScript?',
    questionEn: 'Что такое прототип в JavaScript?',
    answerRu: 'Каждый объект имеет скрытую ссылку [[Prototype]] на другой объект (прототип). При обращении к свойству сначала ищется в объекте, затем по цепочке прототипов вверх до null. Доступен через __proto__ или Object.getPrototypeOf().',
    answerEn: 'Каждый объект имеет скрытую ссылку [[Prototype]] на другой объект (прототип). При обращении к свойству сначала ищется в объекте, затем по цепочке прототипов вверх до null. Доступен через __proto__ или Object.getPrototypeOf().',
    tags: ['prototype', 'inheritance'],
    order: 17,
  },
  {
    id: 'js-018',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между прототипным и классовым наследованием?',
    questionEn: 'В чём разница между прототипным и классовым наследованием?',
    answerRu: 'В JS классы (ES6) — синтаксический сахар над прототипным наследованием. При классовом наследовании (class B extends A) под капотом B.prototype.__proto__ === A.prototype. Прототипное наследование гибче: можно менять цепочку в runtime.',
    answerEn: 'В JS классы (ES6) — синтаксический сахар над прототипным наследованием. При классовом наследовании (class B extends A) под капотом B.prototype.__proto__ === A.prototype. Прототипное наследование гибче: можно менять цепочку в runtime.',
    tags: ['prototype', 'inheritance'],
    order: 18,
  },
  {
    id: 'js-019',
    difficulty: 'MEDIUM',
    questionRu: 'Что делает Object.create()?',
    questionEn: 'Что делает Object.create()?',
    answerRu: 'Object.create(proto) создаёт новый объект с указанным прототипом. Позволяет создавать объекты с точным контролем над цепочкой прототипов без конструктора. Object.create(null) создаёт объект без прототипа вообще.',
    answerEn: 'Object.create(proto) создаёт новый объект с указанным прототипом. Позволяет создавать объекты с точным контролем над цепочкой прототипов без конструктора. Object.create(null) создаёт объект без прототипа вообще.',
    tags: ['prototype', 'inheritance'],
    order: 19,
  },
  {
    id: 'js-020',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает оператор instanceof?',
    questionEn: 'Как работает оператор instanceof?',
    answerRu: 'instanceof проверяет, есть ли в цепочке прототипов объекта prototype конструктора. obj instanceof Foo проверяет: Foo.prototype === Object.getPrototypeOf(obj) (рекурсивно вверх). Можно переопределить через Symbol.hasInstance.',
    answerEn: 'instanceof проверяет, есть ли в цепочке прототипов объекта prototype конструктора. obj instanceof Foo проверяет: Foo.prototype === Object.getPrototypeOf(obj) (рекурсивно вверх). Можно переопределить через Symbol.hasInstance.',
    tags: ['prototype', 'inheritance'],
    order: 20,
  },
  {
    id: 'js-021',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое constructor property?',
    questionEn: 'Что такое constructor property?',
    answerRu: 'Свойство constructor указывает на функцию-конструктор, создавшую объект. Хранится в prototype конструктора, а не в самом объекте. При переопределении prototype нужно вручную восстановить constructor.',
    answerEn: 'Свойство constructor указывает на функцию-конструктор, создавшую объект. Хранится в prototype конструктора, а не в самом объекте. При переопределении prototype нужно вручную восстановить constructor.',
    tags: ['prototype', 'inheritance'],
    order: 21,
  },
  {
    id: 'js-022',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между hasOwnProperty и in?',
    questionEn: 'В чём разница между hasOwnProperty и in?',
    answerRu: 'hasOwnProperty() возвращает true только для собственных (не унаследованных) свойств. Оператор in проверяет весь прототипный chain, включая унаследованные. Пример: "toString" in {} → true, {}.hasOwnProperty("toString") → false.',
    answerEn: 'hasOwnProperty() возвращает true только для собственных (не унаследованных) свойств. Оператор in проверяет весь прототипный chain, включая унаследованные. Пример: "toString" in {} → true, {}.hasOwnProperty("toString") → false.',
    tags: ['prototype', 'inheritance'],
    order: 22,
  },
  {
    id: 'js-023',
    difficulty: 'HARD',
    questionRu: 'Что такое миксины и как реализовать?',
    questionEn: 'Что такое миксины и как реализовать?',
    answerRu: 'Миксин — паттерн для копирования методов в прототип класса без наследования. Реализуется через Object.assign(Target.prototype, mixin). Позволяет добавлять поведение из нескольких источников, обходя ограничение одиночного наследования.',
    answerEn: 'Миксин — паттерн для копирования методов в прототип класса без наследования. Реализуется через Object.assign(Target.prototype, mixin). Позволяет добавлять поведение из нескольких источников, обходя ограничение одиночного наследования.',
    tags: ['prototype', 'inheritance'],
    order: 23,
  },
  {
    id: 'js-024',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает new в JavaScript?',
    questionEn: 'Как работает new в JavaScript?',
    answerRu: 'При вызове new Foo(): 1) Создаётся новый пустой объект. 2) Его [[Prototype]] устанавливается в Foo.prototype. 3) Функция-конструктор вызывается с this = новый объект. 4) Если конструктор возвращает объект — возвращается он, иначе — новый объект.',
    answerEn: 'При вызове new Foo(): 1) Создаётся новый пустой объект. 2) Его [[Prototype]] устанавливается в Foo.prototype. 3) Функция-конструктор вызывается с this = новый объект. 4) Если конструктор возвращает объект — возвращается он, иначе — новый объект.',
    tags: ['prototype', 'inheritance'],
    order: 24,
  },
  {
    id: 'js-025',
    difficulty: 'MEDIUM',
    questionRu: 'Как определяется значение this?',
    questionEn: 'Как определяется значение this?',
    answerRu: 'Зависит от способа вызова: 1) Метод объекта — this = объект. 2) Обычная функция — this = undefined (strict) или global. 3) Arrow function — this из внешнего лексического контекста. 4) new — this = новый объект. 5) call/apply/bind — явно задано.',
    answerEn: 'Зависит от способа вызова: 1) Метод объекта — this = объект. 2) Обычная функция — this = undefined (strict) или global. 3) Arrow function — this из внешнего лексического контекста. 4) new — this = новый объект. 5) call/apply/bind — явно задано.',
    tags: ['this', 'context'],
    order: 25,
  },
  {
    id: 'js-026',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между call, apply и bind?',
    questionEn: 'В чём разница между call, apply и bind?',
    answerRu: 'Все три явно устанавливают this. call(ctx, arg1, arg2) — вызывает немедленно, аргументы через запятую. apply(ctx, [args]) — вызывает немедленно, аргументы массивом. bind(ctx, arg1) — возвращает новую функцию с привязанным this, не вызывает.',
    answerEn: 'Все три явно устанавливают this. call(ctx, arg1, arg2) — вызывает немедленно, аргументы через запятую. apply(ctx, [args]) — вызывает немедленно, аргументы массивом. bind(ctx, arg1) — возвращает новую функцию с привязанным this, не вызывает.',
    tags: ['this', 'context'],
    order: 26,
  },
  {
    id: 'js-027',
    difficulty: 'MEDIUM',
    questionRu: 'Почему стрелочные функции не имеют своего this?',
    questionEn: 'Почему стрелочные функции не имеют своего this?',
    answerRu: 'Arrow functions не создают собственный контекст выполнения. this в них берётся из ближайшего внешнего лексического окружения в момент объявления и не меняется при вызове. Поэтому call/apply/bind не могут изменить this стрелочной функции.',
    answerEn: 'Arrow functions не создают собственный контекст выполнения. this в них берётся из ближайшего внешнего лексического окружения в момент объявления и не меняется при вызове. Поэтому call/apply/bind не могут изменить this стрелочной функции.',
    tags: ['this', 'context'],
    order: 27,
  },
  {
    id: 'js-028',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое потеря контекста и как её избежать?',
    questionEn: 'Что такое потеря контекста и как её избежать?',
    answerRu: 'Потеря контекста — when метод передаётся как колбэк, this становится undefined или global. Решения: 1) bind: setTimeout(this.method.bind(this), 0). 2) Стрелочная функция: setTimeout(() => this.method(), 0). 3) Сохранить: const self = this.',
    answerEn: 'Потеря контекста — when метод передаётся как колбэк, this становится undefined или global. Решения: 1) bind: setTimeout(this.method.bind(this), 0). 2) Стрелочная функция: setTimeout(() => this.method(), 0). 3) Сохранить: const self = this.',
    tags: ['this', 'context'],
    order: 28,
  },
  {
    id: 'js-029',
    difficulty: 'MEDIUM',
    questionRu: 'Каков this в обработчике события?',
    questionEn: 'Каков this в обработчике события?',
    answerRu: 'В обычной функции-обработчике this указывает на DOM-элемент, к которому прикреплён обработчик. В стрелочной функции this берётся из внешнего контекста (например, класса). Поэтому в классах часто используют стрелочные методы или bind.',
    answerEn: 'В обычной функции-обработчике this указывает на DOM-элемент, к которому прикреплён обработчик. В стрелочной функции this берётся из внешнего контекста (например, класса). Поэтому в классах часто используют стрелочные методы или bind.',
    tags: ['this', 'context'],
    order: 29,
  },
  {
    id: 'js-030',
    difficulty: 'EASY',
    questionRu: 'Что вернёт this в глобальном контексте?',
    questionEn: 'Что вернёт this в глобальном контексте?',
    answerRu: 'В браузере в глобальном контексте this === window. В Node.js на верхнем уровне this === module.exports (пустой объект). В строгом режиме ("use strict") this в функции, вызванной без контекста, === undefined.',
    answerEn: 'В браузере в глобальном контексте this === window. В Node.js на верхнем уровне this === module.exports (пустой объект). В строгом режиме ("use strict") this в функции, вызванной без контекста, === undefined.',
    tags: ['this', 'context'],
    order: 30,
  },
  {
    id: 'js-031',
    difficulty: 'MEDIUM',
    questionRu: 'Можно ли изменить this стрелочной функции через bind?',
    questionEn: 'Можно ли изменить this стрелочной функции через bind?',
    answerRu: 'Нет. bind, call и apply не могут изменить this стрелочной функции — он всегда берётся из лексического окружения на момент создания функции. bind вернёт новую функцию, но this в ней останется прежним.',
    answerEn: 'Нет. bind, call и apply не могут изменить this стрелочной функции — он всегда берётся из лексического окружения на момент создания функции. bind вернёт новую функцию, но this в ней останется прежним.',
    tags: ['this', 'context'],
    order: 31,
  },
  {
    id: 'js-032',
    difficulty: 'MEDIUM',
    questionRu: 'Как this работает в классах ES6?',
    questionEn: 'Как this работает в классах ES6?',
    answerRu: 'В методах класса this указывает на экземпляр. В constructor this — создаваемый объект. Если метод передать как колбэк — контекст теряется. Решение: объявлять методы как стрелочные поля (arrow field methods) или использовать bind в конструкторе.',
    answerEn: 'В методах класса this указывает на экземпляр. В constructor this — создаваемый объект. Если метод передать как колбэк — контекст теряется. Решение: объявлять методы как стрелочные поля (arrow field methods) или использовать bind в конструкторе.',
    tags: ['this', 'context'],
    order: 32,
  },
  {
    id: 'js-033',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое Event Loop?',
    questionEn: 'Что такое Event Loop?',
    answerRu: 'Event Loop — механизм выполнения асинхронного кода в JS. Состоит из: Call Stack (стек вызовов), Web APIs (таймеры, fetch), Callback Queue (очередь макрозадач), Microtask Queue (промисы, queueMicrotask). Цикл: выполнить стек → все микрозадачи → одну макрозадачу → рендер → повторить.',
    answerEn: 'Event Loop — механизм выполнения асинхронного кода в JS. Состоит из: Call Stack (стек вызовов), Web APIs (таймеры, fetch), Callback Queue (очередь макрозадач), Microtask Queue (промисы, queueMicrotask). Цикл: выполнить стек → все микрозадачи → одну макрозадачу → рендер → повторить.',
    tags: ['event-loop', 'async'],
    order: 33,
  },
  {
    id: 'js-034',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между микрозадачами и макрозадачами?',
    questionEn: 'В чём разница между микрозадачами и макрозадачами?',
    answerRu: 'Макрозадачи (setTimeout, setInterval, I/O): выполняется одна за итерацию цикла. Микрозадачи (Promise.then, queueMicrotask, MutationObserver): выполняются все после каждой макрозадачи и до следующего рендера. Микрозадачи имеют приоритет выше.',
    answerEn: 'Макрозадачи (setTimeout, setInterval, I/O): выполняется одна за итерацию цикла. Микрозадачи (Promise.then, queueMicrotask, MutationObserver): выполняются все после каждой макрозадачи и до следующего рендера. Микрозадачи имеют приоритет выше.',
    tags: ['event-loop', 'async'],
    order: 34,
  },
  {
    id: 'js-035',
    difficulty: 'MEDIUM',
    questionRu: 'Что выведет код: setTimeout 0, Promise.resolve, console.log?',
    questionEn: 'Что выведет код: setTimeout 0, Promise.resolve, console.log?',
    answerRu: 'Порядок: 1) синхронный console.log (Call Stack). 2) Promise.then (микрозадача). 3) setTimeout (макрозадача). Правило: синхронный код → микрозадачи → макрозадачи.',
    answerEn: 'Порядок: 1) синхронный console.log (Call Stack). 2) Promise.then (микрозадача). 3) setTimeout (макрозадача). Правило: синхронный код → микрозадачи → макрозадачи.',
    tags: ['event-loop', 'async'],
    order: 35,
  },
  {
    id: 'js-036',
    difficulty: 'EASY',
    questionRu: 'Что такое callback hell и как его избежать?',
    questionEn: 'Что такое callback hell и как его избежать?',
    answerRu: 'Callback hell — глубокая вложенность колбэков, делающая код нечитаемым. Решения: 1) Именованные функции вместо анонимных. 2) Промисы с цепочкой .then(). 3) async/await для синхронного стиля. 4) Разбиение на небольшие функции.',
    answerEn: 'Callback hell — глубокая вложенность колбэков, делающая код нечитаемым. Решения: 1) Именованные функции вместо анонимных. 2) Промисы с цепочкой .then(). 3) async/await для синхронного стиля. 4) Разбиение на небольшие функции.',
    tags: ['event-loop', 'async'],
    order: 36,
  },
  {
    id: 'js-037',
    difficulty: 'MEDIUM',
    questionRu: 'Почему JavaScript однопоточный и как справляется с асинхронностью?',
    questionEn: 'Почему JavaScript однопоточный и как справляется с асинхронностью?',
    answerRu: 'JS выполняется в одном потоке, чтобы избежать проблем конкурентности при работе с DOM. Асинхронность реализуется через Event Loop: тяжёлые операции (сеть, таймеры) делегируются Web APIs браузера/Node.js, а колбэки ставятся в очередь и выполняются позже.',
    answerEn: 'JS выполняется в одном потоке, чтобы избежать проблем конкурентности при работе с DOM. Асинхронность реализуется через Event Loop: тяжёлые операции (сеть, таймеры) делегируются Web APIs браузера/Node.js, а колбэки ставятся в очередь и выполняются позже.',
    tags: ['event-loop', 'async'],
    order: 37,
  },
  {
    id: 'js-038',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое requestAnimationFrame и чем отличается от setTimeout?',
    questionEn: 'Что такое requestAnimationFrame и чем отличается от setTimeout?',
    answerRu: 'requestAnimationFrame (rAF) вызывает колбэк перед следующим рендером браузера (~60 раз в секунду). В отличие от setTimeout(fn, 16), rAF синхронизирован с частотой обновления дисплея, не вызывается в фоновых вкладках и точнее для анимаций.',
    answerEn: 'requestAnimationFrame (rAF) вызывает колбэк перед следующим рендером браузера (~60 раз в секунду). В отличие от setTimeout(fn, 16), rAF синхронизирован с частотой обновления дисплея, не вызывается в фоновых вкладках и точнее для анимаций.',
    tags: ['event-loop', 'async'],
    order: 38,
  },
  {
    id: 'js-039',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое Web Workers?',
    questionEn: 'Что такое Web Workers?',
    answerRu: 'Web Workers — отдельные потоки в браузере для выполнения тяжёлых вычислений без блокировки основного потока. Общаются с основным потоком через postMessage/onmessage. Не имеют доступа к DOM.',
    answerEn: 'Web Workers — отдельные потоки в браузере для выполнения тяжёлых вычислений без блокировки основного потока. Общаются с основным потоком через postMessage/onmessage. Не имеют доступа к DOM.',
    tags: ['event-loop', 'async'],
    order: 39,
  },
  {
    id: 'js-040',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает setInterval и каковы его проблемы?',
    questionEn: 'Как работает setInterval и каковы его проблемы?',
    answerRu: 'setInterval(fn, n) ставит задачу в очередь каждые n мс. Проблемы: 1) Если колбэк выполняется дольше интервала, вызовы накапливаются. 2) Точность не гарантирована. 3) Не адаптируется к нагрузке. Альтернатива: рекурсивный setTimeout для динамического управления задержкой.',
    answerEn: 'setInterval(fn, n) ставит задачу в очередь каждые n мс. Проблемы: 1) Если колбэк выполняется дольше интервала, вызовы накапливаются. 2) Точность не гарантирована. 3) Не адаптируется к нагрузке. Альтернатива: рекурсивный setTimeout для динамического управления задержкой.',
    tags: ['event-loop', 'async'],
    order: 40,
  },
  {
    id: 'js-041',
    difficulty: 'HARD',
    questionRu: 'Что такое генераторы и как они связаны с асинхронностью?',
    questionEn: 'Что такое генераторы и как они связаны с асинхронностью?',
    answerRu: 'Генератор (function*) — функция, которую можно приостанавливать через yield и возобновлять. До появления async/await генераторы с co-библиотеками использовались для асинхронного кода. Сейчас актуальны для ленивых коллекций и бесконечных последовательностей.',
    answerEn: 'Генератор (function*) — функция, которую можно приостанавливать через yield и возобновлять. До появления async/await генераторы с co-библиотеками использовались для асинхронного кода. Сейчас актуальны для ленивых коллекций и бесконечных последовательностей.',
    tags: ['event-loop', 'async'],
    order: 41,
  },
  {
    id: 'js-042',
    difficulty: 'HARD',
    questionRu: 'Что такое queueMicrotask?',
    questionEn: 'Что такое queueMicrotask?',
    answerRu: 'queueMicrotask(fn) добавляет функцию в очередь микрозадач напрямую, без создания промиса. Полезно, когда нужно отложить выполнение до конца текущей задачи, но с приоритетом выше setTimeout. Аналогично Promise.resolve().then(fn), но более явно.',
    answerEn: 'queueMicrotask(fn) добавляет функцию в очередь микрозадач напрямую, без создания промиса. Полезно, когда нужно отложить выполнение до конца текущей задачи, но с приоритетом выше setTimeout. Аналогично Promise.resolve().then(fn), но более явно.',
    tags: ['event-loop', 'async'],
    order: 42,
  },
  {
    id: 'js-043',
    difficulty: 'EASY',
    questionRu: 'Что такое Promise и какие у него состояния?',
    questionEn: 'Что такое Promise и какие у него состояния?',
    answerRu: 'Promise — объект, представляющий результат асинхронной операции. Три состояния: pending (ожидание), fulfilled (выполнен успешно), rejected (отклонён). Переход состояния необратим. Создаётся через new Promise((resolve, reject) => ...).',
    answerEn: 'Promise — объект, представляющий результат асинхронной операции. Три состояния: pending (ожидание), fulfilled (выполнен успешно), rejected (отклонён). Переход состояния необратим. Создаётся через new Promise((resolve, reject) => ...).',
    tags: ['promises', 'async-await'],
    order: 43,
  },
  {
    id: 'js-044',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между Promise.all, Promise.allSettled, Promise.race, Promise.any?',
    questionEn: 'В чём разница между Promise.all, Promise.allSettled, Promise.race, Promise.any?',
    answerRu: 'Promise.all: ждёт все, отклоняется при первой ошибке. Promise.allSettled: ждёт все, возвращает статус каждого. Promise.race: возвращает первый завершившийся (успех или ошибка). Promise.any: возвращает первый успешный, ошибка только если все отклонены.',
    answerEn: 'Promise.all: ждёт все, отклоняется при первой ошибке. Promise.allSettled: ждёт все, возвращает статус каждого. Promise.race: возвращает первый завершившийся (успех или ошибка). Promise.any: возвращает первый успешный, ошибка только если все отклонены.',
    tags: ['promises', 'async-await'],
    order: 44,
  },
  {
    id: 'js-045',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает цепочка .then()?',
    questionEn: 'Как работает цепочка .then()?',
    answerRu: '.then() возвращает новый Promise. Если обработчик возвращает значение — следующий .then() получает его. Если возвращает Promise — цепочка ждёт его завершения. Ошибки перехватываются ближайшим .catch() ниже по цепочке.',
    answerEn: '.then() возвращает новый Promise. Если обработчик возвращает значение — следующий .then() получает его. Если возвращает Promise — цепочка ждёт его завершения. Ошибки перехватываются ближайшим .catch() ниже по цепочке.',
    tags: ['promises', 'async-await'],
    order: 45,
  },
  {
    id: 'js-046',
    difficulty: 'EASY',
    questionRu: 'Что такое async/await?',
    questionEn: 'Что такое async/await?',
    answerRu: 'async/await — синтаксический сахар над промисами. async функция всегда возвращает Promise. await приостанавливает выполнение функции до разрешения промиса. Делает асинхронный код похожим на синхронный, упрощает чтение и обработку ошибок через try/catch.',
    answerEn: 'async/await — синтаксический сахар над промисами. async функция всегда возвращает Promise. await приостанавливает выполнение функции до разрешения промиса. Делает асинхронный код похожим на синхронный, упрощает чтение и обработку ошибок через try/catch.',
    tags: ['promises', 'async-await'],
    order: 46,
  },
  {
    id: 'js-047',
    difficulty: 'MEDIUM',
    questionRu: 'Как обрабатывать ошибки в async/await?',
    questionEn: 'Как обрабатывать ошибки в async/await?',
    answerRu: 'Три способа: 1) try/catch вокруг await. 2) .catch() после вызова async-функции: asyncFn().catch(err => ...). 3) Обёртка-хелпер to(promise), возвращающий [error, data]. try/catch предпочтителен для читаемости.',
    answerEn: 'Три способа: 1) try/catch вокруг await. 2) .catch() после вызова async-функции: asyncFn().catch(err => ...). 3) Обёртка-хелпер to(promise), возвращающий [error, data]. try/catch предпочтителен для читаемости.',
    tags: ['promises', 'async-await'],
    order: 47,
  },
  {
    id: 'js-048',
    difficulty: 'MEDIUM',
    questionRu: 'Как выполнить несколько промисов параллельно с async/await?',
    questionEn: 'Как выполнить несколько промисов параллельно с async/await?',
    answerRu: 'Не использовать await последовательно — это последовательное выполнение. Для параллельного: const [a, b] = await Promise.all([fetchA(), fetchB()]). Или стартовать оба без await, потом ждать: const pA = fetchA(); const pB = fetchB(); await Promise.all([pA, pB]).',
    answerEn: 'Не использовать await последовательно — это последовательное выполнение. Для параллельного: const [a, b] = await Promise.all([fetchA(), fetchB()]). Или стартовать оба без await, потом ждать: const pA = fetchA(); const pB = fetchB(); await Promise.all([pA, pB]).',
    tags: ['promises', 'async-await'],
    order: 48,
  },
  {
    id: 'js-049',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое Promise chaining vs async/await — когда что использовать?',
    questionEn: 'Что такое Promise chaining vs async/await — когда что использовать?',
    answerRu: 'Цепочки .then() удобны для простых трансформаций данных и когда нужно явно видеть поток. async/await лучше для сложной логики с ветвлениями, циклами, try/catch. На практике часто смешивают: async/await внутри + Promise.all для параллелизма.',
    answerEn: 'Цепочки .then() удобны для простых трансформаций данных и когда нужно явно видеть поток. async/await лучше для сложной логики с ветвлениями, циклами, try/catch. На практике часто смешивают: async/await внутри + Promise.all для параллелизма.',
    tags: ['promises', 'async-await'],
    order: 49,
  },
  {
    id: 'js-050',
    difficulty: 'MEDIUM',
    questionRu: 'Что произойдёт, если не обработать rejected Promise?',
    questionEn: 'Что произойдёт, если не обработать rejected Promise?',
    answerRu: 'В браузере срабатывает событие unhandledrejection. В Node.js — UnhandledPromiseRejectionWarning (в новых версиях — завершение процесса). Всегда нужно обрабатывать ошибки: .catch() или try/catch. Глобальный обработчик: window.addEventListener("unhandledrejection", ...).',
    answerEn: 'В браузере срабатывает событие unhandledrejection. В Node.js — UnhandledPromiseRejectionWarning (в новых версиях — завершение процесса). Всегда нужно обрабатывать ошибки: .catch() или try/catch. Глобальный обработчик: window.addEventListener("unhandledrejection", ...).',
    tags: ['promises', 'async-await'],
    order: 50,
  },
  {
    id: 'js-051',
    difficulty: 'MEDIUM',
    questionRu: 'Можно ли использовать await вне async функции?',
    questionEn: 'Можно ли использовать await вне async функции?',
    answerRu: 'В ES2022 появился Top-level await — можно использовать await на верхнем уровне ES-модуля (.mjs или type="module"). В обычных скриптах — нельзя. В Node.js поддерживается в .mjs файлах или с "type": "module" в package.json.',
    answerEn: 'В ES2022 появился Top-level await — можно использовать await на верхнем уровне ES-модуля (.mjs или type="module"). В обычных скриптах — нельзя. В Node.js поддерживается в .mjs файлах или с "type": "module" в package.json.',
    tags: ['promises', 'async-await'],
    order: 51,
  },
  {
    id: 'js-052',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает Promise.resolve() и Promise.reject()?',
    questionEn: 'Как работает Promise.resolve() и Promise.reject()?',
    answerRu: 'Promise.resolve(value) возвращает уже выполненный промис с переданным значением. Если передать промис — возвращает его же. Promise.reject(reason) возвращает уже отклонённый промис. Полезны для нормализации значений в Promise-based API.',
    answerEn: 'Promise.resolve(value) возвращает уже выполненный промис с переданным значением. Если передать промис — возвращает его же. Promise.reject(reason) возвращает уже отклонённый промис. Полезны для нормализации значений в Promise-based API.',
    tags: ['promises', 'async-await'],
    order: 52,
  },
  {
    id: 'js-053',
    difficulty: 'EASY',
    questionRu: 'Что такое деструктуризация?',
    questionEn: 'Что такое деструктуризация?',
    answerRu: 'Деструктуризация позволяет извлекать значения из массивов и свойства объектов в переменные. Массив: const [a, b] = [1, 2]. Объект: const { name, age } = user. Поддерживает значения по умолчанию, переименование, вложенную деструктуризацию и rest-паттерн.',
    answerEn: 'Деструктуризация позволяет извлекать значения из массивов и свойства объектов в переменные. Массив: const [a, b] = [1, 2]. Объект: const { name, age } = user. Поддерживает значения по умолчанию, переименование, вложенную деструктуризацию и rest-паттерн.',
    tags: ['es6', 'syntax'],
    order: 53,
  },
  {
    id: 'js-054',
    difficulty: 'EASY',
    questionRu: 'Как работает spread и rest оператор?',
    questionEn: 'Как работает spread и rest оператор?',
    answerRu: 'Оба используют синтаксис (...). Spread — разворачивает итерируемое: [...arr], {...obj}, fn(...args). Rest — собирает оставшиеся элементы в массив: function(a, ...rest), const {x, ...others} = obj. Rest всегда последний в списке параметров/деструктуризации.',
    answerEn: 'Оба используют синтаксис (...). Spread — разворачивает итерируемое: [...arr], {...obj}, fn(...args). Rest — собирает оставшиеся элементы в массив: function(a, ...rest), const {x, ...others} = obj. Rest всегда последний в списке параметров/деструктуризации.',
    tags: ['es6', 'syntax'],
    order: 54,
  },
  {
    id: 'js-055',
    difficulty: 'EASY',
    questionRu: 'Что такое template literals?',
    questionEn: 'Что такое template literals?',
    answerRu: 'Template literals — строки в обратных кавычках (`). Возможности: многострочность, интерполяция выражений ${expr}, tagged templates (функция перед шаблоном для обработки). Пример: `Hello, ${user.name}! You are ${age > 18 ? "adult" : "minor"}.`',
    answerEn: 'Template literals — строки в обратных кавычках (`). Возможности: многострочность, интерполяция выражений ${expr}, tagged templates (функция перед шаблоном для обработки). Пример: `Hello, ${user.name}! You are ${age > 18 ? "adult" : "minor"}.`',
    tags: ['es6', 'syntax'],
    order: 55,
  },
  {
    id: 'js-056',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое Map и Set, чем отличаются от объектов и массивов?',
    questionEn: 'Что такое Map и Set, чем отличаются от объектов и массивов?',
    answerRu: 'Map — коллекция ключ-значение, где ключом может быть любой тип (включая объекты). Итерируется в порядке вставки. Set — коллекция уникальных значений. Преимущества над объектом/массивом: лучшая производительность при частых добавлениях/удалениях, нет конфликтов с прототипом.',
    answerEn: 'Map — коллекция ключ-значение, где ключом может быть любой тип (включая объекты). Итерируется в порядке вставки. Set — коллекция уникальных значений. Преимущества над объектом/массивом: лучшая производительность при частых добавлениях/удалениях, нет конфликтов с прототипом.',
    tags: ['es6', 'syntax'],
    order: 56,
  },
  {
    id: 'js-057',
    difficulty: 'HARD',
    questionRu: 'Что такое WeakMap и WeakSet?',
    questionEn: 'Что такое WeakMap и WeakSet?',
    answerRu: 'WeakMap и WeakSet хранят объекты по слабым ссылкам — если объект нигде больше не используется, сборщик мусора его удалит вместе с записью. Не итерируемы. Используются для кэширования, хранения метаданных объектов без утечек памяти.',
    answerEn: 'WeakMap и WeakSet хранят объекты по слабым ссылкам — если объект нигде больше не используется, сборщик мусора его удалит вместе с записью. Не итерируемы. Используются для кэширования, хранения метаданных объектов без утечек памяти.',
    tags: ['es6', 'syntax'],
    order: 57,
  },
  {
    id: 'js-058',
    difficulty: 'HARD',
    questionRu: 'Что такое Proxy и Reflect?',
    questionEn: 'Что такое Proxy и Reflect?',
    answerRu: 'Proxy позволяет перехватывать операции над объектом (get, set, has, deleteProperty и др.) через обработчики-ловушки (traps). Reflect — объект с методами, зеркально повторяющими ловушки Proxy, для правильного дефолтного поведения. Используются в реактивных системах (Vue 3).',
    answerEn: 'Proxy позволяет перехватывать операции над объектом (get, set, has, deleteProperty и др.) через обработчики-ловушки (traps). Reflect — объект с методами, зеркально повторяющими ловушки Proxy, для правильного дефолтного поведения. Используются в реактивных системах (Vue 3).',
    tags: ['es6', 'syntax'],
    order: 58,
  },
  {
    id: 'js-059',
    difficulty: 'HARD',
    questionRu: 'Как работают итераторы и Symbol.iterator?',
    questionEn: 'Как работают итераторы и Symbol.iterator?',
    answerRu: 'Итератор — объект с методом next(), возвращающим {value, done}. Symbol.iterator — метод, возвращающий итератор. Объект с Symbol.iterator итерируется в for...of. Встроенные итерируемые: массивы, строки, Map, Set, генераторы.',
    answerEn: 'Итератор — объект с методом next(), возвращающим {value, done}. Symbol.iterator — метод, возвращающий итератор. Объект с Symbol.iterator итерируется в for...of. Встроенные итерируемые: массивы, строки, Map, Set, генераторы.',
    tags: ['es6', 'syntax'],
    order: 59,
  },
  {
    id: 'js-060',
    difficulty: 'MEDIUM',
    questionRu: 'Что нового в ES2022-2024?',
    questionEn: 'Что нового в ES2022-2024?',
    answerRu: 'ES2022: приватные поля (#), Top-level await, at(), Object.hasOwn(). ES2023: findLast(), toSorted/toReversed/toSpliced (не мутируют). ES2024: Object.groupBy(), Promise.withResolvers(), Temporal API (stage 3). Стоит знать хотя бы ES2022.',
    answerEn: 'ES2022: приватные поля (#), Top-level await, at(), Object.hasOwn(). ES2023: findLast(), toSorted/toReversed/toSpliced (не мутируют). ES2024: Object.groupBy(), Promise.withResolvers(), Temporal API (stage 3). Стоит знать хотя бы ES2022.',
    tags: ['es6', 'syntax'],
    order: 60,
  },
  {
    id: 'js-061',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между shallow copy и deep copy?',
    questionEn: 'В чём разница между shallow copy и deep copy?',
    answerRu: 'Shallow copy (Object.assign, spread): копирует верхний уровень, вложенные объекты — по ссылке. Deep copy: полная независимая копия. Способы deep copy: structuredClone() (ES2022, нативный), JSON.parse(JSON.stringify()) (теряет функции/undefined), рекурсивная функция, lodash.cloneDeep.',
    answerEn: 'Shallow copy (Object.assign, spread): копирует верхний уровень, вложенные объекты — по ссылке. Deep copy: полная независимая копия. Способы deep copy: structuredClone() (ES2022, нативный), JSON.parse(JSON.stringify()) (теряет функции/undefined), рекурсивная функция, lodash.cloneDeep.',
    tags: ['arrays', 'objects'],
    order: 61,
  },
  {
    id: 'js-062',
    difficulty: 'EASY',
    questionRu: 'Какие методы массива не мутируют оригинал?',
    questionEn: 'Какие методы массива не мутируют оригинал?',
    answerRu: 'Немутирующие: map, filter, reduce, slice, concat, flat, flatMap, find, findIndex, some, every, includes, indexOf, toSorted, toReversed, toSpliced. Мутирующие: push, pop, shift, unshift, splice, sort, reverse, fill. Предпочтительно использовать немутирующие.',
    answerEn: 'Немутирующие: map, filter, reduce, slice, concat, flat, flatMap, find, findIndex, some, every, includes, indexOf, toSorted, toReversed, toSpliced. Мутирующие: push, pop, shift, unshift, splice, sort, reverse, fill. Предпочтительно использовать немутирующие.',
    tags: ['arrays', 'objects'],
    order: 62,
  },
  {
    id: 'js-063',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает Array.reduce()?',
    questionEn: 'Как работает Array.reduce()?',
    answerRu: 'reduce(callback, initialValue) проходит по массиву, аккумулируя результат. callback(accumulator, currentValue, index, array). Без initialValue первый элемент — аккумулятор. Применение: сумма, группировка объектов, создание Map, flat.',
    answerEn: 'reduce(callback, initialValue) проходит по массиву, аккумулируя результат. callback(accumulator, currentValue, index, array). Без initialValue первый элемент — аккумулятор. Применение: сумма, группировка объектов, создание Map, flat.',
    tags: ['arrays', 'objects'],
    order: 63,
  },
  {
    id: 'js-064',
    difficulty: 'EASY',
    questionRu: 'Как проверить, является ли значение массивом?',
    questionEn: 'Как проверить, является ли значение массивом?',
    answerRu: 'Array.isArray(value) — рекомендуемый способ, работает корректно для массивов из разных фреймов. typeof [] === "object" — не подходит. instanceof Array — ненадёжно в мульти-фреймовых средах. value.constructor === Array — ненадёжно при изменённом прототипе.',
    answerEn: 'Array.isArray(value) — рекомендуемый способ, работает корректно для массивов из разных фреймов. typeof [] === "object" — не подходит. instanceof Array — ненадёжно в мульти-фреймовых средах. value.constructor === Array — ненадёжно при изменённом прототипе.',
    tags: ['arrays', 'objects'],
    order: 64,
  },
  {
    id: 'js-065',
    difficulty: 'EASY',
    questionRu: 'Как удалить дубликаты из массива?',
    questionEn: 'Как удалить дубликаты из массива?',
    answerRu: 'Способы: 1) [...new Set(arr)] — быстро для примитивов. 2) filter + indexOf: arr.filter((v,i) => arr.indexOf(v) === i). 3) reduce для объектов по ключу. Для объектов со сложной логикой сравнения — ручная фильтрация.',
    answerEn: 'Способы: 1) [...new Set(arr)] — быстро для примитивов. 2) filter + indexOf: arr.filter((v,i) => arr.indexOf(v) === i). 3) reduce для объектов по ключу. Для объектов со сложной логикой сравнения — ручная фильтрация.',
    tags: ['arrays', 'objects'],
    order: 65,
  },
  {
    id: 'js-066',
    difficulty: 'EASY',
    questionRu: 'Как перебрать свойства объекта?',
    questionEn: 'Как перебрать свойства объекта?',
    answerRu: 'for...in: перебирает все перечислимые свойства включая унаследованные. Object.keys(): только собственные перечислимые. Object.values(): значения. Object.entries(): пары [ключ, значение]. for...of с Object.entries() — самый удобный способ.',
    answerEn: 'for...in: перебирает все перечислимые свойства включая унаследованные. Object.keys(): только собственные перечислимые. Object.values(): значения. Object.entries(): пары [ключ, значение]. for...of с Object.entries() — самый удобный способ.',
    tags: ['arrays', 'objects'],
    order: 66,
  },
  {
    id: 'js-067',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое иммутабельность и зачем она нужна?',
    questionEn: 'Что такое иммутабельность и зачем она нужна?',
    answerRu: 'Иммутабельность — неизменяемость данных после создания. Преимущества: предсказуемость состояния, простота отладки, безопасное сравнение по ссылке (для React). JS: Object.freeze() (поверхностно). Паттерн: создавать новые объекты вместо мутации (spread, map, filter).',
    answerEn: 'Иммутабельность — неизменяемость данных после создания. Преимущества: предсказуемость состояния, простота отладки, безопасное сравнение по ссылке (для React). JS: Object.freeze() (поверхностно). Паттерн: создавать новые объекты вместо мутации (spread, map, filter).',
    tags: ['arrays', 'objects'],
    order: 67,
  },
  {
    id: 'js-068',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает Object.freeze() и Object.seal()?',
    questionEn: 'Как работает Object.freeze() и Object.seal()?',
    answerRu: 'Object.freeze(): нельзя добавлять, удалять или изменять свойства. Поверхностно — вложенные объекты не заморожены. Object.seal(): нельзя добавлять или удалять, но изменять значения можно. Для глубокой заморозки нужна рекурсия.',
    answerEn: 'Object.freeze(): нельзя добавлять, удалять или изменять свойства. Поверхностно — вложенные объекты не заморожены. Object.seal(): нельзя добавлять или удалять, но изменять значения можно. Для глубокой заморозки нужна рекурсия.',
    tags: ['arrays', 'objects'],
    order: 68,
  },
  {
    id: 'js-069',
    difficulty: 'EASY',
    questionRu: 'В чём разница между for...of и for...in?',
    questionEn: 'В чём разница между for...of и for...in?',
    answerRu: 'for...in перебирает ключи объекта (все перечислимые, включая унаследованные) — для объектов. for...of перебирает значения итерируемых объектов (массивы, строки, Map, Set, генераторы). Использование for...in для массивов считается антипаттерном.',
    answerEn: 'for...in перебирает ключи объекта (все перечислимые, включая унаследованные) — для объектов. for...of перебирает значения итерируемых объектов (массивы, строки, Map, Set, генераторы). Использование for...in для массивов считается антипаттерном.',
    tags: ['arrays', 'objects'],
    order: 69,
  },
  {
    id: 'js-070',
    difficulty: 'MEDIUM',
    questionRu: 'Как сравнить два объекта на равенство?',
    questionEn: 'Как сравнить два объекта на равенство?',
    answerRu: 'obj1 === obj2 проверяет ссылки, не содержимое. Для содержимого: JSON.stringify (теряет порядок, undefined, функции). Рекурсивное сравнение: Object.keys + рекурсия. Библиотека: lodash.isEqual. structuredClone для копирования, но не для сравнения.',
    answerEn: 'obj1 === obj2 проверяет ссылки, не содержимое. Для содержимого: JSON.stringify (теряет порядок, undefined, функции). Рекурсивное сравнение: Object.keys + рекурсия. Библиотека: lodash.isEqual. structuredClone для копирования, но не для сравнения.',
    tags: ['arrays', 'objects'],
    order: 70,
  },
  {
    id: 'js-071',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое всплытие и погружение событий?',
    questionEn: 'Что такое всплытие и погружение событий?',
    answerRu: 'Событие проходит 3 фазы: capture (погружение от document до элемента), target (целевой элемент), bubble (всплытие от элемента до document). addEventListener(event, fn, true) — capture фаза. По умолчанию — bubble. stopPropagation() останавливает распространение.',
    answerEn: 'Событие проходит 3 фазы: capture (погружение от document до элемента), target (целевой элемент), bubble (всплытие от элемента до document). addEventListener(event, fn, true) — capture фаза. По умолчанию — bubble. stopPropagation() останавливает распространение.',
    tags: ['events', 'dom'],
    order: 71,
  },
  {
    id: 'js-072',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое делегирование событий?',
    questionEn: 'Что такое делегирование событий?',
    answerRu: 'Делегирование — установка одного обработчика на родителя вместо множества на дочерние элементы. Работает через всплытие. Преимущества: меньше памяти, работает с динамически добавленными элементами. event.target определяет конкретный элемент.',
    answerEn: 'Делегирование — установка одного обработчика на родителя вместо множества на дочерние элементы. Работает через всплытие. Преимущества: меньше памяти, работает с динамически добавленными элементами. event.target определяет конкретный элемент.',
    tags: ['events', 'dom'],
    order: 72,
  },
  {
    id: 'js-073',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между e.stopPropagation() и e.preventDefault()?',
    questionEn: 'В чём разница между e.stopPropagation() и e.preventDefault()?',
    answerRu: 'stopPropagation() — останавливает распространение события по DOM-дереву (всплытие/погружение). preventDefault() — отменяет стандартное поведение браузера (переход по ссылке, отправка формы). Независимы: можно вызвать оба или только один.',
    answerEn: 'stopPropagation() — останавливает распространение события по DOM-дереву (всплытие/погружение). preventDefault() — отменяет стандартное поведение браузера (переход по ссылке, отправка формы). Независимы: можно вызвать оба или только один.',
    tags: ['events', 'dom'],
    order: 73,
  },
  {
    id: 'js-074',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое виртуальный DOM?',
    questionEn: 'Что такое виртуальный DOM?',
    answerRu: 'Virtual DOM — легковесное JS-представление реального DOM. При изменениях сначала обновляется VDOM, затем алгоритм диффинга находит минимальный набор изменений и применяет их к реальному DOM (reconciliation). Используется в React, Vue 2. Ускоряет работу за счёт пакетных обновлений.',
    answerEn: 'Virtual DOM — легковесное JS-представление реального DOM. При изменениях сначала обновляется VDOM, затем алгоритм диффинга находит минимальный набор изменений и применяет их к реальному DOM (reconciliation). Используется в React, Vue 2. Ускоряет работу за счёт пакетных обновлений.',
    tags: ['events', 'dom'],
    order: 74,
  },
  {
    id: 'js-075',
    difficulty: 'MEDIUM',
    questionRu: 'Как эффективно добавить много DOM-элементов?',
    questionEn: 'Как эффективно добавить много DOM-элементов?',
    answerRu: 'Использовать DocumentFragment: создать фрагмент, добавить все элементы в него, потом одним вызовом вставить в DOM. Это вызывает единственный reflow. Альтернативы: innerHTML (осторожно с XSS), insertAdjacentHTML, шаблонизация с сериализацией.',
    answerEn: 'Использовать DocumentFragment: создать фрагмент, добавить все элементы в него, потом одним вызовом вставить в DOM. Это вызывает единственный reflow. Альтернативы: innerHTML (осторожно с XSS), insertAdjacentHTML, шаблонизация с сериализацией.',
    tags: ['events', 'dom'],
    order: 75,
  },
  {
    id: 'js-076',
    difficulty: 'HARD',
    questionRu: 'Что такое MutationObserver?',
    questionEn: 'Что такое MutationObserver?',
    answerRu: 'MutationObserver — API для отслеживания изменений в DOM-дереве (добавление/удаление узлов, изменения атрибутов, текстового содержимого). Асинхронный, использует микрозадачи. Замена устаревшим мутационным событиям. Используется в полифилах, отслеживании изменений.',
    answerEn: 'MutationObserver — API для отслеживания изменений в DOM-дереве (добавление/удаление узлов, изменения атрибутов, текстового содержимого). Асинхронный, использует микрозадачи. Замена устаревшим мутационным событиям. Используется в полифилах, отслеживании изменений.',
    tags: ['events', 'dom'],
    order: 76,
  },
  {
    id: 'js-077',
    difficulty: 'HARD',
    questionRu: 'Как работает IntersectionObserver?',
    questionEn: 'Как работает IntersectionObserver?',
    answerRu: 'IntersectionObserver отслеживает пересечение элемента с viewport или другим элементом. Используется для: ленивой загрузки изображений, бесконечного скролла, анимаций при появлении. Эффективнее scroll-события — не блокирует main thread.',
    answerEn: 'IntersectionObserver отслеживает пересечение элемента с viewport или другим элементом. Используется для: ленивой загрузки изображений, бесконечного скролла, анимаций при появлении. Эффективнее scroll-события — не блокирует main thread.',
    tags: ['events', 'dom'],
    order: 77,
  },
  {
    id: 'js-078',
    difficulty: 'EASY',
    questionRu: 'В чём разница между innerHTML, textContent и innerText?',
    questionEn: 'В чём разница между innerHTML, textContent и innerText?',
    answerRu: 'innerHTML: возвращает/устанавливает HTML-разметку (риск XSS). textContent: только текст, включая скрытые элементы, не вызывает reflow. innerText: только видимый текст, учитывает CSS (display:none скрывает), вызывает reflow. Для вставки пользовательских данных — всегда textContent.',
    answerEn: 'innerHTML: возвращает/устанавливает HTML-разметку (риск XSS). textContent: только текст, включая скрытые элементы, не вызывает reflow. innerText: только видимый текст, учитывает CSS (display:none скрывает), вызывает reflow. Для вставки пользовательских данных — всегда textContent.',
    tags: ['events', 'dom'],
    order: 78,
  },
];
