import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'js-001',
    difficulty: 'EASY',
    questionRu: 'Какие типы данных существуют в JavaScript?',
    questionEn: 'What data types exist in JavaScript?',
    answerRu: 'Примитивные: string, number, bigint, boolean, undefined, null, symbol. Ссылочный: object (включает массивы, функции, объекты).',
    answerEn: 'Primitives: string, number, bigint, boolean, undefined, null, symbol. Reference type: object (includes arrays, functions, objects).',
    tags: ['types', 'operators'],
    order: 1,
  },
  {
    id: 'js-002',
    difficulty: 'EASY',
    questionRu: 'В чём разница между == и ===?',
    questionEn: 'What is the difference between == and ===?',
    answerRu: '== выполняет приведение типов перед сравнением (например, "5" == 5 → true). === сравнивает без приведения типов — значение и тип должны совпадать ("5" === 5 → false).',
    answerEn: '== performs type coercion before comparing (e.g. "5" == 5 → true). === compares without type coercion — both value and type must match ("5" === 5 → false).',
    tags: ['types', 'operators'],
    order: 2,
  },
  {
    id: 'js-003',
    difficulty: 'EASY',
    questionRu: 'Что такое typeof null и почему?',
    questionEn: 'What is typeof null and why?',
    answerRu: 'typeof null возвращает "object" — это исторический баг JavaScript с первой версии. null является примитивом, но из-за внутреннего представления в двоичном коде был отнесён к объектам.',
    answerEn: 'typeof null returns "object" — this is a historical bug in JavaScript dating back to version 1. null is a primitive, but due to its internal binary representation it was classified as an object.',
    tags: ['types', 'operators'],
    order: 3,
  },
  {
    id: 'js-004',
    difficulty: 'EASY',
    questionRu: 'Что такое NaN и как проверить, является ли значение NaN?',
    questionEn: 'What is NaN and how do you check if a value is NaN?',
    answerRu: 'NaN (Not a Number) — результат некорректной математической операции. Особенность: NaN !== NaN. Для проверки используют Number.isNaN(value) (строгий) или isNaN(value) (с приведением типов).',
    answerEn: 'NaN (Not a Number) is the result of an invalid mathematical operation. Its quirk: NaN !== NaN. To check for it use Number.isNaN(value) (strict) or isNaN(value) (with type coercion).',
    tags: ['types', 'operators'],
    order: 4,
  },
  {
    id: 'js-005',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает приведение типов в JavaScript?',
    questionEn: 'How does type coercion work in JavaScript?',
    answerRu: 'JS автоматически приводит типы в определённых контекстах. Явное: Number("5"), String(5), Boolean(0). Неявное: "5" * 2 → 10, [] + {} → "[object Object]". Правила: при + с строкой — конкатенация, при -, *, / — числовое приведение.',
    answerEn: 'JS automatically converts types in certain contexts. Explicit: Number("5"), String(5), Boolean(0). Implicit: "5" * 2 → 10, [] + {} → "[object Object]". Rules: + with a string gives concatenation; -, *, / trigger numeric conversion.',
    tags: ['types', 'operators'],
    order: 5,
  },
  {
    id: 'js-006',
    difficulty: 'EASY',
    questionRu: 'В чём разница между null и undefined?',
    questionEn: 'What is the difference between null and undefined?',
    answerRu: 'undefined — переменная объявлена, но не инициализирована. null — явно присвоенное «пустое» значение. typeof undefined === "undefined", typeof null === "object". При сравнении: null == undefined → true, null === undefined → false.',
    answerEn: 'undefined means a variable has been declared but not initialized. null is an explicitly assigned "empty" value. typeof undefined === "undefined", typeof null === "object". Comparison: null == undefined → true, null === undefined → false.',
    tags: ['types', 'operators'],
    order: 6,
  },
  {
    id: 'js-007',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое Symbol и для чего используется?',
    questionEn: 'What is Symbol and what is it used for?',
    answerRu: 'Symbol — уникальный примитивный тип, каждый Symbol() гарантированно уникален. Используется для создания уникальных ключей объектов, скрытых свойств (не перечисляются в for...in), и встроенных итераторов (Symbol.iterator).',
    answerEn: 'Symbol is a unique primitive type — every Symbol() is guaranteed to be unique. It is used to create unique object keys, hidden properties (not enumerated in for...in), and built-in iterators (Symbol.iterator).',
    tags: ['types', 'operators'],
    order: 7,
  },
  {
    id: 'js-008',
    difficulty: 'EASY',
    questionRu: 'Как работает оператор ?. (optional chaining)?',
    questionEn: 'How does the ?. (optional chaining) operator work?',
    answerRu: 'Optional chaining (?.) позволяет безопасно обращаться к свойствам объекта, который может быть null или undefined. user?.address?.city вернёт undefined вместо ошибки, если user или address равны null/undefined.',
    answerEn: 'Optional chaining (?.) lets you safely access properties on an object that might be null or undefined. user?.address?.city returns undefined instead of throwing an error if user or address is null/undefined.',
    tags: ['types', 'operators'],
    order: 8,
  },
  {
    id: 'js-009',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое замыкание (closure)?',
    questionEn: 'What is a closure?',
    answerRu: 'Замыкание — функция, которая запоминает переменные из внешней области видимости даже после того, как внешняя функция завершила выполнение. Пример: счётчик через замыкание сохраняет значение count между вызовами.',
    answerEn: 'A closure is a function that remembers variables from its outer scope even after the outer function has finished executing. Example: a counter implemented via a closure retains the count value between calls.',
    tags: ['scope', 'closures'],
    order: 9,
  },
  {
    id: 'js-010',
    difficulty: 'EASY',
    questionRu: 'В чём разница между var, let и const?',
    questionEn: 'What is the difference between var, let, and const?',
    answerRu: 'var: функциональная область видимости, поднимается (hoisting) с инициализацией undefined, можно переопределить. let: блочная область видимости, поднимается без инициализации (TDZ), нельзя переопределить. const: то же что let, но нельзя переназначить (объект мутировать можно).',
    answerEn: 'var: function-scoped, hoisted with initialization to undefined, can be re-declared. let: block-scoped, hoisted without initialization (TDZ), cannot be re-declared. const: same as let but cannot be reassigned (though the object it points to can be mutated).',
    tags: ['scope', 'closures'],
    order: 10,
  },
  {
    id: 'js-011',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое Temporal Dead Zone (TDZ)?',
    questionEn: 'What is the Temporal Dead Zone (TDZ)?',
    answerRu: 'TDZ — промежуток от начала блока до строки объявления переменной let/const, где переменная существует, но недоступна. Обращение к ней в этот период выбрасывает ReferenceError.',
    answerEn: 'The TDZ is the period from the start of a block to the line where a let/const variable is declared, during which the variable exists but cannot be accessed. Accessing it in this period throws a ReferenceError.',
    tags: ['scope', 'closures'],
    order: 11,
  },
  {
    id: 'js-012',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое IIFE и зачем используется?',
    questionEn: 'What is an IIFE and why is it used?',
    answerRu: 'IIFE (Immediately Invoked Function Expression) — функция, которая выполняется сразу после объявления: (function() { ... })(). Используется для изоляции области видимости, предотвращения загрязнения глобального пространства имён.',
    answerEn: 'An IIFE (Immediately Invoked Function Expression) is a function that runs immediately after it is defined: (function() { ... })(). It is used to isolate scope and prevent pollution of the global namespace.',
    tags: ['scope', 'closures'],
    order: 12,
  },
  {
    id: 'js-013',
    difficulty: 'MEDIUM',
    questionRu: 'Почему в цикле с var все функции выводят одно значение?',
    questionEn: 'Why do all functions in a var loop print the same value?',
    answerRu: 'Из-за того, что var имеет функциональную область видимости, все итерации делят одну переменную i. К моменту вызова колбэков цикл уже завершён и i равна финальному значению. Решение: использовать let или IIFE.',
    answerEn: 'Because var is function-scoped, all iterations share the same variable i. By the time the callbacks are called the loop has already finished and i equals its final value. Fix: use let or an IIFE.',
    tags: ['scope', 'closures'],
    order: 13,
  },
  {
    id: 'js-014',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое лексическая область видимости?',
    questionEn: 'What is lexical scope?',
    answerRu: 'Лексическая (статическая) область видимости означает, что область видимости функции определяется местом её объявления в коде, а не местом вызова. JavaScript использует именно лексическую область видимости.',
    answerEn: 'Lexical (static) scope means a function\'s scope is determined by where it is declared in the source code, not where it is called. JavaScript uses lexical scoping.',
    tags: ['scope', 'closures'],
    order: 14,
  },
  {
    id: 'js-015',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое hoisting (поднятие)?',
    questionEn: 'What is hoisting?',
    answerRu: 'Hoisting — механизм, при котором объявления переменных и функций перемещаются в начало своей области видимости на этапе компиляции. function declaration поднимается целиком. var поднимается с undefined. let/const поднимаются, но остаются в TDZ.',
    answerEn: 'Hoisting is the mechanism by which variable and function declarations are moved to the top of their scope at compile time. Function declarations are hoisted fully. var is hoisted with the value undefined. let/const are hoisted but remain in the TDZ.',
    tags: ['scope', 'closures'],
    order: 15,
  },
  {
    id: 'js-016',
    difficulty: 'MEDIUM',
    questionRu: 'Как создать приватные переменные в JavaScript?',
    questionEn: 'How do you create private variables in JavaScript?',
    answerRu: 'Несколько способов: 1) Замыкания — переменная внутри функции недоступна снаружи. 2) WeakMap для хранения приватного состояния. 3) Приватные поля класса через # (ES2022): class A { #x = 0; }.',
    answerEn: 'Several approaches: 1) Closures — a variable inside a function is inaccessible from outside. 2) WeakMap for storing private state. 3) Class private fields via # (ES2022): class A { #x = 0; }.',
    tags: ['scope', 'closures'],
    order: 16,
  },
  {
    id: 'js-017',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое прототип в JavaScript?',
    questionEn: 'What is a prototype in JavaScript?',
    answerRu: 'Каждый объект имеет скрытую ссылку [[Prototype]] на другой объект (прототип). При обращении к свойству сначала ищется в объекте, затем по цепочке прототипов вверх до null. Доступен через __proto__ или Object.getPrototypeOf().',
    answerEn: 'Every object has a hidden [[Prototype]] reference to another object (its prototype). When a property is accessed, the engine searches the object first, then walks the prototype chain up to null. Accessible via __proto__ or Object.getPrototypeOf().',
    tags: ['prototype', 'inheritance'],
    order: 17,
  },
  {
    id: 'js-018',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между прототипным и классовым наследованием?',
    questionEn: 'What is the difference between prototypal and classical inheritance?',
    answerRu: 'В JS классы (ES6) — синтаксический сахар над прототипным наследованием. При классовом наследовании (class B extends A) под капотом B.prototype.__proto__ === A.prototype. Прототипное наследование гибче: можно менять цепочку в runtime.',
    answerEn: 'In JS, classes (ES6) are syntactic sugar over prototypal inheritance. With class inheritance (class B extends A), under the hood B.prototype.__proto__ === A.prototype. Prototypal inheritance is more flexible: the chain can be changed at runtime.',
    tags: ['prototype', 'inheritance'],
    order: 18,
  },
  {
    id: 'js-019',
    difficulty: 'MEDIUM',
    questionRu: 'Что делает Object.create()?',
    questionEn: 'What does Object.create() do?',
    answerRu: 'Object.create(proto) создаёт новый объект с указанным прототипом. Позволяет создавать объекты с точным контролем над цепочкой прототипов без конструктора. Object.create(null) создаёт объект без прототипа вообще.',
    answerEn: 'Object.create(proto) creates a new object with the given prototype. It allows creating objects with precise control over the prototype chain without a constructor. Object.create(null) creates an object with no prototype at all.',
    tags: ['prototype', 'inheritance'],
    order: 19,
  },
  {
    id: 'js-020',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает оператор instanceof?',
    questionEn: 'How does the instanceof operator work?',
    answerRu: 'instanceof проверяет, есть ли в цепочке прототипов объекта prototype конструктора. obj instanceof Foo проверяет: Foo.prototype === Object.getPrototypeOf(obj) (рекурсивно вверх). Можно переопределить через Symbol.hasInstance.',
    answerEn: 'instanceof checks whether the constructor\'s prototype exists anywhere in the object\'s prototype chain. obj instanceof Foo checks: Foo.prototype === Object.getPrototypeOf(obj) (recursively upward). Can be customized via Symbol.hasInstance.',
    tags: ['prototype', 'inheritance'],
    order: 20,
  },
  {
    id: 'js-021',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое constructor property?',
    questionEn: 'What is the constructor property?',
    answerRu: 'Свойство constructor указывает на функцию-конструктор, создавшую объект. Хранится в prototype конструктора, а не в самом объекте. При переопределении prototype нужно вручную восстановить constructor.',
    answerEn: 'The constructor property points to the constructor function that created the object. It is stored on the constructor\'s prototype, not on the object itself. When you replace prototype you need to manually restore constructor.',
    tags: ['prototype', 'inheritance'],
    order: 21,
  },
  {
    id: 'js-022',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между hasOwnProperty и in?',
    questionEn: 'What is the difference between hasOwnProperty and in?',
    answerRu: 'hasOwnProperty() возвращает true только для собственных (не унаследованных) свойств. Оператор in проверяет весь прототипный chain, включая унаследованные. Пример: "toString" in {} → true, {}.hasOwnProperty("toString") → false.',
    answerEn: 'hasOwnProperty() returns true only for own (non-inherited) properties. The in operator checks the entire prototype chain including inherited ones. Example: "toString" in {} → true, {}.hasOwnProperty("toString") → false.',
    tags: ['prototype', 'inheritance'],
    order: 22,
  },
  {
    id: 'js-023',
    difficulty: 'HARD',
    questionRu: 'Что такое миксины и как реализовать?',
    questionEn: 'What are mixins and how do you implement them?',
    answerRu: 'Миксин — паттерн для копирования методов в прототип класса без наследования. Реализуется через Object.assign(Target.prototype, mixin). Позволяет добавлять поведение из нескольких источников, обходя ограничение одиночного наследования.',
    answerEn: 'A mixin is a pattern for copying methods into a class prototype without inheritance. Implemented via Object.assign(Target.prototype, mixin). It allows adding behavior from multiple sources, working around the single-inheritance limitation.',
    tags: ['prototype', 'inheritance'],
    order: 23,
  },
  {
    id: 'js-024',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает new в JavaScript?',
    questionEn: 'How does new work in JavaScript?',
    answerRu: 'При вызове new Foo(): 1) Создаётся новый пустой объект. 2) Его [[Prototype]] устанавливается в Foo.prototype. 3) Функция-конструктор вызывается с this = новый объект. 4) Если конструктор возвращает объект — возвращается он, иначе — новый объект.',
    answerEn: 'When new Foo() is called: 1) A new empty object is created. 2) Its [[Prototype]] is set to Foo.prototype. 3) The constructor is called with this = the new object. 4) If the constructor returns an object, that object is returned; otherwise the new object is returned.',
    tags: ['prototype', 'inheritance'],
    order: 24,
  },
  {
    id: 'js-025',
    difficulty: 'MEDIUM',
    questionRu: 'Как определяется значение this?',
    questionEn: 'How is the value of this determined?',
    answerRu: 'Зависит от способа вызова: 1) Метод объекта — this = объект. 2) Обычная функция — this = undefined (strict) или global. 3) Arrow function — this из внешнего лексического контекста. 4) new — this = новый объект. 5) call/apply/bind — явно задано.',
    answerEn: 'Depends on how the function is called: 1) Object method — this = the object. 2) Regular function — this = undefined (strict mode) or global. 3) Arrow function — this from the outer lexical context. 4) new — this = the new object. 5) call/apply/bind — explicitly set.',
    tags: ['this', 'context'],
    order: 25,
  },
  {
    id: 'js-026',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между call, apply и bind?',
    questionEn: 'What is the difference between call, apply, and bind?',
    answerRu: 'Все три явно устанавливают this. call(ctx, arg1, arg2) — вызывает немедленно, аргументы через запятую. apply(ctx, [args]) — вызывает немедленно, аргументы массивом. bind(ctx, arg1) — возвращает новую функцию с привязанным this, не вызывает.',
    answerEn: 'All three explicitly set this. call(ctx, arg1, arg2) — invokes immediately, arguments passed individually. apply(ctx, [args]) — invokes immediately, arguments as an array. bind(ctx, arg1) — returns a new function with this bound, does not invoke it.',
    tags: ['this', 'context'],
    order: 26,
  },
  {
    id: 'js-027',
    difficulty: 'MEDIUM',
    questionRu: 'Почему стрелочные функции не имеют своего this?',
    questionEn: 'Why do arrow functions not have their own this?',
    answerRu: 'Arrow functions не создают собственный контекст выполнения. this в них берётся из ближайшего внешнего лексического окружения в момент объявления и не меняется при вызове. Поэтому call/apply/bind не могут изменить this стрелочной функции.',
    answerEn: 'Arrow functions do not create their own execution context. Their this is taken from the nearest enclosing lexical scope at the time of definition and never changes. Therefore call/apply/bind cannot change the this of an arrow function.',
    tags: ['this', 'context'],
    order: 27,
  },
  {
    id: 'js-028',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое потеря контекста и как её избежать?',
    questionEn: 'What is context loss and how do you avoid it?',
    answerRu: 'Потеря контекста — when метод передаётся как колбэк, this становится undefined или global. Решения: 1) bind: setTimeout(this.method.bind(this), 0). 2) Стрелочная функция: setTimeout(() => this.method(), 0). 3) Сохранить: const self = this.',
    answerEn: 'Context loss happens when a method is passed as a callback and this becomes undefined or global. Solutions: 1) bind: setTimeout(this.method.bind(this), 0). 2) Arrow function: setTimeout(() => this.method(), 0). 3) Save reference: const self = this.',
    tags: ['this', 'context'],
    order: 28,
  },
  {
    id: 'js-029',
    difficulty: 'MEDIUM',
    questionRu: 'Каков this в обработчике события?',
    questionEn: 'What is this in an event handler?',
    answerRu: 'В обычной функции-обработчике this указывает на DOM-элемент, к которому прикреплён обработчик. В стрелочной функции this берётся из внешнего контекста (например, класса). Поэтому в классах часто используют стрелочные методы или bind.',
    answerEn: 'In a regular function handler, this refers to the DOM element the handler is attached to. In an arrow function, this comes from the outer context (e.g. the class). That is why class-based code often uses arrow method fields or bind.',
    tags: ['this', 'context'],
    order: 29,
  },
  {
    id: 'js-030',
    difficulty: 'EASY',
    questionRu: 'Что вернёт this в глобальном контексте?',
    questionEn: 'What does this return in the global context?',
    answerRu: 'В браузере в глобальном контексте this === window. В Node.js на верхнем уровне this === module.exports (пустой объект). В строгом режиме ("use strict") this в функции, вызванной без контекста, === undefined.',
    answerEn: 'In a browser at global scope this === window. In Node.js at the top level this === module.exports (an empty object). In strict mode ("use strict"), this inside a function called without a context === undefined.',
    tags: ['this', 'context'],
    order: 30,
  },
  {
    id: 'js-031',
    difficulty: 'MEDIUM',
    questionRu: 'Можно ли изменить this стрелочной функции через bind?',
    questionEn: 'Can you change the this of an arrow function with bind?',
    answerRu: 'Нет. bind, call и apply не могут изменить this стрелочной функции — он всегда берётся из лексического окружения на момент создания функции. bind вернёт новую функцию, но this в ней останется прежним.',
    answerEn: 'No. bind, call, and apply cannot change the this of an arrow function — it is always taken from the lexical environment at the time of creation. bind will return a new function, but its this remains unchanged.',
    tags: ['this', 'context'],
    order: 31,
  },
  {
    id: 'js-032',
    difficulty: 'MEDIUM',
    questionRu: 'Как this работает в классах ES6?',
    questionEn: 'How does this work in ES6 classes?',
    answerRu: 'В методах класса this указывает на экземпляр. В constructor this — создаваемый объект. Если метод передать как колбэк — контекст теряется. Решение: объявлять методы как стрелочные поля (arrow field methods) или использовать bind в конструкторе.',
    answerEn: 'In class methods, this refers to the instance. In the constructor, this is the object being created. If a method is passed as a callback, context is lost. Fix: declare methods as arrow field methods or use bind in the constructor.',
    tags: ['this', 'context'],
    order: 32,
  },
  {
    id: 'js-033',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое Event Loop?',
    questionEn: 'What is the Event Loop?',
    answerRu: 'Event Loop — механизм выполнения асинхронного кода в JS. Состоит из: Call Stack (стек вызовов), Web APIs (таймеры, fetch), Callback Queue (очередь макрозадач), Microtask Queue (промисы, queueMicrotask). Цикл: выполнить стек → все микрозадачи → одну макрозадачу → рендер → повторить.',
    answerEn: 'The Event Loop is the mechanism for executing asynchronous code in JS. It consists of: Call Stack, Web APIs (timers, fetch), Callback Queue (macrotasks), Microtask Queue (promises, queueMicrotask). The cycle: run the stack → all microtasks → one macrotask → render → repeat.',
    tags: ['event-loop', 'async'],
    order: 33,
  },
  {
    id: 'js-034',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между микрозадачами и макрозадачами?',
    questionEn: 'What is the difference between microtasks and macrotasks?',
    answerRu: 'Макрозадачи (setTimeout, setInterval, I/O): выполняется одна за итерацию цикла. Микрозадачи (Promise.then, queueMicrotask, MutationObserver): выполняются все после каждой макрозадачи и до следующего рендера. Микрозадачи имеют приоритет выше.',
    answerEn: 'Macrotasks (setTimeout, setInterval, I/O): one is executed per loop iteration. Microtasks (Promise.then, queueMicrotask, MutationObserver): all are executed after each macrotask and before the next render. Microtasks have higher priority.',
    tags: ['event-loop', 'async'],
    order: 34,
  },
  {
    id: 'js-035',
    difficulty: 'MEDIUM',
    questionRu: 'Что выведет код: setTimeout 0, Promise.resolve, console.log?',
    questionEn: 'What will the code log: setTimeout 0, Promise.resolve, console.log?',
    answerRu: 'Порядок: 1) синхронный console.log (Call Stack). 2) Promise.then (микрозадача). 3) setTimeout (макрозадача). Правило: синхронный код → микрозадачи → макрозадачи.',
    answerEn: 'Order: 1) synchronous console.log (Call Stack). 2) Promise.then (microtask). 3) setTimeout (macrotask). Rule: synchronous code → microtasks → macrotasks.',
    tags: ['event-loop', 'async'],
    order: 35,
  },
  {
    id: 'js-036',
    difficulty: 'EASY',
    questionRu: 'Что такое callback hell и как его избежать?',
    questionEn: 'What is callback hell and how do you avoid it?',
    answerRu: 'Callback hell — глубокая вложенность колбэков, делающая код нечитаемым. Решения: 1) Именованные функции вместо анонимных. 2) Промисы с цепочкой .then(). 3) async/await для синхронного стиля. 4) Разбиение на небольшие функции.',
    answerEn: 'Callback hell is deeply nested callbacks that make code unreadable. Solutions: 1) Named functions instead of anonymous ones. 2) Promises with .then() chaining. 3) async/await for synchronous-style code. 4) Breaking logic into smaller functions.',
    tags: ['event-loop', 'async'],
    order: 36,
  },
  {
    id: 'js-037',
    difficulty: 'MEDIUM',
    questionRu: 'Почему JavaScript однопоточный и как справляется с асинхронностью?',
    questionEn: 'Why is JavaScript single-threaded and how does it handle asynchrony?',
    answerRu: 'JS выполняется в одном потоке, чтобы избежать проблем конкурентности при работе с DOM. Асинхронность реализуется через Event Loop: тяжёлые операции (сеть, таймеры) делегируются Web APIs браузера/Node.js, а колбэки ставятся в очередь и выполняются позже.',
    answerEn: 'JS runs on a single thread to avoid concurrency issues when manipulating the DOM. Asynchrony is handled via the Event Loop: heavy operations (network, timers) are delegated to browser/Node.js Web APIs, and their callbacks are queued and executed later.',
    tags: ['event-loop', 'async'],
    order: 37,
  },
  {
    id: 'js-038',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое requestAnimationFrame и чем отличается от setTimeout?',
    questionEn: 'What is requestAnimationFrame and how does it differ from setTimeout?',
    answerRu: 'requestAnimationFrame (rAF) вызывает колбэк перед следующим рендером браузера (~60 раз в секунду). В отличие от setTimeout(fn, 16), rAF синхронизирован с частотой обновления дисплея, не вызывается в фоновых вкладках и точнее для анимаций.',
    answerEn: 'requestAnimationFrame (rAF) calls a callback just before the browser\'s next render (~60 times per second). Unlike setTimeout(fn, 16), rAF is synchronized to the display refresh rate, does not fire in background tabs, and is more accurate for animations.',
    tags: ['event-loop', 'async'],
    order: 38,
  },
  {
    id: 'js-039',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое Web Workers?',
    questionEn: 'What are Web Workers?',
    answerRu: 'Web Workers — отдельные потоки в браузере для выполнения тяжёлых вычислений без блокировки основного потока. Общаются с основным потоком через postMessage/onmessage. Не имеют доступа к DOM.',
    answerEn: 'Web Workers are separate browser threads for running heavy computations without blocking the main thread. They communicate with the main thread via postMessage/onmessage. They have no access to the DOM.',
    tags: ['event-loop', 'async'],
    order: 39,
  },
  {
    id: 'js-040',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает setInterval и каковы его проблемы?',
    questionEn: 'How does setInterval work and what are its problems?',
    answerRu: 'setInterval(fn, n) ставит задачу в очередь каждые n мс. Проблемы: 1) Если колбэк выполняется дольше интервала, вызовы накапливаются. 2) Точность не гарантирована. 3) Не адаптируется к нагрузке. Альтернатива: рекурсивный setTimeout для динамического управления задержкой.',
    answerEn: 'setInterval(fn, n) queues the callback every n ms. Problems: 1) If the callback takes longer than the interval, calls can stack up. 2) Timing is not guaranteed. 3) It does not adapt to load. Alternative: recursive setTimeout for dynamic delay control.',
    tags: ['event-loop', 'async'],
    order: 40,
  },
  {
    id: 'js-041',
    difficulty: 'HARD',
    questionRu: 'Что такое генераторы и как они связаны с асинхронностью?',
    questionEn: 'What are generators and how are they related to asynchrony?',
    answerRu: 'Генератор (function*) — функция, которую можно приостанавливать через yield и возобновлять. До появления async/await генераторы с co-библиотеками использовались для асинхронного кода. Сейчас актуальны для ленивых коллекций и бесконечных последовательностей.',
    answerEn: 'A generator (function*) is a function that can be paused with yield and resumed. Before async/await, generators combined with co-libraries were used for async code. Today they are mainly used for lazy collections and infinite sequences.',
    tags: ['event-loop', 'async'],
    order: 41,
  },
  {
    id: 'js-042',
    difficulty: 'HARD',
    questionRu: 'Что такое queueMicrotask?',
    questionEn: 'What is queueMicrotask?',
    answerRu: 'queueMicrotask(fn) добавляет функцию в очередь микрозадач напрямую, без создания промиса. Полезно, когда нужно отложить выполнение до конца текущей задачи, но с приоритетом выше setTimeout. Аналогично Promise.resolve().then(fn), но более явно.',
    answerEn: 'queueMicrotask(fn) adds a function directly to the microtask queue without creating a promise. Useful when you need to defer execution until after the current task but with higher priority than setTimeout. Equivalent to Promise.resolve().then(fn) but more explicit.',
    tags: ['event-loop', 'async'],
    order: 42,
  },
  {
    id: 'js-043',
    difficulty: 'EASY',
    questionRu: 'Что такое Promise и какие у него состояния?',
    questionEn: 'What is a Promise and what states does it have?',
    answerRu: 'Promise — объект, представляющий результат асинхронной операции. Три состояния: pending (ожидание), fulfilled (выполнен успешно), rejected (отклонён). Переход состояния необратим. Создаётся через new Promise((resolve, reject) => ...).',
    answerEn: 'A Promise is an object representing the result of an asynchronous operation. Three states: pending, fulfilled (resolved successfully), rejected. State transitions are irreversible. Created via new Promise((resolve, reject) => ...).',
    tags: ['promises', 'async-await'],
    order: 43,
  },
  {
    id: 'js-044',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между Promise.all, Promise.allSettled, Promise.race, Promise.any?',
    questionEn: 'What is the difference between Promise.all, Promise.allSettled, Promise.race, and Promise.any?',
    answerRu: 'Promise.all: ждёт все, отклоняется при первой ошибке. Promise.allSettled: ждёт все, возвращает статус каждого. Promise.race: возвращает первый завершившийся (успех или ошибка). Promise.any: возвращает первый успешный, ошибка только если все отклонены.',
    answerEn: 'Promise.all: waits for all, rejects on the first failure. Promise.allSettled: waits for all, returns the status of each. Promise.race: returns the first settled (success or failure). Promise.any: returns the first fulfilled, fails only if all are rejected.',
    tags: ['promises', 'async-await'],
    order: 44,
  },
  {
    id: 'js-045',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает цепочка .then()?',
    questionEn: 'How does .then() chaining work?',
    answerRu: '.then() возвращает новый Promise. Если обработчик возвращает значение — следующий .then() получает его. Если возвращает Promise — цепочка ждёт его завершения. Ошибки перехватываются ближайшим .catch() ниже по цепочке.',
    answerEn: '.then() returns a new Promise. If the handler returns a value, the next .then() receives it. If it returns a Promise, the chain waits for it to settle. Errors are caught by the nearest .catch() further down the chain.',
    tags: ['promises', 'async-await'],
    order: 45,
  },
  {
    id: 'js-046',
    difficulty: 'EASY',
    questionRu: 'Что такое async/await?',
    questionEn: 'What is async/await?',
    answerRu: 'async/await — синтаксический сахар над промисами. async функция всегда возвращает Promise. await приостанавливает выполнение функции до разрешения промиса. Делает асинхронный код похожим на синхронный, упрощает чтение и обработку ошибок через try/catch.',
    answerEn: 'async/await is syntactic sugar over promises. An async function always returns a Promise. await pauses execution until the promise settles. It makes asynchronous code look synchronous and simplifies error handling with try/catch.',
    tags: ['promises', 'async-await'],
    order: 46,
  },
  {
    id: 'js-047',
    difficulty: 'MEDIUM',
    questionRu: 'Как обрабатывать ошибки в async/await?',
    questionEn: 'How do you handle errors in async/await?',
    answerRu: 'Три способа: 1) try/catch вокруг await. 2) .catch() после вызова async-функции: asyncFn().catch(err => ...). 3) Обёртка-хелпер to(promise), возвращающий [error, data]. try/catch предпочтителен для читаемости.',
    answerEn: 'Three approaches: 1) try/catch around await. 2) .catch() after the async function call: asyncFn().catch(err => ...). 3) A helper wrapper to(promise) returning [error, data]. try/catch is preferred for readability.',
    tags: ['promises', 'async-await'],
    order: 47,
  },
  {
    id: 'js-048',
    difficulty: 'MEDIUM',
    questionRu: 'Как выполнить несколько промисов параллельно с async/await?',
    questionEn: 'How do you run multiple promises in parallel with async/await?',
    answerRu: 'Не использовать await последовательно — это последовательное выполнение. Для параллельного: const [a, b] = await Promise.all([fetchA(), fetchB()]). Или стартовать оба без await, потом ждать: const pA = fetchA(); const pB = fetchB(); await Promise.all([pA, pB]).',
    answerEn: 'Do not await them sequentially — that is serial execution. For parallel: const [a, b] = await Promise.all([fetchA(), fetchB()]). Or start both without await and wait later: const pA = fetchA(); const pB = fetchB(); await Promise.all([pA, pB]).',
    tags: ['promises', 'async-await'],
    order: 48,
  },
  {
    id: 'js-049',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое Promise chaining vs async/await — когда что использовать?',
    questionEn: 'Promise chaining vs async/await — when should you use each?',
    answerRu: 'Цепочки .then() удобны для простых трансформаций данных и когда нужно явно видеть поток. async/await лучше для сложной логики с ветвлениями, циклами, try/catch. На практике часто смешивают: async/await внутри + Promise.all для параллелизма.',
    answerEn: '.then() chains work well for simple data transformations and when you want an explicit data flow. async/await is better for complex logic with branching, loops, and try/catch. In practice they are often mixed: async/await inside + Promise.all for parallelism.',
    tags: ['promises', 'async-await'],
    order: 49,
  },
  {
    id: 'js-050',
    difficulty: 'MEDIUM',
    questionRu: 'Что произойдёт, если не обработать rejected Promise?',
    questionEn: 'What happens if you do not handle a rejected Promise?',
    answerRu: 'В браузере срабатывает событие unhandledrejection. В Node.js — UnhandledPromiseRejectionWarning (в новых версиях — завершение процесса). Всегда нужно обрабатывать ошибки: .catch() или try/catch. Глобальный обработчик: window.addEventListener("unhandledrejection", ...).',
    answerEn: 'In the browser the unhandledrejection event fires. In Node.js — UnhandledPromiseRejectionWarning (in newer versions the process terminates). Always handle errors via .catch() or try/catch. Global handler: window.addEventListener("unhandledrejection", ...).',
    tags: ['promises', 'async-await'],
    order: 50,
  },
  {
    id: 'js-051',
    difficulty: 'MEDIUM',
    questionRu: 'Можно ли использовать await вне async функции?',
    questionEn: 'Can you use await outside an async function?',
    answerRu: 'В ES2022 появился Top-level await — можно использовать await на верхнем уровне ES-модуля (.mjs или type="module"). В обычных скриптах — нельзя. В Node.js поддерживается в .mjs файлах или с "type": "module" в package.json.',
    answerEn: 'ES2022 introduced top-level await — you can use await at the top level of an ES module (.mjs or type="module"). In regular scripts it is not allowed. In Node.js it is supported in .mjs files or with "type": "module" in package.json.',
    tags: ['promises', 'async-await'],
    order: 51,
  },
  {
    id: 'js-052',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает Promise.resolve() и Promise.reject()?',
    questionEn: 'How do Promise.resolve() and Promise.reject() work?',
    answerRu: 'Promise.resolve(value) возвращает уже выполненный промис с переданным значением. Если передать промис — возвращает его же. Promise.reject(reason) возвращает уже отклонённый промис. Полезны для нормализации значений в Promise-based API.',
    answerEn: 'Promise.resolve(value) returns an already-fulfilled promise with the given value. If a promise is passed, it returns that same promise. Promise.reject(reason) returns an already-rejected promise. Useful for normalizing values in promise-based APIs.',
    tags: ['promises', 'async-await'],
    order: 52,
  },
  {
    id: 'js-053',
    difficulty: 'EASY',
    questionRu: 'Что такое деструктуризация?',
    questionEn: 'What is destructuring?',
    answerRu: 'Деструктуризация позволяет извлекать значения из массивов и свойства объектов в переменные. Массив: const [a, b] = [1, 2]. Объект: const { name, age } = user. Поддерживает значения по умолчанию, переименование, вложенную деструктуризацию и rest-паттерн.',
    answerEn: 'Destructuring lets you unpack values from arrays and properties from objects into variables. Array: const [a, b] = [1, 2]. Object: const { name, age } = user. Supports default values, renaming, nested destructuring, and the rest pattern.',
    tags: ['es6', 'syntax'],
    order: 53,
  },
  {
    id: 'js-054',
    difficulty: 'EASY',
    questionRu: 'Как работает spread и rest оператор?',
    questionEn: 'How do the spread and rest operators work?',
    answerRu: 'Оба используют синтаксис (...). Spread — разворачивает итерируемое: [...arr], {...obj}, fn(...args). Rest — собирает оставшиеся элементы в массив: function(a, ...rest), const {x, ...others} = obj. Rest всегда последний в списке параметров/деструктуризации.',
    answerEn: 'Both use the (...) syntax. Spread — expands an iterable: [...arr], {...obj}, fn(...args). Rest — collects remaining elements into an array: function(a, ...rest), const {x, ...others} = obj. Rest must always be last in a parameter list or destructuring.',
    tags: ['es6', 'syntax'],
    order: 54,
  },
  {
    id: 'js-055',
    difficulty: 'EASY',
    questionRu: 'Что такое template literals?',
    questionEn: 'What are template literals?',
    answerRu: 'Template literals — строки в обратных кавычках (`). Возможности: многострочность, интерполяция выражений ${expr}, tagged templates (функция перед шаблоном для обработки). Пример: `Hello, ${user.name}! You are ${age > 18 ? "adult" : "minor"}.`',
    answerEn: 'Template literals are strings enclosed in backticks (`). Features: multi-line strings, expression interpolation ${expr}, and tagged templates (a function before the template for custom processing). Example: `Hello, ${user.name}! You are ${age > 18 ? "adult" : "minor"}.`',
    tags: ['es6', 'syntax'],
    order: 55,
  },
  {
    id: 'js-056',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое Map и Set, чем отличаются от объектов и массивов?',
    questionEn: 'What are Map and Set, and how do they differ from objects and arrays?',
    answerRu: 'Map — коллекция ключ-значение, где ключом может быть любой тип (включая объекты). Итерируется в порядке вставки. Set — коллекция уникальных значений. Преимущества над объектом/массивом: лучшая производительность при частых добавлениях/удалениях, нет конфликтов с прототипом.',
    answerEn: 'Map is a key-value collection where keys can be of any type (including objects). Iterates in insertion order. Set is a collection of unique values. Advantages over plain objects/arrays: better performance for frequent additions/deletions, no prototype key conflicts.',
    tags: ['es6', 'syntax'],
    order: 56,
  },
  {
    id: 'js-057',
    difficulty: 'HARD',
    questionRu: 'Что такое WeakMap и WeakSet?',
    questionEn: 'What are WeakMap and WeakSet?',
    answerRu: 'WeakMap и WeakSet хранят объекты по слабым ссылкам — если объект нигде больше не используется, сборщик мусора его удалит вместе с записью. Не итерируемы. Используются для кэширования, хранения метаданных объектов без утечек памяти.',
    answerEn: 'WeakMap and WeakSet hold objects via weak references — if an object is no longer referenced elsewhere, the garbage collector will remove it along with its entry. They are not iterable. Used for caching and storing per-object metadata without memory leaks.',
    tags: ['es6', 'syntax'],
    order: 57,
  },
  {
    id: 'js-058',
    difficulty: 'HARD',
    questionRu: 'Что такое Proxy и Reflect?',
    questionEn: 'What are Proxy and Reflect?',
    answerRu: 'Proxy позволяет перехватывать операции над объектом (get, set, has, deleteProperty и др.) через обработчики-ловушки (traps). Reflect — объект с методами, зеркально повторяющими ловушки Proxy, для правильного дефолтного поведения. Используются в реактивных системах (Vue 3).',
    answerEn: 'Proxy lets you intercept operations on an object (get, set, has, deleteProperty, etc.) via handler traps. Reflect is an object whose methods mirror the Proxy traps and provide correct default behavior. Used in reactive systems such as Vue 3.',
    tags: ['es6', 'syntax'],
    order: 58,
  },
  {
    id: 'js-059',
    difficulty: 'HARD',
    questionRu: 'Как работают итераторы и Symbol.iterator?',
    questionEn: 'How do iterators and Symbol.iterator work?',
    answerRu: 'Итератор — объект с методом next(), возвращающим {value, done}. Symbol.iterator — метод, возвращающий итератор. Объект с Symbol.iterator итерируется в for...of. Встроенные итерируемые: массивы, строки, Map, Set, генераторы.',
    answerEn: 'An iterator is an object with a next() method that returns {value, done}. Symbol.iterator is a method that returns an iterator. An object that has Symbol.iterator can be iterated with for...of. Built-in iterables: arrays, strings, Map, Set, generators.',
    tags: ['es6', 'syntax'],
    order: 59,
  },
  {
    id: 'js-060',
    difficulty: 'MEDIUM',
    questionRu: 'Что нового в ES2022-2024?',
    questionEn: 'What is new in ES2022-2024?',
    answerRu: 'ES2022: приватные поля (#), Top-level await, at(), Object.hasOwn(). ES2023: findLast(), toSorted/toReversed/toSpliced (не мутируют). ES2024: Object.groupBy(), Promise.withResolvers(), Temporal API (stage 3). Стоит знать хотя бы ES2022.',
    answerEn: 'ES2022: private fields (#), top-level await, at(), Object.hasOwn(). ES2023: findLast(), toSorted/toReversed/toSpliced (non-mutating). ES2024: Object.groupBy(), Promise.withResolvers(), Temporal API (stage 3). At minimum, know ES2022.',
    tags: ['es6', 'syntax'],
    order: 60,
  },
  {
    id: 'js-061',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между shallow copy и deep copy?',
    questionEn: 'What is the difference between a shallow copy and a deep copy?',
    answerRu: 'Shallow copy (Object.assign, spread): копирует верхний уровень, вложенные объекты — по ссылке. Deep copy: полная независимая копия. Способы deep copy: structuredClone() (ES2022, нативный), JSON.parse(JSON.stringify()) (теряет функции/undefined), рекурсивная функция, lodash.cloneDeep.',
    answerEn: 'Shallow copy (Object.assign, spread): copies the top level, nested objects are copied by reference. Deep copy: a fully independent copy. Deep copy approaches: structuredClone() (ES2022, native), JSON.parse(JSON.stringify()) (loses functions/undefined), a recursive function, lodash.cloneDeep.',
    tags: ['arrays', 'objects'],
    order: 61,
  },
  {
    id: 'js-062',
    difficulty: 'EASY',
    questionRu: 'Какие методы массива не мутируют оригинал?',
    questionEn: 'Which array methods do not mutate the original array?',
    answerRu: 'Немутирующие: map, filter, reduce, slice, concat, flat, flatMap, find, findIndex, some, every, includes, indexOf, toSorted, toReversed, toSpliced. Мутирующие: push, pop, shift, unshift, splice, sort, reverse, fill. Предпочтительно использовать немутирующие.',
    answerEn: 'Non-mutating: map, filter, reduce, slice, concat, flat, flatMap, find, findIndex, some, every, includes, indexOf, toSorted, toReversed, toSpliced. Mutating: push, pop, shift, unshift, splice, sort, reverse, fill. Prefer non-mutating methods.',
    tags: ['arrays', 'objects'],
    order: 62,
  },
  {
    id: 'js-063',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает Array.reduce()?',
    questionEn: 'How does Array.reduce() work?',
    answerRu: 'reduce(callback, initialValue) проходит по массиву, аккумулируя результат. callback(accumulator, currentValue, index, array). Без initialValue первый элемент — аккумулятор. Применение: сумма, группировка объектов, создание Map, flat.',
    answerEn: 'reduce(callback, initialValue) iterates over the array accumulating a result. callback(accumulator, currentValue, index, array). Without initialValue the first element becomes the accumulator. Use cases: sum, grouping objects, building a Map, flattening.',
    tags: ['arrays', 'objects'],
    order: 63,
  },
  {
    id: 'js-064',
    difficulty: 'EASY',
    questionRu: 'Как проверить, является ли значение массивом?',
    questionEn: 'How do you check if a value is an array?',
    answerRu: 'Array.isArray(value) — рекомендуемый способ, работает корректно для массивов из разных фреймов. typeof [] === "object" — не подходит. instanceof Array — ненадёжно в мульти-фреймовых средах. value.constructor === Array — ненадёжно при изменённом прототипе.',
    answerEn: 'Array.isArray(value) is the recommended way and works correctly for arrays from different frames. typeof [] === "object" is not sufficient. instanceof Array is unreliable in multi-frame environments. value.constructor === Array is unreliable with modified prototypes.',
    tags: ['arrays', 'objects'],
    order: 64,
  },
  {
    id: 'js-065',
    difficulty: 'EASY',
    questionRu: 'Как удалить дубликаты из массива?',
    questionEn: 'How do you remove duplicates from an array?',
    answerRu: 'Способы: 1) [...new Set(arr)] — быстро для примитивов. 2) filter + indexOf: arr.filter((v,i) => arr.indexOf(v) === i). 3) reduce для объектов по ключу. Для объектов со сложной логикой сравнения — ручная фильтрация.',
    answerEn: 'Options: 1) [...new Set(arr)] — fast for primitives. 2) filter + indexOf: arr.filter((v,i) => arr.indexOf(v) === i). 3) reduce by key for objects. For objects with complex comparison logic — manual filtering.',
    tags: ['arrays', 'objects'],
    order: 65,
  },
  {
    id: 'js-066',
    difficulty: 'EASY',
    questionRu: 'Как перебрать свойства объекта?',
    questionEn: 'How do you iterate over object properties?',
    answerRu: 'for...in: перебирает все перечислимые свойства включая унаследованные. Object.keys(): только собственные перечислимые. Object.values(): значения. Object.entries(): пары [ключ, значение]. for...of с Object.entries() — самый удобный способ.',
    answerEn: 'for...in: iterates all enumerable properties including inherited ones. Object.keys(): own enumerable keys only. Object.values(): values. Object.entries(): [key, value] pairs. for...of with Object.entries() is the most convenient approach.',
    tags: ['arrays', 'objects'],
    order: 66,
  },
  {
    id: 'js-067',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое иммутабельность и зачем она нужна?',
    questionEn: 'What is immutability and why does it matter?',
    answerRu: 'Иммутабельность — неизменяемость данных после создания. Преимущества: предсказуемость состояния, простота отладки, безопасное сравнение по ссылке (для React). JS: Object.freeze() (поверхностно). Паттерн: создавать новые объекты вместо мутации (spread, map, filter).',
    answerEn: 'Immutability means data cannot be changed after creation. Benefits: predictable state, easier debugging, safe reference comparison (important for React). In JS: Object.freeze() (shallow). Pattern: always create new objects instead of mutating (spread, map, filter).',
    tags: ['arrays', 'objects'],
    order: 67,
  },
  {
    id: 'js-068',
    difficulty: 'MEDIUM',
    questionRu: 'Как работает Object.freeze() и Object.seal()?',
    questionEn: 'How do Object.freeze() and Object.seal() work?',
    answerRu: 'Object.freeze(): нельзя добавлять, удалять или изменять свойства. Поверхностно — вложенные объекты не заморожены. Object.seal(): нельзя добавлять или удалять, но изменять значения можно. Для глубокой заморозки нужна рекурсия.',
    answerEn: 'Object.freeze(): properties cannot be added, removed, or changed. Shallow — nested objects are not frozen. Object.seal(): properties cannot be added or removed, but existing values can be changed. Deep freezing requires a recursive function.',
    tags: ['arrays', 'objects'],
    order: 68,
  },
  {
    id: 'js-069',
    difficulty: 'EASY',
    questionRu: 'В чём разница между for...of и for...in?',
    questionEn: 'What is the difference between for...of and for...in?',
    answerRu: 'for...in перебирает ключи объекта (все перечислимые, включая унаследованные) — для объектов. for...of перебирает значения итерируемых объектов (массивы, строки, Map, Set, генераторы). Использование for...in для массивов считается антипаттерном.',
    answerEn: 'for...in iterates over an object\'s keys (all enumerable ones, including inherited) — intended for objects. for...of iterates over the values of iterables (arrays, strings, Map, Set, generators). Using for...in on arrays is considered an anti-pattern.',
    tags: ['arrays', 'objects'],
    order: 69,
  },
  {
    id: 'js-070',
    difficulty: 'MEDIUM',
    questionRu: 'Как сравнить два объекта на равенство?',
    questionEn: 'How do you compare two objects for equality?',
    answerRu: 'obj1 === obj2 проверяет ссылки, не содержимое. Для содержимого: JSON.stringify (теряет порядок, undefined, функции). Рекурсивное сравнение: Object.keys + рекурсия. Библиотека: lodash.isEqual. structuredClone для копирования, но не для сравнения.',
    answerEn: 'obj1 === obj2 checks references, not content. For content comparison: JSON.stringify (loses key order, undefined, functions). Recursive comparison: Object.keys + recursion. Library: lodash.isEqual. structuredClone is for copying, not comparison.',
    tags: ['arrays', 'objects'],
    order: 70,
  },
  {
    id: 'js-071',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое всплытие и погружение событий?',
    questionEn: 'What are event bubbling and capturing?',
    answerRu: 'Событие проходит 3 фазы: capture (погружение от document до элемента), target (целевой элемент), bubble (всплытие от элемента до document). addEventListener(event, fn, true) — capture фаза. По умолчанию — bubble. stopPropagation() останавливает распространение.',
    answerEn: 'An event passes through 3 phases: capture (from document down to the element), target (the target element itself), and bubble (from the element up to document). addEventListener(event, fn, true) registers for the capture phase. The default is bubble. stopPropagation() stops propagation.',
    tags: ['events', 'dom'],
    order: 71,
  },
  {
    id: 'js-072',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое делегирование событий?',
    questionEn: 'What is event delegation?',
    answerRu: 'Делегирование — установка одного обработчика на родителя вместо множества на дочерние элементы. Работает через всплытие. Преимущества: меньше памяти, работает с динамически добавленными элементами. event.target определяет конкретный элемент.',
    answerEn: 'Event delegation means attaching a single handler to a parent instead of many handlers to child elements. It works via bubbling. Benefits: less memory usage, works for dynamically added elements. event.target identifies the specific element that was interacted with.',
    tags: ['events', 'dom'],
    order: 72,
  },
  {
    id: 'js-073',
    difficulty: 'MEDIUM',
    questionRu: 'В чём разница между e.stopPropagation() и e.preventDefault()?',
    questionEn: 'What is the difference between e.stopPropagation() and e.preventDefault()?',
    answerRu: 'stopPropagation() — останавливает распространение события по DOM-дереву (всплытие/погружение). preventDefault() — отменяет стандартное поведение браузера (переход по ссылке, отправка формы). Независимы: можно вызвать оба или только один.',
    answerEn: 'stopPropagation() stops the event from propagating through the DOM tree (bubbling/capturing). preventDefault() cancels the browser\'s default behavior (following a link, submitting a form). They are independent: you can call both or just one.',
    tags: ['events', 'dom'],
    order: 73,
  },
  {
    id: 'js-074',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое виртуальный DOM?',
    questionEn: 'What is the virtual DOM?',
    answerRu: 'Virtual DOM — легковесное JS-представление реального DOM. При изменениях сначала обновляется VDOM, затем алгоритм диффинга находит минимальный набор изменений и применяет их к реальному DOM (reconciliation). Используется в React, Vue 2. Ускоряет работу за счёт пакетных обновлений.',
    answerEn: 'The virtual DOM is a lightweight JavaScript representation of the real DOM. On changes, the VDOM is updated first, then a diffing algorithm finds the minimal set of changes and applies them to the real DOM (reconciliation). Used by React and Vue 2. Speeds up updates by batching them.',
    tags: ['events', 'dom'],
    order: 74,
  },
  {
    id: 'js-075',
    difficulty: 'MEDIUM',
    questionRu: 'Как эффективно добавить много DOM-элементов?',
    questionEn: 'How do you efficiently add many DOM elements?',
    answerRu: 'Использовать DocumentFragment: создать фрагмент, добавить все элементы в него, потом одним вызовом вставить в DOM. Это вызывает единственный reflow. Альтернативы: innerHTML (осторожно с XSS), insertAdjacentHTML, шаблонизация с сериализацией.',
    answerEn: 'Use a DocumentFragment: create a fragment, add all elements to it, then insert it into the DOM in a single call. This triggers only one reflow. Alternatives: innerHTML (watch out for XSS), insertAdjacentHTML, template-based serialization.',
    tags: ['events', 'dom'],
    order: 75,
  },
  {
    id: 'js-076',
    difficulty: 'HARD',
    questionRu: 'Что такое MutationObserver?',
    questionEn: 'What is MutationObserver?',
    answerRu: 'MutationObserver — API для отслеживания изменений в DOM-дереве (добавление/удаление узлов, изменения атрибутов, текстового содержимого). Асинхронный, использует микрозадачи. Замена устаревшим мутационным событиям. Используется в полифилах, отслеживании изменений.',
    answerEn: 'MutationObserver is an API for watching changes in the DOM tree (node additions/removals, attribute changes, text content changes). It is asynchronous and uses microtasks. It replaces the deprecated mutation events. Used in polyfills and change-tracking scenarios.',
    tags: ['events', 'dom'],
    order: 76,
  },
  {
    id: 'js-077',
    difficulty: 'HARD',
    questionRu: 'Как работает IntersectionObserver?',
    questionEn: 'How does IntersectionObserver work?',
    answerRu: 'IntersectionObserver отслеживает пересечение элемента с viewport или другим элементом. Используется для: ленивой загрузки изображений, бесконечного скролла, анимаций при появлении. Эффективнее scroll-события — не блокирует main thread.',
    answerEn: 'IntersectionObserver tracks when an element intersects the viewport or another element. Used for: lazy loading images, infinite scroll, entrance animations. More efficient than scroll events — does not block the main thread.',
    tags: ['events', 'dom'],
    order: 77,
  },
  {
    id: 'js-078',
    difficulty: 'EASY',
    questionRu: 'В чём разница между innerHTML, textContent и innerText?',
    questionEn: 'What is the difference between innerHTML, textContent, and innerText?',
    answerRu: 'innerHTML: возвращает/устанавливает HTML-разметку (риск XSS). textContent: только текст, включая скрытые элементы, не вызывает reflow. innerText: только видимый текст, учитывает CSS (display:none скрывает), вызывает reflow. Для вставки пользовательских данных — всегда textContent.',
    answerEn: 'innerHTML: gets/sets HTML markup (XSS risk). textContent: plain text only, includes hidden elements, does not cause reflow. innerText: visible text only, respects CSS (display:none hides content), causes reflow. When inserting user-supplied data — always use textContent.',
    tags: ['events', 'dom'],
    order: 78,
  },
];
