import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'net-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['http'],
    questionRu: 'Что такое HTTP и как работает запрос-ответ?',
    questionEn: 'What is HTTP and how does the request-response cycle work?',
    answerRu: '**HTTP** — протокол передачи данных клиент-сервер.\n\nКлиент отправляет **Request**: метод, URL, заголовки, тело.\n\nСервер отвечает **Response**: статус-код, заголовки, тело.\n\n- **Stateless** — каждый запрос независим\n- Работает поверх **TCP/IP**\n- **HTTPS** = HTTP + TLS шифрование',
    answerEn: '**HTTP** is a client-server data transfer protocol.\n\nThe client sends a **Request**: method, URL, headers, body.\n\nThe server responds with a **Response**: status code, headers, body.\n\n- **Stateless** — each request is independent\n- Runs on top of **TCP/IP**\n- **HTTPS** = HTTP + TLS encryption',
  },
  {
    id: 'net-002',
    difficulty: 'EASY',
    order: 2,
    tags: ['http'],
    questionRu: 'Какие HTTP методы существуют и чем отличаются?',
    questionEn: 'What HTTP methods exist and how do they differ?',
    answerRu: '- `GET`: получить данные, без тела, **идемпотентный**\n- `POST`: создать ресурс, с телом, **не идемпотентный**\n- `PUT`: заменить ресурс целиком, **идемпотентный**\n- `PATCH`: частично обновить\n- `DELETE`: удалить, **идемпотентный**\n- `HEAD`: только заголовки без тела\n- `OPTIONS`: узнать поддерживаемые методы (используется в CORS preflight)',
    answerEn: '- `GET`: retrieve data, no body, **idempotent**\n- `POST`: create a resource, has body, **not idempotent**\n- `PUT`: replace a resource entirely, **idempotent**\n- `PATCH`: partially update\n- `DELETE`: remove, **idempotent**\n- `HEAD`: headers only, no body\n- `OPTIONS`: discover supported methods (used in CORS preflight)',
  },
  {
    id: 'net-003',
    difficulty: 'EASY',
    order: 3,
    tags: ['http'],
    questionRu: 'Что означают группы HTTP статус-кодов?',
    questionEn: 'What do the HTTP status code groups mean?',
    answerRu: '- `1xx`: информационные\n- `2xx`: успех — `200 OK`, `201 Created`, `204 No Content`\n- `3xx`: редиректы — `301 Moved Permanently`, `302 Found`, `304 Not Modified`\n- `4xx`: ошибки клиента — `400 Bad Request`, `401 Unauthorized`, `403 Forbidden`, `404 Not Found`, `422 Unprocessable Entity`\n- `5xx`: ошибки сервера — `500`, `503`',
    answerEn: '- `1xx`: informational\n- `2xx`: success — `200 OK`, `201 Created`, `204 No Content`\n- `3xx`: redirects — `301 Moved Permanently`, `302 Found`, `304 Not Modified`\n- `4xx`: client errors — `400 Bad Request`, `401 Unauthorized`, `403 Forbidden`, `404 Not Found`, `422 Unprocessable Entity`\n- `5xx`: server errors — `500`, `503`',
  },
  {
    id: 'net-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['http'],
    questionRu: 'В чём разница между HTTP/1.1, HTTP/2 и HTTP/3?',
    questionEn: 'What is the difference between HTTP/1.1, HTTP/2, and HTTP/3?',
    answerRu: '- **HTTP/1.1**: текстовый, один запрос за раз на соединение, **head-of-line blocking**\n- **HTTP/2**: бинарный, **мультиплексирование** (много запросов по одному TCP), сжатие заголовков (**HPACK**), server push\n- **HTTP/3**: поверх **QUIC** (UDP), устраняет TCP head-of-line blocking, быстрое восстановление соединения',
    answerEn: '- **HTTP/1.1**: text-based, one request at a time per connection, **head-of-line blocking**\n- **HTTP/2**: binary, **multiplexing** (many requests over one TCP connection), header compression (**HPACK**), server push\n- **HTTP/3**: runs over **QUIC** (UDP), eliminates TCP head-of-line blocking, faster connection recovery',
  },
  {
    id: 'net-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['http'],
    questionRu: 'Что такое идемпотентность и безопасность методов?',
    questionEn: 'What are idempotency and safety of HTTP methods?',
    answerRu: '**Безопасный** метод не изменяет состояние сервера: `GET`, `HEAD`, `OPTIONS`.\n\n**Идемпотентный** метод даёт одинаковый результат при повторных вызовах: `GET`, `PUT`, `DELETE`, `HEAD`.\n\n- `POST` — ни безопасный, ни идемпотентный\n- `PATCH` — не обязательно идемпотентный\n\nВажно для retry-логики при сетевых ошибках.',
    answerEn: 'A **safe** method does not modify server state: `GET`, `HEAD`, `OPTIONS`.\n\nAn **idempotent** method produces the same result no matter how many times it is called: `GET`, `PUT`, `DELETE`, `HEAD`.\n\n- `POST` is neither safe nor idempotent\n- `PATCH` is not necessarily idempotent\n\nThis matters for retry logic when network errors occur.',
  },
  {
    id: 'net-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['http'],
    questionRu: 'Что такое CORS и как он работает?',
    questionEn: 'What is CORS and how does it work?',
    answerRu: '**CORS** (Cross-Origin Resource Sharing) — механизм разрешения запросов между разными origin.\n\n1. Браузер добавляет заголовок `Origin`\n2. Сервер отвечает `Access-Control-Allow-Origin`\n\n- **Простые запросы** (`GET`/`POST` с простыми заголовками) — без preflight\n- **Сложные запросы** — сначала `OPTIONS` preflight\n\nCORS — защита **браузера**, не сервера.',
    answerEn: '**CORS** (Cross-Origin Resource Sharing) is a mechanism for permitting cross-origin requests.\n\n1. The browser adds an `Origin` header\n2. The server responds with `Access-Control-Allow-Origin`\n\n- **Simple requests** (`GET`/`POST` with simple headers) go without a preflight\n- **Complex requests** first trigger an `OPTIONS` preflight\n\nCORS is a **browser-side** protection, not a server-side one.',
  },
  {
    id: 'net-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['http'],
    questionRu: 'Что такое preflight запрос?',
    questionEn: 'What is a preflight request?',
    answerRu: '**Preflight** — автоматический `OPTIONS` запрос браузера перед сложным CORS запросом.\n\nПроверяет разрешение метода и заголовков. Сервер отвечает:\n- `Access-Control-Allow-Methods`\n- `Access-Control-Allow-Headers`\n- `Access-Control-Max-Age` (кеш preflight)\n\n**Триггеры**: нестандартные методы, заголовки типа `Authorization`, `Content-Type: application/json`.',
    answerEn: 'A **preflight** is an automatic `OPTIONS` request the browser sends before a complex CORS request.\n\nIt checks whether the method and headers are allowed. The server responds with:\n- `Access-Control-Allow-Methods`\n- `Access-Control-Allow-Headers`\n- `Access-Control-Max-Age` (preflight cache duration)\n\n**Triggers**: non-simple methods, headers such as `Authorization`, `Content-Type: application/json`.',
  },
  {
    id: 'net-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['http'],
    questionRu: 'Что такое HTTP кеширование и какие заголовки управляют им?',
    questionEn: 'What is HTTP caching and which headers control it?',
    answerRu: '**Cache-Control** директивы:\n- `max-age=3600` — кешировать 1 час\n- `no-cache` — кешировать, но валидировать с сервером\n- `no-store` — не кешировать\n- `immutable` — никогда не устареет\n\n**ETag** — хеш ресурса: клиент отправляет `If-None-Match`, сервер отвечает `304` если не изменилось.\n\n**Last-Modified** / `If-Modified-Since` — аналог по дате.',
    answerEn: '**Cache-Control** directives:\n- `max-age=3600` — cache for 1 hour\n- `no-cache` — cache but revalidate with the server\n- `no-store` — do not cache\n- `immutable` — will never be stale\n\n**ETag** — a resource hash: the client sends `If-None-Match`, the server replies `304` if unchanged.\n\n**Last-Modified** / `If-Modified-Since` — the date-based equivalent.',
  },
  {
    id: 'net-009',
    difficulty: 'EASY',
    order: 9,
    tags: ['security'],
    questionRu: 'Что такое HTTPS и TLS?',
    questionEn: 'What are HTTPS and TLS?',
    answerRu: '**HTTPS** = HTTP + **TLS** (Transport Layer Security).\n\nTLS обеспечивает:\n- шифрование трафика\n- аутентификацию сервера через сертификат\n- целостность данных\n\n**TLS handshake**: обмен сертификатами → согласование cipher suite → обмен ключами.\n\nБез HTTPS: перехват (**MITM**), подмена данных, утечка паролей и cookies.',
    answerEn: '**HTTPS** = HTTP + **TLS** (Transport Layer Security).\n\nTLS provides:\n- traffic encryption\n- server authentication via a certificate\n- data integrity\n\n**TLS handshake**: certificate exchange → cipher suite negotiation → key exchange.\n\nWithout HTTPS: interception (**MITM**), data tampering, leakage of passwords and cookies.',
  },
  {
    id: 'net-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['security'],
    questionRu: 'Что такое cookies и атрибуты безопасности?',
    questionEn: 'What are cookies and their security attributes?',
    answerRu: '- `HttpOnly`: недоступен через JS — защита от **XSS**\n- `Secure`: только по HTTPS\n- `SameSite`:\n  - `Strict` — только same-site запросы\n  - `Lax` — разрешает GET cross-site (по умолчанию)\n  - `None` — все запросы, требует `Secure`\n- `Domain` и `Path` ограничивают область действия\n- `Max-Age` / `Expires` — срок жизни',
    answerEn: '- `HttpOnly`: inaccessible via JS — protects against **XSS**\n- `Secure`: HTTPS only\n- `SameSite`:\n  - `Strict` — same-site requests only\n  - `Lax` — allows cross-site GET (default)\n  - `None` — all requests, requires `Secure`\n- `Domain` and `Path` restrict scope\n- `Max-Age` / `Expires` — lifetime',
  },
  {
    id: 'net-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['security'],
    questionRu: 'Что такое Content Security Policy (CSP)?',
    questionEn: 'What is Content Security Policy (CSP)?',
    answerRu: "**CSP** — заголовок `Content-Security-Policy`, ограничивающий источники ресурсов.\n\n- `default-src 'self'` — только свой домен\n- `script-src 'self' cdn.example.com` — скрипты только отсюда\n\nБлокирует **inline-скрипты** (защита от XSS).\n\n`report-uri` — для логирования нарушений. Мощная защита, требует тщательной настройки.",
    answerEn: "**CSP** is the `Content-Security-Policy` header that restricts resource sources.\n\n- `default-src 'self'` — own domain only\n- `script-src 'self' cdn.example.com` — scripts from these sources only\n\nBlocks **inline scripts** (protection against XSS).\n\n`report-uri` — for logging violations. Powerful protection, but requires careful configuration.",
  },
  {
    id: 'net-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['security'],
    questionRu: 'Какие security заголовки важно выставлять?',
    questionEn: 'Which security headers are important to set?',
    answerRu: '- `Strict-Transport-Security` (**HSTS**): только HTTPS, `max-age=31536000`\n- `X-Content-Type-Options: nosniff` — не угадывать MIME\n- `X-Frame-Options: DENY` / `SAMEORIGIN` — защита от **clickjacking**\n- `Referrer-Policy`: контроль заголовка `Referer`\n- `Permissions-Policy`: ограничение браузерных API (camera, geolocation)',
    answerEn: '- `Strict-Transport-Security` (**HSTS**): HTTPS only, `max-age=31536000`\n- `X-Content-Type-Options: nosniff` — do not sniff MIME types\n- `X-Frame-Options: DENY` / `SAMEORIGIN` — protection against **clickjacking**\n- `Referrer-Policy`: control over the `Referer` header\n- `Permissions-Policy`: restricts browser APIs (camera, geolocation)',
  },
  {
    id: 'net-013',
    difficulty: 'EASY',
    order: 13,
    tags: ['security'],
    questionRu: 'В чём разница между аутентификацией и авторизацией?',
    questionEn: 'What is the difference between authentication and authorization?',
    answerRu: '**Аутентификация** — проверка личности (кто ты?): логин/пароль, OAuth, биометрия.\n\n**Авторизация** — проверка прав (что тебе можно?): роли, разрешения.\n\nПорядок: сначала аутентификация, затем авторизация.\n\n- `401 Unauthorized` — не аутентифицирован\n- `403 Forbidden` — аутентифицирован, но нет прав',
    answerEn: '**Authentication** — verifying identity (who are you?): login/password, OAuth, biometrics.\n\n**Authorization** — verifying permissions (what are you allowed to do?): roles, permissions.\n\nOrder: authentication first, then authorization.\n\n- `401 Unauthorized` — not authenticated\n- `403 Forbidden` — authenticated but lacks permission',
  },
  {
    id: 'net-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['security'],
    questionRu: 'Что такое JWT и как работает?',
    questionEn: 'What is JWT and how does it work?',
    answerRu: '**JWT** (JSON Web Token) — три части base64url: `header.payload.signature`.\n\n- **Header**: алгоритм подписи\n- **Payload**: claims (данные, `exp`, `iat`)\n- **Signature**: HMAC/RSA подпись\n\nСервер не хранит сессии — проверяет подпись.\n\n**Минусы**: нельзя отозвать до истечения, payload виден (не шифруется).\n\n**Access token** короткий, **refresh token** длинный.',
    answerEn: '**JWT** (JSON Web Token) consists of three base64url-encoded parts: `header.payload.signature`.\n\n- **Header**: signing algorithm\n- **Payload**: claims (data, `exp`, `iat`)\n- **Signature**: HMAC/RSA signature\n\nThe server stores no sessions — it just verifies the signature.\n\n**Downsides**: cannot be revoked before expiry, payload is visible (not encrypted).\n\n**Access token** is short-lived, **refresh token** is long-lived.',
  },
  {
    id: 'net-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['rest'],
    questionRu: 'Что такое REST и каковы его принципы?',
    questionEn: 'What is REST and what are its principles?',
    answerRu: '**REST** (Representational State Transfer) — архитектурный стиль API.\n\n**Принципы**:\n- ресурсы через URL (`/users/1`)\n- HTTP методы по назначению\n- **stateless** (без сессий на сервере)\n- единообразный интерфейс\n\n**Уровни зрелости Ричардсона**:\n- `0` — RPC\n- `1` — ресурсы\n- `2` — HTTP методы\n- `3` — HATEOAS',
    answerEn: '**REST** (Representational State Transfer) is an architectural style for APIs.\n\n**Principles**:\n- resources identified by URL (`/users/1`)\n- HTTP methods used semantically\n- **stateless** (no server-side sessions)\n- uniform interface\n\n**Richardson Maturity Model** levels:\n- `0` — RPC\n- `1` — resources\n- `2` — HTTP methods\n- `3` — HATEOAS',
  },
  {
    id: 'net-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['rest'],
    questionRu: 'Что такое GraphQL и чем отличается от REST?',
    questionEn: 'What is GraphQL and how does it differ from REST?',
    answerRu: '**GraphQL** — язык запросов для API.\n\n**Преимущества перед REST**:\n- клиент запрашивает точно нужные поля — нет **over/under fetching**\n- один endpoint вместо множества\n- строго типизированная схема\n\n**Минусы**:\n- сложнее кеширование\n- **N+1 проблема**\n- overhead для простых API\n\nREST проще, GraphQL гибче для сложных клиентов.',
    answerEn: '**GraphQL** is a query language for APIs.\n\n**Advantages over REST**:\n- the client requests exactly the fields it needs — no **over- or under-fetching**\n- a single endpoint instead of many\n- strongly typed schema\n\n**Downsides**:\n- harder caching\n- **N+1 problem**\n- overhead for simple APIs\n\nREST is simpler; GraphQL is more flexible for complex clients.',
  },
  {
    id: 'net-017',
    difficulty: 'EASY',
    order: 17,
    tags: ['rest'],
    questionRu: 'Что такое over-fetching и under-fetching в REST?',
    questionEn: 'What are over-fetching and under-fetching in REST?',
    answerRu: '**Over-fetching**: API возвращает больше данных чем нужно — `/users` возвращает все поля, нужны только `name` и `email`.\n\n**Under-fetching**: нужно несколько запросов для получения связанных данных — `/user/1`, затем `/user/1/posts`, затем `/posts/1/comments`.\n\n**GraphQL** решает обе проблемы одним запросом.',
    answerEn: '**Over-fetching**: the API returns more data than needed — `/users` returns all fields when only `name` and `email` are required.\n\n**Under-fetching**: multiple requests are needed to retrieve related data — `/user/1`, then `/user/1/posts`, then `/posts/1/comments`.\n\n**GraphQL** solves both problems with a single request.',
  },
  {
    id: 'net-018',
    difficulty: 'HARD',
    order: 18,
    tags: ['rest'],
    questionRu: 'Что такое N+1 проблема в GraphQL?',
    questionEn: 'What is the N+1 problem in GraphQL?',
    answerRu: '**N+1**: запрос списка N объектов с вложенными данными вызывает N+1 запросов к БД — 1 для списка + N для каждого элемента.\n\n**Решение**: **DataLoader** — батчинг и кеширование запросов в рамках одного GraphQL запроса.\n\nСобирает все ID, делает один запрос к БД, раздаёт результаты.',
    answerEn: '**N+1**: fetching a list of N objects with nested data triggers N+1 database queries — 1 for the list plus N for each item.\n\n**Solution**: **DataLoader** — batches and caches queries within a single GraphQL request.\n\nIt collects all IDs, makes one database query, and distributes the results.',
  },
  {
    id: 'net-019',
    difficulty: 'HARD',
    order: 19,
    tags: ['rest'],
    questionRu: 'Что такое REST vs RPC (gRPC)?',
    questionEn: 'What is REST vs RPC (gRPC)?',
    answerRu: '**REST**:\n- ресурсо-ориентированный\n- HTTP/1.1, JSON\n- самодокументируемый через URL\n\n**gRPC**:\n- функционально-ориентированный (вызов методов)\n- HTTP/2, **Protocol Buffers** (бинарный)\n- строгая типизация через `.proto` файлы\n- быстрее REST\n\ngRPC — для внутренних **микросервисов**, REST — для **публичных API**.',
    answerEn: '**REST**:\n- resource-oriented\n- HTTP/1.1, JSON\n- self-documenting via URL\n\n**gRPC**:\n- function-oriented (method calls)\n- HTTP/2, **Protocol Buffers** (binary)\n- strict typing via `.proto` files\n- faster than REST\n\ngRPC is preferred for internal **microservices**; REST is preferred for **public APIs**.',
  },
  {
    id: 'net-020',
    difficulty: 'HARD',
    order: 20,
    tags: ['rest'],
    questionRu: 'Что такое idempotency key?',
    questionEn: 'What is an idempotency key?',
    answerRu: '**Idempotency key** — уникальный ключ запроса (UUID) в заголовке, позволяющий безопасно повторять не идемпотентные операции.\n\nСервер сохраняет результат по ключу — повторный запрос с тем же ключом вернёт прежний результат без повторного выполнения.\n\nКритично для:\n- платежей\n- отправки email',
    answerEn: 'An **idempotency key** is a unique request identifier (UUID) sent in a header that allows non-idempotent operations to be safely retried.\n\nThe server stores the result indexed by the key — a repeated request with the same key returns the original result without re-executing the operation.\n\nCritical for:\n- payments\n- sending emails',
  },
  {
    id: 'net-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['realtime'],
    questionRu: 'В чём разница между WebSocket, SSE и long polling?',
    questionEn: 'What is the difference between WebSocket, SSE, and long polling?',
    answerRu: '**Long polling**: клиент держит запрос открытым, сервер отвечает при появлении данных, клиент сразу повторяет. Простой, но overhead на HTTP.\n\n**SSE** (Server-Sent Events): однонаправленный стрим сервер→клиент по HTTP, автореконнект, `text/event-stream`.\n\n**WebSocket**: двунаправленный, отдельный протокол (`ws://`), минимальный overhead.',
    answerEn: '**Long polling**: the client keeps a request open; the server responds when data is available, and the client immediately repeats. Simple, but has HTTP overhead.\n\n**SSE** (Server-Sent Events): one-directional server-to-client stream over HTTP, auto-reconnect, `text/event-stream`.\n\n**WebSocket**: bidirectional, separate protocol (`ws://`), minimal overhead.',
  },
  {
    id: 'net-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['realtime'],
    questionRu: 'Когда выбрать WebSocket, а когда SSE?',
    questionEn: 'When should you choose WebSocket vs SSE?',
    answerRu: '**SSE** (сервер → клиент):\n- нативный автореконнект\n- работает через HTTP/2\n- проще реализовать\n- для: live-лента, уведомления, прогресс задачи\n\n**WebSocket** (двусторонняя связь):\n- меньше overhead на сообщение\n- для: чат, онлайн-игры, совместное редактирование\n\nSSE проще и достаточен для большинства реалтайм случаев.',
    answerEn: '**SSE** (server → client):\n- native auto-reconnect\n- works over HTTP/2\n- simpler to implement\n- use for: live feeds, notifications, task progress\n\n**WebSocket** (bidirectional):\n- lower per-message overhead\n- use for: chat, online games, collaborative editing\n\nSSE is simpler and sufficient for most real-time use cases.',
  },
  {
    id: 'net-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['realtime'],
    questionRu: 'Как работает WebSocket handshake?',
    questionEn: 'How does the WebSocket handshake work?',
    answerRu: 'WebSocket начинается с HTTP **Upgrade** запроса:\n- `Upgrade: websocket`\n- `Connection: Upgrade`\n- `Sec-WebSocket-Key` (base64 random)\n\nСервер отвечает `101 Switching Protocols` с `Sec-WebSocket-Accept` (хеш ключа).\n\nПосле — TCP соединение остаётся открытым для фреймов. Поддерживает `ws://` и `wss://` (TLS).',
    answerEn: 'WebSocket starts with an HTTP **Upgrade** request:\n- `Upgrade: websocket`\n- `Connection: Upgrade`\n- `Sec-WebSocket-Key` (base64 random)\n\nThe server responds with `101 Switching Protocols` and a `Sec-WebSocket-Accept` (hash of the key).\n\nAfterwards, the TCP connection stays open for frames. Supports `ws://` and `wss://` (TLS).',
  },
  {
    id: 'net-024',
    difficulty: 'EASY',
    order: 24,
    tags: ['realtime'],
    questionRu: 'Что такое polling и в чём его недостатки?',
    questionEn: 'What is polling and what are its drawbacks?',
    answerRu: '**Short polling**: клиент регулярно опрашивает сервер (`setInterval`).\n\n**Недостатки**:\n- постоянные запросы даже без новых данных\n- задержка = интервал поллинга\n- нагрузка на сервер\n\nLong polling лучше, но сложнее. Для большинства реалтайм задач **SSE** или **WebSocket** предпочтительнее polling.',
    answerEn: '**Short polling**: the client regularly queries the server (`setInterval`).\n\n**Drawbacks**:\n- constant requests even when there is no new data\n- latency equals the polling interval\n- increased server load\n\nLong polling is better but more complex. For most real-time tasks, **SSE** or **WebSocket** are preferable to polling.',
  },
];
