import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'net-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['http'],
    questionRu: 'Что такое HTTP и как работает запрос-ответ?',
    questionEn: 'What is HTTP and how does the request-response cycle work?',
    answerRu: 'HTTP — протокол передачи данных клиент-сервер. Клиент отправляет Request (метод, URL, заголовки, тело). Сервер отвечает Response (статус-код, заголовки, тело). Stateless — каждый запрос независим. Поверх TCP/IP. HTTPS = HTTP + TLS шифрование.',
    answerEn: 'HTTP is a client-server data transfer protocol. The client sends a Request (method, URL, headers, body). The server responds with a Response (status code, headers, body). Stateless — each request is independent. Runs on top of TCP/IP. HTTPS = HTTP + TLS encryption.',
  },
  {
    id: 'net-002',
    difficulty: 'EASY',
    order: 2,
    tags: ['http'],
    questionRu: 'Какие HTTP методы существуют и чем отличаются?',
    questionEn: 'What HTTP methods exist and how do they differ?',
    answerRu: 'GET: получить данные, без тела, идемпотентный. POST: создать ресурс, с телом, не идемпотентный. PUT: заменить ресурс целиком, идемпотентный. PATCH: частично обновить. DELETE: удалить, идемпотентный. HEAD: только заголовки без тела. OPTIONS: узнать поддерживаемые методы (используется в CORS preflight).',
    answerEn: 'GET: retrieve data, no body, idempotent. POST: create a resource, has body, not idempotent. PUT: replace a resource entirely, idempotent. PATCH: partially update. DELETE: remove, idempotent. HEAD: headers only, no body. OPTIONS: discover supported methods (used in CORS preflight).',
  },
  {
    id: 'net-003',
    difficulty: 'EASY',
    order: 3,
    tags: ['http'],
    questionRu: 'Что означают группы HTTP статус-кодов?',
    questionEn: 'What do the HTTP status code groups mean?',
    answerRu: '1xx: информационные. 2xx: успех — 200 OK, 201 Created, 204 No Content. 3xx: редиректы — 301 Moved Permanently, 302 Found, 304 Not Modified. 4xx: ошибки клиента — 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 422 Unprocessable Entity. 5xx: ошибки сервера — 500, 503.',
    answerEn: '1xx: informational. 2xx: success — 200 OK, 201 Created, 204 No Content. 3xx: redirects — 301 Moved Permanently, 302 Found, 304 Not Modified. 4xx: client errors — 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 422 Unprocessable Entity. 5xx: server errors — 500, 503.',
  },
  {
    id: 'net-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['http'],
    questionRu: 'В чём разница между HTTP/1.1, HTTP/2 и HTTP/3?',
    questionEn: 'What is the difference between HTTP/1.1, HTTP/2, and HTTP/3?',
    answerRu: 'HTTP/1.1: текстовый, один запрос за раз на соединение, head-of-line blocking. HTTP/2: бинарный, мультиплексирование (много запросов по одному TCP), сжатие заголовков (HPACK), server push. HTTP/3: поверх QUIC (UDP), устраняет TCP head-of-line blocking, быстрое восстановление соединения.',
    answerEn: 'HTTP/1.1: text-based, one request at a time per connection, head-of-line blocking. HTTP/2: binary, multiplexing (many requests over one TCP connection), header compression (HPACK), server push. HTTP/3: runs over QUIC (UDP), eliminates TCP head-of-line blocking, faster connection recovery.',
  },
  {
    id: 'net-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['http'],
    questionRu: 'Что такое идемпотентность и безопасность методов?',
    questionEn: 'What are idempotency and safety of HTTP methods?',
    answerRu: 'Безопасный метод не изменяет состояние сервера: GET, HEAD, OPTIONS. Идемпотентный метод даёт одинаковый результат при повторных вызовах: GET, PUT, DELETE, HEAD. POST — ни безопасный, ни идемпотентный. PATCH — не обязательно идемпотентный. Важно для retry-логики при сетевых ошибках.',
    answerEn: 'A safe method does not modify server state: GET, HEAD, OPTIONS. An idempotent method produces the same result no matter how many times it is called: GET, PUT, DELETE, HEAD. POST is neither safe nor idempotent. PATCH is not necessarily idempotent. This matters for retry logic when network errors occur.',
  },
  {
    id: 'net-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['http'],
    questionRu: 'Что такое CORS и как он работает?',
    questionEn: 'What is CORS and how does it work?',
    answerRu: 'CORS (Cross-Origin Resource Sharing) — механизм разрешения запросов между разными origin. Браузер добавляет Origin заголовок. Сервер отвечает Access-Control-Allow-Origin. Простые запросы (GET/POST с простыми заголовками) — без preflight. Сложные запросы — сначала OPTIONS preflight. CORS — защита браузера, не сервера.',
    answerEn: 'CORS (Cross-Origin Resource Sharing) is a mechanism for permitting cross-origin requests. The browser adds an Origin header. The server responds with Access-Control-Allow-Origin. Simple requests (GET/POST with simple headers) go without a preflight. Complex requests first trigger an OPTIONS preflight. CORS is a browser-side protection, not a server-side one.',
  },
  {
    id: 'net-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['http'],
    questionRu: 'Что такое preflight запрос?',
    questionEn: 'What is a preflight request?',
    answerRu: 'Preflight — автоматический OPTIONS запрос браузера перед сложным CORS запросом. Проверяет разрешение метода и заголовков. Сервер отвечает Access-Control-Allow-Methods, Access-Control-Allow-Headers, Access-Control-Max-Age (кеш preflight). Триггеры: нестандартные методы, заголовки типа Authorization, Content-Type: application/json.',
    answerEn: 'A preflight is an automatic OPTIONS request the browser sends before a complex CORS request. It checks whether the method and headers are allowed. The server responds with Access-Control-Allow-Methods, Access-Control-Allow-Headers, and Access-Control-Max-Age (preflight cache duration). Triggers: non-simple methods, headers such as Authorization, Content-Type: application/json.',
  },
  {
    id: 'net-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['http'],
    questionRu: 'Что такое HTTP кеширование и какие заголовки управляют им?',
    questionEn: 'What is HTTP caching and which headers control it?',
    answerRu: 'Cache-Control: max-age=3600 — кешировать 1 час. no-cache — кешировать, но валидировать с сервером. no-store — не кешировать. immutable — никогда не устареет. ETag — хеш ресурса, клиент отправляет If-None-Match, сервер отвечает 304 если не изменилось. Last-Modified / If-Modified-Since — аналог по дате.',
    answerEn: 'Cache-Control: max-age=3600 — cache for 1 hour. no-cache — cache but revalidate with the server. no-store — do not cache. immutable — will never be stale. ETag — a resource hash; the client sends If-None-Match, the server replies 304 if unchanged. Last-Modified / If-Modified-Since — the date-based equivalent.',
  },
  {
    id: 'net-009',
    difficulty: 'EASY',
    order: 9,
    tags: ['security'],
    questionRu: 'Что такое HTTPS и TLS?',
    questionEn: 'What are HTTPS and TLS?',
    answerRu: 'HTTPS = HTTP + TLS (Transport Layer Security). TLS шифрует трафик, обеспечивает аутентификацию сервера через сертификат и целостность данных. TLS handshake: обмен сертификатами → согласование cipher suite → обмен ключами. Без HTTPS: перехват (MITM), подмена данных, утечка паролей и cookies.',
    answerEn: 'HTTPS = HTTP + TLS (Transport Layer Security). TLS encrypts traffic, authenticates the server via a certificate, and ensures data integrity. TLS handshake: certificate exchange → cipher suite negotiation → key exchange. Without HTTPS: interception (MITM), data tampering, leakage of passwords and cookies.',
  },
  {
    id: 'net-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['security'],
    questionRu: 'Что такое cookies и атрибуты безопасности?',
    questionEn: 'What are cookies and their security attributes?',
    answerRu: 'HttpOnly: недоступен через JS — защита от XSS. Secure: только по HTTPS. SameSite: Strict — только same-site запросы; Lax — разрешает GET cross-site (по умолчанию); None — все запросы, требует Secure. Domain и Path ограничивают область действия. Max-Age/Expires — срок жизни.',
    answerEn: 'HttpOnly: inaccessible via JS — protects against XSS. Secure: HTTPS only. SameSite: Strict — same-site requests only; Lax — allows cross-site GET (default); None — all requests, requires Secure. Domain and Path restrict scope. Max-Age/Expires — lifetime.',
  },
  {
    id: 'net-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['security'],
    questionRu: 'Что такое Content Security Policy (CSP)?',
    questionEn: 'What is Content Security Policy (CSP)?',
    answerRu: "CSP — заголовок Content-Security-Policy ограничивающий источники ресурсов. default-src 'self' — только свой домен. script-src 'self' cdn.example.com — скрипты только отсюда. Блокирует inline-скрипты (защита от XSS). report-uri для логирования нарушений. Мощная защита, требует тщательной настройки.",
    answerEn: "CSP is the Content-Security-Policy header that restricts resource sources. default-src 'self' — own domain only. script-src 'self' cdn.example.com — scripts from these sources only. Blocks inline scripts (protection against XSS). report-uri for logging violations. Powerful protection, but requires careful configuration.",
  },
  {
    id: 'net-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['security'],
    questionRu: 'Какие security заголовки важно выставлять?',
    questionEn: 'Which security headers are important to set?',
    answerRu: 'Strict-Transport-Security (HSTS): только HTTPS, max-age=31536000. X-Content-Type-Options: nosniff — не угадывать MIME. X-Frame-Options: DENY/SAMEORIGIN — защита от clickjacking. Referrer-Policy: контроль Referer заголовка. Permissions-Policy: ограничение браузерных API (camera, geolocation).',
    answerEn: 'Strict-Transport-Security (HSTS): HTTPS only, max-age=31536000. X-Content-Type-Options: nosniff — do not sniff MIME types. X-Frame-Options: DENY/SAMEORIGIN — protection against clickjacking. Referrer-Policy: control over the Referer header. Permissions-Policy: restricts browser APIs (camera, geolocation).',
  },
  {
    id: 'net-013',
    difficulty: 'EASY',
    order: 13,
    tags: ['security'],
    questionRu: 'В чём разница между аутентификацией и авторизацией?',
    questionEn: 'What is the difference between authentication and authorization?',
    answerRu: 'Аутентификация — проверка личности (кто ты?): логин/пароль, OAuth, биометрия. Авторизация — проверка прав (что тебе можно?): роли, разрешения. Порядок: сначала аутентификация, затем авторизация. 401 Unauthorized — не аутентифицирован. 403 Forbidden — аутентифицирован, но нет прав.',
    answerEn: 'Authentication — verifying identity (who are you?): login/password, OAuth, biometrics. Authorization — verifying permissions (what are you allowed to do?): roles, permissions. Order: authentication first, then authorization. 401 Unauthorized — not authenticated. 403 Forbidden — authenticated but lacks permission.',
  },
  {
    id: 'net-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['security'],
    questionRu: 'Что такое JWT и как работает?',
    questionEn: 'What is JWT and how does it work?',
    answerRu: 'JWT (JSON Web Token) — три части base64url: header.payload.signature. Header: алгоритм подписи. Payload: claims (данные, exp, iat). Signature: HMAC/RSA подпись. Сервер не хранит сессии — проверяет подпись. Минусы: нельзя отозвать до истечения, payload виден (не шифруется). Access token короткий, refresh token длинный.',
    answerEn: 'JWT (JSON Web Token) consists of three base64url-encoded parts: header.payload.signature. Header: signing algorithm. Payload: claims (data, exp, iat). Signature: HMAC/RSA signature. The server stores no sessions — it just verifies the signature. Downsides: cannot be revoked before expiry, payload is visible (not encrypted). Access token is short-lived, refresh token is long-lived.',
  },
  {
    id: 'net-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['rest'],
    questionRu: 'Что такое REST и каковы его принципы?',
    questionEn: 'What is REST and what are its principles?',
    answerRu: 'REST (Representational State Transfer) — архитектурный стиль API. Принципы: ресурсы через URL (/users/1), HTTP методы по назначению, stateless (без сессий на сервере), единообразный интерфейс. Уровни зрелости (Richardson): 0 — RPC, 1 — ресурсы, 2 — HTTP методы, 3 — HATEOAS.',
    answerEn: 'REST (Representational State Transfer) is an architectural style for APIs. Principles: resources identified by URL (/users/1), HTTP methods used semantically, stateless (no server-side sessions), uniform interface. Richardson Maturity Model levels: 0 — RPC, 1 — resources, 2 — HTTP methods, 3 — HATEOAS.',
  },
  {
    id: 'net-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['rest'],
    questionRu: 'Что такое GraphQL и чем отличается от REST?',
    questionEn: 'What is GraphQL and how does it differ from REST?',
    answerRu: 'GraphQL — язык запросов для API. Клиент запрашивает точно нужные поля — нет over/under fetching. Один endpoint вместо множества. Строго типизированная схема. Минусы: сложнее кеширование, N+1 проблема, overhead для простых API. REST проще, GraphQL гибче для сложных клиентов.',
    answerEn: 'GraphQL is a query language for APIs. The client requests exactly the fields it needs — no over- or under-fetching. A single endpoint instead of many. Strongly typed schema. Downsides: harder caching, N+1 problem, overhead for simple APIs. REST is simpler; GraphQL is more flexible for complex clients.',
  },
  {
    id: 'net-017',
    difficulty: 'EASY',
    order: 17,
    tags: ['rest'],
    questionRu: 'Что такое over-fetching и under-fetching в REST?',
    questionEn: 'What are over-fetching and under-fetching in REST?',
    answerRu: 'Over-fetching: API возвращает больше данных чем нужно — /users возвращает все поля, нужны только name и email. Under-fetching: нужно несколько запросов для получения связанных данных — /user/1, затем /user/1/posts, затем /posts/1/comments. GraphQL решает обе проблемы одним запросом.',
    answerEn: 'Over-fetching: the API returns more data than needed — /users returns all fields when only name and email are required. Under-fetching: multiple requests are needed to retrieve related data — /user/1, then /user/1/posts, then /posts/1/comments. GraphQL solves both problems with a single request.',
  },
  {
    id: 'net-018',
    difficulty: 'HARD',
    order: 18,
    tags: ['rest'],
    questionRu: 'Что такое N+1 проблема в GraphQL?',
    questionEn: 'What is the N+1 problem in GraphQL?',
    answerRu: 'N+1: запрос списка N объектов с вложенными данными вызывает N+1 запросов к БД — 1 для списка + N для каждого элемента. Решение: DataLoader — батчинг и кеширование запросов в рамках одного GraphQL запроса. Собирает все ID, делает один запрос к БД, раздаёт результаты.',
    answerEn: 'N+1: fetching a list of N objects with nested data triggers N+1 database queries — 1 for the list plus N for each item. Solution: DataLoader — batches and caches queries within a single GraphQL request. It collects all IDs, makes one database query, and distributes the results.',
  },
  {
    id: 'net-019',
    difficulty: 'HARD',
    order: 19,
    tags: ['rest'],
    questionRu: 'Что такое REST vs RPC (gRPC)?',
    questionEn: 'What is REST vs RPC (gRPC)?',
    answerRu: 'REST: ресурсо-ориентированный, HTTP/1.1, JSON, самодокументируемый через URL. gRPC: функционально-ориентированный (вызов методов), HTTP/2, Protocol Buffers (бинарный), строгая типизация через .proto файлы, быстрее REST. gRPC для внутренних микросервисов, REST для публичных API.',
    answerEn: 'REST: resource-oriented, HTTP/1.1, JSON, self-documenting via URL. gRPC: function-oriented (method calls), HTTP/2, Protocol Buffers (binary), strict typing via .proto files, faster than REST. gRPC is preferred for internal microservices; REST is preferred for public APIs.',
  },
  {
    id: 'net-020',
    difficulty: 'HARD',
    order: 20,
    tags: ['rest'],
    questionRu: 'Что такое idempotency key?',
    questionEn: 'What is an idempotency key?',
    answerRu: 'Idempotency key — уникальный ключ запроса (UUID) в заголовке, позволяющий безопасно повторять не идемпотентные операции. Сервер сохраняет результат по ключу — повторный запрос с тем же ключом вернёт прежний результат без повторного выполнения. Критично для: платежей, отправки email.',
    answerEn: 'An idempotency key is a unique request identifier (UUID) sent in a header that allows non-idempotent operations to be safely retried. The server stores the result indexed by the key — a repeated request with the same key returns the original result without re-executing the operation. Critical for: payments, sending emails.',
  },
  {
    id: 'net-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['realtime'],
    questionRu: 'В чём разница между WebSocket, SSE и long polling?',
    questionEn: 'What is the difference between WebSocket, SSE, and long polling?',
    answerRu: 'Long polling: клиент держит запрос открытым, сервер отвечает при появлении данных, клиент сразу повторяет. Простой, но overhead на HTTP. SSE (Server-Sent Events): однонаправленный стрим сервер→клиент по HTTP, автореконнект, text/event-stream. WebSocket: двунаправленный, отдельный протокол (ws://), минимальный overhead.',
    answerEn: 'Long polling: the client keeps a request open; the server responds when data is available, and the client immediately repeats. Simple, but has HTTP overhead. SSE (Server-Sent Events): one-directional server-to-client stream over HTTP, auto-reconnect, text/event-stream. WebSocket: bidirectional, separate protocol (ws://), minimal overhead.',
  },
  {
    id: 'net-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['realtime'],
    questionRu: 'Когда выбрать WebSocket, а когда SSE?',
    questionEn: 'When should you choose WebSocket vs SSE?',
    answerRu: 'SSE: только сервер → клиент, нативный автореконнект, работает через HTTP/2, проще реализовать. Для: live-лента, уведомления, прогресс задачи. WebSocket: двусторонняя связь, меньше overhead на сообщение. Для: чат, онлайн-игры, совместное редактирование. SSE проще и достаточен для большинства реалтайм случаев.',
    answerEn: 'SSE: server-to-client only, native auto-reconnect, works over HTTP/2, simpler to implement. Use for: live feeds, notifications, task progress. WebSocket: bidirectional communication, lower per-message overhead. Use for: chat, online games, collaborative editing. SSE is simpler and sufficient for most real-time use cases.',
  },
  {
    id: 'net-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['realtime'],
    questionRu: 'Как работает WebSocket handshake?',
    questionEn: 'How does the WebSocket handshake work?',
    answerRu: 'WebSocket начинается с HTTP Upgrade запроса: Upgrade: websocket, Connection: Upgrade, Sec-WebSocket-Key (base64 random). Сервер отвечает 101 Switching Protocols с Sec-WebSocket-Accept (хеш ключа). После — TCP соединение остаётся открытым для фреймов. Поддерживает ws:// и wss:// (TLS).',
    answerEn: 'WebSocket starts with an HTTP Upgrade request: Upgrade: websocket, Connection: Upgrade, Sec-WebSocket-Key (base64 random). The server responds with 101 Switching Protocols and a Sec-WebSocket-Accept (hash of the key). Afterwards, the TCP connection stays open for frames. Supports ws:// and wss:// (TLS).',
  },
  {
    id: 'net-024',
    difficulty: 'EASY',
    order: 24,
    tags: ['realtime'],
    questionRu: 'Что такое polling и в чём его недостатки?',
    questionEn: 'What is polling and what are its drawbacks?',
    answerRu: 'Short polling: клиент регулярно опрашивает сервер (setInterval). Недостатки: постоянные запросы даже без новых данных, задержка = интервал поллинга, нагрузка на сервер. Long polling лучше но сложнее. Для большинства реалтайм задач SSE или WebSocket предпочтительнее polling.',
    answerEn: 'Short polling: the client regularly queries the server (setInterval). Drawbacks: constant requests even when there is no new data, latency equals the polling interval, increased server load. Long polling is better but more complex. For most real-time tasks, SSE or WebSocket are preferable to polling.',
  },
];
