import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'net-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['http'],
    questionRu: 'Что такое HTTP и как работает запрос-ответ?',
    questionEn: 'Что такое HTTP и как работает запрос-ответ?',
    answerRu: 'HTTP — протокол передачи данных клиент-сервер. Клиент отправляет Request (метод, URL, заголовки, тело). Сервер отвечает Response (статус-код, заголовки, тело). Stateless — каждый запрос независим. Поверх TCP/IP. HTTPS = HTTP + TLS шифрование.',
    answerEn: 'HTTP — протокол передачи данных клиент-сервер. Клиент отправляет Request (метод, URL, заголовки, тело). Сервер отвечает Response (статус-код, заголовки, тело). Stateless — каждый запрос независим. Поверх TCP/IP. HTTPS = HTTP + TLS шифрование.',
  },
  {
    id: 'net-002',
    difficulty: 'EASY',
    order: 2,
    tags: ['http'],
    questionRu: 'Какие HTTP методы существуют и чем отличаются?',
    questionEn: 'Какие HTTP методы существуют и чем отличаются?',
    answerRu: 'GET: получить данные, без тела, идемпотентный. POST: создать ресурс, с телом, не идемпотентный. PUT: заменить ресурс целиком, идемпотентный. PATCH: частично обновить. DELETE: удалить, идемпотентный. HEAD: только заголовки без тела. OPTIONS: узнать поддерживаемые методы (используется в CORS preflight).',
    answerEn: 'GET: получить данные, без тела, идемпотентный. POST: создать ресурс, с телом, не идемпотентный. PUT: заменить ресурс целиком, идемпотентный. PATCH: частично обновить. DELETE: удалить, идемпотентный. HEAD: только заголовки без тела. OPTIONS: узнать поддерживаемые методы (используется в CORS preflight).',
  },
  {
    id: 'net-003',
    difficulty: 'EASY',
    order: 3,
    tags: ['http'],
    questionRu: 'Что означают группы HTTP статус-кодов?',
    questionEn: 'Что означают группы HTTP статус-кодов?',
    answerRu: '1xx: информационные. 2xx: успех — 200 OK, 201 Created, 204 No Content. 3xx: редиректы — 301 Moved Permanently, 302 Found, 304 Not Modified. 4xx: ошибки клиента — 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 422 Unprocessable Entity. 5xx: ошибки сервера — 500, 503.',
    answerEn: '1xx: информационные. 2xx: успех — 200 OK, 201 Created, 204 No Content. 3xx: редиректы — 301 Moved Permanently, 302 Found, 304 Not Modified. 4xx: ошибки клиента — 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 422 Unprocessable Entity. 5xx: ошибки сервера — 500, 503.',
  },
  {
    id: 'net-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['http'],
    questionRu: 'В чём разница между HTTP/1.1, HTTP/2 и HTTP/3?',
    questionEn: 'В чём разница между HTTP/1.1, HTTP/2 и HTTP/3?',
    answerRu: 'HTTP/1.1: текстовый, один запрос за раз на соединение, head-of-line blocking. HTTP/2: бинарный, мультиплексирование (много запросов по одному TCP), сжатие заголовков (HPACK), server push. HTTP/3: поверх QUIC (UDP), устраняет TCP head-of-line blocking, быстрое восстановление соединения.',
    answerEn: 'HTTP/1.1: текстовый, один запрос за раз на соединение, head-of-line blocking. HTTP/2: бинарный, мультиплексирование (много запросов по одному TCP), сжатие заголовков (HPACK), server push. HTTP/3: поверх QUIC (UDP), устраняет TCP head-of-line blocking, быстрое восстановление соединения.',
  },
  {
    id: 'net-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['http'],
    questionRu: 'Что такое идемпотентность и безопасность методов?',
    questionEn: 'Что такое идемпотентность и безопасность методов?',
    answerRu: 'Безопасный метод не изменяет состояние сервера: GET, HEAD, OPTIONS. Идемпотентный метод даёт одинаковый результат при повторных вызовах: GET, PUT, DELETE, HEAD. POST — ни безопасный, ни идемпотентный. PATCH — не обязательно идемпотентный. Важно для retry-логики при сетевых ошибках.',
    answerEn: 'Безопасный метод не изменяет состояние сервера: GET, HEAD, OPTIONS. Идемпотентный метод даёт одинаковый результат при повторных вызовах: GET, PUT, DELETE, HEAD. POST — ни безопасный, ни идемпотентный. PATCH — не обязательно идемпотентный. Важно для retry-логики при сетевых ошибках.',
  },
  {
    id: 'net-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['http'],
    questionRu: 'Что такое CORS и как он работает?',
    questionEn: 'Что такое CORS и как он работает?',
    answerRu: 'CORS (Cross-Origin Resource Sharing) — механизм разрешения запросов между разными origin. Браузер добавляет Origin заголовок. Сервер отвечает Access-Control-Allow-Origin. Простые запросы (GET/POST с простыми заголовками) — без preflight. Сложные запросы — сначала OPTIONS preflight. CORS — защита браузера, не сервера.',
    answerEn: 'CORS (Cross-Origin Resource Sharing) — механизм разрешения запросов между разными origin. Браузер добавляет Origin заголовок. Сервер отвечает Access-Control-Allow-Origin. Простые запросы (GET/POST с простыми заголовками) — без preflight. Сложные запросы — сначала OPTIONS preflight. CORS — защита браузера, не сервера.',
  },
  {
    id: 'net-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['http'],
    questionRu: 'Что такое preflight запрос?',
    questionEn: 'Что такое preflight запрос?',
    answerRu: 'Preflight — автоматический OPTIONS запрос браузера перед сложным CORS запросом. Проверяет разрешение метода и заголовков. Сервер отвечает Access-Control-Allow-Methods, Access-Control-Allow-Headers, Access-Control-Max-Age (кеш preflight). Триггеры: нестандартные методы, заголовки типа Authorization, Content-Type: application/json.',
    answerEn: 'Preflight — автоматический OPTIONS запрос браузера перед сложным CORS запросом. Проверяет разрешение метода и заголовков. Сервер отвечает Access-Control-Allow-Methods, Access-Control-Allow-Headers, Access-Control-Max-Age (кеш preflight). Триггеры: нестандартные методы, заголовки типа Authorization, Content-Type: application/json.',
  },
  {
    id: 'net-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['http'],
    questionRu: 'Что такое HTTP кеширование и какие заголовки управляют им?',
    questionEn: 'Что такое HTTP кеширование и какие заголовки управляют им?',
    answerRu: 'Cache-Control: max-age=3600 — кешировать 1 час. no-cache — кешировать, но валидировать с сервером. no-store — не кешировать. immutable — никогда не устареет. ETag — хеш ресурса, клиент отправляет If-None-Match, сервер отвечает 304 если не изменилось. Last-Modified / If-Modified-Since — аналог по дате.',
    answerEn: 'Cache-Control: max-age=3600 — кешировать 1 час. no-cache — кешировать, но валидировать с сервером. no-store — не кешировать. immutable — никогда не устареет. ETag — хеш ресурса, клиент отправляет If-None-Match, сервер отвечает 304 если не изменилось. Last-Modified / If-Modified-Since — аналог по дате.',
  },
  {
    id: 'net-009',
    difficulty: 'EASY',
    order: 9,
    tags: ['security'],
    questionRu: 'Что такое HTTPS и TLS?',
    questionEn: 'Что такое HTTPS и TLS?',
    answerRu: 'HTTPS = HTTP + TLS (Transport Layer Security). TLS шифрует трафик, обеспечивает аутентификацию сервера через сертификат и целостность данных. TLS handshake: обмен сертификатами → согласование cipher suite → обмен ключами. Без HTTPS: перехват (MITM), подмена данных, утечка паролей и cookies.',
    answerEn: 'HTTPS = HTTP + TLS (Transport Layer Security). TLS шифрует трафик, обеспечивает аутентификацию сервера через сертификат и целостность данных. TLS handshake: обмен сертификатами → согласование cipher suite → обмен ключами. Без HTTPS: перехват (MITM), подмена данных, утечка паролей и cookies.',
  },
  {
    id: 'net-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['security'],
    questionRu: 'Что такое cookies и атрибуты безопасности?',
    questionEn: 'Что такое cookies и атрибуты безопасности?',
    answerRu: 'HttpOnly: недоступен через JS — защита от XSS. Secure: только по HTTPS. SameSite: Strict — только same-site запросы; Lax — разрешает GET cross-site (по умолчанию); None — все запросы, требует Secure. Domain и Path ограничивают область действия. Max-Age/Expires — срок жизни.',
    answerEn: 'HttpOnly: недоступен через JS — защита от XSS. Secure: только по HTTPS. SameSite: Strict — только same-site запросы; Lax — разрешает GET cross-site (по умолчанию); None — все запросы, требует Secure. Domain и Path ограничивают область действия. Max-Age/Expires — срок жизни.',
  },
  {
    id: 'net-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['security'],
    questionRu: 'Что такое Content Security Policy (CSP)?',
    questionEn: 'Что такое Content Security Policy (CSP)?',
    answerRu: "CSP — заголовок Content-Security-Policy ограничивающий источники ресурсов. default-src 'self' — только свой домен. script-src 'self' cdn.example.com — скрипты только отсюда. Блокирует inline-скрипты (защита от XSS). report-uri для логирования нарушений. Мощная защита, требует тщательной настройки.",
    answerEn: "CSP — заголовок Content-Security-Policy ограничивающий источники ресурсов. default-src 'self' — только свой домен. script-src 'self' cdn.example.com — скрипты только отсюда. Блокирует inline-скрипты (защита от XSS). report-uri для логирования нарушений. Мощная защита, требует тщательной настройки.",
  },
  {
    id: 'net-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['security'],
    questionRu: 'Какие security заголовки важно выставлять?',
    questionEn: 'Какие security заголовки важно выставлять?',
    answerRu: 'Strict-Transport-Security (HSTS): только HTTPS, max-age=31536000. X-Content-Type-Options: nosniff — не угадывать MIME. X-Frame-Options: DENY/SAMEORIGIN — защита от clickjacking. Referrer-Policy: контроль Referer заголовка. Permissions-Policy: ограничение браузерных API (camera, geolocation).',
    answerEn: 'Strict-Transport-Security (HSTS): только HTTPS, max-age=31536000. X-Content-Type-Options: nosniff — не угадывать MIME. X-Frame-Options: DENY/SAMEORIGIN — защита от clickjacking. Referrer-Policy: контроль Referer заголовка. Permissions-Policy: ограничение браузерных API (camera, geolocation).',
  },
  {
    id: 'net-013',
    difficulty: 'EASY',
    order: 13,
    tags: ['security'],
    questionRu: 'В чём разница между аутентификацией и авторизацией?',
    questionEn: 'В чём разница между аутентификацией и авторизацией?',
    answerRu: 'Аутентификация — проверка личности (кто ты?): логин/пароль, OAuth, биометрия. Авторизация — проверка прав (что тебе можно?): роли, разрешения. Порядок: сначала аутентификация, затем авторизация. 401 Unauthorized — не аутентифицирован. 403 Forbidden — аутентифицирован, но нет прав.',
    answerEn: 'Аутентификация — проверка личности (кто ты?): логин/пароль, OAuth, биометрия. Авторизация — проверка прав (что тебе можно?): роли, разрешения. Порядок: сначала аутентификация, затем авторизация. 401 Unauthorized — не аутентифицирован. 403 Forbidden — аутентифицирован, но нет прав.',
  },
  {
    id: 'net-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['security'],
    questionRu: 'Что такое JWT и как работает?',
    questionEn: 'Что такое JWT и как работает?',
    answerRu: 'JWT (JSON Web Token) — три части base64url: header.payload.signature. Header: алгоритм подписи. Payload: claims (данные, exp, iat). Signature: HMAC/RSA подпись. Сервер не хранит сессии — проверяет подпись. Минусы: нельзя отозвать до истечения, payload виден (не шифруется). Access token короткий, refresh token длинный.',
    answerEn: 'JWT (JSON Web Token) — три части base64url: header.payload.signature. Header: алгоритм подписи. Payload: claims (данные, exp, iat). Signature: HMAC/RSA подпись. Сервер не хранит сессии — проверяет подпись. Минусы: нельзя отозвать до истечения, payload виден (не шифруется). Access token короткий, refresh token длинный.',
  },
  {
    id: 'net-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['rest'],
    questionRu: 'Что такое REST и каковы его принципы?',
    questionEn: 'Что такое REST и каковы его принципы?',
    answerRu: 'REST (Representational State Transfer) — архитектурный стиль API. Принципы: ресурсы через URL (/users/1), HTTP методы по назначению, stateless (без сессий на сервере), единообразный интерфейс. Уровни зрелости (Richardson): 0 — RPC, 1 — ресурсы, 2 — HTTP методы, 3 — HATEOAS.',
    answerEn: 'REST (Representational State Transfer) — архитектурный стиль API. Принципы: ресурсы через URL (/users/1), HTTP методы по назначению, stateless (без сессий на сервере), единообразный интерфейс. Уровни зрелости (Richardson): 0 — RPC, 1 — ресурсы, 2 — HTTP методы, 3 — HATEOAS.',
  },
  {
    id: 'net-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['rest'],
    questionRu: 'Что такое GraphQL и чем отличается от REST?',
    questionEn: 'Что такое GraphQL и чем отличается от REST?',
    answerRu: 'GraphQL — язык запросов для API. Клиент запрашивает точно нужные поля — нет over/under fetching. Один endpoint вместо множества. Строго типизированная схема. Минусы: сложнее кеширование, N+1 проблема, overhead для простых API. REST проще, GraphQL гибче для сложных клиентов.',
    answerEn: 'GraphQL — язык запросов для API. Клиент запрашивает точно нужные поля — нет over/under fetching. Один endpoint вместо множества. Строго типизированная схема. Минусы: сложнее кеширование, N+1 проблема, overhead для простых API. REST проще, GraphQL гибче для сложных клиентов.',
  },
  {
    id: 'net-017',
    difficulty: 'EASY',
    order: 17,
    tags: ['rest'],
    questionRu: 'Что такое over-fetching и under-fetching в REST?',
    questionEn: 'Что такое over-fetching и under-fetching в REST?',
    answerRu: 'Over-fetching: API возвращает больше данных чем нужно — /users возвращает все поля, нужны только name и email. Under-fetching: нужно несколько запросов для получения связанных данных — /user/1, затем /user/1/posts, затем /posts/1/comments. GraphQL решает обе проблемы одним запросом.',
    answerEn: 'Over-fetching: API возвращает больше данных чем нужно — /users возвращает все поля, нужны только name и email. Under-fetching: нужно несколько запросов для получения связанных данных — /user/1, затем /user/1/posts, затем /posts/1/comments. GraphQL решает обе проблемы одним запросом.',
  },
  {
    id: 'net-018',
    difficulty: 'HARD',
    order: 18,
    tags: ['rest'],
    questionRu: 'Что такое N+1 проблема в GraphQL?',
    questionEn: 'Что такое N+1 проблема в GraphQL?',
    answerRu: 'N+1: запрос списка N объектов с вложенными данными вызывает N+1 запросов к БД — 1 для списка + N для каждого элемента. Решение: DataLoader — батчинг и кеширование запросов в рамках одного GraphQL запроса. Собирает все ID, делает один запрос к БД, раздаёт результаты.',
    answerEn: 'N+1: запрос списка N объектов с вложенными данными вызывает N+1 запросов к БД — 1 для списка + N для каждого элемента. Решение: DataLoader — батчинг и кеширование запросов в рамках одного GraphQL запроса. Собирает все ID, делает один запрос к БД, раздаёт результаты.',
  },
  {
    id: 'net-019',
    difficulty: 'HARD',
    order: 19,
    tags: ['rest'],
    questionRu: 'Что такое REST vs RPC (gRPC)?',
    questionEn: 'Что такое REST vs RPC (gRPC)?',
    answerRu: 'REST: ресурсо-ориентированный, HTTP/1.1, JSON, самодокументируемый через URL. gRPC: функционально-ориентированный (вызов методов), HTTP/2, Protocol Buffers (бинарный), строгая типизация через .proto файлы, быстрее REST. gRPC для внутренних микросервисов, REST для публичных API.',
    answerEn: 'REST: ресурсо-ориентированный, HTTP/1.1, JSON, самодокументируемый через URL. gRPC: функционально-ориентированный (вызов методов), HTTP/2, Protocol Buffers (бинарный), строгая типизация через .proto файлы, быстрее REST. gRPC для внутренних микросервисов, REST для публичных API.',
  },
  {
    id: 'net-020',
    difficulty: 'HARD',
    order: 20,
    tags: ['rest'],
    questionRu: 'Что такое idempotency key?',
    questionEn: 'Что такое idempotency key?',
    answerRu: 'Idempotency key — уникальный ключ запроса (UUID) в заголовке, позволяющий безопасно повторять не идемпотентные операции. Сервер сохраняет результат по ключу — повторный запрос с тем же ключом вернёт прежний результат без повторного выполнения. Критично для: платежей, отправки email.',
    answerEn: 'Idempotency key — уникальный ключ запроса (UUID) в заголовке, позволяющий безопасно повторять не идемпотентные операции. Сервер сохраняет результат по ключу — повторный запрос с тем же ключом вернёт прежний результат без повторного выполнения. Критично для: платежей, отправки email.',
  },
  {
    id: 'net-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['realtime'],
    questionRu: 'В чём разница между WebSocket, SSE и long polling?',
    questionEn: 'В чём разница между WebSocket, SSE и long polling?',
    answerRu: 'Long polling: клиент держит запрос открытым, сервер отвечает при появлении данных, клиент сразу повторяет. Простой, но overhead на HTTP. SSE (Server-Sent Events): однонаправленный стрим сервер→клиент по HTTP, автореконнект, text/event-stream. WebSocket: двунаправленный, отдельный протокол (ws://), минимальный overhead.',
    answerEn: 'Long polling: клиент держит запрос открытым, сервер отвечает при появлении данных, клиент сразу повторяет. Простой, но overhead на HTTP. SSE (Server-Sent Events): однонаправленный стрим сервер→клиент по HTTP, автореконнект, text/event-stream. WebSocket: двунаправленный, отдельный протокол (ws://), минимальный overhead.',
  },
  {
    id: 'net-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['realtime'],
    questionRu: 'Когда выбрать WebSocket, а когда SSE?',
    questionEn: 'Когда выбрать WebSocket, а когда SSE?',
    answerRu: 'SSE: только сервер → клиент, нативный автореконнект, работает через HTTP/2, проще реализовать. Для: live-лента, уведомления, прогресс задачи. WebSocket: двусторонняя связь, меньше overhead на сообщение. Для: чат, онлайн-игры, совместное редактирование. SSE проще и достаточен для большинства реалтайм случаев.',
    answerEn: 'SSE: только сервер → клиент, нативный автореконнект, работает через HTTP/2, проще реализовать. Для: live-лента, уведомления, прогресс задачи. WebSocket: двусторонняя связь, меньше overhead на сообщение. Для: чат, онлайн-игры, совместное редактирование. SSE проще и достаточен для большинства реалтайм случаев.',
  },
  {
    id: 'net-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['realtime'],
    questionRu: 'Как работает WebSocket handshake?',
    questionEn: 'Как работает WebSocket handshake?',
    answerRu: 'WebSocket начинается с HTTP Upgrade запроса: Upgrade: websocket, Connection: Upgrade, Sec-WebSocket-Key (base64 random). Сервер отвечает 101 Switching Protocols с Sec-WebSocket-Accept (хеш ключа). После — TCP соединение остаётся открытым для фреймов. Поддерживает ws:// и wss:// (TLS).',
    answerEn: 'WebSocket начинается с HTTP Upgrade запроса: Upgrade: websocket, Connection: Upgrade, Sec-WebSocket-Key (base64 random). Сервер отвечает 101 Switching Protocols с Sec-WebSocket-Accept (хеш ключа). После — TCP соединение остаётся открытым для фреймов. Поддерживает ws:// и wss:// (TLS).',
  },
  {
    id: 'net-024',
    difficulty: 'EASY',
    order: 24,
    tags: ['realtime'],
    questionRu: 'Что такое polling и в чём его недостатки?',
    questionEn: 'Что такое polling и в чём его недостатки?',
    answerRu: 'Short polling: клиент регулярно опрашивает сервер (setInterval). Недостатки: постоянные запросы даже без новых данных, задержка = интервал поллинга, нагрузка на сервер. Long polling лучше но сложнее. Для большинства реалтайм задач SSE или WebSocket предпочтительнее polling.',
    answerEn: 'Short polling: клиент регулярно опрашивает сервер (setInterval). Недостатки: постоянные запросы даже без новых данных, задержка = интервал поллинга, нагрузка на сервер. Long polling лучше но сложнее. Для большинства реалтайм задач SSE или WebSocket предпочтительнее polling.',
  },
];
