import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'nextjs-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['routing'],
    questionRu: 'В чём разница между Pages Router и App Router?',
    questionEn: 'What is the difference between Pages Router and App Router?',
    answerRu: '**Pages Router** (до Next 13): файлы в `/pages`, `getServerSideProps`/`getStaticProps` для data fetching, все компоненты клиентские по умолчанию.\n\n**App Router** (Next 13+): файлы в `/app`, React Server Components по умолчанию, `async`/`await` для data fetching, `layout`, `loading`, `error` как специальные файлы.',
    answerEn: '**Pages Router** (before Next 13): files in `/pages`, `getServerSideProps`/`getStaticProps` for data fetching, all components are Client Components by default.\n\n**App Router** (Next 13+): files in `/app`, React Server Components by default, `async`/`await` for data fetching, `layout`, `loading`, and `error` as special files.',
  },
  {
    id: 'nextjs-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['routing'],
    questionRu: 'Как работает файловая система роутинга в App Router?',
    questionEn: 'How does the file-system routing work in App Router?',
    answerRu: 'Каждая папка в `/app` — сегмент маршрута. `page.tsx` делает маршрут публичным.\n\n**Специальные файлы:**\n- `layout.tsx` — общий UI для сегмента\n- `loading.tsx` — Suspense fallback\n- `error.tsx` — Error Boundary\n- `not-found.tsx`\n\n**Динамические сегменты:** `[id]`, `[...slug]`, `[[...slug]]` (опциональный catch-all).',
    answerEn: 'Each folder in `/app` is a route segment. `page.tsx` makes the route publicly accessible.\n\n**Special files:**\n- `layout.tsx` — shared UI for the segment\n- `loading.tsx` — Suspense fallback\n- `error.tsx` — Error Boundary\n- `not-found.tsx`\n\n**Dynamic segments:** `[id]`, `[...slug]`, `[[...slug]]` (optional catch-all).',
  },
  {
    id: 'nextjs-003',
    difficulty: 'HARD',
    order: 3,
    tags: ['routing'],
    questionRu: 'Что такое Route Groups и Parallel Routes?',
    questionEn: 'What are Route Groups and Parallel Routes?',
    answerRu: '**Route Groups:** папки в скобках `(auth)` группируют маршруты без влияния на URL — удобно для разных layouts.\n\n**Parallel Routes:** `@folder` — рендерить несколько страниц одновременно в одном layout (dashboard с `@analytics` и `@team`).\n\n**Intercepting Routes:** `(..)` перехватывают маршрут для модалок.',
    answerEn: '**Route Groups:** folders in parentheses `(auth)` group routes without affecting the URL — useful for different layouts.\n\n**Parallel Routes:** `@folder` — render multiple pages simultaneously in a single layout (e.g. a dashboard with `@analytics` and `@team`).\n\n**Intercepting Routes:** `(..)` intercept a route for use in modals.',
  },
  {
    id: 'nextjs-004',
    difficulty: 'EASY',
    order: 4,
    tags: ['routing'],
    questionRu: 'Как работает навигация в Next.js?',
    questionEn: 'How does navigation work in Next.js?',
    answerRu: '`<Link href="/about">` — клиентская навигация без перезагрузки, автоматический prefetch в viewport.\n\n`useRouter()` — программная навигация: `router.push()`, `router.replace()`, `router.back()`.\n\n`usePathname()`, `useSearchParams()` — чтение текущего URL.\n\n`redirect()` — серверный редирект.',
    answerEn: '`<Link href="/about">` — client-side navigation without a full page reload, automatically prefetches links in the viewport.\n\n`useRouter()` — programmatic navigation: `router.push()`, `router.replace()`, `router.back()`.\n\n`usePathname()`, `useSearchParams()` — read the current URL.\n\n`redirect()` — server-side redirect.',
  },
  {
    id: 'nextjs-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['routing'],
    questionRu: 'Что такое Middleware в Next.js?',
    questionEn: 'What is Middleware in Next.js?',
    answerRu: '**Middleware** (`middleware.ts` в корне) — код, выполняющийся до обработки запроса на **Edge Runtime**.\n\n**Применения:**\n- авторизация и редирект\n- A/B тесты\n- локализация\n- добавление заголовков\n\nВозвращает `NextResponse`. Конфиг `matcher` ограничивает маршруты.\n\n**Важно:** Edge Runtime ограничен — нет Node.js API.',
    answerEn: '**Middleware** (`middleware.ts` at the root) is code that runs before a request is processed, on the **Edge Runtime**.\n\n**Use cases:**\n- auth and redirects\n- A/B testing\n- localization\n- adding headers\n\nReturns `NextResponse`. The `matcher` config limits which routes it applies to.\n\n**Important:** Edge Runtime is restricted — no Node.js API.',
  },
  {
    id: 'nextjs-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['routing'],
    questionRu: 'Что такое Route Handlers (API Routes)?',
    questionEn: 'What are Route Handlers (API Routes)?',
    answerRu: '**Route Handlers** — файл `route.ts` в `/app` экспортирует функции `GET`, `POST`, `PUT`, `DELETE`.\n\nЗаменяют `pages/api` в App Router. Получают `Request`, возвращают `Response`.\n\nПоддерживают **Edge** и **Node.js** runtime. Поддерживают revalidation, streaming, работу с cookies и headers.',
    answerEn: '**Route Handlers** — a `route.ts` file in `/app` exports `GET`, `POST`, `PUT`, `DELETE` functions.\n\nThey replace `pages/api` in the App Router. They receive a `Request` and return a `Response`.\n\nSupport both **Edge** and **Node.js** runtimes. Support revalidation, streaming, and working with cookies and headers.',
  },
  {
    id: 'nextjs-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['routing'],
    questionRu: 'Что такое Server Actions?',
    questionEn: 'What are Server Actions?',
    answerRu: "**Server Actions** — `async` функции с директивой `'use server'`, выполняющиеся на сервере. Вызываются напрямую из клиентского кода как обычные функции.\n\n**Используются для:**\n- отправки форм\n- мутации данных\n- вызова БД\n\nАвтоматически создают API endpoint. Интегрированы с `revalidatePath`/`revalidateTag`.",
    answerEn: "**Server Actions** are `async` functions marked with the `'use server'` directive that execute on the server. They are called directly from client-side code like regular functions.\n\n**Used for:**\n- form submissions\n- data mutations\n- database calls\n\nThey automatically create an API endpoint and integrate with `revalidatePath`/`revalidateTag`.",
  },
  {
    id: 'nextjs-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['rendering'],
    questionRu: 'Что такое SSR, SSG и ISR — в чём разница?',
    questionEn: 'What are SSR, SSG, and ISR — what is the difference?',
    answerRu: '**SSR** (Server-Side Rendering): HTML генерируется на сервере при каждом запросе — актуальные данные, медленнее.\n\n**SSG** (Static Site Generation): HTML генерируется при сборке — быстро, но данные устаревают.\n\n**ISR** (Incremental Static Regeneration): SSG с фоновой регенерацией через `revalidate` — баланс скорости и свежести.',
    answerEn: '**SSR** (Server-Side Rendering): HTML is generated on the server on every request — data is always fresh, but slower.\n\n**SSG** (Static Site Generation): HTML is generated at build time — fast, but data can become stale.\n\n**ISR** (Incremental Static Regeneration): SSG with background regeneration via `revalidate` — a balance of speed and freshness.',
  },
  {
    id: 'nextjs-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['rendering'],
    questionRu: 'Что такое React Server Components (RSC)?',
    questionEn: 'What are React Server Components (RSC)?',
    answerRu: '**RSC** — компоненты, рендерящиеся только на сервере.\n\n**Преимущества:**\n- прямой доступ к БД и файловой системе\n- нет JS в бандле клиента\n- могут быть `async`\n\n**Ограничения:**\n- нет `useState`/`useEffect`\n- нет браузерных API\n- нет обработчиков событий\n\nВ App Router все компоненты — Server Components по умолчанию.',
    answerEn: '**RSC** are components that render exclusively on the server.\n\n**Advantages:**\n- direct access to databases and filesystem\n- no JS in the client bundle\n- can be `async`\n\n**Limitations:**\n- no `useState`/`useEffect`\n- no browser APIs\n- no event handlers\n\nIn the App Router, all components are Server Components by default.',
  },
  {
    id: 'nextjs-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['rendering'],
    questionRu: "Когда использовать 'use client'?",
    questionEn: "When should you use 'use client'?",
    answerRu: "`'use client'` помечает компонент и его дочерние как **Client Components**.\n\n**Нужна когда используются:**\n- хуки (`useState`, `useEffect`)\n- обработчики событий\n- браузерные API\n\n**Граница:** Server Components могут передавать props клиентским, но не наоборот. Client Components не могут напрямую рендерить `async` Server Components.",
    answerEn: "`'use client'` marks a component and its children as **Client Components**.\n\n**Required when using:**\n- hooks (`useState`, `useEffect`)\n- event handlers\n- browser APIs\n\n**The boundary:** Server Components can pass props to Client Components, but not vice versa. Client Components cannot directly render `async` Server Components.",
  },
  {
    id: 'nextjs-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['rendering'],
    questionRu: 'Как работает Streaming в Next.js?',
    questionEn: 'How does Streaming work in Next.js?',
    answerRu: '**Streaming** — постепенная отправка HTML с сервера по мере готовности частей страницы.\n\nРеализуется через `Suspense`: обёрнутые части стримятся, остальное отправляется сразу. `loading.tsx` автоматически создаёт Suspense boundary для сегмента.\n\nУлучшает **TTFB** и воспринимаемую скорость загрузки.',
    answerEn: '**Streaming** progressively sends HTML from the server as parts of the page become ready.\n\nImplemented via `Suspense`: wrapped parts are streamed while the rest is sent immediately. `loading.tsx` automatically creates a Suspense boundary for the segment.\n\nImproves **TTFB** and perceived load speed.',
  },
  {
    id: 'nextjs-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['rendering'],
    questionRu: 'Что такое generateStaticParams?',
    questionEn: 'What is generateStaticParams?',
    answerRu: "`generateStaticParams` заменяет `getStaticPaths` в App Router. Возвращает массив параметров для статической генерации динамических маршрутов:\n\n```ts\nexport async function generateStaticParams() {\n  return [{ id: '1' }, { id: '2' }];\n}\n```\n\nСтраницы генерируются при сборке. Остальные рендерятся по запросу.",
    answerEn: "`generateStaticParams` replaces `getStaticPaths` in the App Router. It returns an array of params for statically generating dynamic routes:\n\n```ts\nexport async function generateStaticParams() {\n  return [{ id: '1' }, { id: '2' }];\n}\n```\n\nPages are generated at build time. Remaining routes are rendered on demand.",
  },
  {
    id: 'nextjs-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['rendering'],
    questionRu: 'Что такое generateMetadata?',
    questionEn: 'What is generateMetadata?',
    answerRu: '`generateMetadata` — `async` функция для динамических метаданных страницы (`title`, `description`, OpenGraph). Получает `params` и `searchParams`.\n\nЗаменяет статический объект `metadata` для динамических страниц. Выполняется на сервере, может делать запросы к БД.\n\nNext.js дедублирует одинаковые `fetch` запросы.',
    answerEn: '`generateMetadata` is an `async` function for generating dynamic page metadata (`title`, `description`, OpenGraph). It receives `params` and `searchParams`.\n\nReplaces the static `metadata` object for dynamic pages. Runs on the server and can make database requests.\n\nNext.js deduplicates identical `fetch` requests.',
  },
  {
    id: 'nextjs-014',
    difficulty: 'HARD',
    order: 14,
    tags: ['rendering'],
    questionRu: 'Что такое Edge Runtime и Node.js Runtime в Next.js?',
    questionEn: 'What are Edge Runtime and Node.js Runtime in Next.js?',
    answerRu: '**Node.js Runtime** (по умолчанию): полный Node.js, все npm пакеты, неограниченный размер.\n\n**Edge Runtime**: V8-движок без Node.js API, быстрый cold start, ограниченный набор API (`fetch`, `WebCrypto`), ограничение размера бандла (~1MB).\n\n- **Edge** — для Middleware, геолокации, A/B тестов\n- **Node.js** — для работы с БД, файлами',
    answerEn: '**Node.js Runtime** (default): full Node.js, all npm packages, no size limit.\n\n**Edge Runtime**: V8 engine without Node.js API, fast cold start, limited API surface (`fetch`, `WebCrypto`), bundle size limit (~1MB).\n\n- **Edge** — for Middleware, geolocation, A/B testing\n- **Node.js** — for database access, file system operations',
  },
  {
    id: 'nextjs-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['data-fetching'],
    questionRu: 'Как делать data fetching в App Router?',
    questionEn: 'How do you fetch data in the App Router?',
    answerRu: "**Server Components:** `async`/`await` прямо в компоненте — `fetch()`, ORM, SDK. Данные `fetch()` кешируются по умолчанию.\n\n**Клиентский fetching:** React Query, SWR, `useEffect`.\n\n**Мутации:** Server Actions.\n\nNext.js расширяет `fetch`:\n- `{ next: { revalidate: 60 } }` — ISR\n- `{ cache: 'no-store' }` — SSR",
    answerEn: "**Server Components:** `async`/`await` directly in the component — `fetch()`, ORM, or SDK. `fetch()` data is cached by default.\n\n**Client-side fetching:** React Query, SWR, `useEffect`.\n\n**Mutations:** Server Actions.\n\nNext.js extends `fetch`:\n- `{ next: { revalidate: 60 } }` — ISR\n- `{ cache: 'no-store' }` — SSR",
  },
  {
    id: 'nextjs-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['data-fetching'],
    questionRu: 'Как работает кеширование fetch в Next.js?',
    questionEn: 'How does fetch caching work in Next.js?',
    answerRu: "Next.js расширяет `fetch` с опциями кеширования:\n\n- `cache: 'force-cache'` (default) — кеш при сборке\n- `cache: 'no-store'` — без кеша, каждый запрос свежий (SSR)\n- `next.revalidate: 60` — ISR, обновление каждые 60 секунд\n- `next.tags: ['posts']` — тегированный кеш для `revalidateTag()`",
    answerEn: "Next.js extends `fetch` with caching options:\n\n- `cache: 'force-cache'` (default) — caches at build time\n- `cache: 'no-store'` — no cache, every request is fresh (SSR)\n- `next.revalidate: 60` — ISR, refreshes every 60 seconds\n- `next.tags: ['posts']` — tagged cache for use with `revalidateTag()`",
  },
  {
    id: 'nextjs-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['data-fetching'],
    questionRu: 'Что такое revalidatePath и revalidateTag?',
    questionEn: 'What are revalidatePath and revalidateTag?',
    answerRu: "`revalidatePath('/blog')` — инвалидирует кеш для конкретного маршрута.\n\n`revalidateTag('posts')` — инвалидирует все `fetch` с тегом `'posts'`.\n\nВызываются в **Server Actions** или **Route Handlers** после мутации данных. Позволяют точечно обновлять кеш без полной перегенерации.",
    answerEn: "`revalidatePath('/blog')` invalidates the cache for a specific route.\n\n`revalidateTag('posts')` invalidates all `fetch` calls tagged with `'posts'`.\n\nCalled inside **Server Actions** or **Route Handlers** after a data mutation. Allow precise cache updates without a full rebuild.",
  },
  {
    id: 'nextjs-018',
    difficulty: 'HARD',
    order: 18,
    tags: ['data-fetching'],
    questionRu: 'Как работает request deduplication в Next.js?',
    questionEn: 'How does request deduplication work in Next.js?',
    answerRu: 'Next.js автоматически дедублирует идентичные `fetch`-запросы в одном render pass. Два компонента, делающие `fetch` к одному URL, получат один реальный запрос.\n\nРаботает для `fetch()` с одинаковым URL и опциями. Для других источников (ORM, SDK) используется `React cache()` для мемоизации.',
    answerEn: 'Next.js automatically deduplicates identical `fetch` requests within a single render pass. Two components fetching the same URL will only trigger one actual request.\n\nWorks for `fetch()` calls with the same URL and options. For other data sources (ORM, SDK), use `React cache()` for memoization.',
  },
  {
    id: 'nextjs-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['data-fetching'],
    questionRu: 'Что такое cookies() и headers() в Next.js?',
    questionEn: 'What are cookies() and headers() in Next.js?',
    answerRu: "`cookies()` и `headers()` — функции из `next/headers` для чтения HTTP cookies и заголовков в **Server Components** и **Route Handlers**.\n\n- `cookies().get('token')`\n- `cookies().set('name', 'value')`\n\nДелают компонент динамическим (opt out из статики). В **Server Actions** `cookies()` также поддерживает запись.",
    answerEn: "`cookies()` and `headers()` are functions from `next/headers` for reading HTTP cookies and headers in **Server Components** and **Route Handlers**.\n\n- `cookies().get('token')`\n- `cookies().set('name', 'value')`\n\nThey make the component dynamic (opt out of static rendering). In **Server Actions**, `cookies()` also supports writing.",
  },
  {
    id: 'nextjs-020',
    difficulty: 'HARD',
    order: 20,
    tags: ['data-fetching'],
    questionRu: 'Как работает оптимистичное обновление с Server Actions?',
    questionEn: 'How does optimistic updating work with Server Actions?',
    answerRu: '`useOptimistic` (React 19 / Next.js 14+) позволяет немедленно обновить UI до ответа сервера.\n\n**Паттерн:** обновить UI оптимистично → отправить Server Action → при ошибке откатить.\n\n```ts\nconst [optimisticItems, addOptimistic] = useOptimistic(\n  items,\n  (state, newItem) => [...state, newItem]\n);\n```',
    answerEn: '`useOptimistic` (React 19 / Next.js 14+) lets you immediately update the UI before the server responds.\n\n**Pattern:** update UI optimistically → send the Server Action → roll back on error.\n\n```ts\nconst [optimisticItems, addOptimistic] = useOptimistic(\n  items,\n  (state, newItem) => [...state, newItem]\n);\n```',
  },
  {
    id: 'nextjs-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['optimization'],
    questionRu: 'Что даёт компонент next/image?',
    questionEn: 'What does the next/image component provide?',
    answerRu: '`next/image` автоматически:\n- оптимизирует формат (WebP/AVIF)\n- изменяет размер под устройство через `srcset`\n- делает lazy loading\n- предотвращает CLS через резервирование места (обязательны `width`/`height` или `fill`)\n\nОбслуживает изображения через встроенный **Image Optimization API**.',
    answerEn: '`next/image` automatically:\n- optimizes the format (WebP/AVIF)\n- resizes images for the device via `srcset`\n- enables lazy loading\n- prevents CLS by reserving space (`width`/`height` or `fill` are required)\n\nImages are served through the built-in **Image Optimization API**.',
  },
  {
    id: 'nextjs-022',
    difficulty: 'EASY',
    order: 22,
    tags: ['optimization'],
    questionRu: 'Что даёт компонент next/font?',
    questionEn: 'What does next/font provide?',
    answerRu: '`next/font` автоматически:\n- скачивает шрифты при сборке (нет запросов к Google Fonts в runtime)\n- инлайнит CSS\n- применяет `font-display: swap`\n- генерирует CSS-переменную\n\nПолностью устраняет внешние запросы за шрифтами — улучшает приватность и производительность.',
    answerEn: '`next/font` automatically:\n- downloads fonts at build time (no runtime requests to Google Fonts)\n- inlines the CSS\n- applies `font-display: swap`\n- generates a CSS variable\n\nCompletely eliminates external font requests — improving both privacy and performance.',
  },
  {
    id: 'nextjs-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['optimization'],
    questionRu: 'Что такое Bundle Analyzer в Next.js?',
    questionEn: 'What is Bundle Analyzer in Next.js?',
    answerRu: '`@next/bundle-analyzer` визуализирует содержимое JS-бандла. Подключается в `next.config.js`.\n\nЗапуск: `ANALYZE=true npm run build`.\n\nПоказывает размер каждого модуля — помогает найти тяжёлые зависимости для замены или динамического импорта.',
    answerEn: '`@next/bundle-analyzer` visualizes the contents of the JS bundle. Configured in `next.config.js`.\n\nRun with: `ANALYZE=true npm run build`.\n\nShows the size of each module — useful for identifying heavy dependencies to replace or dynamically import.',
  },
  {
    id: 'nextjs-024',
    difficulty: 'EASY',
    order: 24,
    tags: ['deployment'],
    questionRu: 'Как Next.js приложение деплоится на Vercel?',
    questionEn: 'How is a Next.js app deployed to Vercel?',
    answerRu: '**Vercel** — нативная платформа для Next.js.\n\n- Push в git → автодеплой\n- SSR страницы становятся **Serverless Functions**\n- Edge Middleware деплоится на **Edge Network**\n- Статика — на CDN\n\nVercel автоматически определяет оптимальную конфигурацию. ISR поддерживается нативно через Vercel KV.',
    answerEn: '**Vercel** is the native platform for Next.js.\n\n- Push to git → automatic deployment\n- SSR pages become **Serverless Functions**\n- Edge Middleware is deployed to the **Edge Network**\n- Static assets go to a CDN\n\nVercel automatically determines the optimal configuration. ISR is natively supported via Vercel KV.',
  },
  {
    id: 'nextjs-025',
    difficulty: 'MEDIUM',
    order: 25,
    tags: ['deployment'],
    questionRu: 'Как задеплоить Next.js не на Vercel?',
    questionEn: 'How do you deploy Next.js outside of Vercel?',
    answerRu: "**Standalone output:** `output: 'standalone'` в `next.config.js` — создаёт минимальный Node.js сервер. Docker: копировать `.next/standalone` + `.next/static`.\n\n**Статичные сайты:** `output: 'export'` — создаёт статические HTML файлы.\n\n**Платформы:** AWS, Railway, Render, Fly.io.\n\nISR и Image Optimization нужно настраивать самостоятельно.",
    answerEn: "**Standalone output:** `output: 'standalone'` in `next.config.js` creates a minimal Node.js server. Docker: copy `.next/standalone` + `.next/static`.\n\n**Static sites:** `output: 'export'` generates static HTML files.\n\n**Platforms:** AWS, Railway, Render, Fly.io.\n\nYou need to configure ISR and Image Optimization yourself.",
  },
  {
    id: 'nextjs-026',
    difficulty: 'MEDIUM',
    order: 26,
    tags: ['deployment'],
    questionRu: 'Что такое next.config.js и какие основные настройки?',
    questionEn: 'What is next.config.js and what are its main options?',
    answerRu: '`next.config.js` — конфигурационный файл Next.js.\n\n**Ключевые опции:**\n- `images.domains`/`remotePatterns` — разрешённые источники изображений\n- `redirects()`/`rewrites()` — редиректы и проксирование\n- `env` — переменные окружения\n- `webpack` — кастомизация сборки\n- `experimental` — новые функции\n\nПоддерживает `async` функции для динамической конфигурации.',
    answerEn: '`next.config.js` is the Next.js configuration file.\n\n**Key options:**\n- `images.domains`/`remotePatterns` — allowed image sources\n- `redirects()`/`rewrites()` — redirects and proxying\n- `env` — environment variables\n- `webpack` — build customization\n- `experimental` — new features\n\nSupports `async` functions for dynamic configuration.',
  },
];
