import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'nextjs-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['routing'],
    questionRu: 'В чём разница между Pages Router и App Router?',
    questionEn: 'What is the difference between Pages Router and App Router?',
    answerRu: 'Pages Router (до Next 13): файлы в /pages, getServerSideProps/getStaticProps для data fetching, всё клиентские компоненты по умолчанию. App Router (Next 13+): файлы в /app, React Server Components по умолчанию, async/await для data fetching, layouts, loading, error как специальные файлы.',
    answerEn: 'Pages Router (before Next 13): files in /pages, getServerSideProps/getStaticProps for data fetching, all components are Client Components by default. App Router (Next 13+): files in /app, React Server Components by default, async/await for data fetching, layouts, loading, and error as special files.',
  },
  {
    id: 'nextjs-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['routing'],
    questionRu: 'Как работает файловая система роутинга в App Router?',
    questionEn: 'How does the file-system routing work in App Router?',
    answerRu: 'Каждая папка в /app — сегмент маршрута. page.tsx делает маршрут публичным. Специальные файлы: layout.tsx (общий UI для сегмента), loading.tsx (Suspense fallback), error.tsx (Error Boundary), not-found.tsx. Динамические сегменты: [id], [...slug], [[...slug]] (опциональный catch-all).',
    answerEn: 'Each folder in /app is a route segment. page.tsx makes the route publicly accessible. Special files: layout.tsx (shared UI for the segment), loading.tsx (Suspense fallback), error.tsx (Error Boundary), not-found.tsx. Dynamic segments: [id], [...slug], [[...slug]] (optional catch-all).',
  },
  {
    id: 'nextjs-003',
    difficulty: 'HARD',
    order: 3,
    tags: ['routing'],
    questionRu: 'Что такое Route Groups и Parallel Routes?',
    questionEn: 'What are Route Groups and Parallel Routes?',
    answerRu: 'Route Groups: папки в скобках (auth) группируют маршруты без влияния на URL — удобно для разных layouts. Parallel Routes: @folder — рендерить несколько страниц одновременно в одном layout (dashboard с @analytics и @team). Intercepting Routes: (..) перехватывают маршрут для модалок.',
    answerEn: 'Route Groups: folders in parentheses (auth) group routes without affecting the URL — useful for different layouts. Parallel Routes: @folder — render multiple pages simultaneously in a single layout (e.g. a dashboard with @analytics and @team). Intercepting Routes: (..) intercept a route for use in modals.',
  },
  {
    id: 'nextjs-004',
    difficulty: 'EASY',
    order: 4,
    tags: ['routing'],
    questionRu: 'Как работает навигация в Next.js?',
    questionEn: 'How does navigation work in Next.js?',
    answerRu: 'Компонент <Link href="/about"> — клиентская навигация без перезагрузки, автоматический prefetch в viewport. useRouter() — программная навигация: router.push(), router.replace(), router.back(). usePathname(), useSearchParams() — для чтения текущего URL. redirect() — серверный редирект.',
    answerEn: 'The <Link href="/about"> component enables client-side navigation without a full page reload and automatically prefetches links in the viewport. useRouter() is for programmatic navigation: router.push(), router.replace(), router.back(). usePathname(), useSearchParams() read the current URL. redirect() performs a server-side redirect.',
  },
  {
    id: 'nextjs-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['routing'],
    questionRu: 'Что такое Middleware в Next.js?',
    questionEn: 'What is Middleware in Next.js?',
    answerRu: 'Middleware (middleware.ts в корне) — код выполняющийся до обработки запроса на Edge Runtime. Применения: авторизация/редирект, A/B тесты, локализация, добавление заголовков. Возвращает NextResponse. Matcher config ограничивает маршруты. Важно: Edge Runtime ограничен (нет Node.js API).',
    answerEn: 'Middleware (middleware.ts at the root) is code that runs before a request is processed, on the Edge Runtime. Use cases: auth/redirects, A/B testing, localization, adding headers. Returns NextResponse. The matcher config limits which routes it applies to. Important: Edge Runtime is restricted (no Node.js API).',
  },
  {
    id: 'nextjs-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['routing'],
    questionRu: 'Что такое Route Handlers (API Routes)?',
    questionEn: 'What are Route Handlers (API Routes)?',
    answerRu: 'Route Handlers: файл route.ts в /app экспортирует GET, POST, PUT, DELETE функции. Заменяют pages/api в App Router. Получают Request, возвращают Response. Поддерживают Edge и Node.js runtime. Можно делать revalidation, streaming, работу с cookies и headers.',
    answerEn: 'Route Handlers: a route.ts file in /app exports GET, POST, PUT, DELETE functions. They replace pages/api in the App Router. They receive a Request and return a Response. Support both Edge and Node.js runtimes. You can perform revalidation, streaming, and work with cookies and headers.',
  },
  {
    id: 'nextjs-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['routing'],
    questionRu: 'Что такое Server Actions?',
    questionEn: 'What are Server Actions?',
    answerRu: "Server Actions — async функции с директивой 'use server', выполняющиеся на сервере. Вызываются напрямую из клиентского кода как обычные функции. Используются для: отправки форм, мутации данных, вызова БД. Автоматически создают API endpoint. Интегрированы с revalidatePath/revalidateTag.",
    answerEn: "Server Actions are async functions marked with the 'use server' directive that execute on the server. They are called directly from client-side code like regular functions. Used for: form submissions, data mutations, database calls. They automatically create an API endpoint and integrate with revalidatePath/revalidateTag.",
  },
  {
    id: 'nextjs-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['rendering'],
    questionRu: 'Что такое SSR, SSG и ISR — в чём разница?',
    questionEn: 'What are SSR, SSG, and ISR — what is the difference?',
    answerRu: 'SSR (Server-Side Rendering): HTML генерируется на сервере при каждом запросе — актуальные данные, медленнее. SSG (Static Site Generation): HTML генерируется при сборке — быстро, но данные устаревают. ISR (Incremental Static Regeneration): SSG с фоновой регенерацией через revalidate — баланс скорости и свежести.',
    answerEn: 'SSR (Server-Side Rendering): HTML is generated on the server on every request — data is always fresh, but slower. SSG (Static Site Generation): HTML is generated at build time — fast, but data can become stale. ISR (Incremental Static Regeneration): SSG with background regeneration via revalidate — a balance of speed and freshness.',
  },
  {
    id: 'nextjs-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['rendering'],
    questionRu: 'Что такое React Server Components (RSC)?',
    questionEn: 'What are React Server Components (RSC)?',
    answerRu: 'RSC — компоненты, рендерящиеся только на сервере. Преимущества: прямой доступ к БД/файловой системе, нет JS в бандле клиента, могут быть async. Ограничения: нет useState/useEffect, нет браузерных API, нет обработчиков событий. В App Router все компоненты Server по умолчанию.',
    answerEn: 'RSC are components that render exclusively on the server. Advantages: direct access to databases/filesystem, no JS in the client bundle, can be async. Limitations: no useState/useEffect, no browser APIs, no event handlers. In the App Router, all components are Server Components by default.',
  },
  {
    id: 'nextjs-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['rendering'],
    questionRu: "Когда использовать 'use client'?",
    questionEn: "When should you use 'use client'?",
    answerRu: "'use client' директива помечает компонент и его дочерние как клиентские. Нужна когда: используются хуки (useState, useEffect), обработчики событий, браузерные API. Граница: серверные компоненты могут передавать props клиентским, но не наоборот. Клиентские компоненты не могут напрямую рендерить async серверные.",
    answerEn: "The 'use client' directive marks a component and its children as Client Components. It is required when: using hooks (useState, useEffect), event handlers, or browser APIs. The boundary: Server Components can pass props to Client Components, but not vice versa. Client Components cannot directly render async Server Components.",
  },
  {
    id: 'nextjs-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['rendering'],
    questionRu: 'Как работает Streaming в Next.js?',
    questionEn: 'How does Streaming work in Next.js?',
    answerRu: 'Streaming — постепенная отправка HTML с сервера по мере готовности частей страницы. Реализуется через Suspense: обёрнутые части стримятся, остальное отправляется сразу. loading.tsx автоматически создаёт Suspense boundary для сегмента. Улучшает TTFB и воспринимаемую скорость загрузки.',
    answerEn: 'Streaming progressively sends HTML from the server as parts of the page become ready. It is implemented via Suspense: wrapped parts are streamed while the rest is sent immediately. loading.tsx automatically creates a Suspense boundary for the segment. This improves TTFB and perceived load speed.',
  },
  {
    id: 'nextjs-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['rendering'],
    questionRu: 'Что такое generateStaticParams?',
    questionEn: 'What is generateStaticParams?',
    answerRu: "generateStaticParams заменяет getStaticPaths в App Router. Возвращает массив параметров для статической генерации динамических маршрутов: export async function generateStaticParams() { return [{ id: '1' }, { id: '2' }] }. Страницы генерируются при сборке. Оставшиеся рендерятся по запросу.",
    answerEn: "generateStaticParams replaces getStaticPaths in the App Router. It returns an array of params for statically generating dynamic routes: export async function generateStaticParams() { return [{ id: '1' }, { id: '2' }] }. Pages are generated at build time. Remaining routes are rendered on demand.",
  },
  {
    id: 'nextjs-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['rendering'],
    questionRu: 'Что такое generateMetadata?',
    questionEn: 'What is generateMetadata?',
    answerRu: 'generateMetadata — async функция для динамических метаданных страницы (title, description, OpenGraph). Получает params и searchParams. Заменяет статический объект metadata для динамических страниц. Выполняется на сервере, может делать запросы к БД. Next.js дедублирует одинаковые fetch запросы.',
    answerEn: 'generateMetadata is an async function for generating dynamic page metadata (title, description, OpenGraph). It receives params and searchParams. It replaces the static metadata object for dynamic pages. It runs on the server and can make database requests. Next.js deduplicates identical fetch requests.',
  },
  {
    id: 'nextjs-014',
    difficulty: 'HARD',
    order: 14,
    tags: ['rendering'],
    questionRu: 'Что такое Edge Runtime и Node.js Runtime в Next.js?',
    questionEn: 'What are Edge Runtime and Node.js Runtime in Next.js?',
    answerRu: 'Node.js Runtime (по умолчанию): полный Node.js, все npm пакеты, неограниченный размер. Edge Runtime: V8-движок без Node.js API, быстрый cold start, ограниченный набор API (fetch, WebCrypto), ограничение размера бандла (~1MB). Edge для: Middleware, геолокации, A/B тестов. Node.js для: работы с БД, файлами.',
    answerEn: 'Node.js Runtime (default): full Node.js, all npm packages, no size limit. Edge Runtime: V8 engine without Node.js API, fast cold start, limited API surface (fetch, WebCrypto), bundle size limit (~1MB). Use Edge for: Middleware, geolocation, A/B testing. Use Node.js for: database access, file system operations.',
  },
  {
    id: 'nextjs-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['data-fetching'],
    questionRu: 'Как делать data fetching в App Router?',
    questionEn: 'How do you fetch data in the App Router?',
    answerRu: "Server Components: async/await прямо в компоненте — fetch(), ORM, SDK. Данные fetch() кешируются по умолчанию. Для клиентского: React Query, SWR, useEffect. Server Actions для мутаций. Next.js расширяет fetch: { next: { revalidate: 60 } } для ISR, { cache: 'no-store' } для SSR.",
    answerEn: "Server Components: use async/await directly in the component — fetch(), ORM, or SDK. fetch() data is cached by default. For client-side fetching: use React Query, SWR, or useEffect. Use Server Actions for mutations. Next.js extends fetch: { next: { revalidate: 60 } } for ISR, { cache: 'no-store' } for SSR.",
  },
  {
    id: 'nextjs-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['data-fetching'],
    questionRu: 'Как работает кеширование fetch в Next.js?',
    questionEn: 'How does fetch caching work in Next.js?',
    answerRu: "Next.js расширяет fetch с кешированием. cache: 'force-cache' (default) — кеш при сборке. cache: 'no-store' — без кеша, каждый запрос свежий (SSR). next.revalidate: 60 — ISR, обновление каждые 60 секунд. next.tags: ['posts'] — тегированный кеш для revalidateTag().",
    answerEn: "Next.js extends fetch with caching options. cache: 'force-cache' (default) — caches at build time. cache: 'no-store' — no cache, every request is fresh (SSR). next.revalidate: 60 — ISR, refreshes every 60 seconds. next.tags: ['posts'] — tagged cache for use with revalidateTag().",
  },
  {
    id: 'nextjs-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['data-fetching'],
    questionRu: 'Что такое revalidatePath и revalidateTag?',
    questionEn: 'What are revalidatePath and revalidateTag?',
    answerRu: "revalidatePath('/blog') — инвалидирует кеш для конкретного маршрута. revalidateTag('posts') — инвалидирует все fetch с тегом 'posts'. Вызываются в Server Actions или Route Handlers после мутации данных. Позволяют точечно обновлять кеш без полной перегенерации.",
    answerEn: "revalidatePath('/blog') invalidates the cache for a specific route. revalidateTag('posts') invalidates all fetch calls tagged with 'posts'. They are called inside Server Actions or Route Handlers after a data mutation. They allow precise cache updates without a full rebuild.",
  },
  {
    id: 'nextjs-018',
    difficulty: 'HARD',
    order: 18,
    tags: ['data-fetching'],
    questionRu: 'Как работает request deduplication в Next.js?',
    questionEn: 'How does request deduplication work in Next.js?',
    answerRu: 'Next.js автоматически дедублирует идентичные fetch-запросы в одном render pass. Два компонента делающие fetch к одному URL получат один реальный запрос. Работает для fetch() с одинаковым URL и опциями. Для других источников (ORM, SDK) используется React cache() для мемоизации.',
    answerEn: 'Next.js automatically deduplicates identical fetch requests within a single render pass. Two components fetching the same URL will only trigger one actual request. This works for fetch() calls with the same URL and options. For other data sources (ORM, SDK), use React cache() for memoization.',
  },
  {
    id: 'nextjs-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['data-fetching'],
    questionRu: 'Что такое cookies() и headers() в Next.js?',
    questionEn: 'What are cookies() and headers() in Next.js?',
    answerRu: "cookies() и headers() — функции из next/headers для чтения HTTP cookies и заголовков в Server Components и Route Handlers. cookies().get('token'), cookies().set('name', 'value'). Делают компонент динамическим (opt out из статики). В Server Actions cookies() также поддерживает запись.",
    answerEn: "cookies() and headers() are functions from next/headers for reading HTTP cookies and headers in Server Components and Route Handlers. cookies().get('token'), cookies().set('name', 'value'). They make the component dynamic (opt out of static rendering). In Server Actions, cookies() also supports writing.",
  },
  {
    id: 'nextjs-020',
    difficulty: 'HARD',
    order: 20,
    tags: ['data-fetching'],
    questionRu: 'Как работает оптимистичное обновление с Server Actions?',
    questionEn: 'How does optimistic updating work with Server Actions?',
    answerRu: 'useOptimistic (React 19 / Next.js 14+) позволяет немедленно обновить UI до ответа сервера. При вызове Server Action: обновить UI оптимистично → отправить запрос → при ошибке откатить. Паттерн: const [optimisticItems, addOptimistic] = useOptimistic(items, (state, newItem) => [...state, newItem]).',
    answerEn: 'useOptimistic (React 19 / Next.js 14+) lets you immediately update the UI before the server responds. When calling a Server Action: update UI optimistically → send the request → roll back on error. Pattern: const [optimisticItems, addOptimistic] = useOptimistic(items, (state, newItem) => [...state, newItem]).',
  },
  {
    id: 'nextjs-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['optimization'],
    questionRu: 'Что даёт компонент next/image?',
    questionEn: 'What does the next/image component provide?',
    answerRu: 'next/image автоматически: оптимизирует формат (WebP/AVIF), изменяет размер под устройство через srcset, делает lazy loading, предотвращает CLS через резервирование места (обязательны width/height или fill). Обслуживает изображения через встроенный Image Optimization API.',
    answerEn: 'next/image automatically: optimizes the format (WebP/AVIF), resizes images for the device via srcset, enables lazy loading, and prevents CLS by reserving space (width/height or fill are required). Images are served through the built-in Image Optimization API.',
  },
  {
    id: 'nextjs-022',
    difficulty: 'EASY',
    order: 22,
    tags: ['optimization'],
    questionRu: 'Что даёт компонент next/font?',
    questionEn: 'What does next/font provide?',
    answerRu: 'next/font автоматически: скачивает шрифты при сборке (нет запросов к Google Fonts в runtime), инлайнит CSS, применяет font-display: swap, генерирует CSS-переменную. Полностью устраняет внешние запросы за шрифтами — улучшает приватность и производительность.',
    answerEn: 'next/font automatically: downloads fonts at build time (no runtime requests to Google Fonts), inlines the CSS, applies font-display: swap, and generates a CSS variable. It completely eliminates external font requests — improving both privacy and performance.',
  },
  {
    id: 'nextjs-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['optimization'],
    questionRu: 'Что такое Bundle Analyzer в Next.js?',
    questionEn: 'What is Bundle Analyzer in Next.js?',
    answerRu: '@next/bundle-analyzer визуализирует содержимое JS-бандла. Подключается в next.config.js. Запуск: ANALYZE=true npm run build. Показывает размер каждого модуля — помогает найти тяжёлые зависимости для замены или динамического импорта.',
    answerEn: '@next/bundle-analyzer visualizes the contents of the JS bundle. It is configured in next.config.js. Run with: ANALYZE=true npm run build. It shows the size of each module — useful for identifying heavy dependencies to replace or dynamically import.',
  },
  {
    id: 'nextjs-024',
    difficulty: 'EASY',
    order: 24,
    tags: ['deployment'],
    questionRu: 'Как Next.js приложение деплоится на Vercel?',
    questionEn: 'How is a Next.js app deployed to Vercel?',
    answerRu: 'Vercel — нативная платформа для Next.js. Push в git → автодеплой. SSR страницы становятся Serverless Functions. Edge Middleware деплоится на Edge Network. Статика на CDN. Vercel автоматически определяет оптимальную конфигурацию. ISR поддерживается нативно через Vercel KV.',
    answerEn: 'Vercel is the native platform for Next.js. Push to git → automatic deployment. SSR pages become Serverless Functions. Edge Middleware is deployed to the Edge Network. Static assets go to a CDN. Vercel automatically determines the optimal configuration. ISR is natively supported via Vercel KV.',
  },
  {
    id: 'nextjs-025',
    difficulty: 'MEDIUM',
    order: 25,
    tags: ['deployment'],
    questionRu: 'Как задеплоить Next.js не на Vercel?',
    questionEn: 'How do you deploy Next.js outside of Vercel?',
    answerRu: "Standalone output: output: 'standalone' в next.config.js — создаёт минимальный Node.js сервер. Docker: копировать .next/standalone + .next/static. Для статичных сайтов: output: 'export' — создаёт статические HTML файлы. Платформы: AWS, Railway, Render, Fly.io. Нужно самостоятельно настраивать ISR и Image Optimization.",
    answerEn: "Standalone output: output: 'standalone' in next.config.js creates a minimal Node.js server. Docker: copy .next/standalone + .next/static. For static sites: output: 'export' generates static HTML files. Platforms: AWS, Railway, Render, Fly.io. You need to configure ISR and Image Optimization yourself.",
  },
  {
    id: 'nextjs-026',
    difficulty: 'MEDIUM',
    order: 26,
    tags: ['deployment'],
    questionRu: 'Что такое next.config.js и какие основные настройки?',
    questionEn: 'What is next.config.js and what are its main options?',
    answerRu: 'next.config.js — конфигурация Next.js. Ключевые опции: images.domains/remotePatterns (разрешённые источники изображений), redirects()/rewrites() (редиректы и проксирование), env (переменные окружения), webpack (кастомизация сборки), experimental (новые функции). Поддерживает async функции для динамической конфигурации.',
    answerEn: 'next.config.js is the Next.js configuration file. Key options: images.domains/remotePatterns (allowed image sources), redirects()/rewrites() (redirects and proxying), env (environment variables), webpack (build customization), experimental (new features). Supports async functions for dynamic configuration.',
  },
];
