import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'nextjs-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['routing'],
    questionRu: 'В чём разница между Pages Router и App Router?',
    questionEn: 'В чём разница между Pages Router и App Router?',
    answerRu: 'Pages Router (до Next 13): файлы в /pages, getServerSideProps/getStaticProps для data fetching, всё клиентские компоненты по умолчанию. App Router (Next 13+): файлы в /app, React Server Components по умолчанию, async/await для data fetching, layouts, loading, error как специальные файлы.',
    answerEn: 'Pages Router (до Next 13): файлы в /pages, getServerSideProps/getStaticProps для data fetching, всё клиентские компоненты по умолчанию. App Router (Next 13+): файлы в /app, React Server Components по умолчанию, async/await для data fetching, layouts, loading, error как специальные файлы.',
  },
  {
    id: 'nextjs-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['routing'],
    questionRu: 'Как работает файловая система роутинга в App Router?',
    questionEn: 'Как работает файловая система роутинга в App Router?',
    answerRu: 'Каждая папка в /app — сегмент маршрута. page.tsx делает маршрут публичным. Специальные файлы: layout.tsx (общий UI для сегмента), loading.tsx (Suspense fallback), error.tsx (Error Boundary), not-found.tsx. Динамические сегменты: [id], [...slug], [[...slug]] (опциональный catch-all).',
    answerEn: 'Каждая папка в /app — сегмент маршрута. page.tsx делает маршрут публичным. Специальные файлы: layout.tsx (общий UI для сегмента), loading.tsx (Suspense fallback), error.tsx (Error Boundary), not-found.tsx. Динамические сегменты: [id], [...slug], [[...slug]] (опциональный catch-all).',
  },
  {
    id: 'nextjs-003',
    difficulty: 'HARD',
    order: 3,
    tags: ['routing'],
    questionRu: 'Что такое Route Groups и Parallel Routes?',
    questionEn: 'Что такое Route Groups и Parallel Routes?',
    answerRu: 'Route Groups: папки в скобках (auth) группируют маршруты без влияния на URL — удобно для разных layouts. Parallel Routes: @folder — рендерить несколько страниц одновременно в одном layout (dashboard с @analytics и @team). Intercepting Routes: (..) перехватывают маршрут для модалок.',
    answerEn: 'Route Groups: папки в скобках (auth) группируют маршруты без влияния на URL — удобно для разных layouts. Parallel Routes: @folder — рендерить несколько страниц одновременно в одном layout (dashboard с @analytics и @team). Intercepting Routes: (..) перехватывают маршрут для модалок.',
  },
  {
    id: 'nextjs-004',
    difficulty: 'EASY',
    order: 4,
    tags: ['routing'],
    questionRu: 'Как работает навигация в Next.js?',
    questionEn: 'Как работает навигация в Next.js?',
    answerRu: 'Компонент <Link href="/about"> — клиентская навигация без перезагрузки, автоматический prefetch в viewport. useRouter() — программная навигация: router.push(), router.replace(), router.back(). usePathname(), useSearchParams() — для чтения текущего URL. redirect() — серверный редирект.',
    answerEn: 'Компонент <Link href="/about"> — клиентская навигация без перезагрузки, автоматический prefetch в viewport. useRouter() — программная навигация: router.push(), router.replace(), router.back(). usePathname(), useSearchParams() — для чтения текущего URL. redirect() — серверный редирект.',
  },
  {
    id: 'nextjs-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['routing'],
    questionRu: 'Что такое Middleware в Next.js?',
    questionEn: 'Что такое Middleware в Next.js?',
    answerRu: 'Middleware (middleware.ts в корне) — код выполняющийся до обработки запроса на Edge Runtime. Применения: авторизация/редирект, A/B тесты, локализация, добавление заголовков. Возвращает NextResponse. Matcher config ограничивает маршруты. Важно: Edge Runtime ограничен (нет Node.js API).',
    answerEn: 'Middleware (middleware.ts в корне) — код выполняющийся до обработки запроса на Edge Runtime. Применения: авторизация/редирект, A/B тесты, локализация, добавление заголовков. Возвращает NextResponse. Matcher config ограничивает маршруты. Важно: Edge Runtime ограничен (нет Node.js API).',
  },
  {
    id: 'nextjs-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['routing'],
    questionRu: 'Что такое Route Handlers (API Routes)?',
    questionEn: 'Что такое Route Handlers (API Routes)?',
    answerRu: 'Route Handlers: файл route.ts в /app экспортирует GET, POST, PUT, DELETE функции. Заменяют pages/api в App Router. Получают Request, возвращают Response. Поддерживают Edge и Node.js runtime. Можно делать revalidation, streaming, работу с cookies и headers.',
    answerEn: 'Route Handlers: файл route.ts в /app экспортирует GET, POST, PUT, DELETE функции. Заменяют pages/api в App Router. Получают Request, возвращают Response. Поддерживают Edge и Node.js runtime. Можно делать revalidation, streaming, работу с cookies и headers.',
  },
  {
    id: 'nextjs-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['routing'],
    questionRu: 'Что такое Server Actions?',
    questionEn: 'Что такое Server Actions?',
    answerRu: "Server Actions — async функции с директивой 'use server', выполняющиеся на сервере. Вызываются напрямую из клиентского кода как обычные функции. Используются для: отправки форм, мутации данных, вызова БД. Автоматически создают API endpoint. Интегрированы с revalidatePath/revalidateTag.",
    answerEn: "Server Actions — async функции с директивой 'use server', выполняющиеся на сервере. Вызываются напрямую из клиентского кода как обычные функции. Используются для: отправки форм, мутации данных, вызова БД. Автоматически создают API endpoint. Интегрированы с revalidatePath/revalidateTag.",
  },
  {
    id: 'nextjs-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['rendering'],
    questionRu: 'Что такое SSR, SSG и ISR — в чём разница?',
    questionEn: 'Что такое SSR, SSG и ISR — в чём разница?',
    answerRu: 'SSR (Server-Side Rendering): HTML генерируется на сервере при каждом запросе — актуальные данные, медленнее. SSG (Static Site Generation): HTML генерируется при сборке — быстро, но данные устаревают. ISR (Incremental Static Regeneration): SSG с фоновой регенерацией через revalidate — баланс скорости и свежести.',
    answerEn: 'SSR (Server-Side Rendering): HTML генерируется на сервере при каждом запросе — актуальные данные, медленнее. SSG (Static Site Generation): HTML генерируется при сборке — быстро, но данные устаревают. ISR (Incremental Static Regeneration): SSG с фоновой регенерацией через revalidate — баланс скорости и свежести.',
  },
  {
    id: 'nextjs-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['rendering'],
    questionRu: 'Что такое React Server Components (RSC)?',
    questionEn: 'Что такое React Server Components (RSC)?',
    answerRu: 'RSC — компоненты, рендерящиеся только на сервере. Преимущества: прямой доступ к БД/файловой системе, нет JS в бандле клиента, могут быть async. Ограничения: нет useState/useEffect, нет браузерных API, нет обработчиков событий. В App Router все компоненты Server по умолчанию.',
    answerEn: 'RSC — компоненты, рендерящиеся только на сервере. Преимущества: прямой доступ к БД/файловой системе, нет JS в бандле клиента, могут быть async. Ограничения: нет useState/useEffect, нет браузерных API, нет обработчиков событий. В App Router все компоненты Server по умолчанию.',
  },
  {
    id: 'nextjs-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['rendering'],
    questionRu: "Когда использовать 'use client'?",
    questionEn: "Когда использовать 'use client'?",
    answerRu: "'use client' директива помечает компонент и его дочерние как клиентские. Нужна когда: используются хуки (useState, useEffect), обработчики событий, браузерные API. Граница: серверные компоненты могут передавать props клиентским, но не наоборот. Клиентские компоненты не могут напрямую рендерить async серверные.",
    answerEn: "'use client' директива помечает компонент и его дочерние как клиентские. Нужна когда: используются хуки (useState, useEffect), обработчики событий, браузерные API. Граница: серверные компоненты могут передавать props клиентским, но не наоборот. Клиентские компоненты не могут напрямую рендерить async серверные.",
  },
  {
    id: 'nextjs-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['rendering'],
    questionRu: 'Как работает Streaming в Next.js?',
    questionEn: 'Как работает Streaming в Next.js?',
    answerRu: 'Streaming — постепенная отправка HTML с сервера по мере готовности частей страницы. Реализуется через Suspense: обёрнутые части стримятся, остальное отправляется сразу. loading.tsx автоматически создаёт Suspense boundary для сегмента. Улучшает TTFB и воспринимаемую скорость загрузки.',
    answerEn: 'Streaming — постепенная отправка HTML с сервера по мере готовности частей страницы. Реализуется через Suspense: обёрнутые части стримятся, остальное отправляется сразу. loading.tsx автоматически создаёт Suspense boundary для сегмента. Улучшает TTFB и воспринимаемую скорость загрузки.',
  },
  {
    id: 'nextjs-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['rendering'],
    questionRu: 'Что такое generateStaticParams?',
    questionEn: 'Что такое generateStaticParams?',
    answerRu: "generateStaticParams заменяет getStaticPaths в App Router. Возвращает массив параметров для статической генерации динамических маршрутов: export async function generateStaticParams() { return [{ id: '1' }, { id: '2' }] }. Страницы генерируются при сборке. Оставшиеся рендерятся по запросу.",
    answerEn: "generateStaticParams заменяет getStaticPaths в App Router. Возвращает массив параметров для статической генерации динамических маршрутов: export async function generateStaticParams() { return [{ id: '1' }, { id: '2' }] }. Страницы генерируются при сборке. Оставшиеся рендерятся по запросу.",
  },
  {
    id: 'nextjs-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['rendering'],
    questionRu: 'Что такое generateMetadata?',
    questionEn: 'Что такое generateMetadata?',
    answerRu: 'generateMetadata — async функция для динамических метаданных страницы (title, description, OpenGraph). Получает params и searchParams. Заменяет статический объект metadata для динамических страниц. Выполняется на сервере, может делать запросы к БД. Next.js дедублирует одинаковые fetch запросы.',
    answerEn: 'generateMetadata — async функция для динамических метаданных страницы (title, description, OpenGraph). Получает params и searchParams. Заменяет статический объект metadata для динамических страниц. Выполняется на сервере, может делать запросы к БД. Next.js дедублирует одинаковые fetch запросы.',
  },
  {
    id: 'nextjs-014',
    difficulty: 'HARD',
    order: 14,
    tags: ['rendering'],
    questionRu: 'Что такое Edge Runtime и Node.js Runtime в Next.js?',
    questionEn: 'Что такое Edge Runtime и Node.js Runtime в Next.js?',
    answerRu: 'Node.js Runtime (по умолчанию): полный Node.js, все npm пакеты, неограниченный размер. Edge Runtime: V8-движок без Node.js API, быстрый cold start, ограниченный набор API (fetch, WebCrypto), ограничение размера бандла (~1MB). Edge для: Middleware, геолокации, A/B тестов. Node.js для: работы с БД, файлами.',
    answerEn: 'Node.js Runtime (по умолчанию): полный Node.js, все npm пакеты, неограниченный размер. Edge Runtime: V8-движок без Node.js API, быстрый cold start, ограниченный набор API (fetch, WebCrypto), ограничение размера бандла (~1MB). Edge для: Middleware, геолокации, A/B тестов. Node.js для: работы с БД, файлами.',
  },
  {
    id: 'nextjs-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['data-fetching'],
    questionRu: 'Как делать data fetching в App Router?',
    questionEn: 'Как делать data fetching в App Router?',
    answerRu: "Server Components: async/await прямо в компоненте — fetch(), ORM, SDK. Данные fetch() кешируются по умолчанию. Для клиентского: React Query, SWR, useEffect. Server Actions для мутаций. Next.js расширяет fetch: { next: { revalidate: 60 } } для ISR, { cache: 'no-store' } для SSR.",
    answerEn: "Server Components: async/await прямо в компоненте — fetch(), ORM, SDK. Данные fetch() кешируются по умолчанию. Для клиентского: React Query, SWR, useEffect. Server Actions для мутаций. Next.js расширяет fetch: { next: { revalidate: 60 } } для ISR, { cache: 'no-store' } для SSR.",
  },
  {
    id: 'nextjs-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['data-fetching'],
    questionRu: 'Как работает кеширование fetch в Next.js?',
    questionEn: 'Как работает кеширование fetch в Next.js?',
    answerRu: "Next.js расширяет fetch с кешированием. cache: 'force-cache' (default) — кеш при сборке. cache: 'no-store' — без кеша, каждый запрос свежий (SSR). next.revalidate: 60 — ISR, обновление каждые 60 секунд. next.tags: ['posts'] — тегированный кеш для revalidateTag().",
    answerEn: "Next.js расширяет fetch с кешированием. cache: 'force-cache' (default) — кеш при сборке. cache: 'no-store' — без кеша, каждый запрос свежий (SSR). next.revalidate: 60 — ISR, обновление каждые 60 секунд. next.tags: ['posts'] — тегированный кеш для revalidateTag().",
  },
  {
    id: 'nextjs-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['data-fetching'],
    questionRu: 'Что такое revalidatePath и revalidateTag?',
    questionEn: 'Что такое revalidatePath и revalidateTag?',
    answerRu: "revalidatePath('/blog') — инвалидирует кеш для конкретного маршрута. revalidateTag('posts') — инвалидирует все fetch с тегом 'posts'. Вызываются в Server Actions или Route Handlers после мутации данных. Позволяют точечно обновлять кеш без полной перегенерации.",
    answerEn: "revalidatePath('/blog') — инвалидирует кеш для конкретного маршрута. revalidateTag('posts') — инвалидирует все fetch с тегом 'posts'. Вызываются в Server Actions или Route Handlers после мутации данных. Позволяют точечно обновлять кеш без полной перегенерации.",
  },
  {
    id: 'nextjs-018',
    difficulty: 'HARD',
    order: 18,
    tags: ['data-fetching'],
    questionRu: 'Как работает request deduplication в Next.js?',
    questionEn: 'Как работает request deduplication в Next.js?',
    answerRu: 'Next.js автоматически дедублирует идентичные fetch-запросы в одном render pass. Два компонента делающие fetch к одному URL получат один реальный запрос. Работает для fetch() с одинаковым URL и опциями. Для других источников (ORM, SDK) используется React cache() для мемоизации.',
    answerEn: 'Next.js автоматически дедублирует идентичные fetch-запросы в одном render pass. Два компонента делающие fetch к одному URL получат один реальный запрос. Работает для fetch() с одинаковым URL и опциями. Для других источников (ORM, SDK) используется React cache() для мемоизации.',
  },
  {
    id: 'nextjs-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['data-fetching'],
    questionRu: 'Что такое cookies() и headers() в Next.js?',
    questionEn: 'Что такое cookies() и headers() в Next.js?',
    answerRu: "cookies() и headers() — функции из next/headers для чтения HTTP cookies и заголовков в Server Components и Route Handlers. cookies().get('token'), cookies().set('name', 'value'). Делают компонент динамическим (opt out из статики). В Server Actions cookies() также поддерживает запись.",
    answerEn: "cookies() и headers() — функции из next/headers для чтения HTTP cookies и заголовков в Server Components и Route Handlers. cookies().get('token'), cookies().set('name', 'value'). Делают компонент динамическим (opt out из статики). В Server Actions cookies() также поддерживает запись.",
  },
  {
    id: 'nextjs-020',
    difficulty: 'HARD',
    order: 20,
    tags: ['data-fetching'],
    questionRu: 'Как работает оптимистичное обновление с Server Actions?',
    questionEn: 'Как работает оптимистичное обновление с Server Actions?',
    answerRu: 'useOptimistic (React 19 / Next.js 14+) позволяет немедленно обновить UI до ответа сервера. При вызове Server Action: обновить UI оптимистично → отправить запрос → при ошибке откатить. Паттерн: const [optimisticItems, addOptimistic] = useOptimistic(items, (state, newItem) => [...state, newItem]).',
    answerEn: 'useOptimistic (React 19 / Next.js 14+) позволяет немедленно обновить UI до ответа сервера. При вызове Server Action: обновить UI оптимистично → отправить запрос → при ошибке откатить. Паттерн: const [optimisticItems, addOptimistic] = useOptimistic(items, (state, newItem) => [...state, newItem]).',
  },
  {
    id: 'nextjs-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['optimization'],
    questionRu: 'Что даёт компонент next/image?',
    questionEn: 'Что даёт компонент next/image?',
    answerRu: 'next/image автоматически: оптимизирует формат (WebP/AVIF), изменяет размер под устройство через srcset, делает lazy loading, предотвращает CLS через резервирование места (обязательны width/height или fill). Обслуживает изображения через встроенный Image Optimization API.',
    answerEn: 'next/image автоматически: оптимизирует формат (WebP/AVIF), изменяет размер под устройство через srcset, делает lazy loading, предотвращает CLS через резервирование места (обязательны width/height или fill). Обслуживает изображения через встроенный Image Optimization API.',
  },
  {
    id: 'nextjs-022',
    difficulty: 'EASY',
    order: 22,
    tags: ['optimization'],
    questionRu: 'Что даёт компонент next/font?',
    questionEn: 'Что даёт компонент next/font?',
    answerRu: 'next/font автоматически: скачивает шрифты при сборке (нет запросов к Google Fonts в runtime), инлайнит CSS, применяет font-display: swap, генерирует CSS-переменную. Полностью устраняет внешние запросы за шрифтами — улучшает приватность и производительность.',
    answerEn: 'next/font автоматически: скачивает шрифты при сборке (нет запросов к Google Fonts в runtime), инлайнит CSS, применяет font-display: swap, генерирует CSS-переменную. Полностью устраняет внешние запросы за шрифтами — улучшает приватность и производительность.',
  },
  {
    id: 'nextjs-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['optimization'],
    questionRu: 'Что такое Bundle Analyzer в Next.js?',
    questionEn: 'Что такое Bundle Analyzer в Next.js?',
    answerRu: '@next/bundle-analyzer визуализирует содержимое JS-бандла. Подключается в next.config.js. Запуск: ANALYZE=true npm run build. Показывает размер каждого модуля — помогает найти тяжёлые зависимости для замены или динамического импорта.',
    answerEn: '@next/bundle-analyzer визуализирует содержимое JS-бандла. Подключается в next.config.js. Запуск: ANALYZE=true npm run build. Показывает размер каждого модуля — помогает найти тяжёлые зависимости для замены или динамического импорта.',
  },
  {
    id: 'nextjs-024',
    difficulty: 'EASY',
    order: 24,
    tags: ['deployment'],
    questionRu: 'Как Next.js приложение деплоится на Vercel?',
    questionEn: 'Как Next.js приложение деплоится на Vercel?',
    answerRu: 'Vercel — нативная платформа для Next.js. Push в git → автодеплой. SSR страницы становятся Serverless Functions. Edge Middleware деплоится на Edge Network. Статика на CDN. Vercel автоматически определяет оптимальную конфигурацию. ISR поддерживается нативно через Vercel KV.',
    answerEn: 'Vercel — нативная платформа для Next.js. Push в git → автодеплой. SSR страницы становятся Serverless Functions. Edge Middleware деплоится на Edge Network. Статика на CDN. Vercel автоматически определяет оптимальную конфигурацию. ISR поддерживается нативно через Vercel KV.',
  },
  {
    id: 'nextjs-025',
    difficulty: 'MEDIUM',
    order: 25,
    tags: ['deployment'],
    questionRu: 'Как задеплоить Next.js не на Vercel?',
    questionEn: 'Как задеплоить Next.js не на Vercel?',
    answerRu: "Standalone output: output: 'standalone' в next.config.js — создаёт минимальный Node.js сервер. Docker: копировать .next/standalone + .next/static. Для статичных сайтов: output: 'export' — создаёт статические HTML файлы. Платформы: AWS, Railway, Render, Fly.io. Нужно самостоятельно настраивать ISR и Image Optimization.",
    answerEn: "Standalone output: output: 'standalone' в next.config.js — создаёт минимальный Node.js сервер. Docker: копировать .next/standalone + .next/static. Для статичных сайтов: output: 'export' — создаёт статические HTML файлы. Платформы: AWS, Railway, Render, Fly.io. Нужно самостоятельно настраивать ISR и Image Optimization.",
  },
  {
    id: 'nextjs-026',
    difficulty: 'MEDIUM',
    order: 26,
    tags: ['deployment'],
    questionRu: 'Что такое next.config.js и какие основные настройки?',
    questionEn: 'Что такое next.config.js и какие основные настройки?',
    answerRu: 'next.config.js — конфигурация Next.js. Ключевые опции: images.domains/remotePatterns (разрешённые источники изображений), redirects()/rewrites() (редиректы и проксирование), env (переменные окружения), webpack (кастомизация сборки), experimental (новые функции). Поддерживает async функции для динамической конфигурации.',
    answerEn: 'next.config.js — конфигурация Next.js. Ключевые опции: images.domains/remotePatterns (разрешённые источники изображений), redirects()/rewrites() (редиректы и проксирование), env (переменные окружения), webpack (кастомизация сборки), experimental (новые функции). Поддерживает async функции для динамической конфигурации.',
  },
];
