import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'pat-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['solid', 'srp'],
    questionRu: 'Что такое принцип единственной ответственности (SRP)?',
    questionEn: 'What is the Single Responsibility Principle (SRP)?',
    answerRu: 'SRP (Single Responsibility Principle): класс/модуль/функция должны иметь только одну причину для изменения. Один компонент — одна задача. Нарушение: компонент одновременно загружает данные, валидирует и рендерит. Решение: разделить на хук для данных, утилиту для валидации и компонент для рендеринга.',
    answerEn: 'SRP (Single Responsibility Principle): a class/module/function should have only one reason to change. One component — one job. Violation: a component simultaneously fetches data, validates, and renders. Solution: split into a hook for data, a utility for validation, and a component for rendering.',
  },
  {
    id: 'pat-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['solid', 'ocp'],
    questionRu: 'Что такое принцип открытости/закрытости (OCP)?',
    questionEn: 'What is the Open/Closed Principle (OCP)?',
    answerRu: 'OCP (Open/Closed Principle): код открыт для расширения, закрыт для изменения. Добавлять новое поведение без изменения существующего кода. Пример: компонент Button принимает variant prop вместо условий внутри. Паттерны стратегии и декоратора реализуют OCP. В React: composition и render props вместо if/else внутри компонента.',
    answerEn: 'OCP (Open/Closed Principle): code is open for extension, closed for modification. Add new behavior without changing existing code. Example: a Button component accepts a variant prop instead of conditions inside. The Strategy and Decorator patterns implement OCP. In React: composition and render props instead of if/else inside the component.',
  },
  {
    id: 'pat-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['solid', 'lsp'],
    questionRu: 'Что такое принцип подстановки Лисков (LSP)?',
    questionEn: 'What is the Liskov Substitution Principle (LSP)?',
    answerRu: 'LSP (Liskov Substitution Principle): объекты подкласса должны заменять объекты базового класса без нарушения корректности. Подкласс не должен ужесточать preconditions или ослаблять postconditions. Нарушение: Button расширяет Input но не поддерживает onChange. В TS: если подтип сужает union — нарушение LSP.',
    answerEn: 'LSP (Liskov Substitution Principle): subclass objects must be substitutable for base class objects without breaking correctness. A subclass must not strengthen preconditions or weaken postconditions. Violation: Button extends Input but does not support onChange. In TypeScript: if a subtype narrows a union — that is an LSP violation.',
  },
  {
    id: 'pat-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['solid', 'isp'],
    questionRu: 'Что такое принцип разделения интерфейсов (ISP)?',
    questionEn: 'What is the Interface Segregation Principle (ISP)?',
    answerRu: 'ISP (Interface Segregation Principle): не заставлять клиента зависеть от методов которые он не использует. Лучше много маленьких специализированных интерфейсов чем один большой. В TS: разделить большой интерфейс User на Identifiable, Authenticatable, Profileable. В React: не передавать весь объект если нужно одно поле.',
    answerEn: 'ISP (Interface Segregation Principle): do not force a client to depend on methods it does not use. Many small, specialized interfaces are better than one large one. In TypeScript: split a large User interface into Identifiable, Authenticatable, Profileable. In React: do not pass the entire object when only one field is needed.',
  },
  {
    id: 'pat-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['solid', 'dip'],
    questionRu: 'Что такое принцип инверсии зависимостей (DIP)?',
    questionEn: 'What is the Dependency Inversion Principle (DIP)?',
    answerRu: 'DIP (Dependency Inversion Principle): модули верхнего уровня не должны зависеть от модулей нижнего — оба должны зависеть от абстракций. Высокоуровневый код не знает о конкретной реализации. В React: компонент принимает fetchUser как prop вместо прямого вызова API. Dependency Injection через контекст или props.',
    answerEn: 'DIP (Dependency Inversion Principle): high-level modules must not depend on low-level modules — both should depend on abstractions. High-level code does not know about the concrete implementation. In React: a component receives fetchUser as a prop instead of calling the API directly. Dependency Injection via context or props.',
  },
  {
    id: 'pat-006',
    difficulty: 'EASY',
    order: 6,
    tags: ['dry', 'kiss', 'yagni', 'principles'],
    questionRu: 'Что такое DRY, KISS и YAGNI?',
    questionEn: 'What are DRY, KISS, and YAGNI?',
    answerRu: "DRY (Don't Repeat Yourself): не дублировать логику — выносить в функции/хуки/компоненты. KISS (Keep It Simple, Stupid): простое решение лучше сложного — не усложнять без необходимости. YAGNI (You Aren't Gonna Need It): не добавлять функциональность «на будущее» — реализовывать только то что нужно сейчас. Три принципа дополняют SOLID.",
    answerEn: "DRY (Don't Repeat Yourself): do not duplicate logic — extract it into functions/hooks/components. KISS (Keep It Simple, Stupid): a simple solution is better than a complex one — don't over-engineer. YAGNI (You Aren't Gonna Need It): don't add functionality \"for the future\" — implement only what is needed now. These three principles complement SOLID.",
  },
  {
    id: 'pat-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['creational', 'singleton'],
    questionRu: 'Что такое паттерн Singleton?',
    questionEn: 'What is the Singleton pattern?',
    answerRu: 'Singleton гарантирует единственный экземпляр класса с глобальной точкой доступа. В JS: модуль — уже singleton (кешируется). Применение: конфигурация, логгер, connection pool. Минусы: глобальное состояние усложняет тестирование, нарушает SRP. В React: Context как альтернатива singleton для глобальных данных.',
    answerEn: 'Singleton ensures a single instance of a class with a global access point. In JS: a module is already a singleton (it is cached). Use cases: configuration, logger, connection pool. Downsides: global state complicates testing and violates SRP. In React: Context as an alternative to Singleton for global data.',
  },
  {
    id: 'pat-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['creational', 'factory'],
    questionRu: 'Что такое паттерн Factory?',
    questionEn: 'What is the Factory pattern?',
    answerRu: 'Factory инкапсулирует создание объектов. Простая фабрика: функция возвращающая разные объекты по параметру. Factory Method: базовый класс определяет интерфейс создания, подклассы реализуют. Abstract Factory: семейство связанных объектов. В React: компонент-фабрика возвращает разные компоненты по типу: renderField(type) → <Input> или <Select>.',
    answerEn: 'Factory encapsulates object creation. Simple factory: a function that returns different objects based on a parameter. Factory Method: a base class defines the creation interface, subclasses implement it. Abstract Factory: a family of related objects. In React: a factory component returns different components by type: renderField(type) → <Input> or <Select>.',
  },
  {
    id: 'pat-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['creational', 'builder'],
    questionRu: 'Что такое паттерн Builder?',
    questionEn: 'What is the Builder pattern?',
    answerRu: "Builder разделяет конструирование сложного объекта от его представления. Цепочка вызовов методов для пошаговой настройки. Пример: QueryBuilder().select('*').from('users').where('id=1').build(). В JS: популярен как Fluent Interface. Использование: конфигурация запросов, создание сложных объектов с множеством опций.",
    answerEn: "Builder separates the construction of a complex object from its representation. A chain of method calls for step-by-step configuration. Example: QueryBuilder().select('*').from('users').where('id=1').build(). In JS: popular as a Fluent Interface. Use cases: building query configurations, creating complex objects with many options.",
  },
  {
    id: 'pat-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['creational', 'prototype'],
    questionRu: 'Что такое паттерн Prototype?',
    questionEn: 'What is the Prototype pattern?',
    answerRu: 'Prototype создаёт объекты клонированием существующего. В JS прототипное наследование — нативный механизм. Object.create(proto) — создать объект с прототипом. structuredClone() для глубокого клонирования. Применение: когда создание объекта дороже клонирования, для шаблонных объектов. Spread оператор — поверхностное клонирование.',
    answerEn: 'Prototype creates objects by cloning an existing one. In JS, prototypal inheritance is a native mechanism. Object.create(proto) creates an object with a given prototype. structuredClone() for deep cloning. Use cases: when creating an object is more expensive than cloning it, for template objects. The spread operator performs a shallow clone.',
  },
  {
    id: 'pat-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['creational', 'dependency-injection'],
    questionRu: 'Что такое паттерн Dependency Injection?',
    questionEn: 'What is the Dependency Injection pattern?',
    answerRu: 'DI — передача зависимостей объекту извне вместо создания внутри. Улучшает тестируемость и следует DIP. В React: через props (явный DI), Context (неявный DI). Пример: компонент получает fetchData как prop — в тестах передаётся mock, в продакшне — реальный API. Инверсия контроля делает код модульным.',
    answerEn: 'DI means passing dependencies to an object from the outside instead of creating them internally. It improves testability and follows DIP. In React: via props (explicit DI) or Context (implicit DI). Example: a component receives fetchData as a prop — in tests a mock is passed, in production the real API is used. Inversion of control makes code modular.',
  },
  {
    id: 'pat-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['structural', 'decorator', 'hoc'],
    questionRu: 'Что такое паттерн Decorator?',
    questionEn: 'What is the Decorator pattern?',
    answerRu: 'Decorator динамически добавляет поведение объекту без изменения его класса. В JS: функции-обёртки, HOC в React, декораторы TypeScript (@Injectable). Пример: withAuth(Component) добавляет проверку авторизации. Pipe оператор в RxJS. Middleware в Express. Предпочтительнее наследования для расширения функциональности.',
    answerEn: 'Decorator dynamically adds behavior to an object without changing its class. In JS: wrapper functions, HOC in React, TypeScript decorators (@Injectable). Example: withAuth(Component) adds an authorization check. The pipe operator in RxJS. Middleware in Express. Preferred over inheritance for extending functionality.',
  },
  {
    id: 'pat-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['structural', 'adapter'],
    questionRu: 'Что такое паттерн Adapter?',
    questionEn: 'What is the Adapter pattern?',
    answerRu: 'Adapter преобразует интерфейс класса в другой интерфейс ожидаемый клиентом. Позволяет совместно работать несовместимым классам. Применение в frontend: обёртка над сторонней библиотекой — если библиотека изменится, меняем только адаптер. Нормализация API ответов к внутренней модели данных. Интеграция легаси кода.',
    answerEn: "Adapter converts a class's interface into another interface expected by the client. It allows incompatible classes to work together. Frontend use cases: wrapping a third-party library — if the library changes, only the adapter needs to be updated. Normalizing API responses to an internal data model. Integrating legacy code.",
  },
  {
    id: 'pat-014',
    difficulty: 'EASY',
    order: 14,
    tags: ['structural', 'facade'],
    questionRu: 'Что такое паттерн Facade?',
    questionEn: 'What is the Facade pattern?',
    answerRu: 'Facade предоставляет упрощённый интерфейс к сложной подсистеме. Скрывает сложность, предоставляет удобное API. Примеры: jQuery как фасад над DOM API, axios как фасад над fetch/XMLHttpRequest, хук useAuth скрывающий детали работы с токенами. Часто используется для упрощения работы со сложными библиотеками.',
    answerEn: 'Facade provides a simplified interface to a complex subsystem. It hides complexity and exposes a convenient API. Examples: jQuery as a facade over the DOM API, axios as a facade over fetch/XMLHttpRequest, a useAuth hook that hides token management details. Commonly used to simplify interaction with complex libraries.',
  },
  {
    id: 'pat-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['structural', 'proxy'],
    questionRu: 'Что такое паттерн Proxy?',
    questionEn: 'What is the Proxy pattern?',
    answerRu: 'Proxy контролирует доступ к объекту: добавляет логику до/после обращения. JS Proxy — нативная реализация. Применения: валидация, кеширование, логирование, lazy initialization, виртуальные прокси для тяжёлых объектов. Vue 3 реактивность основана на Proxy. Mobx использует Proxy для наблюдения за изменениями.',
    answerEn: 'Proxy controls access to an object: it adds logic before/after property access. The JS Proxy is a native implementation. Use cases: validation, caching, logging, lazy initialization, virtual proxies for heavy objects. Vue 3 reactivity is built on Proxy. MobX uses Proxy to observe changes.',
  },
  {
    id: 'pat-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['structural', 'composite'],
    questionRu: 'Что такое паттерн Composite?',
    questionEn: 'What is the Composite pattern?',
    answerRu: 'Composite позволяет работать с группой объектов как с единым объектом. Дерево компонентов: листья и контейнеры реализуют один интерфейс. React компонентное дерево — пример Composite. Применение: файловая система (файл и папка), UI компоненты (Button и Form оба рендерятся), DOM дерево.',
    answerEn: 'Composite allows treating a group of objects as a single object. A component tree: leaves and containers implement the same interface. The React component tree is an example of Composite. Use cases: file systems (file and folder), UI components (Button and Form both render), the DOM tree.',
  },
  {
    id: 'pat-017',
    difficulty: 'HARD',
    order: 17,
    tags: ['structural', 'flyweight'],
    questionRu: 'Что такое паттерн Flyweight?',
    questionEn: 'What is the Flyweight pattern?',
    answerRu: 'Flyweight разделяет общее состояние между множеством мелких объектов экономя память. Внутреннее состояние (общее, неизменяемое) хранится в flyweight. Внешнее состояние передаётся при вызове. Применение: пулы объектов, кеширование иконок/изображений, виртуализация списков где один компонент переиспользуется с разными данными.',
    answerEn: 'Flyweight shares common state among many fine-grained objects to save memory. Intrinsic state (shared, immutable) is stored in the flyweight. Extrinsic state is passed in at call time. Use cases: object pools, caching icons/images, list virtualization where a single component is reused with different data.',
  },
  {
    id: 'pat-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['behavioral', 'observer'],
    questionRu: 'Что такое паттерн Observer?',
    questionEn: 'What is the Observer pattern?',
    answerRu: 'Observer: объект (subject) уведомляет подписчиков об изменениях. Слабая связанность — subject не знает о конкретных observers. В JS: EventEmitter, addEventListener, RxJS Observable. Redux store — observer паттерн. React useEffect с зависимостями. Применение: события, pub/sub системы, реактивность.',
    answerEn: 'Observer: an object (subject) notifies subscribers about changes. Loose coupling — the subject does not know about concrete observers. In JS: EventEmitter, addEventListener, RxJS Observable. The Redux store is an observer pattern. React useEffect with dependencies. Use cases: events, pub/sub systems, reactivity.',
  },
  {
    id: 'pat-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['behavioral', 'strategy'],
    questionRu: 'Что такое паттерн Strategy?',
    questionEn: 'What is the Strategy pattern?',
    answerRu: 'Strategy определяет семейство алгоритмов, инкапсулирует каждый и делает их взаимозаменяемыми. Выбор алгоритма в runtime. Пример: сортировка с разными компараторами, валидация с разными правилами, оплата разными способами. В JS: передача функции как аргумент — уже паттерн стратегия. Реализует OCP.',
    answerEn: 'Strategy defines a family of algorithms, encapsulates each one, and makes them interchangeable. The algorithm is selected at runtime. Examples: sorting with different comparators, validation with different rules, payment with different methods. In JS: passing a function as an argument is already the Strategy pattern. It implements OCP.',
  },
  {
    id: 'pat-020',
    difficulty: 'MEDIUM',
    order: 20,
    tags: ['behavioral', 'command'],
    questionRu: 'Что такое паттерн Command?',
    questionEn: 'What is the Command pattern?',
    answerRu: "Command инкапсулирует запрос как объект. Позволяет: откладывать выполнение, ставить в очередь, отменять (undo/redo). Пример: { type: 'ADD_TODO', payload: '...' } в Redux — это команды. Undo/redo в текстовых редакторах. Транзакции. Логирование действий. История браузера pushState как командный паттерн.",
    answerEn: "Command encapsulates a request as an object. This enables: deferred execution, queuing, and undoing/redoing actions. Example: { type: 'ADD_TODO', payload: '...' } in Redux — these are commands. Undo/redo in text editors. Transactions. Action logging. Browser history pushState as the Command pattern.",
  },
  {
    id: 'pat-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['behavioral', 'mediator'],
    questionRu: 'Что такое паттерн Mediator?',
    questionEn: 'What is the Mediator pattern?',
    answerRu: 'Mediator централизует взаимодействие объектов — они общаются через посредника, а не напрямую. Уменьшает связанность. Примеры: EventBus/EventEmitter как медиатор между компонентами, Redux store как медиатор между частями приложения, чат-сервер координирующий пользователей. React Context как lightweight медиатор.',
    answerEn: 'Mediator centralizes object interactions — objects communicate through a mediator instead of directly with each other. Reduces coupling. Examples: EventBus/EventEmitter as a mediator between components, the Redux store as a mediator between parts of an application, a chat server coordinating users. React Context as a lightweight mediator.',
  },
  {
    id: 'pat-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['behavioral', 'chain-of-responsibility'],
    questionRu: 'Что такое паттерн Chain of Responsibility?',
    questionEn: 'What is the Chain of Responsibility pattern?',
    answerRu: 'Chain of Responsibility передаёт запрос по цепочке обработчиков — каждый решает обработать или передать дальше. Примеры: middleware в Express (next()), event bubbling в DOM, Redux middleware цепочка, Promise цепочка .then(). Позволяет добавлять/убирать обработчики без изменения клиента.',
    answerEn: 'Chain of Responsibility passes a request along a chain of handlers — each one decides whether to handle it or pass it on. Examples: middleware in Express (next()), event bubbling in the DOM, the Redux middleware chain, a Promise chain with .then(). Allows adding or removing handlers without changing the client.',
  },
  {
    id: 'pat-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['behavioral', 'iterator'],
    questionRu: 'Что такое паттерн Iterator?',
    questionEn: 'What is the Iterator pattern?',
    answerRu: 'Iterator предоставляет последовательный доступ к элементам коллекции без раскрытия её структуры. В JS: Symbol.iterator и протокол итерации. for...of работает с любым итерируемым. Генераторы — удобный способ создания итераторов. Array, Map, Set, String — встроенные итерируемые. Lazy вычисление через генераторы для больших коллекций.',
    answerEn: 'Iterator provides sequential access to elements of a collection without exposing its underlying structure. In JS: Symbol.iterator and the iteration protocol. for...of works with any iterable. Generators are a convenient way to create iterators. Array, Map, Set, and String are built-in iterables. Lazy evaluation via generators for large collections.',
  },
  {
    id: 'pat-024',
    difficulty: 'MEDIUM',
    order: 24,
    tags: ['behavioral', 'state', 'fsm'],
    questionRu: 'Что такое паттерн State?',
    questionEn: 'What is the State pattern?',
    answerRu: 'State позволяет объекту менять поведение при изменении внутреннего состояния — объект как будто меняет класс. Конечный автомат (FSM). Примеры: UI компонент с состояниями idle/loading/success/error, светофор, медиаплеер. XState библиотека для явных конечных автоматов в JS. Предотвращает невалидные состояния.',
    answerEn: 'State allows an object to change its behavior when its internal state changes — the object appears to change its class. Finite State Machine (FSM). Examples: a UI component with idle/loading/success/error states, a traffic light, a media player. XState is a library for explicit state machines in JS. Prevents invalid states.',
  },
  {
    id: 'pat-025',
    difficulty: 'EASY',
    order: 25,
    tags: ['clean-code', 'pure-functions', 'fp'],
    questionRu: 'Что такое чистые функции и почему они важны?',
    questionEn: 'What are pure functions and why are they important?',
    answerRu: 'Чистая функция: всегда возвращает одинаковый результат для одних аргументов (детерминированность) и не имеет побочных эффектов. Преимущества: предсказуемость, тестируемость (не нужны моки), кешируемость. Основа функционального программирования. React компоненты и Redux reducers должны быть чистыми функциями.',
    answerEn: 'A pure function always returns the same result for the same arguments (determinism) and has no side effects. Benefits: predictability, testability (no mocks needed), cacheability. The foundation of functional programming. React components and Redux reducers should be pure functions.',
  },
  {
    id: 'pat-026',
    difficulty: 'MEDIUM',
    order: 26,
    tags: ['clean-code', 'immutability'],
    questionRu: 'Что такое иммутабельность и зачем она нужна в JS?',
    questionEn: 'What is immutability and why is it important in JS?',
    answerRu: 'Иммутабельность — данные не изменяются, вместо этого создаются новые. Преимущества: предсказуемость, простота отладки, безопасное сравнение по ссылке (React shouldComponentUpdate). Инструменты: spread оператор, map/filter вместо мутации, Object.freeze(). Immer позволяет писать мутирующий код производя иммутабельный результат.',
    answerEn: 'Immutability means data is never modified — new data is created instead. Benefits: predictability, easier debugging, safe reference comparisons (React shouldComponentUpdate). Tools: spread operator, map/filter instead of mutation, Object.freeze(). Immer lets you write mutating-style code while producing an immutable result.',
  },
  {
    id: 'pat-027',
    difficulty: 'EASY',
    order: 27,
    tags: ['clean-code', 'separation-of-concerns'],
    questionRu: 'Что такое разделение ответственности (Separation of Concerns)?',
    questionEn: 'What is Separation of Concerns (SoC)?',
    answerRu: 'SoC — разделение кода на части с минимальным пересечением ответственности. В frontend: логика данных (хуки/store) отдельно от UI (компоненты), стили отдельно от разметки, бизнес-логика отдельно от UI-логики. Слоистая архитектура: API layer → business logic → UI. Облегчает тестирование и поддержку.',
    answerEn: 'SoC means splitting code into parts with minimal overlap of responsibilities. In frontend: data logic (hooks/store) separate from UI (components), styles separate from markup, business logic separate from UI logic. Layered architecture: API layer → business logic → UI. Makes testing and maintenance easier.',
  },
  {
    id: 'pat-028',
    difficulty: 'MEDIUM',
    order: 28,
    tags: ['clean-code', 'composition', 'inheritance'],
    questionRu: 'Что такое composition over inheritance?',
    questionEn: 'What is composition over inheritance?',
    answerRu: 'Предпочитать композицию (объединение объектов) наследованию (is-a). Наследование создаёт жёсткую иерархию, сложно изменить. Композиция гибче — можно комбинировать поведение. В React: HOC и хуки вместо class inheritance. Mixins как альтернатива. Паттерны: Strategy, Decorator реализуют принцип. Gang of Four рекомендовали в 1994.',
    answerEn: 'Prefer composition (combining objects) over inheritance (is-a relationships). Inheritance creates rigid hierarchies that are hard to change. Composition is more flexible — behavior can be mixed freely. In React: HOC and hooks instead of class inheritance. Mixins as an alternative. Strategy and Decorator patterns implement this principle. Recommended by the Gang of Four in 1994.',
  },
  {
    id: 'pat-029',
    difficulty: 'MEDIUM',
    order: 29,
    tags: ['clean-code', 'law-of-demeter'],
    questionRu: 'Что такое Law of Demeter (принцип наименьшего знания)?',
    questionEn: 'What is the Law of Demeter (Principle of Least Knowledge)?',
    answerRu: 'Law of Demeter: объект должен взаимодействовать только с ближайшими соседями, не с внутренностями их зависимостей. Антипаттерн: user.getAddress().getCity().getName(). Нарушение — знание о трёх уровнях. Решение: user.getCityName(). В компонентах: не передавать весь объект если нужно одно поле — передавать конкретное значение.',
    answerEn: 'Law of Demeter: an object should only interact with its immediate neighbors, not with the internals of their dependencies. Anti-pattern: user.getAddress().getCity().getName() — a violation involving knowledge of three levels. Solution: user.getCityName(). In components: do not pass the entire object when only one field is needed — pass the specific value.',
  },
];
