import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'pat-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['solid', 'srp'],
    questionRu: 'Что такое принцип единственной ответственности (SRP)?',
    questionEn: 'What is the Single Responsibility Principle (SRP)?',
    answerRu: '**SRP** (**Single Responsibility Principle**): класс/модуль/функция должны иметь только одну причину для изменения. Один компонент — одна задача.\n\n**Нарушение:** компонент одновременно загружает данные, валидирует и рендерит.\n\n**Решение:** разделить на:\n- хук для данных\n- утилиту для валидации\n- компонент для рендеринга',
    answerEn: '**SRP** (**Single Responsibility Principle**): a class/module/function should have only one reason to change. One component — one job.\n\n**Violation:** a component simultaneously fetches data, validates, and renders.\n\n**Solution:** split into:\n- a hook for data\n- a utility for validation\n- a component for rendering',
  },
  {
    id: 'pat-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['solid', 'ocp'],
    questionRu: 'Что такое принцип открытости/закрытости (OCP)?',
    questionEn: 'What is the Open/Closed Principle (OCP)?',
    answerRu: '**OCP** (**Open/Closed Principle**): код открыт для расширения, закрыт для изменения. Добавлять новое поведение без изменения существующего кода.\n\n**Пример:** компонент `Button` принимает `variant` prop вместо условий внутри.\n\nПаттерны `Strategy` и `Decorator` реализуют **OCP**.\n\n**В React:** composition и render props вместо `if/else` внутри компонента.',
    answerEn: '**OCP** (**Open/Closed Principle**): code is open for extension, closed for modification. Add new behavior without changing existing code.\n\n**Example:** a `Button` component accepts a `variant` prop instead of conditions inside.\n\nThe `Strategy` and `Decorator` patterns implement **OCP**.\n\n**In React:** composition and render props instead of `if/else` inside the component.',
  },
  {
    id: 'pat-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['solid', 'lsp'],
    questionRu: 'Что такое принцип подстановки Лисков (LSP)?',
    questionEn: 'What is the Liskov Substitution Principle (LSP)?',
    answerRu: '**LSP** (**Liskov Substitution Principle**): объекты подкласса должны заменять объекты базового класса без нарушения корректности.\n\nПодкласс не должен ужесточать **preconditions** или ослаблять **postconditions**.\n\n**Нарушение:** `Button` расширяет `Input`, но не поддерживает `onChange`.\n\n**В TypeScript:** если подтип сужает union — нарушение LSP.',
    answerEn: '**LSP** (**Liskov Substitution Principle**): subclass objects must be substitutable for base class objects without breaking correctness.\n\nA subclass must not strengthen **preconditions** or weaken **postconditions**.\n\n**Violation:** `Button` extends `Input` but does not support `onChange`.\n\n**In TypeScript:** if a subtype narrows a union — that is an LSP violation.',
  },
  {
    id: 'pat-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['solid', 'isp'],
    questionRu: 'Что такое принцип разделения интерфейсов (ISP)?',
    questionEn: 'What is the Interface Segregation Principle (ISP)?',
    answerRu: '**ISP** (**Interface Segregation Principle**): не заставлять клиента зависеть от методов, которые он не использует. Лучше много маленьких специализированных интерфейсов, чем один большой.\n\n**В TypeScript:** разделить большой интерфейс `User` на `Identifiable`, `Authenticatable`, `Profileable`.\n\n**В React:** не передавать весь объект, если нужно одно поле.',
    answerEn: '**ISP** (**Interface Segregation Principle**): do not force a client to depend on methods it does not use. Many small, specialized interfaces are better than one large one.\n\n**In TypeScript:** split a large `User` interface into `Identifiable`, `Authenticatable`, `Profileable`.\n\n**In React:** do not pass the entire object when only one field is needed.',
  },
  {
    id: 'pat-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['solid', 'dip'],
    questionRu: 'Что такое принцип инверсии зависимостей (DIP)?',
    questionEn: 'What is the Dependency Inversion Principle (DIP)?',
    answerRu: '**DIP** (**Dependency Inversion Principle**): модули верхнего уровня не должны зависеть от модулей нижнего — оба должны зависеть от **абстракций**. Высокоуровневый код не знает о конкретной реализации.\n\n**В React:** компонент принимает `fetchUser` как prop вместо прямого вызова API.\n\n**Dependency Injection** через контекст или props.',
    answerEn: '**DIP** (**Dependency Inversion Principle**): high-level modules must not depend on low-level modules — both should depend on **abstractions**. High-level code does not know about the concrete implementation.\n\n**In React:** a component receives `fetchUser` as a prop instead of calling the API directly.\n\n**Dependency Injection** via context or props.',
  },
  {
    id: 'pat-006',
    difficulty: 'EASY',
    order: 6,
    tags: ['dry', 'kiss', 'yagni', 'principles'],
    questionRu: 'Что такое DRY, KISS и YAGNI?',
    questionEn: 'What are DRY, KISS, and YAGNI?',
    answerRu: "- **DRY** (**Don't Repeat Yourself**): не дублировать логику — выносить в функции/хуки/компоненты.\n- **KISS** (**Keep It Simple, Stupid**): простое решение лучше сложного — не усложнять без необходимости.\n- **YAGNI** (**You Aren't Gonna Need It**): не добавлять функциональность «на будущее» — реализовывать только то, что нужно сейчас.\n\nТри принципа дополняют **SOLID**.",
    answerEn: "- **DRY** (**Don't Repeat Yourself**): do not duplicate logic — extract it into functions/hooks/components.\n- **KISS** (**Keep It Simple, Stupid**): a simple solution is better than a complex one — don't over-engineer.\n- **YAGNI** (**You Aren't Gonna Need It**): don't add functionality \"for the future\" — implement only what is needed now.\n\nThese three principles complement **SOLID**.",
  },
  {
    id: 'pat-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['creational', 'singleton'],
    questionRu: 'Что такое паттерн Singleton?',
    questionEn: 'What is the Singleton pattern?',
    answerRu: '`Singleton` гарантирует **единственный экземпляр** класса с глобальной точкой доступа.\n\n**В JS:** модуль — уже singleton (кешируется).\n\n**Применение:**\n- конфигурация\n- логгер\n- connection pool\n\n**Минусы:** глобальное состояние усложняет тестирование, нарушает **SRP**.\n\n**В React:** `Context` как альтернатива `Singleton` для глобальных данных.',
    answerEn: '`Singleton` ensures a **single instance** of a class with a global access point.\n\n**In JS:** a module is already a singleton (it is cached).\n\n**Use cases:**\n- configuration\n- logger\n- connection pool\n\n**Downsides:** global state complicates testing and violates **SRP**.\n\n**In React:** `Context` as an alternative to `Singleton` for global data.',
  },
  {
    id: 'pat-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['creational', 'factory'],
    questionRu: 'Что такое паттерн Factory?',
    questionEn: 'What is the Factory pattern?',
    answerRu: '`Factory` инкапсулирует **создание объектов**.\n\n- **Простая фабрика:** функция, возвращающая разные объекты по параметру.\n- **Factory Method:** базовый класс определяет интерфейс создания, подклассы реализуют.\n- **Abstract Factory:** семейство связанных объектов.\n\n**В React:** компонент-фабрика возвращает разные компоненты по типу: `renderField(type)` → `<Input>` или `<Select>`.',
    answerEn: '`Factory` encapsulates **object creation**.\n\n- **Simple factory:** a function that returns different objects based on a parameter.\n- **Factory Method:** a base class defines the creation interface, subclasses implement it.\n- **Abstract Factory:** a family of related objects.\n\n**In React:** a factory component returns different components by type: `renderField(type)` → `<Input>` or `<Select>`.',
  },
  {
    id: 'pat-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['creational', 'builder'],
    questionRu: 'Что такое паттерн Builder?',
    questionEn: 'What is the Builder pattern?',
    answerRu: "`Builder` разделяет **конструирование** сложного объекта от его представления. Цепочка вызовов методов для пошаговой настройки.\n\n**Пример:** `QueryBuilder().select('*').from('users').where('id=1').build()`\n\n**В JS:** популярен как **Fluent Interface**.\n\n**Применение:**\n- конфигурация запросов\n- создание сложных объектов с множеством опций",
    answerEn: "`Builder` separates the **construction** of a complex object from its representation. A chain of method calls for step-by-step configuration.\n\n**Example:** `QueryBuilder().select('*').from('users').where('id=1').build()`\n\n**In JS:** popular as a **Fluent Interface**.\n\n**Use cases:**\n- building query configurations\n- creating complex objects with many options",
  },
  {
    id: 'pat-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['creational', 'prototype'],
    questionRu: 'Что такое паттерн Prototype?',
    questionEn: 'What is the Prototype pattern?',
    answerRu: '`Prototype` создаёт объекты **клонированием** существующего. В JS прототипное наследование — нативный механизм.\n\n- `Object.create(proto)` — создать объект с прототипом.\n- `structuredClone()` — глубокое клонирование.\n- **Spread оператор** — поверхностное клонирование.\n\n**Применение:** когда создание объекта дороже клонирования, для шаблонных объектов.',
    answerEn: '`Prototype` creates objects by **cloning** an existing one. In JS, prototypal inheritance is a native mechanism.\n\n- `Object.create(proto)` — creates an object with a given prototype.\n- `structuredClone()` — deep cloning.\n- **Spread operator** — shallow cloning.\n\n**Use cases:** when creating an object is more expensive than cloning it, for template objects.',
  },
  {
    id: 'pat-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['creational', 'dependency-injection'],
    questionRu: 'Что такое паттерн Dependency Injection?',
    questionEn: 'What is the Dependency Injection pattern?',
    answerRu: '**DI** — передача зависимостей объекту **извне** вместо создания внутри. Улучшает тестируемость и следует **DIP**.\n\n**В React:**\n- через props — явный DI\n- через `Context` — неявный DI\n\n**Пример:** компонент получает `fetchData` как prop — в тестах передаётся mock, в продакшне — реальный API.\n\n**Инверсия контроля** делает код модульным.',
    answerEn: '**DI** means passing dependencies to an object **from the outside** instead of creating them internally. It improves testability and follows **DIP**.\n\n**In React:**\n- via props — explicit DI\n- via `Context` — implicit DI\n\n**Example:** a component receives `fetchData` as a prop — in tests a mock is passed, in production the real API is used.\n\n**Inversion of control** makes code modular.',
  },
  {
    id: 'pat-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['structural', 'decorator', 'hoc'],
    questionRu: 'Что такое паттерн Decorator?',
    questionEn: 'What is the Decorator pattern?',
    answerRu: '`Decorator` динамически **добавляет поведение** объекту без изменения его класса.\n\n**В JS:**\n- функции-обёртки\n- HOC в React\n- декораторы TypeScript (`@Injectable`)\n\n**Пример:** `withAuth(Component)` добавляет проверку авторизации.\n\nТакже: pipe оператор в **RxJS**, middleware в **Express**.\n\nПредпочтительнее наследования для расширения функциональности.',
    answerEn: '`Decorator` dynamically **adds behavior** to an object without changing its class.\n\n**In JS:**\n- wrapper functions\n- HOC in React\n- TypeScript decorators (`@Injectable`)\n\n**Example:** `withAuth(Component)` adds an authorization check.\n\nAlso: the pipe operator in **RxJS**, middleware in **Express**.\n\nPreferred over inheritance for extending functionality.',
  },
  {
    id: 'pat-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['structural', 'adapter'],
    questionRu: 'Что такое паттерн Adapter?',
    questionEn: 'What is the Adapter pattern?',
    answerRu: '`Adapter` преобразует интерфейс класса в другой интерфейс, ожидаемый клиентом. Позволяет совместно работать **несовместимым классам**.\n\n**Применение в frontend:**\n- обёртка над сторонней библиотекой — если библиотека изменится, меняем только адаптер\n- нормализация API ответов к внутренней модели данных\n- интеграция легаси кода',
    answerEn: "`Adapter` converts a class's interface into another interface expected by the client. It allows **incompatible classes** to work together.\n\n**Frontend use cases:**\n- wrapping a third-party library — if the library changes, only the adapter needs to be updated\n- normalizing API responses to an internal data model\n- integrating legacy code",
  },
  {
    id: 'pat-014',
    difficulty: 'EASY',
    order: 14,
    tags: ['structural', 'facade'],
    questionRu: 'Что такое паттерн Facade?',
    questionEn: 'What is the Facade pattern?',
    answerRu: '`Facade` предоставляет **упрощённый интерфейс** к сложной подсистеме. Скрывает сложность, предоставляет удобное API.\n\n**Примеры:**\n- `jQuery` как фасад над DOM API\n- `axios` как фасад над `fetch`/`XMLHttpRequest`\n- хук `useAuth`, скрывающий детали работы с токенами\n\nЧасто используется для упрощения работы со сложными библиотеками.',
    answerEn: '`Facade` provides a **simplified interface** to a complex subsystem. It hides complexity and exposes a convenient API.\n\n**Examples:**\n- `jQuery` as a facade over the DOM API\n- `axios` as a facade over `fetch`/`XMLHttpRequest`\n- a `useAuth` hook that hides token management details\n\nCommonly used to simplify interaction with complex libraries.',
  },
  {
    id: 'pat-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['structural', 'proxy'],
    questionRu: 'Что такое паттерн Proxy?',
    questionEn: 'What is the Proxy pattern?',
    answerRu: '`Proxy` **контролирует доступ** к объекту: добавляет логику до/после обращения. `JS Proxy` — нативная реализация.\n\n**Применения:**\n- валидация\n- кеширование\n- логирование\n- lazy initialization\n- виртуальные прокси для тяжёлых объектов\n\n**Vue 3** реактивность основана на `Proxy`. **MobX** использует `Proxy` для наблюдения за изменениями.',
    answerEn: '`Proxy` **controls access** to an object: it adds logic before/after property access. The `JS Proxy` is a native implementation.\n\n**Use cases:**\n- validation\n- caching\n- logging\n- lazy initialization\n- virtual proxies for heavy objects\n\n**Vue 3** reactivity is built on `Proxy`. **MobX** uses `Proxy` to observe changes.',
  },
  {
    id: 'pat-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['structural', 'composite'],
    questionRu: 'Что такое паттерн Composite?',
    questionEn: 'What is the Composite pattern?',
    answerRu: '`Composite` позволяет работать с **группой объектов** как с единым объектом. Дерево компонентов: листья и контейнеры реализуют один интерфейс.\n\nДерево компонентов React — пример `Composite`.\n\n**Применение:**\n- файловая система (файл и папка)\n- UI компоненты (`Button` и `Form` оба рендерятся)\n- DOM дерево',
    answerEn: '`Composite` allows treating a **group of objects** as a single object. A component tree: leaves and containers implement the same interface.\n\nThe React component tree is an example of `Composite`.\n\n**Use cases:**\n- file systems (file and folder)\n- UI components (`Button` and `Form` both render)\n- the DOM tree',
  },
  {
    id: 'pat-017',
    difficulty: 'HARD',
    order: 17,
    tags: ['structural', 'flyweight'],
    questionRu: 'Что такое паттерн Flyweight?',
    questionEn: 'What is the Flyweight pattern?',
    answerRu: '`Flyweight` разделяет **общее состояние** между множеством мелких объектов, экономя память.\n\n- **Внутреннее состояние** (общее, неизменяемое) — хранится в flyweight.\n- **Внешнее состояние** — передаётся при вызове.\n\n**Применение:**\n- пулы объектов\n- кеширование иконок/изображений\n- виртуализация списков, где один компонент переиспользуется с разными данными',
    answerEn: '`Flyweight` shares **common state** among many fine-grained objects to save memory.\n\n- **Intrinsic state** (shared, immutable) — stored in the flyweight.\n- **Extrinsic state** — passed in at call time.\n\n**Use cases:**\n- object pools\n- caching icons/images\n- list virtualization where a single component is reused with different data',
  },
  {
    id: 'pat-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['behavioral', 'observer'],
    questionRu: 'Что такое паттерн Observer?',
    questionEn: 'What is the Observer pattern?',
    answerRu: '`Observer`: объект (**subject**) уведомляет **подписчиков** об изменениях. Слабая связанность — subject не знает о конкретных observers.\n\n**В JS:** `EventEmitter`, `addEventListener`, `RxJS Observable`.\n\n**Redux store** — observer паттерн. `React useEffect` с зависимостями.\n\n**Применение:**\n- события\n- pub/sub системы\n- реактивность',
    answerEn: '`Observer`: an object (**subject**) notifies **subscribers** about changes. Loose coupling — the subject does not know about concrete observers.\n\n**In JS:** `EventEmitter`, `addEventListener`, `RxJS Observable`.\n\nThe **Redux store** is an observer pattern. `React useEffect` with dependencies.\n\n**Use cases:**\n- events\n- pub/sub systems\n- reactivity',
  },
  {
    id: 'pat-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['behavioral', 'strategy'],
    questionRu: 'Что такое паттерн Strategy?',
    questionEn: 'What is the Strategy pattern?',
    answerRu: '`Strategy` определяет семейство **алгоритмов**, инкапсулирует каждый и делает их взаимозаменяемыми. Выбор алгоритма в runtime.\n\n**Примеры:**\n- сортировка с разными компараторами\n- валидация с разными правилами\n- оплата разными способами\n\n**В JS:** передача функции как аргумент — уже паттерн `Strategy`. Реализует **OCP**.',
    answerEn: '`Strategy` defines a family of **algorithms**, encapsulates each one, and makes them interchangeable. The algorithm is selected at runtime.\n\n**Examples:**\n- sorting with different comparators\n- validation with different rules\n- payment with different methods\n\n**In JS:** passing a function as an argument is already the `Strategy` pattern. It implements **OCP**.',
  },
  {
    id: 'pat-020',
    difficulty: 'MEDIUM',
    order: 20,
    tags: ['behavioral', 'command'],
    questionRu: 'Что такое паттерн Command?',
    questionEn: 'What is the Command pattern?',
    answerRu: "`Command` инкапсулирует **запрос как объект**.\n\n**Возможности:**\n- откладывать выполнение\n- ставить в очередь\n- отменять (undo/redo)\n\n**Пример:** `{ type: 'ADD_TODO', payload: '...' }` в Redux — это команды.\n\n**Применение:**\n- undo/redo в текстовых редакторах\n- транзакции\n- логирование действий\n- история браузера `pushState`",
    answerEn: "`Command` encapsulates a **request as an object**.\n\n**This enables:**\n- deferred execution\n- queuing\n- undoing/redoing actions\n\n**Example:** `{ type: 'ADD_TODO', payload: '...' }` in Redux — these are commands.\n\n**Use cases:**\n- undo/redo in text editors\n- transactions\n- action logging\n- browser history `pushState`",
  },
  {
    id: 'pat-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['behavioral', 'mediator'],
    questionRu: 'Что такое паттерн Mediator?',
    questionEn: 'What is the Mediator pattern?',
    answerRu: '`Mediator` централизует **взаимодействие объектов** — они общаются через посредника, а не напрямую. Уменьшает связанность.\n\n**Примеры:**\n- `EventBus`/`EventEmitter` как медиатор между компонентами\n- **Redux store** как медиатор между частями приложения\n- чат-сервер, координирующий пользователей\n\n**React Context** как lightweight медиатор.',
    answerEn: '`Mediator` centralizes **object interactions** — objects communicate through a mediator instead of directly with each other. Reduces coupling.\n\n**Examples:**\n- `EventBus`/`EventEmitter` as a mediator between components\n- the **Redux store** as a mediator between parts of an application\n- a chat server coordinating users\n\n**React Context** as a lightweight mediator.',
  },
  {
    id: 'pat-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['behavioral', 'chain-of-responsibility'],
    questionRu: 'Что такое паттерн Chain of Responsibility?',
    questionEn: 'What is the Chain of Responsibility pattern?',
    answerRu: '`Chain of Responsibility` передаёт **запрос по цепочке** обработчиков — каждый решает обработать или передать дальше.\n\n**Примеры:**\n- middleware в Express (`next()`)\n- event bubbling в DOM\n- цепочка Redux middleware\n- Promise цепочка `.then()`\n\nПозволяет добавлять/убирать обработчики без изменения клиента.',
    answerEn: '`Chain of Responsibility` passes a **request along a chain** of handlers — each one decides whether to handle it or pass it on.\n\n**Examples:**\n- middleware in Express (`next()`)\n- event bubbling in the DOM\n- the Redux middleware chain\n- a Promise chain with `.then()`\n\nAllows adding or removing handlers without changing the client.',
  },
  {
    id: 'pat-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['behavioral', 'iterator'],
    questionRu: 'Что такое паттерн Iterator?',
    questionEn: 'What is the Iterator pattern?',
    answerRu: '`Iterator` предоставляет **последовательный доступ** к элементам коллекции без раскрытия её структуры.\n\n**В JS:** `Symbol.iterator` и протокол итерации. `for...of` работает с любым итерируемым.\n\n**Встроенные итерируемые:** `Array`, `Map`, `Set`, `String`.\n\n**Генераторы** — удобный способ создания итераторов и lazy вычисления для больших коллекций.',
    answerEn: '`Iterator` provides **sequential access** to elements of a collection without exposing its underlying structure.\n\n**In JS:** `Symbol.iterator` and the iteration protocol. `for...of` works with any iterable.\n\n**Built-in iterables:** `Array`, `Map`, `Set`, `String`.\n\n**Generators** are a convenient way to create iterators and enable lazy evaluation for large collections.',
  },
  {
    id: 'pat-024',
    difficulty: 'MEDIUM',
    order: 24,
    tags: ['behavioral', 'state', 'fsm'],
    questionRu: 'Что такое паттерн State?',
    questionEn: 'What is the State pattern?',
    answerRu: '`State` позволяет объекту **менять поведение** при изменении внутреннего состояния — объект как будто меняет класс. **Конечный автомат (FSM)**.\n\n**Примеры:**\n- UI компонент с состояниями `idle`/`loading`/`success`/`error`\n- светофор\n- медиаплеер\n\n**XState** — библиотека для явных конечных автоматов в JS. Предотвращает невалидные состояния.',
    answerEn: '`State` allows an object to **change its behavior** when its internal state changes — the object appears to change its class. **Finite State Machine (FSM)**.\n\n**Examples:**\n- a UI component with `idle`/`loading`/`success`/`error` states\n- a traffic light\n- a media player\n\n**XState** is a library for explicit state machines in JS. Prevents invalid states.',
  },
  {
    id: 'pat-025',
    difficulty: 'EASY',
    order: 25,
    tags: ['clean-code', 'pure-functions', 'fp'],
    questionRu: 'Что такое чистые функции и почему они важны?',
    questionEn: 'What are pure functions and why are they important?',
    answerRu: '**Чистая функция:** всегда возвращает одинаковый результат для одних аргументов (**детерминированность**) и не имеет **побочных эффектов**.\n\n**Преимущества:**\n- предсказуемость\n- тестируемость (не нужны моки)\n- кешируемость\n\nОснова **функционального программирования**. React компоненты и Redux reducers должны быть чистыми функциями.',
    answerEn: 'A **pure function** always returns the same result for the same arguments (**determinism**) and has no **side effects**.\n\n**Benefits:**\n- predictability\n- testability (no mocks needed)\n- cacheability\n\nThe foundation of **functional programming**. React components and Redux reducers should be pure functions.',
  },
  {
    id: 'pat-026',
    difficulty: 'MEDIUM',
    order: 26,
    tags: ['clean-code', 'immutability'],
    questionRu: 'Что такое иммутабельность и зачем она нужна в JS?',
    questionEn: 'What is immutability and why is it important in JS?',
    answerRu: '**Иммутабельность** — данные не изменяются, вместо этого создаются новые.\n\n**Преимущества:**\n- предсказуемость\n- простота отладки\n- безопасное сравнение по ссылке (React `shouldComponentUpdate`)\n\n**Инструменты:**\n- spread оператор\n- `map`/`filter` вместо мутации\n- `Object.freeze()`\n\n**Immer** позволяет писать мутирующий код, производя иммутабельный результат.',
    answerEn: '**Immutability** means data is never modified — new data is created instead.\n\n**Benefits:**\n- predictability\n- easier debugging\n- safe reference comparisons (React `shouldComponentUpdate`)\n\n**Tools:**\n- spread operator\n- `map`/`filter` instead of mutation\n- `Object.freeze()`\n\n**Immer** lets you write mutating-style code while producing an immutable result.',
  },
  {
    id: 'pat-027',
    difficulty: 'EASY',
    order: 27,
    tags: ['clean-code', 'separation-of-concerns'],
    questionRu: 'Что такое разделение ответственности (Separation of Concerns)?',
    questionEn: 'What is Separation of Concerns (SoC)?',
    answerRu: '**SoC** — разделение кода на части с минимальным пересечением ответственности.\n\n**В frontend:**\n- логика данных (хуки/store) отдельно от UI (компоненты)\n- стили отдельно от разметки\n- бизнес-логика отдельно от UI-логики\n\n**Слоистая архитектура:** API layer → business logic → UI.\n\nОблегчает тестирование и поддержку.',
    answerEn: '**SoC** means splitting code into parts with minimal overlap of responsibilities.\n\n**In frontend:**\n- data logic (hooks/store) separate from UI (components)\n- styles separate from markup\n- business logic separate from UI logic\n\n**Layered architecture:** API layer → business logic → UI.\n\nMakes testing and maintenance easier.',
  },
  {
    id: 'pat-028',
    difficulty: 'MEDIUM',
    order: 28,
    tags: ['clean-code', 'composition', 'inheritance'],
    questionRu: 'Что такое composition over inheritance?',
    questionEn: 'What is composition over inheritance?',
    answerRu: 'Предпочитать **композицию** (объединение объектов) **наследованию** (is-a). Наследование создаёт жёсткую иерархию, сложно изменить. Композиция гибче — можно комбинировать поведение.\n\n**В React:** HOC и хуки вместо class inheritance.\n\nПаттерны `Strategy` и `Decorator` реализуют этот принцип.\n\nРекомендовано **Gang of Four** в 1994.',
    answerEn: 'Prefer **composition** (combining objects) over **inheritance** (is-a relationships). Inheritance creates rigid hierarchies that are hard to change. Composition is more flexible — behavior can be mixed freely.\n\n**In React:** HOC and hooks instead of class inheritance.\n\nThe `Strategy` and `Decorator` patterns implement this principle.\n\nRecommended by the **Gang of Four** in 1994.',
  },
  {
    id: 'pat-029',
    difficulty: 'MEDIUM',
    order: 29,
    tags: ['clean-code', 'law-of-demeter'],
    questionRu: 'Что такое Law of Demeter (принцип наименьшего знания)?',
    questionEn: 'What is the Law of Demeter (Principle of Least Knowledge)?',
    answerRu: '**Law of Demeter:** объект должен взаимодействовать только с ближайшими соседями, не с внутренностями их зависимостей.\n\n**Антипаттерн:** `user.getAddress().getCity().getName()` — знание о трёх уровнях.\n\n**Решение:** `user.getCityName()`.\n\n**В компонентах:** не передавать весь объект, если нужно одно поле — передавать конкретное значение.',
    answerEn: '**Law of Demeter:** an object should only interact with its immediate neighbors, not with the internals of their dependencies.\n\n**Anti-pattern:** `user.getAddress().getCity().getName()` — a violation involving knowledge of three levels.\n\n**Solution:** `user.getCityName()`.\n\n**In components:** do not pass the entire object when only one field is needed — pass the specific value.',
  },
];
