import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'perf-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['metrics', 'cwv'],
    questionRu: 'Что такое Core Web Vitals и какие у них пороговые значения?',
    questionEn: 'What are Core Web Vitals and what are their threshold values?',
    answerRu: 'LCP (Largest Contentful Paint): загрузка главного контента — хорошо <2.5s, плохо >4s. INP (Interaction to Next Paint): отзывчивость на взаимодействие — хорошо <200ms, плохо >500ms. CLS (Cumulative Layout Shift): стабильность layout — хорошо <0.1, плохо >0.25. Влияют на SEO-ранжирование Google.',
    answerEn: 'LCP (Largest Contentful Paint): loading of the main content — good <2.5s, poor >4s. INP (Interaction to Next Paint): responsiveness to interactions — good <200ms, poor >500ms. CLS (Cumulative Layout Shift): layout stability — good <0.1, poor >0.25. They affect Google SEO ranking.',
  },
  {
    id: 'perf-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['metrics', 'ttfb', 'fcp', 'tti'],
    questionRu: 'Что такое TTFB, FCP и TTI?',
    questionEn: 'What are TTFB, FCP, and TTI?',
    answerRu: 'TTFB (Time to First Byte): время до первого байта от сервера — характеризует скорость сервера и сети. FCP (First Contentful Paint): первый видимый контент — текст или изображение. TTI (Time to Interactive): страница полностью интерактивна, main thread свободен. FCP хорошо <1.8s, TTI хорошо <3.8s.',
    answerEn: 'TTFB (Time to First Byte): time until the first byte from the server — characterizes server and network speed. FCP (First Contentful Paint): first visible content — text or image. TTI (Time to Interactive): the page is fully interactive and the main thread is free. FCP good <1.8s, TTI good <3.8s.',
  },
  {
    id: 'perf-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['metrics', 'devtools', 'performance-api'],
    questionRu: 'Как измерить производительность в браузере?',
    questionEn: 'How do you measure performance in the browser?',
    answerRu: 'Performance API: performance.now() для точного замера времени. PerformanceObserver для наблюдения за метриками. performance.getEntriesByType(\'navigation\') — timing навигации. web-vitals библиотека для CWV. Chrome DevTools: Lighthouse, Performance tab, Network tab. Real User Monitoring (RUM): собирать метрики с реальных пользователей.',
    answerEn: 'Performance API: performance.now() for precise time measurement. PerformanceObserver for observing metrics. performance.getEntriesByType(\'navigation\') — navigation timing. web-vitals library for CWV. Chrome DevTools: Lighthouse, Performance tab, Network tab. Real User Monitoring (RUM): collect metrics from real users.',
  },
  {
    id: 'perf-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['metrics', 'long-tasks', 'main-thread'],
    questionRu: 'Что такое Long Tasks и почему они важны?',
    questionEn: 'What are Long Tasks and why do they matter?',
    answerRu: 'Long Task — задача на main thread дольше 50ms. Блокирует UI: пользователь не может кликать, скроллить, вводить текст. INP ухудшается. Обнаружение: PerformanceObserver с type \'longtask\', Chrome DevTools Performance tab (красные блоки). Решение: разбить на части через setTimeout/scheduler, Web Workers.',
    answerEn: 'A Long Task is a task on the main thread that takes longer than 50ms. It blocks the UI: users cannot click, scroll, or type. INP degrades. Detection: PerformanceObserver with type \'longtask\', Chrome DevTools Performance tab (red blocks). Solution: break into chunks using setTimeout/scheduler or Web Workers.',
  },
  {
    id: 'perf-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['metrics', 'cls', 'layout-shift'],
    questionRu: 'Что такое CLS и как его улучшить?',
    questionEn: 'What is CLS and how do you improve it?',
    answerRu: 'CLS — неожиданные сдвиги layout во время загрузки. Причины: изображения без размеров, динамически вставляемый контент, шрифты вызывающие FOUT. Решения: всегда задавать width/height у img, резервировать место для рекламы/embeds, font-display: optional или swap, skeleton экраны.',
    answerEn: 'CLS — unexpected layout shifts during page load. Causes: images without dimensions, dynamically injected content, fonts causing FOUT. Solutions: always set width/height on img elements, reserve space for ads/embeds, font-display: optional or swap, skeleton screens.',
  },
  {
    id: 'perf-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['metrics', 'rum', 'lab-data'],
    questionRu: 'В чём разница между lab data и field data?',
    questionEn: 'What is the difference between lab data and field data?',
    answerRu: 'Lab data (синтетические): замеры в контролируемых условиях — Lighthouse, WebPageTest. Воспроизводимые, подходят для разработки. Field data (реальные пользователи): Chrome UX Report, RUM. Отражают реальный опыт с разными устройствами и сетями. Google использует field data для ранжирования. Нужны оба подхода.',
    answerEn: 'Lab data (synthetic): measurements in controlled conditions — Lighthouse, WebPageTest. Reproducible, suitable for development. Field data (real users): Chrome UX Report, RUM. Reflects real-world experience across different devices and networks. Google uses field data for ranking. Both approaches are needed.',
  },
  {
    id: 'perf-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['loading', 'code-splitting', 'bundling'],
    questionRu: 'Что такое code splitting и как реализовать?',
    questionEn: 'What is code splitting and how do you implement it?',
    answerRu: 'Code splitting — разбивка JS бандла на части, загружаемые по требованию. Инструменты: webpack/Vite автоматически сплиттят динамические import(). React.lazy + Suspense для компонентов. Route-based splitting — разные чанки для каждого маршрута. Уменьшает начальный бандл и ускоряет TTI.',
    answerEn: 'Code splitting — breaking a JS bundle into smaller pieces that are loaded on demand. Tools: webpack/Vite automatically split dynamic import() calls. React.lazy + Suspense for components. Route-based splitting — separate chunks for each route. Reduces the initial bundle size and improves TTI.',
  },
  {
    id: 'perf-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['loading', 'tree-shaking', 'bundling'],
    questionRu: 'Что такое tree shaking?',
    questionEn: 'What is tree shaking?',
    answerRu: 'Tree shaking — удаление неиспользуемого кода при сборке. Работает с ES модулями (import/export) — статический анализ зависимостей. Webpack и Rollup/Vite поддерживают автоматически. Условия: ES modules (не CommonJS), sideEffects: false в package.json библиотеки. Значительно уменьшает размер бандла.',
    answerEn: 'Tree shaking — removal of unused code during the build. Works with ES modules (import/export) — static dependency analysis. Webpack and Rollup/Vite support it automatically. Requirements: ES modules (not CommonJS), sideEffects: false in the library\'s package.json. Significantly reduces bundle size.',
  },
  {
    id: 'perf-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['loading', 'images', 'lcp'],
    questionRu: 'Как оптимизировать изображения?',
    questionEn: 'How do you optimize images?',
    answerRu: 'Форматы: WebP/AVIF вместо JPEG/PNG — на 30-50% меньше. srcset для разных разрешений. loading="lazy" для изображений ниже fold. Правильные размеры — не грузить 2000px изображение для 200px блока. CDN с трансформацией. Для LCP изображения: preload, fetchpriority="high", не lazy loading.',
    answerEn: 'Formats: WebP/AVIF instead of JPEG/PNG — 30-50% smaller. srcset for different resolutions. loading="lazy" for below-the-fold images. Proper sizing — don\'t load a 2000px image for a 200px container. CDN with image transformation. For the LCP image: preload, fetchpriority="high", no lazy loading.',
  },
  {
    id: 'perf-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['loading', 'css', 'critical-css'],
    questionRu: 'Что такое Critical CSS и как его применять?',
    questionEn: 'What is Critical CSS and how do you use it?',
    answerRu: 'Critical CSS — минимальный набор стилей для отрисовки above-the-fold контента. Инлайнится в <style> в <head> — браузер рендерит без ожидания CSS файла. Остальные стили загружаются асинхронно через preload. Инструменты: critical, Critters (используется в Angular/Next.js). Улучшает FCP и LCP.',
    answerEn: 'Critical CSS — the minimal set of styles required to render above-the-fold content. It is inlined in a <style> tag in the <head> — the browser renders without waiting for an external CSS file. The remaining styles are loaded asynchronously via preload. Tools: critical, Critters (used in Angular/Next.js). Improves FCP and LCP.',
  },
  {
    id: 'perf-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['loading', 'fonts', 'cls'],
    questionRu: 'Как оптимизировать шрифты?',
    questionEn: 'How do you optimize fonts?',
    answerRu: 'font-display: swap — показывает системный шрифт пока загружается кастомный. optional — только если загрузился очень быстро, иначе системный. Preload критичных шрифтов: <link rel="preload" as="font">. Subset шрифтов — только нужные символы. self-hosted вместо Google Fonts — убирает внешний запрос.',
    answerEn: 'font-display: swap — shows the system font while the custom font loads. optional — uses the custom font only if it loads very quickly, otherwise falls back to the system font. Preload critical fonts: <link rel="preload" as="font">. Font subsetting — include only the needed characters. Self-hosted instead of Google Fonts — eliminates the external request.',
  },
  {
    id: 'perf-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['loading', 'compression', 'brotli', 'gzip'],
    questionRu: 'Что такое compression и какие алгоритмы используются?',
    questionEn: 'What is compression and which algorithms are used?',
    answerRu: 'Сжатие текстовых ресурсов (HTML, CSS, JS) на сервере: Gzip — старый стандарт, широкая поддержка. Brotli — современный, на 15-25% лучше Gzip, поддерживается всеми современными браузерами. Настраивается на уровне сервера/CDN. Content-Encoding: br/gzip в ответе. Бинарные форматы (изображения) не сжимать повторно.',
    answerEn: 'Compression of text resources (HTML, CSS, JS) on the server: Gzip — the old standard, widely supported. Brotli — modern, 15-25% better than Gzip, supported by all modern browsers. Configured at the server/CDN level. Content-Encoding: br/gzip in the response. Do not re-compress binary formats (images).',
  },
  {
    id: 'perf-013',
    difficulty: 'EASY',
    order: 13,
    tags: ['loading', 'cdn'],
    questionRu: 'Что такое CDN и как помогает производительности?',
    questionEn: 'What is a CDN and how does it help performance?',
    answerRu: 'CDN (Content Delivery Network) — распределённая сеть серверов по всему миру. Статические ресурсы отдаются с ближайшего к пользователю узла — снижает latency. Снимает нагрузку с origin сервера. Edge caching, HTTP/2 push, TLS termination на краю. Для динамического контента: Edge Functions (Cloudflare Workers, Vercel Edge).',
    answerEn: 'CDN (Content Delivery Network) — a distributed network of servers around the world. Static assets are served from the node closest to the user — reduces latency. Offloads traffic from the origin server. Edge caching, HTTP/2 push, TLS termination at the edge. For dynamic content: Edge Functions (Cloudflare Workers, Vercel Edge).',
  },
  {
    id: 'perf-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['rendering', 'layout-thrashing', 'dom'],
    questionRu: 'Как избежать layout thrashing?',
    questionEn: 'How do you avoid layout thrashing?',
    answerRu: 'Layout thrashing — чередование чтения и записи DOM-геометрии в цикле вызывает принудительный reflow на каждой итерации. Решение: батчить — сначала прочитать все offsetWidth/getBoundingClientRect, затем записать все изменения стилей. requestAnimationFrame для визуальных обновлений. FastDOM библиотека автоматизирует батчинг.',
    answerEn: 'Layout thrashing — alternating reads and writes of DOM geometry in a loop forces a reflow on every iteration. Solution: batch operations — first read all offsetWidth/getBoundingClientRect values, then write all style changes. Use requestAnimationFrame for visual updates. The FastDOM library automates batching.',
  },
  {
    id: 'perf-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['rendering', 'debounce', 'throttle'],
    questionRu: 'Что такое дебаунсинг и троттлинг?',
    questionEn: 'What are debouncing and throttling?',
    answerRu: 'Debounce: откладывает вызов до паузы в событиях — функция вызывается один раз после остановки. Для: поиска по вводу, resize. Throttle: ограничивает частоту вызовов — не чаще раз в N мс. Для: scroll, mousemove. Debounce — ждёт тишины. Throttle — ограничивает частоту. Оба предотвращают избыточные вычисления.',
    answerEn: 'Debounce: delays the call until a pause in events — the function fires once after activity stops. Use for: search input, resize. Throttle: limits the call rate — no more than once every N ms. Use for: scroll, mousemove. Debounce waits for silence. Throttle limits frequency. Both prevent excessive computation.',
  },
  {
    id: 'perf-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['rendering', 'virtualization', 'lists'],
    questionRu: 'Что такое виртуализация списков и когда нужна?',
    questionEn: 'What is list virtualization and when is it needed?',
    answerRu: 'Виртуализация — рендерит только видимые элементы списка. 10000 строк в DOM → тормоза и память. Виртуализация рендерит ~20 видимых + небольшой буфер. Библиотеки: react-window, TanStack Virtual. Нужна при: >100-200 элементов в списке, особенно с тяжёлым содержимым. Без виртуализации scroll и память деградируют.',
    answerEn: 'Virtualization — renders only the visible items in a list. 10,000 rows in the DOM → slow scrolling and high memory usage. Virtualization renders ~20 visible items + a small buffer. Libraries: react-window, TanStack Virtual. Needed when: >100-200 items in a list, especially with heavy content. Without virtualization, scroll performance and memory degrade.',
  },
  {
    id: 'perf-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['rendering', 'web-workers', 'multithreading'],
    questionRu: 'Как использовать Web Workers для оптимизации?',
    questionEn: 'How do you use Web Workers for optimization?',
    answerRu: 'Web Workers выполняют тяжёлые вычисления в отдельном потоке, не блокируя main thread. Использовать для: парсинга больших JSON, шифрования, обработки изображений, сложных вычислений. Comlink библиотека упрощает работу с Workers. Ограничение: нет доступа к DOM — только передача данных через postMessage.',
    answerEn: 'Web Workers run heavy computations in a separate thread without blocking the main thread. Use them for: parsing large JSON, encryption, image processing, complex calculations. The Comlink library simplifies working with Workers. Limitation: no DOM access — data is exchanged only via postMessage.',
  },
  {
    id: 'perf-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['rendering', 'memoization', 'react'],
    questionRu: 'Что такое мемоизация и когда применять?',
    questionEn: 'What is memoization and when should you use it?',
    answerRu: 'Мемоизация — кеширование результата функции по аргументам. В JS: useMemo, useCallback в React, lodash.memoize. Применять когда: вычисление дорогое, аргументы часто повторяются. Не применять везде — сравнение аргументов тоже стоит времени и памяти. Сначала профилировать, потом оптимизировать.',
    answerEn: 'Memoization — caching a function\'s result based on its arguments. In JS: useMemo, useCallback in React, lodash.memoize. Use when: the computation is expensive and the same arguments repeat often. Don\'t use it everywhere — comparing arguments also has a time and memory cost. Profile first, then optimize.',
  },
  {
    id: 'perf-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['rendering', 'css', 'animation'],
    questionRu: 'Как оптимизировать CSS для производительности?',
    questionEn: 'How do you optimize CSS for performance?',
    answerRu: 'Избегать дорогих селекторов (глубокая вложенность, универсальный *). Анимировать только transform и opacity — GPU compositing без reflow. will-change: transform для заранее известных анимаций. Избегать @import в CSS — последовательная загрузка. Минификация и удаление неиспользуемого CSS (PurgeCSS).',
    answerEn: 'Avoid expensive selectors (deep nesting, universal *). Animate only transform and opacity — GPU compositing with no reflow. will-change: transform for animations known in advance. Avoid @import in CSS — it causes sequential loading. Minify and remove unused CSS (PurgeCSS).',
  },
  {
    id: 'perf-020',
    difficulty: 'HARD',
    order: 20,
    tags: ['rendering', 'css', 'containment'],
    questionRu: 'Что такое containment (contain) в CSS?',
    questionEn: 'What is CSS containment (contain)?',
    answerRu: 'contain сообщает браузеру что изменения внутри элемента не влияют на внешнее дерево. contain: layout — layout внутри изолирован. contain: paint — перерисовка ограничена. contain: strict = layout + paint + size. content-visibility: auto откладывает рендеринг off-screen элементов — значительно ускоряет длинные страницы.',
    answerEn: 'contain tells the browser that changes inside an element do not affect the outside tree. contain: layout — layout is isolated inside. contain: paint — repainting is scoped. contain: strict = layout + paint + size. content-visibility: auto defers rendering of off-screen elements — significantly speeds up long pages.',
  },
  {
    id: 'perf-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['tools', 'lighthouse'],
    questionRu: 'Как использовать Lighthouse для аудита производительности?',
    questionEn: 'How do you use Lighthouse for a performance audit?',
    answerRu: 'Lighthouse встроен в Chrome DevTools (вкладка Lighthouse) или CLI. Анализирует: Performance, Accessibility, Best Practices, SEO. Performance score 0-100 на основе CWV и других метрик. Показывает конкретные рекомендации с оценкой impact. Запускать в incognito без расширений. Важно: lab данные, не реальные пользователи.',
    answerEn: 'Lighthouse is built into Chrome DevTools (Lighthouse tab) or available as a CLI. It audits: Performance, Accessibility, Best Practices, SEO. Performance score 0-100 based on CWV and other metrics. Shows specific recommendations with impact estimates. Run in incognito mode without extensions. Important: lab data, not real users.',
  },
  {
    id: 'perf-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['tools', 'devtools', 'profiling'],
    questionRu: 'Как использовать Chrome DevTools Performance tab?',
    questionEn: 'How do you use the Chrome DevTools Performance tab?',
    answerRu: 'Record → воспроизвести действие → Stop. Анализ: Main thread timeline — видны Long Tasks (красные). Flame chart — стек вызовов во времени. Summary — время на scripting/rendering/painting. Bottom-Up/Call Tree — найти горячие функции. Network — waterfall загрузки ресурсов. FPS meter для анимаций.',
    answerEn: 'Record → reproduce the action → Stop. Analysis: Main thread timeline — Long Tasks are visible (red blocks). Flame chart — call stack over time. Summary — time spent on scripting/rendering/painting. Bottom-Up/Call Tree — identify hot functions. Network — resource loading waterfall. FPS meter for animations.',
  },
  {
    id: 'perf-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['tools', 'webpagetest'],
    questionRu: 'Что такое WebPageTest и чем отличается от Lighthouse?',
    questionEn: 'What is WebPageTest and how does it differ from Lighthouse?',
    answerRu: 'WebPageTest — онлайн инструмент для тестирования с реальных устройств и локаций по всему миру. Детальный waterfall, filmstrip (скриншоты по времени), connection view. Тест на медленных сетях (3G). В отличие от Lighthouse: реальные условия сети, тест из разных регионов, сравнение конкурентов. Более точные TTFB и загрузка ресурсов.',
    answerEn: 'WebPageTest — an online tool for testing from real devices and locations around the world. Detailed waterfall, filmstrip (screenshots over time), connection view. Testing on slow networks (3G). Unlike Lighthouse: real network conditions, testing from different regions, competitor comparison. More accurate TTFB and resource loading data.',
  },
];
