import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'perf-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['metrics', 'cwv'],
    questionRu: 'Что такое Core Web Vitals и какие у них пороговые значения?',
    questionEn: 'Что такое Core Web Vitals и какие у них пороговые значения?',
    answerRu: 'LCP (Largest Contentful Paint): загрузка главного контента — хорошо <2.5s, плохо >4s. INP (Interaction to Next Paint): отзывчивость на взаимодействие — хорошо <200ms, плохо >500ms. CLS (Cumulative Layout Shift): стабильность layout — хорошо <0.1, плохо >0.25. Влияют на SEO-ранжирование Google.',
    answerEn: 'LCP (Largest Contentful Paint): загрузка главного контента — хорошо <2.5s, плохо >4s. INP (Interaction to Next Paint): отзывчивость на взаимодействие — хорошо <200ms, плохо >500ms. CLS (Cumulative Layout Shift): стабильность layout — хорошо <0.1, плохо >0.25. Влияют на SEO-ранжирование Google.',
  },
  {
    id: 'perf-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['metrics', 'ttfb', 'fcp', 'tti'],
    questionRu: 'Что такое TTFB, FCP и TTI?',
    questionEn: 'Что такое TTFB, FCP и TTI?',
    answerRu: 'TTFB (Time to First Byte): время до первого байта от сервера — характеризует скорость сервера и сети. FCP (First Contentful Paint): первый видимый контент — текст или изображение. TTI (Time to Interactive): страница полностью интерактивна, main thread свободен. FCP хорошо <1.8s, TTI хорошо <3.8s.',
    answerEn: 'TTFB (Time to First Byte): время до первого байта от сервера — характеризует скорость сервера и сети. FCP (First Contentful Paint): первый видимый контент — текст или изображение. TTI (Time to Interactive): страница полностью интерактивна, main thread свободен. FCP хорошо <1.8s, TTI хорошо <3.8s.',
  },
  {
    id: 'perf-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['metrics', 'devtools', 'performance-api'],
    questionRu: 'Как измерить производительность в браузере?',
    questionEn: 'Как измерить производительность в браузере?',
    answerRu: 'Performance API: performance.now() для точного замера времени. PerformanceObserver для наблюдения за метриками. performance.getEntriesByType(\'navigation\') — timing навигации. web-vitals библиотека для CWV. Chrome DevTools: Lighthouse, Performance tab, Network tab. Real User Monitoring (RUM): собирать метрики с реальных пользователей.',
    answerEn: 'Performance API: performance.now() для точного замера времени. PerformanceObserver для наблюдения за метриками. performance.getEntriesByType(\'navigation\') — timing навигации. web-vitals библиотека для CWV. Chrome DevTools: Lighthouse, Performance tab, Network tab. Real User Monitoring (RUM): собирать метрики с реальных пользователей.',
  },
  {
    id: 'perf-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['metrics', 'long-tasks', 'main-thread'],
    questionRu: 'Что такое Long Tasks и почему они важны?',
    questionEn: 'Что такое Long Tasks и почему они важны?',
    answerRu: 'Long Task — задача на main thread дольше 50ms. Блокирует UI: пользователь не может кликать, скроллить, вводить текст. INP ухудшается. Обнаружение: PerformanceObserver с type \'longtask\', Chrome DevTools Performance tab (красные блоки). Решение: разбить на части через setTimeout/scheduler, Web Workers.',
    answerEn: 'Long Task — задача на main thread дольше 50ms. Блокирует UI: пользователь не может кликать, скроллить, вводить текст. INP ухудшается. Обнаружение: PerformanceObserver с type \'longtask\', Chrome DevTools Performance tab (красные блоки). Решение: разбить на части через setTimeout/scheduler, Web Workers.',
  },
  {
    id: 'perf-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['metrics', 'cls', 'layout-shift'],
    questionRu: 'Что такое CLS и как его улучшить?',
    questionEn: 'Что такое CLS и как его улучшить?',
    answerRu: 'CLS — неожиданные сдвиги layout во время загрузки. Причины: изображения без размеров, динамически вставляемый контент, шрифты вызывающие FOUT. Решения: всегда задавать width/height у img, резервировать место для рекламы/embeds, font-display: optional или swap, skeleton экраны.',
    answerEn: 'CLS — неожиданные сдвиги layout во время загрузки. Причины: изображения без размеров, динамически вставляемый контент, шрифты вызывающие FOUT. Решения: всегда задавать width/height у img, резервировать место для рекламы/embeds, font-display: optional или swap, skeleton экраны.',
  },
  {
    id: 'perf-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['metrics', 'rum', 'lab-data'],
    questionRu: 'В чём разница между lab data и field data?',
    questionEn: 'В чём разница между lab data и field data?',
    answerRu: 'Lab data (синтетические): замеры в контролируемых условиях — Lighthouse, WebPageTest. Воспроизводимые, подходят для разработки. Field data (реальные пользователи): Chrome UX Report, RUM. Отражают реальный опыт с разными устройствами и сетями. Google использует field data для ранжирования. Нужны оба подхода.',
    answerEn: 'Lab data (синтетические): замеры в контролируемых условиях — Lighthouse, WebPageTest. Воспроизводимые, подходят для разработки. Field data (реальные пользователи): Chrome UX Report, RUM. Отражают реальный опыт с разными устройствами и сетями. Google использует field data для ранжирования. Нужны оба подхода.',
  },
  {
    id: 'perf-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['loading', 'code-splitting', 'bundling'],
    questionRu: 'Что такое code splitting и как реализовать?',
    questionEn: 'Что такое code splitting и как реализовать?',
    answerRu: 'Code splitting — разбивка JS бандла на части, загружаемые по требованию. Инструменты: webpack/Vite автоматически сплиттят динамические import(). React.lazy + Suspense для компонентов. Route-based splitting — разные чанки для каждого маршрута. Уменьшает начальный бандл и ускоряет TTI.',
    answerEn: 'Code splitting — разбивка JS бандла на части, загружаемые по требованию. Инструменты: webpack/Vite автоматически сплиттят динамические import(). React.lazy + Suspense для компонентов. Route-based splitting — разные чанки для каждого маршрута. Уменьшает начальный бандл и ускоряет TTI.',
  },
  {
    id: 'perf-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['loading', 'tree-shaking', 'bundling'],
    questionRu: 'Что такое tree shaking?',
    questionEn: 'Что такое tree shaking?',
    answerRu: 'Tree shaking — удаление неиспользуемого кода при сборке. Работает с ES модулями (import/export) — статический анализ зависимостей. Webpack и Rollup/Vite поддерживают автоматически. Условия: ES modules (не CommonJS), sideEffects: false в package.json библиотеки. Значительно уменьшает размер бандла.',
    answerEn: 'Tree shaking — удаление неиспользуемого кода при сборке. Работает с ES модулями (import/export) — статический анализ зависимостей. Webpack и Rollup/Vite поддерживают автоматически. Условия: ES modules (не CommonJS), sideEffects: false в package.json библиотеки. Значительно уменьшает размер бандла.',
  },
  {
    id: 'perf-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['loading', 'images', 'lcp'],
    questionRu: 'Как оптимизировать изображения?',
    questionEn: 'Как оптимизировать изображения?',
    answerRu: 'Форматы: WebP/AVIF вместо JPEG/PNG — на 30-50% меньше. srcset для разных разрешений. loading="lazy" для изображений ниже fold. Правильные размеры — не грузить 2000px изображение для 200px блока. CDN с трансформацией. Для LCP изображения: preload, fetchpriority="high", не lazy loading.',
    answerEn: 'Форматы: WebP/AVIF вместо JPEG/PNG — на 30-50% меньше. srcset для разных разрешений. loading="lazy" для изображений ниже fold. Правильные размеры — не грузить 2000px изображение для 200px блока. CDN с трансформацией. Для LCP изображения: preload, fetchpriority="high", не lazy loading.',
  },
  {
    id: 'perf-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['loading', 'css', 'critical-css'],
    questionRu: 'Что такое Critical CSS и как его применять?',
    questionEn: 'Что такое Critical CSS и как его применять?',
    answerRu: 'Critical CSS — минимальный набор стилей для отрисовки above-the-fold контента. Инлайнится в <style> в <head> — браузер рендерит без ожидания CSS файла. Остальные стили загружаются асинхронно через preload. Инструменты: critical, Critters (используется в Angular/Next.js). Улучшает FCP и LCP.',
    answerEn: 'Critical CSS — минимальный набор стилей для отрисовки above-the-fold контента. Инлайнится в <style> в <head> — браузер рендерит без ожидания CSS файла. Остальные стили загружаются асинхронно через preload. Инструменты: critical, Critters (используется в Angular/Next.js). Улучшает FCP и LCP.',
  },
  {
    id: 'perf-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['loading', 'fonts', 'cls'],
    questionRu: 'Как оптимизировать шрифты?',
    questionEn: 'Как оптимизировать шрифты?',
    answerRu: 'font-display: swap — показывает системный шрифт пока загружается кастомный. optional — только если загрузился очень быстро, иначе системный. Preload критичных шрифтов: <link rel="preload" as="font">. Subset шрифтов — только нужные символы. self-hosted вместо Google Fonts — убирает внешний запрос.',
    answerEn: 'font-display: swap — показывает системный шрифт пока загружается кастомный. optional — только если загрузился очень быстро, иначе системный. Preload критичных шрифтов: <link rel="preload" as="font">. Subset шрифтов — только нужные символы. self-hosted вместо Google Fonts — убирает внешний запрос.',
  },
  {
    id: 'perf-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['loading', 'compression', 'brotli', 'gzip'],
    questionRu: 'Что такое compression и какие алгоритмы используются?',
    questionEn: 'Что такое compression и какие алгоритмы используются?',
    answerRu: 'Сжатие текстовых ресурсов (HTML, CSS, JS) на сервере: Gzip — старый стандарт, широкая поддержка. Brotli — современный, на 15-25% лучше Gzip, поддерживается всеми современными браузерами. Настраивается на уровне сервера/CDN. Content-Encoding: br/gzip в ответе. Бинарные форматы (изображения) не сжимать повторно.',
    answerEn: 'Сжатие текстовых ресурсов (HTML, CSS, JS) на сервере: Gzip — старый стандарт, широкая поддержка. Brotli — современный, на 15-25% лучше Gzip, поддерживается всеми современными браузерами. Настраивается на уровне сервера/CDN. Content-Encoding: br/gzip в ответе. Бинарные форматы (изображения) не сжимать повторно.',
  },
  {
    id: 'perf-013',
    difficulty: 'EASY',
    order: 13,
    tags: ['loading', 'cdn'],
    questionRu: 'Что такое CDN и как помогает производительности?',
    questionEn: 'Что такое CDN и как помогает производительности?',
    answerRu: 'CDN (Content Delivery Network) — распределённая сеть серверов по всему миру. Статические ресурсы отдаются с ближайшего к пользователю узла — снижает latency. Снимает нагрузку с origin сервера. Edge caching, HTTP/2 push, TLS termination на краю. Для динамического контента: Edge Functions (Cloudflare Workers, Vercel Edge).',
    answerEn: 'CDN (Content Delivery Network) — распределённая сеть серверов по всему миру. Статические ресурсы отдаются с ближайшего к пользователю узла — снижает latency. Снимает нагрузку с origin сервера. Edge caching, HTTP/2 push, TLS termination на краю. Для динамического контента: Edge Functions (Cloudflare Workers, Vercel Edge).',
  },
  {
    id: 'perf-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['rendering', 'layout-thrashing', 'dom'],
    questionRu: 'Как избежать layout thrashing?',
    questionEn: 'Как избежать layout thrashing?',
    answerRu: 'Layout thrashing — чередование чтения и записи DOM-геометрии в цикле вызывает принудительный reflow на каждой итерации. Решение: батчить — сначала прочитать все offsetWidth/getBoundingClientRect, затем записать все изменения стилей. requestAnimationFrame для визуальных обновлений. FastDOM библиотека автоматизирует батчинг.',
    answerEn: 'Layout thrashing — чередование чтения и записи DOM-геометрии в цикле вызывает принудительный reflow на каждой итерации. Решение: батчить — сначала прочитать все offsetWidth/getBoundingClientRect, затем записать все изменения стилей. requestAnimationFrame для визуальных обновлений. FastDOM библиотека автоматизирует батчинг.',
  },
  {
    id: 'perf-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['rendering', 'debounce', 'throttle'],
    questionRu: 'Что такое дебаунсинг и троттлинг?',
    questionEn: 'Что такое дебаунсинг и троттлинг?',
    answerRu: 'Debounce: откладывает вызов до паузы в событиях — функция вызывается один раз после остановки. Для: поиска по вводу, resize. Throttle: ограничивает частоту вызовов — не чаще раз в N мс. Для: scroll, mousemove. Debounce — ждёт тишины. Throttle — ограничивает частоту. Оба предотвращают избыточные вычисления.',
    answerEn: 'Debounce: откладывает вызов до паузы в событиях — функция вызывается один раз после остановки. Для: поиска по вводу, resize. Throttle: ограничивает частоту вызовов — не чаще раз в N мс. Для: scroll, mousemove. Debounce — ждёт тишины. Throttle — ограничивает частоту. Оба предотвращают избыточные вычисления.',
  },
  {
    id: 'perf-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['rendering', 'virtualization', 'lists'],
    questionRu: 'Что такое виртуализация списков и когда нужна?',
    questionEn: 'Что такое виртуализация списков и когда нужна?',
    answerRu: 'Виртуализация — рендерит только видимые элементы списка. 10000 строк в DOM → тормоза и память. Виртуализация рендерит ~20 видимых + небольшой буфер. Библиотеки: react-window, TanStack Virtual. Нужна при: >100-200 элементов в списке, особенно с тяжёлым содержимым. Без виртуализации scroll и память деградируют.',
    answerEn: 'Виртуализация — рендерит только видимые элементы списка. 10000 строк в DOM → тормоза и память. Виртуализация рендерит ~20 видимых + небольшой буфер. Библиотеки: react-window, TanStack Virtual. Нужна при: >100-200 элементов в списке, особенно с тяжёлым содержимым. Без виртуализации scroll и память деградируют.',
  },
  {
    id: 'perf-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['rendering', 'web-workers', 'multithreading'],
    questionRu: 'Как использовать Web Workers для оптимизации?',
    questionEn: 'Как использовать Web Workers для оптимизации?',
    answerRu: 'Web Workers выполняют тяжёлые вычисления в отдельном потоке, не блокируя main thread. Использовать для: парсинга больших JSON, шифрования, обработки изображений, сложных вычислений. Comlink библиотека упрощает работу с Workers. Ограничение: нет доступа к DOM — только передача данных через postMessage.',
    answerEn: 'Web Workers выполняют тяжёлые вычисления в отдельном потоке, не блокируя main thread. Использовать для: парсинга больших JSON, шифрования, обработки изображений, сложных вычислений. Comlink библиотека упрощает работу с Workers. Ограничение: нет доступа к DOM — только передача данных через postMessage.',
  },
  {
    id: 'perf-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['rendering', 'memoization', 'react'],
    questionRu: 'Что такое мемоизация и когда применять?',
    questionEn: 'Что такое мемоизация и когда применять?',
    answerRu: 'Мемоизация — кеширование результата функции по аргументам. В JS: useMemo, useCallback в React, lodash.memoize. Применять когда: вычисление дорогое, аргументы часто повторяются. Не применять везде — сравнение аргументов тоже стоит времени и памяти. Сначала профилировать, потом оптимизировать.',
    answerEn: 'Мемоизация — кеширование результата функции по аргументам. В JS: useMemo, useCallback в React, lodash.memoize. Применять когда: вычисление дорогое, аргументы часто повторяются. Не применять везде — сравнение аргументов тоже стоит времени и памяти. Сначала профилировать, потом оптимизировать.',
  },
  {
    id: 'perf-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['rendering', 'css', 'animation'],
    questionRu: 'Как оптимизировать CSS для производительности?',
    questionEn: 'Как оптимизировать CSS для производительности?',
    answerRu: 'Избегать дорогих селекторов (глубокая вложенность, универсальный *). Анимировать только transform и opacity — GPU compositing без reflow. will-change: transform для заранее известных анимаций. Избегать @import в CSS — последовательная загрузка. Минификация и удаление неиспользуемого CSS (PurgeCSS).',
    answerEn: 'Избегать дорогих селекторов (глубокая вложенность, универсальный *). Анимировать только transform и opacity — GPU compositing без reflow. will-change: transform для заранее известных анимаций. Избегать @import в CSS — последовательная загрузка. Минификация и удаление неиспользуемого CSS (PurgeCSS).',
  },
  {
    id: 'perf-020',
    difficulty: 'HARD',
    order: 20,
    tags: ['rendering', 'css', 'containment'],
    questionRu: 'Что такое containment (contain) в CSS?',
    questionEn: 'Что такое containment (contain) в CSS?',
    answerRu: 'contain сообщает браузеру что изменения внутри элемента не влияют на внешнее дерево. contain: layout — layout внутри изолирован. contain: paint — перерисовка ограничена. contain: strict = layout + paint + size. content-visibility: auto откладывает рендеринг off-screen элементов — значительно ускоряет длинные страницы.',
    answerEn: 'contain сообщает браузеру что изменения внутри элемента не влияют на внешнее дерево. contain: layout — layout внутри изолирован. contain: paint — перерисовка ограничена. contain: strict = layout + paint + size. content-visibility: auto откладывает рендеринг off-screen элементов — значительно ускоряет длинные страницы.',
  },
  {
    id: 'perf-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['tools', 'lighthouse'],
    questionRu: 'Как использовать Lighthouse для аудита производительности?',
    questionEn: 'Как использовать Lighthouse для аудита производительности?',
    answerRu: 'Lighthouse встроен в Chrome DevTools (вкладка Lighthouse) или CLI. Анализирует: Performance, Accessibility, Best Practices, SEO. Performance score 0-100 на основе CWV и других метрик. Показывает конкретные рекомендации с оценкой impact. Запускать в incognito без расширений. Важно: lab данные, не реальные пользователи.',
    answerEn: 'Lighthouse встроен в Chrome DevTools (вкладка Lighthouse) или CLI. Анализирует: Performance, Accessibility, Best Practices, SEO. Performance score 0-100 на основе CWV и других метрик. Показывает конкретные рекомендации с оценкой impact. Запускать в incognito без расширений. Важно: lab данные, не реальные пользователи.',
  },
  {
    id: 'perf-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['tools', 'devtools', 'profiling'],
    questionRu: 'Как использовать Chrome DevTools Performance tab?',
    questionEn: 'Как использовать Chrome DevTools Performance tab?',
    answerRu: 'Record → воспроизвести действие → Stop. Анализ: Main thread timeline — видны Long Tasks (красные). Flame chart — стек вызовов во времени. Summary — время на scripting/rendering/painting. Bottom-Up/Call Tree — найти горячие функции. Network — waterfall загрузки ресурсов. FPS meter для анимаций.',
    answerEn: 'Record → воспроизвести действие → Stop. Анализ: Main thread timeline — видны Long Tasks (красные). Flame chart — стек вызовов во времени. Summary — время на scripting/rendering/painting. Bottom-Up/Call Tree — найти горячие функции. Network — waterfall загрузки ресурсов. FPS meter для анимаций.',
  },
  {
    id: 'perf-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['tools', 'webpagetest'],
    questionRu: 'Что такое WebPageTest и чем отличается от Lighthouse?',
    questionEn: 'Что такое WebPageTest и чем отличается от Lighthouse?',
    answerRu: 'WebPageTest — онлайн инструмент для тестирования с реальных устройств и локаций по всему миру. Детальный waterfall, filmstrip (скриншоты по времени), connection view. Тест на медленных сетях (3G). В отличие от Lighthouse: реальные условия сети, тест из разных регионов, сравнение конкурентов. Более точные TTFB и загрузка ресурсов.',
    answerEn: 'WebPageTest — онлайн инструмент для тестирования с реальных устройств и локаций по всему миру. Детальный waterfall, filmstrip (скриншоты по времени), connection view. Тест на медленных сетях (3G). В отличие от Lighthouse: реальные условия сети, тест из разных регионов, сравнение конкурентов. Более точные TTFB и загрузка ресурсов.',
  },
];
