import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'react-001',
    difficulty: 'MEDIUM',
    questionRu: 'Когда использовать useCallback?',
    questionEn: 'When should you use useCallback?',
    answerRu: '**useCallback** мемоизирует функцию — возвращает ту же ссылку между рендерами, если зависимости не изменились.\n\n**Используй когда:**\n1. Функция передаётся в дочерний компонент, обёрнутый в `React.memo`\n2. Функция используется в зависимостях `useEffect`\n\n```jsx\n// Без useCallback — новая ссылка на каждый рендер\nconst handle = () => doSomething(id);\n\n// С useCallback — стабильная ссылка\nconst handle = useCallback(() => doSomething(id), [id]);\n```\n\n⚠️ Не оборачивай всё подряд — это добавляет overhead. Используй осознанно.',
    answerEn: '**useCallback** memoizes a function — returns the same reference between renders if dependencies haven\'t changed.\n\n**Use when:**\n1. The function is passed to a child component wrapped in `React.memo`\n2. The function is used in `useEffect` dependencies\n\n```jsx\n// Without useCallback — new reference every render\nconst handle = () => doSomething(id);\n\n// With useCallback — stable reference\nconst handle = useCallback(() => doSomething(id), [id]);\n```\n\n⚠️ Don\'t wrap everything — it adds overhead. Use intentionally.',
    tags: ['hooks', 'usecallback', 'performance', 'memoization'],
    order: 1,
  },
  {
    id: 'react-002',
    difficulty: 'HARD',
    questionRu: 'Как работает reconciliation в React?',
    questionEn: 'How does reconciliation work in React?',
    answerRu: 'Reconciliation — процесс, при котором React сравнивает новый Virtual DOM со старым (diffing) и применяет минимальный набор изменений к реальному DOM.\n\n**Алгоритм (heuristics):**\n1. Если тип элемента изменился — старое дерево уничтожается, создаётся новое\n2. Если тип тот же — обновляются только изменившиеся атрибуты\n3. **key** — помогает React отслеживать элементы в списках\n\n```jsx\n[\n  <Item key="a" />,\n  <Item key="b" />,\n]\n```\n\nReact 18 использует **Fiber** — структуру данных для прерываемого рендеринга (Concurrent Mode).',
    answerEn: 'Reconciliation is the process where React compares the new Virtual DOM to the old one (diffing) and applies the minimal set of changes to the real DOM.\n\n**Algorithm (heuristics):**\n1. If element type changed — old tree is destroyed, new one is created\n2. If type is same — only changed attributes are updated\n3. **key** — helps React track elements in lists\n\n```jsx\n[\n  <Item key="a" />,\n  <Item key="b" />,\n]\n```\n\nReact 18 uses **Fiber** — a data structure for interruptible rendering (Concurrent Mode).',
    tags: ['reconciliation', 'virtual-dom', 'diffing', 'fiber'],
    order: 2,
  },
  {
    id: 'react-003',
    difficulty: 'MEDIUM',
    questionRu: 'Что такое useEffect и как правильно им пользоваться?',
    questionEn: 'What is useEffect and how to use it correctly?',
    answerRu: '**useEffect** — хук для побочных эффектов: запросы к API, подписки, работа с DOM.\n\n```jsx\nuseEffect(() => {\n  // эффект\n  const sub = subscribe(id);\n\n  // cleanup — вызывается при размонтировании\n  // или перед следующим запуском эффекта\n  return () => sub.unsubscribe();\n}, [id]); // зависимости\n```\n\n**Варианты зависимостей:**\n- `[]` — только при монтировании\n- `[a, b]` — при изменении a или b\n- без массива — каждый рендер (⚠️ опасно)\n\n**Частые ошибки:**\n- Не указывать все зависимости\n- Делать async саму функцию useEffect (нельзя)',
    answerEn: '**useEffect** — hook for side effects: API requests, subscriptions, DOM manipulation.\n\n```jsx\nuseEffect(() => {\n  // effect\n  const sub = subscribe(id);\n\n  // cleanup — called on unmount\n  // or before the next effect run\n  return () => sub.unsubscribe();\n}, [id]); // dependencies\n```\n\n**Dependency options:**\n- `[]` — only on mount\n- `[a, b]` — when a or b change\n- no array — every render (⚠️ dangerous)\n\n**Common mistakes:**\n- Missing dependencies\n- Making the useEffect callback itself async (not allowed)',
    tags: ['hooks', 'useeffect', 'side-effects'],
    order: 3,
  },
  {
    id: 'react-004',
    difficulty: 'EASY',
    questionRu: 'Что такое React.memo и когда его использовать?',
    questionEn: 'What is React.memo and when to use it?',
    answerRu: '**React.memo** — HOC, который мемоизирует компонент. Пропускает ре-рендер если пропсы не изменились (shallow comparison).\n\n```jsx\nconst Button = React.memo(({ onClick, label }) => {\n  console.log("render");\n  return <button onClick={onClick}>{label}</button>;\n});\n\n// Компонент не перерендерится если onClick и label те же\n```\n\n**Используй когда:**\n- Компонент часто рендерится с теми же пропсами\n- Рендер дорогостоящий\n\n⚠️ Не использовать если:\n- Пропсы меняются почти каждый рендер\n- Компонент простой — overhead мемоизации больше выгоды',
    answerEn: '**React.memo** — HOC that memoizes a component. Skips re-render if props haven\'t changed (shallow comparison).\n\n```jsx\nconst Button = React.memo(({ onClick, label }) => {\n  console.log("render");\n  return <button onClick={onClick}>{label}</button>;\n});\n\n// Won\'t re-render if onClick and label are the same\n```\n\n**Use when:**\n- Component re-renders often with the same props\n- Render is expensive\n\n⚠️ Don\'t use when:\n- Props change almost every render\n- Component is simple — memoization overhead exceeds benefit',
    tags: ['memo', 'performance', 'hoc'],
    order: 4,
  },
  {
    id: 'react-005',
    difficulty: 'HARD',
    questionRu: 'В чём разница между useMemo и useCallback?',
    questionEn: 'What is the difference between useMemo and useCallback?',
    answerRu: 'Оба мемоизируют значение, но:\n\n**useCallback** — мемоизирует **функцию**\n```jsx\nconst fn = useCallback(() => compute(a, b), [a, b]);\n// fn — стабильная ссылка на функцию\n```\n\n**useMemo** — мемоизирует **результат** вычисления\n```jsx\nconst result = useMemo(() => compute(a, b), [a, b]);\n// result — кешированное значение\n```\n\nПо сути `useCallback(fn, deps)` === `useMemo(() => fn, deps)`\n\n**Когда useMemo:**\n- Дорогостоящие вычисления (сортировка, фильтрация)\n- Стабильная ссылка на объект/массив для зависимостей\n\n**Когда useCallback:**\n- Передача функции в React.memo компонент\n- Функция в deps useEffect',
    answerEn: 'Both memoize values, but:\n\n**useCallback** — memoizes a **function**\n```jsx\nconst fn = useCallback(() => compute(a, b), [a, b]);\n// fn — stable function reference\n```\n\n**useMemo** — memoizes a **computed result**\n```jsx\nconst result = useMemo(() => compute(a, b), [a, b]);\n// result — cached value\n```\n\nEssentially `useCallback(fn, deps)` === `useMemo(() => fn, deps)`\n\n**When useMemo:**\n- Expensive computations (sorting, filtering)\n- Stable reference for objects/arrays in dependencies\n\n**When useCallback:**\n- Passing function to React.memo component\n- Function in useEffect deps',
    tags: ['usememo', 'usecallback', 'performance', 'memoization'],
    order: 5,
  },
];
