import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'react-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['basics'],
    questionRu: 'Что такое React и в чём его ключевая идея?',
    questionEn: 'Что такое React и в чём его ключевая идея?',
    answerRu: 'React — библиотека для построения UI на основе компонентов. Ключевые идеи: декларативность (описываешь что отрендерить, не как), компонентный подход, однонаправленный поток данных. Virtual DOM минимизирует реальные DOM-операции через reconciliation.',
    answerEn: 'React — библиотека для построения UI на основе компонентов. Ключевые идеи: декларативность (описываешь что отрендерить, не как), компонентный подход, однонаправленный поток данных. Virtual DOM минимизирует реальные DOM-операции через reconciliation.',
  },
  {
    id: 'react-002',
    difficulty: 'EASY',
    order: 2,
    tags: ['basics'],
    questionRu: 'Что такое JSX и во что он компилируется?',
    questionEn: 'Что такое JSX и во что он компилируется?',
    answerRu: 'JSX — синтаксическое расширение JS, позволяет писать HTML-подобный код в JS. Компилируется в React.createElement(type, props, ...children). С React 17+ через новый JSX transform — в _jsx из react/jsx-runtime, без необходимости импортировать React.',
    answerEn: 'JSX — синтаксическое расширение JS, позволяет писать HTML-подобный код в JS. Компилируется в React.createElement(type, props, ...children). С React 17+ через новый JSX transform — в _jsx из react/jsx-runtime, без необходимости импортировать React.',
  },
  {
    id: 'react-003',
    difficulty: 'EASY',
    order: 3,
    tags: ['basics'],
    questionRu: 'В чём разница между props и state?',
    questionEn: 'В чём разница между props и state?',
    answerRu: 'props — данные, переданные извне компонента (только для чтения). state — внутреннее состояние компонента, управляемое им самим. Изменение state вызывает ре-рендер. props нельзя изменять внутри компонента — это нарушение однонаправленного потока данных.',
    answerEn: 'props — данные, переданные извне компонента (только для чтения). state — внутреннее состояние компонента, управляемое им самим. Изменение state вызывает ре-рендер. props нельзя изменять внутри компонента — это нарушение однонаправленного потока данных.',
  },
  {
    id: 'react-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['basics'],
    questionRu: 'Что такое controlled и uncontrolled компоненты?',
    questionEn: 'Что такое controlled и uncontrolled компоненты?',
    answerRu: 'Controlled: значение формы управляется React state через value + onChange. Данные всегда в sync с состоянием. Uncontrolled: данные хранятся в DOM, доступны через ref. Controlled предпочтительны — предсказуемы, легче валидировать. Uncontrolled для file input и интеграции с не-React кодом.',
    answerEn: 'Controlled: значение формы управляется React state через value + onChange. Данные всегда в sync с состоянием. Uncontrolled: данные хранятся в DOM, доступны через ref. Controlled предпочтительны — предсказуемы, легче валидировать. Uncontrolled для file input и интеграции с не-React кодом.',
  },
  {
    id: 'react-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['basics'],
    questionRu: 'Зачем нужен key в списках и как правильно его выбирать?',
    questionEn: 'Зачем нужен key в списках и как правильно его выбирать?',
    answerRu: 'key помогает React идентифицировать элементы при reconciliation — понять что изменилось, добавилось или удалилось. Должен быть уникальным среди siblings и стабильным. Нельзя использовать index если порядок может меняться — это ломает state и анимации. Лучший key — id из данных.',
    answerEn: 'key помогает React идентифицировать элементы при reconciliation — понять что изменилось, добавилось или удалилось. Должен быть уникальным среди siblings и стабильным. Нельзя использовать index если порядок может меняться — это ломает state и анимации. Лучший key — id из данных.',
  },
  {
    id: 'react-006',
    difficulty: 'EASY',
    order: 6,
    tags: ['basics'],
    questionRu: 'Что такое React.Fragment и зачем нужен?',
    questionEn: 'Что такое React.Fragment и зачем нужен?',
    answerRu: 'Fragment позволяет возвращать несколько элементов без лишнего DOM-узла. Синтаксис: <React.Fragment> или сокращённо <>...</>. Полная форма нужна когда требуется key: <React.Fragment key={id}>. Помогает избежать лишних div в разметке.',
    answerEn: 'Fragment позволяет возвращать несколько элементов без лишнего DOM-узла. Синтаксис: <React.Fragment> или сокращённо <>...</>. Полная форма нужна когда требуется key: <React.Fragment key={id}>. Помогает избежать лишних div в разметке.',
  },
  {
    id: 'react-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['basics'],
    questionRu: 'Что такое React reconciliation и Virtual DOM?',
    questionEn: 'Что такое React reconciliation и Virtual DOM?',
    answerRu: 'Virtual DOM — лёгкое JS-представление реального DOM. При изменении state React строит новый VDOM и сравнивает с предыдущим (diffing). Алгоритм reconciliation находит минимальный набор изменений и применяет их к реальному DOM. Ключи помогают алгоритму работать корректно.',
    answerEn: 'Virtual DOM — лёгкое JS-представление реального DOM. При изменении state React строит новый VDOM и сравнивает с предыдущим (diffing). Алгоритм reconciliation находит минимальный набор изменений и применяет их к реальному DOM. Ключи помогают алгоритму работать корректно.',
  },
  {
    id: 'react-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['hooks'],
    questionRu: 'Что такое хуки и какие правила их использования?',
    questionEn: 'Что такое хуки и какие правила их использования?',
    answerRu: 'Хуки — функции для использования state и других возможностей React в функциональных компонентах. Правила: 1) Вызывать только на верхнем уровне (не в условиях, циклах, вложенных функциях). 2) Вызывать только в React-компонентах или кастомных хуках. Порядок вызовов должен быть стабильным.',
    answerEn: 'Хуки — функции для использования state и других возможностей React в функциональных компонентах. Правила: 1) Вызывать только на верхнем уровне (не в условиях, циклах, вложенных функциях). 2) Вызывать только в React-компонентах или кастомных хуках. Порядок вызовов должен быть стабильным.',
  },
  {
    id: 'react-009',
    difficulty: 'EASY',
    order: 9,
    tags: ['hooks'],
    questionRu: 'Как работает useState?',
    questionEn: 'Как работает useState?',
    answerRu: 'useState(initialValue) возвращает [value, setter]. setter вызывает ре-рендер. Обновления батчатся (с React 18 — всегда, включая async). Для обновления на основе предыдущего значения: setState(prev => prev + 1). Начальное значение вычисляется только при первом рендере.',
    answerEn: 'useState(initialValue) возвращает [value, setter]. setter вызывает ре-рендер. Обновления батчатся (с React 18 — всегда, включая async). Для обновления на основе предыдущего значения: setState(prev => prev + 1). Начальное значение вычисляется только при первом рендере.',
  },
  {
    id: 'react-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['hooks'],
    questionRu: 'Как работает useEffect и каков его жизненный цикл?',
    questionEn: 'Как работает useEffect и каков его жизненный цикл?',
    answerRu: 'useEffect(fn, deps) запускает эффект после рендера. Без deps — после каждого рендера. [] — только после mount. [dep] — при изменении dep. Возвращаемая функция — cleanup (аналог componentWillUnmount). Порядок: рендер → обновление DOM → cleanup предыдущего эффекта → новый эффект.',
    answerEn: 'useEffect(fn, deps) запускает эффект после рендера. Без deps — после каждого рендера. [] — только после mount. [dep] — при изменении dep. Возвращаемая функция — cleanup (аналог componentWillUnmount). Порядок: рендер → обновление DOM → cleanup предыдущего эффекта → новый эффект.',
  },
  {
    id: 'react-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['hooks'],
    questionRu: 'В чём разница между useEffect и useLayoutEffect?',
    questionEn: 'В чём разница между useEffect и useLayoutEffect?',
    answerRu: 'useEffect: асинхронный, запускается после того как браузер отрисовал изменения. useLayoutEffect: синхронный, запускается после DOM-мутаций но до отрисовки браузером. useLayoutEffect для: измерения DOM, предотвращения мерцания. По умолчанию использовать useEffect.',
    answerEn: 'useEffect: асинхронный, запускается после того как браузер отрисовал изменения. useLayoutEffect: синхронный, запускается после DOM-мутаций но до отрисовки браузером. useLayoutEffect для: измерения DOM, предотвращения мерцания. По умолчанию использовать useEffect.',
  },
  {
    id: 'react-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['hooks'],
    questionRu: 'Как работает useRef?',
    questionEn: 'Как работает useRef?',
    answerRu: 'useRef возвращает мутируемый объект { current: value }. Два применения: 1) Доступ к DOM-элементу: ref={myRef}, затем myRef.current. 2) Хранение изменяемого значения между рендерами без вызова ре-рендера (аналог instance variable). Изменение .current не вызывает ре-рендер.',
    answerEn: 'useRef возвращает мутируемый объект { current: value }. Два применения: 1) Доступ к DOM-элементу: ref={myRef}, затем myRef.current. 2) Хранение изменяемого значения между рендерами без вызова ре-рендера (аналог instance variable). Изменение .current не вызывает ре-рендер.',
  },
  {
    id: 'react-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['hooks'],
    questionRu: 'Как работает useContext?',
    questionEn: 'Как работает useContext?',
    answerRu: 'useContext(MyContext) возвращает текущее значение контекста. Компонент ре-рендерится при каждом изменении значения контекста. Контекст создаётся через createContext(defaultValue). Provider оборачивает дерево: <MyContext.Provider value={...}>. Не заменяет state-менеджер для частых обновлений.',
    answerEn: 'useContext(MyContext) возвращает текущее значение контекста. Компонент ре-рендерится при каждом изменении значения контекста. Контекст создаётся через createContext(defaultValue). Provider оборачивает дерево: <MyContext.Provider value={...}>. Не заменяет state-менеджер для частых обновлений.',
  },
  {
    id: 'react-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['hooks'],
    questionRu: 'Как работает useReducer и когда предпочесть его useState?',
    questionEn: 'Как работает useReducer и когда предпочесть его useState?',
    answerRu: 'useReducer(reducer, initialState) возвращает [state, dispatch]. reducer(state, action) => newState. Предпочесть useReducer когда: сложная логика с несколькими sub-values, следующий state зависит от предыдущего, несколько связанных полей обновляются вместе.',
    answerEn: 'useReducer(reducer, initialState) возвращает [state, dispatch]. reducer(state, action) => newState. Предпочесть useReducer когда: сложная логика с несколькими sub-values, следующий state зависит от предыдущего, несколько связанных полей обновляются вместе.',
  },
  {
    id: 'react-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['hooks'],
    questionRu: 'Что такое useMemo и useCallback?',
    questionEn: 'Что такое useMemo и useCallback?',
    answerRu: 'useMemo(fn, deps) мемоизирует результат вычисления — пересчитывает только при изменении deps. useCallback(fn, deps) мемоизирует функцию — возвращает ту же ссылку при неизменных deps. Оба для оптимизации: предотвращают лишние вычисления и ре-рендеры дочерних компонентов.',
    answerEn: 'useMemo(fn, deps) мемоизирует результат вычисления — пересчитывает только при изменении deps. useCallback(fn, deps) мемоизирует функцию — возвращает ту же ссылку при неизменных deps. Оба для оптимизации: предотвращают лишние вычисления и ре-рендеры дочерних компонентов.',
  },
  {
    id: 'react-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['hooks'],
    questionRu: 'Что такое кастомный хук и как его создать?',
    questionEn: 'Что такое кастомный хук и как его создать?',
    answerRu: 'Кастомный хук — функция с именем начинающимся на use, которая может использовать другие хуки. Позволяет выносить и переиспользовать логику с состоянием. Пример: useFetch, useLocalStorage, useDebounce. Не шарит state между компонентами — каждый вызов создаёт изолированный state.',
    answerEn: 'Кастомный хук — функция с именем начинающимся на use, которая может использовать другие хуки. Позволяет выносить и переиспользовать логику с состоянием. Пример: useFetch, useLocalStorage, useDebounce. Не шарит state между компонентами — каждый вызов создаёт изолированный state.',
  },
  {
    id: 'react-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['hooks'],
    questionRu: 'Что такое useId и когда использовать?',
    questionEn: 'Что такое useId и когда использовать?',
    answerRu: 'useId (React 18) генерирует уникальный стабильный ID, одинаковый на сервере и клиенте — решает проблему гидрации. Использовать для связи label и input через htmlFor, aria-атрибутов. Не использовать для key в списках.',
    answerEn: 'useId (React 18) генерирует уникальный стабильный ID, одинаковый на сервере и клиенте — решает проблему гидрации. Использовать для связи label и input через htmlFor, aria-атрибутов. Не использовать для key в списках.',
  },
  {
    id: 'react-018',
    difficulty: 'HARD',
    order: 18,
    tags: ['hooks'],
    questionRu: 'Что такое useTransition и useDeferredValue?',
    questionEn: 'Что такое useTransition и useDeferredValue?',
    answerRu: 'useTransition (React 18) помечает обновление как некритичное — React может прерывать его для срочных обновлений. Возвращает [isPending, startTransition]. useDeferredValue откладывает обновление значения. Используются для: поиска, фильтрации больших списков — UI остаётся отзывчивым.',
    answerEn: 'useTransition (React 18) помечает обновление как некритичное — React может прерывать его для срочных обновлений. Возвращает [isPending, startTransition]. useDeferredValue откладывает обновление значения. Используются для: поиска, фильтрации больших списков — UI остаётся отзывчивым.',
  },
  {
    id: 'react-019',
    difficulty: 'HARD',
    order: 19,
    tags: ['hooks'],
    questionRu: 'Что такое useImperativeHandle?',
    questionEn: 'Что такое useImperativeHandle?',
    answerRu: 'useImperativeHandle(ref, () => ({ method }), deps) позволяет компоненту кастомизировать значение ref, доступное родителю через forwardRef. Используется для предоставления императивного API: focus(), scroll(), reset(). Антипаттерн если можно решить декларативно через props.',
    answerEn: 'useImperativeHandle(ref, () => ({ method }), deps) позволяет компоненту кастомизировать значение ref, доступное родителю через forwardRef. Используется для предоставления императивного API: focus(), scroll(), reset(). Антипаттерн если можно решить декларативно через props.',
  },
  {
    id: 'react-020',
    difficulty: 'EASY',
    order: 20,
    tags: ['state'],
    questionRu: 'Что такое lifting state up?',
    questionEn: 'Что такое lifting state up?',
    answerRu: 'Lifting state up — перемещение state в ближайшего общего предка компонентов, которым нужен доступ к нему. Компоненты получают данные и колбэки через props. Основной паттерн React для шаринга state между siblings.',
    answerEn: 'Lifting state up — перемещение state в ближайшего общего предка компонентов, которым нужен доступ к нему. Компоненты получают данные и колбэки через props. Основной паттерн React для шаринга state между siblings.',
  },
  {
    id: 'react-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['state'],
    questionRu: 'Что такое prop drilling и как его избежать?',
    questionEn: 'Что такое prop drilling и как его избежать?',
    answerRu: 'Prop drilling — передача props через несколько уровней компонентов, которые сами их не используют. Решения: Context API для глобальных данных (тема, локаль, пользователь), composition pattern (children/render props), внешний state-менеджер (Redux, Zustand).',
    answerEn: 'Prop drilling — передача props через несколько уровней компонентов, которые сами их не используют. Решения: Context API для глобальных данных (тема, локаль, пользователь), composition pattern (children/render props), внешний state-менеджер (Redux, Zustand).',
  },
  {
    id: 'react-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['state'],
    questionRu: 'Когда использовать Context, а когда внешний state-менеджер?',
    questionEn: 'Когда использовать Context, а когда внешний state-менеджер?',
    answerRu: 'Context хорош для: редко меняющихся данных (тема, локаль, авторизация), передачи данных глубоко в дерево. Внешний менеджер (Redux, Zustand, Jotai) нужен когда: частые обновления, сложная логика, нужны devtools, state шарится между несвязанными частями приложения.',
    answerEn: 'Context хорош для: редко меняющихся данных (тема, локаль, авторизация), передачи данных глубоко в дерево. Внешний менеджер (Redux, Zustand, Jotai) нужен когда: частые обновления, сложная логика, нужны devtools, state шарится между несвязанными частями приложения.',
  },
  {
    id: 'react-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['state'],
    questionRu: 'Как работает Redux?',
    questionEn: 'Как работает Redux?',
    answerRu: 'Redux: единый store, однонаправленный поток. Action → Reducer (чистая функция state + action = newState) → Store → View. Redux Toolkit упрощает: createSlice генерирует actions и reducer, createAsyncThunk для асинхронных действий. Middleware (thunk) для side effects.',
    answerEn: 'Redux: единый store, однонаправленный поток. Action → Reducer (чистая функция state + action = newState) → Store → View. Redux Toolkit упрощает: createSlice генерирует actions и reducer, createAsyncThunk для асинхронных действий. Middleware (thunk) для side effects.',
  },
  {
    id: 'react-024',
    difficulty: 'MEDIUM',
    order: 24,
    tags: ['state'],
    questionRu: 'Что такое Zustand и чем отличается от Redux?',
    questionEn: 'Что такое Zustand и чем отличается от Redux?',
    answerRu: 'Zustand — минималистичный state-менеджер. Проще: нет actions/reducers, store — просто объект с методами. Меньше бойлерплейта. Подписка на конкретные поля через selector предотвращает лишние ре-рендеры. Хорошо для средних приложений. Redux лучше для сложной логики и команд.',
    answerEn: 'Zustand — минималистичный state-менеджер. Проще: нет actions/reducers, store — просто объект с методами. Меньше бойлерплейта. Подписка на конкретные поля через selector предотвращает лишние ре-рендеры. Хорошо для средних приложений. Redux лучше для сложной логики и команд.',
  },
  {
    id: 'react-025',
    difficulty: 'MEDIUM',
    order: 25,
    tags: ['state'],
    questionRu: 'Что такое React Query (TanStack Query)?',
    questionEn: 'Что такое React Query (TanStack Query)?',
    answerRu: 'React Query — библиотека для управления серверным состоянием. Автоматически: кеширует запросы, обновляет при фокусе/переподключении, дедублирует параллельные запросы, управляет loading/error состоянием. Разделяет серверный state (React Query) и клиентский (Zustand/Redux).',
    answerEn: 'React Query — библиотека для управления серверным состоянием. Автоматически: кеширует запросы, обновляет при фокусе/переподключении, дедублирует параллельные запросы, управляет loading/error состоянием. Разделяет серверный state (React Query) и клиентский (Zustand/Redux).',
  },
  {
    id: 'react-026',
    difficulty: 'MEDIUM',
    order: 26,
    tags: ['state'],
    questionRu: 'Что такое серверный state vs клиентский state?',
    questionEn: 'Что такое серверный state vs клиентский state?',
    answerRu: 'Серверный state: данные с сервера — асинхронны, могут устареть, нужно кешировать и синхронизировать. Инструменты: React Query, SWR, RTK Query. Клиентский state: UI-state — модалки, фильтры, форма. Инструменты: useState, Zustand, Redux. Смешивание в одном store — антипаттерн.',
    answerEn: 'Серверный state: данные с сервера — асинхронны, могут устареть, нужно кешировать и синхронизировать. Инструменты: React Query, SWR, RTK Query. Клиентский state: UI-state — модалки, фильтры, форма. Инструменты: useState, Zustand, Redux. Смешивание в одном store — антипаттерн.',
  },
  {
    id: 'react-027',
    difficulty: 'HARD',
    order: 27,
    tags: ['state'],
    questionRu: 'Как избежать лишних ре-рендеров при использовании Context?',
    questionEn: 'Как избежать лишних ре-рендеров при использовании Context?',
    answerRu: 'Context ре-рендерит всех потребителей при изменении value. Решения: 1) Разделить контексты по частоте обновления. 2) Мемоизировать value через useMemo. 3) Разделить state и dispatch на разные контексты. 4) Использовать внешний state-менеджер с селекторами.',
    answerEn: 'Context ре-рендерит всех потребителей при изменении value. Решения: 1) Разделить контексты по частоте обновления. 2) Мемоизировать value через useMemo. 3) Разделить state и dispatch на разные контексты. 4) Использовать внешний state-менеджер с селекторами.',
  },
  {
    id: 'react-028',
    difficulty: 'MEDIUM',
    order: 28,
    tags: ['performance'],
    questionRu: 'Что такое React.memo и когда его использовать?',
    questionEn: 'Что такое React.memo и когда его использовать?',
    answerRu: 'React.memo — HOC, который мемоизирует компонент: пропускает ре-рендер если props не изменились (shallow comparison). Использовать когда: компонент рендерится часто с теми же props, рендер дорогой. Не использовать везде — сравнение тоже стоит памяти и времени.',
    answerEn: 'React.memo — HOC, который мемоизирует компонент: пропускает ре-рендер если props не изменились (shallow comparison). Использовать когда: компонент рендерится часто с теми же props, рендер дорогой. Не использовать везде — сравнение тоже стоит памяти и времени.',
  },
  {
    id: 'react-029',
    difficulty: 'MEDIUM',
    order: 29,
    tags: ['performance'],
    questionRu: 'В чём разница между useMemo и React.memo?',
    questionEn: 'В чём разница между useMemo и React.memo?',
    answerRu: 'React.memo — мемоизация компонента целиком (сравнивает props). useMemo — мемоизация значения внутри компонента (сравнивает deps). useCallback — мемоизация функции. React.memo бесполезен без useCallback/useMemo для функций-props, так как функции создаются заново каждый рендер.',
    answerEn: 'React.memo — мемоизация компонента целиком (сравнивает props). useMemo — мемоизация значения внутри компонента (сравнивает deps). useCallback — мемоизация функции. React.memo бесполезен без useCallback/useMemo для функций-props, так как функции создаются заново каждый рендер.',
  },
  {
    id: 'react-030',
    difficulty: 'MEDIUM',
    order: 30,
    tags: ['performance'],
    questionRu: 'Что такое code splitting и React.lazy?',
    questionEn: 'Что такое code splitting и React.lazy?',
    answerRu: 'Code splitting — разбивка бандла на части, загружаемые по требованию. React.lazy(() => import(\'./Component\')) — динамический импорт компонента. Обязательно оборачивать в Suspense с fallback. Позволяет уменьшить начальный бандл и ускорить загрузку.',
    answerEn: 'Code splitting — разбивка бандла на части, загружаемые по требованию. React.lazy(() => import(\'./Component\')) — динамический импорт компонента. Обязательно оборачивать в Suspense с fallback. Позволяет уменьшить начальный бандл и ускорить загрузку.',
  },
  {
    id: 'react-031',
    difficulty: 'MEDIUM',
    order: 31,
    tags: ['performance'],
    questionRu: 'Что такое виртуализация списков?',
    questionEn: 'Что такое виртуализация списков?',
    answerRu: 'Виртуализация — рендеринг только видимых элементов списка. Для 10000 строк в DOM рендерится только ~20 видимых. Библиотеки: react-window (легковесная), react-virtual (TanStack). Критично для: больших таблиц, бесконечных лент. Без виртуализации — тормоза и высокое потребление памяти.',
    answerEn: 'Виртуализация — рендеринг только видимых элементов списка. Для 10000 строк в DOM рендерится только ~20 видимых. Библиотеки: react-window (легковесная), react-virtual (TanStack). Критично для: больших таблиц, бесконечных лент. Без виртуализации — тормоза и высокое потребление памяти.',
  },
  {
    id: 'react-032',
    difficulty: 'MEDIUM',
    order: 32,
    tags: ['performance'],
    questionRu: 'Что такое batching в React 18?',
    questionEn: 'Что такое batching в React 18?',
    answerRu: 'Batching — группировка нескольких вызовов setState в один ре-рендер. В React 17 batching работал только в обработчиках событий. React 18 ввёл automatic batching — везде: async функции, setTimeout, промисы. Уменьшает количество ре-рендеров. Отключить: flushSync().',
    answerEn: 'Batching — группировка нескольких вызовов setState в один ре-рендер. В React 17 batching работал только в обработчиках событий. React 18 ввёл automatic batching — везде: async функции, setTimeout, промисы. Уменьшает количество ре-рендеров. Отключить: flushSync().',
  },
  {
    id: 'react-033',
    difficulty: 'MEDIUM',
    order: 33,
    tags: ['performance'],
    questionRu: 'Как профилировать производительность React-приложения?',
    questionEn: 'Как профилировать производительность React-приложения?',
    answerRu: 'Инструменты: React DevTools Profiler — записывает рендеры, показывает причину и длительность. why-did-you-render — логирует лишние ре-рендеры. Chrome Performance tab — общий профиль. Паттерн: сначала найти узкое место, потом оптимизировать (не преждевременно).',
    answerEn: 'Инструменты: React DevTools Profiler — записывает рендеры, показывает причину и длительность. why-did-you-render — логирует лишние ре-рендеры. Chrome Performance tab — общий профиль. Паттерн: сначала найти узкое место, потом оптимизировать (не преждевременно).',
  },
  {
    id: 'react-034',
    difficulty: 'HARD',
    order: 34,
    tags: ['performance'],
    questionRu: 'Что такое Concurrent Mode и React 18?',
    questionEn: 'Что такое Concurrent Mode и React 18?',
    answerRu: 'Concurrent Mode — React может прерывать, откладывать и возобновлять рендеринг. Позволяет UI оставаться отзывчивым при тяжёлых операциях. Основные возможности: автоматический batching, Suspense для данных, useTransition, useDeferredValue, Streaming SSR.',
    answerEn: 'Concurrent Mode — React может прерывать, откладывать и возобновлять рендеринг. Позволяет UI оставаться отзывчивым при тяжёлых операциях. Основные возможности: автоматический batching, Suspense для данных, useTransition, useDeferredValue, Streaming SSR.',
  },
  {
    id: 'react-035',
    difficulty: 'MEDIUM',
    order: 35,
    tags: ['patterns'],
    questionRu: 'Что такое HOC (Higher-Order Component)?',
    questionEn: 'Что такое HOC (Higher-Order Component)?',
    answerRu: 'HOC — функция, принимающая компонент и возвращающая новый компонент с расширенными возможностями. Пример: withAuth(Component), withTheme(Component). Сейчас часто заменяются хуками — они проще и без проблем с именованием и вложенностью. HOC актуальны для class-компонентов.',
    answerEn: 'HOC — функция, принимающая компонент и возвращающая новый компонент с расширенными возможностями. Пример: withAuth(Component), withTheme(Component). Сейчас часто заменяются хуками — они проще и без проблем с именованием и вложенностью. HOC актуальны для class-компонентов.',
  },
  {
    id: 'react-036',
    difficulty: 'MEDIUM',
    order: 36,
    tags: ['patterns'],
    questionRu: 'Что такое render props?',
    questionEn: 'Что такое render props?',
    answerRu: 'Render props — паттерн передачи функции как prop для контроля рендеринга: <DataProvider render={data => <View data={data}/>}/>. Позволяет переиспользовать логику с состоянием. Сейчас в основном заменён кастомными хуками, но встречается в библиотеках.',
    answerEn: 'Render props — паттерн передачи функции как prop для контроля рендеринга: <DataProvider render={data => <View data={data}/>}/>. Позволяет переиспользовать логику с состоянием. Сейчас в основном заменён кастомными хуками, но встречается в библиотеках.',
  },
  {
    id: 'react-037',
    difficulty: 'HARD',
    order: 37,
    tags: ['patterns'],
    questionRu: 'Что такое compound components?',
    questionEn: 'Что такое compound components?',
    answerRu: 'Compound components — группа компонентов, работающих вместе через общий state через Context. Пример: <Select><Select.Option value="1">One</Select.Option></Select>. Даёт гибкость в разметке при сокрытии внутренней логики. Используется в UI-библиотеках (Radix, Headless UI).',
    answerEn: 'Compound components — группа компонентов, работающих вместе через общий state через Context. Пример: <Select><Select.Option value="1">One</Select.Option></Select>. Даёт гибкость в разметке при сокрытии внутренней логики. Используется в UI-библиотеках (Radix, Headless UI).',
  },
  {
    id: 'react-038',
    difficulty: 'MEDIUM',
    order: 38,
    tags: ['patterns'],
    questionRu: 'Что такое Error Boundary?',
    questionEn: 'Что такое Error Boundary?',
    answerRu: 'Error Boundary — class-компонент с componentDidCatch и getDerivedStateFromError, перехватывающий JS-ошибки в дочерних компонентах и показывающий fallback UI. Хуки не поддерживают ErrorBoundary (пока нет useErrorBoundary нативно). Библиотека react-error-boundary упрощает использование.',
    answerEn: 'Error Boundary — class-компонент с componentDidCatch и getDerivedStateFromError, перехватывающий JS-ошибки в дочерних компонентах и показывающий fallback UI. Хуки не поддерживают ErrorBoundary (пока нет useErrorBoundary нативно). Библиотека react-error-boundary упрощает использование.',
  },
  {
    id: 'react-039',
    difficulty: 'MEDIUM',
    order: 39,
    tags: ['patterns'],
    questionRu: 'Что такое Portal?',
    questionEn: 'Что такое Portal?',
    answerRu: 'ReactDOM.createPortal(children, domNode) рендерит children в другой DOM-узел вне иерархии компонента (например, в document.body). События всплывают через React-дерево, не через DOM. Используется для: модальных окон, тултипов, дропдаунов — чтобы избежать проблем с overflow:hidden и z-index.',
    answerEn: 'ReactDOM.createPortal(children, domNode) рендерит children в другой DOM-узел вне иерархии компонента (например, в document.body). События всплывают через React-дерево, не через DOM. Используется для: модальных окон, тултипов, дропдаунов — чтобы избежать проблем с overflow:hidden и z-index.',
  },
  {
    id: 'react-040',
    difficulty: 'MEDIUM',
    order: 40,
    tags: ['patterns'],
    questionRu: 'Что такое Suspense и как работает?',
    questionEn: 'Что такое Suspense и как работает?',
    answerRu: 'Suspense позволяет компонентам «приостанавливать» рендер до готовности данных или кода. Показывает fallback пока дочерние компоненты загружаются. Работает с: React.lazy (code splitting), React Query/SWR с suspense: true, use() хуком (React 19). Вложенные Suspense создают независимые зоны загрузки.',
    answerEn: 'Suspense позволяет компонентам «приостанавливать» рендер до готовности данных или кода. Показывает fallback пока дочерние компоненты загружаются. Работает с: React.lazy (code splitting), React Query/SWR с suspense: true, use() хуком (React 19). Вложенные Suspense создают независимые зоны загрузки.',
  },
  {
    id: 'react-041',
    difficulty: 'MEDIUM',
    order: 41,
    tags: ['patterns'],
    questionRu: 'Что такое forwardRef?',
    questionEn: 'Что такое forwardRef?',
    answerRu: 'forwardRef позволяет компоненту передавать ref, полученный от родителя, вглубь к DOM-элементу или дочернему компоненту. Нужен когда: UI-библиотека должна дать доступ к DOM, нужно фокусировать input внутри компонента снаружи. В React 19 ref передаётся как обычный prop.',
    answerEn: 'forwardRef позволяет компоненту передавать ref, полученный от родителя, вглубь к DOM-элементу или дочернему компоненту. Нужен когда: UI-библиотека должна дать доступ к DOM, нужно фокусировать input внутри компонента снаружи. В React 19 ref передаётся как обычный prop.',
  },
  {
    id: 'react-042',
    difficulty: 'MEDIUM',
    order: 42,
    tags: ['patterns'],
    questionRu: 'В чём разница между presentational и container компонентами?',
    questionEn: 'В чём разница между presentational и container компонентами?',
    answerRu: 'Паттерн разделения ответственности: Presentational (глупые) — только рендер UI, получают данные через props, нет бизнес-логики. Container (умные) — получают данные, управляют state, передают в presentational. Сейчас часто заменяется хуками — логика в хуке, компонент только рендерит.',
    answerEn: 'Паттерн разделения ответственности: Presentational (глупые) — только рендер UI, получают данные через props, нет бизнес-логики. Container (умные) — получают данные, управляют state, передают в presentational. Сейчас часто заменяется хуками — логика в хуке, компонент только рендерит.',
  },
];
