import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'sec-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['xss', 'injections'],
    questionRu: 'Что такое XSS и какие виды бывают?',
    questionEn: 'What is XSS and what types are there?',
    answerRu: 'XSS (Cross-Site Scripting) — внедрение вредоносного скрипта в страницу. Stored XSS: скрипт сохранён в БД и выполняется у всех пользователей. Reflected XSS: скрипт в URL, выполняется при переходе по ссылке. DOM-based XSS: манипуляция DOM без сервера через location.hash, innerHTML. Цель: кража cookies, сессий, данных.',
    answerEn: 'XSS (Cross-Site Scripting) — injecting a malicious script into a page. Stored XSS: the script is saved in the database and executes for all users. Reflected XSS: the script is in the URL and runs when the link is followed. DOM-based XSS: DOM manipulation without a server via location.hash, innerHTML. Goal: stealing cookies, sessions, and data.',
  },
  {
    id: 'sec-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['xss', 'protection'],
    questionRu: 'Как защититься от XSS?',
    questionEn: 'How do you protect against XSS?',
    answerRu: 'Экранировать пользовательский ввод при выводе в HTML. Не использовать innerHTML с пользовательскими данными — только textContent. DOMPurify для санитизации HTML если нужна разметка. CSP заголовок блокирует inline-скрипты. HttpOnly cookies недоступны через JS. React/Vue экранируют автоматически при использовании JSX/template.',
    answerEn: 'Escape user input when rendering to HTML. Never use innerHTML with user data — use textContent instead. DOMPurify for sanitizing HTML when markup is required. CSP header blocks inline scripts. HttpOnly cookies are inaccessible via JS. React/Vue escape automatically when using JSX/templates.',
  },
  {
    id: 'sec-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['sql-injection', 'injections'],
    questionRu: 'Что такое SQL-инъекция и как предотвратить?',
    questionEn: 'What is SQL injection and how do you prevent it?',
    answerRu: "SQL-инъекция — внедрение SQL-кода через пользовательский ввод: ' OR 1=1 --. Позволяет читать, изменять, удалять данные. Защита: параметризованные запросы/prepared statements (никогда не конкатенировать SQL со входными данными), ORM, минимальные права БД-пользователя, валидация входных данных.",
    answerEn: "SQL injection — embedding SQL code through user input: ' OR 1=1 --. Allows reading, modifying, and deleting data. Prevention: parameterized queries/prepared statements (never concatenate SQL with user input), ORMs, minimal database user privileges, input validation.",
  },
  {
    id: 'sec-004',
    difficulty: 'HARD',
    order: 4,
    tags: ['prototype-pollution', 'injections'],
    questionRu: 'Что такое prototype pollution?',
    questionEn: 'What is prototype pollution?',
    answerRu: "Prototype pollution — атака, модифицирующая Object.prototype через уязвимый код: obj['__proto__']['admin'] = true. Все объекты получают свойство admin. Уязвимы: deep merge, clone, set по пути. Защита: Object.create(null) для словарей, проверять ключи на __proto__/constructor/prototype, использовать Map вместо объектов.",
    answerEn: "Prototype pollution — an attack that modifies Object.prototype through vulnerable code: obj['__proto__']['admin'] = true. All objects gain the admin property. Vulnerable operations: deep merge, clone, set-by-path. Prevention: Object.create(null) for dictionaries, checking keys against __proto__/constructor/prototype, using Map instead of plain objects.",
  },
  {
    id: 'sec-005',
    difficulty: 'HARD',
    order: 5,
    tags: ['redos', 'regex', 'dos'],
    questionRu: 'Что такое ReDoS?',
    questionEn: 'What is ReDoS?',
    answerRu: 'ReDoS (Regular Expression DoS) — атака через регулярное выражение с катастрофическим backtracking. Специально сконструированная строка заставляет regex работать экспоненциально долго, блокируя event loop. Защита: избегать вложенных квантификаторов (a+)+, использовать линейные regex, библиотека safe-regex для проверки.',
    answerEn: 'ReDoS (Regular Expression DoS) — an attack exploiting a regular expression with catastrophic backtracking. A specially crafted input string causes the regex to run for an exponentially long time, blocking the event loop. Prevention: avoid nested quantifiers like (a+)+, use linear-time regexes, and check patterns with the safe-regex library.',
  },
  {
    id: 'sec-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['csp', 'xss', 'headers'],
    questionRu: 'Что такое CSP и как защищает от XSS?',
    questionEn: 'What is CSP and how does it protect against XSS?',
    answerRu: "Content Security Policy — заголовок ограничивающий источники ресурсов и скриптов. script-src 'self' — только скрипты с того же домена, блокирует inline-скрипты и eval. Даже при успешной инъекции скрипт не выполнится если нарушает CSP. Nonce-based CSP для легитимных inline-скриптов. report-uri для мониторинга нарушений.",
    answerEn: "Content Security Policy — a header that restricts the sources of resources and scripts. script-src 'self' — only scripts from the same origin, blocks inline scripts and eval. Even if an injection succeeds, the script won't execute if it violates the CSP. Nonce-based CSP for legitimate inline scripts. report-uri for monitoring violations.",
  },
  {
    id: 'sec-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['csrf'],
    questionRu: 'Что такое CSRF и как работает атака?',
    questionEn: 'What is CSRF and how does the attack work?',
    answerRu: 'CSRF (Cross-Site Request Forgery) — сайт злоумышленника заставляет браузер пользователя отправить запрос к другому сайту, где тот авторизован. Браузер автоматически прикрепляет cookies. Пример: img src=\'bank.com/transfer?to=attacker&amount=1000\'. Работает только для state-changing операций.',
    answerEn: 'CSRF (Cross-Site Request Forgery) — an attacker\'s site tricks the user\'s browser into sending a request to another site where the user is authenticated. The browser automatically attaches cookies. Example: img src=\'bank.com/transfer?to=attacker&amount=1000\'. Only works against state-changing operations.',
  },
  {
    id: 'sec-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['csrf', 'protection'],
    questionRu: 'Как защититься от CSRF?',
    questionEn: 'How do you protect against CSRF?',
    answerRu: 'CSRF токен: сервер генерирует уникальный токен, клиент отправляет в заголовке или теле — злоумышленник не знает токен. SameSite=Strict/Lax cookies: браузер не отправляет cookies в cross-site запросах. Double Submit Cookie: токен и в cookie и в заголовке. Проверка Origin/Referer заголовков.',
    answerEn: 'CSRF token: the server generates a unique token, the client sends it in a header or body — the attacker does not know the token. SameSite=Strict/Lax cookies: the browser does not send cookies on cross-site requests. Double Submit Cookie: token in both cookie and header. Validating Origin/Referer headers.',
  },
  {
    id: 'sec-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['clickjacking', 'iframe'],
    questionRu: 'Что такое кликджекинг и как защититься?',
    questionEn: 'What is clickjacking and how do you protect against it?',
    answerRu: 'Кликджекинг — сайт злоумышленника накладывает прозрачный iframe с целевым сайтом. Пользователь думает, что кликает по своему элементу, а кликает по iframe. Защита: X-Frame-Options: DENY/SAMEORIGIN — запрет встраивания в iframe. CSP frame-ancestors \'none\' — современная альтернатива. JavaScript frame-busting ненадёжен.',
    answerEn: 'Clickjacking — an attacker\'s site overlays a transparent iframe of the target site. The user thinks they are clicking their own element but actually clicks the iframe. Protection: X-Frame-Options: DENY/SAMEORIGIN — prevents embedding in iframes. CSP frame-ancestors \'none\' — the modern alternative. JavaScript frame-busting is unreliable.',
  },
  {
    id: 'sec-010',
    difficulty: 'HARD',
    order: 10,
    tags: ['ssrf'],
    questionRu: 'Что такое SSRF?',
    questionEn: 'What is SSRF?',
    answerRu: 'SSRF (Server-Side Request Forgery) — сервер делает запрос к URL указанному пользователем. Атакующий может достучаться до внутренней инфраструктуры: http://169.254.169.254 (AWS metadata). Защита: валидация и whitelist разрешённых URL, блокировка внутренних IP-диапазонов, не возвращать ответ пользователю напрямую.',
    answerEn: 'SSRF (Server-Side Request Forgery) — the server makes a request to a URL provided by the user. An attacker can reach internal infrastructure: http://169.254.169.254 (AWS metadata). Prevention: validate and whitelist allowed URLs, block internal IP ranges, do not return the response directly to the user.',
  },
  {
    id: 'sec-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['open-redirect', 'phishing'],
    questionRu: 'Что такое open redirect и чем опасен?',
    questionEn: 'What is an open redirect and why is it dangerous?',
    answerRu: 'Open redirect — параметр URL перенаправляет на произвольный сайт: /redirect?url=evil.com. Используется для фишинга — ссылка выглядит как доверенный домен. Защита: не использовать пользовательский URL для редиректа, whitelist разрешённых доменов, относительные пути вместо абсолютных URL.',
    answerEn: 'Open redirect — a URL parameter redirects to an arbitrary site: /redirect?url=evil.com. Used for phishing — the link appears to belong to a trusted domain. Prevention: do not use user-supplied URLs for redirects, whitelist allowed domains, use relative paths instead of absolute URLs.',
  },
  {
    id: 'sec-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['passwords', 'hashing', 'auth'],
    questionRu: 'Как безопасно хранить пароли?',
    questionEn: 'How do you store passwords securely?',
    answerRu: 'Никогда не хранить plaintext или MD5/SHA1. Использовать медленные алгоритмы хеширования: bcrypt, Argon2, scrypt — стойкие к brute force. Salt добавляется автоматически — защита от rainbow tables. Pepper (секретный ключ) для дополнительной защиты. bcrypt factor 12+ как минимальная стойкость.',
    answerEn: 'Never store plaintext passwords or use MD5/SHA1. Use slow hashing algorithms: bcrypt, Argon2, scrypt — resistant to brute force. Salt is added automatically, protecting against rainbow tables. Pepper (a secret key) for additional protection. bcrypt cost factor 12+ as a minimum.',
  },
  {
    id: 'sec-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['sessions', 'jwt', 'auth'],
    questionRu: 'В чём разница между сессиями и JWT для аутентификации?',
    questionEn: 'What is the difference between sessions and JWT for authentication?',
    answerRu: 'Сессии: сервер хранит состояние, клиент — только session ID в cookie. Легко инвалидировать, нагрузка на хранилище. JWT: stateless — сервер не хранит, всё в токене. Не требует БД при проверке. Минус: нельзя инвалидировать до истечения без blacklist. Сессии для монолитов, JWT для микросервисов и мобильных.',
    answerEn: 'Sessions: the server stores state, the client holds only a session ID in a cookie. Easy to invalidate, puts load on storage. JWT: stateless — the server stores nothing, everything is in the token. No database lookup needed for verification. Downside: cannot be invalidated before expiry without a blacklist. Sessions for monoliths, JWT for microservices and mobile apps.',
  },
  {
    id: 'sec-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['oauth', 'oidc', 'auth'],
    questionRu: 'Что такое OAuth 2.0 и OpenID Connect?',
    questionEn: 'What are OAuth 2.0 and OpenID Connect?',
    answerRu: 'OAuth 2.0 — протокол авторизации: пользователь разрешает приложению доступ к ресурсам без передачи пароля. Flows: Authorization Code (веб), PKCE (SPA/мобильные), Client Credentials (machine-to-machine). OpenID Connect — слой поверх OAuth 2.0 для аутентификации: добавляет ID Token (JWT) с данными пользователя.',
    answerEn: 'OAuth 2.0 — an authorization protocol: the user grants an application access to resources without sharing their password. Flows: Authorization Code (web), PKCE (SPA/mobile), Client Credentials (machine-to-machine). OpenID Connect — a layer on top of OAuth 2.0 for authentication: adds an ID Token (JWT) containing user data.',
  },
  {
    id: 'sec-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['tokens', 'storage', 'cookies'],
    questionRu: 'Как безопасно хранить токены на клиенте?',
    questionEn: 'How do you store tokens securely on the client?',
    answerRu: 'HttpOnly cookie: недоступен JS — лучшая защита от XSS, уязвим к CSRF (решается SameSite). localStorage: доступен JS — уязвим к XSS, не уязвим к CSRF. Memory (переменная): наиболее безопасно, теряется при обновлении страницы. Рекомендация: refresh token в HttpOnly cookie, access token в памяти.',
    answerEn: 'HttpOnly cookie: inaccessible to JS — best protection against XSS, vulnerable to CSRF (mitigated by SameSite). localStorage: accessible to JS — vulnerable to XSS, not vulnerable to CSRF. Memory (variable): most secure, lost on page refresh. Recommendation: refresh token in an HttpOnly cookie, access token in memory.',
  },
  {
    id: 'sec-016',
    difficulty: 'EASY',
    order: 16,
    tags: ['least-privilege', 'authorization'],
    questionRu: 'Что такое принцип минимальных привилегий?',
    questionEn: 'What is the principle of least privilege?',
    answerRu: 'Principle of Least Privilege — пользователь, процесс или система получают только минимально необходимые права. В frontend: API возвращает только нужные поля, не весь объект. Роли вместо индивидуальных прав. Проверка прав на сервере, не только на клиенте. Клиентская авторизация — только для UX, не безопасности.',
    answerEn: 'Principle of Least Privilege — a user, process, or system is granted only the minimum permissions necessary. In frontend: the API returns only the required fields, not the entire object. Roles instead of individual permissions. Authorization is enforced on the server, not just the client. Client-side authorization is for UX only, not security.',
  },
  {
    id: 'sec-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['rate-limiting', 'dos', 'brute-force'],
    questionRu: 'Что такое rate limiting и зачем нужен?',
    questionEn: 'What is rate limiting and why is it needed?',
    answerRu: 'Rate limiting — ограничение количества запросов от одного клиента за период. Защищает от: brute force атак на пароли, DoS, скрейпинга, спама. Реализация: по IP, по пользователю, по API ключу. Алгоритмы: token bucket, sliding window. HTTP 429 Too Many Requests. На уровне nginx, API Gateway или приложения.',
    answerEn: 'Rate limiting — restricting the number of requests from a single client within a time period. Protects against: brute force password attacks, DoS, scraping, and spam. Implementation: per IP, per user, per API key. Algorithms: token bucket, sliding window. HTTP 429 Too Many Requests. Applied at the nginx, API Gateway, or application level.',
  },
  {
    id: 'sec-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['headers', 'hsts', 'csp'],
    questionRu: 'Какие HTTP заголовки безопасности обязательны?',
    questionEn: 'Which HTTP security headers are essential?',
    answerRu: 'Strict-Transport-Security: max-age=31536000; includeSubDomains — только HTTPS. Content-Security-Policy — ограничение источников. X-Content-Type-Options: nosniff — не угадывать MIME тип. X-Frame-Options: DENY — защита от кликджекинга. Referrer-Policy: strict-origin-when-cross-origin. Permissions-Policy для ограничения API браузера.',
    answerEn: 'Strict-Transport-Security: max-age=31536000; includeSubDomains — HTTPS only. Content-Security-Policy — restricts resource sources. X-Content-Type-Options: nosniff — prevents MIME type sniffing. X-Frame-Options: DENY — clickjacking protection. Referrer-Policy: strict-origin-when-cross-origin. Permissions-Policy for restricting browser APIs.',
  },
  {
    id: 'sec-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['hsts', 'https', 'headers'],
    questionRu: 'Что такое HSTS?',
    questionEn: 'What is HSTS?',
    answerRu: 'HSTS (HTTP Strict Transport Security) — заголовок Strict-Transport-Security сообщает браузеру всегда использовать HTTPS для домена. max-age — срок в секундах. includeSubDomains — распространяется на поддомены. preload — включение в браузерный список HSTS preload. Защищает от SSL stripping атак.',
    answerEn: 'HSTS (HTTP Strict Transport Security) — the Strict-Transport-Security header instructs the browser to always use HTTPS for the domain. max-age — duration in seconds. includeSubDomains — applies to subdomains as well. preload — inclusion in the browser\'s HSTS preload list. Protects against SSL stripping attacks.',
  },
  {
    id: 'sec-020',
    difficulty: 'MEDIUM',
    order: 20,
    tags: ['sri', 'cdn', 'integrity'],
    questionRu: 'Что такое Subresource Integrity (SRI)?',
    questionEn: 'What is Subresource Integrity (SRI)?',
    answerRu: "SRI — атрибут integrity у script/link тегов: integrity='sha384-hash'. Браузер проверяет хеш загруженного ресурса — если CDN скомпрометирован и файл изменён, браузер отказывается его выполнять. Используется для сторонних ресурсов с CDN. Генерация хеша: openssl или srihash.com.",
    answerEn: "SRI — the integrity attribute on script/link tags: integrity='sha384-hash'. The browser verifies the hash of the downloaded resource — if the CDN is compromised and the file is modified, the browser refuses to execute it. Used for third-party CDN resources. Hash generation: openssl or srihash.com.",
  },
  {
    id: 'sec-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['owasp', 'vulnerabilities'],
    questionRu: 'Что такое OWASP Top 10?',
    questionEn: 'What is the OWASP Top 10?',
    answerRu: 'OWASP Top 10 — список наиболее критичных уязвимостей веб-приложений. Актуальные (2021): Broken Access Control, Cryptographic Failures, Injection (SQL/XSS), Insecure Design, Security Misconfiguration, Vulnerable Components, Authentication Failures, Integrity Failures, Logging Failures, SSRF. Стандарт для security-аудитов.',
    answerEn: 'OWASP Top 10 — a list of the most critical web application vulnerabilities. Current edition (2021): Broken Access Control, Cryptographic Failures, Injection (SQL/XSS), Insecure Design, Security Misconfiguration, Vulnerable Components, Authentication Failures, Integrity Failures, Logging Failures, SSRF. The standard reference for security audits.',
  },
  {
    id: 'sec-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['dependencies', 'supply-chain', 'npm'],
    questionRu: 'Как безопасно работать с зависимостями?',
    questionEn: 'How do you manage dependencies securely?',
    answerRu: 'npm audit — проверка известных уязвимостей. Dependabot/Renovate — автоматические PR с обновлениями. Не использовать пакеты без поддержки. Проверять количество зависимостей — каждая расширяет attack surface. Supply chain атаки: проверять имена пакетов (typosquatting). lock-файлы (package-lock.json) для воспроизводимых сборок.',
    answerEn: 'npm audit — checks for known vulnerabilities. Dependabot/Renovate — automated PRs with updates. Avoid unmaintained packages. Audit the number of dependencies — each one expands the attack surface. Supply chain attacks: verify package names (typosquatting). Lock files (package-lock.json) for reproducible builds.',
  },
];
