import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'sec-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['xss', 'injections'],
    questionRu: 'Что такое XSS и какие виды бывают?',
    questionEn: 'Что такое XSS и какие виды бывают?',
    answerRu: 'XSS (Cross-Site Scripting) — внедрение вредоносного скрипта в страницу. Stored XSS: скрипт сохранён в БД и выполняется у всех пользователей. Reflected XSS: скрипт в URL, выполняется при переходе по ссылке. DOM-based XSS: манипуляция DOM без сервера через location.hash, innerHTML. Цель: кража cookies, сессий, данных.',
    answerEn: 'XSS (Cross-Site Scripting) — внедрение вредоносного скрипта в страницу. Stored XSS: скрипт сохранён в БД и выполняется у всех пользователей. Reflected XSS: скрипт в URL, выполняется при переходе по ссылке. DOM-based XSS: манипуляция DOM без сервера через location.hash, innerHTML. Цель: кража cookies, сессий, данных.',
  },
  {
    id: 'sec-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['xss', 'protection'],
    questionRu: 'Как защититься от XSS?',
    questionEn: 'Как защититься от XSS?',
    answerRu: 'Экранировать пользовательский ввод при выводе в HTML. Не использовать innerHTML с пользовательскими данными — только textContent. DOMPurify для санитизации HTML если нужна разметка. CSP заголовок блокирует inline-скрипты. HttpOnly cookies недоступны через JS. React/Vue экранируют автоматически при использовании JSX/template.',
    answerEn: 'Экранировать пользовательский ввод при выводе в HTML. Не использовать innerHTML с пользовательскими данными — только textContent. DOMPurify для санитизации HTML если нужна разметка. CSP заголовок блокирует inline-скрипты. HttpOnly cookies недоступны через JS. React/Vue экранируют автоматически при использовании JSX/template.',
  },
  {
    id: 'sec-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['sql-injection', 'injections'],
    questionRu: 'Что такое SQL-инъекция и как предотвратить?',
    questionEn: 'Что такое SQL-инъекция и как предотвратить?',
    answerRu: "SQL-инъекция — внедрение SQL-кода через пользовательский ввод: ' OR 1=1 --. Позволяет читать, изменять, удалять данные. Защита: параметризованные запросы/prepared statements (никогда не конкатенировать SQL со входными данными), ORM, минимальные права БД-пользователя, валидация входных данных.",
    answerEn: "SQL-инъекция — внедрение SQL-кода через пользовательский ввод: ' OR 1=1 --. Позволяет читать, изменять, удалять данные. Защита: параметризованные запросы/prepared statements (никогда не конкатенировать SQL со входными данными), ORM, минимальные права БД-пользователя, валидация входных данных.",
  },
  {
    id: 'sec-004',
    difficulty: 'HARD',
    order: 4,
    tags: ['prototype-pollution', 'injections'],
    questionRu: 'Что такое prototype pollution?',
    questionEn: 'Что такое prototype pollution?',
    answerRu: "Prototype pollution — атака, модифицирующая Object.prototype через уязвимый код: obj['__proto__']['admin'] = true. Все объекты получают свойство admin. Уязвимы: deep merge, clone, set по пути. Защита: Object.create(null) для словарей, проверять ключи на __proto__/constructor/prototype, использовать Map вместо объектов.",
    answerEn: "Prototype pollution — атака, модифицирующая Object.prototype через уязвимый код: obj['__proto__']['admin'] = true. Все объекты получают свойство admin. Уязвимы: deep merge, clone, set по пути. Защита: Object.create(null) для словарей, проверять ключи на __proto__/constructor/prototype, использовать Map вместо объектов.",
  },
  {
    id: 'sec-005',
    difficulty: 'HARD',
    order: 5,
    tags: ['redos', 'regex', 'dos'],
    questionRu: 'Что такое ReDoS?',
    questionEn: 'Что такое ReDoS?',
    answerRu: 'ReDoS (Regular Expression DoS) — атака через регулярное выражение с катастрофическим backtracking. Специально сконструированная строка заставляет regex работать экспоненциально долго, блокируя event loop. Защита: избегать вложенных квантификаторов (a+)+, использовать линейные regex, библиотека safe-regex для проверки.',
    answerEn: 'ReDoS (Regular Expression DoS) — атака через регулярное выражение с катастрофическим backtracking. Специально сконструированная строка заставляет regex работать экспоненциально долго, блокируя event loop. Защита: избегать вложенных квантификаторов (a+)+, использовать линейные regex, библиотека safe-regex для проверки.',
  },
  {
    id: 'sec-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['csp', 'xss', 'headers'],
    questionRu: 'Что такое CSP и как защищает от XSS?',
    questionEn: 'Что такое CSP и как защищает от XSS?',
    answerRu: "Content Security Policy — заголовок ограничивающий источники ресурсов и скриптов. script-src 'self' — только скрипты с того же домена, блокирует inline-скрипты и eval. Даже при успешной инъекции скрипт не выполнится если нарушает CSP. Nonce-based CSP для легитимных inline-скриптов. report-uri для мониторинга нарушений.",
    answerEn: "Content Security Policy — заголовок ограничивающий источники ресурсов и скриптов. script-src 'self' — только скрипты с того же домена, блокирует inline-скрипты и eval. Даже при успешной инъекции скрипт не выполнится если нарушает CSP. Nonce-based CSP для легитимных inline-скриптов. report-uri для мониторинга нарушений.",
  },
  {
    id: 'sec-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['csrf'],
    questionRu: 'Что такое CSRF и как работает атака?',
    questionEn: 'Что такое CSRF и как работает атака?',
    answerRu: 'CSRF (Cross-Site Request Forgery) — сайт злоумышленника заставляет браузер пользователя отправить запрос к другому сайту, где тот авторизован. Браузер автоматически прикрепляет cookies. Пример: img src=\'bank.com/transfer?to=attacker&amount=1000\'. Работает только для state-changing операций.',
    answerEn: 'CSRF (Cross-Site Request Forgery) — сайт злоумышленника заставляет браузер пользователя отправить запрос к другому сайту, где тот авторизован. Браузер автоматически прикрепляет cookies. Пример: img src=\'bank.com/transfer?to=attacker&amount=1000\'. Работает только для state-changing операций.',
  },
  {
    id: 'sec-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['csrf', 'protection'],
    questionRu: 'Как защититься от CSRF?',
    questionEn: 'Как защититься от CSRF?',
    answerRu: 'CSRF токен: сервер генерирует уникальный токен, клиент отправляет в заголовке или теле — злоумышленник не знает токен. SameSite=Strict/Lax cookies: браузер не отправляет cookies в cross-site запросах. Double Submit Cookie: токен и в cookie и в заголовке. Проверка Origin/Referer заголовков.',
    answerEn: 'CSRF токен: сервер генерирует уникальный токен, клиент отправляет в заголовке или теле — злоумышленник не знает токен. SameSite=Strict/Lax cookies: браузер не отправляет cookies в cross-site запросах. Double Submit Cookie: токен и в cookie и в заголовке. Проверка Origin/Referer заголовков.',
  },
  {
    id: 'sec-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['clickjacking', 'iframe'],
    questionRu: 'Что такое кликджекинг и как защититься?',
    questionEn: 'Что такое кликджекинг и как защититься?',
    answerRu: 'Кликджекинг — сайт злоумышленника накладывает прозрачный iframe с целевым сайтом. Пользователь думает, что кликает по своему элементу, а кликает по iframe. Защита: X-Frame-Options: DENY/SAMEORIGIN — запрет встраивания в iframe. CSP frame-ancestors \'none\' — современная альтернатива. JavaScript frame-busting ненадёжен.',
    answerEn: 'Кликджекинг — сайт злоумышленника накладывает прозрачный iframe с целевым сайтом. Пользователь думает, что кликает по своему элементу, а кликает по iframe. Защита: X-Frame-Options: DENY/SAMEORIGIN — запрет встраивания в iframe. CSP frame-ancestors \'none\' — современная альтернатива. JavaScript frame-busting ненадёжен.',
  },
  {
    id: 'sec-010',
    difficulty: 'HARD',
    order: 10,
    tags: ['ssrf'],
    questionRu: 'Что такое SSRF?',
    questionEn: 'Что такое SSRF?',
    answerRu: 'SSRF (Server-Side Request Forgery) — сервер делает запрос к URL указанному пользователем. Атакующий может достучаться до внутренней инфраструктуры: http://169.254.169.254 (AWS metadata). Защита: валидация и whitelist разрешённых URL, блокировка внутренних IP-диапазонов, не возвращать ответ пользователю напрямую.',
    answerEn: 'SSRF (Server-Side Request Forgery) — сервер делает запрос к URL указанному пользователем. Атакующий может достучаться до внутренней инфраструктуры: http://169.254.169.254 (AWS metadata). Защита: валидация и whitelist разрешённых URL, блокировка внутренних IP-диапазонов, не возвращать ответ пользователю напрямую.',
  },
  {
    id: 'sec-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['open-redirect', 'phishing'],
    questionRu: 'Что такое open redirect и чем опасен?',
    questionEn: 'Что такое open redirect и чем опасен?',
    answerRu: 'Open redirect — параметр URL перенаправляет на произвольный сайт: /redirect?url=evil.com. Используется для фишинга — ссылка выглядит как доверенный домен. Защита: не использовать пользовательский URL для редиректа, whitelist разрешённых доменов, относительные пути вместо абсолютных URL.',
    answerEn: 'Open redirect — параметр URL перенаправляет на произвольный сайт: /redirect?url=evil.com. Используется для фишинга — ссылка выглядит как доверенный домен. Защита: не использовать пользовательский URL для редиректа, whitelist разрешённых доменов, относительные пути вместо абсолютных URL.',
  },
  {
    id: 'sec-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['passwords', 'hashing', 'auth'],
    questionRu: 'Как безопасно хранить пароли?',
    questionEn: 'Как безопасно хранить пароли?',
    answerRu: 'Никогда не хранить plaintext или MD5/SHA1. Использовать медленные алгоритмы хеширования: bcrypt, Argon2, scrypt — стойкие к brute force. Salt добавляется автоматически — защита от rainbow tables. Pepper (секретный ключ) для дополнительной защиты. bcrypt factor 12+ как минимальная стойкость.',
    answerEn: 'Никогда не хранить plaintext или MD5/SHA1. Использовать медленные алгоритмы хеширования: bcrypt, Argon2, scrypt — стойкие к brute force. Salt добавляется автоматически — защита от rainbow tables. Pepper (секретный ключ) для дополнительной защиты. bcrypt factor 12+ как минимальная стойкость.',
  },
  {
    id: 'sec-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['sessions', 'jwt', 'auth'],
    questionRu: 'В чём разница между сессиями и JWT для аутентификации?',
    questionEn: 'В чём разница между сессиями и JWT для аутентификации?',
    answerRu: 'Сессии: сервер хранит состояние, клиент — только session ID в cookie. Легко инвалидировать, нагрузка на хранилище. JWT: stateless — сервер не хранит, всё в токене. Не требует БД при проверке. Минус: нельзя инвалидировать до истечения без blacklist. Сессии для монолитов, JWT для микросервисов и мобильных.',
    answerEn: 'Сессии: сервер хранит состояние, клиент — только session ID в cookie. Легко инвалидировать, нагрузка на хранилище. JWT: stateless — сервер не хранит, всё в токене. Не требует БД при проверке. Минус: нельзя инвалидировать до истечения без blacklist. Сессии для монолитов, JWT для микросервисов и мобильных.',
  },
  {
    id: 'sec-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['oauth', 'oidc', 'auth'],
    questionRu: 'Что такое OAuth 2.0 и OpenID Connect?',
    questionEn: 'Что такое OAuth 2.0 и OpenID Connect?',
    answerRu: 'OAuth 2.0 — протокол авторизации: пользователь разрешает приложению доступ к ресурсам без передачи пароля. Flows: Authorization Code (веб), PKCE (SPA/мобильные), Client Credentials (machine-to-machine). OpenID Connect — слой поверх OAuth 2.0 для аутентификации: добавляет ID Token (JWT) с данными пользователя.',
    answerEn: 'OAuth 2.0 — протокол авторизации: пользователь разрешает приложению доступ к ресурсам без передачи пароля. Flows: Authorization Code (веб), PKCE (SPA/мобильные), Client Credentials (machine-to-machine). OpenID Connect — слой поверх OAuth 2.0 для аутентификации: добавляет ID Token (JWT) с данными пользователя.',
  },
  {
    id: 'sec-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['tokens', 'storage', 'cookies'],
    questionRu: 'Как безопасно хранить токены на клиенте?',
    questionEn: 'Как безопасно хранить токены на клиенте?',
    answerRu: 'HttpOnly cookie: недоступен JS — лучшая защита от XSS, уязвим к CSRF (решается SameSite). localStorage: доступен JS — уязвим к XSS, не уязвим к CSRF. Memory (переменная): наиболее безопасно, теряется при обновлении страницы. Рекомендация: refresh token в HttpOnly cookie, access token в памяти.',
    answerEn: 'HttpOnly cookie: недоступен JS — лучшая защита от XSS, уязвим к CSRF (решается SameSite). localStorage: доступен JS — уязвим к XSS, не уязвим к CSRF. Memory (переменная): наиболее безопасно, теряется при обновлении страницы. Рекомендация: refresh token в HttpOnly cookie, access token в памяти.',
  },
  {
    id: 'sec-016',
    difficulty: 'EASY',
    order: 16,
    tags: ['least-privilege', 'authorization'],
    questionRu: 'Что такое принцип минимальных привилегий?',
    questionEn: 'Что такое принцип минимальных привилегий?',
    answerRu: 'Principle of Least Privilege — пользователь, процесс или система получают только минимально необходимые права. В frontend: API возвращает только нужные поля, не весь объект. Роли вместо индивидуальных прав. Проверка прав на сервере, не только на клиенте. Клиентская авторизация — только для UX, не безопасности.',
    answerEn: 'Principle of Least Privilege — пользователь, процесс или система получают только минимально необходимые права. В frontend: API возвращает только нужные поля, не весь объект. Роли вместо индивидуальных прав. Проверка прав на сервере, не только на клиенте. Клиентская авторизация — только для UX, не безопасности.',
  },
  {
    id: 'sec-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['rate-limiting', 'dos', 'brute-force'],
    questionRu: 'Что такое rate limiting и зачем нужен?',
    questionEn: 'Что такое rate limiting и зачем нужен?',
    answerRu: 'Rate limiting — ограничение количества запросов от одного клиента за период. Защищает от: brute force атак на пароли, DoS, скрейпинга, спама. Реализация: по IP, по пользователю, по API ключу. Алгоритмы: token bucket, sliding window. HTTP 429 Too Many Requests. На уровне nginx, API Gateway или приложения.',
    answerEn: 'Rate limiting — ограничение количества запросов от одного клиента за период. Защищает от: brute force атак на пароли, DoS, скрейпинга, спама. Реализация: по IP, по пользователю, по API ключу. Алгоритмы: token bucket, sliding window. HTTP 429 Too Many Requests. На уровне nginx, API Gateway или приложения.',
  },
  {
    id: 'sec-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['headers', 'hsts', 'csp'],
    questionRu: 'Какие HTTP заголовки безопасности обязательны?',
    questionEn: 'Какие HTTP заголовки безопасности обязательны?',
    answerRu: 'Strict-Transport-Security: max-age=31536000; includeSubDomains — только HTTPS. Content-Security-Policy — ограничение источников. X-Content-Type-Options: nosniff — не угадывать MIME тип. X-Frame-Options: DENY — защита от кликджекинга. Referrer-Policy: strict-origin-when-cross-origin. Permissions-Policy для ограничения API браузера.',
    answerEn: 'Strict-Transport-Security: max-age=31536000; includeSubDomains — только HTTPS. Content-Security-Policy — ограничение источников. X-Content-Type-Options: nosniff — не угадывать MIME тип. X-Frame-Options: DENY — защита от кликджекинга. Referrer-Policy: strict-origin-when-cross-origin. Permissions-Policy для ограничения API браузера.',
  },
  {
    id: 'sec-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['hsts', 'https', 'headers'],
    questionRu: 'Что такое HSTS?',
    questionEn: 'Что такое HSTS?',
    answerRu: 'HSTS (HTTP Strict Transport Security) — заголовок Strict-Transport-Security сообщает браузеру всегда использовать HTTPS для домена. max-age — срок в секундах. includeSubDomains — распространяется на поддомены. preload — включение в браузерный список HSTS preload. Защищает от SSL stripping атак.',
    answerEn: 'HSTS (HTTP Strict Transport Security) — заголовок Strict-Transport-Security сообщает браузеру всегда использовать HTTPS для домена. max-age — срок в секундах. includeSubDomains — распространяется на поддомены. preload — включение в браузерный список HSTS preload. Защищает от SSL stripping атак.',
  },
  {
    id: 'sec-020',
    difficulty: 'MEDIUM',
    order: 20,
    tags: ['sri', 'cdn', 'integrity'],
    questionRu: 'Что такое Subresource Integrity (SRI)?',
    questionEn: 'Что такое Subresource Integrity (SRI)?',
    answerRu: "SRI — атрибут integrity у script/link тегов: integrity='sha384-hash'. Браузер проверяет хеш загруженного ресурса — если CDN скомпрометирован и файл изменён, браузер отказывается его выполнять. Используется для сторонних ресурсов с CDN. Генерация хеша: openssl или srihash.com.",
    answerEn: "SRI — атрибут integrity у script/link тегов: integrity='sha384-hash'. Браузер проверяет хеш загруженного ресурса — если CDN скомпрометирован и файл изменён, браузер отказывается его выполнять. Используется для сторонних ресурсов с CDN. Генерация хеша: openssl или srihash.com.",
  },
  {
    id: 'sec-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['owasp', 'vulnerabilities'],
    questionRu: 'Что такое OWASP Top 10?',
    questionEn: 'Что такое OWASP Top 10?',
    answerRu: 'OWASP Top 10 — список наиболее критичных уязвимостей веб-приложений. Актуальные (2021): Broken Access Control, Cryptographic Failures, Injection (SQL/XSS), Insecure Design, Security Misconfiguration, Vulnerable Components, Authentication Failures, Integrity Failures, Logging Failures, SSRF. Стандарт для security-аудитов.',
    answerEn: 'OWASP Top 10 — список наиболее критичных уязвимостей веб-приложений. Актуальные (2021): Broken Access Control, Cryptographic Failures, Injection (SQL/XSS), Insecure Design, Security Misconfiguration, Vulnerable Components, Authentication Failures, Integrity Failures, Logging Failures, SSRF. Стандарт для security-аудитов.',
  },
  {
    id: 'sec-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['dependencies', 'supply-chain', 'npm'],
    questionRu: 'Как безопасно работать с зависимостями?',
    questionEn: 'Как безопасно работать с зависимостями?',
    answerRu: 'npm audit — проверка известных уязвимостей. Dependabot/Renovate — автоматические PR с обновлениями. Не использовать пакеты без поддержки. Проверять количество зависимостей — каждая расширяет attack surface. Supply chain атаки: проверять имена пакетов (typosquatting). lock-файлы (package-lock.json) для воспроизводимых сборок.',
    answerEn: 'npm audit — проверка известных уязвимостей. Dependabot/Renovate — автоматические PR с обновлениями. Не использовать пакеты без поддержки. Проверять количество зависимостей — каждая расширяет attack surface. Supply chain атаки: проверять имена пакетов (typosquatting). lock-файлы (package-lock.json) для воспроизводимых сборок.',
  },
];
