import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'sd-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['components', 'architecture'],
    questionRu: 'Что такое компонентная архитектура и каковы её принципы?',
    questionEn: 'What is component architecture and what are its principles?',
    answerRu: 'Компонентная архитектура — разбивка UI на изолированные переиспользуемые компоненты. Принципы: единственная ответственность (один компонент — одна задача), изоляция (компонент не знает о внешнем мире), переиспользуемость, композиция вместо наследования. Компоненты общаются через props/events, не напрямую.',
    answerEn: 'Component architecture is the practice of splitting UI into isolated, reusable components. Principles: single responsibility (one component — one task), isolation (a component has no knowledge of the outside world), reusability, composition over inheritance. Components communicate via props/events, not directly.',
  },
  {
    id: 'sd-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['architecture', 'folder-structure'],
    questionRu: 'Как организовать структуру папок в большом фронтенд проекте?',
    questionEn: 'How do you organize the folder structure in a large frontend project?',
    answerRu: 'Feature-based структура: папки по фичам (auth/, dashboard/, profile/) — каждая содержит свои компоненты, хуки, стили, тесты. Лучше масштабируется чем type-based (components/, hooks/, styles/). Shared папка для общего кода. Barrel exports (index.ts) для удобного импорта. Плоская структура лучше глубокой вложенности.',
    answerEn: 'Feature-based structure: folders organized by feature (auth/, dashboard/, profile/) — each containing its own components, hooks, styles, and tests. This scales better than type-based organization (components/, hooks/, styles/). A shared folder holds common code. Barrel exports (index.ts) simplify imports. Flat structure is preferred over deep nesting.',
  },
  {
    id: 'sd-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['design-system', 'components'],
    questionRu: 'Что такое Design System и как его организовать?',
    questionEn: 'What is a Design System and how do you organize one?',
    answerRu: 'Design System — библиотека UI компонентов с единым визуальным языком: токены (цвета, отступы, типографика), базовые компоненты (Button, Input, Modal), составные компоненты. Инструменты: Storybook для документации и разработки. Версионирование через npm пакет. Монорепозиторий для Design System + продукт.',
    answerEn: 'A Design System is a UI component library with a unified visual language: tokens (colors, spacing, typography), primitive components (Button, Input, Modal), and composite components. Tooling: Storybook for documentation and development. Versioned as an npm package. A monorepo is a common setup for hosting the Design System alongside the product.',
  },
  {
    id: 'sd-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['components', 'reusability'],
    questionRu: 'Как проектировать переиспользуемый компонент?',
    questionEn: 'How do you design a reusable component?',
    answerRu: 'API через props: только необходимые, с разумными дефолтами. Composition через children/slots вместо жёстко зашитой разметки. Не привязываться к конкретным данным — компонент работает с любыми. Предоставлять ref для императивного API. Документировать через TypeScript типы и Storybook. Версионировать изменения.',
    answerEn: 'Props-based API: expose only what is necessary, with sensible defaults. Favor composition via children/slots over hard-coded markup. Avoid coupling to specific data shapes — the component should work with any data. Expose a ref for imperative API use. Document with TypeScript types and Storybook. Version breaking changes.',
  },
  {
    id: 'sd-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['atomic-design', 'components'],
    questionRu: 'Что такое Atomic Design?',
    questionEn: 'What is Atomic Design?',
    answerRu: 'Atomic Design — методология Брэда Фроста для иерархии компонентов. Atoms (атомы): Button, Input, Icon — неделимые элементы. Molecules (молекулы): SearchBar = Input + Button. Organisms (организмы): Header = Logo + Nav + SearchBar. Templates: layout без данных. Pages: template с реальными данными. Даёт общий язык команде.',
    answerEn: "Atomic Design is Brad Frost's methodology for a component hierarchy. Atoms: Button, Input, Icon — indivisible elements. Molecules: SearchBar = Input + Button. Organisms: Header = Logo + Nav + SearchBar. Templates: layout without real data. Pages: template with actual data. Provides a shared vocabulary for the team.",
  },
  {
    id: 'sd-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['routing', 'spa'],
    questionRu: 'Как организовать роутинг в большом SPA?',
    questionEn: 'How do you organize routing in a large SPA?',
    answerRu: 'Разделить на публичные и защищённые маршруты. Lazy loading для каждого роута — уменьшает начальный бандл. Nested routes для layouts. Централизованная конфигурация маршрутов вместо разброса по компонентам. Guards/middleware для авторизации. Breadcrumbs и навигация на основе конфигурации маршрутов.',
    answerEn: 'Split routes into public and protected. Lazy load each route to reduce the initial bundle. Use nested routes for shared layouts. Keep route configuration centralized rather than scattered across components. Add guards/middleware for authorization. Drive breadcrumbs and navigation from the route configuration.',
  },
  {
    id: 'sd-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['forms', 'validation'],
    questionRu: 'Как спроектировать систему форм для большого приложения?',
    questionEn: 'How do you design a form system for a large application?',
    answerRu: 'Использовать библиотеку (React Hook Form, Formik) — не изобретать велосипед. Схема валидации через Zod/Yup — переиспользуется на клиенте и сервере. Абстракция над полями: компонент FormField оборачивает label + input + error. Разделять UI компоненты форм и логику валидации. Controlled компоненты для сложных случаев.',
    answerEn: 'Use a library (React Hook Form, Formik) — no need to reinvent the wheel. Define validation schemas with Zod/Yup — they can be reused on both the client and server. Abstract fields with a FormField component that wraps label + input + error. Keep form UI components separate from validation logic. Use controlled components for complex scenarios.',
  },
  {
    id: 'sd-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['state-management', 'architecture'],
    questionRu: 'Как выбрать стратегию управления состоянием для большого приложения?',
    questionEn: 'How do you choose a state management strategy for a large application?',
    answerRu: 'Разделить типы state: серверный (React Query/SWR), глобальный UI (Zustand/Redux), локальный (useState). Не хранить серверные данные в Redux — дублирование и рассинхронизация. URL state для фильтров и пагинации. Form state в React Hook Form. Глобальный state только для данных нужных в разных частях приложения.',
    answerEn: 'Separate state by type: server state (React Query/SWR), global UI state (Zustand/Redux), and local state (useState). Do not store server data in Redux — it leads to duplication and sync issues. Keep filters and pagination in URL state. Manage form state with React Hook Form. Use global state only for data needed across unrelated parts of the application.',
  },
  {
    id: 'sd-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['api', 'architecture', 'react-query'],
    questionRu: 'Как организовать работу с API запросами в большом проекте?',
    questionEn: 'How do you organize API requests in a large project?',
    answerRu: 'Слой API: отдельные функции/классы для каждого эндпоинта — не делать fetch прямо в компонентах. Centralized HTTP client (axios instance) с interceptors для auth токенов и ошибок. React Query для кеширования и синхронизации. Типизация через TypeScript. Обработка ошибок на уровне клиента — не в каждом компоненте отдельно.',
    answerEn: 'API layer: define separate functions/classes per endpoint — never call fetch directly inside components. Use a centralized HTTP client (axios instance) with interceptors for auth tokens and errors. Use React Query for caching and synchronization. Type everything with TypeScript. Handle errors at the client level rather than in each individual component.',
  },
  {
    id: 'sd-010',
    difficulty: 'HARD',
    order: 10,
    tags: ['optimistic-updates', 'react-query', 'ux'],
    questionRu: 'Как реализовать оптимистичные обновления UI?',
    questionEn: 'How do you implement optimistic UI updates?',
    answerRu: 'Оптимистичное обновление: обновить UI сразу до ответа сервера, откатить при ошибке. React Query: useMutation с onMutate (обновить кеш) + onError (откатить) + onSettled (инвалидировать). useOptimistic в React 19. Показывать pending state во время запроса. Критично для: лайков, корзины, чекбоксов — улучшает воспринимаемую скорость.',
    answerEn: 'Optimistic update: update the UI immediately before the server responds, then roll back on error. React Query: use useMutation with onMutate (update the cache) + onError (roll back) + onSettled (invalidate). React 19 introduces useOptimistic. Show a pending state during the request. Essential for likes, shopping carts, and checkboxes — greatly improves perceived performance.',
  },
  {
    id: 'sd-011',
    difficulty: 'HARD',
    order: 11,
    tags: ['realtime', 'websocket', 'sse'],
    questionRu: 'Как организовать real-time обновления в приложении?',
    questionEn: 'How do you implement real-time updates in an application?',
    answerRu: 'WebSocket для двусторонней связи (чат, совместное редактирование). SSE для однонаправленных обновлений (уведомления, live feed). Polling как fallback. Интеграция с React Query: socket событие → queryClient.invalidateQueries или setQueryData. Обработка переподключения и офлайн состояния. Оптимистичные обновления для своих действий.',
    answerEn: 'Use WebSocket for bidirectional communication (chat, collaborative editing). Use SSE for one-way updates (notifications, live feeds). Polling as a fallback. React Query integration: on socket event → call queryClient.invalidateQueries or setQueryData. Handle reconnection and offline state. Use optimistic updates for the user\'s own actions.',
  },
  {
    id: 'sd-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['url-state', 'routing', 'state-management'],
    questionRu: 'Как управлять URL state (фильтры, пагинация)?',
    questionEn: 'How do you manage URL state (filters, pagination)?',
    answerRu: 'Фильтры, сортировка, пагинация — в URL query params: /products?category=shoes&sort=price&page=2. Преимущества: sharable URL, работает кнопка назад, SEO. Синхронизировать через useSearchParams (Next.js) или useLocation+useHistory. URL как единственный источник истины для этих данных — не дублировать в Redux.',
    answerEn: 'Put filters, sorting, and pagination in URL query params: /products?category=shoes&sort=price&page=2. Benefits: shareable URL, back button works, SEO-friendly. Sync with useSearchParams (Next.js) or useLocation + useHistory. Treat the URL as the single source of truth for this data — do not duplicate it in Redux.',
  },
  {
    id: 'sd-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['feature-flags', 'scalability'],
    questionRu: 'Что такое Feature Flags и как реализовать?',
    questionEn: 'What are Feature Flags and how do you implement them?',
    answerRu: "Feature Flags — включение/отключение функций без деплоя. Позволяют: постепенный rollout, A/B тестирование, trunk-based development. Реализация: конфиг объект { featureName: boolean }, React контекст для доступа, хук useFeatureFlag('name'). Сервисы: LaunchDarkly, Unleash, самописное решение через env переменные.",
    answerEn: "Feature Flags let you enable or disable features without a deployment. They enable: gradual rollouts, A/B testing, and trunk-based development. Implementation: a config object { featureName: boolean }, a React context for access, and a useFeatureFlag('name') hook. Services: LaunchDarkly, Unleash, or a custom solution using environment variables.",
  },
  {
    id: 'sd-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['i18n', 'scalability'],
    questionRu: 'Как реализовать интернационализацию (i18n)?',
    questionEn: 'How do you implement internationalization (i18n)?',
    answerRu: "Библиотеки: react-i18next, next-intl для Next.js. Структура: JSON файлы переводов по языкам и namespace. Ключи вместо строк: t('auth.login.button'). Pluralization и форматирование дат/чисел через Intl API. Lazy loading переводов по языку. Определение языка: URL (/en/, /ru/), заголовок Accept-Language, localStorage.",
    answerEn: "Libraries: react-i18next, next-intl for Next.js. Structure: JSON translation files organized by language and namespace. Use keys instead of raw strings: t('auth.login.button'). Handle pluralization and date/number formatting via the Intl API. Lazy load translations per language. Detect language from: URL prefix (/en/, /ru/), Accept-Language header, or localStorage.",
  },
  {
    id: 'sd-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['error-handling', 'scalability'],
    questionRu: 'Как организовать обработку ошибок в приложении?',
    questionEn: 'How do you organize error handling in an application?',
    answerRu: 'Глобальный Error Boundary для неожиданных ошибок. API ошибки: централизованный обработчик в axios interceptor — toast уведомления, редирект на /login при 401. Типизированные ошибки — различать сетевые, валидационные, бизнес-ошибки. Логирование через Sentry. Retry логика для сетевых ошибок (React Query retries). Graceful degradation.',
    answerEn: 'Use a global Error Boundary for unexpected errors. API errors: a centralized handler in an axios interceptor — show toast notifications, redirect to /login on 401. Typed errors — distinguish between network, validation, and business errors. Log to Sentry. Add retry logic for network errors (React Query retries). Implement graceful degradation.',
  },
  {
    id: 'sd-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['notifications', 'toast', 'ux'],
    questionRu: 'Как спроектировать систему уведомлений (toast/notifications)?',
    questionEn: 'How do you design a notification system (toast/notifications)?',
    answerRu: "Централизованный стор уведомлений (Zustand или Context). API: notify({ type: 'success', message: '...' }). Компонент NotificationContainer рендерит список. Автоудаление по таймеру. Очередь при множестве уведомлений. Доступность: aria-live region для скринридеров. Библиотеки: react-hot-toast, sonner — хорошая альтернатива самописному.",
    answerEn: "A centralized notification store (Zustand or Context). API: notify({ type: 'success', message: '...' }). A NotificationContainer component renders the list. Auto-dismiss on a timer. Queue notifications when many arrive at once. Accessibility: use an aria-live region for screen readers. Libraries: react-hot-toast and sonner are great alternatives to a custom implementation.",
  },
  {
    id: 'sd-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['infinite-scroll', 'pagination', 'ux'],
    questionRu: 'Как реализовать бесконечный скролл vs пагинацию?',
    questionEn: 'How do you implement infinite scroll vs. pagination?',
    answerRu: 'Пагинация: лучше для SEO, позволяет перейти на конкретную страницу, проще реализация. Бесконечный скролл: лучший UX для лент контента. Реализация: IntersectionObserver на sentinel элемент внизу списка. React Query useInfiniteQuery. Виртуализация для большого количества элементов. Cursor-based пагинация на API предпочтительнее offset для real-time данных.',
    answerEn: 'Pagination: better for SEO, allows jumping to a specific page, simpler to implement. Infinite scroll: better UX for content feeds. Implementation: attach an IntersectionObserver to a sentinel element at the bottom of the list. Use React Query useInfiniteQuery. Add virtualization for large lists. Prefer cursor-based pagination over offset-based on the API for real-time data.',
  },
  {
    id: 'sd-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['auth', 'security', 'architecture'],
    questionRu: 'Как проектировать авторизацию на фронтенде?',
    questionEn: 'How do you design authentication on the frontend?',
    answerRu: 'Хранить токены безопасно (httpOnly cookie для refresh, memory для access). Axios interceptor добавляет Authorization заголовок. Автообновление access token через refresh token. Protected routes — redirect на login если не авторизован. Role-based UI: показывать/скрывать элементы по ролям (только UX, не безопасность — проверка на сервере). Logout — очистить все токены и кеш.',
    answerEn: 'Store tokens securely (httpOnly cookie for refresh token, in-memory for access token). An axios interceptor attaches the Authorization header. Auto-refresh the access token using the refresh token. Protected routes redirect to login when unauthenticated. Role-based UI shows/hides elements based on roles (UX only — security enforcement belongs on the server). Logout must clear all tokens and cache.',
  },
  {
    id: 'sd-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['micro-frontends', 'architecture'],
    questionRu: 'Что такое micro-frontends и когда использовать?',
    questionEn: 'What are micro-frontends and when should you use them?',
    answerRu: 'Micro-frontends — разбивка фронтенда на независимые части разрабатываемые разными командами. Каждая часть — отдельный деплой, свой стек. Когда использовать: большая команда (5+ команд), независимый деплой частей, разные технологии. Не использовать для: малых команд, одного стека — overhead не оправдан.',
    answerEn: 'Micro-frontends split the frontend into independent pieces developed by separate teams. Each piece is deployed independently and can use its own tech stack. Use them when: you have many teams (5+), parts need independent deployments, or different technologies are involved. Avoid them for small teams with a single stack — the overhead is not justified.',
  },
  {
    id: 'sd-020',
    difficulty: 'HARD',
    order: 20,
    tags: ['micro-frontends', 'module-federation'],
    questionRu: 'Какие подходы к реализации micro-frontends существуют?',
    questionEn: 'What are the approaches to implementing micro-frontends?',
    answerRu: 'Iframe: максимальная изоляция, плохой UX. Web Components: нативные, стековая независимость, сложная интеграция. Module Federation (Webpack 5): runtime загрузка модулей из других приложений — популярный подход. Single-SPA: оркестратор для нескольких SPA. Server-side composition (Edge/CDN): включение фрагментов на уровне сервера.',
    answerEn: 'Iframes: maximum isolation, poor UX. Web Components: native, stack-agnostic, but complex to integrate. Module Federation (Webpack 5): load modules from other applications at runtime — the most popular approach. Single-SPA: an orchestrator for multiple SPAs. Server-side composition (Edge/CDN): assembling page fragments at the server level.',
  },
  {
    id: 'sd-021',
    difficulty: 'HARD',
    order: 21,
    tags: ['micro-frontends', 'module-federation', 'webpack'],
    questionRu: 'Что такое Module Federation?',
    questionEn: 'What is Module Federation?',
    answerRu: 'Module Federation (Webpack 5) позволяет приложениям загружать модули из других приложений в runtime. Host приложение потребляет Remote компоненты. Shared зависимости (React) не дублируются. Каждый remote деплоится независимо. Vite аналог: @originjs/vite-plugin-federation. Позволяет разным командам деплоить независимо без пересборки host.',
    answerEn: 'Module Federation (Webpack 5) allows applications to load modules from other applications at runtime. The host application consumes remote components. Shared dependencies (such as React) are not duplicated. Each remote is deployed independently. The Vite equivalent is @originjs/vite-plugin-federation. This enables different teams to deploy independently without rebuilding the host.',
  },
  {
    id: 'sd-022',
    difficulty: 'HARD',
    order: 22,
    tags: ['micro-frontends', 'state-management', 'communication'],
    questionRu: 'Как организовать shared state между micro-frontends?',
    questionEn: 'How do you manage shared state between micro-frontends?',
    answerRu: 'Custom Events / BroadcastChannel: события между независимыми приложениями. Shared стор через Module Federation. URL как источник истины для роутинга. Shared библиотека для типов и утилит. Избегать тесной связанности — micro-frontends должны быть независимы. Event bus для коммуникации без прямых зависимостей.',
    answerEn: 'Custom Events / BroadcastChannel: for events between independent applications. Share a store via Module Federation. Use the URL as the source of truth for routing state. A shared library for types and utilities. Avoid tight coupling — micro-frontends should remain independent. An event bus enables communication without direct dependencies.',
  },
  {
    id: 'sd-023',
    difficulty: 'HARD',
    order: 23,
    tags: ['micro-frontends', 'dependencies', 'module-federation'],
    questionRu: 'Как решать проблему дублирования зависимостей в micro-frontends?',
    questionEn: 'How do you solve the problem of duplicated dependencies in micro-frontends?',
    answerRu: 'Module Federation shared config: указать общие зависимости (react, react-dom) как singleton — загружаются один раз. Версионирование: semver совместимые версии шарятся автоматически. Несовместимые версии загружаются отдельно. Мониторинг размера бандла. Общий Design System как отдельный пакет. Договорённость команд о версиях ключевых зависимостей.',
    answerEn: 'Module Federation shared config: declare shared dependencies (react, react-dom) as singletons — they are loaded only once. Versioning: semver-compatible versions are shared automatically. Incompatible versions are loaded separately. Monitor bundle sizes. Publish the shared Design System as a separate package. Teams should align on versions of key dependencies.',
  },
];
