import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'sd-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['components', 'architecture'],
    questionRu: 'Что такое компонентная архитектура и каковы её принципы?',
    questionEn: 'What is component architecture and what are its principles?',
    answerRu: '**Компонентная архитектура** — разбивка UI на изолированные переиспользуемые компоненты.\n\nПринципы:\n- **Единственная ответственность** — один компонент, одна задача\n- **Изоляция** — компонент не знает о внешнем мире\n- **Переиспользуемость**\n- **Композиция** вместо наследования\n\nКомпоненты общаются через `props`/`events`, не напрямую.',
    answerEn: '**Component architecture** is the practice of splitting UI into isolated, reusable components.\n\nPrinciples:\n- **Single responsibility** — one component, one task\n- **Isolation** — a component has no knowledge of the outside world\n- **Reusability**\n- **Composition** over inheritance\n\nComponents communicate via `props`/`events`, not directly.',
  },
  {
    id: 'sd-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['architecture', 'folder-structure'],
    questionRu: 'Как организовать структуру папок в большом фронтенд проекте?',
    questionEn: 'How do you organize the folder structure in a large frontend project?',
    answerRu: '**Feature-based структура**: папки по фичам (`auth/`, `dashboard/`, `profile/`) — каждая содержит свои компоненты, хуки, стили, тесты.\n\nЛучше масштабируется, чем **type-based** (`components/`, `hooks/`, `styles/`).\n\n- `shared/` — общий код\n- `index.ts` barrel exports для удобного импорта\n- Плоская структура лучше глубокой вложенности',
    answerEn: '**Feature-based structure**: folders organized by feature (`auth/`, `dashboard/`, `profile/`) — each containing its own components, hooks, styles, and tests.\n\nScales better than **type-based** organization (`components/`, `hooks/`, `styles/`).\n\n- `shared/` folder holds common code\n- `index.ts` barrel exports simplify imports\n- Flat structure is preferred over deep nesting',
  },
  {
    id: 'sd-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['design-system', 'components'],
    questionRu: 'Что такое Design System и как его организовать?',
    questionEn: 'What is a Design System and how do you organize one?',
    answerRu: '**Design System** — библиотека UI компонентов с единым визуальным языком.\n\nСостав:\n- **Токены** — цвета, отступы, типографика\n- **Базовые компоненты** — `Button`, `Input`, `Modal`\n- **Составные компоненты**\n\nИнструменты:\n- **Storybook** для документации и разработки\n- Версионирование через `npm` пакет\n- Монорепозиторий для Design System + продукт',
    answerEn: 'A **Design System** is a UI component library with a unified visual language.\n\nComposition:\n- **Tokens** — colors, spacing, typography\n- **Primitive components** — `Button`, `Input`, `Modal`\n- **Composite components**\n\nTooling:\n- **Storybook** for documentation and development\n- Versioned as an `npm` package\n- A monorepo is a common setup for hosting the Design System alongside the product',
  },
  {
    id: 'sd-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['components', 'reusability'],
    questionRu: 'Как проектировать переиспользуемый компонент?',
    questionEn: 'How do you design a reusable component?',
    answerRu: '- **API через `props`**: только необходимые, с разумными дефолтами\n- **Composition** через `children`/slots вместо жёстко зашитой разметки\n- Не привязываться к конкретным данным — компонент работает с любыми\n- Предоставлять `ref` для императивного API\n- Документировать через **TypeScript** типы и **Storybook**\n- Версионировать изменения',
    answerEn: '- **Props-based API**: expose only what is necessary, with sensible defaults\n- **Composition** via `children`/slots over hard-coded markup\n- Avoid coupling to specific data shapes — the component should work with any data\n- Expose a `ref` for imperative API use\n- Document with **TypeScript** types and **Storybook**\n- Version breaking changes',
  },
  {
    id: 'sd-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['atomic-design', 'components'],
    questionRu: 'Что такое Atomic Design?',
    questionEn: 'What is Atomic Design?',
    answerRu: "**Atomic Design** — методология Брэда Фроста для иерархии компонентов.\n\n- **Atoms** (атомы): `Button`, `Input`, `Icon` — неделимые элементы\n- **Molecules** (молекулы): `SearchBar` = `Input` + `Button`\n- **Organisms** (организмы): `Header` = `Logo` + `Nav` + `SearchBar`\n- **Templates**: layout без данных\n- **Pages**: template с реальными данными\n\nДаёт общий язык команде.",
    answerEn: "**Atomic Design** is Brad Frost's methodology for a component hierarchy.\n\n- **Atoms**: `Button`, `Input`, `Icon` — indivisible elements\n- **Molecules**: `SearchBar` = `Input` + `Button`\n- **Organisms**: `Header` = `Logo` + `Nav` + `SearchBar`\n- **Templates**: layout without real data\n- **Pages**: template with actual data\n\nProvides a shared vocabulary for the team.",
  },
  {
    id: 'sd-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['routing', 'spa'],
    questionRu: 'Как организовать роутинг в большом SPA?',
    questionEn: 'How do you organize routing in a large SPA?',
    answerRu: '- Разделить на **публичные** и **защищённые** маршруты\n- **Lazy loading** для каждого роута — уменьшает начальный бандл\n- **Nested routes** для shared layouts\n- Централизованная конфигурация маршрутов вместо разброса по компонентам\n- **Guards**/**middleware** для авторизации\n- Breadcrumbs и навигация на основе конфигурации маршрутов',
    answerEn: '- Split routes into **public** and **protected**\n- **Lazy load** each route to reduce the initial bundle\n- **Nested routes** for shared layouts\n- Keep route configuration **centralized** rather than scattered across components\n- Add **guards**/**middleware** for authorization\n- Drive breadcrumbs and navigation from the route configuration',
  },
  {
    id: 'sd-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['forms', 'validation'],
    questionRu: 'Как спроектировать систему форм для большого приложения?',
    questionEn: 'How do you design a form system for a large application?',
    answerRu: '- Использовать библиотеку (**React Hook Form**, **Formik**) — не изобретать велосипед\n- Схема валидации через **Zod**/**Yup** — переиспользуется на клиенте и сервере\n- Абстракция над полями: компонент `FormField` оборачивает `label` + `input` + `error`\n- Разделять UI компоненты форм и логику валидации\n- **Controlled** компоненты для сложных случаев',
    answerEn: '- Use a library (**React Hook Form**, **Formik**) — no need to reinvent the wheel\n- Define validation schemas with **Zod**/**Yup** — reusable on both client and server\n- Abstract fields with a `FormField` component that wraps `label` + `input` + `error`\n- Keep form UI components separate from validation logic\n- Use **controlled components** for complex scenarios',
  },
  {
    id: 'sd-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['state-management', 'architecture'],
    questionRu: 'Как выбрать стратегию управления состоянием для большого приложения?',
    questionEn: 'How do you choose a state management strategy for a large application?',
    answerRu: 'Разделить типы state:\n- **Серверный** — React Query / SWR\n- **Глобальный UI** — Zustand / Redux\n- **Локальный** — `useState`\n\nНе хранить серверные данные в Redux — дублирование и рассинхронизация.\n\n- **URL state** для фильтров и пагинации\n- **React Hook Form** для form state\n- Глобальный state только для данных, нужных в разных частях приложения',
    answerEn: 'Separate state by type:\n- **Server state** — React Query / SWR\n- **Global UI state** — Zustand / Redux\n- **Local state** — `useState`\n\nDo not store server data in Redux — it leads to duplication and sync issues.\n\n- **URL state** for filters and pagination\n- **React Hook Form** for form state\n- Global state only for data needed across unrelated parts of the application',
  },
  {
    id: 'sd-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['api', 'architecture', 'react-query'],
    questionRu: 'Как организовать работу с API запросами в большом проекте?',
    questionEn: 'How do you organize API requests in a large project?',
    answerRu: '- **API слой**: отдельные функции/классы для каждого эндпоинта — не делать `fetch` прямо в компонентах\n- **Centralized HTTP client** (`axios` instance) с interceptors для auth токенов и ошибок\n- **React Query** для кеширования и синхронизации\n- Типизация через **TypeScript**\n- Обработка ошибок на уровне клиента — не в каждом компоненте отдельно',
    answerEn: '- **API layer**: separate functions/classes per endpoint — never call `fetch` directly inside components\n- **Centralized HTTP client** (`axios` instance) with interceptors for auth tokens and errors\n- **React Query** for caching and synchronization\n- Type everything with **TypeScript**\n- Handle errors at the client level rather than in each individual component',
  },
  {
    id: 'sd-010',
    difficulty: 'HARD',
    order: 10,
    tags: ['optimistic-updates', 'react-query', 'ux'],
    questionRu: 'Как реализовать оптимистичные обновления UI?',
    questionEn: 'How do you implement optimistic UI updates?',
    answerRu: '**Оптимистичное обновление**: обновить UI сразу до ответа сервера, откатить при ошибке.\n\n**React Query** — `useMutation` с:\n- `onMutate` — обновить кеш\n- `onError` — откатить\n- `onSettled` — инвалидировать\n\n`useOptimistic` в **React 19**.\n\nПоказывать **pending state** во время запроса. Критично для: лайков, корзины, чекбоксов — улучшает воспринимаемую скорость.',
    answerEn: '**Optimistic update**: update the UI immediately before the server responds, then roll back on error.\n\n**React Query** — `useMutation` with:\n- `onMutate` — update the cache\n- `onError` — roll back\n- `onSettled` — invalidate\n\n`useOptimistic` in **React 19**.\n\nShow a **pending state** during the request. Essential for likes, shopping carts, and checkboxes — greatly improves perceived performance.',
  },
  {
    id: 'sd-011',
    difficulty: 'HARD',
    order: 11,
    tags: ['realtime', 'websocket', 'sse'],
    questionRu: 'Как организовать real-time обновления в приложении?',
    questionEn: 'How do you implement real-time updates in an application?',
    answerRu: '- **WebSocket** — двусторонняя связь (чат, совместное редактирование)\n- **SSE** — однонаправленные обновления (уведомления, live feed)\n- **Polling** как fallback\n\nИнтеграция с **React Query**: socket событие → `queryClient.invalidateQueries` или `setQueryData`.\n\nОбработка переподключения и офлайн состояния. Оптимистичные обновления для своих действий.',
    answerEn: '- **WebSocket** — bidirectional communication (chat, collaborative editing)\n- **SSE** — one-way updates (notifications, live feeds)\n- **Polling** as a fallback\n\n**React Query** integration: on socket event → call `queryClient.invalidateQueries` or `setQueryData`.\n\nHandle reconnection and offline state. Use optimistic updates for the user\'s own actions.',
  },
  {
    id: 'sd-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['url-state', 'routing', 'state-management'],
    questionRu: 'Как управлять URL state (фильтры, пагинация)?',
    questionEn: 'How do you manage URL state (filters, pagination)?',
    answerRu: 'Фильтры, сортировка, пагинация — в **URL query params**:\n`/products?category=shoes&sort=price&page=2`\n\nПреимущества:\n- Sharable URL\n- Работает кнопка «назад»\n- SEO-friendly\n\nСинхронизировать через `useSearchParams` (Next.js) или `useLocation` + `useHistory`.\n\nURL как **единственный источник истины** — не дублировать в Redux.',
    answerEn: 'Put filters, sorting, and pagination in **URL query params**:\n`/products?category=shoes&sort=price&page=2`\n\nBenefits:\n- Shareable URL\n- Back button works\n- SEO-friendly\n\nSync with `useSearchParams` (Next.js) or `useLocation` + `useHistory`.\n\nTreat the URL as the **single source of truth** — do not duplicate it in Redux.',
  },
  {
    id: 'sd-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['feature-flags', 'scalability'],
    questionRu: 'Что такое Feature Flags и как реализовать?',
    questionEn: 'What are Feature Flags and how do you implement them?',
    answerRu: "**Feature Flags** — включение/отключение функций без деплоя.\n\nПозволяют:\n- Постепенный rollout\n- A/B тестирование\n- Trunk-based development\n\nРеализация:\n- Конфиг объект `{ featureName: boolean }`\n- React контекст для доступа\n- Хук `useFeatureFlag('name')`\n\nСервисы: **LaunchDarkly**, **Unleash**, самописное решение через `env` переменные.",
    answerEn: "**Feature Flags** let you enable or disable features without a deployment.\n\nThey enable:\n- Gradual rollouts\n- A/B testing\n- Trunk-based development\n\nImplementation:\n- A config object `{ featureName: boolean }`\n- A React context for access\n- A `useFeatureFlag('name')` hook\n\nServices: **LaunchDarkly**, **Unleash**, or a custom solution using environment variables.",
  },
  {
    id: 'sd-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['i18n', 'scalability'],
    questionRu: 'Как реализовать интернационализацию (i18n)?',
    questionEn: 'How do you implement internationalization (i18n)?',
    answerRu: "Библиотеки: **react-i18next**, **next-intl** для Next.js.\n\nСтруктура: JSON файлы переводов по языкам и namespace.\n\n- Ключи вместо строк: `t('auth.login.button')`\n- Pluralization и форматирование дат/чисел через `Intl` API\n- Lazy loading переводов по языку\n\nОпределение языка:\n- URL (`/en/`, `/ru/`)\n- Заголовок `Accept-Language`\n- `localStorage`",
    answerEn: "Libraries: **react-i18next**, **next-intl** for Next.js.\n\nStructure: JSON translation files organized by language and namespace.\n\n- Use keys instead of raw strings: `t('auth.login.button')`\n- Pluralization and date/number formatting via the `Intl` API\n- Lazy load translations per language\n\nDetect language from:\n- URL prefix (`/en/`, `/ru/`)\n- `Accept-Language` header\n- `localStorage`",
  },
  {
    id: 'sd-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['error-handling', 'scalability'],
    questionRu: 'Как организовать обработку ошибок в приложении?',
    questionEn: 'How do you organize error handling in an application?',
    answerRu: '- **Global Error Boundary** для неожиданных ошибок\n- **API ошибки**: централизованный обработчик в `axios` interceptor — toast уведомления, редирект на `/login` при `401`\n- **Типизированные ошибки** — различать сетевые, валидационные, бизнес-ошибки\n- Логирование через **Sentry**\n- **Retry логика** для сетевых ошибок (React Query retries)\n- **Graceful degradation**',
    answerEn: '- **Global Error Boundary** for unexpected errors\n- **API errors**: a centralized handler in an `axios` interceptor — show toast notifications, redirect to `/login` on `401`\n- **Typed errors** — distinguish between network, validation, and business errors\n- Log to **Sentry**\n- **Retry logic** for network errors (React Query retries)\n- **Graceful degradation**',
  },
  {
    id: 'sd-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['notifications', 'toast', 'ux'],
    questionRu: 'Как спроектировать систему уведомлений (toast/notifications)?',
    questionEn: 'How do you design a notification system (toast/notifications)?',
    answerRu: "- **Централизованный стор** уведомлений (Zustand или Context)\n- API: `notify({ type: 'success', message: '...' })`\n- Компонент `NotificationContainer` рендерит список\n- Автоудаление по таймеру\n- Очередь при множестве уведомлений\n- **Доступность**: `aria-live` region для скринридеров\n\nБиблиотеки: **react-hot-toast**, **sonner** — хорошая альтернатива самописному.",
    answerEn: "- **Centralized notification store** (Zustand or Context)\n- API: `notify({ type: 'success', message: '...' })`\n- A `NotificationContainer` component renders the list\n- Auto-dismiss on a timer\n- Queue notifications when many arrive at once\n- **Accessibility**: `aria-live` region for screen readers\n\nLibraries: **react-hot-toast** and **sonner** are great alternatives to a custom implementation.",
  },
  {
    id: 'sd-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['infinite-scroll', 'pagination', 'ux'],
    questionRu: 'Как реализовать бесконечный скролл vs пагинацию?',
    questionEn: 'How do you implement infinite scroll vs. pagination?',
    answerRu: '**Пагинация**:\n- Лучше для SEO\n- Позволяет перейти на конкретную страницу\n- Проще реализация\n\n**Бесконечный скролл**:\n- Лучший UX для лент контента\n- Реализация: `IntersectionObserver` на sentinel элемент внизу списка\n- `useInfiniteQuery` из React Query\n\nВиртуализация для большого количества элементов. **Cursor-based** пагинация предпочтительнее offset для real-time данных.',
    answerEn: '**Pagination**:\n- Better for SEO\n- Allows jumping to a specific page\n- Simpler to implement\n\n**Infinite scroll**:\n- Better UX for content feeds\n- Implementation: `IntersectionObserver` on a sentinel element at the bottom of the list\n- Use `useInfiniteQuery` from React Query\n\nAdd virtualization for large lists. Prefer **cursor-based** pagination over offset-based for real-time data.',
  },
  {
    id: 'sd-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['auth', 'security', 'architecture'],
    questionRu: 'Как проектировать авторизацию на фронтенде?',
    questionEn: 'How do you design authentication on the frontend?',
    answerRu: '- Хранить токены безопасно: **httpOnly cookie** для refresh, **in-memory** для access\n- `axios` interceptor добавляет `Authorization` заголовок\n- Автообновление access token через refresh token\n- **Protected routes** — redirect на `/login` если не авторизован\n- **Role-based UI**: показывать/скрывать элементы по ролям (только UX, проверка на сервере)\n- Logout — очистить все токены и кеш',
    answerEn: '- Store tokens securely: **httpOnly cookie** for refresh token, **in-memory** for access token\n- An `axios` interceptor attaches the `Authorization` header\n- Auto-refresh the access token using the refresh token\n- **Protected routes** redirect to `/login` when unauthenticated\n- **Role-based UI** shows/hides elements based on roles (UX only — security enforcement belongs on the server)\n- Logout must clear all tokens and cache',
  },
  {
    id: 'sd-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['micro-frontends', 'architecture'],
    questionRu: 'Что такое micro-frontends и когда использовать?',
    questionEn: 'What are micro-frontends and when should you use them?',
    answerRu: '**Micro-frontends** — разбивка фронтенда на независимые части, разрабатываемые разными командами. Каждая часть — отдельный деплой, свой стек.\n\n**Когда использовать**:\n- Большая команда (5+ команд)\n- Независимый деплой частей\n- Разные технологии\n\n**Не использовать** для малых команд с одним стеком — overhead не оправдан.',
    answerEn: '**Micro-frontends** split the frontend into independent pieces developed by separate teams. Each piece is deployed independently and can use its own tech stack.\n\n**Use them when**:\n- Many teams (5+)\n- Parts need independent deployments\n- Different technologies are involved\n\n**Avoid** for small teams with a single stack — the overhead is not justified.',
  },
  {
    id: 'sd-020',
    difficulty: 'HARD',
    order: 20,
    tags: ['micro-frontends', 'module-federation'],
    questionRu: 'Какие подходы к реализации micro-frontends существуют?',
    questionEn: 'What are the approaches to implementing micro-frontends?',
    answerRu: '- **Iframe**: максимальная изоляция, плохой UX\n- **Web Components**: нативные, стековая независимость, сложная интеграция\n- **Module Federation** (Webpack 5): runtime загрузка модулей из других приложений — популярный подход\n- **Single-SPA**: оркестратор для нескольких SPA\n- **Server-side composition** (Edge/CDN): включение фрагментов на уровне сервера',
    answerEn: '- **Iframes**: maximum isolation, poor UX\n- **Web Components**: native, stack-agnostic, but complex to integrate\n- **Module Federation** (Webpack 5): load modules from other applications at runtime — the most popular approach\n- **Single-SPA**: an orchestrator for multiple SPAs\n- **Server-side composition** (Edge/CDN): assembling page fragments at the server level',
  },
  {
    id: 'sd-021',
    difficulty: 'HARD',
    order: 21,
    tags: ['micro-frontends', 'module-federation', 'webpack'],
    questionRu: 'Что такое Module Federation?',
    questionEn: 'What is Module Federation?',
    answerRu: '**Module Federation** (Webpack 5) позволяет приложениям загружать модули из других приложений в runtime.\n\n- **Host** приложение потребляет **Remote** компоненты\n- **Shared** зависимости (`React`) не дублируются\n- Каждый remote деплоится независимо\n\nVite аналог: `@originjs/vite-plugin-federation`.\n\nПозволяет разным командам деплоить независимо без пересборки host.',
    answerEn: '**Module Federation** (Webpack 5) allows applications to load modules from other applications at runtime.\n\n- The **host** application consumes **remote** components\n- **Shared** dependencies (such as `React`) are not duplicated\n- Each remote is deployed independently\n\nThe Vite equivalent is `@originjs/vite-plugin-federation`.\n\nEnables different teams to deploy independently without rebuilding the host.',
  },
  {
    id: 'sd-022',
    difficulty: 'HARD',
    order: 22,
    tags: ['micro-frontends', 'state-management', 'communication'],
    questionRu: 'Как организовать shared state между micro-frontends?',
    questionEn: 'How do you manage shared state between micro-frontends?',
    answerRu: '- **Custom Events** / **BroadcastChannel** — события между независимыми приложениями\n- Shared стор через **Module Federation**\n- **URL** как источник истины для роутинга\n- Shared библиотека для типов и утилит\n- **Event bus** для коммуникации без прямых зависимостей\n\nИзбегать тесной связанности — micro-frontends должны быть независимы.',
    answerEn: '- **Custom Events** / **BroadcastChannel** — for events between independent applications\n- Share a store via **Module Federation**\n- **URL** as the source of truth for routing state\n- A shared library for types and utilities\n- **Event bus** enables communication without direct dependencies\n\nAvoid tight coupling — micro-frontends should remain independent.',
  },
  {
    id: 'sd-023',
    difficulty: 'HARD',
    order: 23,
    tags: ['micro-frontends', 'dependencies', 'module-federation'],
    questionRu: 'Как решать проблему дублирования зависимостей в micro-frontends?',
    questionEn: 'How do you solve the problem of duplicated dependencies in micro-frontends?',
    answerRu: '**Module Federation** shared config: указать общие зависимости (`react`, `react-dom`) как `singleton` — загружаются один раз.\n\n- Semver-совместимые версии шарятся автоматически\n- Несовместимые версии загружаются отдельно\n- Мониторинг размера бандла\n- Общий **Design System** как отдельный пакет\n\nКоманды должны договариваться о версиях ключевых зависимостей.',
    answerEn: '**Module Federation** shared config: declare shared dependencies (`react`, `react-dom`) as `singleton` — they are loaded only once.\n\n- Semver-compatible versions are shared automatically\n- Incompatible versions are loaded separately\n- Monitor bundle sizes\n- Publish the shared **Design System** as a separate package\n\nTeams should align on versions of key dependencies.',
  },
];
