import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'sd-001',
    difficulty: 'MEDIUM',
    order: 1,
    tags: ['components', 'architecture'],
    questionRu: 'Что такое компонентная архитектура и каковы её принципы?',
    questionEn: 'Что такое компонентная архитектура и каковы её принципы?',
    answerRu: 'Компонентная архитектура — разбивка UI на изолированные переиспользуемые компоненты. Принципы: единственная ответственность (один компонент — одна задача), изоляция (компонент не знает о внешнем мире), переиспользуемость, композиция вместо наследования. Компоненты общаются через props/events, не напрямую.',
    answerEn: 'Компонентная архитектура — разбивка UI на изолированные переиспользуемые компоненты. Принципы: единственная ответственность (один компонент — одна задача), изоляция (компонент не знает о внешнем мире), переиспользуемость, композиция вместо наследования. Компоненты общаются через props/events, не напрямую.',
  },
  {
    id: 'sd-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['architecture', 'folder-structure'],
    questionRu: 'Как организовать структуру папок в большом фронтенд проекте?',
    questionEn: 'Как организовать структуру папок в большом фронтенд проекте?',
    answerRu: 'Feature-based структура: папки по фичам (auth/, dashboard/, profile/) — каждая содержит свои компоненты, хуки, стили, тесты. Лучше масштабируется чем type-based (components/, hooks/, styles/). Shared папка для общего кода. Barrel exports (index.ts) для удобного импорта. Плоская структура лучше глубокой вложенности.',
    answerEn: 'Feature-based структура: папки по фичам (auth/, dashboard/, profile/) — каждая содержит свои компоненты, хуки, стили, тесты. Лучше масштабируется чем type-based (components/, hooks/, styles/). Shared папка для общего кода. Barrel exports (index.ts) для удобного импорта. Плоская структура лучше глубокой вложенности.',
  },
  {
    id: 'sd-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['design-system', 'components'],
    questionRu: 'Что такое Design System и как его организовать?',
    questionEn: 'Что такое Design System и как его организовать?',
    answerRu: 'Design System — библиотека UI компонентов с единым визуальным языком: токены (цвета, отступы, типографика), базовые компоненты (Button, Input, Modal), составные компоненты. Инструменты: Storybook для документации и разработки. Версионирование через npm пакет. Монорепозиторий для Design System + продукт.',
    answerEn: 'Design System — библиотека UI компонентов с единым визуальным языком: токены (цвета, отступы, типографика), базовые компоненты (Button, Input, Modal), составные компоненты. Инструменты: Storybook для документации и разработки. Версионирование через npm пакет. Монорепозиторий для Design System + продукт.',
  },
  {
    id: 'sd-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['components', 'reusability'],
    questionRu: 'Как проектировать переиспользуемый компонент?',
    questionEn: 'Как проектировать переиспользуемый компонент?',
    answerRu: 'API через props: только необходимые, с разумными дефолтами. Composition через children/slots вместо жёстко зашитой разметки. Не привязываться к конкретным данным — компонент работает с любыми. Предоставлять ref для императивного API. Документировать через TypeScript типы и Storybook. Версионировать изменения.',
    answerEn: 'API через props: только необходимые, с разумными дефолтами. Composition через children/slots вместо жёстко зашитой разметки. Не привязываться к конкретным данным — компонент работает с любыми. Предоставлять ref для императивного API. Документировать через TypeScript типы и Storybook. Версионировать изменения.',
  },
  {
    id: 'sd-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['atomic-design', 'components'],
    questionRu: 'Что такое Atomic Design?',
    questionEn: 'Что такое Atomic Design?',
    answerRu: 'Atomic Design — методология Брэда Фроста для иерархии компонентов. Atoms (атомы): Button, Input, Icon — неделимые элементы. Molecules (молекулы): SearchBar = Input + Button. Organisms (организмы): Header = Logo + Nav + SearchBar. Templates: layout без данных. Pages: template с реальными данными. Даёт общий язык команде.',
    answerEn: 'Atomic Design — методология Брэда Фроста для иерархии компонентов. Atoms (атомы): Button, Input, Icon — неделимые элементы. Molecules (молекулы): SearchBar = Input + Button. Organisms (организмы): Header = Logo + Nav + SearchBar. Templates: layout без данных. Pages: template с реальными данными. Даёт общий язык команде.',
  },
  {
    id: 'sd-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['routing', 'spa'],
    questionRu: 'Как организовать роутинг в большом SPA?',
    questionEn: 'Как организовать роутинг в большом SPA?',
    answerRu: 'Разделить на публичные и защищённые маршруты. Lazy loading для каждого роута — уменьшает начальный бандл. Nested routes для layouts. Централизованная конфигурация маршрутов вместо разброса по компонентам. Guards/middleware для авторизации. Breadcrumbs и навигация на основе конфигурации маршрутов.',
    answerEn: 'Разделить на публичные и защищённые маршруты. Lazy loading для каждого роута — уменьшает начальный бандл. Nested routes для layouts. Централизованная конфигурация маршрутов вместо разброса по компонентам. Guards/middleware для авторизации. Breadcrumbs и навигация на основе конфигурации маршрутов.',
  },
  {
    id: 'sd-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['forms', 'validation'],
    questionRu: 'Как спроектировать систему форм для большого приложения?',
    questionEn: 'Как спроектировать систему форм для большого приложения?',
    answerRu: 'Использовать библиотеку (React Hook Form, Formik) — не изобретать велосипед. Схема валидации через Zod/Yup — переиспользуется на клиенте и сервере. Абстракция над полями: компонент FormField оборачивает label + input + error. Разделять UI компоненты форм и логику валидации. Controlled компоненты для сложных случаев.',
    answerEn: 'Использовать библиотеку (React Hook Form, Formik) — не изобретать велосипед. Схема валидации через Zod/Yup — переиспользуется на клиенте и сервере. Абстракция над полями: компонент FormField оборачивает label + input + error. Разделять UI компоненты форм и логику валидации. Controlled компоненты для сложных случаев.',
  },
  {
    id: 'sd-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['state-management', 'architecture'],
    questionRu: 'Как выбрать стратегию управления состоянием для большого приложения?',
    questionEn: 'Как выбрать стратегию управления состоянием для большого приложения?',
    answerRu: 'Разделить типы state: серверный (React Query/SWR), глобальный UI (Zustand/Redux), локальный (useState). Не хранить серверные данные в Redux — дублирование и рассинхронизация. URL state для фильтров и пагинации. Form state в React Hook Form. Глобальный state только для данных нужных в разных частях приложения.',
    answerEn: 'Разделить типы state: серверный (React Query/SWR), глобальный UI (Zustand/Redux), локальный (useState). Не хранить серверные данные в Redux — дублирование и рассинхронизация. URL state для фильтров и пагинации. Form state в React Hook Form. Глобальный state только для данных нужных в разных частях приложения.',
  },
  {
    id: 'sd-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['api', 'architecture', 'react-query'],
    questionRu: 'Как организовать работу с API запросами в большом проекте?',
    questionEn: 'Как организовать работу с API запросами в большом проекте?',
    answerRu: 'Слой API: отдельные функции/классы для каждого эндпоинта — не делать fetch прямо в компонентах. Centralized HTTP client (axios instance) с interceptors для auth токенов и ошибок. React Query для кеширования и синхронизации. Типизация через TypeScript. Обработка ошибок на уровне клиента — не в каждом компоненте отдельно.',
    answerEn: 'Слой API: отдельные функции/классы для каждого эндпоинта — не делать fetch прямо в компонентах. Centralized HTTP client (axios instance) с interceptors для auth токенов и ошибок. React Query для кеширования и синхронизации. Типизация через TypeScript. Обработка ошибок на уровне клиента — не в каждом компоненте отдельно.',
  },
  {
    id: 'sd-010',
    difficulty: 'HARD',
    order: 10,
    tags: ['optimistic-updates', 'react-query', 'ux'],
    questionRu: 'Как реализовать оптимистичные обновления UI?',
    questionEn: 'Как реализовать оптимистичные обновления UI?',
    answerRu: 'Оптимистичное обновление: обновить UI сразу до ответа сервера, откатить при ошибке. React Query: useMutation с onMutate (обновить кеш) + onError (откатить) + onSettled (инвалидировать). useOptimistic в React 19. Показывать pending state во время запроса. Критично для: лайков, корзины, чекбоксов — улучшает воспринимаемую скорость.',
    answerEn: 'Оптимистичное обновление: обновить UI сразу до ответа сервера, откатить при ошибке. React Query: useMutation с onMutate (обновить кеш) + onError (откатить) + onSettled (инвалидировать). useOptimistic в React 19. Показывать pending state во время запроса. Критично для: лайков, корзины, чекбоксов — улучшает воспринимаемую скорость.',
  },
  {
    id: 'sd-011',
    difficulty: 'HARD',
    order: 11,
    tags: ['realtime', 'websocket', 'sse'],
    questionRu: 'Как организовать real-time обновления в приложении?',
    questionEn: 'Как организовать real-time обновления в приложении?',
    answerRu: 'WebSocket для двусторонней связи (чат, совместное редактирование). SSE для однонаправленных обновлений (уведомления, live feed). Polling как fallback. Интеграция с React Query: socket событие → queryClient.invalidateQueries или setQueryData. Обработка переподключения и офлайн состояния. Оптимистичные обновления для своих действий.',
    answerEn: 'WebSocket для двусторонней связи (чат, совместное редактирование). SSE для однонаправленных обновлений (уведомления, live feed). Polling как fallback. Интеграция с React Query: socket событие → queryClient.invalidateQueries или setQueryData. Обработка переподключения и офлайн состояния. Оптимистичные обновления для своих действий.',
  },
  {
    id: 'sd-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['url-state', 'routing', 'state-management'],
    questionRu: 'Как управлять URL state (фильтры, пагинация)?',
    questionEn: 'Как управлять URL state (фильтры, пагинация)?',
    answerRu: 'Фильтры, сортировка, пагинация — в URL query params: /products?category=shoes&sort=price&page=2. Преимущества: sharable URL, работает кнопка назад, SEO. Синхронизировать через useSearchParams (Next.js) или useLocation+useHistory. URL как единственный источник истины для этих данных — не дублировать в Redux.',
    answerEn: 'Фильтры, сортировка, пагинация — в URL query params: /products?category=shoes&sort=price&page=2. Преимущества: sharable URL, работает кнопка назад, SEO. Синхронизировать через useSearchParams (Next.js) или useLocation+useHistory. URL как единственный источник истины для этих данных — не дублировать в Redux.',
  },
  {
    id: 'sd-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['feature-flags', 'scalability'],
    questionRu: 'Что такое Feature Flags и как реализовать?',
    questionEn: 'Что такое Feature Flags и как реализовать?',
    answerRu: "Feature Flags — включение/отключение функций без деплоя. Позволяют: постепенный rollout, A/B тестирование, trunk-based development. Реализация: конфиг объект { featureName: boolean }, React контекст для доступа, хук useFeatureFlag('name'). Сервисы: LaunchDarkly, Unleash, самописное решение через env переменные.",
    answerEn: "Feature Flags — включение/отключение функций без деплоя. Позволяют: постепенный rollout, A/B тестирование, trunk-based development. Реализация: конфиг объект { featureName: boolean }, React контекст для доступа, хук useFeatureFlag('name'). Сервисы: LaunchDarkly, Unleash, самописное решение через env переменные.",
  },
  {
    id: 'sd-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['i18n', 'scalability'],
    questionRu: 'Как реализовать интернационализацию (i18n)?',
    questionEn: 'Как реализовать интернационализацию (i18n)?',
    answerRu: "Библиотеки: react-i18next, next-intl для Next.js. Структура: JSON файлы переводов по языкам и namespace. Ключи вместо строк: t('auth.login.button'). Pluralization и форматирование дат/чисел через Intl API. Lazy loading переводов по языку. Определение языка: URL (/en/, /ru/), заголовок Accept-Language, localStorage.",
    answerEn: "Библиотеки: react-i18next, next-intl для Next.js. Структура: JSON файлы переводов по языкам и namespace. Ключи вместо строк: t('auth.login.button'). Pluralization и форматирование дат/чисел через Intl API. Lazy loading переводов по языку. Определение языка: URL (/en/, /ru/), заголовок Accept-Language, localStorage.",
  },
  {
    id: 'sd-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['error-handling', 'scalability'],
    questionRu: 'Как организовать обработку ошибок в приложении?',
    questionEn: 'Как организовать обработку ошибок в приложении?',
    answerRu: 'Глобальный Error Boundary для неожиданных ошибок. API ошибки: централизованный обработчик в axios interceptor — toast уведомления, редирект на /login при 401. Типизированные ошибки — различать сетевые, валидационные, бизнес-ошибки. Логирование через Sentry. Retry логика для сетевых ошибок (React Query retries). Graceful degradation.',
    answerEn: 'Глобальный Error Boundary для неожиданных ошибок. API ошибки: централизованный обработчик в axios interceptor — toast уведомления, редирект на /login при 401. Типизированные ошибки — различать сетевые, валидационные, бизнес-ошибки. Логирование через Sentry. Retry логика для сетевых ошибок (React Query retries). Graceful degradation.',
  },
  {
    id: 'sd-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['notifications', 'toast', 'ux'],
    questionRu: 'Как спроектировать систему уведомлений (toast/notifications)?',
    questionEn: 'Как спроектировать систему уведомлений (toast/notifications)?',
    answerRu: "Централизованный стор уведомлений (Zustand или Context). API: notify({ type: 'success', message: '...' }). Компонент NotificationContainer рендерит список. Автоудаление по таймеру. Очередь при множестве уведомлений. Доступность: aria-live region для скринридеров. Библиотеки: react-hot-toast, sonner — хорошая альтернатива самописному.",
    answerEn: "Централизованный стор уведомлений (Zustand или Context). API: notify({ type: 'success', message: '...' }). Компонент NotificationContainer рендерит список. Автоудаление по таймеру. Очередь при множестве уведомлений. Доступность: aria-live region для скринридеров. Библиотеки: react-hot-toast, sonner — хорошая альтернатива самописному.",
  },
  {
    id: 'sd-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['infinite-scroll', 'pagination', 'ux'],
    questionRu: 'Как реализовать бесконечный скролл vs пагинацию?',
    questionEn: 'Как реализовать бесконечный скролл vs пагинацию?',
    answerRu: 'Пагинация: лучше для SEO, позволяет перейти на конкретную страницу, проще реализация. Бесконечный скролл: лучший UX для лент контента. Реализация: IntersectionObserver на sentinel элемент внизу списка. React Query useInfiniteQuery. Виртуализация для большого количества элементов. Cursor-based пагинация на API предпочтительнее offset для real-time данных.',
    answerEn: 'Пагинация: лучше для SEO, позволяет перейти на конкретную страницу, проще реализация. Бесконечный скролл: лучший UX для лент контента. Реализация: IntersectionObserver на sentinel элемент внизу списка. React Query useInfiniteQuery. Виртуализация для большого количества элементов. Cursor-based пагинация на API предпочтительнее offset для real-time данных.',
  },
  {
    id: 'sd-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['auth', 'security', 'architecture'],
    questionRu: 'Как проектировать авторизацию на фронтенде?',
    questionEn: 'Как проектировать авторизацию на фронтенде?',
    answerRu: 'Хранить токены безопасно (httpOnly cookie для refresh, memory для access). Axios interceptor добавляет Authorization заголовок. Автообновление access token через refresh token. Protected routes — redirect на login если не авторизован. Role-based UI: показывать/скрывать элементы по ролям (только UX, не безопасность — проверка на сервере). Logout — очистить все токены и кеш.',
    answerEn: 'Хранить токены безопасно (httpOnly cookie для refresh, memory для access). Axios interceptor добавляет Authorization заголовок. Автообновление access token через refresh token. Protected routes — redirect на login если не авторизован. Role-based UI: показывать/скрывать элементы по ролям (только UX, не безопасность — проверка на сервере). Logout — очистить все токены и кеш.',
  },
  {
    id: 'sd-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['micro-frontends', 'architecture'],
    questionRu: 'Что такое micro-frontends и когда использовать?',
    questionEn: 'Что такое micro-frontends и когда использовать?',
    answerRu: 'Micro-frontends — разбивка фронтенда на независимые части разрабатываемые разными командами. Каждая часть — отдельный деплой, свой стек. Когда использовать: большая команда (5+ команд), независимый деплой частей, разные технологии. Не использовать для: малых команд, одного стека — overhead не оправдан.',
    answerEn: 'Micro-frontends — разбивка фронтенда на независимые части разрабатываемые разными командами. Каждая часть — отдельный деплой, свой стек. Когда использовать: большая команда (5+ команд), независимый деплой частей, разные технологии. Не использовать для: малых команд, одного стека — overhead не оправдан.',
  },
  {
    id: 'sd-020',
    difficulty: 'HARD',
    order: 20,
    tags: ['micro-frontends', 'module-federation'],
    questionRu: 'Какие подходы к реализации micro-frontends существуют?',
    questionEn: 'Какие подходы к реализации micro-frontends существуют?',
    answerRu: 'Iframe: максимальная изоляция, плохой UX. Web Components: нативные, стековая независимость, сложная интеграция. Module Federation (Webpack 5): runtime загрузка модулей из других приложений — популярный подход. Single-SPA: оркестратор для нескольких SPA. Server-side composition (Edge/CDN): включение фрагментов на уровне сервера.',
    answerEn: 'Iframe: максимальная изоляция, плохой UX. Web Components: нативные, стековая независимость, сложная интеграция. Module Federation (Webpack 5): runtime загрузка модулей из других приложений — популярный подход. Single-SPA: оркестратор для нескольких SPA. Server-side composition (Edge/CDN): включение фрагментов на уровне сервера.',
  },
  {
    id: 'sd-021',
    difficulty: 'HARD',
    order: 21,
    tags: ['micro-frontends', 'module-federation', 'webpack'],
    questionRu: 'Что такое Module Federation?',
    questionEn: 'Что такое Module Federation?',
    answerRu: 'Module Federation (Webpack 5) позволяет приложениям загружать модули из других приложений в runtime. Host приложение потребляет Remote компоненты. Shared зависимости (React) не дублируются. Каждый remote деплоится независимо. Vite аналог: @originjs/vite-plugin-federation. Позволяет разным командам деплоить независимо без пересборки host.',
    answerEn: 'Module Federation (Webpack 5) позволяет приложениям загружать модули из других приложений в runtime. Host приложение потребляет Remote компоненты. Shared зависимости (React) не дублируются. Каждый remote деплоится независимо. Vite аналог: @originjs/vite-plugin-federation. Позволяет разным командам деплоить независимо без пересборки host.',
  },
  {
    id: 'sd-022',
    difficulty: 'HARD',
    order: 22,
    tags: ['micro-frontends', 'state-management', 'communication'],
    questionRu: 'Как организовать shared state между micro-frontends?',
    questionEn: 'Как организовать shared state между micro-frontends?',
    answerRu: 'Custom Events / BroadcastChannel: события между независимыми приложениями. Shared стор через Module Federation. URL как источник истины для роутинга. Shared библиотека для типов и утилит. Избегать тесной связанности — micro-frontends должны быть независимы. Event bus для коммуникации без прямых зависимостей.',
    answerEn: 'Custom Events / BroadcastChannel: события между независимыми приложениями. Shared стор через Module Federation. URL как источник истины для роутинга. Shared библиотека для типов и утилит. Избегать тесной связанности — micro-frontends должны быть независимы. Event bus для коммуникации без прямых зависимостей.',
  },
  {
    id: 'sd-023',
    difficulty: 'HARD',
    order: 23,
    tags: ['micro-frontends', 'dependencies', 'module-federation'],
    questionRu: 'Как решать проблему дублирования зависимостей в micro-frontends?',
    questionEn: 'Как решать проблему дублирования зависимостей в micro-frontends?',
    answerRu: 'Module Federation shared config: указать общие зависимости (react, react-dom) как singleton — загружаются один раз. Версионирование: semver совместимые версии шарятся автоматически. Несовместимые версии загружаются отдельно. Мониторинг размера бандла. Общий Design System как отдельный пакет. Договорённость команд о версиях ключевых зависимостей.',
    answerEn: 'Module Federation shared config: указать общие зависимости (react, react-dom) как singleton — загружаются один раз. Версионирование: semver совместимые версии шарятся автоматически. Несовместимые версии загружаются отдельно. Мониторинг размера бандла. Общий Design System как отдельный пакет. Договорённость команд о версиях ключевых зависимостей.',
  },
];
