import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'test-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['pyramid', 'fundamentals'],
    questionRu: 'Что такое пирамида тестирования?',
    questionEn: 'Что такое пирамида тестирования?',
    answerRu: 'Пирамида тестирования: снизу вверх — Unit (много, быстрые, дешёвые) → Integration (меньше) → E2E (мало, медленные, дорогие). Чем выше — тем медленнее и дороже. Цель: максимум покрытия при минимуме затрат. Антипаттерн — перевёрнутая пирамида (много E2E, мало unit).',
    answerEn: 'Пирамида тестирования: снизу вверх — Unit (много, быстрые, дешёвые) → Integration (меньше) → E2E (мало, медленные, дорогие). Чем выше — тем медленнее и дороже. Цель: максимум покрытия при минимуме затрат. Антипаттерн — перевёрнутая пирамида (много E2E, мало unit).',
  },
  {
    id: 'test-002',
    difficulty: 'EASY',
    order: 2,
    tags: ['unit', 'integration', 'e2e'],
    questionRu: 'В чём разница между unit, integration и E2E тестами?',
    questionEn: 'В чём разница между unit, integration и E2E тестами?',
    answerRu: 'Unit: тестирует изолированную функцию/модуль, зависимости замокированы. Быстро, легко отлаживать. Integration: тестирует взаимодействие нескольких модулей вместе. E2E: тестирует полный сценарий через реальный браузер — от UI до БД. Медленно, но проверяет реальный пользовательский путь.',
    answerEn: 'Unit: тестирует изолированную функцию/модуль, зависимости замокированы. Быстро, легко отлаживать. Integration: тестирует взаимодействие нескольких модулей вместе. E2E: тестирует полный сценарий через реальный браузер — от UI до БД. Медленно, но проверяет реальный пользовательский путь.',
  },
  {
    id: 'test-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['tdd', 'methodology'],
    questionRu: 'Что такое TDD (Test-Driven Development)?',
    questionEn: 'Что такое TDD (Test-Driven Development)?',
    answerRu: 'TDD — подход: сначала пишешь тест (red) → пишешь минимальный код чтобы тест прошёл (green) → рефакторишь (refactor). Цикл red-green-refactor. Преимущества: продуманный API до реализации, высокое покрытие, меньше регрессий. Минусы: медленнее разработка поначалу, сложно для UI.',
    answerEn: 'TDD — подход: сначала пишешь тест (red) → пишешь минимальный код чтобы тест прошёл (green) → рефакторишь (refactor). Цикл red-green-refactor. Преимущества: продуманный API до реализации, высокое покрытие, меньше регрессий. Минусы: медленнее разработка поначалу, сложно для UI.',
  },
  {
    id: 'test-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['coverage'],
    questionRu: 'Что такое покрытие кода (code coverage) и какой процент считается хорошим?',
    questionEn: 'Что такое покрытие кода (code coverage) и какой процент считается хорошим?',
    answerRu: 'Coverage — процент кода выполненного при тестах. Типы: statement, branch, function, line coverage. 100% coverage не означает отсутствие багов — важно качество тестов. Разумный ориентир: 70-80% для большинства проектов. Критичная бизнес-логика — 90%+. Не гнаться за цифрой ради цифры.',
    answerEn: 'Coverage — процент кода выполненного при тестах. Типы: statement, branch, function, line coverage. 100% coverage не означает отсутствие багов — важно качество тестов. Разумный ориентир: 70-80% для большинства проектов. Критичная бизнес-логика — 90%+. Не гнаться за цифрой ради цифры.',
  },
  {
    id: 'test-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['snapshot', 'jest'],
    questionRu: 'Что такое snapshot тестирование?',
    questionEn: 'Что такое snapshot тестирование?',
    answerRu: 'Snapshot тест сохраняет сериализованный вывод компонента и сравнивает с ним при следующих запусках. Легко создать, ловит неожиданные изменения UI. Минусы: легко обновить не глядя (jest --updateSnapshot), большие снепшоты трудно читать. Полезны для стабильных UI-компонентов, но не замена семантическим тестам.',
    answerEn: 'Snapshot тест сохраняет сериализованный вывод компонента и сравнивает с ним при следующих запусках. Легко создать, ловит неожиданные изменения UI. Минусы: легко обновить не глядя (jest --updateSnapshot), большие снепшоты трудно читать. Полезны для стабильных UI-компонентов, но не замена семантическим тестам.',
  },
  {
    id: 'test-006',
    difficulty: 'HARD',
    order: 6,
    tags: ['mutation-testing', 'stryker'],
    questionRu: 'Что такое мутационное тестирование?',
    questionEn: 'Что такое мутационное тестирование?',
    answerRu: 'Мутационное тестирование — автоматически вносит мелкие изменения в код (мутации) и проверяет, упадут ли тесты. Если тест не поймал мутацию — он слабый. Инструмент: Stryker. Показывает реальное качество тестов, а не просто coverage. Медленно — запускать не на каждом коммите.',
    answerEn: 'Мутационное тестирование — автоматически вносит мелкие изменения в код (мутации) и проверяет, упадут ли тесты. Если тест не поймал мутацию — он слабый. Инструмент: Stryker. Показывает реальное качество тестов, а не просто coverage. Медленно — запускать не на каждом коммите.',
  },
  {
    id: 'test-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['jest', 'unit'],
    questionRu: 'Что такое Jest и как устроен тест?',
    questionEn: 'Что такое Jest и как устроен тест?',
    answerRu: 'Jest — фреймворк для тестирования JS/TS. Структура: describe (группа тестов) → it/test (один тест) → expect(value).matcher(). Встроены: моки, coverage, watch mode, jsdom. Работает из коробки с CRA, Vite (vitest), Next.js. Конфигурация в jest.config.js или package.json.',
    answerEn: 'Jest — фреймворк для тестирования JS/TS. Структура: describe (группа тестов) → it/test (один тест) → expect(value).matcher(). Встроены: моки, coverage, watch mode, jsdom. Работает из коробки с CRA, Vite (vitest), Next.js. Конфигурация в jest.config.js или package.json.',
  },
  {
    id: 'test-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['jest', 'mocks'],
    questionRu: 'Что такое моки (mocks) и зачем нужны?',
    questionEn: 'Что такое моки (mocks) и зачем нужны?',
    answerRu: 'Мок — замена реальной зависимости на контролируемую версию. Зачем: изолировать тестируемый модуль, контролировать поведение зависимостей, проверять вызовы. Jest: jest.fn() — мок-функция, jest.mock(\'./module\') — мок модуля, jest.spyOn(obj, \'method\') — шпион на метод без замены реализации.',
    answerEn: 'Мок — замена реальной зависимости на контролируемую версию. Зачем: изолировать тестируемый модуль, контролировать поведение зависимостей, проверять вызовы. Jest: jest.fn() — мок-функция, jest.mock(\'./module\') — мок модуля, jest.spyOn(obj, \'method\') — шпион на метод без замены реализации.',
  },
  {
    id: 'test-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['jest', 'mocks', 'stubs', 'spies'],
    questionRu: 'В чём разница между mock, stub и spy?',
    questionEn: 'В чём разница между mock, stub и spy?',
    answerRu: 'Stub: возвращает заранее заданное значение, не проверяет вызовы. Mock: задаёт ожидания о вызовах — проверяет был ли вызван, с какими аргументами. Spy: оборачивает реальную реализацию, позволяя наблюдать за вызовами без замены. В Jest jest.fn() объединяет stub и mock, spyOn — spy.',
    answerEn: 'Stub: возвращает заранее заданное значение, не проверяет вызовы. Mock: задаёт ожидания о вызовах — проверяет был ли вызван, с какими аргументами. Spy: оборачивает реальную реализацию, позволяя наблюдать за вызовами без замены. В Jest jest.fn() объединяет stub и mock, spyOn — spy.',
  },
  {
    id: 'test-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['jest', 'async'],
    questionRu: 'Как тестировать асинхронный код в Jest?',
    questionEn: 'Как тестировать асинхронный код в Jest?',
    answerRu: 'Три способа: 1) async/await: it(\'test\', async () => { const result = await fetchData(); expect(result).toBe(...) }). 2) Вернуть промис: return expect(promise).resolves.toBe(...). 3) done колбэк (устаревший). Для таймеров: jest.useFakeTimers() + jest.runAllTimers(). Обязательно await или return промис иначе тест не ждёт.',
    answerEn: 'Три способа: 1) async/await: it(\'test\', async () => { const result = await fetchData(); expect(result).toBe(...) }). 2) Вернуть промис: return expect(promise).resolves.toBe(...). 3) done колбэк (устаревший). Для таймеров: jest.useFakeTimers() + jest.runAllTimers(). Обязательно await или return промис иначе тест не ждёт.',
  },
  {
    id: 'test-011',
    difficulty: 'EASY',
    order: 11,
    tags: ['jest', 'lifecycle'],
    questionRu: 'Что такое beforeEach, afterEach, beforeAll, afterAll?',
    questionEn: 'Что такое beforeEach, afterEach, beforeAll, afterAll?',
    answerRu: 'beforeEach/afterEach: выполняются до/после каждого теста в describe. beforeAll/afterAll: один раз до/после всех тестов в describe. Используются для: setup/teardown состояния, очистки моков (jest.clearAllMocks()), создания/удаления тестовых данных. beforeEach предпочтительнее beforeAll для изоляции тестов.',
    answerEn: 'beforeEach/afterEach: выполняются до/после каждого теста в describe. beforeAll/afterAll: один раз до/после всех тестов в describe. Используются для: setup/teardown состояния, очистки моков (jest.clearAllMocks()), создания/удаления тестовых данных. beforeEach предпочтительнее beforeAll для изоляции тестов.',
  },
  {
    id: 'test-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['jest', 'parametrized'],
    questionRu: 'Что такое параметризованные тесты (test.each)?',
    questionEn: 'Что такое параметризованные тесты (test.each)?',
    answerRu: 'test.each позволяет запустить один тест с разными данными: test.each([[1,2,3],[2,3,5]])(\'adds %i + %i = %i\', (a,b,expected) => { expect(a+b).toBe(expected) }). Уменьшает дублирование. Поддерживает tagged template literals для читаемости. Полезно для тестирования граничных значений.',
    answerEn: 'test.each позволяет запустить один тест с разными данными: test.each([[1,2,3],[2,3,5]])(\'adds %i + %i = %i\', (a,b,expected) => { expect(a+b).toBe(expected) }). Уменьшает дублирование. Поддерживает tagged template literals для читаемости. Полезно для тестирования граничных значений.',
  },
  {
    id: 'test-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['vitest', 'vite'],
    questionRu: 'Что такое Vitest и чем отличается от Jest?',
    questionEn: 'Что такое Vitest и чем отличается от Jest?',
    answerRu: 'Vitest — современный тест-фреймворк на основе Vite. Совместим с Jest API. Преимущества: нативная поддержка ES modules и TypeScript без настройки, в разы быстрее за счёт Vite трансформаций, общий конфиг с Vite. Минусы: меньше экосистема. Предпочтителен для Vite проектов.',
    answerEn: 'Vitest — современный тест-фреймворк на основе Vite. Совместим с Jest API. Преимущества: нативная поддержка ES modules и TypeScript без настройки, в разы быстрее за счёт Vite трансформаций, общий конфиг с Vite. Минусы: меньше экосистема. Предпочтителен для Vite проектов.',
  },
  {
    id: 'test-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['testing-library', 'react'],
    questionRu: 'Что такое Testing Library и в чём её философия?',
    questionEn: 'Что такое Testing Library и в чём её философия?',
    answerRu: 'Testing Library — библиотека для тестирования компонентов через пользовательское взаимодействие. Философия: тестируй как пользователь, не детали реализации. Запросы приоритет: getByRole → getByLabelText → getByText → getByTestId. Не тестировать внутренний state, методы компонента, детали рендеринга.',
    answerEn: 'Testing Library — библиотека для тестирования компонентов через пользовательское взаимодействие. Философия: тестируй как пользователь, не детали реализации. Запросы приоритет: getByRole → getByLabelText → getByText → getByTestId. Не тестировать внутренний state, методы компонента, детали рендеринга.',
  },
  {
    id: 'test-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['testing-library', 'queries'],
    questionRu: 'В чём разница между getBy, queryBy и findBy?',
    questionEn: 'В чём разница между getBy, queryBy и findBy?',
    answerRu: 'getBy*: возвращает элемент или бросает ошибку если не найден. queryBy*: возвращает элемент или null — для проверки отсутствия. findBy*: возвращает Promise, ждёт появления элемента (async) — для элементов появляющихся после запроса. Множественные: getAllBy, queryAllBy, findAllBy.',
    answerEn: 'getBy*: возвращает элемент или бросает ошибку если не найден. queryBy*: возвращает элемент или null — для проверки отсутствия. findBy*: возвращает Promise, ждёт появления элемента (async) — для элементов появляющихся после запроса. Множественные: getAllBy, queryAllBy, findAllBy.',
  },
  {
    id: 'test-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['testing-library', 'async', 'msw'],
    questionRu: 'Как тестировать асинхронные компоненты с Testing Library?',
    questionEn: 'Как тестировать асинхронные компоненты с Testing Library?',
    answerRu: 'waitFor(() => expect(...)) — ждёт пока assertion не пройдёт. findBy* — async getBy*, ждёт появления элемента. Мокировать fetch/axios через jest.mock или MSW (Mock Service Worker). MSW предпочтительнее — перехватывает реальные сетевые запросы, более реалистично.',
    answerEn: 'waitFor(() => expect(...)) — ждёт пока assertion не пройдёт. findBy* — async getBy*, ждёт появления элемента. Мокировать fetch/axios через jest.mock или MSW (Mock Service Worker). MSW предпочтительнее — перехватывает реальные сетевые запросы, более реалистично.',
  },
  {
    id: 'test-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['testing-library', 'user-event', 'fire-event'],
    questionRu: 'Что такое userEvent и чем отличается от fireEvent?',
    questionEn: 'Что такое userEvent и чем отличается от fireEvent?',
    answerRu: 'fireEvent: напрямую диспатчит DOM событие — быстро но нереалистично. userEvent (v14): симулирует реальное пользовательское взаимодействие — userEvent.type() имитирует каждое нажатие клавиши, фокус, blur. Более реалистично, ловит больше багов. userEvent предпочтительнее для большинства интеракций.',
    answerEn: 'fireEvent: напрямую диспатчит DOM событие — быстро но нереалистично. userEvent (v14): симулирует реальное пользовательское взаимодействие — userEvent.type() имитирует каждое нажатие клавиши, фокус, blur. Более реалистично, ловит больше багов. userEvent предпочтительнее для большинства интеракций.',
  },
  {
    id: 'test-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['testing-library', 'context', 'redux'],
    questionRu: 'Как тестировать компоненты с Context или Redux?',
    questionEn: 'Как тестировать компоненты с Context или Redux?',
    answerRu: 'Обернуть в провайдер при рендере: render(<Provider store={store}><Component/></Provider>). Создать кастомный render-хелпер с нужными провайдерами. Для Redux: createStore с тестовым состоянием. Для Context: передать нужное value. Testing Library поощряет тестировать с реальными провайдерами, не моками.',
    answerEn: 'Обернуть в провайдер при рендере: render(<Provider store={store}><Component/></Provider>). Создать кастомный render-хелпер с нужными провайдерами. Для Redux: createStore с тестовым состоянием. Для Context: передать нужное value. Testing Library поощряет тестировать с реальными провайдерами, не моками.',
  },
  {
    id: 'test-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['msw', 'mocking', 'network'],
    questionRu: 'Что такое MSW (Mock Service Worker)?',
    questionEn: 'Что такое MSW (Mock Service Worker)?',
    answerRu: 'MSW перехватывает сетевые запросы на уровне Service Worker (браузер) или node-fetch (Node.js/Jest). Позволяет мокировать API реалистично без изменения кода. Хендлеры: http.get(\'/api/users\', resolver). Переиспользуются между тестами и разработкой (storybook, dev режим). Предпочтительнее jest.mock для fetch.',
    answerEn: 'MSW перехватывает сетевые запросы на уровне Service Worker (браузер) или node-fetch (Node.js/Jest). Позволяет мокировать API реалистично без изменения кода. Хендлеры: http.get(\'/api/users\', resolver). Переиспользуются между тестами и разработкой (storybook, dev режим). Предпочтительнее jest.mock для fetch.',
  },
  {
    id: 'test-020',
    difficulty: 'EASY',
    order: 20,
    tags: ['e2e', 'fundamentals'],
    questionRu: 'Что такое E2E тестирование и зачем нужно?',
    questionEn: 'Что такое E2E тестирование и зачем нужно?',
    answerRu: 'E2E тесты проверяют полный пользовательский сценарий через реальный браузер: от клика по кнопке до проверки результата в БД. Ловят баги интеграции которые unit/integration тесты не найдут. Медленные и хрупкие — тестировать только критичные user flows: регистрация, оплата, ключевые сценарии.',
    answerEn: 'E2E тесты проверяют полный пользовательский сценарий через реальный браузер: от клика по кнопке до проверки результата в БД. Ловят баги интеграции которые unit/integration тесты не найдут. Медленные и хрупкие — тестировать только критичные user flows: регистрация, оплата, ключевые сценарии.',
  },
  {
    id: 'test-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['e2e', 'cypress', 'playwright'],
    questionRu: 'В чём разница между Cypress и Playwright?',
    questionEn: 'В чём разница между Cypress и Playwright?',
    answerRu: 'Cypress: только Chromium (+ Firefox/Edge), выполняется внутри браузера, отличный DX, time-travel debugging, встроенный dashboard. Playwright: все браузеры (Chromium, Firefox, WebKit/Safari), выполняется вне браузера, параллельные тесты, лучше для CI. Playwright предпочтительнее для кросс-браузерного тестирования.',
    answerEn: 'Cypress: только Chromium (+ Firefox/Edge), выполняется внутри браузера, отличный DX, time-travel debugging, встроенный dashboard. Playwright: все браузеры (Chromium, Firefox, WebKit/Safari), выполняется вне браузера, параллельные тесты, лучше для CI. Playwright предпочтительнее для кросс-браузерного тестирования.',
  },
  {
    id: 'test-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['e2e', 'best-practices'],
    questionRu: 'Как писать надёжные E2E тесты?',
    questionEn: 'Как писать надёжные E2E тесты?',
    answerRu: 'Не использовать CSS-классы и XPath — хрупко. Предпочитать data-testid или ARIA роли. Ждать появления элементов (cy.get / page.waitFor) вместо sleep. Изолировать тесты — каждый тест с чистым состоянием. Мокировать внешние API. Параллельный запуск для скорости. Page Object Model для переиспользования.',
    answerEn: 'Не использовать CSS-классы и XPath — хрупко. Предпочитать data-testid или ARIA роли. Ждать появления элементов (cy.get / page.waitFor) вместо sleep. Изолировать тесты — каждый тест с чистым состоянием. Мокировать внешние API. Параллельный запуск для скорости. Page Object Model для переиспользования.',
  },
  {
    id: 'test-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['e2e', 'pom', 'patterns'],
    questionRu: 'Что такое Page Object Model (POM)?',
    questionEn: 'Что такое Page Object Model (POM)?',
    answerRu: 'POM — паттерн для E2E тестов: каждая страница или компонент представлен классом с методами для взаимодействия. Скрывает селекторы и детали реализации. Пример: LoginPage с методами login(email, password), getErrorMessage(). При изменении UI правишь только класс страницы, не все тесты.',
    answerEn: 'POM — паттерн для E2E тестов: каждая страница или компонент представлен классом с методами для взаимодействия. Скрывает селекторы и детали реализации. Пример: LoginPage с методами login(email, password), getErrorMessage(). При изменении UI правишь только класс страницы, не все тесты.',
  },
  {
    id: 'test-024',
    difficulty: 'MEDIUM',
    order: 24,
    tags: ['e2e', 'ci-cd'],
    questionRu: 'Как запускать тесты в CI/CD?',
    questionEn: 'Как запускать тесты в CI/CD?',
    answerRu: 'Unit/integration тесты: на каждый PR, быстро (<5 мин). E2E: на merge в main или как отдельный stage. Инструменты: GitHub Actions, GitLab CI. Для E2E: headless режим, параллелизация (Playwright sharding, Cypress Cloud). Cypress/Playwright записывают видео и скриншоты при падении. Flaky тесты помечать и чинить приоритетно.',
    answerEn: 'Unit/integration тесты: на каждый PR, быстро (<5 мин). E2E: на merge в main или как отдельный stage. Инструменты: GitHub Actions, GitLab CI. Для E2E: headless режим, параллелизация (Playwright sharding, Cypress Cloud). Cypress/Playwright записывают видео и скриншоты при падении. Flaky тесты помечать и чинить приоритетно.',
  },
];
