import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'test-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['pyramid', 'fundamentals'],
    questionRu: 'Что такое пирамида тестирования?',
    questionEn: 'What is the testing pyramid?',
    answerRu: 'Пирамида тестирования: снизу вверх — Unit (много, быстрые, дешёвые) → Integration (меньше) → E2E (мало, медленные, дорогие). Чем выше — тем медленнее и дороже. Цель: максимум покрытия при минимуме затрат. Антипаттерн — перевёрнутая пирамида (много E2E, мало unit).',
    answerEn: 'The testing pyramid (bottom to top): Unit (many, fast, cheap) → Integration (fewer) → E2E (few, slow, expensive). The higher the level, the slower and more costly. Goal: maximum coverage at minimum cost. Anti-pattern: the inverted pyramid (many E2E, few unit tests).',
  },
  {
    id: 'test-002',
    difficulty: 'EASY',
    order: 2,
    tags: ['unit', 'integration', 'e2e'],
    questionRu: 'В чём разница между unit, integration и E2E тестами?',
    questionEn: 'What is the difference between unit, integration, and E2E tests?',
    answerRu: 'Unit: тестирует изолированную функцию/модуль, зависимости замокированы. Быстро, легко отлаживать. Integration: тестирует взаимодействие нескольких модулей вместе. E2E: тестирует полный сценарий через реальный браузер — от UI до БД. Медленно, но проверяет реальный пользовательский путь.',
    answerEn: 'Unit: tests an isolated function/module with mocked dependencies. Fast and easy to debug. Integration: tests how multiple modules work together. E2E: tests a complete scenario through a real browser — from the UI down to the database. Slow, but verifies a real user journey.',
  },
  {
    id: 'test-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['tdd', 'methodology'],
    questionRu: 'Что такое TDD (Test-Driven Development)?',
    questionEn: 'What is TDD (Test-Driven Development)?',
    answerRu: 'TDD — подход: сначала пишешь тест (red) → пишешь минимальный код чтобы тест прошёл (green) → рефакторишь (refactor). Цикл red-green-refactor. Преимущества: продуманный API до реализации, высокое покрытие, меньше регрессий. Минусы: медленнее разработка поначалу, сложно для UI.',
    answerEn: 'TDD is an approach where you write the test first (red) → write the minimal code to make it pass (green) → refactor (refactor). The red-green-refactor cycle. Advantages: well-designed API before implementation, high coverage, fewer regressions. Drawbacks: slower to start, harder to apply to UI.',
  },
  {
    id: 'test-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['coverage'],
    questionRu: 'Что такое покрытие кода (code coverage) и какой процент считается хорошим?',
    questionEn: 'What is code coverage and what percentage is considered good?',
    answerRu: 'Coverage — процент кода выполненного при тестах. Типы: statement, branch, function, line coverage. 100% coverage не означает отсутствие багов — важно качество тестов. Разумный ориентир: 70-80% для большинства проектов. Критичная бизнес-логика — 90%+. Не гнаться за цифрой ради цифры.',
    answerEn: 'Coverage is the percentage of code executed during tests. Types: statement, branch, function, and line coverage. 100% coverage does not mean zero bugs — test quality matters more than the number. A reasonable target: 70–80% for most projects. Critical business logic: 90%+. Don\'t chase the number for its own sake.',
  },
  {
    id: 'test-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['snapshot', 'jest'],
    questionRu: 'Что такое snapshot тестирование?',
    questionEn: 'What is snapshot testing?',
    answerRu: 'Snapshot тест сохраняет сериализованный вывод компонента и сравнивает с ним при следующих запусках. Легко создать, ловит неожиданные изменения UI. Минусы: легко обновить не глядя (jest --updateSnapshot), большие снепшоты трудно читать. Полезны для стабильных UI-компонентов, но не замена семантическим тестам.',
    answerEn: 'A snapshot test saves the serialized output of a component and compares it on subsequent runs. Easy to create, catches unexpected UI changes. Drawbacks: easy to update blindly (jest --updateSnapshot), large snapshots are hard to read. Useful for stable UI components, but not a replacement for semantic tests.',
  },
  {
    id: 'test-006',
    difficulty: 'HARD',
    order: 6,
    tags: ['mutation-testing', 'stryker'],
    questionRu: 'Что такое мутационное тестирование?',
    questionEn: 'What is mutation testing?',
    answerRu: 'Мутационное тестирование — автоматически вносит мелкие изменения в код (мутации) и проверяет, упадут ли тесты. Если тест не поймал мутацию — он слабый. Инструмент: Stryker. Показывает реальное качество тестов, а не просто coverage. Медленно — запускать не на каждом коммите.',
    answerEn: 'Mutation testing automatically introduces small changes to the code (mutations) and checks whether the tests catch them. If a test misses a mutation, it is weak. Tool: Stryker. It reveals the real quality of your tests, not just coverage figures. It is slow — do not run it on every commit.',
  },
  {
    id: 'test-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['jest', 'unit'],
    questionRu: 'Что такое Jest и как устроен тест?',
    questionEn: 'What is Jest and how is a test structured?',
    answerRu: 'Jest — фреймворк для тестирования JS/TS. Структура: describe (группа тестов) → it/test (один тест) → expect(value).matcher(). Встроены: моки, coverage, watch mode, jsdom. Работает из коробки с CRA, Vite (vitest), Next.js. Конфигурация в jest.config.js или package.json.',
    answerEn: 'Jest is a testing framework for JS/TS. Structure: describe (test group) → it/test (single test) → expect(value).matcher(). Built-in: mocks, coverage, watch mode, jsdom. Works out of the box with CRA, Vite (vitest), Next.js. Configured via jest.config.js or package.json.',
  },
  {
    id: 'test-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['jest', 'mocks'],
    questionRu: 'Что такое моки (mocks) и зачем нужны?',
    questionEn: 'What are mocks and why are they needed?',
    answerRu: 'Мок — замена реальной зависимости на контролируемую версию. Зачем: изолировать тестируемый модуль, контролировать поведение зависимостей, проверять вызовы. Jest: jest.fn() — мок-функция, jest.mock(\'./module\') — мок модуля, jest.spyOn(obj, \'method\') — шпион на метод без замены реализации.',
    answerEn: 'A mock replaces a real dependency with a controlled version. Why: to isolate the module under test, control dependency behavior, and verify calls. In Jest: jest.fn() — mock function, jest.mock(\'./module\') — module mock, jest.spyOn(obj, \'method\') — spy on a method without replacing its implementation.',
  },
  {
    id: 'test-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['jest', 'mocks', 'stubs', 'spies'],
    questionRu: 'В чём разница между mock, stub и spy?',
    questionEn: 'What is the difference between a mock, a stub, and a spy?',
    answerRu: 'Stub: возвращает заранее заданное значение, не проверяет вызовы. Mock: задаёт ожидания о вызовах — проверяет был ли вызван, с какими аргументами. Spy: оборачивает реальную реализацию, позволяя наблюдать за вызовами без замены. В Jest jest.fn() объединяет stub и mock, spyOn — spy.',
    answerEn: 'Stub: returns a predefined value, does not verify calls. Mock: sets expectations on calls — checks whether the function was called and with what arguments. Spy: wraps the real implementation, allowing you to observe calls without replacing it. In Jest, jest.fn() combines stub and mock; spyOn is a spy.',
  },
  {
    id: 'test-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['jest', 'async'],
    questionRu: 'Как тестировать асинхронный код в Jest?',
    questionEn: 'How do you test asynchronous code in Jest?',
    answerRu: 'Три способа: 1) async/await: it(\'test\', async () => { const result = await fetchData(); expect(result).toBe(...) }). 2) Вернуть промис: return expect(promise).resolves.toBe(...). 3) done колбэк (устаревший). Для таймеров: jest.useFakeTimers() + jest.runAllTimers(). Обязательно await или return промис иначе тест не ждёт.',
    answerEn: 'Three approaches: 1) async/await: it(\'test\', async () => { const result = await fetchData(); expect(result).toBe(...) }). 2) Return a promise: return expect(promise).resolves.toBe(...). 3) done callback (deprecated). For timers: jest.useFakeTimers() + jest.runAllTimers(). Always await or return the promise, otherwise the test won\'t wait.',
  },
  {
    id: 'test-011',
    difficulty: 'EASY',
    order: 11,
    tags: ['jest', 'lifecycle'],
    questionRu: 'Что такое beforeEach, afterEach, beforeAll, afterAll?',
    questionEn: 'What are beforeEach, afterEach, beforeAll, and afterAll?',
    answerRu: 'beforeEach/afterEach: выполняются до/после каждого теста в describe. beforeAll/afterAll: один раз до/после всех тестов в describe. Используются для: setup/teardown состояния, очистки моков (jest.clearAllMocks()), создания/удаления тестовых данных. beforeEach предпочтительнее beforeAll для изоляции тестов.',
    answerEn: 'beforeEach/afterEach: run before/after each test in a describe block. beforeAll/afterAll: run once before/after all tests in a describe block. Used for: state setup/teardown, clearing mocks (jest.clearAllMocks()), creating/deleting test data. beforeEach is preferred over beforeAll for better test isolation.',
  },
  {
    id: 'test-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['jest', 'parametrized'],
    questionRu: 'Что такое параметризованные тесты (test.each)?',
    questionEn: 'What are parameterized tests (test.each)?',
    answerRu: 'test.each позволяет запустить один тест с разными данными: test.each([[1,2,3],[2,3,5]])(\'adds %i + %i = %i\', (a,b,expected) => { expect(a+b).toBe(expected) }). Уменьшает дублирование. Поддерживает tagged template literals для читаемости. Полезно для тестирования граничных значений.',
    answerEn: 'test.each lets you run the same test with different data: test.each([[1,2,3],[2,3,5]])(\'adds %i + %i = %i\', (a,b,expected) => { expect(a+b).toBe(expected) }). Reduces duplication. Supports tagged template literals for readability. Useful for testing boundary values.',
  },
  {
    id: 'test-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['vitest', 'vite'],
    questionRu: 'Что такое Vitest и чем отличается от Jest?',
    questionEn: 'What is Vitest and how does it differ from Jest?',
    answerRu: 'Vitest — современный тест-фреймворк на основе Vite. Совместим с Jest API. Преимущества: нативная поддержка ES modules и TypeScript без настройки, в разы быстрее за счёт Vite трансформаций, общий конфиг с Vite. Минусы: меньше экосистема. Предпочтителен для Vite проектов.',
    answerEn: 'Vitest is a modern test framework built on top of Vite. It is compatible with the Jest API. Advantages: native ES modules and TypeScript support with no configuration, significantly faster due to Vite transforms, shared config with Vite. Drawbacks: smaller ecosystem. Preferred for Vite-based projects.',
  },
  {
    id: 'test-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['testing-library', 'react'],
    questionRu: 'Что такое Testing Library и в чём её философия?',
    questionEn: 'What is Testing Library and what is its philosophy?',
    answerRu: 'Testing Library — библиотека для тестирования компонентов через пользовательское взаимодействие. Философия: тестируй как пользователь, не детали реализации. Запросы приоритет: getByRole → getByLabelText → getByText → getByTestId. Не тестировать внутренний state, методы компонента, детали рендеринга.',
    answerEn: 'Testing Library is a library for testing components through user interactions. Philosophy: test the way a user would, not implementation details. Query priority: getByRole → getByLabelText → getByText → getByTestId. Do not test internal state, component methods, or rendering details.',
  },
  {
    id: 'test-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['testing-library', 'queries'],
    questionRu: 'В чём разница между getBy, queryBy и findBy?',
    questionEn: 'What is the difference between getBy, queryBy, and findBy?',
    answerRu: 'getBy*: возвращает элемент или бросает ошибку если не найден. queryBy*: возвращает элемент или null — для проверки отсутствия. findBy*: возвращает Promise, ждёт появления элемента (async) — для элементов появляющихся после запроса. Множественные: getAllBy, queryAllBy, findAllBy.',
    answerEn: 'getBy*: returns the element or throws if not found. queryBy*: returns the element or null — used to assert absence. findBy*: returns a Promise and waits for the element to appear (async) — for elements that appear after a request. Plural variants: getAllBy, queryAllBy, findAllBy.',
  },
  {
    id: 'test-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['testing-library', 'async', 'msw'],
    questionRu: 'Как тестировать асинхронные компоненты с Testing Library?',
    questionEn: 'How do you test asynchronous components with Testing Library?',
    answerRu: 'waitFor(() => expect(...)) — ждёт пока assertion не пройдёт. findBy* — async getBy*, ждёт появления элемента. Мокировать fetch/axios через jest.mock или MSW (Mock Service Worker). MSW предпочтительнее — перехватывает реальные сетевые запросы, более реалистично.',
    answerEn: 'waitFor(() => expect(...)) — waits until the assertion passes. findBy* — async version of getBy*, waits for the element to appear. Mock fetch/axios via jest.mock or MSW (Mock Service Worker). MSW is preferred — it intercepts real network requests and is more realistic.',
  },
  {
    id: 'test-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['testing-library', 'user-event', 'fire-event'],
    questionRu: 'Что такое userEvent и чем отличается от fireEvent?',
    questionEn: 'What is userEvent and how does it differ from fireEvent?',
    answerRu: 'fireEvent: напрямую диспатчит DOM событие — быстро но нереалистично. userEvent (v14): симулирует реальное пользовательское взаимодействие — userEvent.type() имитирует каждое нажатие клавиши, фокус, blur. Более реалистично, ловит больше багов. userEvent предпочтительнее для большинства интеракций.',
    answerEn: 'fireEvent: directly dispatches a DOM event — fast but unrealistic. userEvent (v14): simulates real user interactions — userEvent.type() mimics each keypress, focus, and blur. More realistic and catches more bugs. userEvent is preferred for most interactions.',
  },
  {
    id: 'test-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['testing-library', 'context', 'redux'],
    questionRu: 'Как тестировать компоненты с Context или Redux?',
    questionEn: 'How do you test components that use Context or Redux?',
    answerRu: 'Обернуть в провайдер при рендере: render(<Provider store={store}><Component/></Provider>). Создать кастомный render-хелпер с нужными провайдерами. Для Redux: createStore с тестовым состоянием. Для Context: передать нужное value. Testing Library поощряет тестировать с реальными провайдерами, не моками.',
    answerEn: 'Wrap the component in a provider when rendering: render(<Provider store={store}><Component/></Provider>). Create a custom render helper with the required providers. For Redux: use createStore with a test state. For Context: pass the required value. Testing Library encourages testing with real providers rather than mocks.',
  },
  {
    id: 'test-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['msw', 'mocking', 'network'],
    questionRu: 'Что такое MSW (Mock Service Worker)?',
    questionEn: 'What is MSW (Mock Service Worker)?',
    answerRu: 'MSW перехватывает сетевые запросы на уровне Service Worker (браузер) или node-fetch (Node.js/Jest). Позволяет мокировать API реалистично без изменения кода. Хендлеры: http.get(\'/api/users\', resolver). Переиспользуются между тестами и разработкой (storybook, dev режим). Предпочтительнее jest.mock для fetch.',
    answerEn: 'MSW intercepts network requests at the Service Worker level (browser) or via node-fetch (Node.js/Jest). It lets you mock APIs realistically without changing your code. Handlers: http.get(\'/api/users\', resolver). Reusable across tests and during development (Storybook, dev mode). Preferred over jest.mock for fetch.',
  },
  {
    id: 'test-020',
    difficulty: 'EASY',
    order: 20,
    tags: ['e2e', 'fundamentals'],
    questionRu: 'Что такое E2E тестирование и зачем нужно?',
    questionEn: 'What is E2E testing and why is it needed?',
    answerRu: 'E2E тесты проверяют полный пользовательский сценарий через реальный браузер: от клика по кнопке до проверки результата в БД. Ловят баги интеграции которые unit/integration тесты не найдут. Медленные и хрупкие — тестировать только критичные user flows: регистрация, оплата, ключевые сценарии.',
    answerEn: 'E2E tests verify a complete user scenario through a real browser: from clicking a button to checking the result in the database. They catch integration bugs that unit/integration tests will not find. Slow and brittle — only test critical user flows: registration, payment, key scenarios.',
  },
  {
    id: 'test-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['e2e', 'cypress', 'playwright'],
    questionRu: 'В чём разница между Cypress и Playwright?',
    questionEn: 'What is the difference between Cypress and Playwright?',
    answerRu: 'Cypress: только Chromium (+ Firefox/Edge), выполняется внутри браузера, отличный DX, time-travel debugging, встроенный dashboard. Playwright: все браузеры (Chromium, Firefox, WebKit/Safari), выполняется вне браузера, параллельные тесты, лучше для CI. Playwright предпочтительнее для кросс-браузерного тестирования.',
    answerEn: 'Cypress: Chromium only (+ Firefox/Edge), runs inside the browser, excellent DX, time-travel debugging, built-in dashboard. Playwright: all browsers (Chromium, Firefox, WebKit/Safari), runs outside the browser, parallel tests, better for CI. Playwright is preferred for cross-browser testing.',
  },
  {
    id: 'test-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['e2e', 'best-practices'],
    questionRu: 'Как писать надёжные E2E тесты?',
    questionEn: 'How do you write reliable E2E tests?',
    answerRu: 'Не использовать CSS-классы и XPath — хрупко. Предпочитать data-testid или ARIA роли. Ждать появления элементов (cy.get / page.waitFor) вместо sleep. Изолировать тесты — каждый тест с чистым состоянием. Мокировать внешние API. Параллельный запуск для скорости. Page Object Model для переиспользования.',
    answerEn: 'Avoid CSS classes and XPath — they are brittle. Prefer data-testid or ARIA roles. Wait for elements to appear (cy.get / page.waitFor) instead of using sleep. Isolate tests — each test should start with a clean state. Mock external APIs. Run in parallel for speed. Use the Page Object Model for reusability.',
  },
  {
    id: 'test-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['e2e', 'pom', 'patterns'],
    questionRu: 'Что такое Page Object Model (POM)?',
    questionEn: 'What is the Page Object Model (POM)?',
    answerRu: 'POM — паттерн для E2E тестов: каждая страница или компонент представлен классом с методами для взаимодействия. Скрывает селекторы и детали реализации. Пример: LoginPage с методами login(email, password), getErrorMessage(). При изменении UI правишь только класс страницы, не все тесты.',
    answerEn: 'POM is a pattern for E2E tests where each page or component is represented by a class with interaction methods. It hides selectors and implementation details. Example: a LoginPage class with login(email, password) and getErrorMessage() methods. When the UI changes, you only update the page class, not every test.',
  },
  {
    id: 'test-024',
    difficulty: 'MEDIUM',
    order: 24,
    tags: ['e2e', 'ci-cd'],
    questionRu: 'Как запускать тесты в CI/CD?',
    questionEn: 'How do you run tests in CI/CD?',
    answerRu: 'Unit/integration тесты: на каждый PR, быстро (<5 мин). E2E: на merge в main или как отдельный stage. Инструменты: GitHub Actions, GitLab CI. Для E2E: headless режим, параллелизация (Playwright sharding, Cypress Cloud). Cypress/Playwright записывают видео и скриншоты при падении. Flaky тесты помечать и чинить приоритетно.',
    answerEn: 'Unit/integration tests: on every PR, fast (<5 min). E2E: on merge to main or as a separate stage. Tools: GitHub Actions, GitLab CI. For E2E: headless mode, parallelization (Playwright sharding, Cypress Cloud). Cypress/Playwright record videos and screenshots on failure. Mark flaky tests and fix them as a priority.',
  },
];
