import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'test-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['pyramid', 'fundamentals'],
    questionRu: 'Что такое пирамида тестирования?',
    questionEn: 'What is the testing pyramid?',
    answerRu: '**Пирамида тестирования** (снизу вверх):\n\n- **Unit** — много, быстрые, дешёвые\n- **Integration** — меньше\n- **E2E** — мало, медленные, дорогие\n\nЧем выше уровень — тем медленнее и дороже. Цель: максимум покрытия при минимуме затрат.\n\n**Антипаттерн** — перевёрнутая пирамида (много E2E, мало unit).',
    answerEn: 'The **testing pyramid** (bottom to top):\n\n- **Unit** — many, fast, cheap\n- **Integration** — fewer\n- **E2E** — few, slow, expensive\n\nThe higher the level, the slower and more costly. Goal: maximum coverage at minimum cost.\n\n**Anti-pattern**: the inverted pyramid (many E2E, few unit tests).',
  },
  {
    id: 'test-002',
    difficulty: 'EASY',
    order: 2,
    tags: ['unit', 'integration', 'e2e'],
    questionRu: 'В чём разница между unit, integration и E2E тестами?',
    questionEn: 'What is the difference between unit, integration, and E2E tests?',
    answerRu: '- **Unit**: тестирует изолированную функцию/модуль, зависимости замокированы. Быстро, легко отлаживать.\n- **Integration**: тестирует взаимодействие нескольких модулей вместе.\n- **E2E**: тестирует полный сценарий через реальный браузер — от UI до БД. Медленно, но проверяет реальный пользовательский путь.',
    answerEn: '- **Unit**: tests an isolated function/module with mocked dependencies. Fast and easy to debug.\n- **Integration**: tests how multiple modules work together.\n- **E2E**: tests a complete scenario through a real browser — from the UI down to the database. Slow, but verifies a real user journey.',
  },
  {
    id: 'test-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['tdd', 'methodology'],
    questionRu: 'Что такое TDD (Test-Driven Development)?',
    questionEn: 'What is TDD (Test-Driven Development)?',
    answerRu: '**TDD** — подход: сначала пишешь тест → пишешь минимальный код чтобы тест прошёл → рефакторишь.\n\nЦикл: **red → green → refactor**.\n\n**Преимущества:**\n- продуманный API до реализации\n- высокое покрытие\n- меньше регрессий\n\n**Минусы:**\n- медленнее разработка поначалу\n- сложно для UI',
    answerEn: '**TDD** is an approach where you write the test first → write the minimal code to make it pass → refactor.\n\nCycle: **red → green → refactor**.\n\n**Advantages:**\n- well-designed API before implementation\n- high coverage\n- fewer regressions\n\n**Drawbacks:**\n- slower to start\n- harder to apply to UI',
  },
  {
    id: 'test-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['coverage'],
    questionRu: 'Что такое покрытие кода (code coverage) и какой процент считается хорошим?',
    questionEn: 'What is code coverage and what percentage is considered good?',
    answerRu: '**Coverage** — процент кода, выполненного при тестах.\n\n**Типы:**\n- `statement`\n- `branch`\n- `function`\n- `line`\n\n100% coverage не означает отсутствие багов — важно качество тестов.\n\n**Ориентиры:**\n- 70–80% для большинства проектов\n- 90%+ для критичной бизнес-логики\n\nНе гнаться за цифрой ради цифры.',
    answerEn: '**Coverage** is the percentage of code executed during tests.\n\n**Types:**\n- `statement`\n- `branch`\n- `function`\n- `line`\n\n100% coverage does not mean zero bugs — test quality matters more than the number.\n\n**Targets:**\n- 70–80% for most projects\n- 90%+ for critical business logic\n\nDon\'t chase the number for its own sake.',
  },
  {
    id: 'test-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['snapshot', 'jest'],
    questionRu: 'Что такое snapshot тестирование?',
    questionEn: 'What is snapshot testing?',
    answerRu: '**Snapshot тест** сохраняет сериализованный вывод компонента и сравнивает с ним при следующих запусках.\n\n**Плюсы:**\n- легко создать\n- ловит неожиданные изменения UI\n\n**Минусы:**\n- легко обновить не глядя (`jest --updateSnapshot`)\n- большие снепшоты трудно читать\n\nПолезны для стабильных UI-компонентов, но не замена семантическим тестам.',
    answerEn: 'A **snapshot test** saves the serialized output of a component and compares it on subsequent runs.\n\n**Pros:**\n- easy to create\n- catches unexpected UI changes\n\n**Cons:**\n- easy to update blindly (`jest --updateSnapshot`)\n- large snapshots are hard to read\n\nUseful for stable UI components, but not a replacement for semantic tests.',
  },
  {
    id: 'test-006',
    difficulty: 'HARD',
    order: 6,
    tags: ['mutation-testing', 'stryker'],
    questionRu: 'Что такое мутационное тестирование?',
    questionEn: 'What is mutation testing?',
    answerRu: '**Мутационное тестирование** автоматически вносит мелкие изменения в код (**мутации**) и проверяет, упадут ли тесты.\n\nЕсли тест не поймал мутацию — он слабый.\n\n**Инструмент:** `Stryker`\n\nПоказывает реальное качество тестов, а не просто coverage. Медленно — запускать не на каждом коммите.',
    answerEn: '**Mutation testing** automatically introduces small changes to the code (**mutations**) and checks whether the tests catch them.\n\nIf a test misses a mutation, it is weak.\n\n**Tool:** `Stryker`\n\nIt reveals the real quality of your tests, not just coverage figures. It is slow — do not run it on every commit.',
  },
  {
    id: 'test-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['jest', 'unit'],
    questionRu: 'Что такое Jest и как устроен тест?',
    questionEn: 'What is Jest and how is a test structured?',
    answerRu: '**Jest** — фреймворк для тестирования JS/TS.\n\n**Структура теста:** `describe` (группа) → `it`/`test` (один тест) → `expect(value).matcher()`\n\n**Встроено:**\n- моки (`jest.fn`, `jest.mock`)\n- `coverage`\n- `watch` mode\n- `jsdom`\n\nРаботает из коробки с CRA, Vite (`vitest`), Next.js. Конфигурация в `jest.config.js` или `package.json`.',
    answerEn: '**Jest** is a testing framework for JS/TS.\n\n**Test structure:** `describe` (test group) → `it`/`test` (single test) → `expect(value).matcher()`\n\n**Built-in:**\n- mocks (`jest.fn`, `jest.mock`)\n- `coverage`\n- `watch` mode\n- `jsdom`\n\nWorks out of the box with CRA, Vite (`vitest`), Next.js. Configured via `jest.config.js` or `package.json`.',
  },
  {
    id: 'test-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['jest', 'mocks'],
    questionRu: 'Что такое моки (mocks) и зачем нужны?',
    questionEn: 'What are mocks and why are they needed?',
    answerRu: '**Мок** — замена реальной зависимости на контролируемую версию.\n\n**Зачем:**\n- изолировать тестируемый модуль\n- контролировать поведение зависимостей\n- проверять вызовы\n\n**В Jest:**\n- `jest.fn()` — мок-функция\n- `jest.mock(\'./module\')` — мок модуля\n- `jest.spyOn(obj, \'method\')` — шпион на метод без замены реализации',
    answerEn: 'A **mock** replaces a real dependency with a controlled version.\n\n**Why:**\n- isolate the module under test\n- control dependency behavior\n- verify calls\n\n**In Jest:**\n- `jest.fn()` — mock function\n- `jest.mock(\'./module\')` — module mock\n- `jest.spyOn(obj, \'method\')` — spy on a method without replacing its implementation',
  },
  {
    id: 'test-009',
    difficulty: 'MEDIUM',
    order: 9,
    tags: ['jest', 'mocks', 'stubs', 'spies'],
    questionRu: 'В чём разница между mock, stub и spy?',
    questionEn: 'What is the difference between a mock, a stub, and a spy?',
    answerRu: '- **Stub**: возвращает заранее заданное значение, не проверяет вызовы.\n- **Mock**: задаёт ожидания о вызовах — проверяет был ли вызван, с какими аргументами.\n- **Spy**: оборачивает реальную реализацию, позволяя наблюдать за вызовами без замены.\n\nВ Jest `jest.fn()` объединяет stub и mock; `jest.spyOn` — spy.',
    answerEn: '- **Stub**: returns a predefined value, does not verify calls.\n- **Mock**: sets expectations on calls — checks whether the function was called and with what arguments.\n- **Spy**: wraps the real implementation, allowing you to observe calls without replacing it.\n\nIn Jest, `jest.fn()` combines stub and mock; `jest.spyOn` is a spy.',
  },
  {
    id: 'test-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['jest', 'async'],
    questionRu: 'Как тестировать асинхронный код в Jest?',
    questionEn: 'How do you test asynchronous code in Jest?',
    answerRu: '**Три способа:**\n\n1. `async/await`: `it(\'test\', async () => { const result = await fetchData(); expect(result).toBe(...) })`\n2. Вернуть промис: `return expect(promise).resolves.toBe(...)`\n3. `done` колбэк (устаревший)\n\nДля таймеров: `jest.useFakeTimers()` + `jest.runAllTimers()`\n\nОбязательно `await` или `return` промис, иначе тест не ждёт.',
    answerEn: '**Three approaches:**\n\n1. `async/await`: `it(\'test\', async () => { const result = await fetchData(); expect(result).toBe(...) })`\n2. Return a promise: `return expect(promise).resolves.toBe(...)`\n3. `done` callback (deprecated)\n\nFor timers: `jest.useFakeTimers()` + `jest.runAllTimers()`\n\nAlways `await` or `return` the promise, otherwise the test won\'t wait.',
  },
  {
    id: 'test-011',
    difficulty: 'EASY',
    order: 11,
    tags: ['jest', 'lifecycle'],
    questionRu: 'Что такое beforeEach, afterEach, beforeAll, afterAll?',
    questionEn: 'What are beforeEach, afterEach, beforeAll, and afterAll?',
    answerRu: '- `beforeEach` / `afterEach`: выполняются до/после каждого теста в `describe`.\n- `beforeAll` / `afterAll`: один раз до/после всех тестов в `describe`.\n\n**Используются для:**\n- **setup/teardown** состояния\n- очистки моков (`jest.clearAllMocks()`)\n- создания/удаления тестовых данных\n\n`beforeEach` предпочтительнее `beforeAll` для изоляции тестов.',
    answerEn: '- `beforeEach` / `afterEach`: run before/after each test in a `describe` block.\n- `beforeAll` / `afterAll`: run once before/after all tests in a `describe` block.\n\n**Used for:**\n- **setup/teardown** of state\n- clearing mocks (`jest.clearAllMocks()`)\n- creating/deleting test data\n\n`beforeEach` is preferred over `beforeAll` for better test isolation.',
  },
  {
    id: 'test-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['jest', 'parametrized'],
    questionRu: 'Что такое параметризованные тесты (test.each)?',
    questionEn: 'What are parameterized tests (test.each)?',
    answerRu: '`test.each` позволяет запустить один тест с разными данными:\n\n```\ntest.each([[1,2,3],[2,3,5]])(\'adds %i + %i = %i\', (a,b,expected) => {\n  expect(a+b).toBe(expected)\n})\n```\n\n- Уменьшает дублирование\n- Поддерживает tagged template literals для читаемости\n- Полезно для тестирования граничных значений',
    answerEn: '`test.each` lets you run the same test with different data:\n\n```\ntest.each([[1,2,3],[2,3,5]])(\'adds %i + %i = %i\', (a,b,expected) => {\n  expect(a+b).toBe(expected)\n})\n```\n\n- Reduces duplication\n- Supports tagged template literals for readability\n- Useful for testing boundary values',
  },
  {
    id: 'test-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['vitest', 'vite'],
    questionRu: 'Что такое Vitest и чем отличается от Jest?',
    questionEn: 'What is Vitest and how does it differ from Jest?',
    answerRu: '**Vitest** — современный тест-фреймворк на основе **Vite**. Совместим с Jest API.\n\n**Преимущества:**\n- нативная поддержка ES modules и TypeScript без настройки\n- в разы быстрее за счёт Vite трансформаций\n- общий конфиг с Vite\n\n**Минусы:**\n- меньше экосистема\n\nПредпочтителен для Vite-проектов.',
    answerEn: '**Vitest** is a modern test framework built on top of **Vite**. Compatible with the Jest API.\n\n**Advantages:**\n- native ES modules and TypeScript support with no configuration\n- significantly faster due to Vite transforms\n- shared config with Vite\n\n**Drawbacks:**\n- smaller ecosystem\n\nPreferred for Vite-based projects.',
  },
  {
    id: 'test-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['testing-library', 'react'],
    questionRu: 'Что такое Testing Library и в чём её философия?',
    questionEn: 'What is Testing Library and what is its philosophy?',
    answerRu: '**Testing Library** — библиотека для тестирования компонентов через пользовательское взаимодействие.\n\n**Философия:** тестируй как пользователь, не детали реализации.\n\n**Приоритет запросов:**\n1. `getByRole`\n2. `getByLabelText`\n3. `getByText`\n4. `getByTestId`\n\nНе тестировать: внутренний state, методы компонента, детали рендеринга.',
    answerEn: '**Testing Library** is a library for testing components through user interactions.\n\n**Philosophy:** test the way a user would, not implementation details.\n\n**Query priority:**\n1. `getByRole`\n2. `getByLabelText`\n3. `getByText`\n4. `getByTestId`\n\nDo not test: internal state, component methods, or rendering details.',
  },
  {
    id: 'test-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['testing-library', 'queries'],
    questionRu: 'В чём разница между getBy, queryBy и findBy?',
    questionEn: 'What is the difference between getBy, queryBy, and findBy?',
    answerRu: '- `getBy*`: возвращает элемент или бросает ошибку если не найден.\n- `queryBy*`: возвращает элемент или `null` — для проверки отсутствия.\n- `findBy*`: возвращает `Promise`, ждёт появления элемента (async) — для элементов появляющихся после запроса.\n\n**Множественные варианты:** `getAllBy`, `queryAllBy`, `findAllBy`.',
    answerEn: '- `getBy*`: returns the element or throws if not found.\n- `queryBy*`: returns the element or `null` — used to assert absence.\n- `findBy*`: returns a `Promise` and waits for the element to appear (async) — for elements that appear after a request.\n\n**Plural variants:** `getAllBy`, `queryAllBy`, `findAllBy`.',
  },
  {
    id: 'test-016',
    difficulty: 'MEDIUM',
    order: 16,
    tags: ['testing-library', 'async', 'msw'],
    questionRu: 'Как тестировать асинхронные компоненты с Testing Library?',
    questionEn: 'How do you test asynchronous components with Testing Library?',
    answerRu: '- `waitFor(() => expect(...))` — ждёт пока assertion не пройдёт.\n- `findBy*` — async-версия `getBy*`, ждёт появления элемента.\n- Мокировать `fetch`/`axios` через `jest.mock` или **MSW** (Mock Service Worker).\n\n**MSW предпочтительнее** — перехватывает реальные сетевые запросы, более реалистично.',
    answerEn: '- `waitFor(() => expect(...))` — waits until the assertion passes.\n- `findBy*` — async version of `getBy*`, waits for the element to appear.\n- Mock `fetch`/`axios` via `jest.mock` or **MSW** (Mock Service Worker).\n\n**MSW is preferred** — it intercepts real network requests and is more realistic.',
  },
  {
    id: 'test-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['testing-library', 'user-event', 'fire-event'],
    questionRu: 'Что такое userEvent и чем отличается от fireEvent?',
    questionEn: 'What is userEvent and how does it differ from fireEvent?',
    answerRu: '- `fireEvent`: напрямую диспатчит DOM-событие — быстро, но нереалистично.\n- `userEvent` (v14): симулирует реальное пользовательское взаимодействие — `userEvent.type()` имитирует каждое нажатие клавиши, `focus`, `blur`. Более реалистично, ловит больше багов.\n\n`userEvent` предпочтительнее для большинства интеракций.',
    answerEn: '- `fireEvent`: directly dispatches a DOM event — fast but unrealistic.\n- `userEvent` (v14): simulates real user interactions — `userEvent.type()` mimics each keypress, `focus`, and `blur`. More realistic and catches more bugs.\n\n`userEvent` is preferred for most interactions.',
  },
  {
    id: 'test-018',
    difficulty: 'MEDIUM',
    order: 18,
    tags: ['testing-library', 'context', 'redux'],
    questionRu: 'Как тестировать компоненты с Context или Redux?',
    questionEn: 'How do you test components that use Context or Redux?',
    answerRu: 'Обернуть в провайдер при рендере:\n\n```\nrender(<Provider store={store}><Component/></Provider>)\n```\n\n- Создать кастомный `render`-хелпер с нужными провайдерами.\n- Для Redux: `createStore` с тестовым состоянием.\n- Для Context: передать нужное `value`.\n\nTesting Library поощряет тестировать с реальными провайдерами, не моками.',
    answerEn: 'Wrap the component in a provider when rendering:\n\n```\nrender(<Provider store={store}><Component/></Provider>)\n```\n\n- Create a custom `render` helper with the required providers.\n- For Redux: use `createStore` with a test state.\n- For Context: pass the required `value`.\n\nTesting Library encourages testing with real providers rather than mocks.',
  },
  {
    id: 'test-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['msw', 'mocking', 'network'],
    questionRu: 'Что такое MSW (Mock Service Worker)?',
    questionEn: 'What is MSW (Mock Service Worker)?',
    answerRu: '**MSW** перехватывает сетевые запросы на уровне **Service Worker** (браузер) или `node-fetch` (Node.js/Jest).\n\nПозволяет мокировать API реалистично без изменения кода.\n\n**Хендлеры:** `http.get(\'/api/users\', resolver)`\n\n- Переиспользуются между тестами и разработкой (Storybook, `dev` режим).\n- Предпочтительнее `jest.mock` для `fetch`.',
    answerEn: '**MSW** intercepts network requests at the **Service Worker** level (browser) or via `node-fetch` (Node.js/Jest).\n\nIt lets you mock APIs realistically without changing your code.\n\n**Handlers:** `http.get(\'/api/users\', resolver)`\n\n- Reusable across tests and during development (Storybook, `dev` mode).\n- Preferred over `jest.mock` for `fetch`.',
  },
  {
    id: 'test-020',
    difficulty: 'EASY',
    order: 20,
    tags: ['e2e', 'fundamentals'],
    questionRu: 'Что такое E2E тестирование и зачем нужно?',
    questionEn: 'What is E2E testing and why is it needed?',
    answerRu: '**E2E тесты** проверяют полный пользовательский сценарий через реальный браузер: от клика по кнопке до проверки результата в БД.\n\nЛовят баги интеграции, которые unit/integration тесты не найдут.\n\nМедленные и хрупкие — тестировать только критичные user flows:\n- регистрация\n- оплата\n- ключевые сценарии',
    answerEn: '**E2E tests** verify a complete user scenario through a real browser: from clicking a button to checking the result in the database.\n\nThey catch integration bugs that unit/integration tests will not find.\n\nSlow and brittle — only test critical user flows:\n- registration\n- payment\n- key scenarios',
  },
  {
    id: 'test-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['e2e', 'cypress', 'playwright'],
    questionRu: 'В чём разница между Cypress и Playwright?',
    questionEn: 'What is the difference between Cypress and Playwright?',
    answerRu: '**Cypress:**\n- только Chromium (+ Firefox/Edge)\n- выполняется внутри браузера\n- отличный DX, **time-travel debugging**\n- встроенный **dashboard**\n\n**Playwright:**\n- все браузеры (Chromium, Firefox, WebKit/Safari)\n- выполняется вне браузера\n- параллельные тесты, лучше для CI\n\nPlaywright предпочтительнее для **кросс-браузерного** тестирования.',
    answerEn: '**Cypress:**\n- Chromium only (+ Firefox/Edge)\n- runs inside the browser\n- excellent DX, **time-travel debugging**\n- built-in **dashboard**\n\n**Playwright:**\n- all browsers (Chromium, Firefox, WebKit/Safari)\n- runs outside the browser\n- parallel tests, better for CI\n\nPlaywright is preferred for **cross-browser** testing.',
  },
  {
    id: 'test-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['e2e', 'best-practices'],
    questionRu: 'Как писать надёжные E2E тесты?',
    questionEn: 'How do you write reliable E2E tests?',
    answerRu: '- Не использовать CSS-классы и XPath — хрупко. Предпочитать `data-testid` или **ARIA роли**.\n- Ждать появления элементов (`cy.get` / `page.waitFor`) вместо `sleep`.\n- Изолировать тесты — каждый тест с **чистым состоянием**.\n- Мокировать внешние API.\n- Параллельный запуск для скорости.\n- **Page Object Model** для переиспользования.',
    answerEn: '- Avoid CSS classes and XPath — they are brittle. Prefer `data-testid` or **ARIA roles**.\n- Wait for elements to appear (`cy.get` / `page.waitFor`) instead of `sleep`.\n- Isolate tests — each test should start with a **clean state**.\n- Mock external APIs.\n- Run in parallel for speed.\n- Use the **Page Object Model** for reusability.',
  },
  {
    id: 'test-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['e2e', 'pom', 'patterns'],
    questionRu: 'Что такое Page Object Model (POM)?',
    questionEn: 'What is the Page Object Model (POM)?',
    answerRu: '**POM** — паттерн для E2E тестов: каждая страница или компонент представлен классом с методами для взаимодействия.\n\nСкрывает селекторы и детали реализации.\n\n**Пример:** класс `LoginPage` с методами `login(email, password)` и `getErrorMessage()`.\n\nПри изменении UI правишь только класс страницы, не все тесты.',
    answerEn: '**POM** is a pattern for E2E tests where each page or component is represented by a class with interaction methods.\n\nIt hides selectors and implementation details.\n\n**Example:** a `LoginPage` class with `login(email, password)` and `getErrorMessage()` methods.\n\nWhen the UI changes, you only update the page class, not every test.',
  },
  {
    id: 'test-024',
    difficulty: 'MEDIUM',
    order: 24,
    tags: ['e2e', 'ci-cd'],
    questionRu: 'Как запускать тесты в CI/CD?',
    questionEn: 'How do you run tests in CI/CD?',
    answerRu: '- **Unit/integration тесты:** на каждый PR, быстро (< 5 мин).\n- **E2E:** на merge в `main` или как отдельный stage.\n\n**Инструменты:** GitHub Actions, GitLab CI.\n\nДля E2E: `headless` режим, параллелизация (Playwright `sharding`, Cypress Cloud).\n\nCypress/Playwright записывают видео и скриншоты при падении. **Flaky** тесты помечать и чинить приоритетно.',
    answerEn: '- **Unit/integration tests:** on every PR, fast (< 5 min).\n- **E2E:** on merge to `main` or as a separate stage.\n\n**Tools:** GitHub Actions, GitLab CI.\n\nFor E2E: `headless` mode, parallelization (Playwright `sharding`, Cypress Cloud).\n\nCypress/Playwright record videos and screenshots on failure. Mark **flaky** tests and fix them as a priority.',
  },
];
