import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'tools-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['bundler', 'webpack', 'vite'],
    questionRu: 'Что такое бандлер и зачем нужен?',
    questionEn: 'What is a bundler and why is it needed?',
    answerRu: '**Бандлер** собирает модули и зависимости в один или несколько файлов для браузера.\n\nЗадачи:\n- разрешение импортов\n- транспиляция (`TS`/`JSX` → `JS`)\n- минификация\n- **code splitting**\n- **tree shaking**\n- обработка ассетов (`CSS`, изображения)\n\nОсновные: **Webpack**, **Vite**, **Rollup**, **Parcel**, **esbuild**.',
    answerEn: 'A **bundler** assembles modules and dependencies into one or more files for the browser.\n\nResponsibilities:\n- resolving imports\n- transpilation (`TS`/`JSX` → `JS`)\n- minification\n- **code splitting**\n- **tree shaking**\n- asset handling (`CSS`, images)\n\nMain bundlers: **Webpack**, **Vite**, **Rollup**, **Parcel**, **esbuild**.',
  },
  {
    id: 'tools-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['webpack', 'bundler'],
    questionRu: 'Как работает Webpack?',
    questionEn: 'How does Webpack work?',
    answerRu: '**Webpack** строит граф зависимостей начиная с **entry point**.\n\n- **Loaders** трансформируют файлы (`babel-loader` для JS, `css-loader` для CSS)\n- **Plugins** расширяют функциональность (`HtmlWebpackPlugin`, `MiniCssExtractPlugin`)\n- **Output** — один или несколько бандлов\n\n**Mode**: `development` (быстро) или `production` (оптимизация).',
    answerEn: '**Webpack** builds a dependency graph starting from the **entry point**.\n\n- **Loaders** transform files (`babel-loader` for JS, `css-loader` for CSS)\n- **Plugins** extend functionality (`HtmlWebpackPlugin`, `MiniCssExtractPlugin`)\n- **Output** is one or more bundles\n\n**Mode**: `development` (fast) or `production` (optimized).',
  },
  {
    id: 'tools-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['vite', 'webpack', 'bundler'],
    questionRu: 'Чем Vite отличается от Webpack?',
    questionEn: 'How does Vite differ from Webpack?',
    answerRu: '**Vite** в dev режиме не бандлит — отдаёт **ES модули** напрямую браузеру, трансформирует файлы по запросу через `esbuild`.\n\n- Старт мгновенный независимо от размера проекта\n- **HMR** быстрее\n- Production: **Rollup** под капотом\n\n**Webpack** бандлит всё при старте — медленнее для больших проектов.\n\n**Vite** предпочтителен для новых проектов.',
    answerEn: 'In dev mode, **Vite** does not bundle — it serves **ES modules** directly to the browser and transforms files on demand via `esbuild`.\n\n- Startup is instant regardless of project size\n- **HMR** is faster\n- Production: **Rollup** under the hood\n\n**Webpack** bundles everything at startup — slower for large projects.\n\n**Vite** is preferred for new projects.',
  },
  {
    id: 'tools-004',
    difficulty: 'EASY',
    order: 4,
    tags: ['hmr', 'vite', 'webpack'],
    questionRu: 'Что такое HMR (Hot Module Replacement)?',
    questionEn: 'What is HMR (Hot Module Replacement)?',
    answerRu: '**HMR** — замена модулей в браузере без полной перезагрузки страницы.\n\nПри изменении файла только изменённый модуль заменяется, состояние приложения сохраняется.\n\n- **Vite** и **Webpack** поддерживают HMR\n- **React Fast Refresh** — HMR для React компонентов с сохранением `state`\n\nЗначительно ускоряет разработку.',
    answerEn: '**HMR** replaces modules in the browser without a full page reload.\n\nWhen a file changes, only the changed module is replaced and the application state is preserved.\n\n- **Vite** and **Webpack** both support HMR\n- **React Fast Refresh** is HMR for React components with `state` preservation\n\nIt significantly speeds up development.',
  },
  {
    id: 'tools-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['source-maps', 'debugging'],
    questionRu: 'Что такое source maps?',
    questionEn: 'What are source maps?',
    answerRu: '**Source maps** — файлы (`.map`) маппящие минифицированный/транспилированный код обратно к исходному.\n\nБраузер автоматически использует их в DevTools — видишь оригинальный `TypeScript`/`JSX` вместо бандла.\n\n- В production: отдельные `.map` файлы (не включать в бандл)\n- `hidden-source-map` — для Sentry без публичного доступа',
    answerEn: '**Source maps** are `.map` files that map minified/transpiled code back to the original source.\n\nThe browser automatically uses them in DevTools — you see the original `TypeScript`/`JSX` instead of the bundle.\n\n- In production: use separate `.map` files (do not include them in the bundle)\n- `hidden-source-map` — for Sentry without public access',
  },
  {
    id: 'tools-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['babel', 'transpiler'],
    questionRu: 'Что такое Babel и для чего используется?',
    questionEn: 'What is Babel and what is it used for?',
    answerRu: '**Babel** — транспилятор JS: преобразует современный JS (`ES2022+`, `JSX`, `TypeScript`) в совместимый со старыми браузерами.\n\n- **Плагины** трансформируют конкретные фичи\n- **Presets** — набор плагинов: `@babel/preset-env` (по `browserslist`), `@babel/preset-react`, `@babel/preset-typescript`\n\nСейчас часто заменяется `esbuild`/`SWC` для скорости.',
    answerEn: '**Babel** is a JS transpiler that converts modern JS (`ES2022+`, `JSX`, `TypeScript`) into code compatible with older browsers.\n\n- **Plugins** transform specific features\n- **Presets** are collections of plugins: `@babel/preset-env` (based on `browserslist`), `@babel/preset-react`, `@babel/preset-typescript`\n\nIt is now often replaced by `esbuild`/`SWC` for performance.',
  },
  {
    id: 'tools-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['eslint', 'prettier', 'linting'],
    questionRu: 'Что такое ESLint и Prettier и в чём разница?',
    questionEn: 'What are ESLint and Prettier, and what is the difference between them?',
    answerRu: '**ESLint** — линтер: анализирует код на ошибки и антипаттерны, применяет правила (`no-unused-vars`, `react-hooks/rules-of-hooks`), может автофиксить.\n\n**Prettier** — форматтер: единый стиль кода (отступы, кавычки, точки с запятой), не анализирует логику.\n\nИспользуются вместе: **ESLint** для качества кода, **Prettier** для форматирования.',
    answerEn: '**ESLint** is a linter: it analyzes code for errors and anti-patterns, enforces rules (`no-unused-vars`, `react-hooks/rules-of-hooks`), and can auto-fix issues.\n\n**Prettier** is a formatter: it enforces a consistent code style (indentation, quotes, semicolons) and does not analyze logic.\n\nThey are used together: **ESLint** for code quality, **Prettier** for formatting.',
  },
  {
    id: 'tools-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['git', 'merge', 'rebase'],
    questionRu: 'В чём разница между merge и rebase?',
    questionEn: 'What is the difference between merge and rebase?',
    answerRu: '**`git merge`**: объединяет ветки, создаёт merge commit, сохраняет историю ветвлений — история нелинейная.\n\n**`git rebase`**: переносит коммиты поверх другой ветки — линейная история.\n\n- Не использовать `rebase` на публичных ветках (изменяет SHA коммитов)\n- `merge` — для публичных веток\n- `rebase` — для локальной очистки истории',
    answerEn: '**`git merge`**: combines branches, creates a merge commit, preserves branching history — non-linear history.\n\n**`git rebase`**: replays commits on top of another branch — produces a linear history.\n\n- Do not `rebase` public branches (it rewrites commit SHAs)\n- Use `merge` for public branches\n- Use `rebase` for cleaning up local history',
  },
  {
    id: 'tools-009',
    difficulty: 'EASY',
    order: 9,
    tags: ['git', 'stash'],
    questionRu: 'Что такое git stash?',
    questionEn: 'What is git stash?',
    answerRu: '`git stash` сохраняет незакоммиченные изменения во временное хранилище и возвращает рабочую директорию к `HEAD`.\n\nПолезно для переключения веток без коммита.\n\n- `git stash pop` — восстановить и удалить из стека\n- `git stash apply` — восстановить, оставить в стеке\n- `git stash list` — все сохранённые изменения',
    answerEn: '`git stash` saves uncommitted changes to a temporary storage area and restores the working directory to `HEAD`.\n\nUseful for switching branches without committing.\n\n- `git stash pop` — restore and remove from the stack\n- `git stash apply` — restore and keep in the stack\n- `git stash list` — list all stashed changes',
  },
  {
    id: 'tools-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['git', 'rebase', 'history'],
    questionRu: 'Что такое git rebase -i (interactive rebase)?',
    questionEn: 'What is git rebase -i (interactive rebase)?',
    answerRu: '**Interactive rebase** (`git rebase -i`) позволяет редактировать историю коммитов.\n\nДоступные операции:\n- `squash` — объединить в один коммит\n- `reword` — переименовать коммит\n- `edit` — изменить коммит\n- `drop` — удалить коммит\n- `reorder` — переупорядочить\n\nИспользовать для очистки истории feature-ветки перед merge. Не применять к коммитам, которые уже запушены и используются другими.',
    answerEn: '**Interactive rebase** (`git rebase -i`) lets you edit commit history.\n\nAvailable operations:\n- `squash` — combine into one commit\n- `reword` — rename a commit\n- `edit` — modify a commit\n- `drop` — delete a commit\n- `reorder` — reorder commits\n\nUse it to clean up a feature branch history before merging. Do not apply it to commits that have already been pushed and are used by others.',
  },
  {
    id: 'tools-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['git', 'cherry-pick'],
    questionRu: 'Что такое git cherry-pick?',
    questionEn: 'What is git cherry-pick?',
    answerRu: '`git cherry-pick <commit-hash>` применяет конкретный коммит из другой ветки к текущей.\n\nПолезно для:\n- переноса hotfix из `main` в release ветку\n- взятия одного коммита без merge всей ветки\n\nСоздаёт новый коммит с тем же изменением, но другим SHA. Конфликты разрешаются вручную.',
    answerEn: '`git cherry-pick <commit-hash>` applies a specific commit from another branch to the current branch.\n\nUseful for:\n- porting a hotfix from `main` to a release branch\n- taking a single commit without merging the entire branch\n\nIt creates a new commit with the same change but a different SHA. Conflicts must be resolved manually.',
  },
  {
    id: 'tools-012',
    difficulty: 'HARD',
    order: 12,
    tags: ['git', 'bisect', 'debugging'],
    questionRu: 'Что такое git bisect?',
    questionEn: 'What is git bisect?',
    answerRu: '`git bisect` — бинарный поиск коммита, введшего баг.\n\nПроцесс:\n1. `git bisect start`\n2. `git bisect bad` (текущий)\n3. `git bisect good <hash>`\n4. Git переключает на середину → помечаешь `good`/`bad` → повторять\n\nНаходит проблемный коммит за `O(log n)` шагов.\n\nМожно автоматизировать: `git bisect run npm test`.',
    answerEn: '`git bisect` performs a binary search to find the commit that introduced a bug.\n\nProcess:\n1. `git bisect start`\n2. `git bisect bad` (current)\n3. `git bisect good <hash>`\n4. Git checks out the midpoint → mark `good`/`bad` → repeat\n\nFinds the offending commit in `O(log n)` steps.\n\nCan be automated: `git bisect run npm test`.',
  },
  {
    id: 'tools-013',
    difficulty: 'EASY',
    order: 13,
    tags: ['git', 'conventional-commits'],
    questionRu: 'Что такое Conventional Commits?',
    questionEn: 'What are Conventional Commits?',
    answerRu: '**Conventional Commits** — соглашение о формате коммитов: `type(scope): description`.\n\nТипы:\n- `feat` — новая фича\n- `fix` — баг\n- `docs`, `style`, `refactor`, `test`, `chore`\n\nПозволяет:\n- автогенерацию `CHANGELOG`\n- автоматическое управление версиями (`semantic-release`)\n- понятную историю\n\nИнструменты: `commitlint`, `commitizen`.',
    answerEn: '**Conventional Commits** is a convention for commit message formatting: `type(scope): description`.\n\nTypes:\n- `feat` — new feature\n- `fix` — bug fix\n- `docs`, `style`, `refactor`, `test`, `chore`\n\nEnables:\n- automatic `CHANGELOG` generation\n- automated versioning (`semantic-release`)\n- a readable history\n\nTools: `commitlint`, `commitizen`.',
  },
  {
    id: 'tools-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['npm', 'yarn', 'pnpm', 'package-manager'],
    questionRu: 'В чём разница между npm, yarn и pnpm?',
    questionEn: 'What is the difference between npm, yarn, and pnpm?',
    answerRu: '- **npm**: стандартный, медленнее\n- **yarn** (classic): параллельная установка, `yarn.lock`\n- **yarn berry**: PnP без `node_modules`\n- **pnpm**: content-addressable store — пакеты не дублируются между проектами, жёсткие ссылки, строгий доступ к зависимостям\n\n**pnpm** быстрее и экономит дисковое место. В монорепозиториях `pnpm workspaces` предпочтителен.',
    answerEn: '- **npm**: the standard package manager, relatively slow\n- **yarn** (classic): parallel installation, `yarn.lock`\n- **yarn berry**: Plug\'n\'Play without `node_modules`\n- **pnpm**: content-addressable store — packages are not duplicated across projects, uses hard links, strict dependency access\n\n**pnpm** is faster and saves disk space. `pnpm workspaces` is preferred for monorepos.',
  },
  {
    id: 'tools-015',
    difficulty: 'EASY',
    order: 15,
    tags: ['npm', 'lock-file', 'reproducibility'],
    questionRu: 'Что такое lock-файл и зачем нужен?',
    questionEn: 'What is a lock file and why is it needed?',
    answerRu: '**Lock-файл** (`package-lock.json`, `yarn.lock`, `pnpm-lock.yaml`) фиксирует точные версии всех зависимостей, включая транзитивные.\n\nОбеспечивает воспроизводимые сборки — `npm install` даёт одинаковый результат на всех машинах.\n\n- Всегда коммитить в репозиторий\n- `npm ci` для production — устанавливает строго по lock-файлу',
    answerEn: 'A **lock file** (`package-lock.json`, `yarn.lock`, `pnpm-lock.yaml`) pins the exact versions of all dependencies including transitive ones.\n\nIt ensures reproducible builds — `npm install` produces the same result on every machine.\n\n- Always commit it to the repository\n- Use `npm ci` for production — it installs strictly according to the lock file',
  },
  {
    id: 'tools-016',
    difficulty: 'EASY',
    order: 16,
    tags: ['npm', 'dependencies'],
    questionRu: 'В чём разница между dependencies, devDependencies и peerDependencies?',
    questionEn: 'What is the difference between dependencies, devDependencies, and peerDependencies?',
    answerRu: '- **`dependencies`**: нужны в runtime (`React`, `lodash`)\n- **`devDependencies`**: только для разработки (`Jest`, `ESLint`, `TypeScript`) — не попадают в production бандл\n- **`peerDependencies`**: ожидают что потребитель сам установит пакет (библиотека указывает совместимые версии `React`)\n- **`optionalDependencies`**: необязательные, не ломают установку при ошибке',
    answerEn: '- **`dependencies`**: required at runtime (`React`, `lodash`)\n- **`devDependencies`**: only needed during development (`Jest`, `ESLint`, `TypeScript`) — not included in the production bundle\n- **`peerDependencies`**: expect the consumer to install the package themselves (a library specifies compatible `React` versions)\n- **`optionalDependencies`**: optional, installation does not fail if they are missing',
  },
  {
    id: 'tools-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['monorepo', 'turborepo', 'nx'],
    questionRu: 'Что такое монорепозиторий и какие инструменты используются?',
    questionEn: 'What is a monorepo and what tools are used?',
    answerRu: '**Монорепозиторий** — несколько пакетов/приложений в одном git репозитории.\n\nПреимущества:\n- общий код\n- атомарные изменения\n- единые инструменты\n\nИнструменты:\n- **Turborepo** — кеширование и параллельный запуск задач\n- **Nx** — monorepo framework\n- `pnpm workspaces`\n- **Lerna**\n\nПодходит для Design System, микрофронтендов, shared утилит.',
    answerEn: 'A **monorepo** is multiple packages/applications in a single git repository.\n\nAdvantages:\n- shared code\n- atomic changes\n- unified tooling\n\nTools:\n- **Turborepo** — task caching and parallel execution\n- **Nx** — monorepo framework\n- `pnpm workspaces`\n- **Lerna**\n\nWell suited for Design Systems, micro-frontends, and shared utilities.',
  },
  {
    id: 'tools-018',
    difficulty: 'EASY',
    order: 18,
    tags: ['ci-cd', 'devops'],
    questionRu: 'Что такое CI/CD?',
    questionEn: 'What is CI/CD?',
    answerRu: '**CI** (Continuous Integration): автоматическая сборка и тестирование при каждом `push`/`PR` — раннее обнаружение ошибок.\n\n**CD** (Continuous Delivery): автоматический деплой в staging после прохождения CI.\n\n**Continuous Deployment**: автоматический деплой в production.\n\nИнструменты: **GitHub Actions**, **GitLab CI**, **CircleCI**, **Jenkins**.',
    answerEn: '**CI** (Continuous Integration): automated build and testing on every `push`/`PR` — enables early detection of errors.\n\n**CD** (Continuous Delivery): automatic deployment to staging after CI passes.\n\n**Continuous Deployment**: automatic deployment to production.\n\nTools: **GitHub Actions**, **GitLab CI**, **CircleCI**, **Jenkins**.',
  },
  {
    id: 'tools-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['github-actions', 'ci-cd'],
    questionRu: 'Что такое GitHub Actions и как устроен workflow?',
    questionEn: 'What is GitHub Actions and how is a workflow structured?',
    answerRu: '**GitHub Actions** — CI/CD, встроенный в GitHub.\n\nСтруктура workflow (`.github/workflows/*.yml`):\n- `on` — триггер (`push`, PR, `schedule`)\n- `jobs` — параллельные задачи\n- `steps` — последовательные шаги\n\nSteps используют **actions** (`actions/checkout`, `actions/setup-node`) или `run` (shell команды).\n\n- Секреты — через **Secrets**\n- Кеширование `node_modules` — через `actions/cache`',
    answerEn: '**GitHub Actions** is a CI/CD system built into GitHub.\n\nWorkflow structure (`.github/workflows/*.yml`):\n- `on` — trigger (`push`, PR, `schedule`)\n- `jobs` — parallel tasks\n- `steps` — sequential steps\n\nSteps use **actions** (`actions/checkout`, `actions/setup-node`) or `run` (shell commands).\n\n- Tokens are passed via **Secrets**\n- `node_modules` caching is done via `actions/cache`',
  },
  {
    id: 'tools-020',
    difficulty: 'MEDIUM',
    order: 20,
    tags: ['docker', 'devops'],
    questionRu: 'Что такое Docker и зачем фронтендеру?',
    questionEn: 'What is Docker and why does a frontend developer need it?',
    answerRu: '**Docker** — контейнеризация: приложение и его окружение упакованы в образ, работает одинаково везде.\n\n`Dockerfile` описывает сборку образа.\n\nДля фронтенда:\n- воспроизводимое окружение разработки\n- деплой `Next.js`/Node SSR приложений\n- локальный запуск backend сервисов через `docker-compose`\n\nЗнание базовых команд и `Dockerfile` — норма для **middle+**.',
    answerEn: '**Docker** is a containerization platform: an application and its environment are packaged into an image that runs the same way everywhere.\n\nA `Dockerfile` describes how to build the image.\n\nFor frontend developers:\n- reproducible dev environments\n- deploying `Next.js`/Node SSR apps\n- running backend services locally via `docker-compose`\n\nKnowledge of basic commands and `Dockerfile` is expected at **mid-level** and above.',
  },
  {
    id: 'tools-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['env', 'secrets', 'devops'],
    questionRu: 'Что такое переменные окружения и как безопасно с ними работать?',
    questionEn: 'What are environment variables and how do you work with them safely?',
    answerRu: '`.env` файлы для локальной разработки — в `.gitignore`.\n\nСекреты (API ключи, пароли) — только через CI/CD **Secrets** или **vault**.\n\nВ **Next.js**/**Vite**:\n- `NEXT_PUBLIC_` / `VITE_` — префикс для клиентских переменных (попадают в бандл — не хранить секреты)\n- Серверные переменные — без префикса\n\nКоммитить `.env.example` с заглушками в репозиторий.',
    answerEn: '`.env` files are for local development and should be in `.gitignore`.\n\nSecrets (API keys, passwords) should only be passed via CI/CD **Secrets** or a **vault**.\n\nIn **Next.js**/**Vite**:\n- `NEXT_PUBLIC_` / `VITE_` — prefix for client-side variables (they end up in the bundle — do not store secrets in them)\n- Server-side variables have no prefix\n\nCommit `.env.example` with placeholder values to the repository.',
  },
  {
    id: 'tools-022',
    difficulty: 'EASY',
    order: 22,
    tags: ['semver', 'versioning'],
    questionRu: 'Что такое semantic versioning (semver)?',
    questionEn: 'What is semantic versioning (semver)?',
    answerRu: '**Semver**: `MAJOR.MINOR.PATCH`\n\n- `PATCH` (`1.0.1`): обратно совместимые баг-фиксы\n- `MINOR` (`1.1.0`): новая функциональность, обратно совместимо\n- `MAJOR` (`2.0.0`): **breaking changes**\n\nВ npm:\n- `^` (caret) — обновлять `MINOR` и `PATCH`\n- `~` (tilde) — только `PATCH`\n- Точная версия — без символа\n\n`semantic-release` автоматизирует версионирование по **Conventional Commits**.',
    answerEn: '**Semver**: `MAJOR.MINOR.PATCH`\n\n- `PATCH` (`1.0.1`): backward-compatible bug fixes\n- `MINOR` (`1.1.0`): new functionality, backward-compatible\n- `MAJOR` (`2.0.0`): **breaking changes**\n\nIn npm:\n- `^` (caret) — allows `MINOR` and `PATCH` updates\n- `~` (tilde) — `PATCH` only\n- An exact version has no symbol\n\n`semantic-release` automates versioning based on **Conventional Commits**.',
  },
];
