import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'tools-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['bundler', 'webpack', 'vite'],
    questionRu: 'Что такое бандлер и зачем нужен?',
    questionEn: 'Что такое бандлер и зачем нужен?',
    answerRu: 'Бандлер собирает модули и зависимости в один или несколько файлов для браузера. Задачи: разрешение импортов, транспиляция (TS/JSX → JS), минификация, code splitting, tree shaking, обработка ассетов (CSS, изображения). Основные: Webpack, Vite, Rollup, Parcel, esbuild.',
    answerEn: 'Бандлер собирает модули и зависимости в один или несколько файлов для браузера. Задачи: разрешение импортов, транспиляция (TS/JSX → JS), минификация, code splitting, tree shaking, обработка ассетов (CSS, изображения). Основные: Webpack, Vite, Rollup, Parcel, esbuild.',
  },
  {
    id: 'tools-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['webpack', 'bundler'],
    questionRu: 'Как работает Webpack?',
    questionEn: 'Как работает Webpack?',
    answerRu: 'Webpack строит граф зависимостей начиная с entry point. Loaders трансформируют файлы (babel-loader для JS, css-loader для CSS). Plugins расширяют функциональность (HtmlWebpackPlugin, MiniCssExtractPlugin). Output — один или несколько бандлов. Mode: development (быстро) или production (оптимизация).',
    answerEn: 'Webpack строит граф зависимостей начиная с entry point. Loaders трансформируют файлы (babel-loader для JS, css-loader для CSS). Plugins расширяют функциональность (HtmlWebpackPlugin, MiniCssExtractPlugin). Output — один или несколько бандлов. Mode: development (быстро) или production (оптимизация).',
  },
  {
    id: 'tools-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['vite', 'webpack', 'bundler'],
    questionRu: 'Чем Vite отличается от Webpack?',
    questionEn: 'Чем Vite отличается от Webpack?',
    answerRu: 'Vite в dev режиме: не бандлит — отдаёт ES модули напрямую браузеру, трансформирует файлы по запросу через esbuild. Старт мгновенный независимо от размера проекта. HMR быстрее. Production: Rollup под капотом. Webpack: всё бандлит при старте — медленнее для больших проектов. Vite предпочтителен для новых проектов.',
    answerEn: 'Vite в dev режиме: не бандлит — отдаёт ES модули напрямую браузеру, трансформирует файлы по запросу через esbuild. Старт мгновенный независимо от размера проекта. HMR быстрее. Production: Rollup под капотом. Webpack: всё бандлит при старте — медленнее для больших проектов. Vite предпочтителен для новых проектов.',
  },
  {
    id: 'tools-004',
    difficulty: 'EASY',
    order: 4,
    tags: ['hmr', 'vite', 'webpack'],
    questionRu: 'Что такое HMR (Hot Module Replacement)?',
    questionEn: 'Что такое HMR (Hot Module Replacement)?',
    answerRu: 'HMR — замена модулей в браузере без полной перезагрузки страницы. При изменении файла только изменённый модуль заменяется, состояние приложения сохраняется. Vite и Webpack поддерживают HMR. React Fast Refresh — HMR для React компонентов с сохранением state. Значительно ускоряет разработку.',
    answerEn: 'HMR — замена модулей в браузере без полной перезагрузки страницы. При изменении файла только изменённый модуль заменяется, состояние приложения сохраняется. Vite и Webpack поддерживают HMR. React Fast Refresh — HMR для React компонентов с сохранением state. Значительно ускоряет разработку.',
  },
  {
    id: 'tools-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['source-maps', 'debugging'],
    questionRu: 'Что такое source maps?',
    questionEn: 'Что такое source maps?',
    answerRu: 'Source maps — файлы (.map) маппящие минифицированный/транспилированный код обратно к исходному. Браузер автоматически использует их в DevTools — видишь оригинальный TypeScript/JSX вместо бандла. В production: отдельные .map файлы (не включать в бандл). hidden-source-map — для Sentry без публичного доступа.',
    answerEn: 'Source maps — файлы (.map) маппящие минифицированный/транспилированный код обратно к исходному. Браузер автоматически использует их в DevTools — видишь оригинальный TypeScript/JSX вместо бандла. В production: отдельные .map файлы (не включать в бандл). hidden-source-map — для Sentry без публичного доступа.',
  },
  {
    id: 'tools-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['babel', 'transpiler'],
    questionRu: 'Что такое Babel и для чего используется?',
    questionEn: 'Что такое Babel и для чего используется?',
    answerRu: 'Babel — транспилятор JS: преобразует современный JS (ES2022+, JSX, TypeScript) в совместимый со старыми браузерами. Плагины трансформируют конкретные фичи. Presets — набор плагинов: @babel/preset-env (по browserslist), @babel/preset-react, @babel/preset-typescript. Сейчас часто заменяется esbuild/SWC для скорости.',
    answerEn: 'Babel — транспилятор JS: преобразует современный JS (ES2022+, JSX, TypeScript) в совместимый со старыми браузерами. Плагины трансформируют конкретные фичи. Presets — набор плагинов: @babel/preset-env (по browserslist), @babel/preset-react, @babel/preset-typescript. Сейчас часто заменяется esbuild/SWC для скорости.',
  },
  {
    id: 'tools-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['eslint', 'prettier', 'linting'],
    questionRu: 'Что такое ESLint и Prettier и в чём разница?',
    questionEn: 'Что такое ESLint и Prettier и в чём разница?',
    answerRu: 'ESLint — линтер: анализирует код на ошибки и антипаттерны, применяет правила (no-unused-vars, react-hooks/rules-of-hooks). Может автофиксить. Prettier — форматтер: единый стиль кода (отступы, кавычки, точки с запятой). Не анализирует логику. Используются вместе: ESLint для качества, Prettier для форматирования.',
    answerEn: 'ESLint — линтер: анализирует код на ошибки и антипаттерны, применяет правила (no-unused-vars, react-hooks/rules-of-hooks). Может автофиксить. Prettier — форматтер: единый стиль кода (отступы, кавычки, точки с запятой). Не анализирует логику. Используются вместе: ESLint для качества, Prettier для форматирования.',
  },
  {
    id: 'tools-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['git', 'merge', 'rebase'],
    questionRu: 'В чём разница между merge и rebase?',
    questionEn: 'В чём разница между merge и rebase?',
    answerRu: 'Merge: объединяет ветки, создаёт merge commit, сохраняет историю ветвлений. История нелинейная. Rebase: переносит коммиты поверх другой ветки — линейная история. Не использовать rebase на публичных ветках (изменяет SHA коммитов). Merge для публичных веток, rebase для локальной очистки истории.',
    answerEn: 'Merge: объединяет ветки, создаёт merge commit, сохраняет историю ветвлений. История нелинейная. Rebase: переносит коммиты поверх другой ветки — линейная история. Не использовать rebase на публичных ветках (изменяет SHA коммитов). Merge для публичных веток, rebase для локальной очистки истории.',
  },
  {
    id: 'tools-009',
    difficulty: 'EASY',
    order: 9,
    tags: ['git', 'stash'],
    questionRu: 'Что такое git stash?',
    questionEn: 'Что такое git stash?',
    answerRu: 'git stash сохраняет незакоммиченные изменения во временное хранилище и возвращает рабочую директорию к HEAD. Полезно для переключения веток без коммита. git stash pop — восстановить и удалить из стека. git stash apply — восстановить, оставить в стеке. git stash list — все сохранённые изменения.',
    answerEn: 'git stash сохраняет незакоммиченные изменения во временное хранилище и возвращает рабочую директорию к HEAD. Полезно для переключения веток без коммита. git stash pop — восстановить и удалить из стека. git stash apply — восстановить, оставить в стеке. git stash list — все сохранённые изменения.',
  },
  {
    id: 'tools-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['git', 'rebase', 'history'],
    questionRu: 'Что такое git rebase -i (interactive rebase)?',
    questionEn: 'Что такое git rebase -i (interactive rebase)?',
    answerRu: 'Interactive rebase позволяет редактировать историю коммитов: squash (объединить в один), reword (переименовать), edit (изменить), drop (удалить), reorder. Использовать для очистки истории feature-ветки перед merge. Не применять к коммитам которые уже запушены и используются другими.',
    answerEn: 'Interactive rebase позволяет редактировать историю коммитов: squash (объединить в один), reword (переименовать), edit (изменить), drop (удалить), reorder. Использовать для очистки истории feature-ветки перед merge. Не применять к коммитам которые уже запушены и используются другими.',
  },
  {
    id: 'tools-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['git', 'cherry-pick'],
    questionRu: 'Что такое git cherry-pick?',
    questionEn: 'Что такое git cherry-pick?',
    answerRu: 'git cherry-pick <commit-hash> применяет конкретный коммит из другой ветки к текущей. Полезно для: переноса hotfix из main в release ветку, взятия одного коммита без merge всей ветки. Создаёт новый коммит с тем же изменением но другим SHA. Конфликты разрешаются вручную.',
    answerEn: 'git cherry-pick <commit-hash> применяет конкретный коммит из другой ветки к текущей. Полезно для: переноса hotfix из main в release ветку, взятия одного коммита без merge всей ветки. Создаёт новый коммит с тем же изменением но другим SHA. Конфликты разрешаются вручную.',
  },
  {
    id: 'tools-012',
    difficulty: 'HARD',
    order: 12,
    tags: ['git', 'bisect', 'debugging'],
    questionRu: 'Что такое git bisect?',
    questionEn: 'Что такое git bisect?',
    answerRu: 'git bisect — бинарный поиск коммита, введшего баг. git bisect start → git bisect bad (текущий) → git bisect good <hash> → Git переключает на середину → помечаешь good/bad → повторять. За O(log n) шагов находит проблемный коммит. Можно автоматизировать через скрипт: git bisect run npm test.',
    answerEn: 'git bisect — бинарный поиск коммита, введшего баг. git bisect start → git bisect bad (текущий) → git bisect good <hash> → Git переключает на середину → помечаешь good/bad → повторять. За O(log n) шагов находит проблемный коммит. Можно автоматизировать через скрипт: git bisect run npm test.',
  },
  {
    id: 'tools-013',
    difficulty: 'EASY',
    order: 13,
    tags: ['git', 'conventional-commits'],
    questionRu: 'Что такое Conventional Commits?',
    questionEn: 'Что такое Conventional Commits?',
    answerRu: 'Conventional Commits — соглашение о формате коммитов: type(scope): description. Типы: feat (новая фича), fix (баг), docs, style, refactor, test, chore. Позволяет: автогенерацию CHANGELOG, автоматическое управление версиями (semantic-release), понятную историю. Инструменты: commitlint, commitizen.',
    answerEn: 'Conventional Commits — соглашение о формате коммитов: type(scope): description. Типы: feat (новая фича), fix (баг), docs, style, refactor, test, chore. Позволяет: автогенерацию CHANGELOG, автоматическое управление версиями (semantic-release), понятную историю. Инструменты: commitlint, commitizen.',
  },
  {
    id: 'tools-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['npm', 'yarn', 'pnpm', 'package-manager'],
    questionRu: 'В чём разница между npm, yarn и pnpm?',
    questionEn: 'В чём разница между npm, yarn и pnpm?',
    answerRu: 'npm: стандартный, медленнее. yarn (classic): параллельная установка, yarn.lock. yarn berry: PnP без node_modules. pnpm: content-addressable store — пакеты не дублируются между проектами, жёсткие ссылки, строгий доступ к зависимостям. pnpm быстрее и экономит дисковое место. В монорепозиториях pnpm workspaces предпочтителен.',
    answerEn: 'npm: стандартный, медленнее. yarn (classic): параллельная установка, yarn.lock. yarn berry: PnP без node_modules. pnpm: content-addressable store — пакеты не дублируются между проектами, жёсткие ссылки, строгий доступ к зависимостям. pnpm быстрее и экономит дисковое место. В монорепозиториях pnpm workspaces предпочтителен.',
  },
  {
    id: 'tools-015',
    difficulty: 'EASY',
    order: 15,
    tags: ['npm', 'lock-file', 'reproducibility'],
    questionRu: 'Что такое lock-файл и зачем нужен?',
    questionEn: 'Что такое lock-файл и зачем нужен?',
    answerRu: 'Lock-файл (package-lock.json, yarn.lock, pnpm-lock.yaml) фиксирует точные версии всех зависимостей включая транзитивные. Обеспечивает воспроизводимые сборки — npm install даёт одинаковый результат на всех машинах. Всегда коммитить в репозиторий. npm ci для production — устанавливает строго по lock-файлу.',
    answerEn: 'Lock-файл (package-lock.json, yarn.lock, pnpm-lock.yaml) фиксирует точные версии всех зависимостей включая транзитивные. Обеспечивает воспроизводимые сборки — npm install даёт одинаковый результат на всех машинах. Всегда коммитить в репозиторий. npm ci для production — устанавливает строго по lock-файлу.',
  },
  {
    id: 'tools-016',
    difficulty: 'EASY',
    order: 16,
    tags: ['npm', 'dependencies'],
    questionRu: 'В чём разница между dependencies, devDependencies и peerDependencies?',
    questionEn: 'В чём разница между dependencies, devDependencies и peerDependencies?',
    answerRu: 'dependencies: нужны в runtime (React, lodash). devDependencies: только для разработки (Jest, ESLint, TypeScript) — не попадают в production бандл. peerDependencies: ожидают что потребитель сам установит пакет (библиотека указывает совместимые версии React). optionalDependencies: необязательные, не ломают установку при ошибке.',
    answerEn: 'dependencies: нужны в runtime (React, lodash). devDependencies: только для разработки (Jest, ESLint, TypeScript) — не попадают в production бандл. peerDependencies: ожидают что потребитель сам установит пакет (библиотека указывает совместимые версии React). optionalDependencies: необязательные, не ломают установку при ошибке.',
  },
  {
    id: 'tools-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['monorepo', 'turborepo', 'nx'],
    questionRu: 'Что такое монорепозиторий и какие инструменты используются?',
    questionEn: 'Что такое монорепозиторий и какие инструменты используются?',
    answerRu: 'Монорепозиторий — несколько пакетов/приложений в одном git репозитории. Преимущества: общий код, атомарные изменения, единые инструменты. Инструменты: Turborepo (кеширование и параллельный запуск задач), Nx (monorepo framework), pnpm workspaces, Lerna. Подходит для Design System, микрофронтендов, shared утилит.',
    answerEn: 'Монорепозиторий — несколько пакетов/приложений в одном git репозитории. Преимущества: общий код, атомарные изменения, единые инструменты. Инструменты: Turborepo (кеширование и параллельный запуск задач), Nx (monorepo framework), pnpm workspaces, Lerna. Подходит для Design System, микрофронтендов, shared утилит.',
  },
  {
    id: 'tools-018',
    difficulty: 'EASY',
    order: 18,
    tags: ['ci-cd', 'devops'],
    questionRu: 'Что такое CI/CD?',
    questionEn: 'Что такое CI/CD?',
    answerRu: 'CI (Continuous Integration): автоматическая сборка и тестирование при каждом push/PR — раннее обнаружение ошибок. CD (Continuous Delivery): автоматический деплой в staging после прохождения CI. Continuous Deployment: автоматический деплой в production. Инструменты: GitHub Actions, GitLab CI, CircleCI, Jenkins.',
    answerEn: 'CI (Continuous Integration): автоматическая сборка и тестирование при каждом push/PR — раннее обнаружение ошибок. CD (Continuous Delivery): автоматический деплой в staging после прохождения CI. Continuous Deployment: автоматический деплой в production. Инструменты: GitHub Actions, GitLab CI, CircleCI, Jenkins.',
  },
  {
    id: 'tools-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['github-actions', 'ci-cd'],
    questionRu: 'Что такое GitHub Actions и как устроен workflow?',
    questionEn: 'Что такое GitHub Actions и как устроен workflow?',
    answerRu: 'GitHub Actions — CI/CD встроенный в GitHub. Workflow (.github/workflows/*.yml): on (trigger: push, PR, schedule) → jobs (параллельные задачи) → steps (последовательные шаги). Steps используют actions (actions/checkout, actions/setup-node) или run (shell команды). Secrets для токенов. Кеширование node_modules через actions/cache.',
    answerEn: 'GitHub Actions — CI/CD встроенный в GitHub. Workflow (.github/workflows/*.yml): on (trigger: push, PR, schedule) → jobs (параллельные задачи) → steps (последовательные шаги). Steps используют actions (actions/checkout, actions/setup-node) или run (shell команды). Secrets для токенов. Кеширование node_modules через actions/cache.',
  },
  {
    id: 'tools-020',
    difficulty: 'MEDIUM',
    order: 20,
    tags: ['docker', 'devops'],
    questionRu: 'Что такое Docker и зачем фронтендеру?',
    questionEn: 'Что такое Docker и зачем фронтендеру?',
    answerRu: 'Docker — контейнеризация: приложение и его окружение упакованы в образ, работает одинаково везде. Dockerfile описывает сборку образа. Для фронтенда: воспроизводимое окружение разработки, деплой Next.js/Node SSR приложений, локальный запуск backend сервисов через docker-compose. Знание базовых команд и Dockerfile — норма для middle+.',
    answerEn: 'Docker — контейнеризация: приложение и его окружение упакованы в образ, работает одинаково везде. Dockerfile описывает сборку образа. Для фронтенда: воспроизводимое окружение разработки, деплой Next.js/Node SSR приложений, локальный запуск backend сервисов через docker-compose. Знание базовых команд и Dockerfile — норма для middle+.',
  },
  {
    id: 'tools-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['env', 'secrets', 'devops'],
    questionRu: 'Что такое переменные окружения и как безопасно с ними работать?',
    questionEn: 'Что такое переменные окружения и как безопасно с ними работать?',
    answerRu: '.env файлы для локальной разработки — в .gitignore. Секреты (API ключи, пароли) только через CI/CD secrets или vault. В Next.js/Vite: NEXT_PUBLIC_/VITE_ префикс для клиентских переменных (попадают в бандл — не хранить секреты). Серверные переменные без префикса. .env.example с заглушками коммитить в репозиторий.',
    answerEn: '.env файлы для локальной разработки — в .gitignore. Секреты (API ключи, пароли) только через CI/CD secrets или vault. В Next.js/Vite: NEXT_PUBLIC_/VITE_ префикс для клиентских переменных (попадают в бандл — не хранить секреты). Серверные переменные без префикса. .env.example с заглушками коммитить в репозиторий.',
  },
  {
    id: 'tools-022',
    difficulty: 'EASY',
    order: 22,
    tags: ['semver', 'versioning'],
    questionRu: 'Что такое semantic versioning (semver)?',
    questionEn: 'Что такое semantic versioning (semver)?',
    answerRu: 'Semver: MAJOR.MINOR.PATCH. PATCH (1.0.1): обратно совместимые баг-фиксы. MINOR (1.1.0): новая функциональность, обратно совместимо. MAJOR (2.0.0): breaking changes. В npm: ^ (caret) — обновлять MINOR и PATCH. ~ (tilde) — только PATCH. Точная версия без символа. semantic-release автоматизирует версионирование по Conventional Commits.',
    answerEn: 'Semver: MAJOR.MINOR.PATCH. PATCH (1.0.1): обратно совместимые баг-фиксы. MINOR (1.1.0): новая функциональность, обратно совместимо. MAJOR (2.0.0): breaking changes. В npm: ^ (caret) — обновлять MINOR и PATCH. ~ (tilde) — только PATCH. Точная версия без символа. semantic-release автоматизирует версионирование по Conventional Commits.',
  },
];
