import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'tools-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['bundler', 'webpack', 'vite'],
    questionRu: 'Что такое бандлер и зачем нужен?',
    questionEn: 'What is a bundler and why is it needed?',
    answerRu: 'Бандлер собирает модули и зависимости в один или несколько файлов для браузера. Задачи: разрешение импортов, транспиляция (TS/JSX → JS), минификация, code splitting, tree shaking, обработка ассетов (CSS, изображения). Основные: Webpack, Vite, Rollup, Parcel, esbuild.',
    answerEn: 'A bundler assembles modules and dependencies into one or more files for the browser. Responsibilities: resolving imports, transpilation (TS/JSX → JS), minification, code splitting, tree shaking, asset handling (CSS, images). Main bundlers: Webpack, Vite, Rollup, Parcel, esbuild.',
  },
  {
    id: 'tools-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['webpack', 'bundler'],
    questionRu: 'Как работает Webpack?',
    questionEn: 'How does Webpack work?',
    answerRu: 'Webpack строит граф зависимостей начиная с entry point. Loaders трансформируют файлы (babel-loader для JS, css-loader для CSS). Plugins расширяют функциональность (HtmlWebpackPlugin, MiniCssExtractPlugin). Output — один или несколько бандлов. Mode: development (быстро) или production (оптимизация).',
    answerEn: 'Webpack builds a dependency graph starting from the entry point. Loaders transform files (babel-loader for JS, css-loader for CSS). Plugins extend functionality (HtmlWebpackPlugin, MiniCssExtractPlugin). Output is one or more bundles. Mode: development (fast) or production (optimized).',
  },
  {
    id: 'tools-003',
    difficulty: 'MEDIUM',
    order: 3,
    tags: ['vite', 'webpack', 'bundler'],
    questionRu: 'Чем Vite отличается от Webpack?',
    questionEn: 'How does Vite differ from Webpack?',
    answerRu: 'Vite в dev режиме: не бандлит — отдаёт ES модули напрямую браузеру, трансформирует файлы по запросу через esbuild. Старт мгновенный независимо от размера проекта. HMR быстрее. Production: Rollup под капотом. Webpack: всё бандлит при старте — медленнее для больших проектов. Vite предпочтителен для новых проектов.',
    answerEn: 'In dev mode, Vite does not bundle — it serves ES modules directly to the browser and transforms files on demand via esbuild. Startup is instant regardless of project size. HMR is faster. Production: Rollup under the hood. Webpack bundles everything at startup — slower for large projects. Vite is preferred for new projects.',
  },
  {
    id: 'tools-004',
    difficulty: 'EASY',
    order: 4,
    tags: ['hmr', 'vite', 'webpack'],
    questionRu: 'Что такое HMR (Hot Module Replacement)?',
    questionEn: 'What is HMR (Hot Module Replacement)?',
    answerRu: 'HMR — замена модулей в браузере без полной перезагрузки страницы. При изменении файла только изменённый модуль заменяется, состояние приложения сохраняется. Vite и Webpack поддерживают HMR. React Fast Refresh — HMR для React компонентов с сохранением state. Значительно ускоряет разработку.',
    answerEn: 'HMR replaces modules in the browser without a full page reload. When a file changes, only the changed module is replaced and the application state is preserved. Vite and Webpack both support HMR. React Fast Refresh is HMR for React components with state preservation. It significantly speeds up development.',
  },
  {
    id: 'tools-005',
    difficulty: 'MEDIUM',
    order: 5,
    tags: ['source-maps', 'debugging'],
    questionRu: 'Что такое source maps?',
    questionEn: 'What are source maps?',
    answerRu: 'Source maps — файлы (.map) маппящие минифицированный/транспилированный код обратно к исходному. Браузер автоматически использует их в DevTools — видишь оригинальный TypeScript/JSX вместо бандла. В production: отдельные .map файлы (не включать в бандл). hidden-source-map — для Sentry без публичного доступа.',
    answerEn: 'Source maps are .map files that map minified/transpiled code back to the original source. The browser automatically uses them in DevTools — you see the original TypeScript/JSX instead of the bundle. In production: use separate .map files (do not include them in the bundle). hidden-source-map — for Sentry without public access.',
  },
  {
    id: 'tools-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['babel', 'transpiler'],
    questionRu: 'Что такое Babel и для чего используется?',
    questionEn: 'What is Babel and what is it used for?',
    answerRu: 'Babel — транспилятор JS: преобразует современный JS (ES2022+, JSX, TypeScript) в совместимый со старыми браузерами. Плагины трансформируют конкретные фичи. Presets — набор плагинов: @babel/preset-env (по browserslist), @babel/preset-react, @babel/preset-typescript. Сейчас часто заменяется esbuild/SWC для скорости.',
    answerEn: 'Babel is a JS transpiler that converts modern JS (ES2022+, JSX, TypeScript) into code compatible with older browsers. Plugins transform specific features. Presets are collections of plugins: @babel/preset-env (based on browserslist), @babel/preset-react, @babel/preset-typescript. It is now often replaced by esbuild/SWC for performance.',
  },
  {
    id: 'tools-007',
    difficulty: 'EASY',
    order: 7,
    tags: ['eslint', 'prettier', 'linting'],
    questionRu: 'Что такое ESLint и Prettier и в чём разница?',
    questionEn: 'What are ESLint and Prettier, and what is the difference between them?',
    answerRu: 'ESLint — линтер: анализирует код на ошибки и антипаттерны, применяет правила (no-unused-vars, react-hooks/rules-of-hooks). Может автофиксить. Prettier — форматтер: единый стиль кода (отступы, кавычки, точки с запятой). Не анализирует логику. Используются вместе: ESLint для качества, Prettier для форматирования.',
    answerEn: 'ESLint is a linter: it analyzes code for errors and anti-patterns, enforces rules (no-unused-vars, react-hooks/rules-of-hooks), and can auto-fix issues. Prettier is a formatter: it enforces a consistent code style (indentation, quotes, semicolons) and does not analyze logic. They are used together: ESLint for code quality, Prettier for formatting.',
  },
  {
    id: 'tools-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['git', 'merge', 'rebase'],
    questionRu: 'В чём разница между merge и rebase?',
    questionEn: 'What is the difference between merge and rebase?',
    answerRu: 'Merge: объединяет ветки, создаёт merge commit, сохраняет историю ветвлений. История нелинейная. Rebase: переносит коммиты поверх другой ветки — линейная история. Не использовать rebase на публичных ветках (изменяет SHA коммитов). Merge для публичных веток, rebase для локальной очистки истории.',
    answerEn: 'Merge: combines branches, creates a merge commit, preserves branching history. History is non-linear. Rebase: replays commits on top of another branch — produces a linear history. Do not rebase public branches (it rewrites commit SHAs). Use merge for public branches, rebase for cleaning up local history.',
  },
  {
    id: 'tools-009',
    difficulty: 'EASY',
    order: 9,
    tags: ['git', 'stash'],
    questionRu: 'Что такое git stash?',
    questionEn: 'What is git stash?',
    answerRu: 'git stash сохраняет незакоммиченные изменения во временное хранилище и возвращает рабочую директорию к HEAD. Полезно для переключения веток без коммита. git stash pop — восстановить и удалить из стека. git stash apply — восстановить, оставить в стеке. git stash list — все сохранённые изменения.',
    answerEn: 'git stash saves uncommitted changes to a temporary storage area and restores the working directory to HEAD. Useful for switching branches without committing. git stash pop — restore and remove from the stack. git stash apply — restore and keep in the stack. git stash list — list all stashed changes.',
  },
  {
    id: 'tools-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['git', 'rebase', 'history'],
    questionRu: 'Что такое git rebase -i (interactive rebase)?',
    questionEn: 'What is git rebase -i (interactive rebase)?',
    answerRu: 'Interactive rebase позволяет редактировать историю коммитов: squash (объединить в один), reword (переименовать), edit (изменить), drop (удалить), reorder. Использовать для очистки истории feature-ветки перед merge. Не применять к коммитам которые уже запушены и используются другими.',
    answerEn: 'Interactive rebase lets you edit commit history: squash (combine into one), reword (rename), edit (modify), drop (delete), reorder. Use it to clean up a feature branch history before merging. Do not apply it to commits that have already been pushed and are used by others.',
  },
  {
    id: 'tools-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['git', 'cherry-pick'],
    questionRu: 'Что такое git cherry-pick?',
    questionEn: 'What is git cherry-pick?',
    answerRu: 'git cherry-pick <commit-hash> применяет конкретный коммит из другой ветки к текущей. Полезно для: переноса hotfix из main в release ветку, взятия одного коммита без merge всей ветки. Создаёт новый коммит с тем же изменением но другим SHA. Конфликты разрешаются вручную.',
    answerEn: 'git cherry-pick <commit-hash> applies a specific commit from another branch to the current branch. Useful for: porting a hotfix from main to a release branch, taking a single commit without merging the entire branch. It creates a new commit with the same change but a different SHA. Conflicts must be resolved manually.',
  },
  {
    id: 'tools-012',
    difficulty: 'HARD',
    order: 12,
    tags: ['git', 'bisect', 'debugging'],
    questionRu: 'Что такое git bisect?',
    questionEn: 'What is git bisect?',
    answerRu: 'git bisect — бинарный поиск коммита, введшего баг. git bisect start → git bisect bad (текущий) → git bisect good <hash> → Git переключает на середину → помечаешь good/bad → повторять. За O(log n) шагов находит проблемный коммит. Можно автоматизировать через скрипт: git bisect run npm test.',
    answerEn: 'git bisect performs a binary search to find the commit that introduced a bug. git bisect start → git bisect bad (current) → git bisect good <hash> → Git checks out the midpoint → mark good/bad → repeat. Finds the offending commit in O(log n) steps. Can be automated with a script: git bisect run npm test.',
  },
  {
    id: 'tools-013',
    difficulty: 'EASY',
    order: 13,
    tags: ['git', 'conventional-commits'],
    questionRu: 'Что такое Conventional Commits?',
    questionEn: 'What are Conventional Commits?',
    answerRu: 'Conventional Commits — соглашение о формате коммитов: type(scope): description. Типы: feat (новая фича), fix (баг), docs, style, refactor, test, chore. Позволяет: автогенерацию CHANGELOG, автоматическое управление версиями (semantic-release), понятную историю. Инструменты: commitlint, commitizen.',
    answerEn: 'Conventional Commits is a convention for commit message formatting: type(scope): description. Types: feat (new feature), fix (bug fix), docs, style, refactor, test, chore. Enables: automatic CHANGELOG generation, automated versioning (semantic-release), and a readable history. Tools: commitlint, commitizen.',
  },
  {
    id: 'tools-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['npm', 'yarn', 'pnpm', 'package-manager'],
    questionRu: 'В чём разница между npm, yarn и pnpm?',
    questionEn: 'What is the difference between npm, yarn, and pnpm?',
    answerRu: 'npm: стандартный, медленнее. yarn (classic): параллельная установка, yarn.lock. yarn berry: PnP без node_modules. pnpm: content-addressable store — пакеты не дублируются между проектами, жёсткие ссылки, строгий доступ к зависимостям. pnpm быстрее и экономит дисковое место. В монорепозиториях pnpm workspaces предпочтителен.',
    answerEn: 'npm: the standard package manager, relatively slow. yarn (classic): parallel installation, yarn.lock. yarn berry: Plug\'n\'Play without node_modules. pnpm: content-addressable store — packages are not duplicated across projects, uses hard links, strict dependency access. pnpm is faster and saves disk space. pnpm workspaces is preferred for monorepos.',
  },
  {
    id: 'tools-015',
    difficulty: 'EASY',
    order: 15,
    tags: ['npm', 'lock-file', 'reproducibility'],
    questionRu: 'Что такое lock-файл и зачем нужен?',
    questionEn: 'What is a lock file and why is it needed?',
    answerRu: 'Lock-файл (package-lock.json, yarn.lock, pnpm-lock.yaml) фиксирует точные версии всех зависимостей включая транзитивные. Обеспечивает воспроизводимые сборки — npm install даёт одинаковый результат на всех машинах. Всегда коммитить в репозиторий. npm ci для production — устанавливает строго по lock-файлу.',
    answerEn: 'A lock file (package-lock.json, yarn.lock, pnpm-lock.yaml) pins the exact versions of all dependencies including transitive ones. It ensures reproducible builds — npm install produces the same result on every machine. Always commit it to the repository. Use npm ci for production — it installs strictly according to the lock file.',
  },
  {
    id: 'tools-016',
    difficulty: 'EASY',
    order: 16,
    tags: ['npm', 'dependencies'],
    questionRu: 'В чём разница между dependencies, devDependencies и peerDependencies?',
    questionEn: 'What is the difference between dependencies, devDependencies, and peerDependencies?',
    answerRu: 'dependencies: нужны в runtime (React, lodash). devDependencies: только для разработки (Jest, ESLint, TypeScript) — не попадают в production бандл. peerDependencies: ожидают что потребитель сам установит пакет (библиотека указывает совместимые версии React). optionalDependencies: необязательные, не ломают установку при ошибке.',
    answerEn: 'dependencies: required at runtime (React, lodash). devDependencies: only needed during development (Jest, ESLint, TypeScript) — not included in the production bundle. peerDependencies: expect the consumer to install the package themselves (a library specifies compatible React versions). optionalDependencies: optional, installation does not fail if they are missing.',
  },
  {
    id: 'tools-017',
    difficulty: 'MEDIUM',
    order: 17,
    tags: ['monorepo', 'turborepo', 'nx'],
    questionRu: 'Что такое монорепозиторий и какие инструменты используются?',
    questionEn: 'What is a monorepo and what tools are used?',
    answerRu: 'Монорепозиторий — несколько пакетов/приложений в одном git репозитории. Преимущества: общий код, атомарные изменения, единые инструменты. Инструменты: Turborepo (кеширование и параллельный запуск задач), Nx (monorepo framework), pnpm workspaces, Lerna. Подходит для Design System, микрофронтендов, shared утилит.',
    answerEn: 'A monorepo is multiple packages/applications in a single git repository. Advantages: shared code, atomic changes, unified tooling. Tools: Turborepo (task caching and parallel execution), Nx (monorepo framework), pnpm workspaces, Lerna. Well suited for Design Systems, micro-frontends, and shared utilities.',
  },
  {
    id: 'tools-018',
    difficulty: 'EASY',
    order: 18,
    tags: ['ci-cd', 'devops'],
    questionRu: 'Что такое CI/CD?',
    questionEn: 'What is CI/CD?',
    answerRu: 'CI (Continuous Integration): автоматическая сборка и тестирование при каждом push/PR — раннее обнаружение ошибок. CD (Continuous Delivery): автоматический деплой в staging после прохождения CI. Continuous Deployment: автоматический деплой в production. Инструменты: GitHub Actions, GitLab CI, CircleCI, Jenkins.',
    answerEn: 'CI (Continuous Integration): automated build and testing on every push/PR — enables early detection of errors. CD (Continuous Delivery): automatic deployment to staging after CI passes. Continuous Deployment: automatic deployment to production. Tools: GitHub Actions, GitLab CI, CircleCI, Jenkins.',
  },
  {
    id: 'tools-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['github-actions', 'ci-cd'],
    questionRu: 'Что такое GitHub Actions и как устроен workflow?',
    questionEn: 'What is GitHub Actions and how is a workflow structured?',
    answerRu: 'GitHub Actions — CI/CD встроенный в GitHub. Workflow (.github/workflows/*.yml): on (trigger: push, PR, schedule) → jobs (параллельные задачи) → steps (последовательные шаги). Steps используют actions (actions/checkout, actions/setup-node) или run (shell команды). Secrets для токенов. Кеширование node_modules через actions/cache.',
    answerEn: 'GitHub Actions is a CI/CD system built into GitHub. A workflow (.github/workflows/*.yml): on (trigger: push, PR, schedule) → jobs (parallel tasks) → steps (sequential steps). Steps use actions (actions/checkout, actions/setup-node) or run (shell commands). Secrets are used for tokens. node_modules caching is done via actions/cache.',
  },
  {
    id: 'tools-020',
    difficulty: 'MEDIUM',
    order: 20,
    tags: ['docker', 'devops'],
    questionRu: 'Что такое Docker и зачем фронтендеру?',
    questionEn: 'What is Docker and why does a frontend developer need it?',
    answerRu: 'Docker — контейнеризация: приложение и его окружение упакованы в образ, работает одинаково везде. Dockerfile описывает сборку образа. Для фронтенда: воспроизводимое окружение разработки, деплой Next.js/Node SSR приложений, локальный запуск backend сервисов через docker-compose. Знание базовых команд и Dockerfile — норма для middle+.',
    answerEn: 'Docker is a containerization platform: an application and its environment are packaged into an image that runs the same way everywhere. A Dockerfile describes how to build the image. For frontend developers: reproducible dev environments, deploying Next.js/Node SSR apps, running backend services locally via docker-compose. Knowledge of basic commands and Dockerfile is expected at mid-level and above.',
  },
  {
    id: 'tools-021',
    difficulty: 'MEDIUM',
    order: 21,
    tags: ['env', 'secrets', 'devops'],
    questionRu: 'Что такое переменные окружения и как безопасно с ними работать?',
    questionEn: 'What are environment variables and how do you work with them safely?',
    answerRu: '.env файлы для локальной разработки — в .gitignore. Секреты (API ключи, пароли) только через CI/CD secrets или vault. В Next.js/Vite: NEXT_PUBLIC_/VITE_ префикс для клиентских переменных (попадают в бандл — не хранить секреты). Серверные переменные без префикса. .env.example с заглушками коммитить в репозиторий.',
    answerEn: '.env files are for local development and should be in .gitignore. Secrets (API keys, passwords) should only be passed via CI/CD secrets or a vault. In Next.js/Vite: NEXT_PUBLIC_/VITE_ prefix for client-side variables (they end up in the bundle — do not store secrets in them). Server-side variables have no prefix. Commit .env.example with placeholder values to the repository.',
  },
  {
    id: 'tools-022',
    difficulty: 'EASY',
    order: 22,
    tags: ['semver', 'versioning'],
    questionRu: 'Что такое semantic versioning (semver)?',
    questionEn: 'What is semantic versioning (semver)?',
    answerRu: 'Semver: MAJOR.MINOR.PATCH. PATCH (1.0.1): обратно совместимые баг-фиксы. MINOR (1.1.0): новая функциональность, обратно совместимо. MAJOR (2.0.0): breaking changes. В npm: ^ (caret) — обновлять MINOR и PATCH. ~ (tilde) — только PATCH. Точная версия без символа. semantic-release автоматизирует версионирование по Conventional Commits.',
    answerEn: 'Semver: MAJOR.MINOR.PATCH. PATCH (1.0.1): backward-compatible bug fixes. MINOR (1.1.0): new functionality, backward-compatible. MAJOR (2.0.0): breaking changes. In npm: ^ (caret) — allows MINOR and PATCH updates. ~ (tilde) — PATCH only. An exact version has no symbol. semantic-release automates versioning based on Conventional Commits.',
  },
];
