import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'ts-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['basics'],
    questionRu: 'Чем TypeScript отличается от JavaScript?',
    questionEn: 'How is TypeScript different from JavaScript?',
    answerRu: '**TypeScript** — надмножество JavaScript со **статической типизацией**. Компилируется в JS.\n\nПреимущества:\n- раннее обнаружение ошибок\n- автодополнение в IDE\n- самодокументируемый код\n\nВсе JS-программы валидны в TS, но не наоборот.',
    answerEn: '**TypeScript** is a **statically typed** superset of JavaScript that compiles to JS.\n\nBenefits:\n- early error detection\n- IDE autocompletion\n- self-documenting code\n\nAll JS programs are valid in TS, but not vice versa.',
  },
  {
    id: 'ts-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['basics'],
    questionRu: 'Что такое any, unknown и never — в чём разница?',
    questionEn: 'What are any, unknown, and never — what is the difference?',
    answerRu: '- `any`: отключает проверку типов, можно делать всё что угодно — **антипаттерн**\n- `unknown`: типобезопасная альтернатива `any`, перед использованием нужно сузить тип\n- `never`: тип для значений, которые никогда не возникнут (бесконечный цикл, всегда бросающая функция, exhaustive check)',
    answerEn: '- `any`: disables type checking, you can do anything with it — an **antipattern**\n- `unknown`: a type-safe alternative to `any`, you must narrow the type before using it\n- `never`: the type for values that can never occur (infinite loop, always-throwing function, exhaustive check)',
  },
  {
    id: 'ts-003',
    difficulty: 'EASY',
    order: 3,
    tags: ['basics'],
    questionRu: 'Что такое union и intersection типы?',
    questionEn: 'What are union and intersection types?',
    answerRu: '**Union** (`A | B`): значение может быть типом `A` или `B`.\n\n**Intersection** (`A & B`): значение должно соответствовать и `A`, и `B` одновременно — объединяет свойства.\n\nUnion — «или», intersection — «и».',
    answerEn: '**Union** (`A | B`): a value can be either type `A` or type `B`.\n\n**Intersection** (`A & B`): a value must satisfy both `A` and `B` simultaneously — it merges their properties.\n\nUnion means "or", intersection means "and".',
  },
  {
    id: 'ts-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['basics'],
    questionRu: 'Что такое literal types и const assertion?',
    questionEn: 'What are literal types and const assertion?',
    answerRu: "**Literal types** — тип конкретного значения: `type Dir = 'left' | 'right'`.\n\n**`as const`** говорит TS считать значение максимально узким типом:\n`const dirs = ['left', 'right'] as const` — тип становится `readonly ['left', 'right']`, а не `string[]`.",
    answerEn: "**Literal types** represent a specific value as a type: `type Dir = 'left' | 'right'`.\n\n**`as const`** tells TS to infer the narrowest possible type:\n`const dirs = ['left', 'right'] as const` — the type becomes `readonly ['left', 'right']` instead of `string[]`.",
  },
  {
    id: 'ts-005',
    difficulty: 'EASY',
    order: 5,
    tags: ['basics'],
    questionRu: 'Что такое tuple в TypeScript?',
    questionEn: 'What is a tuple in TypeScript?',
    answerRu: '**Tuple** — массив с фиксированным количеством элементов заданных типов: `type Point = [number, number]`.\n\nВ отличие от массива, порядок и типы позиций фиксированы.\n\nПоддерживает rest и optional элементы: `[string, ...number[]]` или `[string, number?]`.',
    answerEn: 'A **tuple** is an array with a fixed number of elements of specified types: `type Point = [number, number]`.\n\nUnlike a regular array, the order and types of each position are fixed.\n\nIt supports rest and optional elements: `[string, ...number[]]` or `[string, number?]`.',
  },
  {
    id: 'ts-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['basics'],
    questionRu: 'Что такое enum и какие у него альтернативы?',
    questionEn: 'What is an enum and what are its alternatives?',
    answerRu: "**`enum`** — перечисление именованных констант. Числовые enum генерируют JS-код (объект), **`const enum`** — стираются при компиляции.\n\nПроблемы `enum`:\n- неожиданное поведение числовых enum\n- плохая совместимость\n\nАльтернативы:\n- union of literals: `'a' | 'b'`\n- `as const` объект",
    answerEn: "An **`enum`** is a set of named constants. Numeric enums generate a JS object at runtime; **`const enum`**s are erased during compilation.\n\nProblems with `enum`:\n- unexpected behavior of numeric enums\n- poor compatibility\n\nAlternatives:\n- a union of literals: `'a' | 'b'`\n- an `as const` object",
  },
  {
    id: 'ts-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['interfaces'],
    questionRu: 'В чём разница между interface и type?',
    questionEn: 'What is the difference between interface and type?',
    answerRu: '**`interface`**:\n- декларативное слияние (можно расширить в другом месте)\n- `extends` для наследования\n- только объектные типы\n\n**`type`**:\n- любые типы (union, intersection, primitives, tuples)\n- нет слияния\n\nНа практике: `interface` для публичных API и классов, `type` для всего остального.',
    answerEn: '**`interface`**:\n- supports declaration merging (can be extended elsewhere)\n- uses `extends` for inheritance\n- only object types\n\n**`type`**:\n- supports any types (union, intersection, primitives, tuples)\n- no merging\n\nIn practice: use `interface` for public APIs and classes, `type` for everything else.',
  },
  {
    id: 'ts-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['interfaces'],
    questionRu: 'Что такое декларативное слияние интерфейсов?',
    questionEn: 'What is interface declaration merging?',
    answerRu: '**Declaration merging** — если объявить `interface` с одинаковым именем дважды, TS сливает их в один.\n\nИспользуется для расширения сторонних типов (например, добавить поля в `Window` или Express `Request`).\n\n`type` alias не поддерживает слияние.',
    answerEn: '**Declaration merging** means that if you declare an `interface` with the same name twice, TS merges them into one.\n\nIt is used to augment third-party types (e.g., adding fields to `Window` or Express `Request`).\n\nType aliases do not support merging.',
  },
  {
    id: 'ts-009',
    difficulty: 'EASY',
    order: 9,
    tags: ['interfaces'],
    questionRu: 'Как сделать свойства опциональными или readonly?',
    questionEn: 'How do you make properties optional or readonly?',
    answerRu: '**Опциональное свойство**: `name?: string` — может быть `string` или `undefined`.\n\n**`readonly`**: `readonly id: number` — нельзя переназначить после создания.\n\nДля массивов: `ReadonlyArray<T>` или `readonly T[]`.\n\nUtility types:\n- `Partial<T>` делает все поля опциональными\n- `Readonly<T>` делает все поля `readonly`',
    answerEn: '**Optional property**: `name?: string` — can be `string` or `undefined`.\n\n**`readonly`**: `readonly id: number` — cannot be reassigned after creation.\n\nFor arrays: `ReadonlyArray<T>` or `readonly T[]`.\n\nUtility types:\n- `Partial<T>` makes all fields optional\n- `Readonly<T>` makes all fields `readonly`',
  },
  {
    id: 'ts-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['interfaces'],
    questionRu: 'Что такое index signature?',
    questionEn: 'What is an index signature?',
    answerRu: '**Index signature** позволяет описать объект с динамическими ключами: `{ [key: string]: number }`.\n\nОзначает: любой строковый ключ возвращает `number`.\n\nМожно комбинировать с конкретными свойствами — они должны быть совместимы с типом значения индекса.',
    answerEn: 'An **index signature** describes an object with dynamic keys: `{ [key: string]: number }`.\n\nIt means: any string key returns a `number`.\n\nYou can combine it with specific properties — they must be compatible with the index value type.',
  },
  {
    id: 'ts-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['interfaces'],
    questionRu: 'Как работает extends в интерфейсах и типах?',
    questionEn: 'How does extends work in interfaces and types?',
    answerRu: '`interface B extends A` — `B` наследует все свойства `A` и может добавить свои. Нельзя переопределить тип свойства на несовместимый.\n\nДля типов: `type B = A & { extra: string }` — intersection.\n\nИнтерфейс может расширять несколько: `interface C extends A, B`.',
    answerEn: '`interface B extends A` — `B` inherits all properties of `A` and can add its own. You cannot override a property with an incompatible type.\n\nFor types: `type B = A & { extra: string }` — use intersection.\n\nAn interface can extend multiple: `interface C extends A, B`.',
  },
  {
    id: 'ts-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['interfaces'],
    questionRu: 'Что такое structural typing в TypeScript?',
    questionEn: 'What is structural typing in TypeScript?',
    answerRu: 'TS использует **структурную типизацию** (duck typing): тип совместим, если имеет нужную структуру, а не по имени.\n\nОбъект `{ name: string, age: number }` совместим с интерфейсом `{ name: string }` — лишние поля разрешены.\n\nИсключение: object literals проверяются строже (**excess property check**).',
    answerEn: 'TS uses **structural typing** (duck typing): a type is compatible if it has the required structure, not by name.\n\nAn object `{ name: string, age: number }` is compatible with interface `{ name: string }` — extra fields are allowed.\n\nException: object literals are checked more strictly (**excess property check**).',
  },
  {
    id: 'ts-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['generics'],
    questionRu: 'Что такое дженерики (generics) и зачем они нужны?',
    questionEn: 'What are generics and why are they useful?',
    answerRu: '**Дженерики** — параметры типов, позволяющие писать переиспользуемый типобезопасный код.\n\n`function identity<T>(arg: T): T` — работает с любым типом, сохраняя информацию о нём.\n\nБез дженериков пришлось бы использовать `any` и терять типизацию.',
    answerEn: '**Generics** are type parameters that allow you to write reusable, type-safe code.\n\n`function identity<T>(arg: T): T` — works with any type while preserving information about it.\n\nWithout generics you would have to use `any` and lose type safety.',
  },
  {
    id: 'ts-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['generics'],
    questionRu: 'Как ограничить дженерик (generic constraints)?',
    questionEn: 'How do you constrain a generic (generic constraints)?',
    answerRu: '`extends` ограничивает тип:\n`function getLength<T extends { length: number }>(arg: T)` — `T` должен иметь свойство `length`.\n\nМожно ограничить одним дженериком другой:\n`function get<T, K extends keyof T>(obj: T, key: K): T[K]`',
    answerEn: '`extends` constrains the type:\n`function getLength<T extends { length: number }>(arg: T)` — `T` must have a `length` property.\n\nYou can also constrain one generic with another:\n`function get<T, K extends keyof T>(obj: T, key: K): T[K]`',
  },
  {
    id: 'ts-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['generics'],
    questionRu: 'Что такое keyof и typeof в TypeScript?',
    questionEn: 'What are keyof and typeof in TypeScript?',
    answerRu: "**`keyof T`** — union тип из всех ключей `T`: `keyof { a: 1, b: 2 }` → `'a' | 'b'`.\n\n**`typeof`** — получить тип значения на уровне типов: `const config = {...}; type Config = typeof config`.\n\nВместе: `keyof typeof obj` — ключи объекта как union.",
    answerEn: "**`keyof T`** — a union type of all keys of `T`: `keyof { a: 1, b: 2 }` → `'a' | 'b'`.\n\n**`typeof`** — gets the type of a value at the type level: `const config = {...}; type Config = typeof config`.\n\nCombined: `keyof typeof obj` — the keys of an object as a union.",
  },
  {
    id: 'ts-016',
    difficulty: 'HARD',
    order: 16,
    tags: ['generics'],
    questionRu: 'Что такое conditional types?',
    questionEn: 'What are conditional types?',
    answerRu: '**Условные типы**: `T extends U ? X : Y` — если `T` совместим с `U`, тип `X`, иначе `Y`.\n\nПример: `type IsString<T> = T extends string ? true : false`.\n\nС `infer` можно извлекать типы:\n`type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never`',
    answerEn: '**Conditional types**: `T extends U ? X : Y` — if `T` is assignable to `U`, the type is `X`, otherwise `Y`.\n\nExample: `type IsString<T> = T extends string ? true : false`.\n\nWith `infer` you can extract types:\n`type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never`',
  },
  {
    id: 'ts-017',
    difficulty: 'HARD',
    order: 17,
    tags: ['generics'],
    questionRu: 'Что такое mapped types?',
    questionEn: 'What are mapped types?',
    answerRu: '**Mapped types** создают новый тип, итерируясь по ключам другого:\n`type Readonly<T> = { readonly [K in keyof T]: T[K] }`\n\nВозможности:\n- модифицировать модификаторы (`+/-` `readonly`, `+/-` `?`)\n- менять тип значений\n- фильтровать ключи через `as`',
    answerEn: '**Mapped types** create a new type by iterating over the keys of another:\n`type Readonly<T> = { readonly [K in keyof T]: T[K] }`\n\nCapabilities:\n- modify modifiers (`+/-` `readonly`, `+/-` `?`)\n- transform value types\n- filter keys using `as`',
  },
  {
    id: 'ts-018',
    difficulty: 'HARD',
    order: 18,
    tags: ['generics'],
    questionRu: 'Что такое infer в TypeScript?',
    questionEn: 'What is infer in TypeScript?',
    answerRu: '**`infer`** используется внутри conditional types для извлечения части типа:\n`type UnpackArray<T> = T extends Array<infer Item> ? Item : T`\n\nПозволяет «захватить» тип в переменную.\n\nВстроенный пример: `ReturnType<T>` использует `infer R` для получения типа возвращаемого значения.',
    answerEn: '**`infer`** is used inside conditional types to extract part of a type:\n`type UnpackArray<T> = T extends Array<infer Item> ? Item : T`\n\nIt lets you "capture" a type into a variable.\n\nBuilt-in example: `ReturnType<T>` uses `infer R` to obtain the return type of a function.',
  },
  {
    id: 'ts-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['utility-types'],
    questionRu: 'Какие встроенные utility types используются чаще всего?',
    questionEn: 'What are the most commonly used built-in utility types?',
    answerRu: '- `Partial<T>`: все поля опциональны\n- `Required<T>`: все поля обязательны\n- `Readonly<T>`: все поля `readonly`\n- `Pick<T, K>`: выбрать поля `K` из `T`\n- `Omit<T, K>`: убрать поля `K` из `T`\n- `Record<K, V>`: объект с ключами `K` и значениями `V`\n- `ReturnType<T>`: тип возвращаемого значения функции',
    answerEn: '- `Partial<T>`: all fields optional\n- `Required<T>`: all fields required\n- `Readonly<T>`: all fields `readonly`\n- `Pick<T, K>`: select fields `K` from `T`\n- `Omit<T, K>`: remove fields `K` from `T`\n- `Record<K, V>`: object with keys `K` and values `V`\n- `ReturnType<T>`: the return type of a function',
  },
  {
    id: 'ts-020',
    difficulty: 'EASY',
    order: 20,
    tags: ['utility-types'],
    questionRu: 'В чём разница между Pick и Omit?',
    questionEn: 'What is the difference between Pick and Omit?',
    answerRu: "**`Pick<T, 'a' | 'b'>`** — создаёт тип только с перечисленными полями.\n\n**`Omit<T, 'a' | 'b'>`** — создаёт тип без перечисленных полей.\n\n`Pick` удобен когда нужно мало полей, `Omit` — когда нужно убрать 1–2 поля из большого типа.",
    answerEn: "**`Pick<T, 'a' | 'b'>`** — creates a type with only the listed fields.\n\n**`Omit<T, 'a' | 'b'>`** — creates a type without the listed fields.\n\n`Pick` is convenient when you need just a few fields; `Omit` is better when you want to remove 1–2 fields from a large type.",
  },
  {
    id: 'ts-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['utility-types'],
    questionRu: 'Что делает NonNullable?',
    questionEn: 'What does NonNullable do?',
    answerRu: '**`NonNullable<T>`** убирает `null` и `undefined` из типа:\n`NonNullable<string | null | undefined>` → `string`\n\nПолезно когда получаешь тип из другого источника и знаешь, что значение гарантированно не `null`.',
    answerEn: '**`NonNullable<T>`** removes `null` and `undefined` from a type:\n`NonNullable<string | null | undefined>` → `string`\n\nUseful when you receive a type from another source and know the value is guaranteed to be non-null.',
  },
  {
    id: 'ts-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['utility-types'],
    questionRu: 'Что такое Parameters и ReturnType?',
    questionEn: 'What are Parameters and ReturnType?',
    answerRu: '**`Parameters<T>`** — tuple тип параметров функции `T`.\n\n**`ReturnType<T>`** — тип возвращаемого значения функции `T`.\n\nПример:\n`type F = (a: string, b: number) => boolean`\n- `Parameters<F>` → `[string, number]`\n- `ReturnType<F>` → `boolean`\n\nПолезны для типизации обёрток над функциями.',
    answerEn: '**`Parameters<T>`** — a tuple type of the parameters of function `T`.\n\n**`ReturnType<T>`** — the return type of function `T`.\n\nExample:\n`type F = (a: string, b: number) => boolean`\n- `Parameters<F>` → `[string, number]`\n- `ReturnType<F>` → `boolean`\n\nUseful for typing wrappers around functions.',
  },
  {
    id: 'ts-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['utility-types'],
    questionRu: 'Что такое Awaited?',
    questionEn: 'What is Awaited?',
    answerRu: '**`Awaited<T>`** рекурсивно разворачивает `Promise`:\n- `Awaited<Promise<string>>` → `string`\n- `Awaited<Promise<Promise<number>>>` → `number`\n\nПоявился в TS 4.5. Используется вместо ручного `ReturnType` + разворачивания `Promise` для async функций.',
    answerEn: '**`Awaited<T>`** recursively unwraps a `Promise`:\n- `Awaited<Promise<string>>` → `string`\n- `Awaited<Promise<Promise<number>>>` → `number`\n\nIntroduced in TS 4.5. Used instead of manually combining `ReturnType` and `Promise` unwrapping for async functions.',
  },
  {
    id: 'ts-024',
    difficulty: 'HARD',
    order: 24,
    tags: ['utility-types'],
    questionRu: 'Как создать свой utility type?',
    questionEn: 'How do you create a custom utility type?',
    answerRu: 'Через **mapped types** и **conditional types**.\n\nПример `DeepPartial`:\n`type DeepPartial<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K] }`\n\nПример `Mutable` (убрать `readonly`):\n`type Mutable<T> = { -readonly [K in keyof T]: T[K] }`',
    answerEn: 'Using **mapped types** and **conditional types**.\n\nExample `DeepPartial`:\n`type DeepPartial<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K] }`\n\nExample `Mutable` (remove `readonly`):\n`type Mutable<T> = { -readonly [K in keyof T]: T[K] }`',
  },
  {
    id: 'ts-025',
    difficulty: 'MEDIUM',
    order: 25,
    tags: ['narrowing'],
    questionRu: 'Что такое type narrowing?',
    questionEn: 'What is type narrowing?',
    answerRu: "**Narrowing** — сужение типа в определённой ветке кода на основе проверок.\n\nПосле `if (typeof x === 'string')` TS знает, что `x` — `string`.\n\nРаботает с: `typeof`, `instanceof`, `in`, сравнениями, truthiness check и **type guards**.",
    answerEn: "**Narrowing** is the process of refining a type within a specific branch of code based on checks.\n\nAfter `if (typeof x === 'string')`, TS knows that `x` is a `string`.\n\nWorks with: `typeof`, `instanceof`, `in`, comparisons, truthiness checks, and **type guards**.",
  },
  {
    id: 'ts-026',
    difficulty: 'MEDIUM',
    order: 26,
    tags: ['narrowing'],
    questionRu: 'Что такое type guard?',
    questionEn: 'What is a type guard?',
    answerRu: "**Type guard** — функция с возвращаемым типом **predicate** (`arg is Type`), которая сужает тип аргумента:\n`function isString(x: unknown): x is string { return typeof x === 'string' }`\n\nПосле вызова TS знает тип в ветке `true`.",
    answerEn: "A **type guard** is a function with a return type **predicate** (`arg is Type`) that narrows the type of its argument:\n`function isString(x: unknown): x is string { return typeof x === 'string' }`\n\nAfter the call, TS knows the type in the `true` branch.",
  },
  {
    id: 'ts-027',
    difficulty: 'MEDIUM',
    order: 27,
    tags: ['narrowing'],
    questionRu: 'Что такое discriminated union?',
    questionEn: 'What is a discriminated union?',
    answerRu: "**Discriminated union** — union тип с общим литеральным полем-**дискриминатором**:\n`type Shape = { kind: 'circle', radius: number } | { kind: 'rect', width: number }`\n\nSwitch по `kind` сужает тип в каждой ветке. TS проверяет исчерпанность через `never`.",
    answerEn: "A **discriminated union** is a union type with a shared literal **discriminant** field:\n`type Shape = { kind: 'circle', radius: number } | { kind: 'rect', width: number }`\n\nSwitching on `kind` narrows the type in each branch. TS checks exhaustiveness via `never`.",
  },
  {
    id: 'ts-028',
    difficulty: 'HARD',
    order: 28,
    tags: ['narrowing'],
    questionRu: 'Что такое assertion functions?',
    questionEn: 'What are assertion functions?',
    answerRu: '**Assertion function** — функция, которая бросает ошибку если условие не выполнено, и сужает тип:\n`function assert(cond: unknown): asserts cond`\n\nПосле вызова TS считает `cond` truthy.\n\nВариант: `asserts x is string` — после вызова `x` имеет тип `string`.',
    answerEn: 'An **assertion function** throws an error if a condition is not met and narrows the type:\n`function assert(cond: unknown): asserts cond`\n\nAfter the call, TS treats `cond` as truthy.\n\nVariant: `asserts x is string` — after the call, `x` has type `string`.',
  },
  {
    id: 'ts-029',
    difficulty: 'HARD',
    order: 29,
    tags: ['narrowing'],
    questionRu: 'Как работает exhaustiveness check?',
    questionEn: 'How does exhaustiveness checking work?',
    answerRu: '**Exhaustiveness check** — проверка что все варианты `union` обработаны.\n\nВ `switch`/`if` после всех кейсов присваиваем переменную типу `never`:\n`const _exhaustive: never = shape`\n\nЕсли добавить новый вариант в `union` без обработки — TS выдаст ошибку компиляции.',
    answerEn: '**Exhaustiveness checking** verifies that all variants of a union are handled.\n\nAfter all cases in a `switch`/`if`, assign the variable to `never`:\n`const _exhaustive: never = shape`\n\nIf you add a new variant to the union without handling it, TS will produce a compile-time error.',
  },
  {
    id: 'ts-030',
    difficulty: 'HARD',
    order: 30,
    tags: ['advanced'],
    questionRu: 'Что такое template literal types?',
    questionEn: 'What are template literal types?',
    answerRu: "**Template literal types** строят строковые типы по шаблону:\n`type EventName<T extends string> = \\`on${Capitalize<T>}\\``\n\nИз `'click' | 'focus'` получим `'onClick' | 'onFocus'`.\n\nПолезны для типизации:\n- event-систем\n- CSS-свойств\n- API-путей",
    answerEn: "**Template literal types** build string types from a template:\n`type EventName<T extends string> = \\`on${Capitalize<T>}\\``\n\nFrom `'click' | 'focus'` you get `'onClick' | 'onFocus'`.\n\nUseful for typing:\n- event systems\n- CSS properties\n- API paths",
  },
  {
    id: 'ts-031',
    difficulty: 'MEDIUM',
    order: 31,
    tags: ['advanced'],
    questionRu: 'Что такое declaration files (.d.ts)?',
    questionEn: 'What are declaration files (.d.ts)?',
    answerRu: "**`.d.ts`** файлы содержат только объявления типов без реализации.\n\nИспользуются для типизации JS-библиотек без TS-кода. Пакеты `@types/*` содержат такие файлы.\n\nМожно создать свой для JS-модуля:\n`declare module 'lib' { export function fn(): void }`",
    answerEn: "**`.d.ts`** files contain only type declarations without implementation.\n\nThey are used to add types to JS libraries that don't have TS code. `@types/*` packages contain such files.\n\nYou can create your own for a JS module:\n`declare module 'lib' { export function fn(): void }`",
  },
  {
    id: 'ts-032',
    difficulty: 'MEDIUM',
    order: 32,
    tags: ['advanced'],
    questionRu: 'Что такое satisfies оператор?',
    questionEn: 'What is the satisfies operator?',
    answerRu: '**`satisfies`** (TS 4.9) проверяет что значение соответствует типу, но сохраняет более узкий тип:\n`const config = { port: 3000 } satisfies Config` — `port` остаётся типом `3000`, не `number`.\n\nВ отличие от `as Config` не теряет конкретность типа.',
    answerEn: '**`satisfies`** (TS 4.9) validates that a value matches a type while preserving a narrower inferred type:\n`const config = { port: 3000 } satisfies Config` — `port` remains type `3000`, not `number`.\n\nUnlike `as Config`, it does not widen the type.',
  },
  {
    id: 'ts-033',
    difficulty: 'MEDIUM',
    order: 33,
    tags: ['advanced'],
    questionRu: 'Что такое type coercion через as и когда это опасно?',
    questionEn: 'What is type assertion with as and when is it dangerous?',
    answerRu: '**Type assertion** (`as Type`) говорит TS считать значение указанным типом без проверки.\n\nОпасно: можно написать `as string` когда реально `number` — ошибка в runtime.\n\nДвойной assert (`as unknown as T`) — красный флаг.\n\nБезопаснее: **type guard** или `unknown` → narrowing.',
    answerEn: '**Type assertion** (`as Type`) tells TS to treat a value as the specified type without a runtime check.\n\nDangerous: you can assert `as string` when the value is actually a `number` — causing a runtime error.\n\nA double assertion (`as unknown as T`) is a red flag.\n\nSafer alternatives: a **type guard** or `unknown` → narrowing.',
  },
  {
    id: 'ts-034',
    difficulty: 'HARD',
    order: 34,
    tags: ['advanced'],
    questionRu: 'Как типизировать this в функциях?',
    questionEn: 'How do you type this in functions?',
    answerRu: 'TS позволяет явно указать тип `this` первым параметром (удаляется при компиляции):\n`function fn(this: HTMLElement, e: Event) {}`\n\nПолезно для методов, передаваемых как колбэки.\n\n`noImplicitThis` в `tsconfig` требует явного указания `this`.',
    answerEn: 'TS lets you explicitly annotate the type of `this` as the first parameter (it is erased at compile time):\n`function fn(this: HTMLElement, e: Event) {}`\n\nUseful for methods passed as callbacks.\n\n`noImplicitThis` in `tsconfig` requires `this` to be explicitly typed.',
  },
  {
    id: 'ts-035',
    difficulty: 'MEDIUM',
    order: 35,
    tags: ['advanced'],
    questionRu: 'Что такое strict mode в tsconfig и какие флаги включает?',
    questionEn: 'What is strict mode in tsconfig and which flags does it enable?',
    answerRu: '`strict: true` включает группу флагов:\n- `noImplicitAny` — запрет неявного `any`\n- `strictNullChecks` — `null`/`undefined` не совместимы с другими типами\n- `strictFunctionTypes`\n- `strictBindCallApply`\n- `strictPropertyInitialization`\n- `noImplicitThis`\n\nРекомендуется включать в новых проектах.',
    answerEn: '`strict: true` enables a group of flags:\n- `noImplicitAny` — disallows implicit `any`\n- `strictNullChecks` — `null`/`undefined` are not assignable to other types\n- `strictFunctionTypes`\n- `strictBindCallApply`\n- `strictPropertyInitialization`\n- `noImplicitThis`\n\nRecommended for all new projects.',
  },
];
