import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'ts-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['basics'],
    questionRu: 'Чем TypeScript отличается от JavaScript?',
    questionEn: 'Чем TypeScript отличается от JavaScript?',
    answerRu: 'TypeScript — надмножество JavaScript со статической типизацией. Компилируется в JS. Преимущества: раннее обнаружение ошибок, автодополнение в IDE, самодокументируемый код. Все JS-программы валидны в TS, но не наоборот.',
    answerEn: 'TypeScript — надмножество JavaScript со статической типизацией. Компилируется в JS. Преимущества: раннее обнаружение ошибок, автодополнение в IDE, самодокументируемый код. Все JS-программы валидны в TS, но не наоборот.',
  },
  {
    id: 'ts-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['basics'],
    questionRu: 'Что такое any, unknown и never — в чём разница?',
    questionEn: 'Что такое any, unknown и never — в чём разница?',
    answerRu: 'any: отключает проверку типов, можно делать всё что угодно — антипаттерн. unknown: типобезопасная альтернатива any, перед использованием нужно сузить тип. never: тип для значений, которые никогда не возникнут (бесконечный цикл, всегда бросающая функция, exhaustive check).',
    answerEn: 'any: отключает проверку типов, можно делать всё что угодно — антипаттерн. unknown: типобезопасная альтернатива any, перед использованием нужно сузить тип. never: тип для значений, которые никогда не возникнут (бесконечный цикл, всегда бросающая функция, exhaustive check).',
  },
  {
    id: 'ts-003',
    difficulty: 'EASY',
    order: 3,
    tags: ['basics'],
    questionRu: 'Что такое union и intersection типы?',
    questionEn: 'Что такое union и intersection типы?',
    answerRu: 'Union (A | B): значение может быть типом A или B. Intersection (A & B): значение должно соответствовать и A, и B одновременно — объединяет свойства. Union — «или», intersection — «и».',
    answerEn: 'Union (A | B): значение может быть типом A или B. Intersection (A & B): значение должно соответствовать и A, и B одновременно — объединяет свойства. Union — «или», intersection — «и».',
  },
  {
    id: 'ts-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['basics'],
    questionRu: 'Что такое literal types и const assertion?',
    questionEn: 'Что такое literal types и const assertion?',
    answerRu: "Literal types — тип конкретного значения: type Dir = 'left' | 'right'. const assertion (as const) говорит TS считать значение максимально узким типом: const dirs = ['left', 'right'] as const — тип становится readonly ['left', 'right'], а не string[].",
    answerEn: "Literal types — тип конкретного значения: type Dir = 'left' | 'right'. const assertion (as const) говорит TS считать значение максимально узким типом: const dirs = ['left', 'right'] as const — тип становится readonly ['left', 'right'], а не string[].",
  },
  {
    id: 'ts-005',
    difficulty: 'EASY',
    order: 5,
    tags: ['basics'],
    questionRu: 'Что такое tuple в TypeScript?',
    questionEn: 'Что такое tuple в TypeScript?',
    answerRu: 'Tuple — массив с фиксированным количеством элементов заданных типов: type Point = [number, number]. В отличие от массива, порядок и типы позиций фиксированы. Поддерживает rest и optional элементы: [string, ...number[]] или [string, number?].',
    answerEn: 'Tuple — массив с фиксированным количеством элементов заданных типов: type Point = [number, number]. В отличие от массива, порядок и типы позиций фиксированы. Поддерживает rest и optional элементы: [string, ...number[]] или [string, number?].',
  },
  {
    id: 'ts-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['basics'],
    questionRu: 'Что такое enum и какие у него альтернативы?',
    questionEn: 'Что такое enum и какие у него альтернативы?',
    answerRu: "enum — перечисление именованных констант. Числовые enum генерируют JS-код (объект), const enum — стираются при компиляции. Проблемы enum: неожиданное поведение числовых enum, плохая совместимость. Альтернативы: union of literals ('a' | 'b') или as const объект.",
    answerEn: "enum — перечисление именованных констант. Числовые enum генерируют JS-код (объект), const enum — стираются при компиляции. Проблемы enum: неожиданное поведение числовых enum, плохая совместимость. Альтернативы: union of literals ('a' | 'b') или as const объект.",
  },
  {
    id: 'ts-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['interfaces'],
    questionRu: 'В чём разница между interface и type?',
    questionEn: 'В чём разница между interface и type?',
    answerRu: 'interface: декларативное слияние (можно расширить в другом месте), extends для наследования, только объектные типы. type: любые типы (union, intersection, primitives, tuples), нет слияния. На практике: interface для публичных API и классов, type для всего остального.',
    answerEn: 'interface: декларативное слияние (можно расширить в другом месте), extends для наследования, только объектные типы. type: любые типы (union, intersection, primitives, tuples), нет слияния. На практике: interface для публичных API и классов, type для всего остального.',
  },
  {
    id: 'ts-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['interfaces'],
    questionRu: 'Что такое декларативное слияние интерфейсов?',
    questionEn: 'Что такое декларативное слияние интерфейсов?',
    answerRu: 'Declaration merging — если объявить interface с одинаковым именем дважды, TS сливает их в один. Используется для расширения сторонних типов (например, добавить поля в Window или Express Request). type alias не поддерживает слияние.',
    answerEn: 'Declaration merging — если объявить interface с одинаковым именем дважды, TS сливает их в один. Используется для расширения сторонних типов (например, добавить поля в Window или Express Request). type alias не поддерживает слияние.',
  },
  {
    id: 'ts-009',
    difficulty: 'EASY',
    order: 9,
    tags: ['interfaces'],
    questionRu: 'Как сделать свойства опциональными или readonly?',
    questionEn: 'Как сделать свойства опциональными или readonly?',
    answerRu: 'Опциональное свойство: name?: string — может быть string или undefined. readonly: readonly id: number — нельзя переназначить после создания. Массив: ReadonlyArray<T> или readonly T[]. Utility types: Partial<T> делает все поля опциональными, Readonly<T> — все readonly.',
    answerEn: 'Опциональное свойство: name?: string — может быть string или undefined. readonly: readonly id: number — нельзя переназначить после создания. Массив: ReadonlyArray<T> или readonly T[]. Utility types: Partial<T> делает все поля опциональными, Readonly<T> — все readonly.',
  },
  {
    id: 'ts-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['interfaces'],
    questionRu: 'Что такое index signature?',
    questionEn: 'Что такое index signature?',
    answerRu: 'Index signature позволяет описать объект с динамическими ключами: { [key: string]: number }. Означает: любой строковый ключ возвращает number. Можно комбинировать с конкретными свойствами — они должны быть совместимы с типом значения индекса.',
    answerEn: 'Index signature позволяет описать объект с динамическими ключами: { [key: string]: number }. Означает: любой строковый ключ возвращает number. Можно комбинировать с конкретными свойствами — они должны быть совместимы с типом значения индекса.',
  },
  {
    id: 'ts-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['interfaces'],
    questionRu: 'Как работает extends в интерфейсах и типах?',
    questionEn: 'Как работает extends в интерфейсах и типах?',
    answerRu: 'interface B extends A — B наследует все свойства A и может добавить свои. Нельзя переопределить тип свойства на несовместимый. type B = A & { extra: string } — intersection для типов. Интерфейс может extends несколько: interface C extends A, B.',
    answerEn: 'interface B extends A — B наследует все свойства A и может добавить свои. Нельзя переопределить тип свойства на несовместимый. type B = A & { extra: string } — intersection для типов. Интерфейс может extends несколько: interface C extends A, B.',
  },
  {
    id: 'ts-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['interfaces'],
    questionRu: 'Что такое structural typing в TypeScript?',
    questionEn: 'Что такое structural typing в TypeScript?',
    answerRu: 'TS использует структурную типизацию (duck typing): тип совместим, если имеет нужную структуру, а не по имени. Объект { name: string, age: number } совместим с интерфейсом { name: string } — лишние поля разрешены. Исключение: object literals проверяются строже (excess property check).',
    answerEn: 'TS использует структурную типизацию (duck typing): тип совместим, если имеет нужную структуру, а не по имени. Объект { name: string, age: number } совместим с интерфейсом { name: string } — лишние поля разрешены. Исключение: object literals проверяются строже (excess property check).',
  },
  {
    id: 'ts-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['generics'],
    questionRu: 'Что такое дженерики (generics) и зачем они нужны?',
    questionEn: 'Что такое дженерики (generics) и зачем они нужны?',
    answerRu: 'Дженерики — параметры типов, позволяющие писать переиспользуемый типобезопасный код. function identity<T>(arg: T): T — работает с любым типом, сохраняя информацию о нём. Без дженериков пришлось бы использовать any и терять типизацию.',
    answerEn: 'Дженерики — параметры типов, позволяющие писать переиспользуемый типобезопасный код. function identity<T>(arg: T): T — работает с любым типом, сохраняя информацию о нём. Без дженериков пришлось бы использовать any и терять типизацию.',
  },
  {
    id: 'ts-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['generics'],
    questionRu: 'Как ограничить дженерик (generic constraints)?',
    questionEn: 'Как ограничить дженерик (generic constraints)?',
    answerRu: 'extends ограничивает тип: function getLength<T extends { length: number }>(arg: T) — T должен иметь свойство length. Можно ограничить другим дженериком: function get<T, K extends keyof T>(obj: T, key: K): T[K].',
    answerEn: 'extends ограничивает тип: function getLength<T extends { length: number }>(arg: T) — T должен иметь свойство length. Можно ограничить другим дженериком: function get<T, K extends keyof T>(obj: T, key: K): T[K].',
  },
  {
    id: 'ts-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['generics'],
    questionRu: 'Что такое keyof и typeof в TypeScript?',
    questionEn: 'Что такое keyof и typeof в TypeScript?',
    answerRu: "keyof T — union тип из всех ключей T: keyof { a: 1, b: 2 } → 'a' | 'b'. typeof — получить тип значения на уровне типов: const config = {...}; type Config = typeof config. Вместе: keyof typeof obj — ключи объекта как union.",
    answerEn: "keyof T — union тип из всех ключей T: keyof { a: 1, b: 2 } → 'a' | 'b'. typeof — получить тип значения на уровне типов: const config = {...}; type Config = typeof config. Вместе: keyof typeof obj — ключи объекта как union.",
  },
  {
    id: 'ts-016',
    difficulty: 'HARD',
    order: 16,
    tags: ['generics'],
    questionRu: 'Что такое conditional types?',
    questionEn: 'Что такое conditional types?',
    answerRu: 'Условные типы: T extends U ? X : Y. Если T совместим с U — тип X, иначе Y. Пример: type IsString<T> = T extends string ? true : false. С infer можно извлекать типы: type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never.',
    answerEn: 'Условные типы: T extends U ? X : Y. Если T совместим с U — тип X, иначе Y. Пример: type IsString<T> = T extends string ? true : false. С infer можно извлекать типы: type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never.',
  },
  {
    id: 'ts-017',
    difficulty: 'HARD',
    order: 17,
    tags: ['generics'],
    questionRu: 'Что такое mapped types?',
    questionEn: 'Что такое mapped types?',
    answerRu: 'Mapped types создают новый тип, итерируясь по ключам другого: type Readonly<T> = { readonly [K in keyof T]: T[K] }. Можно модифицировать модификаторы (+/- readonly, +/- ?), менять тип значений, фильтровать ключи через as.',
    answerEn: 'Mapped types создают новый тип, итерируясь по ключам другого: type Readonly<T> = { readonly [K in keyof T]: T[K] }. Можно модифицировать модификаторы (+/- readonly, +/- ?), менять тип значений, фильтровать ключи через as.',
  },
  {
    id: 'ts-018',
    difficulty: 'HARD',
    order: 18,
    tags: ['generics'],
    questionRu: 'Что такое infer в TypeScript?',
    questionEn: 'Что такое infer в TypeScript?',
    answerRu: 'infer используется внутри conditional types для извлечения части типа: type UnpackArray<T> = T extends Array<infer Item> ? Item : T. Позволяет «захватить» тип в переменную. Встроенный пример: ReturnType<T> использует infer R для получения типа возвращаемого значения.',
    answerEn: 'infer используется внутри conditional types для извлечения части типа: type UnpackArray<T> = T extends Array<infer Item> ? Item : T. Позволяет «захватить» тип в переменную. Встроенный пример: ReturnType<T> использует infer R для получения типа возвращаемого значения.',
  },
  {
    id: 'ts-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['utility-types'],
    questionRu: 'Какие встроенные utility types используются чаще всего?',
    questionEn: 'Какие встроенные utility types используются чаще всего?',
    answerRu: 'Partial<T>: все поля опциональны. Required<T>: все поля обязательны. Readonly<T>: все поля readonly. Pick<T, K>: выбрать поля K из T. Omit<T, K>: убрать поля K из T. Record<K, V>: объект с ключами K и значениями V. ReturnType<T>: тип возвращаемого значения функции.',
    answerEn: 'Partial<T>: все поля опциональны. Required<T>: все поля обязательны. Readonly<T>: все поля readonly. Pick<T, K>: выбрать поля K из T. Omit<T, K>: убрать поля K из T. Record<K, V>: объект с ключами K и значениями V. ReturnType<T>: тип возвращаемого значения функции.',
  },
  {
    id: 'ts-020',
    difficulty: 'EASY',
    order: 20,
    tags: ['utility-types'],
    questionRu: 'В чём разница между Pick и Omit?',
    questionEn: 'В чём разница между Pick и Omit?',
    answerRu: "Pick<T, 'a' | 'b'> — создаёт тип только с перечисленными полями. Omit<T, 'a' | 'b'> — создаёт тип без перечисленных полей. Pick удобен когда нужно мало полей, Omit — когда нужно убрать 1–2 поля из большого типа.",
    answerEn: "Pick<T, 'a' | 'b'> — создаёт тип только с перечисленными полями. Omit<T, 'a' | 'b'> — создаёт тип без перечисленных полей. Pick удобен когда нужно мало полей, Omit — когда нужно убрать 1–2 поля из большого типа.",
  },
  {
    id: 'ts-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['utility-types'],
    questionRu: 'Что делает NonNullable?',
    questionEn: 'Что делает NonNullable?',
    answerRu: 'NonNullable<T> убирает null и undefined из типа: NonNullable<string | null | undefined> → string. Полезно когда получаешь тип из другого источника и знаешь, что значение гарантированно не null.',
    answerEn: 'NonNullable<T> убирает null и undefined из типа: NonNullable<string | null | undefined> → string. Полезно когда получаешь тип из другого источника и знаешь, что значение гарантированно не null.',
  },
  {
    id: 'ts-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['utility-types'],
    questionRu: 'Что такое Parameters и ReturnType?',
    questionEn: 'Что такое Parameters и ReturnType?',
    answerRu: 'Parameters<T> — tuple тип параметров функции T. ReturnType<T> — тип возвращаемого значения. Пример: type F = (a: string, b: number) => boolean; Parameters<F> → [string, number]; ReturnType<F> → boolean. Полезны для типизации обёрток над функциями.',
    answerEn: 'Parameters<T> — tuple тип параметров функции T. ReturnType<T> — тип возвращаемого значения. Пример: type F = (a: string, b: number) => boolean; Parameters<F> → [string, number]; ReturnType<F> → boolean. Полезны для типизации обёрток над функциями.',
  },
  {
    id: 'ts-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['utility-types'],
    questionRu: 'Что такое Awaited?',
    questionEn: 'Что такое Awaited?',
    answerRu: 'Awaited<T> рекурсивно разворачивает Promise: Awaited<Promise<string>> → string, Awaited<Promise<Promise<number>>> → number. Появился в TS 4.5. Используется вместо ручного ReturnType + Awaited для async функций.',
    answerEn: 'Awaited<T> рекурсивно разворачивает Promise: Awaited<Promise<string>> → string, Awaited<Promise<Promise<number>>> → number. Появился в TS 4.5. Используется вместо ручного ReturnType + Awaited для async функций.',
  },
  {
    id: 'ts-024',
    difficulty: 'HARD',
    order: 24,
    tags: ['utility-types'],
    questionRu: 'Как создать свой utility type?',
    questionEn: 'Как создать свой utility type?',
    answerRu: 'Через mapped types и conditional types. Пример DeepPartial: type DeepPartial<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K] }. Пример Mutable (убрать readonly): type Mutable<T> = { -readonly [K in keyof T]: T[K] }.',
    answerEn: 'Через mapped types и conditional types. Пример DeepPartial: type DeepPartial<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K] }. Пример Mutable (убрать readonly): type Mutable<T> = { -readonly [K in keyof T]: T[K] }.',
  },
  {
    id: 'ts-025',
    difficulty: 'MEDIUM',
    order: 25,
    tags: ['narrowing'],
    questionRu: 'Что такое type narrowing?',
    questionEn: 'Что такое type narrowing?',
    answerRu: "Narrowing — сужение типа в определённой ветке кода на основе проверок. После if (typeof x === 'string') TS знает, что x — string. Работает с typeof, instanceof, in, сравнениями, truthiness check и type guards.",
    answerEn: "Narrowing — сужение типа в определённой ветке кода на основе проверок. После if (typeof x === 'string') TS знает, что x — string. Работает с typeof, instanceof, in, сравнениями, truthiness check и type guards.",
  },
  {
    id: 'ts-026',
    difficulty: 'MEDIUM',
    order: 26,
    tags: ['narrowing'],
    questionRu: 'Что такое type guard?',
    questionEn: 'Что такое type guard?',
    answerRu: "Type guard — функция с возвращаемым типом predicate (arg is Type), которая сужает тип аргумента: function isString(x: unknown): x is string { return typeof x === 'string' }. После вызова TS знает тип в ветке true.",
    answerEn: "Type guard — функция с возвращаемым типом predicate (arg is Type), которая сужает тип аргумента: function isString(x: unknown): x is string { return typeof x === 'string' }. После вызова TS знает тип в ветке true.",
  },
  {
    id: 'ts-027',
    difficulty: 'MEDIUM',
    order: 27,
    tags: ['narrowing'],
    questionRu: 'Что такое discriminated union?',
    questionEn: 'Что такое discriminated union?',
    answerRu: "Discriminated union — union тип с общим литеральным полем-дискриминатором: type Shape = { kind: 'circle', radius: number } | { kind: 'rect', width: number }. Switch по kind сужает тип в каждой ветке. TS проверяет исчерпанность через never.",
    answerEn: "Discriminated union — union тип с общим литеральным полем-дискриминатором: type Shape = { kind: 'circle', radius: number } | { kind: 'rect', width: number }. Switch по kind сужает тип в каждой ветке. TS проверяет исчерпанность через never.",
  },
  {
    id: 'ts-028',
    difficulty: 'HARD',
    order: 28,
    tags: ['narrowing'],
    questionRu: 'Что такое assertion functions?',
    questionEn: 'Что такое assertion functions?',
    answerRu: 'Assertion function — функция, которая бросает ошибку если условие не выполнено, и сужает тип: function assert(cond: unknown): asserts cond. После вызова TS считает cond truthy. Вариант: asserts x is string — после вызова x имеет тип string.',
    answerEn: 'Assertion function — функция, которая бросает ошибку если условие не выполнено, и сужает тип: function assert(cond: unknown): asserts cond. После вызова TS считает cond truthy. Вариант: asserts x is string — после вызова x имеет тип string.',
  },
  {
    id: 'ts-029',
    difficulty: 'HARD',
    order: 29,
    tags: ['narrowing'],
    questionRu: 'Как работает exhaustiveness check?',
    questionEn: 'Как работает exhaustiveness check?',
    answerRu: 'Проверка что все варианты union обработаны. В switch/if после всех кейсов присваиваем переменную типу never: const _exhaustive: never = shape. Если добавить новый вариант в union без обработки — TS выдаст ошибку компиляции.',
    answerEn: 'Проверка что все варианты union обработаны. В switch/if после всех кейсов присваиваем переменную типу never: const _exhaustive: never = shape. Если добавить новый вариант в union без обработки — TS выдаст ошибку компиляции.',
  },
  {
    id: 'ts-030',
    difficulty: 'HARD',
    order: 30,
    tags: ['advanced'],
    questionRu: 'Что такое template literal types?',
    questionEn: 'Что такое template literal types?',
    answerRu: "Template literal types строят строковые типы по шаблону: type EventName<T extends string> = `on${Capitalize<T>}`. Из 'click' | 'focus' получим 'onClick' | 'onFocus'. Полезны для типизации event-систем, CSS-свойств, API-путей.",
    answerEn: "Template literal types строят строковые типы по шаблону: type EventName<T extends string> = `on${Capitalize<T>}`. Из 'click' | 'focus' получим 'onClick' | 'onFocus'. Полезны для типизации event-систем, CSS-свойств, API-путей.",
  },
  {
    id: 'ts-031',
    difficulty: 'MEDIUM',
    order: 31,
    tags: ['advanced'],
    questionRu: 'Что такое declaration files (.d.ts)?',
    questionEn: 'Что такое declaration files (.d.ts)?',
    answerRu: ".d.ts файлы содержат только объявления типов без реализации. Используются для типизации JS-библиотек без TS-кода. Пакеты @types/* содержат такие файлы. Можно создать свой для JS-модуля: declare module 'lib' { export function fn(): void }.",
    answerEn: ".d.ts файлы содержат только объявления типов без реализации. Используются для типизации JS-библиотек без TS-кода. Пакеты @types/* содержат такие файлы. Можно создать свой для JS-модуля: declare module 'lib' { export function fn(): void }.",
  },
  {
    id: 'ts-032',
    difficulty: 'MEDIUM',
    order: 32,
    tags: ['advanced'],
    questionRu: 'Что такое satisfies оператор?',
    questionEn: 'Что такое satisfies оператор?',
    answerRu: 'satisfies (TS 4.9) проверяет что значение соответствует типу, но сохраняет более узкий тип: const config = { port: 3000 } satisfies Config — port остаётся типом 3000, не number. В отличие от as Config не теряет конкретность типа.',
    answerEn: 'satisfies (TS 4.9) проверяет что значение соответствует типу, но сохраняет более узкий тип: const config = { port: 3000 } satisfies Config — port остаётся типом 3000, не number. В отличие от as Config не теряет конкретность типа.',
  },
  {
    id: 'ts-033',
    difficulty: 'MEDIUM',
    order: 33,
    tags: ['advanced'],
    questionRu: 'Что такое type coercion через as и когда это опасно?',
    questionEn: 'Что такое type coercion через as и когда это опасно?',
    answerRu: 'Type assertion (as Type) говорит TS считать значение указанным типом без проверки. Опасно: можно сказать as string когда реально number — ошибка в runtime. Двойной assert (as unknown as T) — красный флаг. Безопаснее: type guard или unknown → narrowing.',
    answerEn: 'Type assertion (as Type) говорит TS считать значение указанным типом без проверки. Опасно: можно сказать as string когда реально number — ошибка в runtime. Двойной assert (as unknown as T) — красный флаг. Безопаснее: type guard или unknown → narrowing.',
  },
  {
    id: 'ts-034',
    difficulty: 'HARD',
    order: 34,
    tags: ['advanced'],
    questionRu: 'Как типизировать this в функциях?',
    questionEn: 'Как типизировать this в функциях?',
    answerRu: 'TS позволяет явно указать тип this первым параметром (удаляется при компиляции): function fn(this: HTMLElement, e: Event) {}. Полезно для методов, передаваемых как колбэки. noImplicitThis в tsconfig требует явного указания this.',
    answerEn: 'TS позволяет явно указать тип this первым параметром (удаляется при компиляции): function fn(this: HTMLElement, e: Event) {}. Полезно для методов, передаваемых как колбэки. noImplicitThis в tsconfig требует явного указания this.',
  },
  {
    id: 'ts-035',
    difficulty: 'MEDIUM',
    order: 35,
    tags: ['advanced'],
    questionRu: 'Что такое strict mode в tsconfig и какие флаги включает?',
    questionEn: 'Что такое strict mode в tsconfig и какие флаги включает?',
    answerRu: 'strict: true включает группу флагов: noImplicitAny (запрет неявного any), strictNullChecks (null/undefined не совместимы с другими типами), strictFunctionTypes, strictBindCallApply, strictPropertyInitialization, noImplicitThis. Рекомендуется включать в новых проектах.',
    answerEn: 'strict: true включает группу флагов: noImplicitAny (запрет неявного any), strictNullChecks (null/undefined не совместимы с другими типами), strictFunctionTypes, strictBindCallApply, strictPropertyInitialization, noImplicitThis. Рекомендуется включать в новых проектах.',
  },
];
