import type { CardSeed } from './types';

export const cards: CardSeed[] = [
  {
    id: 'ts-001',
    difficulty: 'EASY',
    order: 1,
    tags: ['basics'],
    questionRu: 'Чем TypeScript отличается от JavaScript?',
    questionEn: 'How is TypeScript different from JavaScript?',
    answerRu: 'TypeScript — надмножество JavaScript со статической типизацией. Компилируется в JS. Преимущества: раннее обнаружение ошибок, автодополнение в IDE, самодокументируемый код. Все JS-программы валидны в TS, но не наоборот.',
    answerEn: 'TypeScript is a statically typed superset of JavaScript that compiles to JS. Benefits: early error detection, IDE autocompletion, self-documenting code. All JS programs are valid in TS, but not vice versa.',
  },
  {
    id: 'ts-002',
    difficulty: 'MEDIUM',
    order: 2,
    tags: ['basics'],
    questionRu: 'Что такое any, unknown и never — в чём разница?',
    questionEn: 'What are any, unknown, and never — what is the difference?',
    answerRu: 'any: отключает проверку типов, можно делать всё что угодно — антипаттерн. unknown: типобезопасная альтернатива any, перед использованием нужно сузить тип. never: тип для значений, которые никогда не возникнут (бесконечный цикл, всегда бросающая функция, exhaustive check).',
    answerEn: 'any: disables type checking, you can do anything with it — an antipattern. unknown: a type-safe alternative to any, you must narrow the type before using it. never: the type for values that can never occur (infinite loop, always-throwing function, exhaustive check).',
  },
  {
    id: 'ts-003',
    difficulty: 'EASY',
    order: 3,
    tags: ['basics'],
    questionRu: 'Что такое union и intersection типы?',
    questionEn: 'What are union and intersection types?',
    answerRu: 'Union (A | B): значение может быть типом A или B. Intersection (A & B): значение должно соответствовать и A, и B одновременно — объединяет свойства. Union — «или», intersection — «и».',
    answerEn: 'Union (A | B): a value can be either type A or type B. Intersection (A & B): a value must satisfy both A and B simultaneously — it merges their properties. Union means "or", intersection means "and".',
  },
  {
    id: 'ts-004',
    difficulty: 'MEDIUM',
    order: 4,
    tags: ['basics'],
    questionRu: 'Что такое literal types и const assertion?',
    questionEn: 'What are literal types and const assertion?',
    answerRu: "Literal types — тип конкретного значения: type Dir = 'left' | 'right'. const assertion (as const) говорит TS считать значение максимально узким типом: const dirs = ['left', 'right'] as const — тип становится readonly ['left', 'right'], а не string[].",
    answerEn: "Literal types represent a specific value as a type: type Dir = 'left' | 'right'. const assertion (as const) tells TS to infer the narrowest possible type: const dirs = ['left', 'right'] as const — the type becomes readonly ['left', 'right'] instead of string[].",
  },
  {
    id: 'ts-005',
    difficulty: 'EASY',
    order: 5,
    tags: ['basics'],
    questionRu: 'Что такое tuple в TypeScript?',
    questionEn: 'What is a tuple in TypeScript?',
    answerRu: 'Tuple — массив с фиксированным количеством элементов заданных типов: type Point = [number, number]. В отличие от массива, порядок и типы позиций фиксированы. Поддерживает rest и optional элементы: [string, ...number[]] или [string, number?].',
    answerEn: 'A tuple is an array with a fixed number of elements of specified types: type Point = [number, number]. Unlike a regular array, the order and types of each position are fixed. It supports rest and optional elements: [string, ...number[]] or [string, number?].',
  },
  {
    id: 'ts-006',
    difficulty: 'MEDIUM',
    order: 6,
    tags: ['basics'],
    questionRu: 'Что такое enum и какие у него альтернативы?',
    questionEn: 'What is an enum and what are its alternatives?',
    answerRu: "enum — перечисление именованных констант. Числовые enum генерируют JS-код (объект), const enum — стираются при компиляции. Проблемы enum: неожиданное поведение числовых enum, плохая совместимость. Альтернативы: union of literals ('a' | 'b') или as const объект.",
    answerEn: "An enum is a set of named constants. Numeric enums generate a JS object at runtime; const enums are erased during compilation. Problems with enums: unexpected behavior of numeric enums, poor compatibility. Alternatives: a union of literals ('a' | 'b') or an as const object.",
  },
  {
    id: 'ts-007',
    difficulty: 'MEDIUM',
    order: 7,
    tags: ['interfaces'],
    questionRu: 'В чём разница между interface и type?',
    questionEn: 'What is the difference between interface and type?',
    answerRu: 'interface: декларативное слияние (можно расширить в другом месте), extends для наследования, только объектные типы. type: любые типы (union, intersection, primitives, tuples), нет слияния. На практике: interface для публичных API и классов, type для всего остального.',
    answerEn: 'interface: supports declaration merging (can be extended elsewhere), uses extends for inheritance, only object types. type: supports any types (union, intersection, primitives, tuples), no merging. In practice: use interface for public APIs and classes, type for everything else.',
  },
  {
    id: 'ts-008',
    difficulty: 'MEDIUM',
    order: 8,
    tags: ['interfaces'],
    questionRu: 'Что такое декларативное слияние интерфейсов?',
    questionEn: 'What is interface declaration merging?',
    answerRu: 'Declaration merging — если объявить interface с одинаковым именем дважды, TS сливает их в один. Используется для расширения сторонних типов (например, добавить поля в Window или Express Request). type alias не поддерживает слияние.',
    answerEn: 'Declaration merging means that if you declare an interface with the same name twice, TS merges them into one. It is used to augment third-party types (e.g., adding fields to Window or Express Request). Type aliases do not support merging.',
  },
  {
    id: 'ts-009',
    difficulty: 'EASY',
    order: 9,
    tags: ['interfaces'],
    questionRu: 'Как сделать свойства опциональными или readonly?',
    questionEn: 'How do you make properties optional or readonly?',
    answerRu: 'Опциональное свойство: name?: string — может быть string или undefined. readonly: readonly id: number — нельзя переназначить после создания. Массив: ReadonlyArray<T> или readonly T[]. Utility types: Partial<T> делает все поля опциональными, Readonly<T> — все readonly.',
    answerEn: 'Optional property: name?: string — can be string or undefined. readonly: readonly id: number — cannot be reassigned after creation. For arrays: ReadonlyArray<T> or readonly T[]. Utility types: Partial<T> makes all fields optional, Readonly<T> makes all fields readonly.',
  },
  {
    id: 'ts-010',
    difficulty: 'MEDIUM',
    order: 10,
    tags: ['interfaces'],
    questionRu: 'Что такое index signature?',
    questionEn: 'What is an index signature?',
    answerRu: 'Index signature позволяет описать объект с динамическими ключами: { [key: string]: number }. Означает: любой строковый ключ возвращает number. Можно комбинировать с конкретными свойствами — они должны быть совместимы с типом значения индекса.',
    answerEn: 'An index signature describes an object with dynamic keys: { [key: string]: number }. It means: any string key returns a number. You can combine it with specific properties — they must be compatible with the index value type.',
  },
  {
    id: 'ts-011',
    difficulty: 'MEDIUM',
    order: 11,
    tags: ['interfaces'],
    questionRu: 'Как работает extends в интерфейсах и типах?',
    questionEn: 'How does extends work in interfaces and types?',
    answerRu: 'interface B extends A — B наследует все свойства A и может добавить свои. Нельзя переопределить тип свойства на несовместимый. type B = A & { extra: string } — intersection для типов. Интерфейс может extends несколько: interface C extends A, B.',
    answerEn: 'interface B extends A — B inherits all properties of A and can add its own. You cannot override a property with an incompatible type. type B = A & { extra: string } — use intersection for types. An interface can extend multiple: interface C extends A, B.',
  },
  {
    id: 'ts-012',
    difficulty: 'MEDIUM',
    order: 12,
    tags: ['interfaces'],
    questionRu: 'Что такое structural typing в TypeScript?',
    questionEn: 'What is structural typing in TypeScript?',
    answerRu: 'TS использует структурную типизацию (duck typing): тип совместим, если имеет нужную структуру, а не по имени. Объект { name: string, age: number } совместим с интерфейсом { name: string } — лишние поля разрешены. Исключение: object literals проверяются строже (excess property check).',
    answerEn: 'TS uses structural typing (duck typing): a type is compatible if it has the required structure, not by name. An object { name: string, age: number } is compatible with interface { name: string } — extra fields are allowed. Exception: object literals are checked more strictly (excess property check).',
  },
  {
    id: 'ts-013',
    difficulty: 'MEDIUM',
    order: 13,
    tags: ['generics'],
    questionRu: 'Что такое дженерики (generics) и зачем они нужны?',
    questionEn: 'What are generics and why are they useful?',
    answerRu: 'Дженерики — параметры типов, позволяющие писать переиспользуемый типобезопасный код. function identity<T>(arg: T): T — работает с любым типом, сохраняя информацию о нём. Без дженериков пришлось бы использовать any и терять типизацию.',
    answerEn: 'Generics are type parameters that allow you to write reusable, type-safe code. function identity<T>(arg: T): T — works with any type while preserving information about it. Without generics you would have to use any and lose type safety.',
  },
  {
    id: 'ts-014',
    difficulty: 'MEDIUM',
    order: 14,
    tags: ['generics'],
    questionRu: 'Как ограничить дженерик (generic constraints)?',
    questionEn: 'How do you constrain a generic (generic constraints)?',
    answerRu: 'extends ограничивает тип: function getLength<T extends { length: number }>(arg: T) — T должен иметь свойство length. Можно ограничить другим дженериком: function get<T, K extends keyof T>(obj: T, key: K): T[K].',
    answerEn: 'extends constrains the type: function getLength<T extends { length: number }>(arg: T) — T must have a length property. You can also constrain one generic with another: function get<T, K extends keyof T>(obj: T, key: K): T[K].',
  },
  {
    id: 'ts-015',
    difficulty: 'MEDIUM',
    order: 15,
    tags: ['generics'],
    questionRu: 'Что такое keyof и typeof в TypeScript?',
    questionEn: 'What are keyof and typeof in TypeScript?',
    answerRu: "keyof T — union тип из всех ключей T: keyof { a: 1, b: 2 } → 'a' | 'b'. typeof — получить тип значения на уровне типов: const config = {...}; type Config = typeof config. Вместе: keyof typeof obj — ключи объекта как union.",
    answerEn: "keyof T — a union type of all keys of T: keyof { a: 1, b: 2 } → 'a' | 'b'. typeof — gets the type of a value at the type level: const config = {...}; type Config = typeof config. Combined: keyof typeof obj — the keys of an object as a union.",
  },
  {
    id: 'ts-016',
    difficulty: 'HARD',
    order: 16,
    tags: ['generics'],
    questionRu: 'Что такое conditional types?',
    questionEn: 'What are conditional types?',
    answerRu: 'Условные типы: T extends U ? X : Y. Если T совместим с U — тип X, иначе Y. Пример: type IsString<T> = T extends string ? true : false. С infer можно извлекать типы: type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never.',
    answerEn: 'Conditional types: T extends U ? X : Y. If T is assignable to U — the type is X, otherwise Y. Example: type IsString<T> = T extends string ? true : false. With infer you can extract types: type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never.',
  },
  {
    id: 'ts-017',
    difficulty: 'HARD',
    order: 17,
    tags: ['generics'],
    questionRu: 'Что такое mapped types?',
    questionEn: 'What are mapped types?',
    answerRu: 'Mapped types создают новый тип, итерируясь по ключам другого: type Readonly<T> = { readonly [K in keyof T]: T[K] }. Можно модифицировать модификаторы (+/- readonly, +/- ?), менять тип значений, фильтровать ключи через as.',
    answerEn: 'Mapped types create a new type by iterating over the keys of another: type Readonly<T> = { readonly [K in keyof T]: T[K] }. You can modify modifiers (+/- readonly, +/- ?), transform value types, and filter keys using as.',
  },
  {
    id: 'ts-018',
    difficulty: 'HARD',
    order: 18,
    tags: ['generics'],
    questionRu: 'Что такое infer в TypeScript?',
    questionEn: 'What is infer in TypeScript?',
    answerRu: 'infer используется внутри conditional types для извлечения части типа: type UnpackArray<T> = T extends Array<infer Item> ? Item : T. Позволяет «захватить» тип в переменную. Встроенный пример: ReturnType<T> использует infer R для получения типа возвращаемого значения.',
    answerEn: 'infer is used inside conditional types to extract part of a type: type UnpackArray<T> = T extends Array<infer Item> ? Item : T. It lets you "capture" a type into a variable. Built-in example: ReturnType<T> uses infer R to obtain the return type of a function.',
  },
  {
    id: 'ts-019',
    difficulty: 'MEDIUM',
    order: 19,
    tags: ['utility-types'],
    questionRu: 'Какие встроенные utility types используются чаще всего?',
    questionEn: 'What are the most commonly used built-in utility types?',
    answerRu: 'Partial<T>: все поля опциональны. Required<T>: все поля обязательны. Readonly<T>: все поля readonly. Pick<T, K>: выбрать поля K из T. Omit<T, K>: убрать поля K из T. Record<K, V>: объект с ключами K и значениями V. ReturnType<T>: тип возвращаемого значения функции.',
    answerEn: 'Partial<T>: all fields optional. Required<T>: all fields required. Readonly<T>: all fields readonly. Pick<T, K>: select fields K from T. Omit<T, K>: remove fields K from T. Record<K, V>: object with keys K and values V. ReturnType<T>: the return type of a function.',
  },
  {
    id: 'ts-020',
    difficulty: 'EASY',
    order: 20,
    tags: ['utility-types'],
    questionRu: 'В чём разница между Pick и Omit?',
    questionEn: 'What is the difference between Pick and Omit?',
    answerRu: "Pick<T, 'a' | 'b'> — создаёт тип только с перечисленными полями. Omit<T, 'a' | 'b'> — создаёт тип без перечисленных полей. Pick удобен когда нужно мало полей, Omit — когда нужно убрать 1–2 поля из большого типа.",
    answerEn: "Pick<T, 'a' | 'b'> — creates a type with only the listed fields. Omit<T, 'a' | 'b'> — creates a type without the listed fields. Pick is convenient when you need just a few fields; Omit is better when you want to remove 1–2 fields from a large type.",
  },
  {
    id: 'ts-021',
    difficulty: 'EASY',
    order: 21,
    tags: ['utility-types'],
    questionRu: 'Что делает NonNullable?',
    questionEn: 'What does NonNullable do?',
    answerRu: 'NonNullable<T> убирает null и undefined из типа: NonNullable<string | null | undefined> → string. Полезно когда получаешь тип из другого источника и знаешь, что значение гарантированно не null.',
    answerEn: 'NonNullable<T> removes null and undefined from a type: NonNullable<string | null | undefined> → string. Useful when you receive a type from another source and know the value is guaranteed to be non-null.',
  },
  {
    id: 'ts-022',
    difficulty: 'MEDIUM',
    order: 22,
    tags: ['utility-types'],
    questionRu: 'Что такое Parameters и ReturnType?',
    questionEn: 'What are Parameters and ReturnType?',
    answerRu: 'Parameters<T> — tuple тип параметров функции T. ReturnType<T> — тип возвращаемого значения. Пример: type F = (a: string, b: number) => boolean; Parameters<F> → [string, number]; ReturnType<F> → boolean. Полезны для типизации обёрток над функциями.',
    answerEn: 'Parameters<T> — a tuple type of the parameters of function T. ReturnType<T> — the return type of the function. Example: type F = (a: string, b: number) => boolean; Parameters<F> → [string, number]; ReturnType<F> → boolean. Useful for typing wrappers around functions.',
  },
  {
    id: 'ts-023',
    difficulty: 'MEDIUM',
    order: 23,
    tags: ['utility-types'],
    questionRu: 'Что такое Awaited?',
    questionEn: 'What is Awaited?',
    answerRu: 'Awaited<T> рекурсивно разворачивает Promise: Awaited<Promise<string>> → string, Awaited<Promise<Promise<number>>> → number. Появился в TS 4.5. Используется вместо ручного ReturnType + Awaited для async функций.',
    answerEn: 'Awaited<T> recursively unwraps a Promise: Awaited<Promise<string>> → string, Awaited<Promise<Promise<number>>> → number. Introduced in TS 4.5. Used instead of manually combining ReturnType and Promise unwrapping for async functions.',
  },
  {
    id: 'ts-024',
    difficulty: 'HARD',
    order: 24,
    tags: ['utility-types'],
    questionRu: 'Как создать свой utility type?',
    questionEn: 'How do you create a custom utility type?',
    answerRu: 'Через mapped types и conditional types. Пример DeepPartial: type DeepPartial<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K] }. Пример Mutable (убрать readonly): type Mutable<T> = { -readonly [K in keyof T]: T[K] }.',
    answerEn: 'Using mapped types and conditional types. Example DeepPartial: type DeepPartial<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K] }. Example Mutable (remove readonly): type Mutable<T> = { -readonly [K in keyof T]: T[K] }.',
  },
  {
    id: 'ts-025',
    difficulty: 'MEDIUM',
    order: 25,
    tags: ['narrowing'],
    questionRu: 'Что такое type narrowing?',
    questionEn: 'What is type narrowing?',
    answerRu: "Narrowing — сужение типа в определённой ветке кода на основе проверок. После if (typeof x === 'string') TS знает, что x — string. Работает с typeof, instanceof, in, сравнениями, truthiness check и type guards.",
    answerEn: "Narrowing is the process of refining a type within a specific branch of code based on checks. After if (typeof x === 'string'), TS knows that x is a string. It works with typeof, instanceof, in, comparisons, truthiness checks, and type guards.",
  },
  {
    id: 'ts-026',
    difficulty: 'MEDIUM',
    order: 26,
    tags: ['narrowing'],
    questionRu: 'Что такое type guard?',
    questionEn: 'What is a type guard?',
    answerRu: "Type guard — функция с возвращаемым типом predicate (arg is Type), которая сужает тип аргумента: function isString(x: unknown): x is string { return typeof x === 'string' }. После вызова TS знает тип в ветке true.",
    answerEn: "A type guard is a function with a return type predicate (arg is Type) that narrows the type of its argument: function isString(x: unknown): x is string { return typeof x === 'string' }. After the call, TS knows the type in the true branch.",
  },
  {
    id: 'ts-027',
    difficulty: 'MEDIUM',
    order: 27,
    tags: ['narrowing'],
    questionRu: 'Что такое discriminated union?',
    questionEn: 'What is a discriminated union?',
    answerRu: "Discriminated union — union тип с общим литеральным полем-дискриминатором: type Shape = { kind: 'circle', radius: number } | { kind: 'rect', width: number }. Switch по kind сужает тип в каждой ветке. TS проверяет исчерпанность через never.",
    answerEn: "A discriminated union is a union type with a shared literal discriminant field: type Shape = { kind: 'circle', radius: number } | { kind: 'rect', width: number }. Switching on kind narrows the type in each branch. TS checks exhaustiveness via never.",
  },
  {
    id: 'ts-028',
    difficulty: 'HARD',
    order: 28,
    tags: ['narrowing'],
    questionRu: 'Что такое assertion functions?',
    questionEn: 'What are assertion functions?',
    answerRu: 'Assertion function — функция, которая бросает ошибку если условие не выполнено, и сужает тип: function assert(cond: unknown): asserts cond. После вызова TS считает cond truthy. Вариант: asserts x is string — после вызова x имеет тип string.',
    answerEn: 'An assertion function throws an error if a condition is not met and narrows the type: function assert(cond: unknown): asserts cond. After the call, TS treats cond as truthy. Variant: asserts x is string — after the call, x has type string.',
  },
  {
    id: 'ts-029',
    difficulty: 'HARD',
    order: 29,
    tags: ['narrowing'],
    questionRu: 'Как работает exhaustiveness check?',
    questionEn: 'How does exhaustiveness checking work?',
    answerRu: 'Проверка что все варианты union обработаны. В switch/if после всех кейсов присваиваем переменную типу never: const _exhaustive: never = shape. Если добавить новый вариант в union без обработки — TS выдаст ошибку компиляции.',
    answerEn: 'Exhaustiveness checking verifies that all variants of a union are handled. After all cases in a switch/if, assign the variable to never: const _exhaustive: never = shape. If you add a new variant to the union without handling it, TS will produce a compile-time error.',
  },
  {
    id: 'ts-030',
    difficulty: 'HARD',
    order: 30,
    tags: ['advanced'],
    questionRu: 'Что такое template literal types?',
    questionEn: 'What are template literal types?',
    answerRu: "Template literal types строят строковые типы по шаблону: type EventName<T extends string> = `on${Capitalize<T>}`. Из 'click' | 'focus' получим 'onClick' | 'onFocus'. Полезны для типизации event-систем, CSS-свойств, API-путей.",
    answerEn: "Template literal types build string types from a template: type EventName<T extends string> = `on${Capitalize<T>}`. From 'click' | 'focus' you get 'onClick' | 'onFocus'. Useful for typing event systems, CSS properties, and API paths.",
  },
  {
    id: 'ts-031',
    difficulty: 'MEDIUM',
    order: 31,
    tags: ['advanced'],
    questionRu: 'Что такое declaration files (.d.ts)?',
    questionEn: 'What are declaration files (.d.ts)?',
    answerRu: ".d.ts файлы содержат только объявления типов без реализации. Используются для типизации JS-библиотек без TS-кода. Пакеты @types/* содержат такие файлы. Можно создать свой для JS-модуля: declare module 'lib' { export function fn(): void }.",
    answerEn: ".d.ts files contain only type declarations without implementation. They are used to add types to JS libraries that don't have TS code. @types/* packages contain such files. You can create your own for a JS module: declare module 'lib' { export function fn(): void }.",
  },
  {
    id: 'ts-032',
    difficulty: 'MEDIUM',
    order: 32,
    tags: ['advanced'],
    questionRu: 'Что такое satisfies оператор?',
    questionEn: 'What is the satisfies operator?',
    answerRu: 'satisfies (TS 4.9) проверяет что значение соответствует типу, но сохраняет более узкий тип: const config = { port: 3000 } satisfies Config — port остаётся типом 3000, не number. В отличие от as Config не теряет конкретность типа.',
    answerEn: 'satisfies (TS 4.9) validates that a value matches a type while preserving a narrower inferred type: const config = { port: 3000 } satisfies Config — port remains type 3000, not number. Unlike as Config, it does not widen the type.',
  },
  {
    id: 'ts-033',
    difficulty: 'MEDIUM',
    order: 33,
    tags: ['advanced'],
    questionRu: 'Что такое type coercion через as и когда это опасно?',
    questionEn: 'What is type assertion with as and when is it dangerous?',
    answerRu: 'Type assertion (as Type) говорит TS считать значение указанным типом без проверки. Опасно: можно сказать as string когда реально number — ошибка в runtime. Двойной assert (as unknown as T) — красный флаг. Безопаснее: type guard или unknown → narrowing.',
    answerEn: 'Type assertion (as Type) tells TS to treat a value as the specified type without a runtime check. Dangerous: you can assert as string when the value is actually a number — causing a runtime error. A double assertion (as unknown as T) is a red flag. Safer alternatives: a type guard or unknown → narrowing.',
  },
  {
    id: 'ts-034',
    difficulty: 'HARD',
    order: 34,
    tags: ['advanced'],
    questionRu: 'Как типизировать this в функциях?',
    questionEn: 'How do you type this in functions?',
    answerRu: 'TS позволяет явно указать тип this первым параметром (удаляется при компиляции): function fn(this: HTMLElement, e: Event) {}. Полезно для методов, передаваемых как колбэки. noImplicitThis в tsconfig требует явного указания this.',
    answerEn: 'TS lets you explicitly annotate the type of this as the first parameter (it is erased at compile time): function fn(this: HTMLElement, e: Event) {}. Useful for methods passed as callbacks. noImplicitThis in tsconfig requires this to be explicitly typed.',
  },
  {
    id: 'ts-035',
    difficulty: 'MEDIUM',
    order: 35,
    tags: ['advanced'],
    questionRu: 'Что такое strict mode в tsconfig и какие флаги включает?',
    questionEn: 'What is strict mode in tsconfig and which flags does it enable?',
    answerRu: 'strict: true включает группу флагов: noImplicitAny (запрет неявного any), strictNullChecks (null/undefined не совместимы с другими типами), strictFunctionTypes, strictBindCallApply, strictPropertyInitialization, noImplicitThis. Рекомендуется включать в новых проектах.',
    answerEn: 'strict: true enables a group of flags: noImplicitAny (disallows implicit any), strictNullChecks (null/undefined are not assignable to other types), strictFunctionTypes, strictBindCallApply, strictPropertyInitialization, noImplicitThis. Recommended for all new projects.',
  },
];
